### ISSUE TITLE
can i some app use same gourpid and consumer all topic message

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-kafka#100]
if a have two app, them have same topic and the same group id.
can i set some properties to let app 1 to consume all message in topic and let app 2 also to consume all message in same topic?
thanks

**Comment by garyrussell** [comment]
No; they need different group ids - see the [kafka documentation](http://kafka.apache.org/090/documentation.html#newconsumerconfigs).

**Comment by dragontree101** [comment]
i see the doc, i want to confirme it , thanks!
