### ISSUE TITLE
JsonDeserializer constructor with TypeReference argument

### ISSUE THREAD

**Issue by pavelpe** [spring-projects/spring-kafka#1055]
Couldn't find any way to construct `JsonDeserializer` with `TypeReference` argument. 
The only way is `Class <T> targetType` but `ObjectMapper` instance (default) which is initialized inside deserializer has `readerFor(TypeReference<?> type)` for a long time already. 

Building custom `ObjectMapper` feels like workaround in such case.

Is there any specific reason why `JsonDeserializer` does not provide such constructor?

**Comment by artembilan** [comment]
I don't see how a custom `ObjectMapper` can be as a workaround, but this is a good request for the improvement.

We definitely can add a bunch of new constructors to apply `TypeReference`.

I see another way via `headers`:
```
ObjectReader deserReader = null;
if (this.typeMapper.getTypePrecedence().equals(TypePrecedence.TYPE_ID)) {
	JavaType javaType = this.typeMapper.toJavaType(headers);
	if (javaType != null) {
		deserReader = this.objectMapper.readerFor(javaType);
	}
}
```

But if there is no type info in the headers, there is no way to interact with the `TypeReference`...

Please, share your experience on the matter meanwhile we are introducing those new constructors.

Thanks

**Comment by pavelpe** [comment]
> I don't see how a custom `ObjectMapper` can be as a workaround, but this is a good request for the improvement.
>

Yes you are right, there is no way to pass `ObjectMapper` directly via ctors.
The idea (theoretically) was to pass custom `ObjectMapper` with custom `ObjectReader` into JsonDeser to be used at this stage:
```
if (this.reader == null) {
   this.reader = this.objectMapper.readerFor(this.targetType);
}
```
But eventually I haven't tried this approach so I didn't pay attention to `protected` access modifier at:
```
protected JsonDeserializer(ObjectMapper objectMapper)
```

 Thanks for provided example 
> I see anothekr way via `headers`:
> ```
> ObjectReader deserReader = null;
> if (this.typeMapper.getTypePrecedence().equals(TypePrecedence.TYPE_ID)) {
> 	JavaType javaType = this.typeMapper.toJavaType(headers);
> 	if (javaType != null) {
> 		deserReader = this.objectMapper.readerFor(javaType);
> 	}
> }
> ```
> But if there is no type info in the headers, there is no way to interact with the `TypeReference`...
>
but it is not an option in my case because `headers` are omitted on the send.

I was trying to implement _generic_ consumer (not aware of multiple consumed topics types). 
The simplest solution I came about was to init `targetType` to `Object`  class with `ConsumerRecord` type in `@KafkaListener` method. 
But when new ctors will be available, I would switch to TypeReference approach. It seems more elegant to me.

Thanks.

**Comment by artembilan** [comment]
I think all good now. We are going to release `2.3 M1`  this week or early next week.
