### ISSUE TITLE
@KafkaListener id SpEL expression is not being evaluated

### ISSUE THREAD

**Issue by JorgeLeonelMatos** [spring-projects/spring-kafka#1059]
**Affects Version(s):** 2.1.4.RELEASE

### Kafka Listener:
```
    @KafkaListener(
        id = "#{consumerContext.getCountry()}",
        containerFactory = KAFKA_LISTENER_FACTORY_BEAN_NAME,
        topics = "#{consumerContext.getTopics()}",
        groupId = "#{consumerContext.getGroupId()}",
        clientIdPrefix = "#{consumerContext.getClientId()}",
        errorHandler = VALIDATION_ERROR_HANDLER_BEAN_NAME
    )
```

### Consumer Context POJO (for testing purposes)
```
@Service
public class ConsumerContext {

    public String getCountry() {
        return "US";
    }

    public String[] getTopics() {
        return Arrays.asList("TOPIC-1,TOPIC-2".split(",")).stream().toArray(String[]::new);
    }

    public String getGroupId() {
        return getCountry() + ".consumer.group.id";
    }

    public String getClientId() {
        return getCountry() + ".consumer.client.id";
    }

}
```
And at the end:

- [ ] id = `"#{consumerContext.getCountry()}"` was evaluated at `#consumerContext.getCountry()}` (**ISSUE**)
- [x] topics = "#{consumerContext.getTopics()}" was evaluates at `"TOPIC-1,TOPIC-2"` (OK)
- [x] groupId = "#{consumerContext.getGroupId()}" was evaluates at `"US.consumer.group.id"` (OK)
- [x]  clientIdPrefix = "#{consumerContext.getTopics()}" was evaluates at `"US.consumer.client.id"` (OK)

However according documentation:

> public @interface KafkaListener {
> 
> 	/**
> 	 * The unique identifier of the container managing for this endpoint.
> 	 * <p>If none is specified an auto-generated one is provided.
> 	 * <p>Note: When provided, this value will override the group id property
> 	 * in the consumer factory configuration, unless {@link #idIsGroup()}
> 	 * is set to false.
> 	 * <p>SpEL {@code #{...}} and property place holders {@code ${...}} are supported.
> 	 * @return the {@code id} for the container managing for this endpoint.
> 	 * @see org.springframework.kafka.config.KafkaListenerEndpointRegistry#getListenerContainer(String)
> 	 */
> 	String id() default "";
> 

Do you guys have any clue how to make this works using spel on the id property of the `@KafkaListener`? Or this is a real issue?

My end goal is this approach is to have dynamic Kafka Listeners (https://stackoverflow.com/questions/55482708/spring-kafka-with-dynamic-kafkalistener)

**Comment by garyrussell** [comment]
@JorgeLeonelMatos This is a bug - however, since you are specifying `groupId` you don't really need an `id` attribute; if you omit it, the framework will generate a unique id.

`org.springframework.kafka.KafkaListenerEndpointContainer#0`

Starting with version 2.2.5, you can identify the container with `getGroupId()`.

**Comment by artembilan** [comment]
I wonder if we have to disable SpEL and PP for that `id`. It is really a static identificator for the some particular bean or its representation.
In fact an `id` for beans is never in Spring more than static value.

So, my point is to fix those JavaDocs instead.

**Comment by garyrussell** [comment]
I don't really see a problem with it being computed, especially for use cases like this. It's not a bean name; the listener object instance is registered as a bean, but this id is the listener container's id for the `RabbitListenerEndpointRegistry`; the container is not registered as a bean.

**Comment by JorgeLeonelMatos** [comment]
Since the `id` will be used as the identifier for `kafkaListenerEndpointRegistry.getListenerContainerIds()`  ... and based on my previous example, the threads name will be

`[org.springframework.kafka.KafkaListenerEndpointContainer#10-0-C-1]` ... and being able to search by consumerId is not possible ... using the SpEL naming strategy of course.

So, meanwhile ... do you have a solution to define the override kafka listener container id?

**Comment by garyrussell** [comment]
@JorgeLeonelMatos While SpEL is not currently working, you **can** use a property placeholder...

```java
@SpringBootApplication
public class Kgh1059Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh1059Application.class, args);
	}

	@Bean
	public ApplicationRunner runner(KafkaListenerEndpointRegistry registry, GenericApplicationContext context) {
		return args -> {
			Properties props = new Properties();
			PropertiesPropertySource source = new PropertiesPropertySource("dynamicListenerId", props);
			context.getEnvironment().getPropertySources().addLast(source);
			Foo foo1 = new Foo();
			props.setProperty("id.to.use", "id1");
			context.registerBean("bean1", Foo.class, () -> foo1);
			context.getBean("bean1");
			Foo foo2 = new Foo();
			props.setProperty("id.to.use", "id2");
			context.registerBean("bean2", Foo.class, () -> foo2);
			context.getBean("bean2");

			registry.getListenerContainerIds().forEach(System.out::println);
		};
	}

}

class Foo {

	@KafkaListener(id = "${id.to.use}", topics = "kgh1059")
	public void listen(String in) {
		System.out.println(in);
	}

}
```

**Comment by JorgeLeonelMatos** [comment]
thanks, @garyrussell for the workaround ;)

**Comment by dpk903** [comment]
Hi @garyrussell , It is not working again from 3.0.0.
Seems, trying to setId before adding listener in KafkaListenerAnnotationBeanPostProcessor.processKafkaListener(),
Getting " EL1008E: Property or field '__listener' cannot be found on object of type 'org.springframework.beans.factory.config.BeanExpressionContext' - maybe not public or not valid?"

 Its working fine with 2.9.4
 
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/27766501/209805436-b919b0c8-9347-4802-b0ae-9ea028dd316d.png">

**Comment by garyrussell** [comment]
Thanks - https://github.com/spring-projects/spring-kafka/issues/2521

**Comment by rishiraj88** [comment]
Thanks.
