### ISSUE TITLE
Null Headers - NPE

### ISSUE THREAD

**Issue by kirankumar-mahi** [spring-projects/spring-kafka#1066]
Hi There,

I am getting below error while consuming the message. I am using `StringDeserializer` while consuming the message.

```
Error while processing: ConsumerRecord(topic = SampleTopic , partition = 0, offset = 6289, CreateTime = 1555017745404, serialized key size = -1,  serialized value size = 21, headers = null, producer = console-producer, key = null, value = {"test": "testValue"})


java.lang.NullPointerException: null
        at org.springframework.kafka.support.DefaultKafkaHeaderMapper.toHeaders(DefaultKafkaHeaderMapper.java:240)
        at org.springframework.kafka.support.converter.MessagingMessageConverter.toMessage(MessagingMessageConverter.java:102)
        at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:217)
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:75)
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:51)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:989)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:969)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:910)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:783)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:652)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)

```

Below is the dependency used in project

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>2.0.9.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>2.0.8.RELEASE</version>
        </dependency>
```

**Comment by garyrussell** [comment]
Please use spring-kafka 2.1.x with Boot 2.0.x - you can [check the Boot POM](https://github.com/spring-projects/spring-boot/blob/2.0.x/spring-boot-project/spring-boot-dependencies/pom.xml) to find the proper version to use with boot - or, even easier, let boot manage the version for you.

If you still have a problem when using the proper version, please provide a sample message so we can see what the problem is.

**Comment by kirankumar-mahi** [comment]
Hi Gary, I am using apache kafka-client 1.1.1  version in our project.  Moving to  spring-kafka 2.1.x with Boot 2.0.x is giving some dependency errors. 

From kafka-client 1.1.1  console producer I am pushing the test message 
{"test": "testValue"}

The error at consumer side is

Error while processing: ConsumerRecord(topic = SampleTopic , partition = 0, offset = 6289, CreateTime = 1555017745404, serialized key size = -1, serialized value size = 21, headers = null, producer = console-producer, key = null, value = **{"test": "testValue"}**)

**Comment by garyrussell** [comment]
`...headers = null,...`

It appears you are using an old kafka-clients jar (less than 0.11).

`headers` is never null with 0.11 or later.

You really must use the versions the framework is tested with - it's best to just let spring-boot and spring-kafka pull in the right version transitively.

2.0.8 uses 0.11.0.2, 2.1.12 uses 1.0.2.

See [the project page](https://spring.io/projects/spring-kafka) for the compatibility matrix.

**Comment by kirankumar-mahi** [comment]
Hi Gary,

I am using below dependency from MapR Kafka clients 1.1.1.  Is there any way to suppress header checking.

   <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>1.1.1-mapr-1808</version>
        </dependency>

**Comment by garyrussell** [comment]
I have no idea what `1.1.1-mapr-1808` is? Have you tried with the official 1.1.1 version?

That said, your dependencies appear to be completely messed up Boot 2.0.x needs spring-kafka 2.1.x so I don't know how you can even get that far.

Show your complete POM.

**Comment by garyrussell** [comment]
I looked at the bytecode in that jar and it does indeed unconditionally populate the headers() field so you must have an older jar on the CP as well.

**Comment by garyrussell** [comment]
Perhaps you are trying to use the framework with mapr messages instead of proper Kafka messages, and it is creating header-less `ConsumerRecord`s.

That can certainly never happen with the standard client.

If that's the case, you can work around it by injecting a custom `MessagingMesageConverter` into the container factory and configure that converter with a custom `KafkaHeaderMapper` that is a no-op and never maps headers.

I will go ahead and add a null check, even though it can never happen with the real client.

**Comment by garyrussell** [comment]
But you should really complain to mapr because they are not honoring the clients' contract.

**Comment by garyrussell** [comment]
>MapR Streams is a cluster-based messaging system for streaming data at scale. It’s integrated into the MapR Data Platform and implements the Apache Kafka Java API so applications written for Kafka can also run on MapR Streams.

You should really complain to mapr because they are not honoring the clients' contract.

**Comment by kirankumar-mahi** [comment]
Thanks Gary for your inputs. I will surely take this up with MapR.

**Comment by garyrussell** [comment]
They must be explicitly setting it to `null`. Even if you use the minimal constructor that doesn't take a `Headers`, you still get an empty set...

```java
    public ConsumerRecord(String topic,
                          int partition,
                          long offset,
                          long timestamp,
                          TimestampType timestampType,
                          long checksum,
                          int serializedKeySize,
                          int serializedValueSize,
                          K key,
                          V value) {
        this(topic, partition, offset, timestamp, timestampType, checksum, serializedKeySize, serializedValueSize,
                key, value, new RecordHeaders());
    }
```

That's why we assumed we could never get a `null` there.

**Comment by kirankumar-mahi** [comment]
Hi Gary, By when this release will be available in maven ?. I would like to wait and consider this release.

**Comment by garyrussell** [comment]
Not for a month or so; but, in any case, we won't be fixing it in 2.0.x; it's no longer supported. I provided you with a work-around (customize the converter with a no-op header mapper).

**Comment by vishnu3** [comment]
I am facing the same issue. 
I created same custom headers as shown in this example 
https://memorynotfound.com/spring-kafka-adding-custom-header-kafka-message-example/
but after that kafka consumer started receiving list of numbers in header values. 
consumer is giving error as must be string or byte

**Comment by garyrussell** [comment]
Don't comment on old closed issues. If you are having a problem open a new issue showing actual code and a complete description of the error.

**Comment by garyrussell** [comment]
This seems unrelated. Don't comment on old closed issues. If you are having a problem open a new issue showing actual code and a complete description of the error.
