### ISSUE TITLE
Allow the invoker to stop in the middle of the batch

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-kafka#108]
Currently, the normal process of stopping the invoker (whether on shutdown or rebalance) is to wait until the entire batch is handled. As this can be a lengthy process, we can simply stop in the middle of processing the batch, with the sole exception of auto-commit scenarios, when this can result in acknowledging messages erroneously.

**Comment by mbogoevici** [comment]
Actually, there's a bit more to this, as we need to be careful about the way we purge in-flight data (which also applies to unprocessed messages of a batch). After rebalance, a consumer will start fetching where it left off from the partitions it retained, so if we dump data from a partition that was retained, it will not be fetched again in the same session (even if it hasn't been acknowledged)

I see two possible options here - either do a selective purge during `onPartitionsAssigned` (as this is the only moment when we know which partitions we retained), or reposition the consumer on partition reassignment to the last committed position, and allow the client to re-fetching the data we dumped.

**Comment by artembilan** [comment]
Fixed with https://github.com/spring-projects/spring-kafka/commit/67ffc2e331672d5cb4832fba8db5fc075c19aaa6
