### ISSUE TITLE
Why: Use LogAccessor for logging

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-kafka#1081]
I'm curious why this was merged https://github.com/spring-projects/spring-kafka/pull/1078
The reason I'm asking is that it looks that this approach creates a lot more objects, executes more code for no apparent benefit

**Comment by garyrussell** [comment]
When using `this.logger.debug(a + b + c)` we avoid the creation of the complex log message, when it would be discarded, by adding

```java
if (this.logger.isDebugEnabled()) {
    this.logger.debug(a + b + c);
}
```

This causes 2 checks on `isDebugEnabled()`, the explicit one as well as the one within the `debug()` methods; `is*Enabled()` is actually quite expensive when you do micro-benchmarking.

Using a `Supplier` reduces this overhead.

With modern JVMs the creation of these short-lived objects is not expensive at all and it makes the code quite a bit cleaner.

**Comment by igouss** [comment]
I understand that creating an object in TLH is just a bump pointer allocation. Hower it would still lead to more frequent young generation collections.

However would the logging framework not have to perform isDebugEnabled() check internally?

The expensive part is computing `a + b + c`, I think that maybe a better approach would be to use slf4j like logging library that can to log.debug("{}, {}, {}", a, b, c) that would computer the log string only if debug is enabled.

The real problem is when we do `log.debug("foo=" + computeFoo()) ` and in this cause I agree that the supplier of value that would execute only if debug is enabled would be a good optimization, but this is not what is done here.

**Comment by garyrussell** [comment]
>However would the logging framework not have to perform isDebugEnabled() check internally

Yes, but now it's only done once.

>but this is not what is done here

? This is exactly what's done here.

If you can provide concrete proof that this is detrimental in a real application, we can reconsider.

**Comment by igouss** [comment]
I think you are correct.
