### ISSUE TITLE
Configuring a Kafka Streams app using properties/yaml only

### ISSUE THREAD

**Issue by helpermethod** [spring-projects/spring-kafka#1106]
Hi,

thanks for the great work you're doing with Spring Kafka!

Quick question: Is it possible to configure a Kafka Streams application using Properties/Yaml only? E.g. is there some way to configure Default Key Serde, Schema Registry URL etc.?

Best regards,
Oliver

**Comment by artembilan** [comment]
I think you talk from the Spring Boot perspective and that one has this: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L657

Pay attention there is a general property: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L698

There you can provide a Streams property like this: `default.key.serde`. Or whatever is possible in the: https://kafka.apache.org/documentation/#streamsconfigs

Not sure though about `Schema Registry URL`. Doesn't look like this one is an out-of-the-box feature. You might need to have some code anyway to leverage that for (de)serialization.

**Comment by helpermethod** [comment]
Thank you very much, that solved all of my problems!
