### ISSUE TITLE
KafkaTestUtils uses EmbeddedKafkaRule, impossible to use with JUnit5

### ISSUE THREAD

**Issue by d35h** [spring-projects/spring-kafka#1109]
When I use ```@EmbeddedKafka``` with ```JUnit5``` and make use of the ```KafkaTestUtils```, I have gotten the following exception during ```./gradlew build``` command being executed:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.springframework.kafka.test.rule.EmbeddedKafkaRule, unresolved supertypes: org.junit.rules.ExternalResource, org.junit.rules.TestRule
    class org.springframework.kafka.test.rule.KafkaRule, unresolved supertypes: org.junit.rules.TestRule
> Task :compileTestKotlin FAILED

FAILURE: Build failed with an exception.
```

After the investigation I figured out where the problem is:
I was using ```KafkaTestUtils#consumerProps``` to create properties of the consumer, however, the file ```KafkaTestUtils``` uses indirectly ```org.springframework.kafka.test.rule.EmbeddedKafkaRule```, which is not supposed to be used together with ```JUnit5```.  

There are two methods: ```public static Map<String, Object> consumerProps(String group, String autoCommit, KafkaEmbedded embeddedKafka)``` and ```public static Map<String, Object> producerProps(KafkaEmbedded embeddedKafka)```, which both are marked as deprecated, and this two methods have ```EmbeddedKafkaRule``` as their argument, which is dependent on ```JUnit4``` resources and this is why it did not work without dependencies of ```JUnit4```

Would it be possible to have two separated utils files? One specifically for ```JUnit4``` and another one for ```JUnit5```?

My gradle file is:
```
  implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("org.simpleflatmapper:sfm-csv:$csvFormatter")
    implementation("com.amazonaws:aws-java-sdk:$awsJavaSdk")

    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude("junit", "junit")
    }
    testImplementation("cloud.localstack:localstack-utils:$localStackVersion")
    testImplementation("org.springframework.kafka:spring-kafka-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")
```

My test is:
```
@ExtendWith(value = [SpringExtension::class])
@SpringBootTest
@EmbeddedKafka
@DirtiesContext
@TestInstance(PER_CLASS)
@DisplayName("Kafka and S3 integration tests")
class KafkaSaverTestsGitHub {

    @Suppress("SpringJavaInjectionPointsAutowiringInspection")
    @Autowired
    lateinit var kafkaBroker: EmbeddedKafkaBroker

    @Test
    fun shouldNotBeNull() {
        assertThat(kafkaBroker).isNotNull
    }

    private fun getConsumerConfig(): HashMap<String, Any> {
        val configs = HashMap(KafkaTestUtils.consumerProps("consumer", "false", kafkaBroker))
        configs[ConsumerConfig.AUTO_OFFSET_RESET_CONFIG] = "earliest"
        return configs
    }
```

**Comment by d35h** [comment]
Thank you in advance!

**Comment by Woodham** [comment]
I was keeping an eye on the other issue and wondering why I wasn't seeing the same problem as you - I think I must have worked around it by adding this dependency:

```
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-migrationsupport</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
```
From here: https://github.com/junit-team/junit5/tree/master/junit-jupiter-migrationsupport

> This module provides support for JUnit 4 rules within JUnit Jupiter. Currently, this support is limited to subclasses of the org.junit.rules.Verifier and org.junit.rules.ExternalResource rules of JUnit 4, respectively.

While I agree ideally this should be changed in spring-kafka this should work around the issue in the meantime!

**Comment by d35h** [comment]
@Woodham thank you, your workaround is more elegant than the one I had

**Comment by artembilan** [comment]
Oh! That is really a good catch for that `KafkaTestUtils`.
We thought that `static` method with such a transitive dependency (I mean `KafkaEmbedded extends EmbeddedKafkaRule implements KafkaRule`) won't bring the `ClassNotFoundException` issue if it is not called explicitly.
But looks like such a lazy-load trick works only for classes. 
Since we have deprecated those `KafkaEmbedded`-based method in the previous version it doesn't sound too harmful to remove them in the current one.
Fortunately we have that `junit-jupiter-migrationsupport` (thanks @Woodham for the pointer!) workaround for the current version.

@garyrussell , WDYT?

**Comment by garyrussell** [comment]
I would say, yes, we can remove the deprecated classes and methods in 2.3.
