### ISSUE TITLE
Reset Embedded Kafka Broker After Each Test Method

### ISSUE THREAD

**Issue by limafoxtrottango** [spring-projects/spring-kafka#1114]
Currently, @EmbeddedKafka can be applied only on classes (@Target(ElementType.TYPE)). This gives us a global Kafka broker for that class than will be used by all the test methods. What if I want to use a different broker for each method? 

Use Case: Consider two methods and two Kafka topics, A and B. One method wants to simulate a publish error to topic A. The other method wants both topics A and B for testing. A good way to simulate a publish error would be to delete topic A. But we can't do that since B needs that topic.

I don't want to incrementally keep adding topics as I don't want to introduce any ordering in my unit tests. Also I don't want to put my methods in separate classes.

**Comment by garyrussell** [comment]
Don't ask the same question in multiple places; it's a waste of your time and ours.

In any case, GitHub issues are NOT for asking questions, which is explained in the issue template, which you probably did not read.

It's better to use different topics in each test. However, you can add `@DirtiesContext` to each test method or add `@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD` to the test class.

**Comment by limafoxtrottango** [comment]
I am sorry should have been more careful. Thanks a lot.

**Comment by lukasz-cpu** [comment]
maybe someone will be reading this post in the future, but 

@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)

doesn't work properly in that case
