### ISSUE TITLE
Add TopologyTestDriver support

### ISSUE THREAD

**Issue by CliffWheadon** [spring-projects/spring-kafka#1115]
**Affects Version(s):** 2.2.5.RELEASE

Currently, to test a Spring-Kafka that leverages kafka-streams you must use Embedded Kafka and a combination of Producers and Consumers to verify that you get the correct output given certain inputs. 

KafkaStreams actually provides a [TopologyTestDriver](https://kafka.apache.org/21/javadoc/org/apache/kafka/streams/TopologyTestDriver.html) that can be used to test the Topologies built via the StreamsBuiilder without the need to have an embedded kafka. 

It would be awesome if spring-kafka could make use of TopologyTestDriver to test topologies and sub-topologies within a kafka-streams app so that we don't need to worry about spinning up embedded kafka and making sure that the embedded kafka instances are isolated between tests.

**Comment by garyrussell** [comment]
? 

We already have tests that use the test driver

https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/streams/messaging/MessagingTransformerTests.java#L68

You just have to add the jars to the classpath (until 2.3 where we [add them automatically](https://github.com/garyrussell/spring-kafka/commit/fe2144295ead3d72a4dec842fd1572479dfa8e5c)).

Do you have something else in mind?

**Comment by CliffWheadon** [comment]
I think I was overcomplicating things when I was thinking about this, combined with being a bit ignorant. 

I'm using spring-boot as well, so I've got an `@SpringBootTest` annotation on what I have now. Since in the [reference](https://docs.spring.io/spring-kafka/reference/html/#kafka-streams), the DSL code is contained within an `@Bean` method that returns a KStream and takes a StreamsBuilder (which Spring handles creating for me) I wasn't sure how I'd actually get at a StreamsBuilder in the test to create a Topology and initialize the TopologyTestDriver. 

I should either be able to just create a new StreamsBuilder as noted in the example, and then call the method containing the streams DSL code, or get a StreamsBuilder from the `StreamsBuilderFactoryBean` instance that should be available and do the same.

Feel free to close this, and I appreciate the help 😄

**Comment by artembilan** [comment]
Closed as *Invalid*.

@CliffWheadon ,

No problem! At least we really have a solution for you and that's great it fits to your requirements. 😄
