### ISSUE TITLE
Commit offsets while consumer is paused

### ISSUE THREAD

**Issue by martindam** [spring-projects/spring-kafka#112]
The KafkaMessageListenerContainer currently does not commit offsets while it is in paused mode. See discussion here: https://github.com/spring-projects/spring-kafka/issues/84#issuecomment-219555741

**Comment by artembilan** [comment]
@martindam , hello!

Let us know if your tests are fine with the latest fix.
Our plans to release RC today.
So, any last-minute feedback is appreciate.

Thank you for all your contribution!

**Comment by martindam** [comment]
I tried it out all weekend with both producer and consumer on multiple instances, and I haven't found anything else. IMO you can release the RC

**Comment by garyrussell** [comment]
@martindam thanks for getting back to us
