### ISSUE TITLE
KafkaTestUtils.getSingleRecord() asserts on all records instead of the specified topic

### ISSUE THREAD

**Issue by MitchelNijdam-Rockstars** [spring-projects/spring-kafka#1121]
The Javadoc on `KafkaTestUtils.getSingleRecord(Consumer<K, V> consumer, String topic)` says:

> Poll the consumer, expecting a single record for the specified topic.

However it asserts for only one record in all topics the consumer is configured to poll for:

https://github.com/spring-projects/spring-kafka/blob/786c551a235e995069a2ce33be48c45a6f998ebc/spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java#L142-L146

In my test case, the consumer is configured to consume 2 topics, where I expect one message on each. Using this method fails because it received 2 messages in total, and asserts on that instead of filtering for the topic I specified.

I'm wondering if this is correct, or that the javadoc is just not clear enough for me.

**Comment by garyrussell** [comment]
Good point.

I think we can make some improvements - re-seek the records retrieved for other topics.
