### ISSUE TITLE
the groupId property for @KafkaListener is invalid

### ISSUE THREAD

**Issue by bpzhang** [spring-projects/spring-kafka#1131]
There is a problem for KafkaListener .
When I set a value to groupId and I want to consumer specified group id info,but it is invalid.
The code like 
`@KafkaListener(topics = "order-create-apply", groupId="order-group")`

**Comment by garyrussell** [comment]
Your issue is not clear; please explain in more detail, with an example.

Thanks.

**Comment by bpzhang** [comment]
Now I have two group in Kakfa. One name is order-group ,the other one is user-group.
and I have two Consumer consume the message.

There is **a topic** with the **same name** in the **two** groups, the topic name is **create-order**. Now I have specified a different group name in the annotation, but it still listen to all the names that are create-order when I consume, and will not distinguish between groups.

**Comment by garyrussell** [comment]
Sorry, it's still not clear what you mean.

Topics are not "in" groups. A consumer group simply represents a group of consumers and the group **consumes from one or more topics**.

All groups will get all messages from the subscribed topic(s); there is no way to select messages within a topic.

Perhaps some code or a diagram will help explain your problem?

**Comment by bpzhang** [comment]
Thank you for your reply, I understand what it meant, I confused the concept
