### ISSUE TITLE
KafkaListenerEndpointRegistry.stop(Runnable) does not call callback when there are no containers to stop

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-kafka#1134]
Boot's tests for its Kafka auto-configuration are taking 30 seconds each to run as we have a context with a `KafkaListenerEndpointRegistry` that has no `MessageListenerContainer`s. This causes it to fail to call the `callback` that's passed into `stop(Runnable)` so we have to wait for Framework's 30 second timeout to pop.

**Comment by artembilan** [comment]
Good catch, Andy!

Will fix soon...

**Comment by artembilan** [comment]
Do you need the fix until Spring Boot 1.5.x ?

**Comment by wilkinsona** [comment]
Boot 1.5 doesn't appear to be affected. For example, [this test](https://build.spring.io/browse/BOOT-PUB7-JOB1-1417/test/case/217332935) takes less than 1 second. That may be due to the tests being different in 1.5, I'm not sure.

**Comment by artembilan** [comment]
Yeah... I think so. We will back-port any way until the version which is pulled by Initializr (seems for me 1.3.x), because we haven't committed into `1.1.x` for a while already...

**Comment by garyrussell** [comment]
Yeah I found and fixed this in my experimental reactive `@KafkaListener` because in that environment, the MLC list was empty.

https://github.com/spring-projects/spring-kafka/pull/1123/files#diff-f23a91d9c56afd55946555b6ec1a150fR331

**Comment by wilkinsona** [comment]
Thanks, both. What's your schedule for the next Spring Kafka maintenance releases? I'd like to switch to snapshots if you have releases planned before the next round of Boot releases. We have 2.2 M5 scheduled for 24 July. Given the Framework releases planned for 17 July, we'll probably have 1.5 and 2.1 releases around then as well.

**Comment by wilkinsona** [comment]
I've figured out why we're only seeing the 30 second delay in Boot 2.2.

It is due to https://github.com/spring-projects/spring-kafka/issues/1102. In Boot 2.1 (Spring Kafka 2.2), `isRunning()` only returns `true` if one of the MLCs is running. As there are no MLCs in the affected tests, it returns `false`. As a result, `stop(Runnable)` is never called and the 30 second delay doesn't occur.

**Comment by garyrussell** [comment]
Thanks Andy, yes we'll have a new milestone (M4). I've scheduled it for July 23 (it's the day before Artem goes on extended PTO, so we may go a few days earlier - as long as SF stays where it is).

**Comment by garyrussell** [comment]
@wilkinsona Do you plan to change the version in s-b-dependencies? (I just hit the problem while testing a patch and I see the version is still M3). Working around it with a version override for now.

Thanks.

**Comment by wilkinsona** [comment]
Oops. Thanks for the reminder. I'd intended to move to snapshots and then got distracted by other things. I've just pushed the change: https://github.com/spring-projects/spring-boot/commit/b67fedd749f191367828a3111a17cc882d59dfb9.
