### ISSUE TITLE
Issues to run Spring-Kafka version 1.3.9 with Kafka client 0.10.2.2

### ISSUE THREAD

**Issue by mauriciobento** [spring-projects/spring-kafka#1136]
I have issues to run Spring-Kafka version 1.3.9 with Kafka client 0.10.2.2

The https://spring.io/projects/spring-kafka says that "All users with brokers >= 0.10.x.x (and all spring boot 1.5.x users) are recommended to use spring-kafka version 1.3.x or higher" I have setup in my pom.xml the Spring-Kafka version 1.3.9 and overriding the Kafka client from 0.11.x.x to 0.10.2.2

When I run the instance I have this error:

> Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/common/header/Headers at org.springframework.kafka.core.KafkaTemplate.(KafkaTemplate.java:74) ~[spring-kafka-1.3.9.RELEASE.jar:?]

The 0.11.x.x contains the package header. However, the version 0.10.2.2 doesn't. The brokers with version 0.10.x.x aren't compatible with spring-kafka version 1.3.9. And this is the opposite with what the spring-kafka website says. Please, correct me if I'm wrong.

My question is any problem to use the 0.11.xx version instead of 0.10.x.x right? I couldn't see the release notes between the two versions. Btw, my Kafka instance is running on 0.10.x.x version. Thanks

**Comment by garyrussell** [comment]
You should not downgrade the `kafka-clients`. The 0.11 clients can communicate with the 0.10.x.x broker.

See [the Confluent compatibility matrix](https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix).

I think the table on the project page is quite clear.

Spring for Apache Kafka Version | Spring Integration for Apache Kafka Version | kafka-clients
-- | -- | --
2.3.x | 3.2.x | 2.2.0
2.2.x | 3.1.x | 2.0.0, 2.1.0
2.1.x | 3.0.x | 1.0.x, 1.1.x, 2.0.0
1.3.x | 2.3.x | 0.11.0.x, 1.0.x

Let me know if we can make it clearerl

**Comment by mauriciobento** [comment]
My concerns were only that. I removed the 0.10 from my pom and let the spring-kafka to use the 0.11.x.x version. Since that I don't have issues to use the 0.11.x.x lib in a kafka broker 0.10 I'm fine. Thank you Russel

**Comment by garyrussell** [comment]
No problem. Note that while the 0.11 client will work with the 0.10 broker, you obviously can't use 0.11 broker features (such as headers).

0.10.x.x is very old. The current version is 2.2.1 (and 2.3.0 will be out soon). There have been lots of improvements over the years.

**Comment by mauriciobento** [comment]
Unfortunately, it doesn't depend on me. I wish to use the latest Kafka version always. We upgraded recently the brokers from 0.9 to 0.10 and have no idea when the company will use the last one. And I have no idea why they are using these old versions.
