### ISSUE TITLE
Support to accept more than one RecordInterceptors in AbstractKafkaListenerContainerFactory 

### ISSUE THREAD

**Issue by rajeshhereforyou** [spring-projects/spring-kafka#1142]
Hi,

As of now, we are using spring-kafka 2.2.7.RELEASE and using 'RecordInterceptor' interface and 'setRecordInterceptor(RecordInterceptor<K, V> recordInterceptor) to intercept one consumer record. 

But this method (setRecordInterceptor(RecordInterceptor<K, V> recordInterceptor) of 'AbstractKafkaListenerContainerFactory ' can accept only one RecordInterceptor and we are looking for a method which can take list of interceptors. 

Can we add a method/ modify the existing method to a list of interceptors?

**Comment by artembilan** [comment]
Why just don't have a `CompositeRecordInterceptor` and delegate to all your particular `RecordInterceptor` s ?
I mean there is just nothing to do in the Framework since you really can do that on your side.

Thanks for understanding

**Comment by rajeshhereforyou** [comment]
Let me explain our use-case. We have two different custom libraries. One is for tracing the request id, parent request id etc where we have created a custom RecordInterceptor by implementing RecordInterceptor interface and added our custom tracing logic in it and setting this custom RecordInterceptor while creating the 'ConcurrentKafkaListenerContainerFactory' bean 

The other library is purely for tracing health and performance metrics of an app. 

Since these are two separate concerns and two different libraries, we are looking for more than one CustomRecordInterceptors.

I believe i've explained the scenario in detail for your understanding. Please let me know if that helps.

**Comment by artembilan** [comment]
Right. So, what is wrong with the `CompositeRecordInterceptor`:
```
public class CompositeRecordInterceptor<K, V> implements RecordInterceptor<K, V> {
	
	private final Collection<RecordInterceptor<K, V>> delegates = new ArrayList<>();

	public CompositeRecordInterceptor(RecordInterceptor<K, V>... delegates) {
		this.delegates.addAll(Arrays.asList(delegates));
	}

	@Override
	public ConsumerRecord<K, V> intercept(ConsumerRecord<K, V> record) {
		ConsumerRecord<K, V> recordToIntercept = record;
		for (RecordInterceptor<K, V> delegate : delegates) {
			recordToIntercept = delegate.intercept(recordToIntercept);
		}
		return recordToIntercept;
	}

}
```
As you see I don't say anything about "CustomRecordInterceptor".

Hope that helps.

**Comment by garyrussell** [comment]
We will add the `CompositeRecordInterceptor` in 2.3; for 2.2.x you can use Artem's suggestion.

**Comment by rajeshhereforyou** [comment]
okay, will try. Thanks

**Comment by artembilan** [comment]
Reopen since Gary has issued a PR on the matter...
