### ISSUE TITLE
double acks when using acknowledgingMessageListener

### ISSUE THREAD

**Issue by dmachlin** [spring-projects/spring-kafka#117]
Hi,
It seems that in `KafkaMessageListenerContainer.java` acks are being added twice
First, when `this.acknowledgingMessageListener.onMessage(record, new ConsumerAcknowledgment(record))` is called and eventually `ListenerConsumer.this.acks.put(this.record);` is called in `ConsumerAcknowledgment.acknowledge()` and later after `onMessage` ends `this.acks.add(record);` is called.

```
private void invokeListener(final ConsumerRecords<K, V> records) {
			Iterator<ConsumerRecord<K, V>> iterator = records.iterator();
			while (iterator.hasNext() && (this.autoCommit || (this.invoker != null && this.invoker.active))) {
				final ConsumerRecord<K, V> record = iterator.next();
				if (this.logger.isTraceEnabled()) {
					this.logger.trace("Processing " + record);
				}
				try {
					if (this.acknowledgingMessageListener != null) {
						this.acknowledgingMessageListener.onMessage(record, new ConsumerAcknowledgment(record));
					}
					else {
						this.listener.onMessage(record);
					}
					this.acks.add(record);
					if (this.isManualImmediateAck || this.isRecordAck) {
						this.consumer.wakeup();
					}
				}
				catch (Exception e) {
					if (this.containerProperties.isAckOnError()) {
						this.acks.add(record);
					}
					if (this.containerProperties.getErrorHandler() != null) {
						this.containerProperties.getErrorHandler().handle(e, record);
					}
					else {
						this.logger.error("Listener threw an exception and no error handler for " + record, e);
					}
				}
			}
		}
```

**Comment by mbogoevici** [comment]
Hi, 

Thanks for reporting. This looks like a bug. We should only ack during handling if the mode is not manual.

**Comment by artembilan** [comment]
H-m. I wonder why it is a problem to commit the same offset twice or more time.
Why is that not idempotent?
The same problem we can see with several call to the `ConsumerAcknowledgment.acknowledge()`.
So, what we should do there then?

**Comment by mbogoevici** [comment]
The problem is not so much that we're calling it multiple times, but that the very idea of manual acks is to not acknowledge the message unless the user says so. My take here is that by putting the acks in indiscriminately, we're rendering the manual ack process ineffective.

**Comment by artembilan** [comment]
Got it!
So the code:
```
 else {
         this.listener.onMessage(record);
}
this.acks.add(record);
if (this.isManualImmediateAck || this.isRecordAck) {
```
should be improved with:
```
if (!this.isAnyManualAck) {
	this.acks.add(record);
}
```
?

**Comment by mbogoevici** [comment]
yes, and also on exception handling I believe

**Comment by artembilan** [comment]
By the way I don't see that we check that we provide `AcknowledgingMessageListener` if mode is `MANUAL`. 
Otherwise it looks like we don't acks them at all because there is nothing who takes care about `Acknowledgment`
One more bug or am I missing anything ?

**Comment by mbogoevici** [comment]
I think that's a bug - we definitely need to check for that.

**Comment by artembilan** [comment]
@dmachlin , that would be great to have your [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc) on the matter.
Just in time before this project goes GA! 

Thank you for catching that out anyway!
