### ISSUE TITLE
ReplyingKafkaTemplate supports message headers only from spring-kafka

### ISSUE THREAD

**Issue by mkamalov** [spring-projects/spring-kafka#1171]
Hi,

This is a short description of a problem:
I have my own service that cunsuming messages from kafka topic, make a calculation and send a result to output topic. The sevice uses output topic name from kafka header and supports correlationId for requests.
I can't configure ReplyingKafkaTemplate to support my service if I use my own header names for reply topic and correlation id. ReplyingKafkaTemplate is written to support message headers only from spring-kafka and there is no way to map spring-kafka headers to custom ones.

It means that I have to use Spring Kafka header names if I want my service is invoked via ReplyingKafkaTemplate. I can't use CORRELATION_ID instead of kafka_correlationId for message header if I want to support spring kafka integration. Do you have a plan to support custom headers mapper for Kafka Headers and support it in ReplyingKafkaTemplate?

Thanks, Marat.

**Affects Version(s):** \<Spring for Apache Kafka version>

**Comment by artembilan** [comment]
I don't understand what is the problem with built-in headers.
Let's look at this service!
```
@KafkaListener(id = A_REQUEST, topics = A_REQUEST)
@SendTo  // default REPLY_TOPIC header
public String handleA(String in) {
	return in.toUpperCase();
}
```
there is just no any headers you mention. Everything is hidden from you by the Framework.
The `KafkaHeaders.REPLY_TOPIC` and `KafkaHeaders.CORRELATION_ID` headers are picked up from the request message and stored internally until you return something for sending a reply.
On the producer side everything is transparent as well: you just use `ReplyingKafkaTemplate.sendAndReceive(ProducerRecord);`.

What is the point where one would need custom headers for such a correlation mechanism?

Please, elaborate more.

**Comment by mkamalov** [comment]
Hi Artem.

You are right if I use ReplyingKafkaTemplate with @SendTo, but what if my service doesn't have dependency to spring-kafka and it is written on native kafka API or it is written on python?

Thanks.

**Comment by artembilan** [comment]
Well, if you really can't modify a service according `ReplyingKafkaTemplate` contract, then I don't see any problems to let you to override a header name for reply topic, reply partition and correlation key.

Unfortunately this is going to involve much more, than just `ReplyingKafkaTemplate`. We rely exactly on these headers in many other framework components.
So, if you are going to change keys on request-reply side, you need to ensure that receive-reply side is configured respectively...

I see the point, but it is much involved, than it seems at a glance.

Let's wait for @garyrussell 's opinion on Monday!

**Comment by mkamalov** [comment]
Request-reply side is a common approach. It has correlation id, reply topic and optional partition number (i'm not sure about DLT headers). This data could be send via headers or if could be put to a message body if recive-reply side doesn't support kafka headers.
My point of view that maybe will be better to use some kind of abstraction to support request-reply design pattern. Hard coded header names work in most cases, but sometimes people want to create recieve-reply side based on message body or use other header names or use python. 
It sounds simple when we talk about reply topic, partition and correlation id, but could be tricky if we think about other parts of the solution. For example, DLT headers is not common for request-reply design pattern.

Sorry, I just want to share my use case with spring-kafka team. Please, think about it together :)

Now, I use spring-kafka header names, because I don't have any other option.

Thanks.

**Comment by artembilan** [comment]
Yeah... Sounds like we need plugable `CorrelationKeysStrategy`. As on request side, as well as on reply one...
Well, we will discuss this with Gary next week.

Thank you for sharing your experience!

**Comment by garyrussell** [comment]
We have something similar in Spring Integration with the outbound gateway having the option to use the standard `JMSCorrelationID` property or a custom `correlationKey` header name. In that case, the `JMSReplyTo` is not customizable though.
 
I agree that the best solution is some kind of strategy interface to set/get the correlation and set the replyTo.

**Comment by garyrussell** [comment]
@mkamalov After implementing this, I realized there is another solution you could use.

You can add a custom `ProducerInterceptor` on the producer side to "move" the headers to the ones you want.

Similarly you can add a `ConsumerInterceptor` on the reply consumer side to "move" the correlationId header back to where the template expects it.

Just a thought, in case you need an interim solution.

I am expecting to release 2.3.0.M4 on Monday.

**Comment by mkamalov** [comment]
@garyrussell Thanks, ProducerInterceptor/ConsumerInterceptor should work.

Thanks for you work. I will try it.
