### ISSUE TITLE
Asynchronous server-side processing in a request/reply scenario

### ISSUE THREAD

**Issue by dnitzan** [spring-projects/spring-kafka#1189]
Request/reply semantics requires that the server side listener method (annotated with `@SendTo`) return a response synchronously. There are use cases where server side request processing is asynchronous such that the listener method can't return a result immediately and must defer the response, releasing the consumer thread to handle other incoming requests. Once the result is available, an application thread would need to send it back to the client. This would be a feature similar to Servlet 3.0 Asynchronous Processing.

**Comment by garyrussell** [comment]
We already added this [for `@RabbitListener`](https://docs.spring.io/spring-amqp/docs/2.1.x/reference/html/#async-returns) last year.

However, managing the offsets for Kafka could make this tricky to implement - we wouldn't want to commit the offset until the async operation is complete.

If the next async operation completes first, and its offset committed, and then the first one fails, it's too late because its offset has already been implicitly committed.

Since Kafka message are not discretely acknowledged, going async with Kafka record consumption is really not recommended because of the risk of message loss and/or the complexity of managing offsets.

For this reason we didn't proceed here, but we can put it on the backlog and give it some more thought.

**Comment by dnitzan** [comment]
True, we faced the same issues building a custom request/reply mechanism on top of Spring Kafka. We eventually elected to just commit periodically (with `ack-mode=time`) regardless of downstream asynchronous processing and it is perfectly fine for us. If such a relaxed guarantee is sufficient, then it greatly simplifies the implementation.

**Comment by garyrussell** [comment]
OK; with that caveat; we'll try to get it into the next 2.3 milestone.

**Comment by dcheung2** [comment]
I think it is reasonable difficulty. But still may could be done even without a full prefect asynchronized flow.

for example.

when ackMode=BATCH
-> That container could async all the listeners within same BATCH but refer the ack until all messages in a poll() responsed

when ackMode=TIME
-> same as BATCH, but synchronize all once by time, not poll()

when ackMode=RECORD
-> No real concurrently processing. Just one message a time, but allow developers to use async API.

The real difficulty is timeout/retry management which make the state complex.

For another example, 
if the first message jammed,  the 2nd failed, but 3rd successes.  should it ack or retry from where ?
but this is a problem business logic to worry about. not the middleware
That spring-kafka should provide some configuration.

**Comment by garyrussell** [comment]
I have added support for out-of-order manual commits, which will now make implementing this possible.

**Comment by garyrussell** [comment]
Also support Kotlin Coroutines, discussed here https://github.com/spring-projects/spring-kafka/discussions/2653

**Comment by Wzy19930507** [comment]
Hi, @sobychacko @artembilan
may i pick it up.

**Comment by sobychacko** [comment]
@Wzy19930507 Certainly!

**Comment by artembilan** [comment]
I'm sorry. What is the plan for this issue?
Looks like Gary has added already enough functionality.
What else you see has to be fixed?

Thanks

**Comment by garyrussell** [comment]
>What else you see has to be fixed?

Add support for `Mono` and `Future` listener method return types in the MMLA, similar to what we have in RabbitMQ.

This is now possible when out of order commits are enabled.

**Comment by artembilan** [comment]
Cool!
Then it sounds like a copy/paste from the: https://github.com/spring-projects/spring-amqp/blob/main/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java#L375

**Comment by Wzy19930507** [comment]
- @KafkaListener @KafkaHandler support Async return, duplicate with  #2325
  - support Mono and CompletableFuture copy/paste from https://github.com/spring-projects/spring-amqp/issues/2374,
  - support Kotlin Continuation, copy/paste from https://github.com/spring-projects/spring-amqp/issues/1210
  - Invoke KafkaListenerErrorHandler, copy/paste from https://github.com/spring-projects/spring-amqp/issues/2461
  - add warn log if the container is not configured for MANUAL acks and isAsyncAcks, copy/paste from https://github.com/spring-projects/spring-amqp/commit/ae06325b9d212eeaa571148219fd075b1890a1ea
- skip fatal exceptions message and detect async return than coerce the out-of-order manual commit, copy/paste from https://github.com/spring-projects/spring-amqp/issues/1409

**Comment by PsyBrainy** [comment]
Hello @garyrussell, @Wzy19930507, @artembilan, and the Spring Kafka team,

I am following the development of asynchronous processing features for server-side request/response scenarios in KafkaListener, specifically those utilizing Kotlin's suspend functions. It's been enlightening to see the evolution of this feature through various discussions and commits.

As of the latest updates and the merging of related commits into the main branch, could you please provide an overview of the current state of this feature? Are there any additional configurations or considerations that we should be aware of when implementing this in our projects?

Thank you for your continuous efforts and contributions to enhancing Spring Kafka functionalities.

Best regards, psybrany
