### ISSUE TITLE
Wait some time before retrying 

### ISSUE THREAD

**Issue by sahmadov** [spring-projects/spring-kafka#1192]
First if all, sorry if this concern was raised before. I am creating issue as I couldn't find anything regarding that.

🎁 Enhancement
Problem:
While implementing retry logic most of the time people needs to wait some time before retrying.

Solution:
Maybe it makes sense to add one more parameter `SeekToCurrentErrorHandler ` which will define the milliseconds that spring should wait before retrying to consume. `WAIT_TIME_BEFORE_RETRY `

```
@Bean
public ConcurrentKafkaListenerContainerFactory kafkaListenerContainerFactory(
    ConcurrentKafkaListenerContainerFactoryConfigurer configurer,
    ConsumerFactory<Object, Object> kafkaConsumerFactory,
    KafkaTemplate<Object, Object> template) {
  ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
  configurer.configure(factory, kafkaConsumerFactory);
  factory.setErrorHandler(new SeekToCurrentErrorHandler(
      new DeadLetterPublishingRecoverer(template), 3, WAIT_TIME_BEFORE_RETRY));
  return factory;
}
```

**Comment by garyrussell** [comment]
This feature will be in the next version; there is [an open pull request here](https://github.com/spring-projects/spring-kafka/pull/1185).

**Comment by sahmadov** [comment]
cool. thanks.
