### ISSUE TITLE
spring-kafka and kafka-client 0.10

### ISSUE THREAD

**Issue by fouadh** [spring-projects/spring-kafka#120]
Hi,

Is there a plan to support the kafka-client 0.10 in the next release ? 

For the moment, I integrated it in my own fork but this would probably be cleaner in the original project.

Thanks !

**Comment by artembilan** [comment]
Hello @fouadh !

Yes, we definitely looking forward to fix the latest minor problems and release `1.0.0 GA` enough soon: the next week or so.
After that we will switch to `1.1` version and will pick `kafka-client 0.10` with their amazing KStreams support!

Anyway I wonder if there are some problems to still stay with `kafka-client 0.9`, but already use Kafka 0.10 as server. 
Or even better: haven't you tried to use Spring Kafka 1.0.0. RC1 but for `kafka-client` dependency to `0.10` already ?

**Comment by fouadh** [comment]
Hello @artembilan !

Thanks for the answer. 

Indeed, I tried to use kafka-client 0.10 dependency with spring-kafka 1.0.0.RC1 and unfortunately, it didn't work without modifying spring-kafka code. Fortunately, it was only cosmetic changes :-)

Here are a summary of the modifications (probably not in the Spring way :-p) I did in my fork:

The classes which have been updated:
* KafkaMessageListenerContainer
* KafkaMessageListenerContainerTests
* KafkaEmbedded

With more details:
* KafkaConsumer.seekToEnd(), KafkaConsumer.pause() and KafkaConsumer.resume() signatures have been modified
* CoreUtils.rm() removed, I used CoreUtils.delete() instead
* TestUtils.createBrokerConfig() signature changed: 2 options added
* AdminUtils.createTopic() signature changed: 1 option added
* BrokerEndPoint has been replaced by Node
* Some classes have been moved in different places (and some methods renamed) which change (a little bit) the way to loop over the topic metadata returned by AdminUtils$.MODULE$.fetchTopicMetadataFromZk() method

After that, I was able to use the generated library in a simple Producer/Consumer scenario. I didn't push my tests further before knowing your roadmap.

I will issue a pull request if you may be interested in. I mean I will try coz I never did it before ^^

**Comment by artembilan** [comment]
OK, @fouadh .

Thank you tackling that and for the contribution as well!

As I said before I'm afraid that `0.10` won't see life in Spring Kafka until the next `1.1` version. Enough soon though. So, we may consider your upgrade PR when we switch `master` to `1.1` version already.

Meanwhile it would be great if you confirm that you have singed [CLA](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc) (no rush, of course). 

And let us know if you definitely need to switch to `kafka-client-0.10` already right now. 
Doesn't `0.9` work with Kafka Broker 0.10, really?

**Comment by fouadh** [comment]
No no, 0.9 works well with broker 0.10...it is just that in my project, we are evaluating kafka-client 0.10.

And when we use it with spring-kafka, we get some NoSuchMethod exception at runtime due to the signature changes.

I wanted to sign the CLA but I don't see Spring Kafka in [the list of projects](https://support.springsource.com/spring_committer_signup): should I select spring integration or another one ?

Thanks in advance !

**Comment by artembilan** [comment]
OK. Thank you for your investigation. That sounds promising :smile: 

So, to confirm: we can still use Spring Kafka with Broker in version >= 0.9.
Since Spring Kafka isn't compatible with `kafka-client-0.10`, we don't have choice unless still stay with that one which is pulled transitively by Spring Kafka.

Yes, you can choose Spring Integration project for CLA and Gary Russell as a project lead.
But as we are discussing here, we will be able to utilize your PR only when we switch to `1.1`.

Cheers!

**Comment by arashiya** [comment]
Hi @fouadh, I am also evaluating 0.10 can u give me PR so that i can see changes?
