### ISSUE TITLE
@KafkaListener groupId property is not working

### ISSUE THREAD

**Issue by theanswer0815** [spring-projects/spring-kafka#1221]
```java
@KafkaListener(id="consumer1" ,idIsGroup = false, groupId="myGroup", 
topicPartitions ={@TopicPartition(topic="myTopic", partitions={"0"})})
@KafkaListener(id="consumer2", idIsGroup = false, groupId="myGroup" ,
topicPartitions ={@TopicPartition(topic="myTopic", partitions={"0"})})
```

I configured 2 consumers in one group,  i found consumer1 and consumer2 both reading the message. please tell me how could i get the message consumed just once in the group.
i found the  2 consumers have the same offset value in my console log, that confused me.
whether  using spring-boot 2.1.5.RELEASE or spring-boot 1.5.3.RELEASE & spring-kafka 1.3.10.RELEASE has the same problem.

**Comment by garyrussell** [comment]
GitHub issues are not for asking questions about why something is not working the way you expect; they are for reporting bugs and asking for new features.

When you manually assign topics and partitions with `@TopicPartition`, you are NOT using group management, you are explicitly  saying you want to receive all records in that partition.

use `topics = "myTopic"` instead and Kafka will allocate partitions to the instances.

**Comment by theanswer0815** [comment]
I'm sorry. i will use issues funciton  in right way. thank you very much

**Comment by artembilan** [comment]
This is just an Apache Kafka feature: when you assign partitions manually to your consumers, they are not involved in group management: https://kafka.apache.org/documentation/#intro_consumers
So, what you have with your configuration is expected behavior.
Therefore closing as *Works as Designed*.
