### ISSUE TITLE
Fix "Mapping Types" code snippet 

### ISSUE THREAD

**Issue by justinbaur** [spring-projects/spring-kafka#1226]
The return type of [mapping types](https://docs.spring.io/spring-kafka/docs/current/reference/html/#serdes-mapping-types) code snippet does not match method signature and JsonSerializer parameter type misspelled.

```
@Bean
public ProducererFactory<Foo, Bar> kafkaProducerFactory(KafkaProperties properties,
    JsonSserializer customSerializer) {

    return new DefaultKafkaConsumerFactory<>(properties.buildProducerProperties(),
        customSerializer, customSerializer);
}
```

**Comment by artembilan** [comment]
Contribution is welcome!

Please, open the Pull Request with an appropriate change and we will continue discussion over there.

Thank you for heads up!

**Comment by justinbaur** [comment]
I have the issue updated in my fork was just adding for transparency and linking to PR.  Thanks!
