### ISSUE TITLE
Consider providing some default values for `ackTime` and `ackCount`

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-kafka#124]
Currently they're both set to 0, which essentially renders the default behaviour of `TIME`, `COUNT`,`COUNT_TIME` and `MANUAL` identical to `BATCH` (and `MANUAL_IMMEDIATE_SYNC` in the case of `MANUAL`).

It would be better if we provided some defaults, or at the very least, we validated the values (e.g. COUNT requires a non-zero count value, etc).

**Comment by artembilan** [comment]
Any wisdom which *magic number* should we choose?

**Comment by mbogoevici** [comment]
For time, we could, in principle, use the default settings of autocommit - the default for `auto.commit.interval.ms` is 5s.

For count, I'm not sure - this is very dependent on the nature of the application. Maybe we should just validate that a positive number is set in that case.

**Comment by artembilan** [comment]
:+1: for both ideas.
We can reconsider in the future on demand.
