### ISSUE TITLE
no errors are reported when it is not possible to honor a @KafkaListener

### ISSUE THREAD

**Issue by ccronemberger** [spring-projects/spring-kafka#1252]
In my project I have the following ThreadPoolTaskExecutor:

    @Bean(name = "threadPoolExecutor")
    public ThreadPoolTaskExecutor getAsyncExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(2);
        executor.setMaxPoolSize(10);
        executor.setQueueCapacity(10);
        executor.setThreadNamePrefix("consumer-");
        executor.initialize();
        return executor;
    }

And in the application I have 3 methods annotated with @KafkaListener. When the application starts I can see on the Kafka server that only 2 listeners managed to start.
In this case I would expect an error to be reported.
By increasing the core pool size to 3 I managed to fix the issue. This is also strange because the max pool size is 10, so I think this is another problem.

**Comment by garyrussell** [comment]
The framework has no way to detect an improperly configured executor - each container is independent.

How do you expect it to work?

**Comment by ccronemberger** [comment]
It could have a timeout for example. Or at least log a warning message if it takes too long to start the listener.

    Em sexta-feira, 27 de setembro de 2019 11:45:09 BRT, Gary Russell <notifications@github.com> escreveu:  
 
 
The framework has no way to detect an improperly configured executor - each container is independent.

How do you expect it to work?
