### ISSUE TITLE
EmbeddedKafka does not support specifying zookeeper port

### ISSUE THREAD

**Issue by AhmadAbdelghany** [spring-projects/spring-kafka#1254]
Hi

I am trying to use the EmbeddedKafka to test my consumer application. The `@EmbeddedKafka` annotation starts kafka & zookeeper locally but only the embedded kafka is configurable. It would have been very handy if the zookeeper port it configurable through the annotation too.

The reason for that is that I have some libraries that read the `application.properties` and can't resolve placeholders like `spring.embedded.kafka.brokers`. So, making the port configurable would make life much easier for me.

Would you please consider adding it to the annotation and passing it along when you start embedded zookeeper? https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java#L216

Thanks

**Comment by garyrussell** [comment]
We can certainly do it, but why do you need it? There is no need to interact with ZK directly with modern Kafka clients.

**Comment by AhmadAbdelghany** [comment]
Unfortunately, I am using a proprietary client library that requires `kafka.zookeeper.servers` property to be set and fails otherwise.
