### ISSUE TITLE
Question: want to stop consuming messages upon fatal error

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-kafka#126]
Hello gentlemen,

I'd like to pause message consumption in case of fatal problem with processing.
Is this possible as of now?

In my case processing depends on a third-party service, so in case of a serious issue with it would be nice just to stop processing until further notice.

**Comment by garyrussell** [comment]
Yes, you can add a custom `ErrorHandler` and call `stop()` on the message listener container based on the exception.

**Comment by artembilan** [comment]
Hello, @stepio !

Let us know what you would like to hear else in this issue.
I find Gary's answer as good one and sufficient to close the ticket.

Thanks

**Comment by stepio** [comment]
Thanks for the quick reply, @garyrussell !

Hi, @artembilan , I haven't tried yet the proposed approach, but looks good - at least I know for sure that it's possible.
I haven't tried this yet, but at least I know exactly that it's possible.

As of now it's a bit unclear how to set this ErrorHandler. For example as of now I create a consumer factory using a code snippet below:
```java
    public ConcurrentKafkaListenerContainerFactory<String, T> listenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, T> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(new DefaultKafkaConsumerFactory<>(consumerConfigs()));
        factory.setConcurrency(kafkaConcurrency);
        factory.setRecordFilterStrategy(new SimpleDeDuplicationStrategy<>());
        return factory;
    }
```
And then I specify the constructed containerFactory for the appropriate KafkaListener annotation.

Certainly I can dig into your code and find the right place, but if you have anything to add, I'll appreciate your comments.

**Comment by stepio** [comment]
Most probably I should add something like this:
```java
        factory.getContainerProperties().setErrorHandler(new StoppingErrorHandler());
```

**Comment by artembilan** [comment]
For your `@KafkaListener` case you should configure proper `AbstractKafkaListenerContainerFactory` `@Bean`:

```
@Bean
public KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<Integer, String>>
			kafkaAutoStartFalseListenerContainerFactory() {
	ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
			new ConcurrentKafkaListenerContainerFactory<>();
	ContainerProperties props = factory.getContainerProperties();
        ...
	props.setErrorHandler(...);
        ...
	return factory;
}
```

because `ErrorHandler` now is a part of `ContainerProperties`

**Comment by artembilan** [comment]
Oops! You have figured out that already :smile:

**Comment by stepio** [comment]
Thanks anyway! 👍 Now I know for sure

**Comment by artembilan** [comment]
You are welcome!
Glad to see that issues have so simple solutions out-of-the-box. :wink:

**Comment by clauss13** [comment]
Hi guys,
I am running into a similiar issue and I cannot figure out how to "stop the container" in the custom ErrorHandler. Can you provide an example of what the "new StoppingErrorHandler()" would be
`new StoppingErrorHandler()` ?? 
I am using spring-kafka 1.1.1-Release
Any info would be most welcomed. 
thanks again for your work on this.

**Comment by artembilan** [comment]
The `AbstractMessageListenerContainer` implements `SmartLifecycle`, therefore you can inject  `AbstractMessageListenerContainer` bean into your custom `ErrorHandler` and call its `stop()` whenever you need.

**Comment by garyrussell** [comment]
Note that you should execute the `stop()` on another thread - e.g. 

`Executors.newSingleThreadExecutor().execute(() -> container.stop());` 

to avoid delaying the shutdown (stop will wait for the listener thread to return to the container); the default wait time is 10 seconds before stop() gives up.

**Comment by clauss13** [comment]
thank you both very much for your pointers.  sometimes u swirl around the solution and a nudge is necessary :)

@garyrussell I was thinking of decresing the shutdowntimeout but I'll go for yours.  

One more thing:  I am not storing the offsets and I am using ACK manual_imm. Thus to my understanding, the incomming message that triggers the pause/custom_handling is "lost" to the current consumer i.e. once stopped, after resuming & starting the container, it will not consume it again, but will process with the next incoming msg. Is my understanding correct??  
Is there any way of re-consuming this _last_message with the current (stopped & started) container ???
thanks again for your help

**Comment by garyrussell** [comment]
There is a boolean container property `ackOnError` (default true) which acks failed messages.

There's probably an argument for not defaulting this to true when using manual acks but currently it's true for all ack modes. 

Setting it to false should work for you.

**Comment by shashidarp** [comment]
We are trying to do similar handling but unable to inject AbstractMessageListenerContainer and stop the container. 

@stepio @artembilan @garyrussell 

Could you share StoppingErrorHandler() code ?.  

I am trying to inject the ConcurrentMessageListenerContainer created in the factory (  createContainerInstance(KafkaListenerEndpoint endpoint) ) into the ErrorHandler but a call to stop method on it is not causing the container threads to stops and we are seeing continuous  errors and finally OutOfMemory exception.

Thanks in advance for the help.

**Comment by artembilan** [comment]
If you are talking about `@KafkaListener(id ="foo")`, you have to take a look to its JavaDocs:
```
/**
	 * The unique identifier of the container managing for this endpoint.
	 * <p>If none is specified an auto-generated one is provided.
	 * @return the {@code id} for the container managing for this endpoint.
	 * @see org.springframework.kafka.config.KafkaListenerEndpointRegistry#getListenerContainer(String)
	 */
	String id() default "";
```
And, therefore, inject `KafkaListenerEndpointRegistry` to your `ErrorHandler`.
Select the proper container from there by desired `id`, cast it to the `Lifecycle` and call its `stop()`, like Gary suggest above https://github.com/spring-projects/spring-kafka/issues/126#issuecomment-259138893

**Comment by garyrussell** [comment]
You can also `stop()` the `KafkaListenerEndpointRegistry` bean and it will stop all the containers.

**Comment by shashidarp** [comment]
@artembilan @garyrussell Thanks for your input. Suggested approach works.

Posting the code for reference.

```
ErrorHandler

@Component
public class StoppingErrorHandler implements ErrorHandler {

  @Autowired
  private KafkaListenerEndpointRegistry kafkaListenerEndpointRegistry;
  
  @Override
  public void handle(Exception thrownException, ConsumerRecord<?, ?> record) {
    kafkaListenerEndpointRegistry.stop();
  }

}
```

```
Factory configuration.

@Autowired
  private StoppingErrorHandler stoppingErrorHandler;

  @Bean
  public KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<Integer, String>> kafkaListenerContainerFactory() {

    ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
        new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory());
    factory.setConcurrency(1);
    factory.getContainerProperties().setPollTimeout(1000);
    factory.getContainerProperties().setErrorHandler(stoppingErrorHandler);
    return factory;

  }

```

**Comment by hussein-joe** [comment]
@shashidarp Just for your info, if you are using batch processing of kafka listeners, this error handler might  not work.
You will need to do the following

```
factory.setBatchListener(true);
factory.getContainerProperties().setAckOnError(false);
factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.BATCH);
//factory.getContainerProperties().setErrorHandler(stoppingErrorHandler);
factory.getContainerProperties().setGenericErrorHandler(stoppingErrorHandler);
```
Where the stoppingErrorHandler is implemented this way

```
@Component
public class StoppingErrorHandler implements BatchErrorHandler {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(StoppingErrorHandler.class);
	@Autowired
	private KafkaListenerEndpointRegistry kafkaListenerEndpointRegistry;
	
	@Override
	public void handle(Exception thrownException, ConsumerRecords<?, ?> data) {
		LOGGER.error("Exception thrown while processing, going to stop");
		kafkaListenerEndpointRegistry.stop();
	}
}
```
@garyrussell  Could you please verify this approach?

**Comment by artembilan** [comment]
That's correct, @shashidarp .

There is a validation code:
```
			Assert.state(ok, "Error handler is not compatible with the message listener, expecting an instance of "
					+ (batch ? "BatchErrorHandler" : "ErrorHandler") + " not " + errHandler.getClass().getName());
```

So, when you have `AckMode.BATCH`, you definitely have to use an instance of `BatchErrorHandler`. 

And your configuration is correct as well. We have there this couple of methods:
```
/**
 * Set the error handler to call when the listener throws an exception.
 * @param errorHandler the error handler.
 * @see #setGenericErrorHandler(GenericErrorHandler)
 */
public void setErrorHandler(ErrorHandler errorHandler) {
	this.errorHandler = errorHandler;
}

/**
 * Set the error handler to call when the listener throws an exception.
 * @param errorHandler the error handler.
 */
public void setGenericErrorHandler(GenericErrorHandler<?> errorHandler) {
	this.errorHandler = errorHandler;
}
```
And, yeah, there is no specific option for the `BatchErrorHandler`.

I wonder if we could remove `setGenericErrorHandler()` altogether and change `setErrorHandler()` signature to the `GenericErrorHandler`. That would be legal in the current `2.0` version and will become useful option.

**Comment by artembilan** [comment]
@pkfka ,

Please, stop commenting on old closed issues.

Looks like you have some questions, so consider to represent them in the Community forums.
We don't provide personal support from here.
Only bug reports and feature requests are valid for this project here in GitHub.

Thank you for understanding.
