### ISSUE TITLE
Bug: Upgrade to v2.3.0.RELEASE throws nested exception at runtime

### ISSUE THREAD

**Issue by funkanalytics** [spring-projects/spring-kafka#1264]
**Affects Version(s):** \2.3.0.RELEASE
Upon upgrade to 2.3.0.RELEASE
runtime error:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.kafka.config.internalKafkaListenerAnnotationProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/log/LogAccessor

--Reverted back to 2.2.9.RELEASE, no issues
--tested previous version 2.2.8.RELEASE, no issues

**Comment by artembilan** [comment]
You have to use Spring Framework `5.2` which is a minimal requirements for this `spring-kafka-2.3.0.RELEASE`.

However it may sound like you use Spring Boot `2.1.x`, where Spring Kafka 2.3 is for Spring Boot `2.2`.
Consider to upgrade to that one. `RC1` has been released a couple days ago: https://spring.io/blog/2019/10/03/spring-boot-2-2-0-rc1-has-been-released

**Comment by artembilan** [comment]
Please, let us know how it is for you and we will close this with a *Works as Designed* resolution.

**Comment by garyrussell** [comment]
Boot 2.2 GA is currently scheduled for Oct 16.
