### ISSUE TITLE
Exception Bug in KafkaMessageListenerContainer.java

### ISSUE THREAD

**Issue by mlyard** [spring-projects/spring-kafka#1265]
The method doInvokeRecordListener in KafkaMessageListenerContainer.java "returns ee" [RuntimeException] when it should "throw ee" instead! 

The calling method return type for doInvokeRecordListener is void, thus when ee is returned its not caught.

The current broken catch is:
				catch (RuntimeException ee) {
					this.logger.error(ee, "Error handler threw an exception");
					return ee;   <--ISSUE--
				}

The proposed fix:
				catch (RuntimeException ee) {
					this.logger.error(ee, "Error handler threw an exception");
					throw ee;    <-- FIX--
				}

NOTE: All the other catches are throwing the exceptions except for this one, which might be an oversight!

The above might also apply to the method doInvokeBatchListener in the same class.

**Comment by garyrussell** [comment]
It's designed that way. 

This is an exception thrown by an error handler that handles an exception thrown by the listener.

When not using transactions, the exception is ignored.

When using transactions, the return value is thrown by the calling code so that the transaction rolls back.

	RuntimeException aborted = doInvokeRecordListener(record, producer, iterator);
	if (aborted != null) {
		throw aborted;
	}
