### ISSUE TITLE
key and value AssertJ conditions cannot be combined using allOf due to type errors

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-kafka#1299]
When trying to combine the `key` and `value` conditions as follows
```
assertThat(recordList).haveExactly(1, allOf(key(key2), value(message2)));
```
I get the a compile error due to the generic types used for each condition.

I've created my own `keyValue` condition that uses `allOf` with `ConsumerRecordKeyCondition` and `ConsumerRecordValueCondition` for now. But if would be useful if the Spring Kafka conditions could be combined (or a new condition added).

**Comment by garyrussell** [comment]
Thanks; contributions are welcome.
