### ISSUE TITLE
Expected release date?

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-kafka#130]
Is there an expected 1.0 release date? For some reason our Nexus will not mirror the libs-milestone maven repo, which makes it very difficult to test out this project. I'm trying to decide if I should just manually add the artifacts or wait it out a little while.

Thanks.

**Comment by garyrussell** [comment]
We were expecting to release this by now, but we're thinking of reworking the manual ack stuff; so that means we'll need to produce another release candidate and make the actual release a couple of weeks later; certainly before the end of July.

We don't publish milestones/candidates to maven central but you can add our milestone repo to your pom `https://repo.spring.io/milestone`.

**Comment by efenderbosch** [comment]
Unfortunately, adding the repo in my pom doesn't work since we have a private Nexus. It attempts to use Nexus for all dependency resolution and it fails even when adding the repo to Nexus as a proxy.

Thanks for the timeline update.

**Comment by efenderbosch** [comment]
Also, will kafka-client be upgraded to 0.10 for 1.0, or stay @ 0.9?

**Comment by garyrussell** [comment]
Unfortunately, there are some breaking API changes in the 0.10 client, so we are thinking of releasing 1.1 very soon after 1.0 (and support both).

**Comment by krishna81m** [comment]
Sorry, but I could not find spring-kafka in http://search.maven.org/#search%7Cga%7C1%7Cspring%20kafka.

Also, I see a JDK 8 dependency: java.lang.annotation.Repeatable, any reason why JDK 1.7 was already not supported.

**Comment by artembilan** [comment]
That's correct: we don't promote to Maven Central milestone release.
The latest one is RC1. We are going to release RC2 soon, maybe even tomorrow.
And RELEASE, with Maven Central, will be available over a week or so. 

Java has ability to [ignore](http://stackoverflow.com/questions/3567413/why-doesnt-a-missing-annotation-cause-a-classnotfoundexception-at-runtime) unknown (not in classpath) annotations, so we still support Java 7, although, right, we compile it against Java 8.

**Comment by krishna81m** [comment]
Thanks, until then, attaching poms if it helps anyone.

[pom.zip](https://github.com/spring-projects/spring-kafka/files/342972/pom.zip)

**Comment by artembilan** [comment]
Guys, we have released `1.0.0.RELEASE` today.
You can find it now in the Maven Central already: http://search.maven.org/#search%7Cga%7C1%7Cspring-kafka

**Comment by stepio** [comment]
Congratulations!!

**Comment by krishna81m** [comment]
Yay!, saved us some work ;)
