### ISSUE TITLE
SimpleKafkaHeaderMapper does not use default patterns

### ISSUE THREAD

**Issue by jdarc** [spring-projects/spring-kafka#1310]
**Affects Version(s):** \ 2.2.8 -> 2.3.3

The documentation for `SimpleKafkaHeaderMapper` default constructor specifies that default patterns are used, namely `!id`, `!timestamp` and `*`, however this does not seem to be the case. 

As you can see from the code snippet below from this repo, the call to `super()` in this constructor does not include these patterns.

```
public class SimpleKafkaHeaderMapper extends AbstractKafkaHeaderMapper {

	/**
	 * Construct an instance with the default object mapper and default header patterns
	 * for outbound headers; all inbound headers are mapped. The default pattern list is
	 * {@code "!id", "!timestamp" and "*"}. In addition, most of the headers in
	 * {@link KafkaHeaders} are never mapped as headers since they represent data in
	 * consumer/producer records.
	 */
	public SimpleKafkaHeaderMapper() {
		super();
	}
```

Comparatively, the `DefaultKafkaHeaderMapper` does include these patterns when calling `super();`

```
	/**
	 * Construct an instance with the provided object mapper and default header patterns
	 * for outbound headers; all inbound headers are mapped. The patterns are applied in
	 * order, stopping on the first match (positive or negative). Patterns are negated by
	 * preceding them with "!". The default pattern list is
	 * {@code "!id", "!timestamp" and "*"}. In addition, most of the headers in
	 * {@link KafkaHeaders} are never mapped as headers since they represent data in
	 * consumer/producer records.
	 * @param objectMapper the object mapper.
	 * @see org.springframework.util.PatternMatchUtils#simpleMatch(String, String)
	 */
	public DefaultKafkaHeaderMapper(ObjectMapper objectMapper) {
		this(objectMapper,
				"!" + MessageHeaders.ID,
				"!" + MessageHeaders.TIMESTAMP,
				"*");
	}
```

**Comment by artembilan** [comment]
Right, this is a bug.
And looks like we are missing some unit test on the matter.

You are very welcome with contribution!

Thank you!

**Comment by jdarc** [comment]
Hi Artem,

We've been looking at the issue with a view to provide a fix and noticed that the default pattern specified in the documentation, specifically "!id", "!timestamp" and "*" doesn't seem to apply for the SimpleKafkaHeaderMapper.

**Comment by artembilan** [comment]
Well, I would say the type and header name are not related. Even if it supports only `byte[]` and `String` it doesn't mean that I can't say those `ID` and `TIMESTAMP` headers as `String`.
Therefore filtering by pattern still applies.

Does it make sense ?

**Comment by jdarc** [comment]
Apologies, I didn't explain my intention clearly. What I am proposing is that the default header pattern simply be "*" when constructing a SimpleKafkaHeaderMapper with the parameterless constructor, e.g.

public SimpleKafkaHeaderMapper() {
	super("*");
}

The user is free to pass in any set of patterns they wish via the alternative constructor, namely:

public SimpleKafkaHeaderMapper(String... patterns) {
	super(patterns);
}

**Comment by artembilan** [comment]
Well, to be consistence we still need to disable `ID` and `TIMESTAMP`. Even if they are in most cases neither `byte[]` nor `String`, there is no guarantee that they are not going to be present in the target application with the expected type.

So, I still insist that we fix this `SimpleKafkaHeaderMapper` with an expected and consistent behavior:
```
public SimpleKafkaHeaderMapper() {
	this("!" + MessageHeaders.ID,
				"!" + MessageHeaders.TIMESTAMP,
				"*");
}
```

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-kafka/commit/5091fdc0ecad21dba3788bbea8000a8e3e1a2958
