### ISSUE TITLE
Kafka properties for multiple producers

### ISSUE THREAD

**Issue by emilnkrastev** [spring-projects/spring-kafka#1312]
Hi guys,

I have a project with multiple producers and I would like to have a way to provide Kafka properties for each one of them. For example: `spring.kafka.producers.<producer-name>.<property>`

Does it make sense to have such functionality?

Regards!

**Comment by garyrussell** [comment]
I assume you are talking about Spring boot auto configuration.

Such issues should be raised in that project.

**Comment by emilnkrastev** [comment]
Thanks for the fast reply!

Will do!

Closing this one.

**Comment by artembilan** [comment]
Well, it sounds like the question is more for Spring Boot project: this one definitely doesn't host configuration properties for Spring Boot auto-configuration.

Anyway, Spring Boot is more about a *convention on configuration* with strong opinion what and how auto-configure. If something goes out of standard, the goal cannot be achieved with just configuration properties.

Therefore the answer to your question is "No, it does not make sense to have such a functionality as out-of-the-box solution".

Of course, you can go ahead and build something on the matter in your project, but I doubt it is going to be so common that need to make it somehow into Spring Boot project.

Thanks for understanding.
