### ISSUE TITLE
Add validation function to aggregating template

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1319]
See #1318 

Deprecate `releaseStrategy` and replace with `Function<List<ConsumerRecord<K, V>>, List<ConsumerRecord<K, V>> validatorFunction;`.

Call the validator function each time a new record for the correlation id arrives and when the request times out. The function allows releasing (a possibly modifield) list at those times; returning `null` means don't release.

**Comment by trajano** [comment]
I'm not keen on the `null` part.  Can `Optional` semantics be used instead?

**Comment by garyrussell** [comment]
Yes, we could do that, or we could use `Predicate<List<ConsumerRecords<K, V>>>` and the predicate could manipulate the `List` argument directly, returning true when it's time to release the list.
