### ISSUE TITLE
Have (De)Serializer classes look for ObjectMappers in the application context before constructing its own objectMapper

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-kafka#1320]
> When providing the (De)Serializer class through Kafka properties, the Kafka client instantiates the object, not Spring. Kafka knows nothing about Spring or Boot.
> 
> The only way for Spring to do the instantiation is through a custom Producer/Consumer factory, taking the (De)Serializers as constructor arguments.

Why can't we have the constructor of the(De)Serializer class look for an ObjectMapper bean in the application context before constructing its own ObjectMapper?

_Originally posted by @jbotuck in https://github.com/spring-projects/spring-kafka/issues/680#issuecomment-557179220_

**Comment by artembilan** [comment]
See my comment over there https://github.com/spring-projects/spring-kafka/issues/680#issuecomment-557181132

**Comment by garyrussell** [comment]
>Why can't we have the constructor of the(De)Serializer class look for an ObjectMapper bean in the application context before constructing its own ObjectMapper?

Because, in most cases, Kafka constructs the deserializer and there is no reference to the application context.

**Comment by jbotuck** [comment]
Some reason I thought that even though kafka constructs the serializer, we can some how get a reference to the applicationContext in the constructor body by calling some magical static method Spring.getApplicationContext(). After further research looks like I was wrong.
