### ISSUE TITLE
Interceptor Improvement : BatchRecordInterceptor for Batch Record Consumers 

### ISSUE THREAD

**Issue by dharmeshjogadia** [spring-projects/spring-kafka#1322]
In `KafkaMessageListenerContainer`, we have interceptor for `ConsumerRecord<K,V>` as `RecordInterceptor<K,V>` but   `ConsumerRecords<K,V>` that's batch consumer records, there's no record interceptor available. 

It's good to have interceptors for batch consumers as well.
Let me know if there's any specific reason to don't have this feature for batch record consumers.

**Comment by garyrussell** [comment]
Kafka already provides `ConsumerInterceptor`. We added `RecordInterceptor` because users requested to have the ability to intercept individual records.

I don't see any value in adding another interceptor since Kafka already provides one.

**Comment by dharmeshjogadia** [comment]
Ohh yeah, `ConsumerInterceptor` will help here. Thanks @garyrussell
