### ISSUE TITLE
Spring Kafka : Producing too many repetitive logs when hitting org.apache.kafka.common.errors.GroupAuthorizationException

### ISSUE THREAD

**Issue by sothavirak** [spring-projects/spring-kafka#1331]
🎁 Enhancement
Below entry will swam the log files in no time after the application starts. This happen when a client is not authorized to access the topic with a particular consumer group. 

{"@timestamp":"2019-11-08T15:52:40.016+00:00","@version":1,"message":"Error while processing: null","logger_name":"org.springframework.kafka.listener.LoggingErrorHandler","thread_name":"org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1","level":"ERROR","level_value":40000,"stack_trace":"org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: consumer-group-a\n"}

**Comment by garyrussell** [comment]
Please show the full stack trace.

**Comment by garyrussell** [comment]
Never mind - Kafka suppresses the stack trace for all `ApiException`s

**Comment by sothavirak** [comment]
Hey @garyrussell any chance to backport this feature to 2.1.x version?

**Comment by garyrussell** [comment]
2.1.x is no longer supported since the end of October (a year after 2.2 was released); Boot 2.0 (which uses 2.1) went end of life in March.

I might make an exception if you can explain convincingly why you can't move to a supported version.

You can, of course, build it yourself from source.

**Comment by sothavirak** [comment]
Fair enough! Thanks again @garyrussell
