### ISSUE TITLE
Log spam for consumers without READ authorization

### ISSUE THREAD

**Issue by lukasz-kaminski** [spring-projects/spring-kafka#1334]
**Affects Version(s):** 2.3.5 and earlier

🐞 **Bug report**

Together with @anderseknert and @mdanielolsson we were playing around with Kafka authorization policies when we stumbled upon this bug.
If consumer is allowed to DESCRIBE, CREATE, WRITE but **not** READ, `KafkaConsumer::poll` will throw `TopicAuthorizationException`.  `KafkaMessageContainerListener` will just log it and continue polling, which causes a massive amount of logs to be produced.

Our solution is to pause the consumer for some time and then try again (see PR).

Use those repos to easily reproduce:
- [https://github.com/mdanielolsson/dockerized-kafka](https://github.com/mdanielolsson/dockerized-kafka)
- [https://github.com/lukasz-kaminski/spring-kafka-auth-tester](https://github.com/lukasz-kaminski/spring-kafka-auth-tester)

**Comment by garyrussell** [comment]
This is already fixed on master: https://github.com/spring-projects/spring-kafka/pull/1332

**Comment by lukasz-kaminski** [comment]
I've forked repo 4 days ago, so I missed this one. Closing the ticket then.

**Comment by anderseknert** [comment]
Having spent some time on the broker side of things implementing custom authorization models for Kafka, we experienced two show stoppers in our clients:

1. Logs getting flooded by unauthorized clients (~200 million log messages from a single one in a few hours!).
2. Clients unable to ever recover if unauthorized even once.

The fix recently merged seems to fix the first problem (which of course is great), but not the second one. I'll admit that my general Kafka-knowledge is limited so I'm not sure how errors are generally handled client side, but outside of the fairly static ACL model, authorization decisions could be based on any number of inputs and could vary over time without one unauthorized decision being too exceptional in nature, and certainly not fatal. 

While the description to this PR also seems to focus on the log flooding, the fix addresses also the second problem. Should we create a new issue/PR for that, or what would you advise us to do @garyrussell ?

**Comment by garyrussell** [comment]
@anderseknert I would entertain another PR if you wish to submit one.

I would name the property `authExeptionRetryInterval` and, if null (default), treat the condition as fatal and, if not null, add the sleep.

It should apply to all authorization exceptions not just `TopicAuthorizationException`.

The java docs should warn that it must be less than the `max.poll.interval.ms` consumer property.

We would also need an update to the what's new and kafka.adoc to mention the new property.

Thanks in advance for your contribution!

**Comment by anderseknert** [comment]
Sounds like a good way forward, thanks @garyrussell!
@lukasz-kaminski let's sync on who does what on this and then prepare a new issue and PR with the above points in mind. You can close this one again as the log flooding is indeed solved already.

**Comment by lukasz-kaminski** [comment]
Thanks @anderseknert and @garyrussell. I'm preparing the PR.

**Comment by anderseknert** [comment]
Sounds great @lukasz-kaminski 👍 I created https://github.com/spring-projects/spring-kafka/issues/1336 for that feature so we can keep track of it separately from the logging issue (which is solved already).
