### ISSUE TITLE
Allow denied authorization decisions to be retried

### ISSUE THREAD

**Issue by anderseknert** [spring-projects/spring-kafka#1336]
**Affects Version(s):** 2.3.5 and earlier

🎁 Enhancement
To allow for custom, more dynamic authorization models in Kafka, it would be great to have an option to allow the client to retry a failed authorization decision after some configured time has passed.

**Comment by lukasz-kaminski** [comment]
@garyrussell I applied all your comments from #1334

**Comment by lukasz-kaminski** [comment]
I've rebased the branch
