### ISSUE TITLE
how to close temple when programmer is stop?

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-kafka#134]
i use template to send message, but i don't find any way to close template.
i found test case, use template is `template.send()` and `template.flush`
if I use `kafkaProducer`, I will `kafkaProducer.close` and print log `Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.` but when use template I am not see any close message.

Would template will close kafkaProducer auto?

**Comment by stepio** [comment]
Hi @dragontree101 ,

To initialise `KafkaTemplate`, you have to specify `ProducerFactory`. And `DefaultKafkaProducerFactory` implements `DisposableBean`. So you may store the reference to your `DefaultKafkaProducerFactory` call `destroy()` when necessary:
```java
	@Override
	public void destroy() throws Exception { //NOSONAR
		CloseSafeProducer<K, V> producer = this.producer;
		this.producer = null;
		if (producer != null) {
			producer.delegate.close();
		}
	}
```
Or Spring will call it upon destroying the appropriate bean.

**Comment by stepio** [comment]
@artembilan 

Is there any benefit in using Spring's `DisposableBean` in comparison to `AutoClosable` from Java 7 ?
Tried "googling", but have not found a good answer.

**Comment by dragontree101** [comment]
thanks @stepio
before i have create DefaultKafkaProducerFactory this not as a bean 
after i add ```@Bean```  annotation i see the log print already

and seems if a bean implements ```Closeable``` interface, and spring will auto call ```close()``` method?

**Comment by dragontree101** [comment]
and i haven another question.
i want to use ```@Scheduled``` to ```flush()``` producer, but if a producer has not ```send()``` and it's ```producer``` is null, and throw ```NullPointerException```
so i am not flush template by ```@Scheduled```?

**Comment by stepio** [comment]
> and seems if a bean implements Closeable interface, and spring will auto call close() method?

Yes, Spring documentation states so:
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html
> To disable destroy method inference for a particular @Bean, specify an empty string as the value, e.g. @Bean(destroyMethod=""). Note that the DisposableBean and the Closeable/AutoCloseable interfaces will nevertheless get detected and the corresponding destroy/close method invoked.

**Comment by stepio** [comment]
> i want to use @Scheduled to flush() producer, but if a producer has not send() and it's producer is null, and throw NullPointerException
> so i am not flush template by @Scheduled?

I'm not sure that you need to do this. If you want to interact with Kafka synchronously, maybe you just need to specify `autoFlush` as `true` using the appropriate constructor?
```java
	/**
	 * Create an instance using the supplied producer factory and autoFlush setting.
	 * Set autoFlush to true if you wish to synchronously interact with Kafaka, calling
	 * {@link Future#get()} on the result.
	 * @param producerFactory the producer factory.
	 * @param autoFlush true to flush after each send.
	 */
	public KafkaTemplate(ProducerFactory<K, V> producerFactory, boolean autoFlush) {
		this.producerFactory = producerFactory;
		this.autoFlush = autoFlush;
	}
```

**Comment by stepio** [comment]
@artembilan 

> but if a producer has not send() and it's producer is null, and throw NullPointerException

Maybe null-check should be added there - to ignore calls to `flush` if lazy-loading `producer` is not initialised yet?

**Comment by dragontree101** [comment]
i not want to synchronously to send message, so i want to Scheduled to flush message , i think it will maybe raise perform by Schedule flush message rather than synchronously send message

**Comment by stepio** [comment]
In my case messages are delivered successfully without explicit flushing - so I recommend you also ignore flushing.

**Comment by dragontree101** [comment]
why producer not call ```flush``` method and message also will be send to kafka?

**Comment by stepio** [comment]
Javadocs to Kafka's `flush` say:
> Invoking this method makes all buffered records immediately available to send (even if <code>linger.ms</code> is greater than 0) and blocks on the completion of the requests associated with these records.

So scheduling of `flush` makes no sense - it's needed only if you need to commit the current batch immediately (like in case of synchronous sending). Regular "flushing" is handled by `KafkaProducer` itself - if you need to tune it, try updating properties `linger.ms` and `batch.size`.

**Comment by dragontree101** [comment]
thanks very much

**Comment by stepio** [comment]
> Maybe null-check should be added there - to ignore calls to flush if lazy-loading producer is not initialised yet?

Maybe not - exception helped to prevent invalid usage of the method.

**Comment by artembilan** [comment]
@dragontree101 , sorry for delay. That was long Independence Day weekend here in US.
But I'm sure @stepio 's help was useful for you.

Thank you very much, @stepio , for this kind of contribution as well.

Regarding `NPE`. Well, I think it is a bug and we should fix it as an `IllegalStateException` and let end-user to know that he/she must send a message to Kafka before flushing the producer.

That's it. 

Feel free to raise a PR on the matter to close this issue properly!

**Comment by stepio** [comment]
@artembilan 

Using `IllegalStateException` seems fair enough. As it's not a high priority task, I can do this myself - approximately within a couple of days.

**Comment by artembilan** [comment]
Well, actually it may be considered as a high priority.
@garyrussell has fixed today some nasty bug and commented there this way:
https://github.com/spring-projects/spring-kafka/issues/135#issuecomment-230486287. 

That's not a big deal to push the button for release, but he is on PTO and off-line now, so I need some time to discuss with him about his immediate release idea.

Thank you for considering PR.

(I guess I should stop saying that all the time to you, because you help so much that I only do that like tell "Thank you!" :smile: )

**Comment by garyrussell** [comment]
I am not so sure an `ISE` is necessary; we can simply ignore the `flush()` if there's no producer - but I don't mind either way.

**Comment by artembilan** [comment]
Well, just make `flush()` as void to swallow `NPE` isn't good anyway.
We have to tell end-user that his architecture rickety to use component that way in that state.

If it doesn't not make sense to call `flash` when we haven't made any sending, it should say about that.
That's why our typical `Assert.state(this.producer != null)` would be the best compromise.
