### ISSUE TITLE
Kafka offsets not commited

### ISSUE THREAD

**Issue by adamdec** [spring-projects/spring-kafka#135]
Hi, we were trying to use new spring-kafka 1.0.0.RELEASE 'RECORD' strategy for committing offsets with ConcurrentKafkaListenerContainerFactory configuration:
- concurrency=1
- pollTimeout=10 000

In our scenario we encountered strange situation when offsets were not commited by ListenerConsumer.

It happened that ListenerInvoker thread processed the Kafka messages so quickly that all he was doing was to wake up ListenerConsumer thread (which was blocked on poll() method) every 1sec. Please note that there was no other messages on Kafka topic to consume so ListenerConsumer  will be blocked on poll() invocation for the entire 10seconds.

We think that the problem is because pollTimeout (ListenerConsumer ) is greater then 1 sec (ListenerInvoker) and due to that we were able to produce a live-lock on ListenerConsumer.

Please comment.

**Comment by garyrussell** [comment]
It's a bug; looks like we don't properly handle RECORD mode in `processCommits` - the consumer is woken up from the poll but never commits. Will have a fix soon.

**Comment by adamdec** [comment]
What is the ETA? :)

**Comment by garyrussell** [comment]
Working on the patch now; we should be able to release 1.0.1 today.
