### ISSUE TITLE
Improve AckMode documentation

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#1353]
I am having trouble understanding AckMode.

When using a record listener I thought I could use AckMode.BATCH to commit offsets after every records from the poll where processed. And AckMode.RECORD to commit at each listener call.

But when using transaction I could not understand the documentation saying :
"Set the transaction manager to start a transaction; only AbstractMessageListenerContainer.AckMode.RECORD and AbstractMessageListenerContainer.AckMode.BATCH (default) are supported with transactions."
Since the offset should be sent with the record transaction not in a batch.

Gary Russell @garyrussell 17:18
We should make that clearer - RECORD is required for record listeners; BATCH (actually any non manual ack mode) will work with a Batch listener (where the listener gets the whole batch in a single transaction).

**Comment by garyrussell** [comment]
I think we should simply ignore the AckMode when using transactions since we have to send the offset(s) to the transaction in all cases depending on whether a record or batch listener is being used.

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-kafka/commit/705930c7e9bd2ebf5f9db63bfad2830c7274753b references the wrong issue in the headline.
