### ISSUE TITLE
AfterRollbackProcessor and default FixedBackOff

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#1354]
https://github.com/spring-projects/spring-kafka/blob/f4e9728a27f7ef4988d739765f1aa0a16f92a262/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java#L74

It seems like when using "-1" as maxFailure "new FixedBackOff()" is created which has 5 seconds of delay.
But when using a maxFailure != -1 "new FixedBackOff(0L, maxFailures == 0 ? 0 : maxFailures - 1);" is used which has 0 seconds of delay.

**Comment by garyrussell** [comment]
Please explain further; the folllowing logic handles the negative `maxAttempts` case:

https://github.com/spring-projects/spring-kafka/blob/f4e9728a27f7ef4988d739765f1aa0a16f92a262/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java#L75-L77

this sets the backOff's max attempts to `Long.MAX_VALUE`.

This test passes fine:

```java
public class FailedRecordProcessorTests {

	@Test
	void testInfiniteRetrys() {
		FailedRecordProcessor processor = new FailedRecordProcessor(null, -1) {
		};
		assertThat(KafkaTestUtils.getPropertyValue(processor, "failureTracker.backOff", FixedBackOff.class)
				.getMaxAttempts()).isEqualTo(Long.MAX_VALUE);
	}

}
```

**Comment by garyrussell** [comment]
Please explain further; the folllowing logic handles the negative `maxAttempts` case:

https://github.com/spring-projects/spring-kafka/blob/f4e9728a27f7ef4988d739765f1aa0a16f92a262/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java#L75-L77

this sets the backOff's max attempts to `Long.MAX_VALUE`.

This test passes fine:

```java
public class FailedRecordProcessorTests {

	@Test
	void testInfiniteRetrys() {
		FailedRecordProcessor processor = new FailedRecordProcessor(null, -1) {
		};
		assertThat(KafkaTestUtils.getPropertyValue(processor, "failureTracker.backOff", FixedBackOff.class)
				.getMaxAttempts()).isEqualTo(Long.MAX_VALUE);
	}

}
```

It was fixed here: https://github.com/spring-projects/spring-kafka/pull/1276 in 2.3.2 - what version are you using?

**Comment by Rajh** [comment]
Hi, I was talking about the delay, not the number of attempts.

`
public class FixedBackOff implements BackOff {
        /**
	 * The default recovery interval: 5000 ms = 5 seconds.
	 */
	public static final long DEFAULT_INTERVAL = 5000;
`

**Comment by garyrussell** [comment]
Oh; sorry.
