### ISSUE TITLE
Recoverer in AfterRollbackProcessor

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#1355]
Hi,

I would like to be able to recover messages in a BatchListener using Transaction and AfterRollBackProcessor.

Use case :
Having a process which is publishing to 2 differents topics (A, B).
If an error occures between A and B, we have to rollback to prevent A to be published.
Thus prevents us from catching and handling the error in the listener directly.

I would like to fallback into a single record listener to identify the message which is failing, rollback again and send it to a DLT.

To be able to do that, maybe the AfterRollbackProcessor from the BatchListener could recover the messages to another topic C which will be read by a single record listener.

**Comment by garyrussell** [comment]
I believe the "new" recovering batch error handler will satisfy your needs: https://docs.spring.io/spring-kafka/docs/2.5.4.RELEASE/reference/html/#recovering-batch-eh
