### ISSUE TITLE
Add the possibility of adding custom HandlerMethodArgumentResolver

### ISSUE THREAD

**Issue by filip-halemba** [spring-projects/spring-kafka#1361]
Currently you have to implement own `MessageHandlerMethodFactory`.

**Comment by garyrussell** [comment]
https://gitter.im/spring-projects/spring-kafka?at=5e26ff4a6b64bc54d1273719

**Comment by filip-halemba** [comment]
@garyrussell can you please take a look on change in my fork - I don't know if my conception is correct.

**Comment by filip-halemba** [comment]
I have opened https://github.com/spring-projects/spring-kafka/pull/1362
