### ISSUE TITLE
Support Micrometer metrics for Kafka Producers

### ISSUE THREAD

**Issue by sparty02** [spring-projects/spring-kafka#1366]
**Affects Version(s):** 2.4.x

🎁 Enhancement

Spring Kafka should support producer metrics, complementing the existing listener metrics implemented by PR #1242.  Some useful metrics (not necessarily exhaustive):

- successful send count
- failed send count
- timer for message send
- distribution timer for message send (min/max/median/mean/95%/etc) --- not sure what support micrometer has for this

**Comment by garyrussell** [comment]
>distribution timer for message send (min/max/median/mean/95%/etc) --- not sure what support micrometer has for this

Micrometer delegates such analysis to the reporting tools (Prometheus etc).
