### ISSUE TITLE
Spring kafka should handle some fatal exceptions like InvalidPidMappingException, UnknownProducerIdException.

### ISSUE THREAD

**Issue by bartosz-stasikowski-projectdrgn** [spring-projects/spring-kafka#1369]
**Affects Version(s):** 2.3.1.RELEASE

🎁 Enhancement
Spring kafka should handle some fatal exceptions like InvalidPidMappingException, UnknownProducerIdException.

Context: processing messages with transactions in non batch mode
Problem: Some exceptions like InvalidPidMappingException, UnknownProducerIdException are fatal and will cause KafkaMessageListenerContainer to fail every time polled record is processed

Usecase:
1. Records are polled
2. Transaction fails because of InvalidPidMappingException or UnknownProducerIdException when processing record
3. Rollback processing fails for InvalidPidMappingException or will send message to DLT for UnknownProducerIdException (if configured to do so)
4. Next poll will get another record which will have the same problem because exception is fatal 
 - in case of InvalidPidMappingException records will be processed after service is restarted or the is a rebalance
 - in case of UnknownProducerIdException records wont be processed again since offsets were commited in rollback processing

Currently InvalidPidMappingException exception can be handled in ErrorHandler but the only thing I can think of is to restart listener container.
For UnknownProducerIdException it is possible to not perform rollback processing and handle in the same way as InvalidPidMappingException in error handler.
This is strange and it should be handled by spring-kafka since it is a common problem when using transactions.

**Comment by garyrussell** [comment]
Please show some logs and stack traces - any failures related to transactions are considered fatal (`txFailed` contains the exception) from the producer perspective and the producer is closed...

https://github.com/spring-projects/spring-kafka/blob/909af16384e372e3699198c275db3827328a0bff/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L637-L660

and

https://github.com/spring-projects/spring-kafka/blob/909af16384e372e3699198c275db3827328a0bff/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L681-L689

**Comment by bartosz-stasikowski-projectdrgn** [comment]
Yes it works exactly as you want, but producer is not closed because its cache is null.

```
@Override
		public void close(@Nullable Duration timeout) {
			LOGGER.trace(() -> toString() + " close(" + (timeout == null ? "null" : timeout) + ")");
			if (this.cache != null) {
```

CloseSafeProducer is created in doCreateTxProducer() where cache is taken from ` this.cache.get(prefix)` which is null as this.cache is empty:

```
return new CloseSafeProducer<>(newProducer, this.cache.get(prefix), remover,
				(String) newProducerConfigs.get(ProducerConfig.TRANSACTIONAL_ID_CONFIG));
```
Should it be `getCache(prefix)` rather that `this.cache.get(prefix)`?


This is my InvalidPidMappingException stack:
```
org.apache.kafka.common.KafkaException: Cannot execute transactional method because we are in an error state
at org.apache.kafka.clients.producer.internals.TransactionManager.maybeFailWithError(TransactionManager.java:924)
at org.apache.kafka.clients.producer.internals.TransactionManager.beginTransaction(TransactionManager.java:290)
at org.apache.kafka.clients.producer.KafkaProducer.beginTransaction(KafkaProducer.java:642)
at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.beginTransaction(DefaultKafkaProducerFactory.java:597)
at org.springframework.kafka.core.ProducerFactoryUtils.getTransactionalResourceHolder(ProducerFactoryUtils.java:101)
at org.springframework.kafka.transaction.KafkaTransactionManager.doBegin(KafkaTransactionManager.java:160)
at com.projectdrgn.common.messaging.config.KafkaProducerConfig$kafkaTransactionManager$kafkaTransactionManager$1.doBegin(KafkaProducerConfig.kt:65)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.recordAfterRollback(KafkaMessageListenerContainer.java:1463)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListenerInTx(KafkaMessageListenerContainer.java:1438)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1398)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1165)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:949)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:884)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.
at org.apache.kafka.clients.producer.internals.TransactionManager$AddPartitionsToTxnHandler.handleResponse(TransactionManager.java:1204)
at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:1069)
at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:561)
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:553)
at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:307)
at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238)
... 1 common frames omitted
Caused by: org.apache.kafka.common.errors.InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id.

```

**Comment by garyrussell** [comment]
Yes, that looks like a bug - investigating.

**Comment by garyrussell** [comment]
Hmmm - no; the cache should have been previously populated by the previous call to `getCache()` here, before `doCreateTxProducer()` is called.

https://github.com/spring-projects/spring-kafka/blob/909af16384e372e3699198c275db3827328a0bff/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L463-L473

Can you show all your kafka-related configuration (and possibly a TRACE level log that shows this behavior)?

**Comment by bartosz-stasikowski-projectdrgn** [comment]
But doCreateTxProducer is called from createTransactionalProducerForPartition() in my case (suffix != null):

```
protected Producer<K, V> createTransactionalProducerForPartition(String txIdPrefix) {
		String suffix = TransactionSupport.getTransactionIdSuffix();
		if (suffix == null) {
			return createTransactionalProducer(txIdPrefix);
		}
		else {
			synchronized (this.consumerProducers) {
				if (!this.consumerProducers.containsKey(suffix)) {
					CloseSafeProducer<K, V> newProducer = doCreateTxProducer(txIdPrefix, suffix,
							this::removeConsumerProducer);
```

**Comment by garyrussell** [comment]
Oops - yes; got it.

**Comment by garyrussell** [comment]
I'd still like to see your configuration; I don't see how we can get there will `null`.

https://github.com/spring-projects/spring-kafka/blob/909af16384e372e3699198c275db3827328a0bff/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L373-L380

**Comment by bartosz-stasikowski-projectdrgn** [comment]
I am not sure if I understand: in my code txIdPrefix != null and this.producerPerConsumerPartition is true.

If by configuration you mean producer/consumer config then:

```
2020-01-29 18:28:47.346 INFO  17368 --- [rocessor-0-C-1] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = all
	batch.size = 16384
	bootstrap.servers = [localhost:9092]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = true
	interceptor.classes = [my.example.logging.MyProducerInterceptor]
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 1
	max.block.ms = 30000
	max.in.flight.requests.per.connection = 1
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = my-service-tx-my-messaging-processor.my.topic.0
	value.serializer = class my.example.converter.MySerializer
	
	
2020-01-29 18:28:45.109 INFO  17368 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = default
	client.id = my-messaging-processor-0
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = my-messaging-processor
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = [my.example.logging.MyConsumerInterceptor]
	internal.leave.group.on.close = true
	isolation.level = read_committed
	key.deserializer = class org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 100
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
```

**Comment by garyrussell** [comment]
Got it; sorry; now I see it.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
Just one more question: how closing producer will affect consumer when executing next poll() by KafkaMessageListenerContainer?
The problem here is that rollback processor will not seek back to previous offset since transaction will fail to start.

**Comment by garyrussell** [comment]
I am not sure what you mean; on the next poll we'll get a new Producer before starting the transaction. The failure shouldn't affect the seeks.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
Lets say that I am currently processing record with offset 1 and I get such not recoverable exception, producer will be closed and what will happen next?
Will I still need to seek back to reprocess the same record (in rollback processor which is using transactions too and currently is failing)?

**Comment by garyrussell** [comment]
There's no producer involved in the ARP, unless retries are exhausted and we "skip" (commit) the failed record offset after calling the recoverer (e.g. a `DeadLetterPublishingRecoverer`). In that case (with the fix) a new producer will be used.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
But when I am using transactions every ARP is done inside transaction, transaction is started every time ARP is done and producer is created (if needed) (even if I do not need to commit any offset - when I just want to seek back in afterRollbackProcessor) :

```
if (afterRollbackProcessorToUse.isProcessInTransaction() && this.transactionTemplate != null) {
	this.transactionTemplate.execute(new TransactionCallbackWithoutResult() {

		@Override
		protected void doInTransactionWithoutResult(TransactionStatus status) {
			afterRollbackProcessorToUse.process(unprocessed, ListenerConsumer.this.consumer, e, true);
		}

	});
}
			
```
But like you wrote fix should help and consumer should be created when starting ARP transaction.
Thanks.

**Comment by garyrussell** [comment]
You can disable running the ARP in a new transaction by setting `commitRecovered` to false:

```java
	/**
	 * {@inheritDoc}
	 * Set to true and the container will run the
	 * {@link #process(List, Consumer, Exception, boolean)} method in a transaction and,
	 * if a record is skipped and recovered, we will send its offset to the transaction.
	 * Requires a {@link KafkaTemplate}.
	 * @param commitRecovered true to process in a transaction.
	 * @since 2.3
	 * @see #isProcessInTransaction()
	 * @see #process(List, Consumer, Exception, boolean)
	 * @see #setKafkaTemplate(KafkaTemplate)
	 */
	@Override
	public void setCommitRecovered(boolean commitRecovered) { // NOSONAR enhanced javadoc
		super.setCommitRecovered(commitRecovered);
	}
```

However, that also disables committing the offset altogether, so there is a risk of redelivery if you restart the container before the next record in the partition is successfully processed. We should probably separate those behaviors.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
Yes, I am intentionally using isCommitRecovered = true.

Just one more question, regarding this fix and ProducerFencedException:
Lets assume scenario:
1. Processor's A producer is fenced (by Processor B) (for example because max.pool.interval.ms was exceeded) and transaction fails for some record
2. Processor's A ARP is creating new producer when starting transaction - when producer is created it executes initTransactions() - which fence other producers (am I right?)
3. Processor's B producer is fenced and transaction fails
4. Processor's B ARP is creating new producer when starting transaction - it fence back Processor's A producer

Will it work like that? I am just afraid there will be such loop for this exception.

**Comment by garyrussell** [comment]
Yes, I believe you are correct; good point.

I need to think about it some more, but we should probably skip the ARP after a PFE since we would have lost the partitions anyway.

**Comment by garyrussell** [comment]
I believe I have fixed this; working on some tests; PR to come soon.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
@garyrussell 
Is there any plan to release 2.3? 
I saw those changes are applied to this branch.

**Comment by garyrussell** [comment]
@bartosz-stasikowski-projectdrgn Next week - see https://github.com/spring-projects/spring-kafka/milestones for the planned release schedules.
