### ISSUE TITLE
On Partitions Assignment need of transaction-ability 

### ISSUE THREAD

**Issue by tomasAlabes** [spring-projects/spring-kafka#1370]
The origin of this issue is this [SO question](https://stackoverflow.com/questions/59958682/on-partitions-assignment-and-chainedkafkatransactionmanager-at-startup-with-jpa/59959119), @garyrussell suggested creating this issue to implement a couple of options regarding this case.

## Question

I have many transactional consumers with a `ChainedKafkaTransactionManager` based on a `JpaTransactionManager` and a `KafkaTransactionManager` (all `@KafkaListener`'s).

The JPA one needs a ThreadLocal variable to be set, to be able to know to which DB to connect to (is the tenant id).

When starting the application, in the `onPartitionsAssigned` [listener](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2223), spring-kafka is trying to create a chained txn, hence trying to create a JPA txn, but there's no tenant set, then it fails.

That tenant is set through a http filter and/or kafka interceptors (through event headers).

I tried using the auto-wired `KafkaListenerEndpointRegistry` with `setAutoStartup(false)`, but I see that the consumers don't receive any events, probably because they aren't initialized yet (I thought they were initialized on-demand).

If I set a mock tenant id and call `registry.start()` when the application is ready, the initializations seem to be done in other threads (probably because I'm using a `ConcurrentKafkaListenerContainerFactory`), so it doesn't work.

Is there a way to avoid the JPA transaction on that initial `onPartitionsAssigned` listener, that is part of the consumer initialization?

## Suggestion

> If your chained TM has the KafkaTM first, followed by JPA TM (which would be the normal case), you can achieve similar functionality by just injecting the Kafka TM into the container and using @Transactional (with just the JPA TM on the listener) to start the JPA transaction when the listener is called.
> The time between the transaction commits will be marginally increased but it would provide similar functionality.

In parallel, this issue is created to provide the option/s to either 

* disable the initial commit on assignment, 
* or do it without a transaction at all

Thanks @garyrussell!

**Comment by garyrussell** [comment]
@tomasAlabes After further review, this logic (committing initial offsets during assignment) was [added to protect a corner case](https://github.com/spring-projects/spring-kafka/issues/110) where a rebalance while a new consumer early in the life of the same group causes a rebalance and may cause messages, previously assigned to the current consumer(s), to be "lost" when `auto.offset.reset` is `latest`.

I will go ahead and add options to disable it but, in a future release, I think we should only ever apply this logic when using `latest`.

**Comment by tomasAlabes** [comment]
Got it. Will it be transactional though? Or at least have the "non-transactional" option? Because `auto.offset.reset` is `latest` for me now.

**Comment by garyrussell** [comment]
This is my plan:

```java
	/**
	 * Offset commit behavior during assignment.
	 * @since 2.3.6
	 */
	public enum AssignmentCommitOption {

		/**
		 * Always commit the current offset during partition assignment.
		 */
		ALWAYS,

		/**
		 * Never commit the current offset during partition assignment.
		 */
		NEVER,

		/**
		 * Commit the current offset during partition assignment when auto.offset.reset is
		 * 'latest'; transactional if so configured.
		 */
		LATEST_ONLY,

		/**
		 * Commit the current offset during partition assignment when auto.offset.reset is
		 * 'latest'; never in a transaction.
		 */
		LATEST_ONLY_NO_TX

	}
```

**Comment by tomasAlabes** [comment]
What are the consequences of not being in a transaction? Maybe clarifying pros/cons in the doc is useful too, to know which/why to pick.

**Comment by garyrussell** [comment]
I don't think it makes any material difference in practice since it's not a "real" transaction given that we don't actually produce any records during this operation (Kafka transactions are really only about producing records).

It was probably overkill to use a transaction here, but I thought it made sense to always commit offsets in a consistent manner rather than mixing setting offsets via the consumer here and producer when actually consuming records.

**Comment by rodion-fisenko** [comment]
Hi!
@garyrussell , could you say how the property `assignmentCommitOption` can be changed using yml/properties or java config? 
Unfortunately I have not found any description how to do it in the [documentation](https://docs.spring.io/spring-kafka/reference/html/).

**Comment by garyrussell** [comment]
If you want to set it for all listeners, do something like this:

```java
@Component
class Customizer {

	public Customizer(ConcurrentKafkaListenerContainerFactory<?, ?> factory, DefaultKafkaProducerFactory<?, ?> pf) {
		factory.getContainerProperties().setAssignmentCommitOption(AssignmentCommitOption.LATEST_ONLY);
	}

}
```


If you only want to set it for a specific listener:

```java
@Component
class Customizer {

	public Customizer(ConcurrentKafkaListenerContainerFactory<?, ?> factory, DefaultKafkaProducerFactory<?, ?> pf) {
		factory.setContainerCustomizer(container -> {
			if (container.getContainerProperties().getGroupId().equals("foo")) {
				container.getContainerProperties().setAssignmentCommitOption(AssignmentCommitOption.LATEST_ONLY);
			}
		});
	}

}
```

**Comment by rodion-fisenko** [comment]
Thank you for so quick response!

@garyrussell , could you say it it possible to customise the properties using the dependency `spring-cloud-stream-binder-kafka`? 

[As I see in the code](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/54ac274ea32997221c5ca3c6c4ae7605345047a1/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L651) just few value of the properties can be customised. Unfortunately approach you provided doesn't work for me in this case.

**Comment by garyrussell** [comment]
Well, you raised the question here against spring-kafka, not the kafka binder. How was I supposed to know you were using spring-cloud-stream?

There, you need to add ` ListenerContainerCustomizer` bean:

```java
@Bean
    public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
    return (container, dest, group) -> container.setAssignmentCommitOption(AssignmentCommitOption.LATEST_ONLY);
}
```

**Comment by rodion-fisenko** [comment]
Sorry for this misunderstanding. 
Your solutions works for me. Thank you so much :)
