### ISSUE TITLE
Typo fix in reference document

### ISSUE THREAD

**Issue by gogleowner** [spring-projects/spring-kafka#1374]
I'm sorry, but I'm very poor at English.

It's very very trivial. 
I found a typo in reference document.

![image](https://user-images.githubusercontent.com/5387870/73719696-8bbd6100-4763-11ea-9fb7-ab87f73dc33c.png)

![image](https://user-images.githubusercontent.com/5387870/73719675-75afa080-4763-11ea-84c1-fabb53d183f1.png)

I'll fix this and PR it.

Thank you.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/commit/5e16cf008dfafe496ab3d0fae5c29fda1d4afee4
