### ISSUE TITLE
Kafka Streams - Problem defining state store by using KafkaStreamsInfrastructureCustomizer

### ISSUE THREAD

**Issue by stijnvanbever** [spring-projects/spring-kafka#1386]
**Affects Version(s):** 2.4.1-RELEASE

Hello,

This is an issue created as continuation to remarks on this issue: https://github.com/spring-projects/spring-kafka/issues/1236#issuecomment-585962281

I'm using the new `KafkaStreamsInfrastructureCustomizer` to add a state store which would be used by a `Transformer` in a `KStream`. But this causes the application context to not load.

The exception thrown is (I cut off the top part): 
```
Caused by: org.apache.kafka.streams.errors.TopologyException: Invalid topology: StateStore testStateStore is not added yet.
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.connectProcessorAndStateStore(InternalTopologyBuilder.java:653)
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.connectProcessorAndStateStores(InternalTopologyBuilder.java:597)
	at org.apache.kafka.streams.kstream.internals.graph.StatefulProcessorNode.writeToTopology(StatefulProcessorNode.java:92)
	at org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder.buildAndOptimizeTopology(InternalStreamsBuilder.java:303)
	at org.apache.kafka.streams.StreamsBuilder.build(StreamsBuilder.java:558)
	at org.springframework.kafka.config.StreamsBuilderFactoryBean.start(StreamsBuilderFactoryBean.java:251)
	... 76 more
```
So while going through the debugger at `org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder#buildAndOptimizeTopology(java.util.Properties)` I noticed that the `StreamsSourceNode` was added before the `StateStoreNode` (due to the Customizer only being called while starting instead of at creation time).

This is because the streams was added first to the Topology and when that one tries to connect the processor to the state store, it cannot find it. (at: `org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder#buildAndOptimizeTopology(java.util.Properties)`).

Kafka documentation dictates that state stores should be added first before creating streams that will use them.

I believe that applying the `KafkaStreamsInfrastructureCustomizer` at creation time of the `StreamsBuilder` could solve the problem.

Code that reproduces the problem:
```
@Configuration
public class StateStoreProblem {
    @Bean
    public StreamsBuilderFactoryBeanCustomizer streamsBuilderFactoryBeanCustomizer() {
        return factoryBean -> factoryBean.setInfrastructureCustomizer(customizer());
    }

    private KafkaStreamsInfrastructureCustomizer customizer() {
        return new KafkaStreamsInfrastructureCustomizer() {
            @Override
            public void configureBuilder(StreamsBuilder builder) {
                StoreBuilder storeBuilder = Stores.keyValueStoreBuilder(
                        Stores.persistentKeyValueStore("testStateStore"),
                        Serdes.String(),
                        Serdes.String());
                builder.addStateStore(storeBuilder);
            }
        };
    }

    @Bean
    public KStream<String, String> testStream(StreamsBuilder kStreamBuilder) {
        KStream<String, String> stream =
                kStreamBuilder.stream("test_topic");

        stream
                .transform(() -> new Transformer<String, String, KeyValue<String, String>>() {
            @Override
            public void init(ProcessorContext context) { }

            @Override
            public KeyValue<String, String> transform(String key, String value) {
                return null;
            }

            @Override
            public void close() { }
        }, "testStateStore")
                .to("test_output");

        return stream;
    }
}
```

Thanks in advance for looking into this!

**Comment by artembilan** [comment]
@stijnvanbever,

Please, consider to provide a fix on the matter.
Sounds like you are fully on board with the feature and bug popped out from there.

Thank you!

**Comment by stijnvanbever** [comment]
@artembilan I'd be happy to. 
I have no experience in contributing to open-source projects, but I'll see what I can do.

**Comment by garyrussell** [comment]
I'll take care of it; I copied your test case and reproduced it.
