### ISSUE TITLE
Consider supporting non-transactional producer in a transactional template

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1388]
https://gitter.im/spring-projects/spring-kafka?at=5e4d41f26053e67dc4d13228

Currently, the template has this logic in doSend()
```java
		if (this.transactional) {
			Assert.state(inTransaction(),
					"No transaction is in process; "
						+ "possible solutions: run the template operation within the scope of a "
						+ "template.executeInTransaction() operation, start a transaction with @Transactional "
						+ "before invoking the template method, "
						+ "run in a transaction started by a listener container when consuming a record");
		}
```

Add an option to support using a non-transactional producer.

Options

- second non-transactional PF
- add `createNonTransactionalProducer` to PF

I think I prefer the second.

**Comment by artembilan** [comment]
Let's go with the second option! This way we are going to have an explicit contract to implement and no any confusions about several `ProducerFactory` beans.

**Comment by Rajh** [comment]
The DeadLetterPublishingRecoverer is forcing a new transaction.
Should it allow non-tx if the template is compatible ?

https://github.com/spring-projects/spring-kafka/blob/a7be6ac9f7d523982fde7ab7c7108cac1656b20a/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L152

**Comment by garyrussell** [comment]
Good catch; will make it optional there too.
