### ISSUE TITLE
ACKs being committed in MANUAL ackMode without acknowledge method being called

### ISSUE THREAD

**Issue by murphd40** [spring-projects/spring-kafka#141]
Hi Spring team,

I'm trying to commit received Kafka messages only when they have been processed fully.

Here's my configuration:
 * `autoCommit = false`
 * `ackMode = MANUAL`

I'm using the `KafkaMessageDrivenChannelAdapter` so messages are sent with the associated `Acknowledgment` in the message headers.

It is my understanding that the acknowledgements should only be committed when the I call the `acknowledge()` method for the `Acknowledgement` in the message headers; is that correct?

My issue at the moment is that the messages are being acknowledged even when I don't call `acknowledge()`. Is this an issue or have I misconfigured?

I'm using `2.0.0.RC1` from the milestone repo

**Comment by artembilan** [comment]
Probably you should try with the latest Spring Kafka `1.0.1`: https://spring.io/blog/2016/07/04/spring-for-apache-kafka-1-0-and-spring-integration-kafka-2-0-go-ga.

We have fixed recently commit process for `RECORD` ( #135 ) , but that may effect `MANUAL` as well.

**Comment by murphd40** [comment]
Thanks for the quick reply :smile: 

I'll try that and let you know if it fixes

**Comment by murphd40** [comment]
It still seems to be committing on its own.

I spent some time looking at the code. When `acknowledge()` is called, the record is added to the `acks` queue (see [here](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L842)).

But it seems that the record is added to this queue upon receipt of a message, even if a `acknowledgingMessageListener` is being used (see [here](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L602))

**Comment by artembilan** [comment]
OK. Thank you!

Consider as a bug :wink: 

Will be fixed soon, although let us know if you would like to provide some contribution on the matter: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by murphd40** [comment]
Thanks for the fix!

**Comment by garyrussell** [comment]
I think we need to release 1.0.2 ASAP for this bug.
