### ISSUE TITLE
ConcurrentMessageListenerContainer might throw java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-kafka#1414]
https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java#L95 this code might throw java.util.ConcurrentModificationException

```
2020-03-09 18:27:37,216 BatchLoggingErrorHandler ERROR --- Error while processing: 
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
	at com.xmatters.audit.cdc.ChunkingCdcMessageListener.managePause(ChunkingCdcMessageListener.java:352)
```

Where ChunkingCdcMessageListener
```
class ChunkingCdcMessageListener {
...
private void managePause() {
for (MessageListenerContainer messageListenerContainer : kafkaListenerEndpointRegistry.getAllListenerContainers()) {
...
  ConcurrentMessageListenerContainer<String, String> cdcListener = (ConcurrentMessageListenerContainer<String, String>) messageListenerContainer;
    for (KafkaMessageListenerContainer<String, String> partitionListener : cdcListener.getContainers()) {
....
```

I'm using springBootVersion = '2.2.3.RELEASE' with sping-kafka-2.3.5-RELEASE. I don't have reproductions steps for this. I think at the time exception was throws new consumers were added and old deleted.

**Comment by garyrussell** [comment]
We can (and will) fix the `ConcurrentModificationException` but pausing/resuming containers while at the same time stopping and starting them (which would modify the collection) has inherent dangers and the outcomes can't be guaranteed. i.e. you might not get what you expected.

**Comment by garyrussell** [comment]
We can (and will) fix the `ConcurrentModificationException` but pausing/resuming containers while at the same time stopping and starting them (which would modify the collection) has inherent dangers and the outcomes can't be guaranteed. i.e. you might not get what you expected.

I suggest you synchronize the stop/start and pause/resume.

**Comment by igouss** [comment]
That was fast!

**Comment by garyrussell** [comment]
@igouss Thanks for reporting; I am planning on releasing 2.4.4 tomorrow; let me know if you need it on another branch.
