### ISSUE TITLE
Kafka Streams Store Health Indicator

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-kafka#1421]
In cloud environments like kubernetes, kube api checks the application health and routes trafiic to that pod replying "UP". Some `HealthIndicator` can be registered to check whether state store(s) are initialized fully in order for kubernetes or some other cluster orchestrators to wait application readiness.

For kafka streams I think we can utilize `StateRestoreListener` and when its `onRestoreEnd` method is called, we can indicate that kafka streams store(s) is up at least.

**Comment by artembilan** [comment]
@nyilmaz ,

thank you for your request, but would you mind to be more specific.
The `HealthIndicator` is Spring Boot feature and out of scope of this project: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-health

The mentioned `StateRestoreListener` can be configured on the `StreamsBuilderFactoryBean`.
There is also a `KafkaStreamsCustomizer`, where you can configure a `setGlobalStateRestoreListener(this.stateRestoreListener)` or anything for `KafkaStreams` customization.
See docs for more info: https://docs.spring.io/spring-kafka/docs/2.4.4.RELEASE/reference/html/#streams-kafka-streams

Saying that I'm not sure what you expect from us to do in this project to fix the issue.
Please, elaborate.

**Comment by artembilan** [comment]
You also can declare a `StreamsBuilderFactoryBeanCustomizer` to inject your requirements into an auto-configured by Spring Boot `StreamsBuilderFactoryBean` .

See the same docs:

> Starting with version 2.3, you can perform additional customization of that bean, by providing a bean that implements `StreamsBuilderFactoryBeanCustomizer`. There must only be one such bean, or one must be marked `@Primary`.

**Comment by nyilmaz** [comment]
sure @artembilan, I am currently using that approach (besides i've added the customizer lol https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsCustomizer.java).

I introspected other health indicators all being packaged under spring boot.

I guess, i have ended up in wrong project for doing this, apologizes. Going after an issue at spring-boot.
