### ISSUE TITLE
Remaining records should not be processed after catching ProducerFencedException in transactional non batch processing

### ISSUE THREAD

**Issue by bartosz-stasikowski-projectdrgn** [spring-projects/spring-kafka#1424]
**Affects Version(s):** 2.3.6.RELEASE (newest too)

🐞 Bug report
Context: non batch, transactional processing.

Scenario:
1. Listener one polls 10 records from topicparition topic-1 and process it one by one
2. For some reason listener two gets assigned partition topic 1 and fences listener one
3. Listener one wants to commit transaction on first processed record and gets ProducerFencedException, as we are still in the loop in KafkaMessageListenerContainer.invokeRecordListenerInTx we just log error and process another record which was polled - producer is created and fences back listener two - **what is most important - if that succeed first record wont be reprocessed as we will commit new offset of second record**
4. Listener two gets fenced and can do the same and fence back producer 1

I think we are missing break after logging ProducerFencedException in KafkaMessageListenerContainer.invokeRecordListenerInTx - probably should be done after finally is done.

Any ideas how can we avoid that other than setting max.poll.records to 1?

**Comment by garyrussell** [comment]
Ouch!

Thanks - 2.3.7 is due today so I will be sure to include a fix for this; I can't think of a work around.

**Comment by bartosz-stasikowski-projectdrgn** [comment]
@garyrussell One more thought:

This (skipping records) should work when polled records from one topic-partition but if I polled records from multiple topic partitions I should only omit records from topic partition I was fenced off but process other messages.

Example:
1. Listener fetched 3 records from topicpartition topic-1 and 2 records from topic-3
2. Producer is fenced when processing first records form topic-1 but we do not know if we are fenced from topic-3 (we do not have to be fenced)
3. We should omit all records from topicparition topic-1 but try to process those from topicpartition topic-3, if we just skip them and we are still assigned to topic-3 then it is possible we wont process those records again

**Comment by garyrussell** [comment]
@bartosz-stasikowski-projectdrgn I thought about that too but I don't believe it's an issue; when a rebalance occurs we will lose all assigned partitions, so it's correct to discard them all.

Of course, when we next poll, a new rebalance will be triggered but, as long as the other instances handle their current poll results in a timely fashion, there will be no more fencing.

Make sense?

**Comment by bartosz-stasikowski-projectdrgn** [comment]
@garyrussell  

Yes, it makes sense. Rebalance will revoke all partitions, I forgot about it. 
Good,  this makes it easier.
