### ISSUE TITLE
Question regarding the invokeListener()

### ISSUE THREAD

**Issue by sandeepmalik** [spring-projects/spring-kafka#143]
Hi, 

Inside the invokeListener() of ListenerConsumer, I see this 
try {
					if (this.acknowledgingMessageListener != null) {
						this.acknowledgingMessageListener.onMessage(record,
								new ConsumerAcknowledgment(record, this.isManualImmediateAck));
					}
					else {
						this.listener.onMessage(record);
					}
					**_this.acks.add(record);_**
					if (this.isRecordAck) {
						this.consumer.wakeup();
					}
				}

My question is: 
the line in bold+italics, shouldn't this be inside the else block? Why are we adding the record to ack queue, even if the record may not have been acknowledged yet? Also, in the ConsumerAcknowledgment.acknowledgement(), we're putting the same record again in the queue?
ListenerConsumer.this.acks.put(this.record);

That seems like duplication of record acks. 

Thanks,
Sandeep

**Comment by artembilan** [comment]
Please, look into #141 .
So, this one duplicates and therefore is fixed already as well.

Cheers!

**Comment by sandeepmalik** [comment]
Thank you!
