### ISSUE TITLE
Need working example of Listener (Not test)

### ISSUE THREAD

**Issue by shailesh-joshi** [spring-projects/spring-kafka#144]
I am trying to integrate spring-kafka in my new application. I am able to produce messages and put them in Kafka using Kafka Template but listener is not working for me.

I have opened question at stackoverflow, but didn't find any answer.
http://stackoverflow.com/questions/38274667/spring-kafka-not-integration-consumer-not-consuming-message

Is there any example with `@KafkaListener` which is not using *embedded Kafka*?

**Comment by stepio** [comment]
Posted a fix suggestion in the related stackoverflow question.

**Comment by artembilan** [comment]
Even if our [quick sample](http://docs.spring.io/spring-kafka/reference/htmlsingle/#quick-tour) refers to Embedded Kafka, there is no so much difference with real one and we should just follow with standard Kafka Consumer Config approach, like Spring Kafka expect via `Map<String, Object> consumerConfigs` for its `DefaultKafkaConsumerFactory`.

Closing this one as redundant in favor of mentioned SO question.
