### ISSUE TITLE
Reactive kafka commit retry has no backoff

### ISSUE THREAD

**Issue by CodeMyWorld** [spring-projects/spring-kafka#1440]
**Affects Version(s):** \<2.3.1>

I am not sure whether here is the right place to issue the bug of reactive kafka.
When kafka client commits failed, client will retry immediately after the failed commit request (Kafka broker is temporally unavailable). And after 100 times retry within 10 ms, the comsumer flux is terminated, the consumer will not poll new messages anymore.
Retry should have backoff, instead of retrying immediately. By checking the log, the consumer thread retried to commit 100 times within 10ms. This time is not enough for Kafka client failover in a clustered environment.

**Comment by garyrussell** [comment]
I see you already opened this in the right place.

https://github.com/reactor/reactor-kafka/issues/127
