### ISSUE TITLE
Java & reference doc of Spring Kafka has a spelling typo for KafkaStreamBrancher

### ISSUE THREAD

**Issue by Musikolo** [spring-projects/spring-kafka#1459]
Hi,

I just noticed that java doc of [KafkaStreamBrancher](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/support/KafkaStreamBrancher.html) contains a spelling typo. Examples use class name `KafkaStreamsBrancher` instead of `KafkaStreamBrancher`  with no `s`. 

The same applies to section [4.2.4. Using KafkaStreamsBrancher](https://docs.spring.io/spring-kafka/docs/current/reference/html/#using-kafkastreamsbrancher) of the reference Spring Kafka documentation. 

Not a big deal, but it took me a while to realize about this little thing.

Thank you!

**Comment by garyrussell** [comment]
Thanks.
