### ISSUE TITLE
When there are retries left on ErrorHandler no ERROR should be logged

### ISSUE THREAD

**Issue by olahellgren** [spring-projects/spring-kafka#1461]
**Affects Version(s): ^2.3.7.RELEASE**

🎁 Enhancement
When an Exception is thrown and handled by `SeekToCurrentErrorHandler` an `error` is logged. As an error is an indication that you have to fix something this doesn't seem correct, this seems wrong. Since this could be resolved in subsequent retries by the `ErrorHandler`. And could be an intermittent error, like concurrency, network etc.

See: https://github.com/spring-projects/spring-kafka/blob/37dc6d60d95d2ced86ac93e4f90185f4bebf9897/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1734

This should be resolved by logging with less level until last retry.

Any thoughts?

**Comment by garyrussell** [comment]
I think we can throw a custom exception (from the framework retrying error handlers) to suppress this.

**Comment by garyrussell** [comment]
I think I've come up with a better solution; stay tuned...

**Comment by olahellgren** [comment]
Great! 

#1462 seems like a good solution.

Thank you!
