### ISSUE TITLE
Problem with @EmbeddedKafka and java 14

### ISSUE THREAD

**Issue by ganzah** [spring-projects/spring-kafka#1474]
Description:
Running a test annotated with EmbeddedKafka while using java 14 fails with messages like:

> java.lang.IllegalArgumentException: Unable to canonicalize address 127.0.0.1/\<unresolved\>:42171 because it's not resolvable
> 	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]

Versions:
spring boot version: 2.2.6 or 2.2.7 (SNAPSHOT)
spring kafka version: 2.3.7 or 2.3.8 or 2.4.6
java version: 14

Steps to reproduce:
Go to the spring initializer page and generate a maven project for Java 14 using spring boot version 2.2.6 or 2.2.7 (SNAPSHOT) and add Spring for Apache Kafka as a dependency. Add the EmbeddedKafka annotation to the DemoApplicationTests class and run "./mvnw test" from a terminal using java 14. The test will fail and the message mentioned above will be printed several times

Observations:

1. I believe the problem is a change in how Java 14 handles InetSocketAddress (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8232369). The version of the zookeeper library used by spring boot/spring kafka (in the versions mentioned above) does not work with this change
2. The problem is not happening with spring boot 2.3.0 (RC1), which is using spring-kafka 2.5.0 (RC1)
3. The problem does not happen with java 13
4. Given the above observations, I do not know if there is something that could be done here. I chose to open an issue because I did not find a mention to this specific situation regarding java 14 and the current versions of spring boot/spring kafka. Sorry if I missed something here!

**Comment by garyrussell** [comment]
When using spring kafka with spring boot; if you want to use a newer version of the kafka and zookeeper clients; **you have to override all the relevant jars**, as described [in the documentation](https://docs.spring.io/spring-kafka/docs/2.4.6.RELEASE/reference/html/#deps-for-24x).

Boot 2.2 will cause the older clients to be pulled in, if you override just the spring-kafka version.

**Comment by ganzah** [comment]
You are right @garyrussell. 
Overriding all the jars solves the problem. 
Thank you very much for the reply!
