### ISSUE TITLE
Abort consumer retries when listenercontainer is stopped

### ISSUE THREAD

**Issue by gnagy** [spring-projects/spring-kafka#1480]
Problem: while spring-kafka shuts down gracefully when ApplicationContext is closed, if there are retries, especially with exponential backoff, the shutdown process can wait a considerable time for a sleeping thread. For example, in a kubernetes cluster pods can come and go as a result of redeploys or scaling, where this delay can be detrimental.

Looking at how retries work now, FailedRecordTracker does a Threads.sleep() for the full backoff amount. Would it be possible to have a shorter loop (50-100ms perhaps?) and check for `listenerContainer.isRunning()` and bail out early? Not committing the offset would mean the message could be retried by another consumer.

**Comment by garyrussell** [comment]
Yes; that makes sense.

We might also want to consider exiting the while loop when using a record listener; to stop mid-batch.

**Comment by garyrussell** [comment]
@gnagy I have a working prototype for this, but it's too big a change to get into tomorrow's 2.5.0.RELEASE; we don't allow significant changes between a release candidate and release.

I'll leave it in "waiting for triage" for now and will discuss with the team whether 2.5.1 is a possibility (I tend to think it is but we need to agree).

**Comment by garyrussell** [comment]
>We might also want to consider exiting the while loop when using a record listener; to stop mid-batch.

That is already available with a recent change. I aim to get my prototype merged in time for next week's 2.7.0-M1 milestone.
