### ISSUE TITLE
Separate transactionIdPrefix for transactions started by a listener container

### ISSUE THREAD

**Issue by milofelipe** [spring-projects/spring-kafka#1503]
**Problem:**

As stated in the docs, when running multiple instances of an application, the `transactional.id` of consumer initiated transactions need to be the same. But it needs to be unique for each application instance when the transaction is started by the `KafkaTemplate` or `@Transactional`.

Overriding the KafkaTemplate's `transactionIdPrefix` can achieve a unique `transactional.id` for `KafkaTemplate` initiated transactions, for example:
`kafkaTemplate.setTransactionIdPrefix(String.format("tx-%s-", UUID.randomUUID()));`

But `@Transactional` still uses the default `transactionIdPrefix + n` `transactional.id`. Overriding the KafkaTransactionManager's `transactionIdPrefix` fixes this:
`kafkaTransactionManager.setTransactionIdPrefix(String.format("tx-%s-", UUID.randomUUID()));`

But the problem with this is it breaks the transactional.id of consumer initiated transactions. Consumer initiated transactions use the KafkaTransactionManager's transactionIdPrefix plus the zombie fenced suffix of `.<group.id>.<topic>.<partition>`. Making the transactional.id not the same for all instances anymore.

**Proposed Solution(s):**

Have a separate transactionIdPrefix configuration for the listener container. Looking at the code, the KafkaMessageListenerContainer sets a transaction suffix:
`TransactionSupport.setTransactionIdSuffix(zombieFenceTxIdSuffix(record.topic(), record.partition()));`

The DefaultKafkaProducerFactory checks if a suffix exists, then uses the prefix+suffix as the transactional.id. Maybe the prefix shouldn't be used anymore if a suffix exists. Or the new consumer prefix be used.

Another approach could be allowing TransactionSupport to hold a transactionId:
`TransactionSupport.setTransactionId(zombieFenceTxId(record.topic(), record.partition()));` Then the DefaultKafkaProducerFactory uses that if it exists before checking for a suffix.

**Comment by garyrussell** [comment]
Why not just configure 2 `KafkaTransactionManager`s - one for the container and one for `@Transactional`?

also, with 2.5 (and 2.5.0 brokers) and `EOSMode.BETA`, we no longer need the zombie fenced suffix.

https://docs.spring.io/spring-kafka/docs/2.5.2.RELEASE/reference/html/#exactly-once

**Comment by milofelipe** [comment]
Yes. Configuring two `KafkaTransactionManager`s, two `ChainedKafkaTransactionManager`s, and one `KafkaTemplate` is the workaround we did. I guess this is ok. Would have been great to just have one configuration parameter to do this.

I've read about `EOSMode.BETA` and it does solve the zombie fenced issue. Unfortunately, we can't upgrade our brokers to 2.5.0 yet.
