### ISSUE TITLE
Json de-serialization strategy configured per topic

### ISSUE THREAD

**Issue by tfactor2** [spring-projects/spring-kafka#1506]
As far as I understand the current strategy for deserialization is the following:
1. Programmatically set deserializer for a `Consumer` (`ConsumerFactory`) - `new JsonDeserializer<>(MyClass.class)`
2. Add type information into message headers (`__KeyTypeId__`, `__TypeId__`)

Both approaches have drawbacks in my opinion:
* the first one: it becomes not possible to deserialize different payloads per consumer
* the second one: it's insecure (one can forget to add a package to trusted ones), set a coupling between producer and consumer, bloats headers

Instead, a client (consumer) can provide a mapper or mapper function that depending on data available takes a decision of what java type to use.

Currently `Jackson2JavaTypeMapper` plays such a mapper function role. But it's limited to _headers_:
`JavaType toJavaType(Headers headers)`.

I'm suggesting to:
1. extend  `Jackson2JavaTypeMapper` with something like `JavaType toJavaType(String topic, Headers headers, byte[] data)` 
2. Extend API of JsonDeserializer: maybe pass `Map` `Topic -> JavaType` for simplest cases and give an ability to pass a function for more complicated ones - or something like that.

This will allow developing a contract-driven architecture with weak dependencies rather than strong binary ones.

**Comment by garyrussell** [comment]
>the second one: it's insecure (one can forget to add a package to trusted ones), set a coupling between producer and consumer, bloats headers

See `setIdClassMapping(Map<String, Class<?>> idClassMapping)`

The sender maps the types to a token and the receiver maps the token to a class. This was to prevent that coupling.

In 2.5, we added 

```java
	/**
	 * Set a {@link BiFunction} that receives the data to be deserialized and the headers
	 * and returns a JavaType.
	 * @param typeFunction the function.
	 * @since 2.5
	 */
	public void setTypeFunction(BiFunction<byte[], Headers, JavaType> typeFunction) {
		this.typeFunction = typeFunction;
	}
```
See [Using Methods to Determine Types](https://docs.spring.io/spring-kafka/docs/2.5.2.RELEASE/reference/html/#serdes-type-methods).

It is similar to your suggestion, but does not provide access to the topic name, just the bytes and headers.

**Comment by tfactor2** [comment]
Thanks for the hint and quick reply!

As mentioned by you - there is no topic there - was that an intentional decision?

Using a topic could eliminate serialization overhead completely from the producer side.

**Comment by garyrussell** [comment]
It wasn't "intentional"; just not considered when we added the feature; consuming from multiple topics is quite rare; so you can configure a different method for each consumer.

However, I think it's useful, so I'll add that option in the next release.
