### ISSUE TITLE
Transaction timeout is not configurable in KafkaMessageListenerContainer

### ISSUE THREAD

**Issue by orange-buffalo** [spring-projects/spring-kafka#1527]
**Affects Version(s):** 2.5.2

**Use Case**
Consume a record transactionally using `@KafkaListener` method with a custom timeout (for example, using a `ChainedKafkaTransactionManager` with Kafka and JTA TMs).

**Problem**
`org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer#ListenerConsumer` creates a `TransactionTemplate` (`determineTransactionTemplate` method) without any possibility to configure the transaction, including no way to provide a custom timeout. 

**Suggestion**
Provide `TransactionDefinition` to the `ContainerProperties` similarly how `PlatformTransactionManager` is provided and use it to create `TransactionTemplate`.

**Details**
Just in case it is interesting or useful, we are implementing an Idempotent Consumer pattern using a `RecordFilterStrategy` that stores the record identifier in the database (and filters out the records that already exist in the database). In order to guarantee transactional processing of this filter and business logic in the `@KafkaListener`, we provide a JTA TM via `ContainerProperties#setTransactionManager` (actually no use of `KafkaTransactionManager` in this use case). Some of the business operations might take longer to process and we need to provide a custom transaction timeout for them. As transaction is now fully managed by the listener container, we have no means to achieve this. It would be helpful to have something like this:
```
ConcurrentKafkaListenerContainerFactory<Object, Object> factory = ....

factory.getContainerProperties().setTransactionManager(transactionManager);

DefaultTransactionDefinition transactionDefinition = new DefaultTransactionDefinition();
transactionDefinition.setTimeout(TIMEOUT_IN_SECONDS);
factory.getContainerProperties().setTransactionDefinition(transactionDefinition);

factory.getContainerProperties()
                .getKafkaConsumerProperties()
                .put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, TIMEOUT_IN_SECONDS * 1000);
```

**Comment by garyrussell** [comment]
>(actually no use of KafkaTransactionManager in this use case)

If you are not using Kafka transactions then why not just start the transaction yourself in the filter?

**Comment by garyrussell** [comment]
Since you are not using Kafka transactions, one work around would be to use `@Transactional` on the listener and do the filtering there, instead of using the built-in filter strategy.

**Comment by orange-buffalo** [comment]
Many thanks for the workaround suggestion and for the prompt feature implementation!

**Comment by skubicz** [comment]
Great feature. When it will be released?

**Comment by garyrussell** [comment]
July 22.
