### ISSUE TITLE
Kafka Consumer not able to read all message after offset commit (error=OFFSET_OUT_OF_RANGE)

### ISSUE THREAD

**Issue by navinas33** [spring-projects/spring-kafka#1529]
i created consumer to receive messages as batch , ConsumerConfig:

    allow.auto.create.topics = false
    auto.commit.interval.ms = 5000
    auto.offset.reset = latest
    bootstrap.servers = [localhost:9092]
    check.crcs = true
    client.dns.lookup = default
    client.id =
    client.rack =
    connections.max.idle.ms = 540000
    default.api.timeout.ms = 60000
    enable.auto.commit = false
    exclude.internal.topics = true
    fetch.max.bytes = 52428800
    fetch.max.wait.ms = 500
    fetch.min.bytes = 1
    group.id = cm-persistence-notification
    group.instance.id = null
    heartbeat.interval.ms = 3000
    interceptor.classes = []
    internal.leave.group.on.close = true
    isolation.level = read_uncommitted
    key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
    max.partition.fetch.bytes = 1048576
    max.poll.interval.ms = 300000
    max.poll.records = 1000
    metadata.max.age.ms = 300000
    metric.reporters = []
    metrics.num.samples = 2
    metrics.recording.level = INFO
    metrics.sample.window.ms = 30000
    partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
    receive.buffer.bytes = 65536
    reconnect.backoff.max.ms = 1000
    reconnect.backoff.ms = 50
    request.timeout.ms = 30000
    retry.backoff.ms = 100
    sasl.client.callback.handler.class = null
    sasl.jaas.config = null
    sasl.kerberos.kinit.cmd = /usr/bin/kinit
    sasl.kerberos.min.time.before.relogin = 60000
    sasl.kerberos.service.name = null
    sasl.kerberos.ticket.renew.jitter = 0.05
    sasl.kerberos.ticket.renew.window.factor = 0.8
    sasl.login.callback.handler.class = null
    sasl.login.class = null
    sasl.login.refresh.buffer.seconds = 300
    sasl.login.refresh.min.period.seconds = 60
    sasl.login.refresh.window.factor = 0.8
    sasl.login.refresh.window.jitter = 0.05
    sasl.mechanism = GSSAPI
    security.protocol = PLAINTEXT
    send.buffer.bytes = 131072
    session.timeout.ms = 10000
    ssl.cipher.suites = null
    ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
    ssl.endpoint.identification.algorithm = https
    ssl.key.password = null
    ssl.keymanager.algorithm = SunX509
    ssl.keystore.location = null
    ssl.keystore.password = null
    ssl.keystore.type = JKS
    ssl.protocol = TLS
    ssl.provider = null
    ssl.secure.random.implementation = null
    ssl.trustmanager.algorithm = PKIX
    ssl.truststore.location = null
    ssl.truststore.password = null
    ssl.truststore.type = JKS
    value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

Spring boot Config:

public KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<String, String>> cmPersistenceListenerContainerFactory(
        KafkaProperties kafkaProperties )
    {
        ConcurrentKafkaListenerContainerFactory<String, String> containerFactory =
            new ConcurrentKafkaListenerContainerFactory<>();

        Map<String, Object> consumerProperties = kafkaProperties.buildConsumerProperties();
        consumerProperties.put( ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1000" );
        consumerProperties.put( ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false );
        consumerProperties.put( ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, false );

        containerFactory
            .setConsumerFactory(
                new DefaultKafkaConsumerFactory<>(
                    consumerProperties, new StringDeserializer(), new StringDeserializer() ) );
        containerFactory.setBatchListener( true );
       
        containerFactory.getContainerProperties().setCommitLogLevel(LogIfLevelEnabled.Level.INFO);
        
        containerFactory.getContainerProperties().setAckMode( AckMode.MANUAL_IMMEDIATE );
        
        return containerFactory;
    }

    @Bean
    public KafkaAdmin kafkaAdmin( KafkaProperties kafkaProperties )
    {
        return new KafkaAdmin( kafkaProperties.buildAdminProperties() );
    }

Listener Class :

```
@KafkaListener( id = "batch-listener-0", topics = "topic1", groupId = "test", containerFactory = KafkaConsumerConfiguration.CONTAINER_FACTORY_NAME )
    public void receive(
        @Payload List<String> messages,
        @Header( KafkaHeaders.RECEIVED_MESSAGE_KEY ) List<String> keys,
        @Header( KafkaHeaders.RECEIVED_PARTITION_ID ) List<Integer> partitions,
        @Header( KafkaHeaders.RECEIVED_TOPIC ) List<String> topics,
        @Header( KafkaHeaders.OFFSET ) List<Long> offsets,
        Acknowledgment ack )
    {
        long startTime = System.currentTimeMillis();

        handleNotifications( messages ); // will take more than 5s to process all messages

        long endTime = System.currentTimeMillis();

        long timeElapsed = endTime - startTime;

        LOGGER.info( "Execution Time :{}", timeElapsed );

        ack.acknowledge();

        
        LOGGER.info( "Acknowledgment Success" );

    }


```I am using manual Acknowledgment after processing message .

I found some debug log :

enter image description here

In above debug log , ****fetch offset is happening before offset commit, that offset is not commited so it returning OFFSET_OUT_OF_RANGE, consumer is not able to receive any message after that , Is there any way to handle this error in consumer code or how to fetch offset only after commit ****

**Comment by navinas33** [comment]
for loop in producer to send messages continuously , count 1000000 able to receive all message in consumer console , but failed to receive in java in consumer , i need to receive message and do db operation so will take some time for that , so i am committing offsets manually. Able to receive and update db sometimes , its a sporadic failure Producer code : github.com/navinas33/kafka-producer-test Consumer code : github.com/navinas33/kafka-test

log.retention period is 24 hours , so messages are available in kafka

**Comment by garyrussell** [comment]
Why are you asking the same question in [multiple places](https://stackoverflow.com/questions/62688963/kafka-consumer-not-able-to-read-all-message-after-offset-commit-error-offset-ou)? It's a waste of our time and yours. The container always commits any pending offsets before performing a `poll()`.

This appears to be come kind of corruption in the log; you might get a faster response on one of the kafka mailing lists.

**Comment by navinas33** [comment]
Same working in local setup , but failing in Kubernetes cluster with 3 broker replica. how to manage Fetch offset in Fetcher Class cluster with multiple brokers. Consumer is skipping some 200000 offset everytime in cluster 

```
2020-07-05 04:49:02.012  INFO 1 --- [istener-0-0-C-1] o.a.k.c.consumer.internals.Fetcher       : [Consumer clientId=consumer-1, groupId=cm-persistence-notification] Fetch offset 19254 is out of range for partition nbi.cm.changes.mo.test25-2, resetting offset
2020-07-05 04:49:02.014  INFO 1 --- [istener-0-0-C-1] o.a.k.c.c.internals.SubscriptionState    : [Consumer clientId=consumer-1, groupId=cm-persistence-notification] Resetting offset for partition nbi.cm.changes.mo.test25-2 to offset 269386.

```

Got out of range for partition in org.apache.kafka.clients.consumer.internals.Fetcher<K, V>

![image](https://user-images.githubusercontent.com/19791213/86700856-1bc34780-c02f-11ea-9066-e4bd012decf5.png)

I want to know when all will get OFFSET_OUT_OF_RANGE error , I got some answer for this question like :
1. offset deleted in kafka due to retention period or size.
2. Partition rebalance.

But in my case, everything is working fine , offset available in kafka and rebalancining  not happening .

**Comment by garyrussell** [comment]
This has nothing to do with Spring. While we can answer many Kafka questions, we are not Kafka experts here; we are Spring experts; as I said, you should ask your question on the [Kafka Mailing List](https://kafka.apache.org/contact).
