### ISSUE TITLE
Allow for checking the status of a topic just being created

### ISSUE THREAD

**Issue by henke77** [spring-projects/spring-kafka#1538]
🎁 Enhancement
When you create topics inside the EmbeddedKafkaBroker using one of the addTopics() methods you may run into topic already exists exceptions. The problem is that you cannot circumvent this by checking with getTopics() method because it doesn't return topics that are just being created. Therefore, it would be useful if the addTopics() methods would return the CreateTopicsResult that they receive from the AdminClient call or something analog that allows for checking the status of a topic just being created.

**Comment by garyrussell** [comment]
Can you explain the use case? Normally, topics are added to an empty broker at the beginning of a test. It would be unusual to add topics that already exist.

It would be a breaking change for us to change the behavior of the existing methods (we could add other flavors that just return the `CreateTopicsResult` so the user can check the result of individual adds.

Contributions are welcome!

As an alternative, you could call `doWithAdmin()` with your own callback.

**Comment by henke77** [comment]
I tried https://docs.spring.io/spring-kafka/docs/current/reference/html/#using-the-same-brokers-for-multiple-test-classes
Here I ran into the the topic exists exceptions.

**Comment by henke77** [comment]
In addition, you must be sure the topic really exists before assigning a consumer.

**Comment by garyrussell** [comment]
We generally recommend using different topics in each test, to avoid cross-talk between tests and issues with test ordering.
