### ISSUE TITLE
Update scalaVersion to 2.13

### ISSUE THREAD

**Issue by DieBauer** [spring-projects/spring-kafka#1544]
**Affects Version(s):** \<Spring for Apache Kafka version>

The Kafka library is built with Scala. Scala is known to be binary incompatible between 'minor' versions. This means that a library built with Scala 2.12 cannot be replaced by a library built with Scala 2.13. 

Scala 2.13 is released over a year ago (https://scala-lang.org/news/2.13.0) and a Kafka library built with Scala 2.13 is released since Kafka 2.4.0+ (https://www.confluent.io/blog/apache-kafka-2-4-latest-version-updates). 

I would like to be able to have my project use Scala 2.13 artifacts (performance improvements, longer support, etc..) and also use Spring Kafka. 

I propose to change the scalaVersion of Spring Kafka to 2.13. 

Pros: 
- Projects are unblocked to use Scala 2.13 artifacts

Cons: 
- Projects that use artifacts that are not available for Scala 2.13 (legacy, unmaintained, ..) cannot use the releases of Spring Kafka that have the scalaVersion set to 2.13.

**Comment by garyrussell** [comment]
The Kafka [downloads page](https://kafka.apache.org/downloads) still recommends 2.12.

>We build for multiple versions of Scala. This only matters if you are using Scala and you want a version built for the same Scala version you use. Otherwise any version should work (2.12 is recommended).

So we need to stick with that until it changes.

Furthermore, the runtime does not use scala at all; we only use the scala libraries in the spring-kafka-test jar (for the embedded Kafka server).

You can always override the versions in your project; [instructions here](https://docs.spring.io/spring-kafka/docs/2.4.7.RELEASE/reference/html/#deps-for-24x).

**Comment by DieBauer** [comment]
Thanks for the instructions! Adding the following to my POM does indeed help me :)

```
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${kafka.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.13</artifactId>
            <version>${kafka.version}</version>
            <classifier>test</classifier>
            <scope>test</scope>
        </dependency>
```

You are completely correct, this is only an issue when you have spring-kafka-test as a dependency on your classpath. 

I think it makes sense to follow the kafka guideline then in upgrading, since there is a workaround in place!

**Comment by garyrussell** [comment]
FYI, as of the recent 2.6 release; they are now recommending 2.13 - so our next release (also 2.6 coincidentally) will move to that version.

https://kafka.apache.org/downloads
