### ISSUE TITLE
Consumer properties set on ConcurrentKafkaListenerContainerFactory are silently ignored

### ISSUE THREAD

**Issue by orange-buffalo** [spring-projects/spring-kafka#1552]
**Affects Version(s):** 2.5.4

**Use Case**
Setup a custom `ConcurrentKafkaListenerContainerFactory` with custom `max.poll.inteval.ms`:
```java
@Bean
public ConcurrentKafkaListenerContainerFactory<?, ?> customListenerContainerFactory(
        ConsumerFactory<Object, Object> kafkaConsumerFactory,
        ConcurrentKafkaListenerContainerFactoryConfigurer configurer) {
   ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
   configurer.configure(factory, kafkaConsumerFactory);
   factory.getContainerProperties()
                .getKafkaConsumerProperties()
                .put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 10_000);
   return factory;
}
```

**Expected Result**
`max.poll.inteval.ms` for the consumers created by this factory is set to the provided value (`10_000` in this example) or exception is thrown if not possible or warning is logged if not possible.

**Actual Result**
`max.poll.inteval.ms` configuration is ignored.

**Assessment**
`DefaultKafkaConsumerFactory#createConsumerWithAdjustedProperties` only iterates string values in the provided properties (btw, what is the reason here? Kafka consumer accepts object types). There is a guard check `DefaultKafkaConsumerFactory#checkForUnsupportedProps` that logs warnings when values are not strings, but it only iterates the explicitly set values and does not iterate over defaults, while `containerProperties.kafkaConsumerProperties` is provided as defaults for the validated `Properties` instance.

**Comment by garyrussell** [comment]
Notice that that property (`kafkaConsumerProperties`) is a `Properties` object. It's an unfortunate side-effect of the poor design of `java.util.Properties` being a subclass of `HashTable`. Properties can have defaults:

```java
    /**
     * Creates an empty property list with the specified defaults.
     *
     * @param   defaults   the defaults.
     */
    public Properties(Properties defaults) {
        this.defaults = defaults;
    }
```

If you iterate over the hash table instead, defaults are not looked up; you have to use `getProperty()`.

```java
    /**
     * Searches for the property with the specified key in this property list.
     * If the key is not found in this property list, the default property list,
     * and its defaults, recursively, are then checked. The method returns
     * {@code null} if the property is not found.
     *
     * @param   key   the property key.
     * @return  the value in this property list with the specified key value.
     * @see     #setProperty
     * @see     #defaults
     */
    public String getProperty(String key) {
```

This container property was designed for overrides via the `properties` attribute on `@KafkaListener`, so the values are always Strings there.

I did not anticipate these properties to be set on the factory like that, but I can see that this behavior is not intuitive. I suppose we could iterate a second time over the hash table, ignoring any properties that are present in the `propertyNames()` set.

In the meantime, you can work around it wit

```java
.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "10000");
```

**Comment by garyrussell** [comment]
It's actually a bit more difficult than that, we currently use these properties as the `defaults` for another properties object:

```java
Properties consumerProperties = new Properties(this.containerProperties.getKafkaConsumerProperties());
```

and the `Properties` object does not provide any access to the default table directly, so we can't iterate over it.

I think the only thing we can do at this point is reject non-String property values - so at least it will fail fast rather than just silently ignoring the properties.

**Comment by garyrussell** [comment]
I figured out a way forward...

**Comment by garyrussell** [comment]
By the way, we **did** add this warning log (since 2.3.5)...

```java
	private void checkForUnsupportedProps(Properties properties) {
		properties.forEach((key, value) -> {
			if (!(key instanceof String) || !(value instanceof String)) {
				LOGGER.warn(() -> "Property override for '" + key.toString()
					+ "' ignored, only <String, String> properties are supported; value is a(n) " + value.getClass());
			}
		});
	}
```
