### ISSUE TITLE
Add `ConversionException` in `FailedRecordProcessor.classifier` to skip retrying

### ISSUE THREAD

**Issue by bananayong** [spring-projects/spring-kafka#1566]
**Affects Version(s):** 2.5.4

Hi, I would like to request a convenience feature.
I am writing a kafka listener which need json deserialization.
I learned that spring-kafka support `JsonDeserializer` and `JsonMessageConverter`.
And, I did choose `JsonMessageConverter` because it's more flexible.

The problem is when using `JsonMessageConverter`, if deserialization fails, it keeps to retry because `ConversionException`is not in exception classifications of `FailedRecordProcessor`
I solved this issue through `errorHandler.addNotRetryableException(ConversionException.class)`
But, It will be nice if `ConversionException` is in exception classifications by default

Please, Consider to add `ConversionException` in exception classifications

Thank you!

**Comment by garyrussell** [comment]
Thanks; yes; really the converter should throw a `MessageConversionException` (which is already in the default list) but that would be a breaking change now. So, yes, we'll add `ConversionException` to the default list.

**Comment by bananayong** [comment]
If you don't mind, can I get this issue for a contribution?

**Comment by garyrussell** [comment]
Sure. That would be great.

**Comment by garyrussell** [comment]
Thanks for the contribution!

Cherry-picked to 2.5.x after resolving conflicts.
