### ISSUE TITLE
How @KafkaListener design to multithread consume on different partitions

### ISSUE THREAD

**Issue by samuelweiwei** [spring-projects/spring-kafka#1581]
Since kafkalistener has annotations to define to listener to specific partition like below:
@KafkaListener(id = "listener1", containerFactory = "kafkaListenerContainerFactory", topicPartitions = {
			@TopicPartition(topic = "${kafka.consumer.qry}", partitions = { "1" }) })
how can we use it in prod enviroment. For in prod deployment, partition is up to the concurrency model, and partition
is defined dynamically. We should not write the partition int specific constant, it's hard coding.
But we can't configure the code in annotation with a java variable, it's comilation anchored.
Is there any measure to take to confiure the thread dynamically on different numbers of parttitions?

**Comment by artembilan** [comment]
The mentioned properties really can be configured dynamically.

See their JavaDocs:

```
/**
	 * The partitions within the topic.
	 * Partitions specified here can't be duplicated in {@link #partitionOffsets()}.
	 * @return the partitions within the topic. Property place
	 * holders and SpEL expressions are supported, which must
	 * resolve to Integers (or Strings that can be parsed as
	 * Integers).
	 */
	String[] partitions() default {};
```
and
```
/**
	 * Override the container factory's {@code concurrency} setting for this listener. May
	 * be a property placeholder or SpEL expression that evaluates to a {@link Number}, in
	 * which case {@link Number#intValue()} is used to obtain the value.
	 * <p>SpEL {@code #{...}} and property place holders {@code ${...}} are supported.
	 * @return the concurrency.
	 * @since 2.2
	 */
	String concurrency() default "";
```

The key word over there is `SpEL`, so you really can refer to any "java variable" from there.
See docs for more info: https://docs.spring.io/spring-kafka/docs/2.5.5.RELEASE/reference/html/#kafka-listener-annotation

Please, consider to ask questions in the future on StackOverflow: the GH issues are not forum.

Thanks

Closing as `Works as Desiged`
