### ISSUE TITLE
NullPointerException when starting KafkaMessageListenerContainer without setting ApplicationContext

### ISSUE THREAD

**Issue by vinh0604** [spring-projects/spring-kafka#1597]
**Version:** 2.5.6.RELEASE
**Issue:** 
When providing fully-qualified class names as value for `ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG` or `ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG`, `KafkaMessageListenerContainer` is no longer able to start without assigning an `ApplicationContext` first.
The reason is because it would need the `ClassLoader` from `ApplicationContext` in order to check whether deserializer class names are valid. However, if ApplicationContext is not set, it simply throw `NullPointerException`.

**Steps to re-produce:**
- Setting up a similar example as https://docs.spring.io/spring-kafka/docs/2.5.6.RELEASE/reference/html/#a-very-very-quick-example.
- Replace `props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, IntegerDeserializer.class);` `props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.IntegerDeserializer");`
- Run the test.

**Expected:** Test ran successfully. or failed with a descriptive error.
**Actual**: Test threw `NullPointerException`

```
java.lang.NullPointerException
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.checkDeserializer(KafkaMessageListenerContainer.java:940)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:668)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:302)
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:338)
```

**Comment by garyrussell** [comment]
If there's no context, we should use the container's classloader.

**Comment by sarvesh05** [comment]
I'm facing this issue. How can I locally resolve this?
Or do I need to wait for this to get released?

**Comment by garyrussell** [comment]
You should not be manually creating a listener container; it is designed to be managed by Spring; if there is not a proper application context, many features will not work. Define it as a Spring bean; if you are using Spring Boot, use the auto configured container factory to create it.

In a test case (such as referenced in the original post), it is ok to set it to `mock(ApplicationContext.class)`.

**Comment by vinh0604** [comment]
@sarvesh05 I solved it by manually setting the application context to `new GenericApplicationContext()`.

**Comment by asaintsever** [comment]
Hi, the issue is also present in spring-kafka 2.3.11 (part of Spring Boot 2.2.10.RELEASE). No backport to 2.3.x ?

**Comment by oburgosm** [comment]
I have observed that 2.4.9.RELEASE is also affected

**Comment by garyrussell** [comment]
As I said above, creating a container outside of a Spring context is not advised because a lot of functionality depends on it. It is not back-ported to all supported versions because there is a simple work around for test cases like this. I back ported to 2.5.x as a convenience since that was the version it was originally reported against.
