### ISSUE TITLE
After set  factory.getContainerProperties().setIdleBetweenPolls a new consumer group always on the Re-joining group status

### ISSUE THREAD

**Issue by xzhan** [spring-projects/spring-kafka#1601]
This is our consumer server listener
```java
  @Bean("retryMessageDelay5minConcurrentKafkaListenerContainerFactory")
    public ConcurrentKafkaListenerContainerFactory<String, String> retryMessageDelay5minConcurrentKafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(retryMessageDelay5minConsumerFactory());
        factory.setBatchListener(true);
        factory.getContainerProperties().setAckMode(ContainerProperties.AckMode.MANUAL_IMMEDIATE);
        factory.getContainerProperties().setIdleBetweenPolls(RetryConsts.DELAY_UNIT_5MIN);
        factory.setConcurrency(serviceConfig.getConcurrency());
        factory.getContainerProperties().setPollTimeout(serviceConfig.getPollTimeOutInMills());
        factory.setAutoStartup(serviceConfig.enableRetryNotification());
        ******
    }
```

Consumer server log

01:04 [ INFO] [tainer#38-0-C-1] o.a.k.c.Metadata                         :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] Cluster ID: Qbq_iQhCQHqv8r2yOhugFw
01:04 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.AbstractCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] Discovered group coordinator rphf95kaf001.qa.webex.com:9092 (id: 2147483504 rack: null)
01:04 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.AbstractCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] (Re-)joining group
01:04 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.AbstractCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] (Re-)joining group
01:05 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.ConsumerCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] Finished assignment for group at generation 5: {consumer-retryservice_group-18-6cdd9275-f136-4870-afe1-e750558b1883=Assignment(partitions=[hmdev2_meeting_retry_webex_notification_delay_5min-0, hmdev2_meeting_retry_webex_notification_delay_5min-1, hmdev2_meeting_retry_webex_notification_delay_5min-2, hmdev2_meeting_retry_webex_notification_delay_5min-3])}
01:05 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.AbstractCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] (Re-)joining group
01:05 [ INFO] [tainer#38-0-C-1] o.a.k.c.c.i.AbstractCoordinator          :  [Consumer clientId=consumer-retryservice_group-18, groupId=retryservice_group] (Re-)joining group

**Comment by xzhan** [comment]
I check the requirement https://github.com/spring-projects/spring-kafka/pull/1198  ,but it not works. dose anything my side wrong ?

**Comment by garyrussell** [comment]
`DELAY_UNIT_5MIN`

If you are idling for 5 minutes, you should increase `max.poll.interval.ms` in the consumer factory from its default 5 minutes. The framework does attempt to reduce the actual idle interval based on that setting, so it's not clear why a rebalance would occur.

**Comment by xzhan** [comment]
> `DELAY_UNIT_5MIN`
> 
> If you are idling for 5 minutes, you should increase `max.poll.interval.ms` in the consumer factory from its default 5 minutes. The framework does attempt to reduce the actual idle interval based on that setting, so it's not clear why a rebalance would occur.

Thanks @garyrussell  here is our config  max.poll.interval.ms set as 3600000 1 hours. 


07:35 [ INFO] [  restartedMain] o.a.k.c.c.ConsumerConfig                 :  ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [rphf95kaf001.qa.webex.com:9092, rphf95kaf002.qa.webex.com:9092, rphf95kaf003.qa.webex.com:9092]
	check.crcs = true
	client.dns.lookup = default
	client.id = 
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = internalservice_group
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 3600000
	max.poll.records = 5
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 600000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509


our kafka server (10 nodes) is Kafka 2.2.1+cdh6.3.0  - not worked

but my local kafka server only one machine kafka_2.12-2.5.0  - it worked

**Comment by garyrussell** [comment]
>our kafka server (10 nodes) is Kafka 2.2.1+cdh6.3.0 - not worked

>but my local kafka server only one machine kafka_2.12-2.5.0 - it worked

I suggest you reach out to Cloudera - I am not familiar with cdh6.3.0.

**Comment by xzhan** [comment]
> > our kafka server (10 nodes) is Kafka 2.2.1+cdh6.3.0 - not worked
> 
> > but my local kafka server only one machine kafka_2.12-2.5.0 - it worked
> 
Thanks @garyrussell , just not sure session.timeout.ms any impact for  that
