### ISSUE TITLE
The topic records shouldn't are added to "acks" queue when the "autoCommit" setted true in the class  KafkaMessageListenerContainer<K, V>

### ISSUE THREAD

**Issue by abc112358** [spring-projects/spring-kafka#161]
In the method run() of class ListenerConsumer of inner Class KafkaMessageListenerContainer<K, V>, it    invoke the method "invokeListener" ,which add the records  to "acks" queue when the "autoCommit" setted  true in the configuration.The size of "acks" queue will increase with the data increasement until beyond Integer.MAX_VALUE because the "acks" queue never poll when the "autoCommit" setted  true.
so ,I think the logic of handling message and putting the records to acks queue should separate into two part , and it should just invoke the logic of handling message  when  "autoCommit"  set true.
I don't know if I was clear.

**Comment by garyrussell** [comment]
Thanks for reporting - will fix asap - please note that we generally don't recommend using autoCommit - especially with broker partition assignment - since we have to run the listener on the consumer thread for this case, it can cause partition rebalancing when the listener is slow.

**Comment by Robin7Ma** [comment]
I found it too today. I spend all day long to test, I should search the issues early!

I want know when to release v1.0.3?

And before that, can I use the  stopgap code ( FIX1 & FIX0 ) below to make it work?

```java

public class MyKafkaMessageListenerContainer<K, V> extends AbstractMessageListenerContainer<K, V> {

  // Other codes ...

	private final class ListenerConsumer implements SchedulingAwareRunnable {

    // Other codes ...

    private void invokeListener(final ConsumerRecords<K, V> records) {
    	Iterator<ConsumerRecord<K, V>> iterator = records.iterator();
    	while (iterator.hasNext() && (this.autoCommit || (this.invoker != null && this.invoker.active))) {
    		final ConsumerRecord<K, V> record = iterator.next();
    		if (this.logger.isTraceEnabled()) {
    			this.logger.trace("Processing " + record);
    		}
    		try {
    			if (this.acknowledgingMessageListener != null) {
    				this.acknowledgingMessageListener.onMessage(record,
    						new ConsumerAcknowledgment(record, this.isManualImmediateAck));
    			} else {
    				this.listener.onMessage(record);
    			}
    			// this.acks.add(record); // FIX 0, line 601
    			if (this.isRecordAck) {
    				this.consumer.wakeup();
    			}
    		} catch (Exception e) {
    			if (this.containerProperties.isAckOnError()) {
    				// this.acks.add(record); // FIX 1, line 608
    			}
    			if (this.containerProperties.getErrorHandler() != null) {
    				this.containerProperties.getErrorHandler().handle(e, record);
    			} else {
    				this.logger.error("Listener threw an exception and no error handler for " + record, e);
    			}
    		}
    	}
    	if (this.isManualAck || this.isBatchAck) {
    		this.consumer.wakeup();
    	}
    }
  }
}

```

Thanks for your work!

**Comment by garyrussell** [comment]
We will release 1.0.3 tomorrow or Monday.
