### ISSUE TITLE
Kafka not working after upgrading to Hoxton.SR9

### ISSUE THREAD

**Issue by aariza1** [spring-projects/spring-kafka#1628]
Hello,
I have been getting the following exception in all our services that include Kafka after upgrading to Hoxton.SR9.
With Hoxton.SR8 is working just fine.

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException:

Somehow the service is not able to subscribe to the kafka topic.

We are also using Spring Boot 2.3.6.RELEASE
Any idea what could be triggering this error?

Thank you in advance!

**Comment by garyrussell** [comment]
You need to show the full stack trace.

**Comment by aariza1** [comment]
Stacktrace:

`.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[6129], headers={kafka_offset=1249928, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@52f30b66, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=61, kafka_receivedMessageKey=1001799931, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605146692343, kafka_groupId=classification-group-provider, accept=application/json}], failedMessage=GenericMessage [payload=byte[6129], headers={kafka_offset=1249928, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@52f30b66, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=61, kafka_receivedMessageKey=1001799931, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605146692343, kafka_groupId=classification-group-provider, accept=application/json}]`

**Comment by garyrussell** [comment]
>Caused by: org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'

This is a spring-cloud-stream issue; please open it in [that project](https://github.com/spring-cloud/spring-cloud-stream/issues); since it's in a different org, I can't move this there.

Show your configuration (application.yml).

**Comment by aariza1** [comment]
Thank you for your answer, I opened the issue there just before I did it here and they told me I had to open it here.

**Comment by garyrussell** [comment]
Right; you should always include as much information as possible, including a stack trace, to avoid such time wasting. With the simple description, I don't blame them for sending you here.

**Comment by aariza1** [comment]
Alright, i just posted the issue there with everything they could need. Thank you very much for your time.
