### ISSUE TITLE
Default concurrency value

### ISSUE THREAD

**Issue by raizoor** [spring-projects/spring-kafka#1629]
**Affects Version(s):** 2.2

🎁 Enhancement ->  default concurrency:
 
Isn't better if the default concurrency value were an calculated parameter? Example:
If I have 1 topic with 8 partitions and two containers, concurrency automatically will be set to 4 per container.

I think that is "more correct/adherent"  in the actual usage of springboot and kafka (microservices). 

Thanks !

**Comment by garyrussell** [comment]
We can't do that - we don't know how many instances of your application you might run. 

We can't assume there is only one instance.

We would end up with idle consumer threads.

It's not clear what you mean by "two containers" in this context; each `@KafkaListener` gets its own concurrent container; the framework doesn't look to see if you have 2 listeners in the same group listening to the same topic(s). I really don't see why you would do that anyway.

**Comment by raizoor** [comment]
Sorry, may be I'm not cleary..

When I said "two containers" I mean two instances. Imagine a springboot microservice running in an Kubernetes cluster, scale up and scale down many times of day. Now, imagine that:
-> I have two instances (2 kubernetes pods) that consumes topic with 8 partitions;
  -> If I set concurrency = 8 and I'll normally stay with 2 instances untill normally days;
    -> In normal days, I'm aways will be 4 iddle kafka threads.

But you're right, how can KafkaListener know about active instances to that topic? :(

**Comment by garyrussell** [comment]
It's generally best to over-provision the partitions; and adjust the concurrency to make good use of the resources on each instance (CPU, memory, I/O).

If you start with two instances, concurrency 4 and only 8 partitions, you can't scale out any more without adding partitions.

If you provision, say, 32 partitions; you can scale out to 8 instances without making any changes.

Initially, each instance (of 2) will get 16 partitions and end up with 4 when you have 8 instances.
