### ISSUE TITLE
Add (custom-)logging capabilities to SeekToCurrentErrorHandler similar to RetryTemplate

### ISSUE THREAD

**Issue by DRoppelt** [spring-projects/spring-kafka#1638]
Follow up of this question here: https://stackoverflow.com/questions/64937593/seektocurrenterrorhandler-exponentialbackoff-will-log-errors-after-backoff-has
**Affects Version(s):** 2.6.*

With the recent addition of  being able to set `BiFunction<ConsumerRecord<?, ?>, Exception, BackOff>` in SeekToCurrentErrorHandler via `handler.setBackOffFunction((record, ex) -> { ... });` (since 2.6), I found moving away from RetryTemplate very appealing. 

RetryTemplate gives a flexibility of what type of RetryPolicy to apply at what backoff. That BackOffFunction is close enough to that, so that we can skip RetryTemplate altogehter and benefit from the seek/poll guarantee that SeekToCurrentErrorHandler gives. Most importantly preventing rebalancing between retry-attempts. Also, the wording in here already makes it sound like we should not bother using RetryTemplate at all and only use Seek-To-Current: https://docs.spring.io/spring-kafka/reference/html/#stateful-retry

What I am missing however: RetryTemplate offers a `.setListeners(..)` to add loggers to give us some context for when an error happens:

Sample:

```
RetryTemplate retryTemplate = new RetryTemplate();
retryTemplate.setListeners(new RetryListener[]{new RetryListener() {
    @Override
    public <T, E extends Throwable> boolean open(RetryContext context, RetryCallback<T, E> callback) {
        return true;
    }
    @Override
    public <T, E extends Throwable> void close(RetryContext context, RetryCallback<T, E> callback, Throwable throwable) {
    }
    @Override
    public <T, E extends Throwable> void onError(RetryContext context, RetryCallback<T, E> callback, Throwable throwable) {
        System.out.println("Oops happened at " + context);
    }
}});
```
Where this gives us:
- error + stacktrace
- which appempt we are on (e.g. attempt 6)
- if retryContext is exhausted (i.e. we are at the last attempt)
- and some other functions (callback?), that I have not used myself

I think that adding a similar `.setListeners(...)` for error-handlers (maybe not just seek-to-current?) would cover a common use-case: logging when an exception happens. Especially since `MessageListenerContainer$ListenerConsumer : Error handler threw an exception` may log much later when a large retry-interval is applied.

I could see an interface (+sample implementation) similar to this:

```
SeekToCurrentErrorHandler eh = new SeekToCurrentErrorHandler ();
eh .setListeners(new ErrorListener[]{new ErrorListener() {
    @Override
    public void onError(Exception thrownException, ConsumerRecord<?, ?> record, Consumer<?, ?> consumer, MessageListenerContainer container) {
      //ConsumerRecord<?, ?> record = records.get(0); // not sure about the advantages about single record vs. having all polled records when logging an error for the current record? Current record would suffice IMO
      TopicPartitionOffset recordPosition = new TopicPartitionOffset(record.topic(), record.partition(), record.offset());
      Integer deliveryAttempt= deliveryAttempt(recordPosition);
      log.warn("Listener threw an exception, attempt {}. On partition {} at offset {}. Record timestamp {}. Message: {}", deliveryAttempt, recordPosition.getTopicPartition(), recordPosition.getOffset(), record.timestamp(), thrownException.getMessage());
    }
}});
```

Alternatively, this can be achieved by extending `SeekToCurrentErrorHandler#handle(..)`, as Gary suggested in my SO question. So this addition is not necessary, there are other ways to achieve it.

Thoughts?

I would also submit a PR if you think this is something that should be included.

**Comment by garyrussell** [comment]
Yes; I like the idea of a listener; I don't believe we would have the equivalent of open/close, but maybe `onError` and `afterRecovery`.

A PR would be welcome; the listener(s) should be added to the `FailedRecordProcessor` so that it will also be available on the `DefaultAfterRollbackProcessor`.

**Comment by garyrussell** [comment]
@DRoppelt Please take a look at the Pull Request to see if it meets your needs:

https://github.com/spring-projects/spring-kafka/pull/1691/files#diff-5a2b05fc5aea02b976dd8bf40ede8497a201427199840bc99015370116ac1f1a
