### ISSUE TITLE
Support null Payload in Multi-Method @KafkaListener

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#164]
See the discussion in #163 - since method selection is performed after message conversion, we can't select the method to call with a null payload.

Suggestion is some kind of fallback `@KafkaHandler` with just the key as a parameter.

**Comment by garyrussell** [comment]
I don't think this needs any code, just documentation - this works fine...

```java

	template.send("annotated8", 0, 1, "foo");
	template.send("annotated8", 0, 1, null);

@KafkaHandler
public void bar(String bar) {
	latch1.countDown();
}

@KafkaHandler
public void bar(@Payload(required = false) KafkaNull nul, 
                @Header(KafkaHeaders.RECEIVED_MESSAGE_KEY) int key) {
	latch1.countDown();
}
```

I don't think it's worth the effort to add code to detect a "special" method to handle the null case. @artembilan WDYT?

**Comment by artembilan** [comment]
OK. Fine with me. 
I can live with that template until special request to avoid an extra useless parameter, more over with annotation and that required attribute. :smile: 

Reviewing your PR and merging...
