### ISSUE TITLE
How to make video byte[] data producer and consumer with Kafka and spring boot ? 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [spring-projects/spring-kafka#1651]
Hi all, 

I am able to make produce and consumer for object-> json data or simle string data.
But I am want to make producer and consumer for video byte[] data . but kafkaTemplate.send() is not accepting byte[] data. 
`kafkaTemplate.send(TOPIC, videoStreamService.prepareContent(fileName, fileType, httpRangeList));`

kindly help me any for this problem. 

How to make video byte[] data producer and consumer with Kafka and spring boot ?

Objective: Make a simple producer and consumer app for live video steaming with spring boot and Kafka STACK. 

```
import com.saksoft.model.User;
import com.saksoft.service.VideoStreamService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Mono;

@RestController
@RequestMapping("/video")
public class VideoStreamController {

    private final VideoStreamService videoStreamService;

    @Autowired
    private KafkaTemplate<String, User> kafkaTemplate;

    private static final String TOPIC = "Kafka_Example";
    
    public VideoStreamController(VideoStreamService videoStreamService) {
        this.videoStreamService = videoStreamService;
    }

    @GetMapping("/stream/{fileType}/{fileName}")
    public Mono<ResponseEntity<byte[]>> streamVideo(ServerHttpResponse serverHttpResponse, @RequestHeader(value = "Range", required = false) String httpRangeList,
                                                    @PathVariable("fileType") String fileType,
                                                    @PathVariable("fileName") String fileName) {
        return Mono.just(videoStreamService.prepareContent(fileName, fileType, httpRangeList));
    }
    
    @GetMapping("/stream/published/{fileType}/{fileName}")
    public String published(ServerHttpResponse serverHttpResponse, @RequestHeader(value = "Range", required = false) String httpRangeList,
            @PathVariable("fileType") String fileType,
            @PathVariable("fileName") String fileName) {
        kafkaTemplate.send(TOPIC, videoStreamService.prepareContent(fileName, fileType, httpRangeList));
        return "Published successfully";
    }
}
```

Thanks
Dileep

**Comment by artembilan** [comment]
First of all this is a `question` category which we don't handle here on GitHub. It belongs to StackOverflow.

Anyway: to send a `byte[]` with Spring Kafka + Spring Boot, you need to provide a `spring.kafka.producer.valueSerializer.org.apache.kafka.common.serialization.BytesSerializer` configuration property, if you produce bytes yourself. Plus you have to autowire a `KafkaTemplate` as `KafkaTemplate<String, byte[]>`, not `User` as you have right now.
Or you can build a `ProducerRecord` manually.

Something similar on the consumer side: `spring.kafka.consumer.valueDeserializer.org.apache.kafka.common.serialization.BytesDeserializer`.

Closing as a StackOverflow matter.
