### ISSUE TITLE
"resetStateOnExceptionChange" has no effect as the exception is always "ListenerExecutionFailedException"

### ISSUE THREAD

**Issue by DRoppelt** [spring-projects/spring-kafka#1653]
**Affects Version(s):** 2.6.3 & 2.6.4

🐞 Bug report

Using "resetStateOnExceptionChange" does not have any effect since `exception.getClass()` is always `ListenerExecutionFailedException`. This feature was recently introduced with #1610

I have following setup:
- via ` errorHandler.setBackOffFunction((record, ex) -> {...}`, exception `SocketTimeoutException` is defined as "always retry"
- a given event hits `SocketTimeoutException` when processing a event for the first time -> is retried again
- later on, the exception-type changes, lets say I am calling a webservice that initially was unavailable but now says "resource not found", which leads to a different exception type

Expectation:
- using "resetStateOnExceptionChange", the BackOff type is evaluated again and now does not match "always retry" and the record is handled by the recoverer

What happens instead:
- record is retried again, the errorhandler does not realize that the exception changed

Looking at it with a debugger: `exception.getClass()` is always `ListenerExecutionFailedException` and never changes. The actual exception is nested one deeper at `exception.getCause()`.
![grafik](https://user-images.githubusercontent.com/6932863/101918958-4f9c2d80-3bca-11eb-9c4b-5f25ac2d42d6.png)

Sample to reproduce:

```
@Slf4j
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @KafkaListener(id = "gh1653", topics = "gh1653")
    public void listen(String in, @Header(KafkaHeaders.DELIVERY_ATTEMPT) int delivery) throws Exception {
        log.info("Processing {}", in);
        if(delivery>=2) {
            throw new RuntimeException("I have changed since the first attempt. Do not retry me. Attempt "+ delivery);
        }

        if(Integer.valueOf(in) % 2 == 0) {
            throw new SocketTimeoutException("I am retried infinitely. Payload is " + in);
        }


    }

    @Bean
    public ConcurrentKafkaListenerContainerFactory<?, ?> kafkaListenerContainerFactory(
            ConcurrentKafkaListenerContainerFactoryConfigurer configurer,
            ConsumerFactory<Object, Object> kafkaConsumerFactory) {

        ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
        configurer.configure(factory, kafkaConsumerFactory);
        factory.getContainerProperties().setDeliveryAttemptHeader(true); // optional, see https://docs.spring.io/spring-kafka/reference/html/#delivery-header
        FixedBackOff noRetryBackOff = new FixedBackOff(0, -1);
        FixedBackOff infiniteRetryBackOff = new FixedBackOff(1_000, Long.MAX_VALUE);
        SeekToCurrentErrorHandler eh = new SeekToCurrentErrorHandler((rec, ex) -> log.error("I am the dlq"));

        eh.setBackOffFunction((record, ex) -> {
            if(ex.getCause().getClass().equals(SocketTimeoutException.class)) {
                log.info("Classified {} as retryable", record.key());
                return infiniteRetryBackOff;
            }
            return noRetryBackOff;
        });
        eh.setResetStateOnExceptionChange(true);
        factory.setErrorHandler(eh);
        return factory;
    }

    @Bean
    public NewTopic topic() {
        return new NewTopic("gh1653", 1, (short) 1);
    }

    @Bean
    public ApplicationRunner runner(KafkaTemplate<String, String> template) {
        return args -> {
            IntStream.range(0, 10).forEach(i -> template.send("gh1653", i+"", i+""));
        };
    }
}
```

**Comment by DRoppelt** [comment]
One way to fix this would be to access ".getCause()" in both exceptions.

So from

`exception.getClass().isInstance(failedRecord.getLastException())`

To

`exception.getCause().getClass().isInstance(failedRecord.getLastException().getCause())`

But I am wondering if the handled exception should be unwrapped out of "ListenerExecutionException" at an earlier stage?

**Comment by DRoppelt** [comment]
I have submitted a PR, but I am not particularily happy how the fix looks like. Calling a "getCause()" looks wrong and I would rather have the exception handed down to this function be unwrapped already. But I am not familiar enough with where the correct place of "unwrap cause from ListenerExecutionFailedException" should take place

**Comment by garyrussell** [comment]
Sorry; I didn't see your PR before submitting my own. https://github.com/spring-projects/spring-kafka/pull/1655

I don't think we can unwrap the cause any earlier without causing a breaking change.

**Comment by DRoppelt** [comment]
No problem, I appreciate your fast reaction though! I like your changes better, so I will close this PR

**Comment by DRoppelt** [comment]
The last bugfix (2.6.4) was released just a few days ago, but do you have an ETA when a 2.6.5 will be released, which would include this fix?

**Comment by garyrussell** [comment]
2.6.5 will be released just (usually the day) before the next Boot 2.4.x release (which is not currently scheduled). I would guess late January or some time in February.

If there is a serious bug fix that doesn't have a reasonable work around, we would pull it forward.

In this case, there is a simple work around:

```java
class MyErrorHandler extends SeekToCurrentErrorHandler {
	
	@Override
	public void handle(Exception thrownException, List<ConsumerRecord<?, ?>> records,
			Consumer<?, ?> consumer, MessageListenerContainer container) {

		super.handle((Exception) thrownException.getCause(), records, consumer, container);
	}
	
}```

**Comment by sebastianloefflath** [comment]
Hey guys :)

it just came across this problem again.

affected version: spring-kafka 3.0.4
(Context: Spring Boot 3.0.4, Spring Cloud 2022.0.1)

the cause of the ListenerExecutionFailedException is always a [TimestampedException](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/listener/TimestampedException.html).

The stacktrace is:
ListenerExecutionFailedException -> TimestampedException -> ListenerExecutionFailedException -> MyException

it starts at 
1. the [RecordMessagingMessageListenerAdapter](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.html#onMessage(org.apache.kafka.clients.consumer.ConsumerRecord,org.springframework.kafka.support.Acknowledgment,org.apache.kafka.clients.consumer.Consumer)) that wraps `MyException` in a `ListenerExecutionFailedException`
2. the [KafkaBackoffAwareMessageListenerAdapter](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapter.html#onMessage(org.apache.kafka.clients.consumer.ConsumerRecord,org.springframework.kafka.support.Acknowledgment,org.apache.kafka.clients.consumer.Consumer)) wraps the `ListenerExecutionFailedException` into a `TimestampedException`
3. the `org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer.decorateException` wraps the `TimestampedException` in a `ListenerExecutionFailedException`

i have not tried the mentioned workaround yet :)

more context:

i use the following spring retry configuration:
```
@Configuration
class KafkaConfig(
    kafkaAdmin: KafkaAdmin
) : RetryTopicConfigurationSupport() {

    init {
        kafkaAdmin.setAutoCreate(false)
    }

    @ConditionalOnMissingBean
    @Bean
    fun scheduler() = ThreadPoolTaskScheduler()

    @Bean
    fun defaultRetryConfig(
        kafkaTemplate: KafkaTemplate<*, *>,
        @Value("\${spring.application.name}") appName: String
    ) =
        RetryTopicConfigurationBuilder
            .newInstance()
            .maxAttempts(1)
            .dltSuffix(".dlt-$appName")
            .notRetryOn(FatalException::class.java) // send directly to DLT
            .traversingCauses(true)
            .autoStartDltHandler(false) // do not consume DLT topic
            .create(kafkaTemplate)

    override fun manageNonBlockingFatalExceptions(nonBlockingRetriesExceptions: MutableList<Class<out Throwable>>) {
        nonBlockingRetriesExceptions.add(FatalException::class.java)
    }

    override fun configureBlockingRetries(blockingRetries: BlockingRetriesConfigurer) {
        blockingRetries
            .retryOn(RetryableException::class.java)
            .backOff(FixedBackOff(1_000, FixedBackOff.UNLIMITED_ATTEMPTS))
    }```
