### ISSUE TITLE
MessageListenerContainer getAssignedPartitions return partitions assigned even if broker is disconnected

### ISSUE THREAD

**Issue by clydzik** [spring-projects/spring-kafka#1657]
**Affects Version(s):** 2.5.8

I'm trying to find simplest way to know when kafka consumers exposed with @KafkaListener are operating normally. Means are connected to broker and are pooling messages.
I read the stack question and answer by Gary:

https://stackoverflow.com/questions/56134056/kafka-consumer-health-check

I tried to use the second approach to check 
org.springframework.kafka.listener.KafkaMessageListenerContainer#getAssignedPartitions

if the partitions are assigned in that container
I do that through org.springframework.kafka.config.KafkaListenerEndpointRegistry bean

The test procedure is like this:
1. i start test with @EmbeddedKafka, my listener gets assigned to topic and get partition assigned
2. i stop the kafka with EmbeddedKafkaBroker.destroy(). I see that consumer is trying to reconnect to broker
3. now i use the KafkaListenerEndpointRegistry to access KafkaMessageListenerContainer to check its partitions

and as i checked the partitions are still assigned even if the listener is not connected to the broker.

**Comment by garyrussell** [comment]
We have no control over that; it is all internal to the kafka-clients; we only know that the partitions are no longer assigned if a reblance occurs (and the listener `onPartitionsRevoked()` is called.

The kafka-clients API provides us with no mechanism to check the health of the the connection.

**Comment by clydzik** [comment]
That is fair explanation.
I was just interested in the fact that You mention that (as i understood) as alternate solution to check that directly on consumers and i wanted to try that approach before using AdminClient.

So i know this is not right way to continue discussion on alternatives on issue but having in mind that i want to check ifmy consumer is 'operating normally' is there an other approach (besides AdminClient) ?

**Comment by garyrussell** [comment]
You can use idle events:

```java
@SpringBootApplication
public class Kgh1657Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh1657Application.class, args);
	}

	@KafkaListener(id = "kgh1657", topics = "kgh1657")
	void listen(String in) {
		System.out.println(in);
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("kgh1657").partitions(1).replicas(1).build();
	}

	@EventListener
	void idle(ListenerContainerIdleEvent event) {
		System.out.println(event);
	}

}
```

```properties
spring.kafka.listener.idle-event-interval=5000
```

You can't tell that the event is due to it really having no records to process Vs. a dead connection but you could add code to the event listener to check the status of the broker.

**Comment by clydzik** [comment]
So as i understand the idle event can be a trigger to check the broker via for instance KafkaAdmin?
I think i have own trigger in that case so do not need additional one.

To summarize about the bug i understand that bug is accurate but probably there is no way for now to solve it by limitation from kafka-clients.
How we should proceed right now with it ? Should i close it ?

**Comment by garyrussell** [comment]
>Should i close it ?

I don't think we have a choice; sorry; closing.

Maybe you could open a new feature suggestion on the Apache Kafka JIRA - e.g. provide an API on the consumer `isConnected()` or similar.

If you do so, please add a reference here so we can track it.
