### ISSUE TITLE
Conusmer stop working after migration from 2.1.5 to 2.3.0

### ISSUE THREAD

**Issue by stefanofara** [spring-projects/spring-kafka#1658]
Hi,
we are migrating our spirng boot app from 2.1.5 to 2.3.0 .

The application cannot start consumer properly and the consumer ends with the following error

o.a.k.c.NetworkClient|handleServerDisconnect|[Consumer clientId= XXXXXX, groupId=XXXXXX] Bootstrap broker XXXXX:9092 (id: -2 rack: null) disconnected

In order to make consumer running we forced 2.2.7 version on spring-kafka, exclude the kafka-clients and add the kafka-clients 2.0.1

ON srever side we are using confluent 5.2.3 which brings kafka 2.2.2.

Any idea?

Thanks in advance,
Stefano

                  <dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>2.2.7.RELEASE</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.kafka</groupId>
					<artifactId>kafka-clients</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>2.0.1</version>
		</dependency>

**Comment by garyrussell** [comment]
Spring Boot 2.3.x requires spring-kafka 2.5.x.

You should not specify the version; let Boot bring in the proper supported version.

I am not aware of any problems when using a 2.5.1 kafka-clients with a 2.2.x broker.

**Comment by stefanofara** [comment]
Hi,
if I use the version 2.5.x the spring boot app consumer cannot connect to kafka and raises the error 

o.a.k.c.NetworkClient|handleServerDisconnect|[Consumer clientId= XXXXXX, groupId=XXXXXX] Bootstrap broker XXXXX:9092 (id: -2 rack: null) disconnected

Forcing kafka-clients to version 2.0.1 the consumer works fine.

**Comment by garyrussell** [comment]
I just tested a new Spring Boot (2.3.7) app (with spring-kafka 2.5.10, kafka-clients 2.5.1) against confuent platform 5.2.3 with no problems; so something else is going on in your environment.
