### ISSUE TITLE
Consider making onlyLogRecordMetadata true by default

### ISSUE THREAD

**Issue by jjathman** [spring-projects/spring-kafka#1659]
Having the default configuration in `ConsumerProperties.onlyLogRecordMetadata` be true by default. The standard configuration has the potential issue of logging sensitive data and wouldn't be expected by most developers in my opinion. Also, when using Spring Boot modifying this value is not very easy (see https://github.com/spring-projects/spring-boot/issues/24568). 

For example, I work in a health care setting and we would often have patient information in Kafka messages. We would *not* want this information logged in any circumstance. I was a little surprised to see that the `SeekToCurrentErrorHandler` would end up logging the entire record from the topic. 

I think this kind of verbose logging is something that should only be enabled explicitly by users.

**Comment by snicoll** [comment]
paging @garyrussell as `ContainerProperties` is only used to configure the listener and I don't see any constant for that property in `ConsumerConfig`.

**Comment by garyrussell** [comment]
>Also, when using Spring Boot modifying this value is not very easy ...

It is quite easy - just add this to your app...

```java
@Component
class Customizer {

	Customizer(AbstractKafkaListenerContainerFactory<?, ?, ?> factory) {
		factory.getContainerProperties().setOnlyLogRecordMetadata(true);
	}

}
```

**Comment by snicoll** [comment]
Indeed, and the other issue you've created means a property should be exposed as of Spring Boot 2.5....

**Comment by jjathman** [comment]
@garyrussell Ah OK. Thanks for that tip, I was really struggling with how to update this property.
