### ISSUE TITLE
ConsumerAwareRebalanceListener methods inherited from base interface are never called

### ISSUE THREAD

**Issue by mvh77** [spring-projects/spring-kafka#1668]
**Affects Version(s):** 2.6.4

I implemented this:

```java
var cp = new ContainerProperties(MY_TOPIC);
cp.setConsumerRebalanceListener(new ConsumerAwareRebalanceListener() {

    @Override
    public void onPartitionsAssigned(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        // this will be called ok        
    }

    @Override
    public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
        // from base interface, this will never be called
    }
});
```

onPartitionsRevoked (from base interface) is never called. The problem is at _KafkaMessageListenerContainer_ (line 2583-2589). The workaround is obviously to implement _onPartitionsRevokedBeforeCommit_ instead but the default implementation of _onPartitionsRevokedBeforeCommit_ should probably call _onPartitionsRevoked_ and the default implementations of _onPartitionsAssigned_ & _onPartitionsLost_ should also call the base IF methods?

**Comment by garyrussell** [comment]
While it is intended that you implement the consumer-aware methods, the default implementation should invoke the non-consumer-aware methods if not implemented.

**Comment by garyrussell** [comment]
A simple work around is to implement the consumer-aware method and ignore the consumer.
