### ISSUE TITLE
Support for the autoStartup configuration.

### ISSUE THREAD

**Issue by xiabin1** [spring-projects/spring-kafka#168]
The method  isAutoStartup() of SmartLifecycle is override in class AbstractMessageListenerContainer.But the variable of “autostartup” is setted to true constant. I hope it will be open for user to config because I want to controller it  myself in my project and I think it was an important configuration.

Thank you.

**Comment by garyrussell** [comment]
It's set to true by default but you can set it to false by calling `setAutoStartup(false)`.

[The code is here](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java#L165).

**Comment by xiabin1** [comment]
Sorry, I saw that method.But I misunderstanded it .

Thank you.

2016-08-15 20:36 GMT+08:00 Gary Russell <notifications@github.com>:
