### ISSUE TITLE
Spring Kafka & JPA - ChainedTransaction - HeuristicCompletionException

### ISSUE THREAD

**Issue by tamilsmani** [spring-projects/spring-kafka#1682]
Team,

I have configured Dead Letter Topic with KafkaTransactionManager & JpaTransactionManager using ChainedKafkaTransactionManager.

I have programmatically set the entity object to null to throw JPAException so that the JPA operation will be rolled back and commit (increment) the current Topic offset by 1. Also, the errored message should be published to Dead Letter Topic.

While trying to achieve the behavior, I do see the ChainedTransactionManager throws HeuristicCompletionException 

org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is rolled back; nested exception is org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
	at org.springframework.data.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:177) ~[spring-data-commons-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:152) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]

GIT Link: https://github.com/tamilsmani/kafka-transaction

1). Kafka Config - https://github.com/tamilsmani/kafka-transaction/blob/master/src/main/java/com/example/config/KafaTransactionDLTConfiguration.java

2). JPA Config - https://github.com/tamilsmani/kafka-transaction/blob/master/src/main/resources/jpa-persistence-context.xml

JPA I have configured in-memory H2 Database and you have to connect to the Kafka server locally (Actual Topic & DLT topic will be created automatically while running the application)

Please use below command to publish the "String" message to topic "my-replicated-demo-topic"
$ <kafka-home/bin/kafka-console-producer.sh --broker-list :9092 -topic my-replicated-demo-topic

Please help to resolve the issue?

**Comment by garyrussell** [comment]
The `ChainedKafkaTransactionManager` is a subclass of `ChainedTransactionManager`.

This has nothing to do with this project, that exception is thrown by the `ChainedTransactionManager` (spring-data-commons)  after calling `JpaTransactionManager`.  

It's not clear why you consider this a problem but, as I said on the other issue, you should reach out to the Spring Data folks for help with this.

**Comment by garyrussell** [comment]
The `ChainedKafkaTransactionManager` is a subclass of `ChainedTransactionManager`.

This has nothing to do with this project, that exception is thrown by the `ChainedTransactionManager` (spring-data-commons)  after calling `JpaTransactionManager`.  

It's not clear why you consider this a problem; it appears to be by design; but, as I said on the other issue, you should reach out to the Spring Data folks for help with this.
