### ISSUE TITLE
We are not able to get partitions end offset using KafkaMessageListenerContainer.

### ISSUE THREAD

**Issue by yamunachukka** [spring-projects/spring-kafka#1685]
I need to stop the consumer on the topic's last message.How can i identify particular message is the last message in the topic.

**Comment by garyrussell** [comment]
GitHub issues are NOT for asking questions. Did you not read the instructions in the issue template?

See https://stackoverflow.com/questions/64631411/spring-boot-kafka-polling-until-queue-is-empty-and-sleep/64648097#64648097
