### ISSUE TITLE
receiveAutoAck should use concatMap operator instead of flatMap operator

### ISSUE THREAD

**Issue by oemergenc** [spring-projects/spring-kafka#1693]
The documentation of the reactor-kafka project states that messages should be consumed using the `concatMap` operator, but the `ReactiveKafkaConsumerTemplate` uses the `flatMap` operator at least in case of the `receiveAutoAck` method here:

https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaConsumerTemplate.java#L69

Reference documentation of the reactor-kafka project: https://projectreactor.io/docs/kafka/release/reference/#_auto_acknowledgement_of_batches_of_records

See this Stackoverflow thread for reference:
https://stackoverflow.com/questions/65901791/message-ordering-of-reactivekafkaconsumertemplate-receiveautoack

**Comment by garyrussell** [comment]
cherry-picked to 2.6.x as 2f8b0425
