### ISSUE TITLE
Deprecate ChainedKafkaTransactionManager

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1699]
See https://github.com/spring-projects/spring-data-commons/issues/2232

**Comment by ecapoccia** [comment]
what is going to be the recommended approach in future to handle best effort 1pc between kafka and a db?

**Comment by ecapoccia** [comment]
yeah that makes sense, thanks for your reply @garyrussell

**Comment by ecapoccia** [comment]
Hi, one more question, sorry to pester @garyrussell. 

On this part: "_This provides virtually the same functionality as the Chained KTM in that the DB transaction will commit or roll back just before the Kafka transaction_".

The chained transaction manager ensured an ordered sequence of commits by reversing the order of transaction managers during commit or rollback:

`for (PlatformTransactionManager transactionManager : reverse(transactionManagers))`

from your answer you seem to imply that using a @Transactional coupled with a transactional kafka producer offers the same guarantees, so it is impossible that the kafka transaction commits before the DB transaction does. Is this the case, and how is this enforced?

**Comment by garyrussell** [comment]
For the consumer-initiated transaction case, it generally doesn't make sense to commit the Kafka transaction before the DB because it will cause message loss if the Kafka commit succeeds and the DB rolls back.

So in 99.99999% of the cases the behavior I described is what is needed.

For producer-initiated transactions, with transaction synchronization, the Kafka commit will also occur after the DB.

If you have a use case for the reverse, you can achieve that with nested `@Transactional` methods with the outer method starting the DB transaction and calling another `@Transactional` method to start the Kafka transaction. Again, this is functionally the same as using the CKTM because the Kafka transaction will commit or roll back first.
