### ISSUE TITLE
Configure the activation of a subset of producer and consumer metrics

### ISSUE THREAD

**Issue by garridobarrera** [spring-projects/spring-kafka#1702]
Hi,
I don't find any way to configure the activation of a subset of producer and consumer metrics. Is there possible ?

Regards

**Comment by garyrussell** [comment]
Please don't use GitHub issues to ask questions; I guess you didn't read the instructions.

Micrometer provides a mechanism [Meter Filters](https://micrometer.io/docs/concepts#_meter_filters) which allows you to suppress and/or modify meters.
