### ISSUE TITLE
Why commit automatically, when i don't acknowledge a message, in MANUAL AckMode

### ISSUE THREAD

**Issue by CEASARTING** [spring-projects/spring-kafka#1713]
I encountered a problem, when the program went wrong, it would still commit, I am a little dizzy.

this is my config
```java
@Configuration
@EnableKafka
public class KafkaConsumerListenerConfig {

    @Bean
    public Map<String, Object> consumerConfigs() {
        Map<String, Object> propsMap = new HashMap<>();
        propsMap.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        propsMap.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ResourceJsonDeserializer.class.getName());
        propsMap.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        propsMap.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false");

        return propsMap;
    }

    @Bean
    public ConsumerFactory<Integer, String> consumerFactory() {
        return new DefaultKafkaConsumerFactory<>(consumerConfigs());
    }

    @Bean
    KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<Integer, String>> kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<Integer, String>
                factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(1);
        factory.getContainerProperties().setPollTimeout(pollTimeout);
        factory.getContainerProperties().setAckMode(AckMode.MANUAL);
        return factory;
    }

}
```

this is my listener

```java

@KafkaListener(topics = "${kafka.topic}")
    public void consume(ConsumerRecord<String, SyncResMessage> record, Acknowledgment ack) {
        /* PROCESS */
        if (ack != null) {
            LOGGER.info("commit successfully.");
            ack.acknowledge();
        } else {
            LOGGER.error("Message of commit is null, record is {}.", JsonUtil.toString(record));
        }
    }
```

why it will commit automatically when it throws exception in PROCESS. 

please help me~~
(spring-kafka 2.1.7.RELEASE)

**Comment by garyrussell** [comment]
GitHub issues are NOT for asking questions - did you not read the issue template?

With that configuration, the container will NOT commit the offset(s). What makes you think it does?

**Comment by garyrussell** [comment]
By the way, 2.1.x (and 2.2.x) is no longer supported.

**Comment by CEASARTING** [comment]
> GitHub issues are NOT for asking questions - did you not read the issue template?
> 
> With that configuration, the container will NOT commit the offset(s). What makes you think it does?

i'm sorry about this and thanks for your replay.
 this is my log, 
![image](https://user-images.githubusercontent.com/32626433/109029045-69470e80-76fd-11eb-846b-24d673912715.png)
at first it throws exception when consumer consumes the message of 74024 offset, 
 and then it consumes 74025 immediately. this phenomenon makes me think it commits automatically

**Comment by garyrussell** [comment]
With that old version, the default error handler simply logs the error and moves on to the next record.

You need to add a `SeekToCurrentErrorHandler` to replay the failed record; after some number of attempts, it gives up and sends the record to a recoverer (e.g. the `DeadLetterPublishingRecoverer` - added in 2.2.x).

https://docs.spring.io/spring-kafka/docs/2.1.x/reference/html/_reference.html#_seek_to_current_container_error_handlers

With newer versions, the error handler can be configured to add a delay before redelivering.

**Comment by CEASARTING** [comment]
> With that old version, the default error handler simply logs the error and moves on to the next record.
> 
> You need to add a `SeekToCurrentErrorHandler` to replay the failed record; after some number of attempts, it gives up and sends the record to a recoverer (e.g. the `DeadLetterPublishingRecoverer` - added in 2.2.x).
> 
> https://docs.spring.io/spring-kafka/docs/2.1.x/reference/html/_reference.html#_seek_to_current_container_error_handlers
> 
> With newer versions, the error handler can be configured to add a delay before redelivering.

thank you so much!
