### ISSUE TITLE
Reconsider Defaults for @RetryableTopic Container Factory and KafkaTemplate

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1717]
Consider the following Boot app:

```java
@SpringBootApplication
public class Kgh920Application {


	private static final Logger LOG = LoggerFactory.getLogger(Kgh920Application.class);


	public static void main(String[] args) {
		SpringApplication.run(Kgh920Application.class, args);
	}

	@RetryableTopic(attempts = 5, backoff = @Backoff(delay = 1000, multiplier = 2.0), kafkaTemplate = "kafkaTemplate")
	@KafkaListener(groupId = "kgh920", topics = "kgh920", containerFactory = "kafkaListenerContainerFactory")
	public void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		LOG.info(in + " from " + topic);
		throw new RuntimeException("test");
	}

	@DltHandler
	public void dlt(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		LOG.info(in + " from " + topic);
	}

}
```

In order to use Boot's auto-configured `KafkaTemplate`, we are forced to add the `kafkaTemplate` property.

Similarly, the default container factory for `@KafkaListener` should apply without having to explicitly set it to the default in the annotation.

While the documentation recommends using a different factory for retryable Vs. non-retryable topics, at least when there are only retryable listeners, it would be more sensible to use the current defaults.

cc/ @tomazfernandes

**Comment by tomazfernandes** [comment]
We already use the @KafkaListener's factory if none is provided in the @RetryableTopic annotation, you can check it here: https://github.com/spring-projects/spring-kafka/blob/120ca483c44be3985ef22a9a8dcef31a032f5cb1/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryResolver.java#L75

As for the template, good call, I had used a different bean name for using as default for the RT, retryTopicDefaultKafkaTemplate, but that's easy to change for the SB's default one.

Maybe we can even check first for the RT's default, and if not found try to find the SB's default, or would that be confusing?

**Comment by tomazfernandes** [comment]
It's this logic here: https://github.com/spring-projects/spring-kafka/blob/120ca483c44be3985ef22a9a8dcef31a032f5cb1/spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java#L150

**Comment by garyrussell** [comment]
I was forced to add `containerFactory = "kafkaListenerContainerFactory"` (the name of the default). Without it, I get

```
A component required a bean named 'retryTopicListenerContainerFactory' that could not be found.
```

Without the KT entry, I get

```
A component required a bean named 'retryTopicDefaultKafkaTemplate' that could not be found.
```

Yes, I think we could fall back to the SK/SB default for the CF and the SB default for the template (after looking for the RT beans), as long as we log that neither was found in each case.

**Comment by tomazfernandes** [comment]
Hmm, I use the same resolveFactory method in the KLABPP to get the KL's factory and pass to the RT logic, so that's unexpected. I'll take a look.

**Comment by garyrussell** [comment]
Unfortunately, the default CF is resolved in the `KafkaListenerEndpointRegistrar`, not the BPP (when not provided in the annotation).

**Comment by tomazfernandes** [comment]
Oh, I see. I can’t wait till then because I need the instance to configure the error handling. Maybe we should just use the same bean name then? That should be one line to add in the LCFResolver

**Comment by garyrussell** [comment]
Sure, the bean name constant is in the KLABPP; it's just that it is passed into the registrar in `afterSingletonsInstantiated()`.
