### ISSUE TITLE
Spring Kafka 1.0.3 is incompatible with Spring Boot 1.4.0

### ISSUE THREAD

**Issue by hho** [spring-projects/spring-kafka#172]
Spring Kafka 1.0.3 depends on Spring Messaging 4.2.6.
Spring Boot 1.4.0 manages that version to Spring Messaging 4.3.2.

If used together, this line (recently introduced while fixing #160):

> https://github.com/spring-projects/spring-kafka/pull/163/files#diff-9eb98895b58208ad047d219021c8db6dR635

in Spring Kafka leads to a `java.lang.NoSuchMethodError`, as the parameterless constructor for `MessageMethodArgumentResolver` is no longer available in Spring Messaging &ge;4.3.0.

**Comment by jhoeller** [comment]
I consider this a bug in Spring Framework 4.3: That default constructor got dropped accidentally. We'll fix this in 4.3.3 (https://jira.spring.io/browse/SPR-14616).

**Comment by artembilan** [comment]
Spring Kafka `1.0` was started when there had no Spring Framework 4.3 yet. And we can't make such a minor upgrade in the point release. Version `1.1` is indeed based on the SF-4.3 already.

We will test SK-1.0.x against an appropriate SF-4.3.3.B-S when it is available.

**Comment by hho** [comment]
Thank you both for the quick replies!

I'll wait for Boot 1.4.1 (which presumably will use Framework 4.3.3) and use the Kafka 1.1 snapshot builds until then.

**Comment by artembilan** [comment]
Testing against the latest SF-4.3.3.B-S confirms that the fix is there.

Thank you for catching that out!
