### ISSUE TITLE
Exception management of ReplyingKafkaTemplate using Kafka Streams

### ISSUE THREAD

**Issue by Jereminet** [spring-projects/spring-kafka#1728]
Hi,

Because of business requirements, we need to use a ReplyingKafkaTemplate with Kafka Streams playing the role of the consumer. We want to provide a support for exception management (server side) such that it is possible to escalate errors as part of the future response. After digging into the code, we could find that in the onMessage() method of this listener you already check, if the record value is null, whether the record suffers from a deserialization exception and if so, you set the exception of the future object accordingly.

We would like to enhance this behavior with more exceptions, but we couldn’t find any hook points. Could it be possible to define an entry point such that other exceptions could also be considered when going through a batch of records ?

Below a screenshot of the method I'm referring to and the specific section where we would like to have more control.

Thank your for your consideration.

![ReplyingKafkaTemplate](https://user-images.githubusercontent.com/22636967/110507281-283cfa00-8100-11eb-80db-b868b16396f0.png)

**Comment by garyrussell** [comment]
The fix is in 2.6.7-SNAPSHOT (https://repo.spring.io/snapshot) if you want to try it out.

**Comment by Jereminet** [comment]
I will sure do ! Thanks again for your time and consideration !
