### ISSUE TITLE
Add support for @KafkaListener to handle batching 

### ISSUE THREAD

**Issue by ssherwood** [spring-projects/spring-kafka#174]
GH-142 has added batch support but I was also interested in seeing this capability exposed as part of the KafkaListener annotation.  In pull https://github.com/spring-projects/spring-kafka/pull/169 @artembilan and @garyrussell suggest this capability but were holding off on it until someone asks for it.  I guess that I am now asking for it.

As described, it could be something like this:
````
@KafkaListener(topics = "foo")
public void handleBatch(List<String> batch) {
...
}
````
Or
````
@KafkaListener(topics = "foo")
public void handleBatch(List<ConsumerRecord> batch) {
...
}
````
This could compliment the `max.poll.records` that was introduced in Kafka 0.10 as a way of defining the limit to be consumed in a single batch.  There probably should also be a maximum amount of wait time for each batch just in case the max records doesn't fill up so that it can still be consumed by the listener in a timely fashion.

I'm asking for this capability specifically for the ability to be able to produce a batch insert into a downstream database with each call to the "handleBatch".  In our use cases, there are some performance improvements that are achieved when handling Kafka records this way.

**Comment by garyrussell** [comment]
It may not be as much work as I thought when I added that comment - I'll take a look.

**Comment by garyrussell** [comment]
It did turn out to be a pain as I suspected but I basically got the first option (`List<String>` working) `List<ConsumerRecord>` is going to be a bit problematic but I have a couple of ideas.

I do populate some of the metadata in headers...

		@KafkaListener(id = "list2", topics = "annotated15", containerFactory = "batchFactory")
		public void listen11(List<String> list,
				@Header(KafkaHeaders.RECEIVED_MESSAGE_KEY) List<Integer> keys,
				@Header(KafkaHeaders.RECEIVED_PARTITION_ID) List<Integer> partitions,
				@Header(KafkaHeaders.RECEIVED_TOPIC) List<String> topics,
				@Header(KafkaHeaders.OFFSET) List<Long> offsets) {
			this.payload = list;
			this.keys = keys;
			this.partitions = partitions;
			this.topics = topics;
			this.offsets = offsets;
			this.latch11.countDown();
		}





Commit is on [this branch](https://github.com/garyrussell/spring-kafka/tree/GH-174).

**Comment by artembilan** [comment]
M-m-m. Can't then support something like ` listen11(List<Message<?>> batch)` ?
(I haven't looked to your code yet).
With that metadata in headers it looks like we have to merge all of them back to the proper model manually. Not sure where is a correlation, unless I have to believe you for `order` in all those lists.

**Comment by garyrussell** [comment]
Yes - good point; we should support that too - I also solved the `List<ConsumerRecord>` problem. 

I will add code for the List<Message<?>> version.

> unless I have to believe you for order in all those lists

Yes, you have to believe me 😄
