### ISSUE TITLE
Possibility to implement Classifier<Throwable, Boolean> for SeekToCurrentErrorHandler

### ISSUE THREAD

**Issue by sausageRoll** [spring-projects/spring-kafka#1742]
**Affects Version(s):** 2.6.7

🎁 Enhancement
Currently I use [SeekToCurrentErrorHandler](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java) for kafka listener ErrorHandler

And I want to skip retrying for certain exception. I can see there is an exception [classifier](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java#L57) for that purpose. It looks like for the logic itself it could have the following type: `Classifier<Throwable, Boolean>`. Unfortunately it's very tied to `ExtendedBinaryExceptionClassifier` implementation. 

I would like to write my own implementation for `Classifier<Throwable, Boolean>` as I want to analyse not only type of the exception, but the exception itself.

For example, in my case there could be a web client exception with different content inside and based on that content I would like to retry or skip.

**Comment by garyrussell** [comment]
@sausageRoll You can achieve your desired behavior by adding a BackOff function instead:

```java
	/**
	 * Set a function to dynamically determine the {@link BackOff} to use, based on the
	 * consumer record and/or exception. If null is returned, the default BackOff will be
	 * used.
	 * @param backOffFunction the function.
	 * @since 2.6
	 */
	public void setBackOffFunction(BiFunction<ConsumerRecord<?, ?>, Exception, BackOff> backOffFunction) {
		this.failureTracker.setBackOffFunction(backOffFunction);
	}
```

Return a `BackOff` with no retries to skip retrying.

**Comment by sausageRoll** [comment]
@garyrussell 
Interesting, I've missed that logic 
Thank you for the information! I think it solves the problem

**Comment by garyrussell** [comment]
Here's an example I used for another question:

```java
	@Bean
	ErrorHandler eh(KafkaOperations<String, Object> template) {
		SeekToCurrentErrorHandler eh = new SeekToCurrentErrorHandler(new DeadLetterPublishingRecoverer(template));
		BackOff neverRetryOrBackOff = new FixedBackOff(0L, 0);
		BackOff normalBackOff = new FixedBackOff(2000L, 3);
		eh.setBackOffFunction((rec, ex) -> {
			if (ex.getMessage().contains("No method found for class")) {
				return neverRetryOrBackOff;
			}
			else {
				return normalBackOff;
			}
		});
		return eh;
	}
```

**Comment by sausageRoll** [comment]
Hello @garyrussell 

Sorry for commenting on the closed tickets, but I think there could be one potential problem with that approach, please let me know what do you think about that.

1. Let's say I have 2 possible exceptions: A and B.
For A - I want to use infiniteBackoff(for example exponential backoff with max interval), for B - neverRetryOrBackOff

2. Then during message handling A acquired and we started using infiniteBackoff

3. The root cause of the problem that was causing A was solved and now during the same message handling B acquired

In that case I would like to switch to neverRetryOrBackOff, however it will be infiniteBackoff, because it's picked once and there is no way to re-evaluate that.

**Comment by garyrussell** [comment]
@sausageRoll I have that covered with 

```java
	/**
	 * Set to true to reset the retry {@link BackOff} if the exception is a different type
	 * to the previous failure for the same record. The
	 * {@link #setBackOffFunction(BiFunction) backOffFunction}, if provided, will be
	 * called to get the {@link BackOff} to use for the new exception; otherwise, the
	 * configured {@link BackOff} will be used.
	 * @param resetStateOnExceptionChange true to reset.
	 * @since 2.6.3
	 */
	public void setResetStateOnExceptionChange(boolean resetStateOnExceptionChange) {
```

**Comment by sausageRoll** [comment]
@garyrussell Very smart
I knew you have smth. Thank you!
