### ISSUE TITLE
RetryTopicConfigurer / DestinationTopicProcessor refactor

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-kafka#1745]
When these classes were first created one of the goals was to change existing Spring Kafka classes as little as possible in order to reduce the risk of breaking existing functionalities, and that led to lots of indirections and complexities in the `RetryTopicConfigurer` class. 

I've since then made one large refactor of this part which has mitigated this issue a lot, but I still think both this class and the `DestinationTopicProcessor` interface are a lot more complex than they should be.

This is the last major refactor I have in mind, and I think it should solve probably be the last maintenance pain point for this functionality as a whole.

This is not as important as the other issue I've just opened about KafkaConsumerBackoffManager, but it's something I'd like to do after that, if that's ok.

Please let me know what you think.

Thanks!

**Comment by apolci** [comment]
I just had to look at the internals of those two classes in search for a possible extension point (see #1772) and I can confirm your statement.
I planned to try to make a pull request for my feature request (not sure that I'm able to do it), but I fear it would conflict with this refactoring.

**Comment by tomazfernandes** [comment]
You're welcome to raise the PR! And since it looks like a really necessary feature, it's something I can work on as well if you prefer. Either way, I think we can hold this refactor for a while in the meantime and just work on this part. Let me know what you think, and thanks again for bringing this up!
