### ISSUE TITLE
Fix Remaining Doc References 'Spring Kafka' to 'Spring for Apache Kafka`

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1753]

**Comment by vahidhashemian** [comment]
A few more instances to clean up please:

- https://github.com/spring-projects/spring-kafka/blob/524f585e5e5ff17f81509d0689042fd85331f1b3/build.gradle#L36
- https://github.com/spring-projects/spring-kafka/blob/2580664545ea4baeb6eaadc6ed2030b53347bb69/src/api/overview.html#L9 (lines 8-9)
- https://github.com/spring-projects/spring-kafka/blob/2580664545ea4baeb6eaadc6ed2030b53347bb69/src/api/overview.html#L17
- https://github.com/spring-projects/spring-kafka/blob/2580664545ea4baeb6eaadc6ed2030b53347bb69/CONTRIBUTING.adoc#L3
- https://github.com/spring-projects/spring-kafka/blob/2580664545ea4baeb6eaadc6ed2030b53347bb69/spring-kafka/src/main/java/org/springframework/kafka/KafkaException.java#L25
- https://github.com/spring-projects/spring-kafka/blob/2580664545ea4baeb6eaadc6ed2030b53347bb69/spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java#L33

Thanks!

**Comment by garyrussell** [comment]
@vahidhashemian Done; thanks for pointing these out. 0fd1a384

**Comment by vahidhashemian** [comment]
Thanks a lot for the quick turnaround @garyrussell.
