### ISSUE TITLE
ContainerProperties from KafkaListenerContainerFactory are dropped

### ISSUE THREAD

**Issue by thomasmey** [spring-projects/spring-kafka#1770]
Hi,

I think the overwritten method here
https://github.com/spring-projects/spring-kafka/blob/1c798665050936d19934811198732c09ad98282f/spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java#L61
has a bug, as that it does *not* use the already existing container properties from super class org.springframework.kafka.config.AbstractKafkaListenerContainerFactory.containerProperties

So it basically drops any configuration like container clientId (!)

What do you think, bug or feature?

**Comment by garyrussell** [comment]
If that were the case, nothing would work.

The properties are copied in later; see

https://github.com/spring-projects/spring-kafka/blob/1c798665050936d19934811198732c09ad98282f/spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java#L402-L405

**Comment by thomasmey** [comment]
Hi,

mhh, I think I see now where the confusion comes from:

when I do:
``
        @Bean
        public ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory() {
                ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
                factory.getContainerProperties().setClientId("clientId");
                return factory;
        }
``
this can not work with the current code. the question is: should this (set a container client id programatically)?

makes sense?

**Comment by garyrussell** [comment]
Why do you say it "can not work"? It does work.

I tested it (again) when I answered this https://github.com/spring-projects/spring-kafka/issues/398#issuecomment-820414777

The only difference is I set it via a boot property `spring.kafka.consumer.client-id=foo`; before I added the clientIdPrefix to the annotations, I got the already exists exception.

**Comment by garyrussell** [comment]
The client Id comes from the endpoint (populated from the `@KafkaListener`) and overwrites the container properties, even if not set (which is a bug).

If you want to change it programmatically, use a container customizer instead...

```java
factory.setContainerCustomizer(container -> {
	container.getContainerProperties().setClientId("client-for-"
			+ container.getContainerProperties().getTopics()[0]);
});
```

**Comment by thomasmey** [comment]
> My apologies; I see it does NOT work in that case. Investigating...

No, worries. 
Thanks for looking into it 😃
