### ISSUE TITLE
RetryableTopic: improve customization of retry/dl topic names

### ISSUE THREAD

**Issue by apolci** [spring-projects/spring-kafka#1772]
**PROBLEM**

In our company we have a naming convention to distinguish "public" topics, meant for communication between different applications, and "private" topics, like retry and deadletter topics, meant to be used internally by an application. This convention mandate different prefixes for the names of those topics, and this is not possible with the current customization possibilities of RetryableTopic.

**SOLUTION**
The first possibility is to add a new "prefix" configuration property, to be handled in a similar way to the current suffix property. Probably easier to do, but in addition to increase the number of properties, doesn't give complete control on the different names (not only topic name) to the user.

Another approach is to move all the naming logic (specifically the logic of org.springframework.kafka.retrytopic.RetryTopicConfigurer.EndpointCustomizerFactory#createEndpointCustomizer) to an injected strategy bean that could be overridden in the configuration.

**Comment by tomazfernandes** [comment]
Hi @apolci, thanks a lot for bringing this up!

Thinking about what you're proposing, I do like the bean injection solution. I actually remember having a dedicated class for handling the topic naming part that was instantiated in the RetryTopicConfigurationBuilder and injected into the RetryTopicConfigurer, but I think at some point it looked not that useful. Looks like it was the wrong call!

Another approach that comes to mind might be if we changed the createEndpointCustomizer method to protected, and extracted EndpointCustomizer interface to its own separate / public file, and maybe the EndpointCustomizerFactory as well. This way we'd be able to override them with other implementations. I think we'd also need to change org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor#getRetryTopicConfigurer() to protected so we can override it and provide the new instance.

But I do like the bean injection solution better.

**Comment by apolci** [comment]
@tomazfernandes after your comment in (#1745) I started to work on this.
I extracted the code to a RetryTopicNamesProvider with it's associated factory (I would like to avoid this last one). Will improve in the next days and then make a PR.

**Comment by tomazfernandes** [comment]
Sounds great @apolci, looking forward to it!

**Comment by apolci** [comment]
Just a question: will this change be included in the next release (2.7.1)?

Thank you
