### ISSUE TITLE
KafkaTemplate constructor with configOverrides and Transaction

### ISSUE THREAD

**Issue by manolis-pi** [spring-projects/spring-kafka#1776]
**Affects Version(s):** 2.6.7

I believe there is an issue with the constructor 
KafkaTemplate​(ProducerFactory<K,​V> producerFactory, java.util.Map<java.lang.String,​java.lang.Object> configOverrides) 

When we want to pass a configOverridesa with a pair (ProducerConfig.TRANSACTIONAL_ID_CONFIG, "someTxId") the line
this.transactional = producerFactory.transactionCapable() 
is called before the merge of the configOverrides Map.

So, although (if configOverrides is not empty) a new ProducerFactory will be created with merged producer properties and the supplied one will be disregarded , the  supplied producerFactory has also to be setup  with a pair (ProducerConfig.TRANSACTIONAL_ID_CONFIG, "dummy-value").
So, maybe line 174 in the  source code of KafkaTemplate has to be the last line in the constructor.

**Comment by garyrussell** [comment]
Thanks for reporting. We obviously don't have a test case for that.

At least you have a work-around for now.
