### ISSUE TITLE
Handler disappearing from List<InvocableHandlerMethod> in DelegatingInvocableHandler.java

### ISSUE THREAD

**Issue by Sreedharchethanath** [spring-projects/spring-kafka#1780]
My application has 3 KafkaHandler methods . On application startup it detects these methods as in the List<InvocableHandlerMethod> handlers has all the 3 methods.

However while running unit tests after a certain period of time one of the handler disappears overtime

Other information :
1) Im running in debug mode but this issue occurs even when i skip all debug points as well
2) I see the below exception when running in debug mode
nested exception is org.apache.kafka.clients.consumer.CommitFailedException: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:350)
3) Version of spring-kafka is spring-kafka-2.5.10.RELEASE

**Comment by garyrussell** [comment]
This makes no sense; methods are detected during initialization; they can't "disappear" later.

When opening an issue like this, you need to provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) that exhibits this behavior; we can't guess what's going on from a textual description.

2. This simply means your listener is taking too long to process the records from the poll; you need to decrease `max.poll.records` or increase `max.poll.interval.ms`.

**Comment by Sreedharchethanath** [comment]
Apologies ! Shouldn’t have raised this as an issue rather a query on stack
overflow . I’ll  close this out tomorrow .

Thanks and regards
Sreedhar

**Comment by Sreedharchethanath** [comment]
This wasn't an issue . I had @KafkaListeners annotations configured in two classes (class A and class B) . Class B extends Class A. Class B had one KafkaHandler method and Class A had 2 methods
There were two instances of messagelisteners getting created and every time a test was run it was picking from one of these listeners which led me incorrectly deducing the first listener was getting removed
Fix was to have the @KafkaListener in the subclass . 
Apologies for the inconvenience.Closing the issue
