### ISSUE TITLE
Batch Listener Exponential Backoff configuration does not work anymore in 2.7.0

### ISSUE THREAD

**Issue by dataGeeek** [spring-projects/spring-kafka#1785]
**Affects Version(s):** \<2.7.0>

After updating from 2.6.0 to 2.7.0 our configuration for exponential backoff for a batch listener does not work anymore. 
We now observe more than 30 retries in 10 seconds instead of 4.
We could not find any hint in the documentation regarding breaking changes between 2.6.0 and 2.7.0 in that regard.

See our configuration and listener code:

```@Configuration
class KafkaConfiguration {
    @Bean
    fun seekToCurrentBatchErrorHandler(exponentialBackOff: ExponentialBackOff) =
        SeekToCurrentBatchErrorHandler().apply {
            setBackOff(exponentialBackOff)
        }
    @Bean
    fun exponentialBackoff(): ExponentialBackOff = ExponentialBackOff()
}


@KafkaListener(
        topics = ["topic"],
        groupId = "group-id"
    )
    fun listen(records: ConsumerRecords<String, String>) {
        // ...
    }

**Comment by garyrussell** [comment]
Thanks for reporting; it's a bug.
