### ISSUE TITLE
Use MessageConverter from spring messaging for content negotiation

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-kafka#1789]
It would be good to have a Kafka record converter that uses the Kafka headers and payload (per global serdes) but then delegates to Spring Messaging for the conversion to a type that matches the listener. Spring already has a `CompositeMessageConverter` that can handle some of the logic. As a user I would like to have some reasonable defaults and then simply  add beans of type MessageConverter to express my preferences.

**Comment by garyrussell** [comment]
Needs docs.
