### ISSUE TITLE
The example document for RecoveringBatchErrorHandler losts the return type in the method with annotation bean

### ISSUE THREAD

**Issue by zhfkt** [spring-projects/spring-kafka#1790]
**Affects Version(s):** 2.7.0

On https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka-docs/src/main/asciidoc/kafka.adoc , for the following code snippet.

```java
@Bean
public RecoveringBatchErrorHandler(KafkaTemplate<String, String> template) {
    DeadLetterPublishingRecoverer recoverer =
            new DeadLetterPublishingRecoverer(template);
    RecoveringBatchErrorHandler errorHandler =
            new RecoveringBatchErrorHandler(recoverer, new FixedBackOff(2L, 5000));
}
```

The example document for RecoveringBatchErrorHandler losts the return type in the method with annotation bean .

I think it may be corrected in the following:

```java
@Bean
public BatchErrorHandler RecoveringBatchErrorHandler(KafkaTemplate<String, String> template) {
    DeadLetterPublishingRecoverer recoverer =
            new DeadLetterPublishingRecoverer(template);
    RecoveringBatchErrorHandler errorHandler =
            new RecoveringBatchErrorHandler(recoverer, new FixedBackOff(2L, 5000));

    return errorHandler;

}

```

Thank you.

**Comment by artembilan** [comment]
I think the name of the name of that bean method is missed.
Probably better to have it like this: `public RecoveringBatchErrorHandler batchErrorHandler(KafkaTemplate<String, String> template) {`

Feel free to contribute the fix: https://github.com/spring-projects/spring-kafka/blob/main/CONTRIBUTING.adoc!

Thank you for catching that out and reporting!
