### ISSUE TITLE
Spring Kafka overriding custom header pattern and removes id from Producer Record Header

### ISSUE THREAD

**Issue by skkadium** [spring-projects/spring-kafka#1803]
Apologies for the uncertainty. Please find below the issue in detail:

**Requirement:**
The application must generate a Spring Message<T> object including `id `as header and send the message to Kafka Topic. We have used Spring Cloud Streams to integrate the application with Kafka.

**Expected Output** 
The consumer application that consumes message from the Kakfa Topic must be able to read the message headers `id` and validate if the value of the header is same as Kafka Producer Record Key.

**Actual Output**
The consumer application that consumes message from the Kafka Topic is always receiving the header `id `value as "None".

**Customization**
To avoid unwanted headers like `spring_json_header_types` generated along with custom headers by the default mapper class i.e. `BinderHeaderMapper` and override the default header patterns to allow `id`, a custom header mapper is implemented.

```
@Slf4j
public class CustomKafkaHeaderMapper extends AbstractKafkaHeaderMapper {

  private final ObjectMapper objectMapper;

  public CustomKafkaHeaderMapper(String... patterns) {
    super(patterns);
    this.objectMapper = new ObjectMapper();
    this.objectMapper.registerModule(
        (new SimpleModule())
            .addDeserializer(
                MimeType.class, new CustomKafkaHeaderMapper.MimeTypeJsonDeserializer()));
  }

  @Override
  public void fromHeaders(MessageHeaders messageHeaders, Headers target) {
    messageHeaders.forEach(
        (key, value) -> {
          if (!KafkaHeaders.DELIVERY_ATTEMPT.equals(key) && this.matches(key, value)) {
            Object valueToAdd = this.headerValueToAddOut(key, value);
            if (valueToAdd instanceof byte[]) {
              target.add(new RecordHeader(key, (byte[]) valueToAdd));
            } else if (valueToAdd instanceof String) {
              target.add(new RecordHeader(key, ((String) valueToAdd).getBytes(this.getCharset())));
            } else {
              try {
                target.add(new RecordHeader(key, new ObjectMapper().writeValueAsBytes(valueToAdd)));
              } catch (JsonProcessingException e) {
                logger.error(
                    e,
                    () -> "Could not map " + key + " with type " + value.getClass().getName()
                    );
              }
            }
          }
        });
  }

  @Override
  public void toHeaders(Headers source, Map<String, Object> target) {
    source.forEach(
        header -> {
          if (KafkaHeaders.DELIVERY_ATTEMPT.equals(header.key())) {
            target.put(header.key(), ByteBuffer.wrap(header.value()).getInt());
          } else {
            target.put(header.key(), new String(header.value(), this.getCharset()));
          }
        });
  }

  private class MimeTypeJsonDeserializer extends StdNodeBasedDeserializer<MimeType> {
    private static final long serialVersionUID = 1L;

    MimeTypeJsonDeserializer() {
      super(MimeType.class);
    }

    public MimeType convert(JsonNode root, DeserializationContext ctxt) throws IOException {
      if (root instanceof TextNode) {
        return MimeType.valueOf(root.asText());
      } else {
        JsonNode type = root.get("type");
        JsonNode subType = root.get("subtype");
        JsonNode parameters = root.get("parameters");
        Map<String, String> params =
            (Map)
                CustomKafkaHeaderMapper.this.objectMapper.readValue(
                    parameters.traverse(),
                    TypeFactory.defaultInstance()
                        .constructMapType(HashMap.class, String.class, String.class));
        return new MimeType(type.asText(), subType.asText(), params);
      }
    }
  }
}

```

This `customHeaderMapper` bean name is configured to the Binder properties as mentioned below:
`spring.cloud.stream.kafka.binder.headerMapperBeanName=customKafkaHeaderMapper
`

**Analysis**
I thought the Custom Header Mapper will serve the purpose and set the `id `header in the Kafka Producer Record. But in my initial analysis, I observed that

- The custom header mapper bean is captured and configured to be used in the code below inside `KafkaMessageChannelBinder` class `createProducerMessageHandler `method.

```
final KafkaHeaderMapper mapper = null;
    if (this.configurationProperties.getHeaderMapperBeanName() != null) {
      mapper = (KafkaHeaderMapper)applicationContext.getBean(this.configurationProperties.getHeaderMapperBeanName(), KafkaHeaderMapper.class);
    }
```
But at the end of this method, the handler is set to a new KafkaHeaderMapper object that uses the custom header mapper to map spring message headers.

```
final KafkaHeaderMapper mapper = null;
    if (this.configurationProperties.getHeaderMapperBeanName() != null) {
      mapper = (KafkaHeaderMapper)applicationContext.getBean(this.configurationProperties.getHeaderMapperBeanName(), KafkaHeaderMapper.class);
    }

    if (mapper == null) {
      try {
        mapper = (KafkaHeaderMapper)applicationContext.getBean("kafkaBinderHeaderMapper", KafkaHeaderMapper.class);
      } catch (BeansException var14) {
      }
    }

    Object mapper;
    if (producerProperties.getHeaderMode() != null && !HeaderMode.headers.equals(producerProperties.getHeaderMode())) {
      mapper = null;
    } else if (mapper == null) {
      String[] headerPatterns = ((KafkaProducerProperties)producerProperties.getExtension()).getHeaderPatterns();
      if (headerPatterns != null && headerPatterns.length > 0) {
        mapper = new BinderHeaderMapper(BinderHeaderMapper.addNeverHeaderPatterns(Arrays.asList(headerPatterns)));
      } else {
        mapper = new BinderHeaderMapper();
      }
    } else {
      mapper = new KafkaHeaderMapper() {
        public void toHeaders(Headers source, Map<String, Object> target) {
          mapper.toHeaders(source, target);
        }

        public void fromHeaders(MessageHeaders headers, Headers target) {
          mapper.fromHeaders(headers, target);
          BinderHeaderMapper.removeNeverHeaders(target);
        }
      };
    }

    handler.setHeaderMapper((KafkaHeaderMapper)mapper);
```
If it can be observed inside the `fromHeaders` method of the above code, the `mapper` is the custom header mapper instance that is mapping the spring message headers to the `Apache Kafka Headers`. Till here, I can see the `id` header entry available in the `Apache Kafka Headers`. Post that the `BinderHeaderMapper's` `removeNeverHeaders `is invoked by passing the Apache Kafka Headers to explicitly remove the `id `header from the record.

```
public static void removeNeverHeaders(Headers headers) {
    headers.remove("id");
    headers.remove("timestamp");
    headers.remove("deliveryAttempt");
    headers.remove("scst_nativeHeadersPresent");
  }
```

As per my analysis, even if my application sets the a simple Spring Message with `id `header, before the message is written to the Kafka topic, the above code is removing the 'id' header from the Apache Kafka Headers and  the id value is deserialized as 'None' by the consumer.

I would like to know, if there is a way to avoid the removal of the `id `header from the Kafka Producer Record Headers as per our project requirement.

Please let me know, if you need further information.

**Comment by artembilan** [comment]
First of all it sounds more like Spring Cloud Stream Kafka Binder question: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka.

Secondly the `id` header is auto-generated (in most cases) by the framework as an `UUID` for every single new message instance. It is probably not so good to make your business logic to rely on such an internal header. So, please, consider to map against some other custom headers which definitely not going to be removed silently for you. And probably there won't be a need in any fixes in the framework and no need for any custom code on your side.

**Comment by garyrussell** [comment]
`id` and `timestamp` are reserved spring-messaging headers and are not available for user values.

**Comment by arronharden-els** [comment]
I'm working with @skkadium on the project where we're encountering a problem with this, so thought I'd add a bit more context.

We're writing a couple of new components which are integrating with an existing system and Kafka deployment, which already has definitions around what should be set in headers and so on (the presence of an `id` header being one of these definitions). The existing system is heterogeneous in nature, having components connecting to the Kafka instance written in various different languages and frameworks. As far as I know these other components are able to meet the definitions for Kafka events without much issue. Asking everyone to switch to using a header other than `id` will be hard sell.

With regard to the `id` header itself, we don't particularly need the ability to set a value of our choosing, we'd happy if it were generated automatically on our behalf, so long as we have the ability to get the value generated.

**Comment by garyrussell** [comment]
There is nothing preventing you using `id` externally, you just can't use it within the the Spring application. It is reserved; even if it was mapped, it changes each time the message is mutated within the app, so i won't meet your requirements anyway.

You need a custom header mapper that maps it to something else (e.g. `myCompany_id`) inbound, and back to `id` outbound.

**Comment by skkadium** [comment]
Hey @garyrussell ,

We're already making use of a custom header mapper that maps headers from and to Apache Headers. As mentioned in the post, even with the custom header mapper, when I set the `id` header for the outbound message, the below code explicitly removes the header while mapping the `MessageHeaders `to `ApacheKafkaHeaders`. Please have a look at the fromHeaders method below. The `BinderHeaderMapper's `static method `removeNeverHeaders `is invoked to remove the `id `header.

_KafkaMessageChannelBinder.class_

```
mapper = new KafkaHeaderMapper() {
        public void toHeaders(Headers source, Map<String, Object> target) {
          mapper.toHeaders(source, target);
        }

        public void fromHeaders(MessageHeaders headers, Headers target) {
          mapper.fromHeaders(headers, target);
          BinderHeaderMapper.removeNeverHeaders(target);
        }
      };
```

**Comment by garyrussell** [comment]
Oh, I see.

However, (unrelated to this project), you can add a `ProducerMessageHandlerCustomizer` bean in Spring Cloud Stream and completely replace that header mapper with your own.

I do suggest you remove those other headers (except `id`) though.

**Comment by skkadium** [comment]
@garyrussell Thanks for the suggestion. It worked and now the Kafka Topic is written with message that includes `id `as one of the headers.
