### ISSUE TITLE
EmbeddedKafkaBroker is not destroy between test class when spring-test context changes

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-kafka#1805]
Hi,

I have found a bit of an insidious issue where the `EmbeddedKafkaBroker` is not properly destroy and as such does not release its port. This is issue is found in JUnit5 tests having a spring context. It can be reproduce in this small project: 
[spring-kafka.zip](https://github.com/spring-projects/spring-kafka/files/6506804/spring-kafka.zip). Launching a `./gradlew build` will launch two test classes, with the second one failing because of a `java.net.BindException: Address already in use`.

What happens is that one of the test class configures the spring cache while the other does not (with `@AutoConfigureCache`). Having this additional configuration forces a refresh of the spring-test context when starting the second test class and thus call a second time `EmbeddedKafkaContextCustomizer#customizeContext`. However after the first test ended the `EmbeddedKafkaBroker` bean was not destroy because it was cached.

I am not certain whether this should be an issue in spring-test or in spring-kafka, since having a `DisposableBean` bean not being destroyed before refreshing the cache is a bit insidious and error-prone.

As a temporary solution I destroy the bean manually in an `@AfterAll`:
```
  @AfterAll
  static void afterAll(@Autowired ApplicationContext applicationContext) {
    EmbeddedKafkaBroker embeddedKafkaBroker = applicationContext.getBean(EmbeddedKafkaBroker.class);
    embeddedKafkaBroker.destroy();
  }
```

**Comment by garyrussell** [comment]
Simply add `@DirtiesContext` to the test class and the context will be destroyed - just destroying the broker is not enough, you want all listener containers to shut down too.

**Comment by celcius112** [comment]
I usually prefer not to use `@DirtiesContext` whenever possible. If it is necessary here, then so be it.

**Comment by garyrussell** [comment]
Understood, the problem with "live" components, such as listener containers, we need to shut them down - otherwise, with large test suites, you end up with a lot of unecessary memory and/or cpu use.
