### ISSUE TITLE
EmbeddedKafkaBroker cannot be injected in tests with spring-test context

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-kafka#1806]
In a JUnit 5 test using a spring-test context, it is not possible to autowire the `EmbeddedKafkaBroker` because there is a resolution clash between `EmbeddedKafkaCondition`'s and `SpringExtension`'s parameter resolution.

For instance:
```
@EmbeddedKafka(partitions = 1, brokerProperties = "listeners=PLAINTEXT://localhost:9092")
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class MyTest {
  @AfterAll
  static void afterAll(@Autowired EmbeddedKafkaBroker embeddedKafkaBroker) {
    embeddedKafkaBroker.destroy();
  }
}
```
will fail with error:
```
org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing ParameterResolvers for parameter [org.springframework.kafka.test.EmbeddedKafkaBroker embeddedKafkaBroker] in method [static void fr.bpifrance.notification.AbstractKafkaIT.afterAll(org.springframework.kafka.test.EmbeddedKafkaBroker)]: org.springframework.kafka.test.condition.EmbeddedKafkaCondition@f2bee8dd, org.springframework.test.context.junit.jupiter.SpringExtension@5562e7c1
```

**Comment by celcius112** [comment]
As for `EmbeddedKafkaCondition` it is unfortunately automatically involved because of `@EmbeddedKafka`. In summary:
- `@EmbeddedKafka` applies `EmbeddedKafkaCondition` who understands the type `EmbeddedKafkaBroker`
- `@SpringBootTest` applies `SpringExtension` who understands a type annotated by `@Autowired`

Since both extensions will understand the parameter we are trying to resolve JUnit 5 will force the failure.

**Comment by garyrussell** [comment]
>I don't think being `static` is important for JUnit's parameter resolution.

Correct - we (I) just didn't anticipate someone doing something like this; as I said in the other issue, shutting down the broker is not enough; the test listener containers need to be shut down too.

In any case, using `@Autowired` in a static method is just not appropriate.

**Comment by celcius112** [comment]
Ok let's forget about my example 😛. 
A non-static method in a spring-test context, like a `@Test` or `@BeforeEach`, will also not be able to inject the broker by parameter.

**Comment by garyrussell** [comment]
>... will also not be able to inject the broker by parameter.

Good point, if you leave off `@Autowired`, the parameter won't be considered by `SpringExtension` because it  only considers parameters so annotated (unless you change the default auto wire mode on a `@TestConstructor` or via a property. However, then, the `EmbeddedKafkaCondition` won't resolve it either, because instead of creating a broker in the condition, it leaves it to the `@EmbeddedKafkaBroker` to register it with application context instead.

We need to fix `supportsParameter()` to return false if the condition does not, itself, create a broker.
