### ISSUE TITLE
KafkaTemplate.send(...) does not invoke FailureCallback when broker is down

### ISSUE THREAD

**Issue by uklance** [spring-projects/spring-kafka#1807]
**Affects Version(s):** org.springframework.kafka:spring-kafka:2.6.5

🐞 Bug report
I have the following code
```
public static void main(String[] args) {
  Map<String, Object> configProps = Map.of(BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");,
  Serializer<String> keySerializer = new StringSerializer();
  Serializer<String> valueSerializer = new StringSerializer();
  ProducerFactory<String, Email> producerFactory = new DefaultKafkaProducerFactory<>(configProps, keySerializer, valueSerializer);
  KafkaTemplate<String, String> template = new KafkaTemplate<>(producerFactory);
  for (int i = 0; i < 1000; ++i) {
     Thread.sleep(10_000);
     String value = String.valueOf(i);
     ProducerRecord<String, String> record = new ProducerRecord<>("my-topic", value, value);
     ListenableFuture<SendResult<String, String>> future  = template.send(record);
     future.addCallback(this::successCallback, exception -> failureCallback(value, exception));
  }
}

private void successCallback(SendResult<String, String> sendResult) {
  String value = sendResult.getProducerRecord().value();
  System.out.println("Send success value=" + value);
}

private void failureCallback(String value, Throwable exception) {
  System.out.println(String.format("Send error value=%s exception=%s", value, exception);
}
```

**Steps to reproduce**
1. Start zookeeper on localhost
2. Start kafka on localhost:9092
3. Run the main above
4. After 20 seconds (or so) stop the kafka broker

**Expected Results**
- `successCallback(...)` should be invoked for every message sent to kafka whilst the broker is running
- `failureCallback(...)` should be invoked for every message sent to kafka whilst the broker is stopped

**Actual Results**
- `successCallback(...)` is invoked for every message sent to kafka whilst the broker is running
- `failureCallback(...)` is not invoked whilst the broker is stopped, there is no way of handling these errors using `KafkaTemplate`

**Workaround**
If I use the core kafka client classes (not the spring wrapper) it works as expected. If I change the code above to use `KafkaProducer.send(ProducerRecord<K, V> record, Callback callback)` then I receive the exception as expected (the exception is a `org.apache.kafka.common.errors.TimeoutException`)

**Thoughts**
I think it's weird how spring-kafka forces me to register the callback (via `ListenableFuture.addCallback(...)`) after I call `KafkaTemplate.send(...)`. I'd like to pass the callback to the `send(...)` method (same as `KafkaProducer`) but the `KafkaTemplate` wrapper does not allow me to do this as far as I can see. It's possible there's a timing issue since the callback is registered after `send(...)`.

**Comment by garyrussell** [comment]
There is no timing issue. The listenable future will call the callback during the `add...` if the future is already completed (normally, or exceptionally).

I just tested it and it worked fine for me...

```java
@SpringBootApplication
public class Kgh1807Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh1807Application.class, args);
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> {
			for (int i = 0; i < 1000; i++) {
				Thread.sleep(1000);
				ListenableFuture<SendResult<String, String>> future = template.send("kgh1807", "test");
				future.addCallback(sr -> System.out.println(sr.getRecordMetadata()),
						ex -> ex.printStackTrace());
			}
		};
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("kgh1807").partitions(1).replicas(1).build();
	}

}
```
```
kgh1807-0@0
kgh1807-0@1
kgh1807-0@2
kgh1807-0@3
kgh1807-0@4
kgh1807-0@5
kgh1807-0@6
2021-05-24 13:17:23.324 ... Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
...
2021-05-24 13:19:23.117... Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Expiring 120 record(s) for kgh1807-0:120002 ms has passed since batch creation
	at org.springframework.kafka.core.KafkaTemplate.lambda$buildCallback$4(KafkaTemplate.java:620)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer$1.onCompletion(DefaultKafkaProducerFactory.java:872)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1366)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:231)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:197)
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:690)
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:381)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:324)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:240)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 120 record(s) for kgh1807-0:120002 ms has passed since batch creation
...
```
Notice that the exceptions start 120 seconds after the first failed send (due to the `delivery.timeout.ms` default.

**Comment by uklance** [comment]
Are you using `spring-kafka:2.6.5`?

I'll try to create a minimal reproducible project when I get some time, I've definitely seen this behaviour and switching from KafkaTemplate to KafkaProducer allowed me to handle the exception.

> Notice that the exceptions start 120 seconds after the first failed send

Yes, I've seen this behaviour too. I think I was actually seeing the exceptions in the logs (via slf4j) but they weren't being passed back to my handler. I left it running for 10 minutes or so.

**Comment by garyrussell** [comment]
I am using 2.7.1 but nothing has changed in this area for years.

**Comment by garyrussell** [comment]
If the broker is down, the `send()` itself will throw a `TimeoutException` after the `max.block.ms` (default 60 seconds) due to failure to obtain metadata.

The callback is only called if the send is started, but an error is returned by the broker.

The `send()` needs to be in a `try/catch` block because other exceptions can be thrown there too, such as `RecordTooLargeException`.
