### ISSUE TITLE
Wrong nullability annotations produce static code analysis errors

### ISSUE THREAD

**Issue by reitzmichnicht** [spring-projects/spring-kafka#1825]
Using latest spring-kafka produces some static analysis errors due to wrong annotations. For example in
https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
the method getListenerContainer can return null as documented, but on package level the annotation @org.springframework.lang.NonNullApi lets analyzers expect that the method cannot return null values.
It would be great if the nullability annotations are used correctly or removed instead.

Kind regards,
Michael

**Comment by garyrussell** [comment]
Thanks for pointing out this error; let us know if you see others (and contributions are also welcome).

**Comment by reitzmichnicht** [comment]
Thank you very much for the quick fix.
