### ISSUE TITLE
There is no easy way to set up the order of listening to topics

### ISSUE THREAD

**Issue by BOOMeranGG** [spring-projects/spring-kafka#1827]
I used spring-kafka in my work, and I had a need to configure the order of starting listening to topics. I mean, start listening to topic B only after all the messages from topic A have been processed.
At the moment, there is no easy way to do this (like setting up the order in @KafkaListener). Please correct me if I'm wrong.

If you think that this functionality is worth implementing, I can try to do it.

**Comment by garyrussell** [comment]
You can add 2 `@KafkaListener` annotations; set the one for topic B `autoStartup = "false"`.

For the first container enable idle container events and add an event listener.

When the first container goes idle, in the event listener, stop the first container and start the second one.

**Comment by BOOMeranGG** [comment]
Yes, I have implemented as you wrote. But it becomes not so convenient when there are several such dependencies. Topic A is waiting for B, C, D, topic E is waiting for F and G, e.t.c.
Recently I had to implement this for the second time, and I think it would be convenient to specify in @KafkaListener.
For example `initializationOrder=2`, and the topic will start only when other topics with `initializationOrder=1` finish receiving data.

**Comment by garyrussell** [comment]
We already have a property `containerGroup`; I think a new component would be simpler, and easier to configure/understand. Something like this...

```java
/**
 * Sequence the starting of container groups when all containers in the previous group are
 * idle.
 *
 * @author Gary Russell
 * @since 2.8
 *
 */
public abstract class ContainerGroupSequencer {

	/**
	 * Set containers in each group to not auto start. Start the containers in the first
	 * group. Start containers in group[n] when all containers in group[n-1] are idle;
	 * stop the containers in group[n-1].
	 * @param registry the registry.
	 * @param defaultIdleEventInterval the idle event interval if not already set.
	 * @param containerGroups The list of container groups, in order.
	 */
	public ContainerGroupSequencer(KafkaListenerEndpointRegistry registry, long defaultIdleEventInterval,
			String... containerGroups) {

		// ...
	}

}
```

**Comment by BOOMeranGG** [comment]
Спасибо! Это похоже на то, что мне нужно

**Comment by garyrussell** [comment]
I created a PR; sorry, I didn't notice your comment about submitting a change.

It turned out to be a bit more complicated than I thought it would be due to some initialization timing issues.
