### ISSUE TITLE
old connections are not closed after changing bootstraps.servers list by calling DefaultKafkaProducerFactory's updateConfigs 

### ISSUE THREAD

**Issue by zrlw** [spring-projects/spring-kafka#1839]
**Affects Version(s):**  2.7.2

after changing bootstraps.servers list by calling DefaultKafkaProducerFactory's updateConfigs, the connections with the old bootstraps.servers list are still existed.

**Expected**
reset the  producer and clear the cache of the transactional if changing bootstraps.servers list.

**Comment by garyrussell** [comment]
You need to call `reset()` on the factory to close the existing producers.
