### ISSUE TITLE
Partitions  are not created on @KafkaListener Annotation

### ISSUE THREAD

**Issue by z0mb1ek** [spring-projects/spring-kafka#184]
I have 0.10 version on Kafka and write code like:
`@KafkaListener(id = "bar", topicPartitions =`
`{@TopicPartition(topic = "queue", partitions = {"0", "1"})}, group = "test")`
`public void listen(ConsumerRecord<?, ?> record) {`
`}`

but it create only "0" partition. I test 1.0.3 and 1.1.0 M2 versions.

**Comment by artembilan** [comment]
What do you mean with "create"?
The `@KafkaListener` doesn't create partitions on Topic. They must be created in advance there.
`@KafkaListener` just listens to them according provided configuration.

Would be great to see some test-case to play locally.
The big issue that we are going to release `1.1 GA` today, so, please, be responsive as much as possible.

Thanks

**Comment by mbogoevici** [comment]
What you see is the effect of `auto.create.topics.enable=true` on the broker with the default `num.partitions=1`.

**Comment by z0mb1ek** [comment]
@artembilan 
Than i create listener without params it create one partition and topic. And thats why i thought that params will create it for me. Should I user some admin class like rabbit mq?

**Comment by artembilan** [comment]
Well, we use `AdminUtils.createTopic()` from the `kafka_2.11-0.10.0.1.jar` in our tests with the `KafkaEmbedded` abstraction.

**Comment by z0mb1ek** [comment]
I think you should write some tips in the documentation.

**Comment by artembilan** [comment]
@z0mb1ek , 

Please, be more specific. What you would like to see as an explanation in docs?

Thanks

**Comment by z0mb1ek** [comment]
I want to see that I must go to apache java libs and searching that big code for create just topic. I think that spring could do it for me.

**Comment by garyrussell** [comment]
Can you point us to where the current documentation implies that spring-kafka gets involved with creating topics?

The `@TopicPartition` annotation is use to specify which partitions you want to listen to (when not using broker-assigned partitions).

The 0.9.x.x and later client libraries are pure Java and don't provide a mechanism to create topics; that requires adding scala jars to the classpath.

I doubt that spring-kafka will provide support for creating topics until (if ever) a pure java client would support doing so.

We can certainly add a comment to the documentation to that effect, but I am unsure what led you to the conclusion that it does.

Spring AMQP (for RabbitMQ) has specific documentation as to how to configure it to create queues/exchanges/bindings - it does nothing by default.

**Comment by garyrussell** [comment]
Closed with no response.
