### ISSUE TITLE
Add receive() Operation to KafkaTemplate

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1861]
Fetch a specific record.

**Comment by saagar2000** [comment]
do we have plan to support receive for multiple topic/partition/offsets ? I  would be happy to contribute.

**Comment by garyrussell** [comment]
Do you mean fetch several records in one operation?

We don't have plans to do so, but feel free to submit a PR (we can reopen this issue).

**Comment by saagar2000** [comment]
yes - fetch several records across different topics - okay  I will try to work on it. Thank you

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-kafka/issues/1948
