### ISSUE TITLE
How to configure errorHandler when using @RetryableTopic

### ISSUE THREAD

**Issue by TheLeftHandOfGod** [spring-projects/spring-kafka#1863]
When I use **@RetryableTopic**, the **errorHandler** configuration of **@KafkaListener** does not take effect and is replaced with **SeekToCurrentErrorHandler**, I want to print the error stack trace. How should I configure?

```
@RetryableTopic(
        attempts = "2",
        backoff = @Backoff(delay = 1000L, multiplier = 2.0),
        topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_INDEX_VALUE,
        fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC,
        listenerContainerFactory = "retryKafkaListenerContainerFactory"
)
@KafkaListener(
        topics = TOPIC_ENTERPRISE,
        clientIdPrefix = "enterprise",
        containerFactory = "kafkaListenerContainerFactory",
        errorHandler = "customKafkaListenerErrorHandler"
)
public void enterpriseConsumer(ConsumerRecord<Long, String> record) {
    LOGGER.info("{} - topoc:{}, part: {}, offset: {}， key: {}, value: {}", Thread.currentThread().getName(), record.topic(), record.partition(), record.offset(), record.key(), record.value());
    int i = 1 / 0;
}
```

**Comment by garyrussell** [comment]
It's a bug; the error handler is not set up when it's retryable. 

It's not actually replaced; the STCEH is a container error handler used to handle the retries. The `errorHandler` is a `KafkaListenerErrorHandler` and it is (incorrectly) ignored.

The KLEH must re-throw the exception to make the retries work.

Thanks for reporting.

**Comment by h0riz4n** [comment]
Sorry, but now is it possible to configure ur errorHandler using RetryableTopic annotation?

**Comment by artembilan** [comment]
See `@KafkaListener(errorHandler)`.
This test demonstrate such a feature: https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java#L328

**Comment by h0riz4n** [comment]
> See `@KafkaListener(errorHandler)`. This test demonstrate such a feature: https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java#L328

Yes, I have this one variant, but when I throwing errors in my errorHandler then @RetryableTopic annotation takes this and throwing full stacktrace in console and I want to log error by my self without stacktrace

**Comment by artembilan** [comment]
There is option like this:
```
			@Override
			protected void configureCustomizers(CustomizersConfigurer customizersConfigurer) {
				customizersConfigurer
						.customizeDeadLetterPublishingRecoverer(dlprCustomizer)
						.customizeListenerContainer(listenerContainerCustomizer)
						.customizeErrorHandler(errorHandlerCustomizer);
			}
```
on the `RetryTopicConfigurationSupport`.
In that `errorHandlerCustomizer` you can do `errorHandler.setLogLevel(KafkaException.Level.ERROR);` to lose that debug by default.

This part of documentation how to configure that `Support`: https://docs.spring.io/spring-kafka/reference/retrytopic/retry-config.html#retry-topic-global-settings

**Comment by h0riz4n** [comment]
![image](https://github.com/spring-projects/spring-kafka/assets/96946731/b3c46665-06fb-46e5-9e78-ff463625a566)
I apologize for my stupidity, but no matter how I work with the configs, I still get this stacktrace, I want just log exception message

**Comment by artembilan** [comment]
Thanks for sharing stacktrace!

Now I see where it is:
```
		if (nextDestination.isDltTopic()
				&& !ListenerExceptionLoggingStrategy.NEVER.equals(this.loggingStrategy)) {
			LOGGER.error(e, () -> getErrorMessage(cr) + " and won't be retried. "
					+ "Sending to DLT with name " + nextDestination.getDestinationName() + ".");
		}
```
So, apparently we can configure that `loggingStrategy` to `ListenerExceptionLoggingStrategy.NEVER`.

See same `RetryTopicConfigurationSupport`:

```
		@Override
		protected Consumer<DeadLetterPublishingRecovererFactory> configureDeadLetterPublishingContainerFactory() {
			return DeadLetterPublishingRecovererFactory::neverLogListenerException;
		}
```

**Comment by h0riz4n** [comment]
Thank u!
U really helped me, this works!

**Comment by sinankivanc3131** [comment]
@artembilan @h0riz4n so is it possible to use custom ConsumerRecordRecoverer with non-blocking retries?
