### ISSUE TITLE
The settings of the properties field have the same problem, and SpEL expressions cannot solve it

### ISSUE THREAD

**Issue by linchutao** [spring-projects/spring-kafka#1880]
**Affects Version(s):** \<Spring for Apache Kafka version>

**Comment by linchutao** [comment]
[https://github.com/spring-projects/spring-kafka/issues/361#issue-240745473](Enabling @KafkaListener to take in variable topic names from application.yml)

**Comment by linchutao** [comment]
[Enabling @KafkaListener to take in variable topic names from application.yml file](https://github.com/spring-projects/spring-kafka/issues/361)

**Comment by linchutao** [comment]
#361

**Comment by artembilan** [comment]
I'm sorry what is the problem? Can you be, please, more specific?
Otherwise this looks like `Invalid` and will be closed respectively.

Thank you for understanding!

**Comment by linchutao** [comment]
Sorry, let me show you a demo

`@KafkaListener(groupId = "my-group", topics = "#{'${consumer-config.topics}'.split(',')}", properties = "#{'${consumer-config.properties}'.split(',')}")`

with

`consumer-config:
  topics: topic1,topic2
  properties: max.poll.records:100,group.instance.id:instance1`

properties cannot be processed normally like topics，I noticed that the processing of properties in the source code is not the same as topics

**Comment by garyrussell** [comment]
Unlike the other properties that support SpEL, there is no mention of `SpEL` in the javadocs for properties.

```java
	/**
	 * Kafka consumer properties; they will supersede any properties with the same name
	 * defined in the consumer factory (if the consumer factory supports property overrides).
	 * <p>
	 * <b>Supported Syntax</b>
	 * <p>The supported syntax for key-value pairs is the same as the
	 * syntax defined for entries in a Java
	 * {@linkplain java.util.Properties#load(java.io.Reader) properties file}:
	 * <ul>
	 * <li>{@code key=value}</li>
	 * <li>{@code key:value}</li>
	 * <li>{@code key value}</li>
	 * </ul>
	 * {@code group.id} and {@code client.id} are ignored.
	 * @return the properties.
	 * @since 2.2.4
	 * @see org.apache.kafka.clients.consumer.ConsumerConfig
	 * @see #groupId()
	 * @see #clientIdPrefix()
	 */
	String[] properties() default {};
```

Vs

```java
	/**
	 * The topics for this listener.
	 * The entries can be 'topic name', 'property-placeholder keys' or 'expressions'.
	 * An expression must be resolved to the topic name.
	 * This uses group management and Kafka will assign partitions to group members.
	 * <p>
	 * Mutually exclusive with {@link #topicPattern()} and {@link #topicPartitions()}.
	 * @return the topic names or expressions (SpEL) to listen to.
	 */
	String[] topics() default {};
```

This would be a new feature.

**Comment by linchutao** [comment]
Thanks @garyrussell , This is how I deal with it now
`@KafkaListener(groupId = "my-group", topics = "#{'${consumer-config.topics}'.split(',')}", properties = {"max.poll.records:" + "${consumer-config.properties.max.poll.records}", "group.instance.id:" + "${consumer-config.properties.group.instance.id}",})`

with

```
consumer-config:
  topics: topic1,topic2
  properties:
    max.poll.records: 100
    group.instance.id: instance1
```
It works, but the configuration looks a little cumbersome

**Comment by garyrussell** [comment]
Understood; this is a reasonable new feature request.

**Comment by garyrussell** [comment]
@linchutao I have implemented the change, but FYI, this works with current versions:

```properties
some.prop=max.poll.records: 10\nfetch.min.bytes: 123456
```
or
```properties
some.prop=max.poll.records: 10\n \
 fetch.min.bytes: 123456
```
```java
	@KafkaListener(id = "kgh1880", topics = "kgh1880", autoStartup = "false",
			properties = "${some.prop}")
```

i.e. insert a newline between properties

**Comment by garyrussell** [comment]
```yaml
some:
  prop: |
    max.poll.records: 10
    fetch.min.bytes: 123456
```

**Comment by linchutao** [comment]
Thanks @garyrussell , It looks much more comfortable.
