### ISSUE TITLE
KafkaHeaders.DLT_EXCEPTION_FQCN is always a KafkaListenerExecutionException

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-kafka#1882]
When using the dead letter recoverer, KafkaHeaders.DLT_EXCEPTION_FQCN is almost always a KafkaListenerExecutionException. This makes the header less helpful than it could be. Is there any way we can add a header for the cause of the exception?

**Comment by garyrussell** [comment]
This is a reasonable request; you can, however, see the cause in the stack trace header.
