### ISSUE TITLE
There is no any description about @EnableKafka

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-kafka#189]
http://stackoverflow.com/questions/39903880/spring-integration-kafka-consumer-listener-not-recoeiving-messages

Looks like `@EnableKafka` is going to have a bad story like `@EnableIntegration` before :smile:

**Comment by garyrussell** [comment]
`@KafkaListener` javadocs have it but, yes, it should be in the book too...

```
 * <p>
 * Processing of {@code @KafkaListener} annotations is performed by registering a
 * {@link KafkaListenerAnnotationBeanPostProcessor}. This can be done manually or, more
 * conveniently, through {@link EnableKafka} annotation.
```
