### ISSUE TITLE
StreamsBuilderFactoryBean#start blocks Spring application startup with large global stores

### ISSUE THREAD

**Issue by denisw** [spring-projects/spring-kafka#1899]
**Affects Version(s):**  All

`StreamsBuilderFactoryBean#start` calls the `KafkaStreams` instance's `start()` method directly on the main thread. This is usually no problem as `KafkaStreams#start` to be _mostly_ non-blocking. However, the method _does_ block until all global state stores have been fully restored:

https://issues.apache.org/jira/browse/KAFKA-7380

This means that if the Kafka Streams application has large global state stores, `StreamsBuilderFactoryBean#start` may block the Spring application startup for several minutes. In our case, not even Netty and Actuator is started in this timeframe, which leads to our application being repeatedly killed by our Kubernetes cluster because the liveness probe is not reachable.

Perhaps Spring Kafka could work around this issue by running `KafkaStreams#start` in a separate thread.

**Comment by artembilan** [comment]
We may reconsider the behavior as you suggest, but of course better to have a normal fix from the upstream Kafka Streams library.
Meanwhile as a workaround I would suggest to have that `StreamsBuilderFactoryBean` in a `setAutoStartup(false)` in the config and call its start manually somewhere later when an application is ready already, e.g. listening for the `ApplicationReadyEvent` or implement an `ApplicationRunner` instead. This way those liveness probes should be OK and you may control what thread to use to start that `StreamsBuilderFactoryBean` on background.

**Comment by garyrussell** [comment]
Specifically, with Spring Boot:

```properties
spring.kafka.streams.auto-startup=false
```

```java
@Bean
public ApplicationRunner runner1(StreamsBuilderFactoryBean sbfb) {
	return args -> {
		sbfb.start();
	};
}
```

**Comment by denisw** [comment]
Hi,

Thank you for the suggested workaround. Unfortunately, we don't use Spring Kafka directly, but via Spring Cloud Stream, which calls `start()` of each `StreamsBuilderFactoryBean` on its own and doesn't seem to offer any customization on this matter.

**Comment by garyrussell** [comment]
With the other binders, you could set the binding `autoStartup` property to `false` and start the binding manually from your code but, unfortunately, the Kafka Streams binder does not currently support the `autoStartup` property.

cc/ @sobychacko

**Comment by garyrussell** [comment]
`StreamsBuilderFactoryBean`s are unconditionally started in `StreamsBuilderFactoryManager.start()`.

**Comment by garyrussell** [comment]
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1126

**Comment by sobychacko** [comment]
@garyrussell Shall we close this issue since the binder issue is already addressed?
