### ISSUE TITLE
Autoconfiguration for Kafka Infrastructure classes and profile support for CF

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-kafka#190]
It would be nice to have autoconfig for kafka, I believe this was attempted before to be included in spring boot but am creating the issue here.  Also, it would be good to have a cloud profile as well for the autoconfiguration such that we can map vcap env-vars to the ones boot expects.  

For example, from a spring data flow context, a mapping such as

stream create fooz --definition "time | log"
stream deploy fooz --properties "app.time.spring.cloud.stream.kafka.binder.brokers=${vcap.services.kafkanew.credentials.brokers},app.time.spring.cloud.stream.kafka.binder.zkNodes=${vcap.services.kafkanew.credentials.zkNodes},app.log.spring.cloud.stream.kafka.binder.brokers=${vcap.services.kafkanew.credentials.brokers},app.log.spring.cloud.stream.kafka.binder.zkNodes=${vcap.services.kafkanew.credentials.zkNodes}"

but that is using spring cloud stream.... would be good to have the same for a spring kafka app.

**Comment by artembilan** [comment]
The Spring Boot effort is here: https://github.com/spring-projects/spring-boot/pull/6961.
Need more review/merge love, so it can appear in the next Boot `1.5`.

Not sure about Cloud profile. Or in other words: not familiar at all.
Is it something what [Spring Cloud Services](http://docs.pivotal.io/spring-cloud-services/1-1/index.html) provides? 
Thanks

**Comment by markpollack** [comment]
Why was it closed?  Also, should there be zk information in `KafkaProperties`?  @mbogoevici 

The cloud profile is really a cloud foundry profile.  A service in cloud foundry has its information exposed under the vcap_services env-var and boot can flatten that out.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.java

If we had a standard boot config property for Kafka then we could configure it automatically, via spring.kafka.bootstrapServers=${vcap.services.kafka.credentials.brokers}

the right-hand side .kafka. references a service name that could be defined by the user.  It would prob be a separate issue.

**Comment by mbogoevici** [comment]
@markpollack

I don't think that there should be zk properties at this level. The zk props are used in the binder for topic management. We might port them if we move fve topic mgmt code here but for now they won't be used.

**Comment by garyrussell** [comment]
>Why was it closed? 

Why was what closed? 

spring-projects/spring-boot#6961 is still open.

**Comment by markpollack** [comment]
my bad!

**Comment by markpollack** [comment]
The end goal would be to autoconfig a spring cloud stream app that uses Kafka, so, in that case, it sounds like we should move the mgmt code here or add another autoconfig class (but with a diff prefix?) into the Kafka binder project.  Seems better to move the topic mgmt code in here and have the same prefix.

**Comment by artembilan** [comment]
Sounds like one more request for `spring-kafka-admin` :smile: 
See related: #119

**Comment by mbogoevici** [comment]
a separate library like for Rabbit would be a better way to go, I agree.

**Comment by garyrussell** [comment]
This is moot.
