### ISSUE TITLE
Cannot use Kotlin property syntax on ContainerProperties.idleEventInterval since release 2.7.3

### ISSUE THREAD

**Issue by psychobaatezu** [spring-projects/spring-kafka#1900]
Since release 2.7.3, it's not possible anymore to use the Kotlin property syntax on ContainerProperties.idleEventInterval field.

![image](https://user-images.githubusercontent.com/15527217/128357297-649bb74a-2ab1-4d50-baf6-3f9ffca92399.png)

This is caused by this commit : 0ee2d49ea525de038d315bc243b62f1004a26dc6

![image](https://user-images.githubusercontent.com/15527217/128357511-8b2a3581-0f08-4f62-ba77-3d2997e07c7f.png)

Granted, the field is actually nullable. But by adding the annotation on the getter instead of the actual field, it tells the Kotlin interpreter that the getter will return a nullable Long type (Long?) and the setter will apply the given value to a non-nullable Long Type (Long). This discrepancy blocks Kotlin property syntax because the underneath getter/setter are not for the same type.

So to use 2.7.3, existing code need to change to this to continue to work :

![image](https://user-images.githubusercontent.com/15527217/128358237-7530e1d7-4eb1-4f82-9100-028b9d6138e8.png)

The solution to solve that is to put `@Nullable` annotation on the field instead, which by the way is more accurate.

**Comment by psychobaatezu** [comment]
Possible fix : https://github.com/spring-projects/spring-kafka/pull/1901

**Comment by garyrussell** [comment]
Thanks; merged and cherry-picked to 2.7.x.
