### ISSUE TITLE
Consumer stuck at high cpu when reconnecting to broker fails by AuthenticationException

### ISSUE THREAD

**Issue by thimmwork** [spring-projects/spring-kafka#1902]
**Affects Version(s):** 2.6.10 (also observed in 2.6.9, possibly more)
Stacktraces below reference 2.6.10

Setup and preface:
We're running Spring Boot 2.4.8, kafka-clients 2.6.2 in Kubernetes with 2 service instances (let's call them A and B) sharing the same consumer group.

Due to a scheduled maintenance, authentication to our broker failed for a short time.
When service instance A went down, a consumer rebalance was triggered. a new instance C was created instead, tried to connect to the broker and failed in the expected way.

The issue:
This occurs on (the surviving) instance B, which got stuck at max CPU.
The client logged the following errors:
> [Consumer clientId=my-client-5, groupId=my-group-id] Connection to node 14 (broker-14.<url>/<ip:port>) failed authentication due to: Authentication failed: Invalid username or password

and

> java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.common.errors.SaslAuthenticationException's; no record information is available
> 	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:151)
> 	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:113)
> 	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1439)
> 	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1136)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed: Invalid username or password

After that, CPU usage raised from moderate 5% to 700% and did not go down - even hours later.
When authentication against our broker worked again, instance C connected in a regular fashion.
Instance A remained stuck at max CPU and did not recover.

Instance A is dead now, but I managed to pull a thread dump, if that's of any help:

> java.lang.Thread.State: RUNNABLE
> 	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
> 	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
> 	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
> 	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
> 	- locked <0x00000000d4bee1d0> (a sun.nio.ch.Util$3)
> 	- locked <0x00000000d4bee1c0> (a java.util.Collections$UnmodifiableSet)
> 	- locked <0x00000000d4ba1820> (a sun.nio.ch.EPollSelectorImpl)
> 	at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:105)
> 	at org.apache.kafka.common.network.Selector.select(Selector.java:871)
> 	at org.apache.kafka.common.network.Selector.poll(Selector.java:469)
> 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:547)
> 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
> 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
> 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1296)
> 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
> 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1165)
> 	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
> 	at com.sun.proxy.$Proxy245.poll(Unknown Source)
> 	at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:89)
> 	at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:83)
> 	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1283)
> 	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1174)
> 	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1087)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

**Comment by garyrussell** [comment]
Starting with version 2.7.4, you can configure a `ConditionalDelegatingErrorHandler` and when a `SaslAuthenticationException` is thrown, you can invoke the `ContainerStoppingErrorHandler`.

**Comment by thimmwork** [comment]
The way the `ConditionalDelegatingErrorHandler` uses the default implementation of `isAckAfterHandle() { return true; }` , it is not able to propagate the info that an error was not recovered from to the container, so the only option left is to stop the container or perform a similiar action that terminates the consumer.

Are there plans to delegate `isAckAfterHandle()` to either its defaultErrorHandler or even the errorHandler that actually handled the error?

**Comment by garyrussell** [comment]
Yes; this is a bug; in 2.8, we have a new implementation that does exactly that...

https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java#L79-L82

and

https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java#L99-L108

**Comment by thimmwork** [comment]
Will 2.8 contain any other changes that resolve the issue with the high cpu usage problem?
After all, custom error handlers are only a workaround.

**Comment by neorayer** [comment]
Hi @thimmwork , how did you resolve the issue? I'm getting the same issue at the moment. Thanks.

**Comment by thimmwork** [comment]
Hi @neorayer ,
which version are you running? From Kafka client 2.9.7 / 3.0.5 on there's the possibility to configure _restartAfterAuthException: true_ that restarts the internal container. We haven't re-encountered this issue after upgrading and configuring this. So you should try that first.

**Comment by neorayer** [comment]
Thank you @thimmwork ! I'm still using version 2.7. I'll upgrade it and try it out. Cheers.
