### ISSUE TITLE
JsonSerde serializing subclass incorrectly as super class

### ISSUE THREAD

**Issue by sanket-1609** [spring-projects/spring-kafka#1922]
Affects Version(s): 2.5.3 /probably all

🐞 Bug report
Looks like JsonSerde is not serializing the subclass properly when used in Streams. 
It delegates to JsonSerializer which works as expected in a kafkaTemplate but behaves differently in streams.

Application/TestCase here (Read readme)
https://github.com/sanket-1609/JSONSerde-bug/tree/master 

This is my first bug report so apologies if specified in incorrect format.

**Comment by sanket-1609** [comment]
I see.
Changing it to generic did the trick. 

`    private static final JsonSerde employeeJsonSerde;
    private static final CustomSerde customSerde;

    static {
        employeeJsonSerde = new JsonSerde();
        HashMap<String, Object> ma = new HashMap<>();
        ma.put(JsonDeserializer.TRUSTED_PACKAGES, "*");
        employeeJsonSerde.deserializer().configure(ma,false);
        customSerde = new CustomSerde();
    }

    public static JsonSerde employeeJsonSerde(){
        return employeeJsonSerde;
    }`

**Comment by sanket-1609** [comment]
Do you think it would be better for JsonSerde to serialize the subclass as subclass, since within a JVM the object wouldn't loose other attributes even if we typecast it.

Happy to close this one if you disagree, for my use case I think i will jsut use the customserde so I dont have to put in generics

Thanks

**Comment by garyrussell** [comment]
I believe it is working as designed.

```java
    static {
        employeeJsonSerde = new JsonSerde<>(Employee.class);
        customSerde = new CustomSerde();
    }
```

Here you are explicitly saying serialize as an `Employee` - this might be desirable - for example if the subclass has sensitive information you don't want to convey.

Remove the type to get the behavior you desire:

```java
    static {
        employeeJsonSerde = new JsonSerde<>();
        ((JsonDeserializer<?>) employeeJsonSerde.deserializer()).trustedPackages("*");
        customSerde = new CustomSerde();
    }
```

**Comment by sanket-1609** [comment]
I see, I didn't realize that specifying it in constructor was what causing it.
Closing this one out.
Thanks for the help.
