### ISSUE TITLE
BatchInterceptor Result Ignored Unless the Listener Consumes `ConsumerRecords` Instead of `List<ConsumerRecord>`.

### ISSUE THREAD

**Issue by marosivanco** [spring-projects/spring-kafka#1929]
**Affects Version(s):** 2.7.6

I am trying to filter consumer records **before** the deserialization.

### Use Cases
Here are some scenarios in which the deserialization skipping makes perfect sense:

1. Consume only records not older than few seconds. The record creation time is in the header.
An example is a notification system which sends push notifications to the consumer devices. Such notifications are often relevant only at the moment of an event. The records corresponding to the old events need to be skipped.
2. Process only records which hold entity of certain type. The entity type is in the header.
An example is a sale system which maintains list of sale items. The items are updated based on the records from the topic. Each item type is represented by its entity (e.g. AVRO record). The books sale system consumes only Book entities, the other entities (Electronics, Cloths,...) can be skipped safely.

### Related existing APIs
There are several APIs which are kind of similar to what I need - Record Filter Strategy, Batch/Record Interceptor. Unfortunately, the Record Filter Strategy is invoked after deserialization.

The Batch Interceptor is also invoked after deserialization. However, when the factory is configured with `ByteArrayDeserializer`, the interceptor could be used to transform `ConsumerRecord` to a kind of `LazyConsumerRecord`, which could perform the deserialization (String/Json/Avro) on-demand. However, the interceptor results are ignored, see: [org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer#doInvokeBatchOnMessage](https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2104), the original `recordList` is used. Instead, the new list constructed from the modified `recordsArg` should be used.

### Workaround
Use `ByteArrayDeserializer` and defer deserialization to the message listener. This has obvious disadvantage of cluttering message listener with the deserialization and the deserialization error handling.

### Possible Solution
Deffer creation of `List<ConsumerRecord<K, V>> recordList` from `ConsumerRecords<K, V> recordsArg` after the execution of [org.springframework.kafka.listener.BatchInterceptor#intercept](https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/BatchInterceptor.java#L45)

**Comment by garyrussell** [comment]
This is not something Spring can help with - deserialization occurs within the `KafkaConsumer` before Spring gets the records.

You can configure a `ConsumerInterceptor` in the consumer factory - see https://kafka.apache.org/documentation/#consumerconfigs_interceptor.classes and `ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG`.

```java
/**
 * A plugin interface that allows you to intercept (and possibly mutate) records received by the consumer. A primary use-case
 * is for third-party components to hook into the consumer applications for custom monitoring, logging, etc.
 *
 * <p>
 * This class will get consumer config properties via <code>configure()</code> method, including clientId assigned
 * by KafkaConsumer if not specified in the consumer config. The interceptor implementation needs to be aware that it will be
 * sharing consumer config namespace with other interceptors and serializers, and ensure that there are no conflicts.
 * <p>
 * Exceptions thrown by ConsumerInterceptor methods will be caught, logged, but not propagated further. As a result, if
 * the user configures the interceptor with the wrong key and value type parameters, the consumer will not throw an exception,
 * just log the errors.
 * <p>
 * ConsumerInterceptor callbacks are called from the same thread that invokes
 * {@link org.apache.kafka.clients.consumer.KafkaConsumer#poll(java.time.Duration)}.
 * <p>
 * Implement {@link org.apache.kafka.common.ClusterResourceListener} to receive cluster metadata once it's available. Please see the class documentation for ClusterResourceListener for more information.
 */
public interface ConsumerInterceptor<K, V> extends Configurable, AutoCloseable {

    /**
     * This is called just before the records are returned by
     * {@link org.apache.kafka.clients.consumer.KafkaConsumer#poll(java.time.Duration)}
     * <p>
     * This method is allowed to modify consumer records, in which case the new records will be
     * returned. There is no limitation on number of records that could be returned from this
     * method. I.e., the interceptor can filter the records or generate new records.
     * <p>
     * Any exception thrown by this method will be caught by the caller, logged, but not propagated to the client.
     * <p>
     * Since the consumer may run multiple interceptors, a particular interceptor's onConsume() callback will be called
     * in the order specified by {@link org.apache.kafka.clients.consumer.ConsumerConfig#INTERCEPTOR_CLASSES_CONFIG}.
     * The first interceptor in the list gets the consumed records, the following interceptor will be passed the records returned
     * by the previous interceptor, and so on. Since interceptors are allowed to modify records, interceptors may potentially get
     * the records already modified by other interceptors. However, building a pipeline of mutable interceptors that depend on the output
     * of the previous interceptor is discouraged, because of potential side-effects caused by interceptors potentially failing
     * to modify the record and throwing an exception. If one of the interceptors in the list throws an exception from onConsume(),
     * the exception is caught, logged, and the next interceptor is called with the records returned by the last successful interceptor
     * in the list, or otherwise the original consumed records.
     *
     * @param records records to be consumed by the client or records returned by the previous interceptors in the list.
     * @return records that are either modified by the interceptor or same as records passed to this method.
     */
    public ConsumerRecords<K, V> onConsume(ConsumerRecords<K, V> records);

    /**
     * This is called when offsets get committed.
     * <p>
     * Any exception thrown by this method will be ignored by the caller.
     *
     * @param offsets A map of offsets by partition with associated metadata
     */
    public void onCommit(Map<TopicPartition, OffsetAndMetadata> offsets);

    /**
     * This is called when interceptor is closed
     */
    public void close();
}
```

**Comment by garyrussell** [comment]
You could use a custom deserializer which can use the headers, and return null in the `record.value()`; then filter these out in the interceptor (or a record interceptor).

**Comment by marosivanco** [comment]
> This is not something Spring can help with - deserialization occurs within the KafkaConsumer before Spring gets the records.

Actually, I think Spring can help a lot. I assume that:

1. message listener should focus on processing relevant messages
2. record filter strategy should focus on choosing which records are relevant
3. deserializers should focus on deserialization

I could move these aspects (deserialization, filtering, processing) around various components, but IMO this makes the code less maintainable. There is the performance penalty associated with deserializing records which will never be processed.

Even though the deserialization happens in kafka, the spring could use (lightweight) ByteArrayDeserializer and perform (heavy) deserialization (Json/Avro) later. I already configured ByteArrayDeserializers for key and value and implemented custom LazyBatchInterceptor which replaces records with instances of custom LazyConsumerRecord.

The documentation to [org.springframework.kafka.listener.BatchInterceptor#intercept](https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/BatchInterceptor.java#L45) actually states that the interceptor can replace records:
```
/**
 * Perform some action on the records or return a different one. If null is returned
 * the records will be skipped. Invoked before the listener.
 * @param records the records.
 * @param consumer the consumer.
 * @return the records or null.
 */
@Nullable
ConsumerRecords<K, V> intercept(ConsumerRecords<K, V> records, Consumer<K, V> consumer);
```
Contrary to the documentation, the replacement records are ignored.
If the replacement would work, something like this could be possible:
```java
...
        config.put(KEY_DESERIALIZER_CLASS_CONFIG, ByteArrayDeserializer.class);
        config.put(VALUE_DESERIALIZER_CLASS_CONFIG, ByteArrayDeserializer.class);
        config.put(LazyBatchInterceptor.KEY_DESERIALIZER_CLASS, StringDeserializer.class);
        config.put(LazyBatchInterceptor.VALUE_DESERIALIZER_CLASS, KafkaAvroDeserializer.class);
...
        var consumerFactory = new DefaultKafkaConsumerFactory<>(config);
...
        factory.setConsumerFactory(consumerFactory);
        factory.setBatchInterceptor(new LazyBatchInterceptor<>(config));

```
```java
public class LazyBatchInterceptor<K, V> implements BatchInterceptor<K, V> {
    /**
     * Property name for the delegate key deserializer.
     */
    public static final String KEY_DESERIALIZER_CLASS = "lazy-batch-interceptor.deserializer.key.class";
    /**
     * Property name for the delegate value deserializer.
     */
    public static final String VALUE_DESERIALIZER_CLASS = "lazy-batch-interceptor.deserializer.value.class";

    private final Deserializer<K> keyDeserializer;
    private final Deserializer<V> valueDeserializer;

    public LazyBatchInterceptor(Map<String, Object> config) {
        this.keyDeserializer = instantiateDeserializer(config, KEY_DESERIALIZER_CLASS);
        this.keyDeserializer.configure(config, true);
        this.valueDeserializer = instantiateDeserializer(config, VALUE_DESERIALIZER_CLASS);
        this.valueDeserializer.configure(config, false);
    }

    @Nullable
    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public ConsumerRecords<K, V> intercept(ConsumerRecords<K, V> records, Consumer<K, V> consumer) {
        Map recs = StreamSupport.stream(records.spliterator(), false)
                .map(r -> (ConsumerRecord<byte[], byte[]>) r)
                .map(r -> new LazyConsumerRecord<>(r, keyDeserializer, valueDeserializer))
                .collect(groupingBy(r -> new TopicPartition(r.topic(), r.partition())));
        return new ConsumerRecords<>((Map<TopicPartition, List<ConsumerRecord<K, V>>>) recs);
    }

    @SuppressWarnings({"unchecked"})
    private <D> Deserializer<D> instantiateDeserializer(Map<String, ?> config, String configKey) {
        if (config.containsKey(configKey)) {
            try {
                Object value = config.get(configKey);
                Class<Deserializer<D>> clazz = (Class<Deserializer<D>>) (value instanceof Class ? value : ClassUtils.forName((String) value, null));
                var delegate = clazz.getDeclaredConstructor().newInstance();
                Assert.isInstanceOf(Deserializer.class, delegate, "'delegate' must be a 'Deserializer', not a ");
                return delegate;
            } catch (Exception e) {
                throw new IllegalStateException(e);
            }
        }
        throw new IllegalStateException("Missing configuration property " + configKey);
    }
}
```
```java
public class LazyConsumerRecord<K, V> extends ConsumerRecord<K, V> {
    private final byte[] keyBytes;
    private final byte[] valueBytes;
    private final Deserializer<K> keyDeserializer;
    private final Deserializer<V> valueDeserializer;
    private boolean keyDeserialized;
    private boolean valueDeserialized;
    private K key;
    private V value;

    public LazyConsumerRecord(ConsumerRecord<byte[], byte[]> src, Deserializer<K> keyDeserializer, Deserializer<V> valueDeserializer) {
        super(
                src.topic(),
                src.partition(),
                src.offset(),
                src.timestamp(),
                src.timestampType(),
                src.checksum(),
                src.serializedKeySize(),
                src.serializedValueSize(),
                null,
                null
        );
        this.keyBytes = src.key();
        this.valueBytes = src.value();
        this.keyDeserializer = keyDeserializer;
        this.valueDeserializer = valueDeserializer;
    }

    @Override
    public K key() {
        if (!keyDeserialized) {
            key = keyDeserializer.deserialize(topic(), headers(), keyBytes);
            keyDeserialized = true;
        }
        return key;
    }

    @Override
    public V value() {
        if (!valueDeserialized) {
            value = valueDeserializer.deserialize(topic(), headers(), valueBytes);
            valueDeserialized = true;
        }
        return value;
    }
}
```
Please note, that such LazyBatchInterceptor component could be reusable by many projects. It mitigates the performance penalty, works nicely with existing deserializers (e.g. ErrorHandlingDeserializer) and record filtering strategy.

**Comment by garyrussell** [comment]
>Contrary to the documentation, the replacement records are ignored.

??

https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2274-L2284

and 

https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2089-L2091

Feel free to contribute your `LazyBatchInterceptor` idea via a Pull Request.

**Comment by garyrussell** [comment]
Oh, sorry - we need to rebuild the `recordList` from the new CRs.

https://github.com/spring-projects/spring-kafka/blob/d8cfee6c36e866a73317db83c667d55bb8a53920/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2089-L2091

**Comment by garyrussell** [comment]
@marosivanco As a work around, set `interceptBeforeTx` to true (container property). 

It doesn't require transactions, it just means the intercept will be done before the `List<ConsumerRecord>` is built from the `ConsumerRecords`.
