### ISSUE TITLE
Spring Kafka 2.5.15 is incompatible with Spring Boot 2.4.0 onwards 

### ISSUE THREAD

**Issue by anmoldeep0123** [spring-projects/spring-kafka#1944]
######## pom.xml #########
<spring-kafka.version>2.5.15.RELEASE</spring-kafka.version>
<spring-boot.version>2.4.0</spring-boot.version>
######## pom.xml #########

Error:

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.SpringApplication.run(SpringApplication.java:324)

The following method did not exist:

    org.springframework.context.ConfigurableApplicationContext.setApplicationStartup(Lorg/springframework/core/metrics/ApplicationStartup;)V

The method's class, org.springframework.context.ConfigurableApplicationContext, is available from the following locations:

    jar:file:/project-name.jar!/BOOT-INF/lib/spring-context-5.2.15.RELEASE.jar!/org/springframework/context/ConfigurableApplicationContext.class

The class hierarchy was loaded from the following locations:

    org.springframework.context.ConfigurableApplicationContext: jar:file:/project-name.jar!!/BOOT-INF/lib/spring-context-5.2.15.RELEASE.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.context.ConfigurableApplicationContext

**Comment by garyrussell** [comment]
That is correct (it is not supported) - see the [project page](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions) for the compatibility matrix.

It is better to use Boot's dependency management and NOT specify versions for dependent projects; that way, Boot will bring in the compatible version.

The current Spring Boot 2.4.x version (2.4.10) requires spring-kafka 2.6.10.

**Comment by garyrussell** [comment]
That is correct (it is not supported) - see the [project page](https://spring.io/projects/spring-kafka) for the compatibility matrix.

It is better to use Boot's dependency management and NOT specify versions for dependent projects; that way, Boot will bring in the compatible version.

The current Spring Boot 2.4.x version (2.4.10) requires spring-kafka 2.6.10 and Spring Framework 5.3.9.
