### ISSUE TITLE
Spring boot Kafka - Kafka Producer can not get manually close

### ISSUE THREAD

**Issue by ofirgrm** [spring-projects/spring-kafka#1959]
**Version**: 2.5.1
**Class**: [org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer](https://github.com/spring-projects/spring-kafka/blob/v2.5.1.RELEASE/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java)

Kafka producer factory provides a closeable interface to close a Kafka producer (the same can be achieved with the close() method). 
```
        try (Producer producer = producerFactory().createProducer()) {
            ...
            producer.flush();
        }
```
However, a bug in the code prevents closing/removing a producer.

The close() method, in normal execution (when this.closed=false) runs the following code (line 869):
`this.closed = this.removeProducer.test(this, timeout);`
The line of code calls a method to remove the current producer and return a 'success' indication to the closed property
However, the removeProducer(), in line 571, contains the following code:
```
        if (producerToRemove.closed) {
            // remove the producer
            return true;
        } else {
            return false;
        }
```
The bug is in the if statement which should check for the negative condition:
`if (!producerToRemove.closed) {`

Since producerToRemove==this and when we enter removeConsumerProducer() method this.closed was 'false', the code will always return false and fail to remove the producer.

This is how I detected/reproduced it, but you may think of a quicker way:
1. Run Kafka (i.e. Confluent image version 6.1.1) using TestContainers in a test class (TestA.class)
2. After Kafka started, create a producer and producer a message to a topic
3. Shutdown Kafka container after the test execution is over
4. Create another test class (TestB) which is a duplication of TestA.
5. Run the 2 test classes

The first test class TestA (might be the other one if the runner will chose to start with TestB) will create a Kafka container with exposed port X and then create a producer to produce a message to a topic. Finally, it will shut down the Kafka container, however, at this stage, the producers are still up and running (although there is no indication yet)
The second test class, TestB will again, create a Kafka container, this time, most likely, using a different exposed port - Y. Since the producers created by TestA are still running, at this point, you should see in the log Warnings from the producer about port X not available.

**Comment by garyrussell** [comment]
This is not a bug; it is by design.

```java
/**
 * The {@link ProducerFactory} implementation for a {@code singleton} shared {@link Producer} instance.
 * <p>
 * This implementation will return the same {@link Producer} instance (if transactions are
 * not enabled) for the provided {@link Map} {@code configs} and optional {@link Serializer}
 * implementations on each {@link #createProducer()} invocation.
 * <p>
 * If you are using {@link Serializer}s that have no-arg constructors and require no setup, then simplest to
 * specify {@link Serializer} classes against {@link ProducerConfig#KEY_SERIALIZER_CLASS_CONFIG} and
 * {@link ProducerConfig#VALUE_SERIALIZER_CLASS_CONFIG} keys in the {@code configs} passed to the
 * {@link DefaultKafkaProducerFactory} constructor.
 * <p>
 * If that is not possible, but you are sure that at least one of the following is true:
 * <ul>
 *     <li>only one {@link Producer} will use the {@link Serializer}s</li>
 *     <li>you are using {@link Serializer}s that may be shared between {@link Producer} instances (and specifically
 *     that their close() method is a no-op)</li>
 *     <li>you are certain that there is no risk of any single {@link Producer} being closed while other
 *     {@link Producer} instances with the same {@link Serializer}s are in use</li>
 * </ul>
 * then you can pass in {@link Serializer} instances for one or both of the key and value serializers.
 * <p>
 * If none of the above is true then you may provide a {@link Supplier} function for one or both {@link Serializer}s
 * which will be used to obtain {@link Serializer}(s) each time a {@link Producer} is created by the factory.
 * <p>
 * The {@link Producer} is wrapped and the underlying {@link KafkaProducer} instance is
 * not actually closed when {@link Producer#close()} is invoked. The {@link KafkaProducer}
 * is physically closed when {@link DisposableBean#destroy()} is invoked or when the
 * application context publishes a {@link ContextStoppedEvent}. You can also invoke
 * {@link #reset()}.
 * <p>
 * Setting {@link #setTransactionIdPrefix(String)} enables transactions; in which case, a
 * cache of producers is maintained; closing a producer returns it to the cache. The
 * producers are closed and the cache is cleared when the factory is destroyed, the
 * application context stopped, or the {@link #reset()} method is called.
 *
 * @param <K> the key type.
 * @param <V> the value type.
 *
 * @author Gary Russell
 * @author Murali Reddy
 * @author Nakul Mishra
 * @author Artem Bilan
 * @author Chris Gilbert
 */
public class DefaultKafkaProducerFactory<K, V> extends KafkaResourceFactory
```

This is in accordance with recommendations from `KafkaProducer`

```java
 * The producer is <i>thread safe</i> and sharing a single producer instance across threads will generally be faster than
 * having multiple instances.
```
If you are using a Spring test application context, add `@DirtiesContext` to the test case, to destroy the connection factory, which will close the producer.

Or, call `reset()` on the producer factory.

**Comment by ofirgrm** [comment]
Thanks, for the quick reply, Gary.
I was able to close the producers after calling reset() on the same factory (@DirtiesContext had no affect)

I do have to add that IMHO, the design is awkward and leads to bad and outdated coding habits as in modern coding the design and the code is one of the same.
What I dislike most is having to read the following line in javadoc:
"instance is not actually closed when {@link Producer#close()} is invoked"
and the reasons are:
1. if the Producer implements Closeable interface, it strongly suggests that by calling close() or by using try() statement, the resource, aka, the producer will get properly closed and release its resource(s). This is how it works with every other closable resource I'm familiar with (i.e. files, DB, streams...) and breaking this behaviour should not be taken so lightly
2. It is my belief that if you have to explain something that is unexpected, it means that you did something wrong and there is probably a better solution. I also believe that if you provided an optimal solution you don't have to explain why you did what you did by javadoc, since, it's the code that should explain itself.
3. The idea of multiple factory instances producing the same object seems absurd. Think about it from a "child-like/naive" POV, does it make sense that 10 car factories will produce the exact same physical car? perhaps a factory is not the correct design pattern here?

I do hope that you will find my comments constructive.

Thanks.
