### ISSUE TITLE
Platform Brussels build fails with NoSuchMethodErrors due to use of AssertJ 3.4

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-kafka#196]
Spring Boot, and as a result the Platform, has dependency management for AssertJ. Due to Boot 1.5 and Platform Brussels still supporting Java 6 and 7, it uses AssertJ 2.x. This results in a no such method error in Spring Kafka's tests. For example:

```
java.lang.NoSuchMethodError: org.assertj.core.api.AbstractIterableAssert.allMatch(Ljava/util/function/Predicate;)Lorg/assertj/core/api/AbstractIterableAssert;
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainerTests.testAfterListenCommit(ConcurrentMessageListenerContainerTests.java:234)
```

There are (at least) a couple of ways to fix this:

1. Downgrade Assert J 2.5 and change the assertions
2. Change you build.gradle to override the AssertJ version in to springIoTestRuntime configuration

I have a slight preference for 1 as it's the safer solution, but it's also more work and stops you from using any new goodies in Assert J 3.x. What would you prefer?

**Comment by wilkinsona** [comment]
Now I look more closely, I'm not sure that 2 is an option. AssertJ is a dependency of `spring-kafka-test` and we'll want to be sure that it can be used with Boot 1.5/Platform Brussels dependency management. I think downgrading to AssertJ 2.5 is the way to go.

**Comment by garyrussell** [comment]
I see boot still uses 2.5.0 - I don't have a problem dropping back, my guess is Artem picked the latest version when we switched (initially 3.3.0, and later 3.4.1). I doubt we're using anything more fancy - will check.

**Comment by garyrussell** [comment]
We have a few uses of `assertThatExceptionOfType` but we can work around those.

**Comment by artembilan** [comment]
Pay attention that it is just an `optional` dependency.
Maybe the second option with the `springIoTestRuntime` override would be sufficient ?

**Comment by garyrussell** [comment]
Yes, it's optional but the tests won't run with the older jar.

**Comment by wilkinsona** [comment]
Thanks both

**Comment by artembilan** [comment]
Similar fix for Spring Integration Kafka: https://github.com/spring-projects/spring-integration-kafka/commit/f63aa3bfa39a834dc03978a84af8927aba2cff57
