### ISSUE TITLE
Set Producer Factory maxAge through application.properties

### ISSUE THREAD

**Issue by gmiano** [spring-projects/spring-kafka#1968]
Hello,
I am developed a spring boot application that uses both Kafka consumers and producers. In order to guarantee exactly-once semantic, transactions have been properly enabled and they work as expected. 

I am having some problems caused by a ProducerFencedException without a rebalance. Looking at the documentation I found out the following tip:

`Starting with version 2.5.8, you can now configure the maxAge property on the producer factory. This is useful when using transactional producers that might lay idle for the broker’s transactional.id.expiration.ms. With current kafka-clients, this can cause a ProducerFencedException without a rebalance. By setting the maxAge}}to less than {{transactional.id.expiration.ms, the factory will refresh the producer if it is past it’s max age.`

I would like to set maxAge property on the producer factory through application.properties, but I found out no documentation or way to do so. Is it possible? If not, how can I deal with it with a minimum development effort and minimum code written?

Regards,
Giuseppe.

**Comment by garyrussell** [comment]
This would need to be an enhancement the spring-boot project; not here. I suggest you open an issue over there.

In the meantime, you can do it in any bean definition by adding the pf as a parameter...

```java
@Bean
SomeOtherBean otherOne(ProducerFactory<?, ?> pf) {
    pf.setMaxAge(...);
    return new SomeOtherBean();
};
```
