### ISSUE TITLE
Rebalance triggered under load

### ISSUE THREAD

**Issue by martindam** [spring-projects/spring-kafka#199]
Today I discovered an issue with the KafkaMessageListenerContainer (running 1.0.2) and manual acknowledgement that triggers rebalances and prevents offsets from being committed. 

What I believe is happening is the following sequence:
1) A batch is received on thread A and sends the batch to thread B and goes back to polling
2) Thread B invokes the listener for each record
3) When the record is processed the record is acknowledged which adds the offset to the ack queue
4) The batch is now fully processed and because it is manual ack, the consumer is woken up
5) Thread A throws the WakeupException and goes to commit the offset
6) Meanwhile thread B finished another batch and now calls wakeup again. This interrupts the commitSync() and the offset is not committed. 
7) Thread A goes back to polling, but now another batch is finished so the consumer is woken up again
8) and so on

Because the consumer is woken up all the time, it does not get to send its heartbeat nor commit its offset. This sequence of events can continue until the session timeouts and a rebalance happens. This is a fairly complicated sequence in order for an error to occur, but after have been running this in staging for some time, we see it happen fairly often with our workload. The image below is the "Time since last heartbeat" for the consumer which should be below 30s (the red area) and preferable below 10s (the yellow area). 

![image](https://cloud.githubusercontent.com/assets/10091249/19877382/f204c3b8-9f9b-11e6-98ef-1e2c03262cd2.png)

When I changed the consumer to remove the wakeup on line 623 (https://github.com/spring-projects/spring-kafka/blob/9ec3a780155e73a47aaf93807a51e4718523e777/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L623) the heartbeats succeeds, the commits are performed correctly and the overall performance is improved. Please have a look and get back to me - for now, I will be running it with my fix as we had 4-6 rebalances per hour per consumer before.

**Comment by garyrussell** [comment]
Thanks for reporting this - I think we need to do a best-effort commit - i.e. perhaps a boolean indicating the consumer is in `poll()` and only wakeup if it's true. Not entirely reliable (we might miss a wake up in the small race condition between polls, but I think it's better than waiting for the poll to end to do the commits.

**Comment by martindam** [comment]
I think that it should be an option whether the wakeup should be used or not. Using it will have a big impact of performance and is frankly not needed unless you are using an immediate manual commit.

**Comment by garyrussell** [comment]
But isn't it the case that, if you are using BATCH acks (commit after batch is processed), and you have a long poll timeout, we could end up losing the commit if the JVM fails while waiting for the poll to end?

**Comment by martindam** [comment]
Yes that is true with the current implementation. But that should be up to the user to tune the consumer correctly in my opinion. 

To add to my last comment, if you interrupt the poll() again and again, you would not be sending heartbeats which could trigger a rebalance. So using the wakeup() is tricky to get right I think

**Comment by garyrussell** [comment]
Makes sense.

**Comment by martindam** [comment]
Pushed the fix I have been running for some days. Please apply it on the 1.0.x branch as well

**Comment by artembilan** [comment]
See https://github.com/spring-projects/spring-kafka/pull/200

**Comment by artembilan** [comment]
I wonder if this SO is related: http://stackoverflow.com/questions/40406638/spring-kafka-batch-not-updating-offsets-with-larger-batches

**Comment by martindam** [comment]
@artembilan It looks a lot like the issue I was seeing
