### ISSUE TITLE
Move support for Kerberos from Spring Cloud Stream Kafka Binder to Spring Kafka

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-kafka#201]
The functionality to configure security in Spring Cloud Stream Kafka Binder

http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR1/reference/htmlsingle/#_using_spring_boot_properties

Should be moved into the Spring Kafka project as it is more general purpose.  Property name would have their 'stream' bits removed, so spring.kafka.jaas.loginModule.

The PR https://github.com/spring-projects/spring-boot/pull/6961 should then be updated to include these properties in Spring Boot autoconfiguration.

**Comment by mbogoevici** [comment]
Maybe this is a good time to discuss about `spring-kafka-admin` as part of what's going on in the binder is tied to creating topics which requires Zookeeper permissions (which are another part of the binder setup, but are not required by `spring-kafka`).
