### ISSUE TITLE
Batch listener + ErrorHandlingDeserializer + deserialization error = empty list of records

### ISSUE THREAD

**Issue by cfredri4** [spring-projects/spring-kafka#2036]
Found in 2.8.0 and 2.7.x (and probably more).

Long story short. A batch `@KafkaListener` with `List<ConsumerRecord<?, ?>> records` argument, together with a consumer with an `ErrorHandlingDeserializer`, will cause an empty list of records to be delivered to the listener if the records fail deserialization. This is unlike non-batch listeners where an exception is thrown on deserialization errors.

I also came across this post on SO which I suspect is the same thing:

https://stackoverflow.com/questions/62820095/kafkalistener-function-invoked-but-receiving-empty-list

**Comment by garyrussell** [comment]
So what do you expect to happen?

This wasn't an intentional design, but surely getting an empty list has no bad side effect (and tells you that all records from the poll were discarded).

**Comment by garyrussell** [comment]
I deleted my previous comments - with a batch listener the failed records are always passed to the listener with a `null` value; I don't see how an empty list can be sent; I will test.

**Comment by cfredri4** [comment]
Thanks for the information, that explains a few things. I forgot to mention that I have a record filter strategy which filters events with null values, that's likely why the list becomes empty.

I would have expected an exception to be thrown as that is how a simple non-batch listener behaves with `ErrorHandlingDeserializer`.

**Comment by garyrussell** [comment]
We can't do it that way because we don't know which record in the batch failed.

This works as expected:

```java
@SpringBootApplication
public class Kgh2036Application {

	private final LogAccessor logger = new LogAccessor(LogFactory.getLog(Kgh2036Application.class));

	public static void main(String[] args) {
		SpringApplication.run(Kgh2036Application.class, args);
	}

	@KafkaListener(id = "kgh2036", topics = "kgh2036")
	void listen(List<ConsumerRecord<String, String>> in) {
		in.forEach(rec -> {
			if (rec.value() == null) {
				DeserializationException ex = ListenerUtils.getExceptionFromHeader(rec,
						SerializationUtils.VALUE_DESERIALIZER_EXCEPTION_HEADER, this.logger);
				if (ex != null) {
					logger.error(ex, "Record at offset " + rec.offset() + " could not be deserialized");
				}
			}
		});
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> {
			template.send("kgh2036", "junk");
		};
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("kgh2036").partitions(1).replicas(1).build();
	}

}
```

I suggest you remove the filter and move the null check to your listener; with the `DefaultErrorHandler` (2.8) or `RecoveringBatchErrorHandler` (earlier versions), you can throw a `BatchListenerFailedException` to indicate which record failed deserialization, and it can be sent to a DLT (or logger, or whatever recoverer) in the error hander.

You can't do it in the filter because you need to process the records before the failed one.

**Comment by cfredri4** [comment]
Thank you very much, it sounds like a misunderstanding from my end then. I'm not sure if/where/how this could have been documented to prevent others from making the same mistake?

And thanks for the suggestions, it will help me workaround this.

**Comment by garyrussell** [comment]
>I'm not sure if/where/how this could have been documented to prevent others from making the same mistake?

It's documented near the end of this section of the reference manual

https://docs.spring.io/spring-kafka/docs/current/reference/html/#error-handling-deserializer

Although some of that documentation is out of date and it doesn't cover the `List<ConsumerRecord<?, ?>>` case.

I will use this issue to improve it.
