### ISSUE TITLE
KafkaAvroDeserializer schemaRegistry is not initialized before data deserialization

### ISSUE THREAD

**Issue by hurahurat** [spring-projects/spring-kafka#2038]
Sometimes when restarting my application, I find out that schemaRegistry in KafkaAvroDeserializer is not initialized before data deserialization which causes InvalidConfigurationException been thrown. 
And after that schemaRegistry will never been initialized.

**Comment by garyrussell** [comment]
So, why open an issue here? This project does not provide that deserializer; I suggest you reach out to them; and I am sure they will need much more information, stack traces etc.

**Comment by hurahurat** [comment]
Thank you for your response. I open an issue here because I find out that there are 3 instances of my custom deserializer class that exist (supposed it should be only one) which could be a bug or my misconfiguration. And this problem just occurs sometimes unexpectedly where one of them has schemaRegistry field is null.
Could you please take a look at my spring kafka configuration?
	
	@Bean
	public ConsumerFactory<String, Object> consumerFactory() {
		config.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, environment.getProperty("spring.kafka.consumer.bootstrap-servers"));
		config.put(ConsumerConfig.GROUP_ID_CONFIG, environment.getProperty("spring.kafka.consumer.group-id"));
		config.put(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, environment.getProperty("spring.kafka.properties.schema.registry.url"));
		config.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, environment.getProperty("spring.kafka.consumer.auto-offset-reset"));
		
		config.put(DelegatingByTopicSerialization.VALUE_SERIALIZATION_TOPIC_DEFAULT, JsonDeserializer.class.getName());
		config.put(DelegatingByTopicDeserializer.VALUE_SERIALIZATION_TOPIC_CONFIG, 
			"text-msg.*:" + StringDeserializer.class.getName() + "," 
			+ "my-jdbc-test:" + TestRecordDeserializer.class.getName()
		);
		config.put(KafkaAvroDeserializerConfig.SCHEMA_REFLECTION_CONFIG, "true");
		
		return new DefaultKafkaConsumerFactory<String, Object>(
			config,
			new StringDeserializer(),
			new DelegatingByTopicDeserializer(Map.of(
					Pattern.compile("text-msg.*"), new StringDeserializer(),
					Pattern.compile("my-jdbc-test"), new TestRecordDeserializer()
				),
				new JsonDeserializer<Object>())
			);
	}
	
![Screenshot 2021-12-10 100113](https://user-images.githubusercontent.com/78128232/145499776-e73bfd2d-2079-4070-87d1-c398d0f07d5b.png)

![Screenshot 2021-12-10 100157](https://user-images.githubusercontent.com/78128232/145499799-3be97c0c-7c65-4d42-9a36-668d82d98725.png)


If I remove DelegatingByTopicDeserializer.VALUE_SERIALIZATION_TOPIC_CONFIG or keep it and set "return new DefaultKafkaConsumerFactory<String, Object>(config)" my application doesn't start. I didn't find too much detail about DelegatingByTopicSerialization in spring kafka document so I may misunderstand some things.
Thank you.

**Comment by hurahurat** [comment]
Thank you for your response. While debugging I have known how to make it works. 
But with DelegatingByTopicDeserializer I find out that settings in "spring.kafka.value.serialization.bytopic.config" will be called two times in KafkaMessageListenerContainer( one with consumerFactory.createConsumer and another with findDeserializerClass) which causes my deserializer class have two instances. I suppose it should be only one.

**Comment by garyrussell** [comment]
I am not sure what you mean - `findDeserializer` simply determines which deserializers are configured.

What is `spring.kafka.value.serialization.bytopic.config`?

**Comment by hurahurat** [comment]
I will explain in more detail.
	
My ConsumerFactory bean

```
@Bean
public ConsumerFactory<String, Object> consumerFactory() {
    Map<String, Object> config = new HashMap<>();
    config.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, environment.getProperty("spring.kafka.consumer.bootstrap-servers"));
    config.put(ConsumerConfig.GROUP_ID_CONFIG, environment.getProperty("spring.kafka.consumer.group-id"));
    config.put(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, environment.getProperty("spring.kafka.properties.schema.registry.url"));
    config.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, environment.getProperty("spring.kafka.consumer.auto-offset-reset"));
    
    config.put(DelegatingByTopicSerialization.VALUE_SERIALIZATION_TOPIC_DEFAULT, JsonDeserializer.class.getName());
    config.put(DelegatingByTopicDeserializer.VALUE_SERIALIZATION_TOPIC_CONFIG, 
		    "text-msg.*:" + StringDeserializer.class.getName() + "," 
		    + "test-jdbc-.*:" + TestRecordDeserializer.class.getName()
		    );
    
    
    config.put(KafkaAvroDeserializerConfig.SCHEMA_REFLECTION_CONFIG, "true");
    config.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
    
    return new DefaultKafkaConsumerFactory<String, Object>(
	    config,
	    new StringDeserializer(),
	    new DelegatingByTopicDeserializer(Map.of(
			    Pattern.compile("text-msg.*"), new StringDeserializer(),
			    Pattern.compile("test-jdbc-.*"), new TestRecordDeserializer()
		    ),
		    new JsonDeserializer<Object>())
	    );
    }
```
My GenericKafkaAvroDeserializer class and TestRecordDeserializer class:

```
public abstract class GenericKafkaAvroDeserializer<V> extends KafkaAvroDeserializer {
    private Schema readerSchema;
    
    protected GenericKafkaAvroDeserializer(Class<V> type) {
	    readerSchema = ReflectData.get().getSchema(type);
    }
    
    @Override
    public Object deserialize(String s, byte[] bytes) {
	    return deserialize(bytes, readerSchema);
    }
}

public class TestRecordDeserializer extends GenericKafkaAvroDeserializer<TestRecord> {
    public TestRecordDeserializer() {
	    super(TestRecord.class);
    }
}
```
I found that there were 3 instances of TestRecordDeserializer class had been created. Occasionally one of them had schemaRegistry field is null.

![Screenshot 2021-12-10 100113](https://user-images.githubusercontent.com/78128232/145913635-76f90f7e-a403-4f32-8f44-4f55452bf6c3.png)

![Screenshot 2021-12-10 100157](https://user-images.githubusercontent.com/78128232/145913648-e726b19a-2236-4190-8ce0-2d92daca1ff1.png)

If I return the DefaultKafkaConsumerFactory like this one

```
return new DefaultKafkaConsumerFactory<String, Object>(
    config,
    new StringDeserializer(),
    new DelegatingByTopicDeserializer()
);
```

I still found there were 2 instances of TestRecordDeserializer class had been created. While debugging, it turns out that valueDeserializerSupplier of DefaultKafkaConsumerFactory is called twice(one with consumerFactory.createConsumer and another with findDeserializerClass in KafkaMessageListenerContainer). 
	
Here is valueDeserializerSupplier function from DefaultKafkaConsumerFactory
```
private Supplier<Deserializer<V>> valueDeserializerSupplier(
     @Nullable Supplier<Deserializer<V>> valueDeserializerSupplier) {
     return valueDeserializerSupplier == null
		? () -> null
		: () -> {
			Deserializer<V> deserializer = valueDeserializerSupplier.get();
			if (deserializer != null) {
				deserializer.configure(this.configs, false);
			}
			return deserializer;
		};
}
```

If deserializer is not null configure will be called so configure of DelegatingByTopicDeserializer is also called twice.
```
protected void configure(Map<String, ?> configs, boolean isKey) {
    this.forKeys = isKey;
    Object insensitive = configs.get(CASE_SENSITIVE);
    if (insensitive instanceof String) {
	    this.cased = Boolean.parseBoolean((String) insensitive);
    }
    else if (insensitive instanceof Boolean) {
	    this.cased = (Boolean) insensitive;
    }
    String configKey = defaultKey();
    if (configKey != null) {
	    buildDefault(configs, configKey, isKey, configs.get(configKey));
    }
    configKey = configKey();
    Object value = configs.get(configKey);
    if (value == null) {
	    return;
    }
    else if (value instanceof Map) {
	    processMap(configs, isKey, configKey, (Map<Object, Object>) value);
    }
    else if (value instanceof String) {
	    this.delegates.putAll(createDelegates((String) value, configs, isKey));
    }
    else {
	    throw new IllegalStateException(
			    configKey + " must be a map or String, not " + value.getClass());
    }
}
```
Because forKeys is false and DelegatingByTopicDeserializer.VALUE_SERIALIZATION_TOPIC_CONFIG is set createDelegates is called twice too which causes there are two instances of my Deserializer class were created. 
	
So my current workaround is to remove DelegatingByTopicDeserializer.VALUE_SERIALIZATION_TOPIC_CONFIG and call configure function of my custom Deserializer manually.
With this approach, only one instance is created and my app works fine.
```
return new DefaultKafkaConsumerFactory<String, Object>(
    config,
    new StringDeserializer(),
    new DelegatingByTopicDeserializer(Map.of(
		    Pattern.compile("text-msg.*"), new StringDeserializer(),
		    Pattern.compile("test-jdbc-.*"), new TestRecordDeserializer(config)
	    ),
	    new JsonDeserializer<Object>())
);

public class TestRecordDeserializer extends GenericKafkaAvroDeserializer<TestRecord> {
    public TestRecordDeserializer(Map<String, ?> configs) {
	    super(TestRecord.class, configs);
    }
    
    public TestRecordDeserializer(Map<String, ?> configs, boolean isKey) {
	    super(TestRecord.class, configs, isKey);
    }
}

public abstract class GenericKafkaAvroDeserializer<V> extends KafkaAvroDeserializer {
    private Schema readerSchema;
    
    protected GenericKafkaAvroDeserializer(Class<V> type, Map<String, ?> configs) {
	    this(type, configs, false);
    }
    
    protected GenericKafkaAvroDeserializer(Class<V> type, Map<String, ?> configs, boolean isKey) {
	    readerSchema = ReflectData.get().getSchema(type);
	    configure(configs, isKey);
    }
    
    @Override
    public Object deserialize(String s, byte[] bytes) {
	    return deserialize(bytes, readerSchema);
    }
}
```

**Comment by garyrussell** [comment]
Thanks; it is clear now.

Your work around sounds good.
