### ISSUE TITLE
Possible performance issues with Spring Kafka 

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-kafka#204]
While investigating https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/71 I have created https://github.com/mbogoevici/performance-measurements for a comparative analysis of the binder, the Spring Kafka client and the native client.

The producer application needs to be run once to fill a topic and then the various consumers can be used for draining it (for Spring Cloud Stream it needs to change the consumer group between executions).

At a first pass, the binder-based consumer and the Spring Kafka consumer have a pretty similar behaviour and consume messages at significantly lower rate than the native consumer. (i.e. will complete the draining of the topic in about 30-40 seconds vs about 5 in the former case).

**Comment by mbogoevici** [comment]
Some updates on this: the problem seems local to macOS (in particular Sierra). Re-testing this on Linux shows a completely different performance profile, where the three variants (native, spring-kafka and spring-cloud-stream) complete more consistently.

**Comment by artembilan** [comment]
Thank you for sharing, @mbogoevici!

Just curious: how did you realize that the problem is with MacOS when we have there flesh disk and in the end all your tests use the same Kafka? What has forced you to go to Linux for testing?

**Comment by mbogoevici** [comment]
@artembilan 
it is the same machine (dual-booting Mac and Linux), so we can rule out hardware differences. Sierra in particular is  notoriously buggy.  I went to Linux because I just wanted a second series of tests, and the results were unbelievably bad. It would be interesting to test in a different environment though and to repeat this.

Expanding the tests, I can still see some differences where for example Spring Kafka brings in messages at about 500K msgs/second (at 1000 bytes size), whereas the binder reports 200-250K msgs per second, so probably we can look at some optimizations in the binder  (although we're talking about overheads of 1-2 microseconds per message, which may be largely offset by any meaningful application code).

**Comment by mbogoevici** [comment]
Closing this for now, but leaving as reference in case someone runs into similar issues.

**Comment by ltalhouarne** [comment]
@mbogoevici Thanks a lot for looking into this.

**Comment by mbogoevici** [comment]
@ltalhouarne Thanks for using Spring Cloud Stream and Spring Kafka and for reporting the issues you're running into. we're glad to help.

**Comment by artembilan** [comment]
OK! Anyway, let's come back to this tomorrow when I run your tests here on Windows 😀!

**Comment by garyrussell** [comment]
There was some discussion recently about "slow" Spring tests and Sierra (by @joshlong I think); some problem with `/etc/hosts`, IIRC the resolution was to add the output of `hostname` to the 127.0.0.1 entry (or something like that).

**Comment by mbogoevici** [comment]
@garyrussell Unfortunately, I had that set already in my `/etc/hosts` while I was running the tests.

**Comment by mbogoevici** [comment]
A further note on this - with the test project,  the 'native' client test app and the 'spring-kafka' client test app both display significant performance degradation compared to the CLI perf-test in macOS - even if the 'native' client seems to be faster (i.e. messages come in a different rates), and drastically different than on Linux for instance. Also, similar performance has been reported for El Capitan.
