### ISSUE TITLE
Missing interceptors for producer

### ISSUE THREAD

**Issue by nikoncode** [spring-projects/spring-kafka#2049]
Hi guys,

Do you have any plans to implement a producer interceptor? I know that Kafka provides `ProducerInterceptor` but it's not managed by spring. I also know that it can be hacked to pass bean using configuration methods.

There are other ways how to solve problem exists: use ProducerPostProcessor or AOP, but I am interested in more graceful way to do that.

**Comment by garyrussell** [comment]
There are no current plans, but contributions are welcome.
