### ISSUE TITLE
Memory leak with spring-kafka 2.8.0

### ISSUE THREAD

**Issue by wllianwd** [spring-projects/spring-kafka#2056]
Updating **Spring Boot 2.5.7** to **2.6.1** brings **spring-kafka 2.8.0**, in a service with a massive kafka producer it causes a memory leak.

![image](https://user-images.githubusercontent.com/3443152/147118442-dbd35c56-eb86-4727-b201-da854cffc83d.png)

![image](https://user-images.githubusercontent.com/3443152/147124316-b1eb6309-de75-46fc-8400-dd1aaa5a46b4.png)

![image](https://user-images.githubusercontent.com/3443152/147120310-22f9a1b7-cbbe-4703-8ae7-d5600c9b8b43.png)

Rolling back to Spring Boot 2.5.7 fix the issue.

Sample Producer:
```
@Component
class KafkaProducer(
    private val kafkaTemplate: KafkaTemplate<String, MyObject>,
    private val kafkaLoggerCallback: KafkaLoggerCallback
) {

    @Async
    @EventListener
    fun process(id, String, event: MyObject) {
        kafkaTemplate.send("topic", id, event).addCallback(kafkaLoggerCallback)
    }

}
```

**Comment by artembilan** [comment]
Sorry, that picture doesn't say anything to me about memory.
What objects and from where are eating the RAM, please?
Any simple Spring Boot project to reproduce?
Thanks

**Comment by wllianwd** [comment]
@artembilan I added some more info, I wonder if the issue is in **kafka-clients** ?

**Comment by artembilan** [comment]
OK. It still not clear from that picture how many objected of that instance (it scares be that `DefaultListableBeanFactory` is so big), but I wonder what if you rollback to Apache Kafka `2.8.1`: https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps ?

**Comment by artembilan** [comment]
I see there is Micrometer for metrics and Datalog for tracing.
So, your plane `@Component` is not enough to reproduce.
Please, provide for us a minimal Spring Boot sample to play with.

I don't see difference in the `org.apache.kafka.clients.producer.internals.RecordAccumulator` in those versions, so something else on top of it what controls its content and behavior...
But yeah, that's hard to judge. Perhaps I just cannot read that memory report properly to understand how those `RecordHeader` instances are kept in the `RecordAccumulator`...

**Comment by garyrussell** [comment]
I suggest you reach out to the Kafka folks, according the docs, the producer should not consume much more than 32Mb (by default); I don't see any changes to the default between 2.7.1 and 3.0.0.

https://kafka.apache.org/documentation/#producerconfigs_buffer.memory

>The total bytes of memory the producer can use to buffer records waiting to be sent to the server. If records are sent faster than they can be delivered to the server the producer will block for `max.block.ms` after which it will throw an exception.

>**This setting should correspond roughly to the total memory the producer will use,** but is not a hard bound since not all memory the producer uses is used for buffering. Some additional memory will be used for compression (if compression is enabled) as well as for maintaining in-flight requests.

(my emphasis)

**Comment by wllianwd** [comment]
I can confirm that downgrading kafka-clients to 2.7.1 fix the issue.
As you can see below:
* The green line around 16:40 is the service using kafka-clients 2.7.1
* The purple line around 16:55 is without downgrading, that means kafka-clients 3.0.0

![image](https://user-images.githubusercontent.com/3443152/147265331-c745c460-4810-4b23-bace-79e00f2756f0.png)

Al I did was this:
```
    <properties>
        ...
        <kafka.version>2.7.1</kafka.version>
    </properties>
```

**Comment by artembilan** [comment]
OK. Sounds like an Apache Kafka issue by itself.
Did you try with `<kafka.version>2.8.1</kafka.version>`?

Any chances that you can make just a plain Apache Kafka project (without Spring and tracing) and report it to Apache Kafka by itself?

**Comment by wllianwd** [comment]
I'll try with `2.8.1` and anyway try to report directly to kafka project.

@artembilan @garyrussell thanks for your support :)

Shall I close this issue here?

**Comment by artembilan** [comment]
Yes, you can, but please, link back here when you raise an issue for Apache Kafka project, so we will know what is going on their side.
Thanks

**Comment by garyrussell** [comment]
Awaiting link to Kafka JIRA.

**Comment by wllianwd** [comment]
Here the kafka JIRA: https://issues.apache.org/jira/browse/KAFKA-13597

**Comment by garyrussell** [comment]
According to the last comment, the issue was caused by an incompatible producer interceptor.

https://issues.apache.org/jira/browse/KAFKA-13597?focusedCommentId=17477981&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17477981
