### ISSUE TITLE
Partial positive acknowledge support for BatchAcknowledgingMessageListener

### ISSUE THREAD

**Issue by bgK** [spring-projects/spring-kafka#2066]
**Affects Version(s):** 2.8.1

When consuming records using a batch listener, I would like to be able to commit the offsets for records up to a specific index in the batch, and then keep processing the batch until all the records are processed, without having to yield control back to the container.

In our case, some of the records can be handled together when they are consecutive, for improved performance. When consuming a record, I would like to be able to check if it can be grouped with some of the next records in the batch. If so, create a sub batch, handle it, and then commit the offsets for the last handled index in the batch. Proceed that way until the whole batch has been handled.

Adding the following method to the `org.springframework.kafka.support.Acknowledgment` interface seems like a suitable API change for the use case:

```java
    void acknowledge(int index);
```

**Comment by smaillns** [comment]
Any update ?

**Comment by garyrussell** [comment]
Not at this time; I can probably take a look at it in a couple of weeks.

**Comment by garyrussell** [comment]
@bgK @smaillns  PR issued; sorry for the delay.

**Comment by bgK** [comment]
@garyrussell Thanks! I ran some tests, works fine for me.

I noticed a small copy and paste typo here:
https://github.com/spring-projects/spring-kafka/blob/4ed8023e6403350f59a12203401967a01c9ed660/spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java#L62

**Comment by garyrussell** [comment]
Thanks for testing; fixed the copy/paste.
