### ISSUE TITLE
Failed to create bean with name embeddedKafka on Windows 10 machine

### ISSUE THREAD

**Issue by skpandey91** [spring-projects/spring-kafka#2073]
**Affects Version(s):** \<Spring for Apache Kafka version>

Hi ,

**After I upgrade spring-kafka to 2.8.0 from 2.7.x. My test cases using Embeded kafka are failing with below error on Windows but passing on Linux.**

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: C:\Users\xxx\AppData\Local\Temp\spring.kafka.185f9fca-3e31-4425-8363-bd457ce888547164466084250575279

See below git hub example.
[example](https://github.com/skpandey91/spring-kafka-test)
Please try to run it on Windows 10 machine with mvn clean install command

**Comment by garyrussell** [comment]
Duplicates https://github.com/spring-projects/spring-kafka/issues/2018

This is a known Kafka 3.0.0 bug; see the documentation for how to downgrade the kafka jar versions until 3.0.1 is available.

https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps

**Comment by garyrussell** [comment]
The current 2.8.x version is 2.8.2.
