### ISSUE TITLE
Spring Dev Tools breaks @KafkaHandler

### ISSUE THREAD

**Issue by Venthe** [spring-projects/spring-kafka#2079]
**Problem**
When using Spring Devtools, @KafkaHandler does not pick up the method to handle a message payload
`org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.kafka.KafkaException: No method found for class [redacted] dto.BanknotesTrustMessage`.
Removing of said dependency fixes the issue.

**Environment**
```
org.springframework.boot:spring-boot-devtools:transient (2.5.6)
org.springframework.cloud:spring-cloud-dependencies:2020.0.3
org.springframework.kafka:spring-kafka:transient (2.7.8)
org.springframework.boot:spring-boot-starter-parent:2.5.6
```

**Minimal code, details ommited**
```java
class Dto {}

@Service
@KafkaListener(
        topics = "${ex-kafka-topic}",
        groupId = "${ex-consumer-group}"
)
public class TrustDealService {
    @KafkaHandler
    public void handler(Dto message) { }
}
```

**Investigation & culprit**
See `org.springframework.kafka.listener.adapter.DelegatingInvocableHandler@307`, `methodParameter.getParameterType().isAssignableFrom(payloadClass)`

Problem is related to different class loaders for classes from payload and handler method, see attachements.

![methodParameter.getParameterType()](https://user-images.githubusercontent.com/1686874/150708192-0ca1ae1c-ccbf-42d1-b848-4dc950e73fd0.png)

![payloadClass](https://user-images.githubusercontent.com/1686874/150708208-ba8c9834-54af-4441-b84e-8f49e7749e04.png)

**References**
https://stackoverflow.com/questions/5375349/class-instance-obtained-through-multiple-class-loader

**Expected outcome**
Spring Kafka matches the method irregardless of the class loader

**Comment by garyrussell** [comment]
Most likely a class loader issue because the deserializer (and its target class `Dto`) is loaded by a different class loader to the listener class.

Try adding the deserializer instance to the `DefaultKafkaConsumerFactory` (via constructor or setter), instead of using consumer properties, so that the the same class loader is used for both.

**Comment by garyrussell** [comment]
Or, if you only have one `@KafkaHandler` method - move the `@KafkaListener` to the method instead, and then use a `ByteArrayDeserializer` and a `JsonMessageConverter`.

**Comment by Venthe** [comment]
> Or, if you only have one `@KafkaHandler` method - move the `@KafkaListener` to the method instead, and then use a `ByteArrayDeserializer` and a `JsonMessageConverter` (assuming you are currently using the `JsonDeserializer`).

Not possible, multiple listeners

> Try adding the deserializer instance to the DefaultKafkaConsumerFactory (via constructor or setter), instead of using consumer properties, so that the the same class loader is used for both.

It's easier for me to just remove dev tools instead of using a workaround like this, but thanks.

**Comment by garyrussell** [comment]
There is nothing more we can do; Kafka loads the classes, not Spring.
