### ISSUE TITLE
Cannot assign null value into backOffFunction when using kotlin

### ISSUE THREAD

**Issue by chanhyeong** [spring-projects/spring-kafka#2092]
**Affects Version(s):** over 2.6.x

![image](https://user-images.githubusercontent.com/10507662/152167381-65ec75b5-b97a-4be7-b67b-71da7bd3a03f.png)

Can't put null value to `FailedRecordProcessor#setBackOffFunction`
This is a similar issue with #1988 

It is a nullable field because there is a logic like below
https://github.com/spring-projects/spring-kafka/blob/676a5ad667839b1b96240e1a87e8876d300479e2/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java#L215-L221

#### Versions
- kotlin: 1.5.31
- spring boot: 2.5.x
- spring kafka: 2.7.9

**Comment by garyrussell** [comment]
Why do you need to explicitly set it to `null`? It is already `null` by default.

**Comment by chanhyeong** [comment]
@garyrussell 
I implemented my error handler inheriting `SeekToCurrentErrorHandler` which has default BackOff.
(DEFAULT_FIXED_BACKOFF: FixedBackOff(0, 1))
And I want to have other BackOff Function for some exceptions, so I call `setBackOffFunction` in `handle` method like this.

```kt
// example of setBackOffFunction method
when (exception) {
    is SomeException-> super.setBackOffFunction { _, _ ->
        FixedBackOff(exception.intervalMillis, exception.maxAttempts)
    }
    ...
    else -> ...
}
```

The backOffFunction will be used for next error handling if I don't set to null. So I want to clear this backOffFunction.
It can be null in Java and I think it also should be able in kotlin.

```kt
// whole code samples

setBackOffFunction()

try {
    SeekUtils.recover(...)
} finally {
    clearBackOffFunction()
}

private fun clearBackOffFunction() {
    super.setBackOffFunction(DEFAULT_BACKOFF_FUNCTION)
}
```

I implemented like this and I set backOffFunction which has sample value with default (passed value on constructor)

**Comment by garyrussell** [comment]
I agree the change is correct, but I just needed to understand your use case.

That said, it is not really best practice to change the function at runtime; why not just create a function that returns that returns `null` when you want the default `BackOff` to be used. See the javadocs.

```java
	/**
	 * Set a function to dynamically determine the {@link BackOff} to use, based on the
	 * consumer record and/or exception. If null is returned, the default BackOff will be
	 * used.
	 * @param backOffFunction the function.
	 * @since 2.6
	 */
	public void setBackOffFunction(BiFunction<ConsumerRecord<?, ?>, Exception, BackOff> backOffFunction) {
```

**Comment by chanhyeong** [comment]
Thanks.

> why not just create a function that returns that returns null when you want the default BackOff to be used.

I couldn't think about that. Thank you for your answer
