### ISSUE TITLE
@EmbeddedKafka zkSessionTimeout default value

### ISSUE THREAD

**Issue by Fr0z3Nn** [spring-projects/spring-kafka#2109]
Hi, spring-kafka team,

**Expected Behavior**

@EmbeddedKafka zkSessionTimeout should was 18000 by default.

**Current Behavior**

I see that your annotation @EmbeddedKafka has zkSessionTimeout 6000.

**Context**

I think change this default value will protect from unexpected fall. 
You can check it changes in Kafka Team project
https://cwiki.apache.org/confluence/display/KAFKA/KIP-537%3A+Increase+default+zookeeper+session+timeout
I got unexpected fall in my cloud integration test with 1% chance caused by
org.apache.zookeeper.ClientCnxn$SessionTimeoutException and after changes zkSessionTimeout to 18000 it worked properly

**Comment by garyrussell** [comment]
I already patched it 😄
