### ISSUE TITLE
ListenerContainerFactoryConfigurer not public

### ISSUE THREAD

**Issue by on-delete** [spring-projects/spring-kafka#2117]
As stated in this commit: https://github.com/spring-projects/spring-kafka/commit/95fc922af41fe3a235211c17cc45414532596498
the loglevel for `KafkaBackoffException` was set to DEBUG, but you could change it by providing a custom `ListenerContainerFactoryConfigurer` (from the example). But this `ListenerContainerFactoryConfigurer` is package-private, so you cannot instantiate a new one from another class (e.g. your @Configuration class). Am i missing something here?

**Comment by artembilan** [comment]
We can change that ctor to `public`, indeed.
But then many other `private` methods would have to become `protected` to let extensions to call them conveniently.

However I wonder if this one works for you:
```
@PostConstruct
public void setup(ListenerContainerFactoryConfigurer configurer) {
    configurer.setErrorHandlerCustomizer(commonErrorHandler -> ((DefaultErrorHandler) commonErrorHandler).setLogLevel(KafkaException.Level.WARN));
}
```

CC @tomazfernandes
