### ISSUE TITLE
Spring kafka for 0.10

### ISSUE THREAD

**Issue by dilipthelip** [spring-projects/spring-kafka#212]
Hi ,

We are using org.springframework.kafka:spring-kafka:1.1.1.RELEASE in one of our project.

I recently heard spring-kafka does not have support for 0.10 kafka yet. 

Does anyone know supporting version of spring-kafka that supports 0.10 ?

**Comment by stepio** [comment]
Hi,

Versions `1.1.x.RELEASE` depend on Kafka `0.10.0.1`, you may see the same in `build.gradle`:
https://github.com/spring-projects/spring-kafka/blob/70980019f1b8382ea9c6516458be30a09bf506a5/build.gradle

**Comment by dilipthelip** [comment]
Nice. Thanks for the update @stepio
