### ISSUE TITLE
Add Utility to Log ProducerRecord Metadata Only

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2132]
e.g.

https://github.com/spring-projects/spring-kafka/blob/38ed222a305e3b5f363ac51393da2d1c046fabd0/spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java#L381

https://github.com/spring-projects/spring-kafka/blob/38ed222a305e3b5f363ac51393da2d1c046fabd0/spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java#L399

Need an option to just log the metadata.

https://stackoverflow.com/questions/71244102/spring-kafka-replyingkafkatemplate-logs-full-details-instead-of-metadata-only-wh

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-kafka/commit/891664b63a647a4956f5be94cb39ebf79a6c0055 and back-ported to 2.8.x, 2.7.x

**Comment by artembilan** [comment]
Closed according the previous comment.
