### ISSUE TITLE
Consider using Serializer<?> for the delegates of DelegatingByTypeSerializer

### ISSUE THREAD

**Issue by v-chernyshev** [spring-projects/spring-kafka#2140]
**Expected Behavior**

I've tried using the newly added assignable types support and, initially, wrote the following code:

```java
final var delegates = new LinkedHashMap<Class<?>, Serializer<?>>();
delegates.put(Message.class, new ProtobufMessageSerializer());
delegates.put(byte[].class, new ByteArraySerializer());

return new DefaultKafkaProducerFactory<>(
        this.springProperties.buildProducerProperties(),
        new VoidSerializer(),
        new DelegatingByTypeSerializer(delegates, true));
```

Where `ProtobufMessageSerializer` is a custom type that can handle any protobuf message. Unfortunately, the code does not compile because the constructor of `DelegatingByTypeSerializer` and the internal member variables all expect to see the raw `Serializer` type. It is, of course, possible to tweak the code to:

```java
final var delegates = new LinkedHashMap<Class<?>, Serializer>();
```

But then a warning is raised to highlight the usage of raw types. Generally we treat this warning type as an error.

**Current Behavior**

I am basically forced to do this instead to silence the warning:

```java
@SuppressWarnings("rawtypes")
final var delegates = new LinkedHashMap<Class<?>, Serializer>();
```

**Context**

Our project uses the retryable topics feature, `@SendTo` and the `ErrorHandlingDeserializer` class to intercept potential poison pill messages. They are, however, extremely unlikely to happen, so I'd like to make sure that the first delegate that's checked at runtime is the base protobuf `Message` class. As far as I know, the only way to guarantee the iteration order is to explicitly populate a `LinkedHashMap`, but creating such a map requires warning suppression.

**Comment by garyrussell** [comment]
Unfortunately, that doesn't work:
<img width="688" alt="Screen Shot 2022-03-01 at 3 04 50 PM" src="https://user-images.githubusercontent.com/483832/156240678-96cb9a64-dfa0-4cfb-a1d5-ed5faa9cbb35.png">


>The method serialize(String, Headers, capture#6-of ?) in the type Serializer<capture#6-of ?> is not applicable for the arguments (String, Headers, Object)

Which is why I had to use raw types here in the first place.

**Comment by garyrussell** [comment]
Unfortunately, that won't work.
<img width="688" alt="Screen Shot 2022-03-01 at 3 04 50 PM" src="https://user-images.githubusercontent.com/483832/156242156-710f9311-6913-4b7d-8aa2-f3da23e3e241.png">

>The method serialize(String, Headers, capture#6-of ?) in the type Serializer<capture#6-of ?> is not applicable for the arguments (String, Headers, Object)

This is why I used raw types in the first place.

This compiles 

```java
@Override
public byte[] serialize(String topic, Headers headers, Object data) {
	Serializer<? super Object> delegate = findDelegate(data, this.delegates);
	return delegate.serialize(topic, headers, data);
}
```

But now we can't create the instance:

<img width="905" alt="Screen Shot 2022-03-01 at 3 17 57 PM" src="https://user-images.githubusercontent.com/483832/156242424-5de9461d-c6bd-494f-91bf-42006d824192.png">

>The constructor DelegatingByTypeSerializer(Map<Class<? extends Serializable>,Serializer<? extends Serializable>>, boolean) is undefined
