### ISSUE TITLE
Web documentation ToC missing items

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-kafka#2142]
The online documentation for 2.x is missing items after 4 as can be seen in this screenshot:
<img width="1626" alt="Screen Shot 2022-03-01 at 01 44 06" src="https://user-images.githubusercontent.com/76525045/156217506-dfdff2bb-6500-43fe-b7be-4d815f77411d.png">

Building it locally it displays correctly:
![Screen Shot 2022-03-01 at 14 33 32](https://user-images.githubusercontent.com/76525045/156219269-94623d16-4f2f-45e1-9fb9-2f2ded4067fe.png)

And for 3.0.0 it also displays correctly both locally and on the web:
![Screen Shot 2022-03-01 at 14 34 37](https://user-images.githubusercontent.com/76525045/156219393-7a0489fe-ed0b-430a-bab4-89cd0470d8d2.png)

Not sure if it might be a matter of rebuilding / redeploying.

**Comment by tomazfernandes** [comment]
As a side note, I see a fellow developer added his name to the docs' writers - I thought such space was for the project's founders or maybe team members only. Since I've written a whole chapter and made quite a few changes and additions elsewhere, would it make sense if I added my name to it as well? No worries if it doesn't.

Thanks

**Comment by artembilan** [comment]
Hi, @tomazfernandes !

You know it is OK, not only from local build. The latest available snapshot is good: https://docs.spring.io/spring-kafka/docs/2.8.4-SNAPSHOT/reference/html/.

So, no need to worry about this matter any more: it was fixed somehow in between.

Yes, you are feel free to add your name to the author list: we do that when contributor does a significant addition to the doc.

Thank you!

**Comment by tomazfernandes** [comment]
Oh, I see, that's good news it's fixed then. I was following the links at https://spring.io/projects/spring-kafka#learn , seems like it's one version behind there.

Well, it'll be an honor being in such prestigious company, thanks! I should submit this change later today.

**Comment by artembilan** [comment]
Thanks for the poitner, @tomazfernandes !

Have just fixed all the versions to the actual

**Comment by tomazfernandes** [comment]
Nice! I have a PR open with a documentation update, added my name there, hope it's ok, LMK otherwise.

Feel free to close this issue if you think that's the case.

Thanks!

**Comment by artembilan** [comment]
Fixed in the current SNAPSHOT
