### ISSUE TITLE
Implementation of waitListening("foo") ?

### ISSUE THREAD

**Issue by chrc** [spring-projects/spring-kafka#215]
Hi,

Into the page http://docs.spring.io/spring-kafka/reference/html/_introduction.html#_with_java_configuration

```
@Autowired
private Listener listener;

@Autowired
private KafkaTemplate<Integer, String> template;

@Test
public void testSimple() throws Exception {
    waitListening("foo");
    template.send("annotated1", 0, "foo");
    assertTrue(this.listener.latch1.await(10, TimeUnit.SECONDS));
}
...
```
how do you implemente  the function **waitListening("foo")** ?

Thx

**Comment by artembilan** [comment]
Well, there is no such a functionality any more:
```
private void waitListening(String id) throws InterruptedException {
		MessageListenerContainer container = registry.getListenerContainer(id);
		@SuppressWarnings("unchecked")
		KafkaMessageListenerContainer<Integer, String> kmlc =
				((ConcurrentMessageListenerContainer<Integer, String>) container).getContainers().get(0);
		int n = 0;
		while (n++ < 6000 && (kmlc.getAssignedPartitions() == null || kmlc.getAssignedPartitions().size() == 0)) {
			Thread.sleep(100);
		}
		assertTrue(kmlc.getAssignedPartitions().size() > 0);
}
```
That has evolved to the `ContainerTestUtils`. 

But at the same time that test-case against real Kafka interaction doesn't need any waiting tricks.
The sample for the Reference Manual has been extracted from this test: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

I'll fix that docs soon.

Thank you for catching and sharing doubts!

**Comment by chrc** [comment]
Thank you a lot :)
