### ISSUE TITLE
RetryableTopic - provide a mechanism to suppress non-essential headers

### ISSUE THREAD

**Issue by v-chernyshev** [spring-projects/spring-kafka#2155]
**Expected Behavior**

I'd like to have a way to suppress the generation of the exception headers as they are quite verbose and drastically increase the size of the messages.

**Current Behavior**

Exception information headers are unconditionally added in this function: https://github.com/spring-projects/spring-kafka/blob/dc47e72a374dbfd5893d79e6dc841bc90d44362d/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L363-L364

**Context**

In our application the initial attempt is quite likely to fail as we have to wait for data to be available in an external system that does not provide native notifications.  The current retryable topics implementation adds a number of exception-related headers, including the full stacktrace information. When combined they increase the average message size from a couple hundred bytes to approximately 10 kilobytes. For us this overhead is hard to ignore.

Unfortunately, I do not see any way to hook into the header generation process. `setHeadersFunction` cannot be used as it is already customised by the recoverer factory: https://github.com/spring-projects/spring-kafka/blob/dc47e72a374dbfd5893d79e6dc841bc90d44362d/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java#L139

The only workaround I can think of is to add a custom producer interceptor that strips the headers out of the records, but then the CPU resources are wasted on rendering the information that is almost immediately thrown away. It would be nice to avoid generating these headers in the first place.

**Comment by tomazfernandes** [comment]
Possibly related to [this SO question](https://stackoverflow.com/questions/71379877/how-to-add-custom-header-while-sending-message-to-dlt-using-spring-kafka-non-blo).

But I think it might be worth it to have a dedicated option not to include the stacktrace in `DeadLetterPublishingRecoverer`.

**Comment by v-chernyshev** [comment]
Yeah, even if I get access to the original header function via reflection it won't help with suppressing the generation of the headers that are not strictly required. The reason for it is that `this.headersFunction.apply` is called after all the exception headers have already been set up.

**Comment by garyrussell** [comment]
I suggest we add something like 

```java
public interface HeaderCreator {

    void create(Headers kafkaHeaders, Exception exception, boolean isKey); 

}
```

with the default being `this::addExceptionInfoHeaders`

WDYT?

**Comment by v-chernyshev** [comment]
Something like `setExceptionHeaderCreator` would indeed allow me to provide a no-op implementation, which would solve this particular problem. Should `this.headerNames.exceptionInfo` be passed into the `create` method too? Given the comment here:

https://github.com/spring-projects/spring-kafka/blob/3c9e00fae5c8ec2c8608048eb63fce62f644fdad/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L635-L643

It is possible to replace the header names. Having programmatic access to this data could make the code a bit more generic. Although, admittedly, if the header names are replaced then you also know what they are.

**Comment by garyrussell** [comment]
Oh, because you might want to add just some of the headers (e.g. all except the full stack trace).

That makes sense.

Another option would be to add a `BitSet` to represent which exception headers to add, which would be simpler for most users, but still provide the hook to completely configure your own headers.

**Comment by tomazfernandes** [comment]
I think the solution seems great.

Just a thought, for the SO issue, considering we already have a `setHeadersFunction` for adding new headers in `DLPR`, we might have a similar method in `DLPRF`, to be called in `addHeaders`.

**Comment by garyrussell** [comment]
Why would we need to add a setter to the factory, given that we already have a setter for a DLPR customizer? (Or maybe I misunderstand your comment).

**Comment by tomazfernandes** [comment]
`DLPR` already has a header configuration method - `setHeadersFunction` - but we are using it for the RT feature's header management. The way I suggested we would add additional complexity only in the feature's component, not having to add any additional complexity to `DLPR` to address what seems to be a RT's matter.

Also, I think the resulting API would be simpler, since the user would have an explicit method for handling this in the feature's component, instead of having to go through the customizer and knowing to use a different method than the `setHeadersFunction` there.

Of course, that's only a way of looking into this. Makes sense?

**Comment by garyrussell** [comment]
Good point; will add that too. PR coming soon...
