### ISSUE TITLE
Minor Javadoc Issue

### ISSUE THREAD

**Issue by tunix** [spring-projects/spring-kafka#2162]
The javadoc states that this method doesn't apply to batch listeners but it should?

https://github.com/spring-projects/spring-kafka/blob/bee97d9c8fcc1f9489b4244a653ef19b4f8abc83/spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java#L336

**Comment by garyrussell** [comment]
Thanks; merged and cherry-picked to supported branches.
