### ISSUE TITLE
Deprecate Producer Listener

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2163]
Now that `ProducerInterceptor` is available.

https://github.com/spring-projects/spring-kafka/pull/2112

**Comment by viktorardelean** [comment]
@garyrussell, I can work on this. Could you please assign it to me?

**Comment by garyrussell** [comment]
Thanks!

We usually use `@deprecated since 3.0 in favor of #setProducerInterceptor` in the javadocs.

Now that we are on JDK 17, we can also set the `since` and for `Removal` attributes on `@Deprecated`

**Comment by viktorardelean** [comment]
@garyrussell PR raised. Please have a look: https://github.com/spring-projects/spring-kafka/pull/2225

**Comment by garyrussell** [comment]
Closing as invalid - the `ProducerInterceptor` does not have access to the outbound record.
