### ISSUE TITLE
RetryableTopic - breaking changes in the error handler

### ISSUE THREAD

**Issue by v-chernyshev** [spring-projects/spring-kafka#2184]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.4.

**Describe the bug**

`ListenerContainerFactoryConfigurer` now creates its error handler here:

https://github.com/spring-projects/spring-kafka/blob/93efeb4f604b5c96810a57bc584c18c194b7c321/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java#L235-L246

There are two breaking changes/regressions compared to version 2.8.3:

- `createDefaultErrorHandlerInstance` no longer provides a "no retry" back off strategy by default. The outcome of this change is that a to-be-recovered record is retried 10 times instead of immediately being sent into the next recovery topic.
- `errorHandler.defaultFalse` completely disables the default classification of the fatal exceptions (such as `DeserializationException.class`). In fact, every classification request now returns `false`.

The second change causes every back off exception to be printed at error level due to the code here:

https://github.com/spring-projects/spring-kafka/blob/f0ad7b0c0b2005eb2fd58fd361eacbfe007c7284/spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java#L143-L164

`getClassifier().classify(thrownException)` now always returns false and `this.failureTracker.getRecoverer().accept` may throw a back off exception, which does not reach the following special back off exception handler any longer:

https://github.com/spring-projects/spring-kafka/blob/93efeb4f604b5c96810a57bc584c18c194b7c321/spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java#L109-L113

**To Reproduce**

Unfortunately, I do not have a sample right now, but I will try to prepare it this week. I believe that any application that uses the retryable topics recovery mechanism is impacted.

**Expected behavior**

I expect the default behaviour of the retryable topics recovery system to be identical to version 2.8.3.

**Comment by v-chernyshev** [comment]
A slight clarification regarding the back off exception handler changes. The passed `thrownException` may be a back off exception, but then it is unwrapped here:

https://github.com/spring-projects/spring-kafka/blob/93efeb4f604b5c96810a57bc584c18c194b7c321/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java#L176-L179

The `catch` statement of `getRecoveryStrategy` intercepts it and prints an error.

**Comment by tomazfernandes** [comment]
Hi @v-chernyshev, thanks for reporting this.

> 
> There are two breaking changes/regressions compared to version 2.8.3:
> 
> * `createDefaultErrorHandlerInstance` no longer provides a "no retry" back off strategy by default. The outcome of this change is that a to-be-recovered record is retried 10 times instead of immediately being sent into the next recovery topic.
> * `errorHandler.defaultFalse` completely disables the default classification of the fatal exceptions (such as `DeserializationException.class`). In fact, every classification request now returns `false`.

I don't see this behavior in my tests. Since all classifications now return `false` by default, they skip the 10 retrials, and only attempt retrials if you add exceptions to be retried on the `LCFC`. Any further details you can share on that would be appreciated.

> 
> The second change causes every back off exception to be printed at error level due to the code here:
> 
This one I can reproduce. The idea is that `KafkaBackOffException`s should be logged at it's own level, and we now set it to `DEBUG`. I'll try to come with a workaround for this while we look for the fix.

**Comment by v-chernyshev** [comment]
> Just for clarification, the exception isn't unwrapped here, it's just thrown again.

Yes, you are absolutely right, I didn't phrase myself properly.

> I don't see this behavior in my tests. Since all classifications now return false by default

All right, I'll try to come up with an example based on our code, hopefully by the end of tomorrow. Thanks for looking into it!

**Comment by tomazfernandes** [comment]
@v-chernyshev ok, thanks. I'll keep looking for the behavior you described.

Can you just please check if by any chance you're adding exceptions to the `DeadLetterPublishingRecoverer` classification? That would be the most likely cause.

**Comment by v-chernyshev** [comment]
> Can you just please check if by any chance you're adding exceptions to the DeadLetterPublishingRecoverer classification? That would be the most likely cause.

Yes, your guess is correct. In my tests I added all the default exceptions back via `setClassifications` and replaced the default value with `true` to partialyl return the 2.8.3 behaviour. The now default back off strategy, however, has `this.noRetries` in `FailedRecordTracker.recovered` set to false, so the else branch is picked. Then `nextBackOff` is equal to zero, the thread sleeps for 10 milliseconds in `ListenerUtils.stoppableSleep` and then `false` is returned from the method.

**Comment by tomazfernandes** [comment]
We have this logic in `FailedRecordProcessor.getRecoveryStrategy`:

```
if (getClassifier().classify(thrownException)) {
	return this.failureTracker::recovered;
}
else {
	try {
		this.failureTracker.getRecoverer().accept(records.get(0), recoveryConsumer, thrownException);
		this.failureTracker.getRetryListeners().forEach(rl -> rl.recovered(records.get(0), thrownException));
	}
```

Since the classification returns false, it should go to the else branch which has no sleep, which is what happens on my tests.

Looks right?

**Comment by tomazfernandes** [comment]
Ok, so just to make sure we're on the same page. Functionality-wise the framework is behaving as expected - it only retries when it should.

The problem at hand is that `KafkaBackOffException`s are being logged as ERROR - and that's what caught your attention in the first place.

Does that sound about right?

**Comment by tomazfernandes** [comment]
We've documented the changes [here](https://docs.spring.io/spring-kafka/reference/html/#x28-retryable-topics-changes)

**Comment by v-chernyshev** [comment]
Thanks for the link, somehow I've missed this section. And yes, all of it started with the back off exceptions showing up in the logs, which is the only issue. Everything else is due to my misunderstanding of the changes, sorry for the confusion.

**Comment by tomazfernandes** [comment]
No problem, I totally understand that starting to see `ERROR` logs everywhere would lead to worries.

It was really good that you brought this up early - now we had a chance to double check the behavior and see that the changes we made are ok functionality-wise, and can also start looking for a workaround and fix for the logs. So thanks a lot for that.

Specially because, well, if that's really the case, people should be seeing these logs everywhere, so I expect to see this issue popping around again here and on StackOverflow.

It also occurred to me that the `KafkaBackOffException` may get in the way of the blocking retries and count against them, so I'll also look into that.

**Comment by tomazfernandes** [comment]
`KafkaBackOffException` doesn't get in the way of blocking retries because those are opt-in and so the user would have to explicitly add KBOE to the classification list. At least one integration test failed when I added it, so we seem to be covered there. 

One unexpected side effect though is that `retryListeners` are notified of the `KafkaBackOffException` with `recoveryFailed`, so that might be a problem to some users.

**Comment by tomazfernandes** [comment]
As for the workaround, this one based on what you suggested worked out for me:

```
@Bean(name = RetryTopicInternalBeanNames.LISTENER_CONTAINER_FACTORY_CONFIGURER_NAME)
public ListenerContainerFactoryConfigurer lcfc(KafkaConsumerBackoffManager kafkaConsumerBackoffManager,
						DeadLetterPublishingRecovererFactory deadLetterPublishingRecovererFactory,
						@Qualifier(RetryTopicInternalBeanNames
						    .INTERNAL_BACKOFF_CLOCK_BEAN_NAME) Clock clock) {
	ListenerContainerFactoryConfigurer lcfc = new ListenerContainerFactoryConfigurer(kafkaConsumerBackoffManager, deadLetterPublishingRecovererFactory, clock);

	lcfc.setBlockingRetriesBackOff(new FixedBackOff(0, 0));
	lcfc.setErrorHandlerCustomizer(eh -> ((DefaultErrorHandler) eh).setClassifications(Collections.emptyMap(), true));
	return lcfc;
}
```

**Comment by tomazfernandes** [comment]
@v-chernyshev, I opened a PR with a fix for the log issue, if you're able to take a look it'd be great. It's a simple one but those are the worst 😄 

I'm not sure `retryListeners` being notified with the `KafkaBackOffException` on `recoveryFailed` is a bug or a feature, but seems it's been like that since before the last version changes, so since no one is complaining I left it that way.

Thanks

**Comment by v-chernyshev** [comment]
@garyrussell @tomazfernandes I'm afraid that this problem has started happening again in version 2.9.0 with seeks after error set to false. A `KafkaBackoffException` thrown here:

https://github.com/spring-projects/spring-kafka/blob/51db0b6ecca9514686b4c138de69a1d9efe80664/spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerPartitionPausingBackOffManager.java#L74-L83

Is then wrapped in a `ListenerExecutionFailedException` here:

https://github.com/spring-projects/spring-kafka/blob/51db0b6ecca9514686b4c138de69a1d9efe80664/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2395-L2397

Then it reaches this error handler:

https://github.com/spring-projects/spring-kafka/blob/51db0b6ecca9514686b4c138de69a1d9efe80664/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2694-L2697

Which calls `handleOne`:

https://github.com/spring-projects/spring-kafka/blob/51db0b6ecca9514686b4c138de69a1d9efe80664/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2825-L2827

This method is defined here:

https://github.com/spring-projects/spring-kafka/blob/51db0b6ecca9514686b4c138de69a1d9efe80664/spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java#L152-L163

The exception, quite rightfully, cannot be recovered, so `logger.error` is invoked. The end result is an error in the logs for every back-off.

**Comment by v-chernyshev** [comment]
Please let me know if I should submit a separate issue with these details.

**Comment by garyrussell** [comment]
Please open a new issue; this is not a regression but a problem with the new feature. We hoped that folks would try it out via the milestones/release candidate before it was formally released.

Thanks.

**Comment by v-chernyshev** [comment]
Thank you for the prompt reply.

> We hoped that folks would try it out via the milestones/release candidate before it was formally released.

Unfortunately, I have just found a bit of spare time to update the dependencies of the service that uses this feature 😞 I'll send new issues with the feedback based on my testing of version 2.9.0.
