### ISSUE TITLE
Consider providing custom KafkaSender to ReactiveKafkaProducerTemplate

### ISSUE THREAD

**Issue by MisterRnobe** [spring-projects/spring-kafka#2190]
**Context**

My application uses `spring-cloud-sleuth` for tracing so I want it to be propagated through kafka. I am using `ReactiveKafkaProducerTemplate` to send events but it does not support tracing propagation. Although, `spring-cloud-sleuth-instrumentation` contains `TracingKafkaProducerFactory` that creates required `KafkaSender`. I tried to copy-paste `ReactiveKafkaProducerTemplate` implementation with setting this `KafkaSender` and it works fine as expected.

I guess `ReactiveKafkaConsumerTemplate` needs the same mechanism

**Expected Behavior**

I think constructor with `KafkaSender` would be fine

**Current Behavior**

There is no way to provide custom `KafkaSender` for now

**Comment by artembilan** [comment]
Yes, feel free to contribute a `KafkaSender`-based extra ctor into this `ReactiveKafkaProducerTemplate`.

Perhaps something similar for the `ReactiveKafkaConsumerTemplate` based on the external `KafkaReceiver`.

Thanks

**Comment by breader124** [comment]
Hi, is this ticket still open for contributions? If so, I'd like to start working on it

**Comment by garyrussell** [comment]
Sure; thanks!
