### ISSUE TITLE
Transaciton not working if exception was thrown after 1 sec.  

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [spring-projects/spring-kafka#2196]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.0

**Describe the bug**

In a slow transactional method, messages are send even this method fails after 1s

**To Reproduce**

```
@GetMapping("/test")
    @Transactional
    public void test() {
        kafkaTemplate.send("top", "hello").addCallback(result -> {
            System.out.println("send succ");
        }, e -> {
            System.out.println("send failure");
        });
        Thread.sleep(1000);
        throw new IllegalStateException("test");
    }
```

**Expected behavior**

Consumers unable to consume such message.

**Comment by Nick-The-Uncharted** [comment]
I debugged and I am sure that  org.apache.kafka.clients.producer.KafkaProducer#beginTransaction and org.apache.kafka.clients.producer.internals.TransactionManager#maybeAddPartitionToTransaction was called.

**Comment by garyrussell** [comment]
Records are written to the log even if the transaction is rolled back - Kafka adds a marker record after the published records to indicate commit or rollback; consumers must be configured with `isolation.level=read_committed` to prevent them receiving rolled-back records.

**Comment by Nick-The-Uncharted** [comment]
@garyrussell Thank you very much, setting isolationLevel resolved my problem. I thought the default level was read_committed so I never think in the right direction.

**Comment by Nick-The-Uncharted** [comment]
@garyrussell I am trying to understand how transaction works in kafka. Do you know why didn't kafka broker just filter out all aborted partition data and send it to consumer? I saw current implentation is consumers did all the filtering in `org.apache.kafka.clients.consumer.internals.Fetcher.CompletedFetch#nextFetchedRecord`.

**Comment by garyrussell** [comment]
I have no idea. We don't have extensive knowledge of Kafka internals here; you'd be better off asking on one of their mailing lists. https://kafka.apache.org/contact
