### ISSUE TITLE
Metadata timeout on KafkaTemplate::send when using .completable().await() the second time 

### ISSUE THREAD

**Issue by m-kay** [spring-projects/spring-kafka#2199]
I'm using spring-kafka version 2.8.4 in spring-boot 2.6.5 with Kotlin 1.6.10 and JDK 17 in a reactive stack.

When I try to send 2 messages to 2 different topics and wait for each `send` to complete by calling `.completable().await()` the second call gets a TimeoutException while fetching topic metadata. If I use the kafka consumers blocking call `.get()` on the second call everything works fine. Can you explain this behavior somehow?

To reproduce the issue I created a small demo app where you can find the different implementations in [DemoController.kt](https://github.com/m-kay/kafka-template-coroutines-await/blob/main/src/main/kotlin/com/example/demo/DemoController.kt) and execute the tests in [DemoApplicationTests.kt](https://github.com/m-kay/kafka-template-coroutines-await/blob/main/src/test/kotlin/com/example/demo/DemoApplicationTests.kt)

**Comment by m-kay** [comment]
To me it does not seem to be a problem with Kotlin and coroutines because I can reproduce the same issue just using `Mono`, see my [updated test](https://github.com/m-kay/kafka-template-coroutines-await/blob/main/src/main/kotlin/com/example/demo/DemoController.kt#L40).

**Comment by garyrussell** [comment]
Wait - I see the problem - you are doing the second send on the Consumer's I/O thread; it can't fetch the metadata while it is, itself, blocked waiting for metadata.

>2022-03-30 09:59:44.576 INFO 63611 --- [ad | producer-1] com.example.demo.DemoController : sending message to topic 2

You need to hand off the send to another thread.

**Comment by garyrussell** [comment]
This works:

```kotlin
  @PostMapping("/mono")
  fun mono() : Mono<Void> {
      log.info("sending message to topic 1")
      val sent = Mono.fromFuture(kafkaTemplate.send("topic-1", "some key", "some value").completable())
              .publishOn(Schedulers.boundedElastic()) // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
              .flatMap{ first ->
                  log.info("sent message to topic 1 to partitition ${first.recordMetadata.partition()}")
                  log.info("sending message to topic 2")
                  Mono.fromFuture(kafkaTemplate.send("topic-2", "some key", "some value").completable())
                          .map { second -> log.info("sent message to topic 2 to partition ${second.recordMetadata.partition()}") }
              }
      return Mono.`when`(sent)
  }
```

I don't know if Kotlin coroutines support something similar.

**Comment by m-kay** [comment]
So it seems spring-kafka is not really safe to use in a reactive stack? Is there already something like spring-kafka-reactive using the [reactor-kafka](https://github.com/reactor/reactor-kafka) library?

**Comment by m-kay** [comment]
Just found the `ReactiveKafkaProducerTemplate` which seems to solve my problem. 

Thanks a lot for your support @garyrussell.

**Comment by garyrussell** [comment]
>So it seems spring-kafka is not really safe to use in a reactive stack?

It wasn't designed with that in mind.

>Just found the `ReactiveKafkaProducerTemplate` 

That template is a (very) lightweight wrapper around `reactor-kafka`'s sender. We expect to add tighter integration in the future.

Feel free to open feature suggestions for anything from `spring-kafka` you would like to see added.
