### ISSUE TITLE
Spring kafka throws deserialise error on null values when avro schema allows it

### ISSUE THREAD

**Issue by chris-gunawardena** [spring-projects/spring-kafka#2206]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**  
spring-kafka: 2.8.4
spring-boot:2.6.6
spring-core: 5.3.18
org.apache.avro:avro: 1.11.0

**Describe the bug**
When sending null as a value to a field that has the types specified in asvro schema as  string and null, spring-kafka thows the error: got null, expected string. Same message works fine in  kafka-avro-console-consumer 

See: https://www.youtube.com/watch?v=irO65pdmF-k

**To Reproduce**
Create a schema with a field that allows string and null types and send null as value to that field. 
eg: 
...
{
            "name": "foo",
            "type": [
                "null",
                "string"
            ],
     "doc": "some desc" 
},
...

In the video below I send kafka payloads from kafka-avro-console-producer to two consumers. One is kafka-avro-console-consumer and the other is spring-kafka listener. When I send null as value, the spring-kafka consumer throws error while  kafka-avro-console-consumer  has no issues.

https://www.youtube.com/watch?v=irO65pdmF-k

**Expected behavior**
Expect spring kafka to allow nulls as values if the avro schema allows it. 

**Sample**
Link below you can find the avro schema, working payload, non working payload, config & listener code.

https://gist.github.com/chris-gunawardena/a30d47660e3c1bec957e1cbd82d35814

**Comment by garyrussell** [comment]
<img width="766" alt="Screen Shot 2022-04-03 at 7 35 49 AM" src="https://user-images.githubusercontent.com/483832/161426002-5cac70ce-47af-4489-8a94-3f50a6bcf289.png">

Looking at the video, this clearly has nothing to do with Spring; the root cause of the exception is thrown by the Avro deserializer; well before Spring is inolved.

You need to raise this issue with Avro, not here.

**Comment by chris-gunawardena** [comment]
For anyone else that finds this, this was caused by setting kafka config to specific deserialiser while using a generic deserialiser in the listener.
