### ISSUE TITLE
nack with sleep 0ms causes ListenerConsumer to become stuck in infinite re-seek loop

### ISSUE THREAD

**Issue by SebastianGoeb** [spring-projects/spring-kafka#2224]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.4

**Describe the bug**

Calling `acknowledgment.nack(0, 0)` in `BatchAcknowledgingMessageListener#onMessage` causes `KafkaMessageListenerContainer.ListenerConsumer` to keep seeking to the previous offset on every record batch, even after subsequent calls to `acknowledgment.acknowledge()`.

`KafkaMessageListenerContainer.ListenerConsumer#nackSleep` defaults to -1, which is the unset state (no sleeping, no seeking to previous offset).

If set >= 0 (including zero), seeking to previous offset is activated (e.g. with `acknowledgement.nack(someIndex, 0)`)
```
// org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer#invokeBatchOnMessage:2206
if (this.nackSleep >= 0) {
	int index = 0;
	toSeek = new ArrayList<>();
```

However, only if set >0 (excluding zero), the subsequent call to `pauseForNackSleep()` deactivated seeking again.
```
// org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer#pauseForNackSleep:2497
if (this.nackSleep > 0) {
	this.nackWake = System.currentTimeMillis() + this.nackSleep;
	this.nackSleep = -1;
```

Calling `nack(0, 0)` hangs the entire ListenerConsumer and all partitions it handles forever, or until `nack(someIndex, >=1)` is called. The two if-conditions should probably be the same.

**To Reproduce**

Simple example for a working consumer, that gets stuck at some point, and then fixes itself:

```
@Component
public class MyConsumer implements BatchAcknowledgingMessageListener<String, Object> {
    private int executions = 0;

    @KafkaListener(topics = "mytopic")
    public void onMessage(List<ConsumerRecord<String, Object>> data, Acknowledgment acknowledgment) {
        executions++;
        if (executions == 10) {
            // 10th execution gets ListenerConsumer stuck in seek-loop
            acknowledgment.nack(0, 0);
        } else if (executions == 20) {
            // 20th execution unsticks ListenerConsumer
            acknowledgment.nack(0, 1);
        } else {
            // executions 0-9 advance offset normally
            // executions 10-19 always re-seek to the same offset (e.g. logging always Seeking to offset 123456 for partition mytopic-0)
            // executions 20+ advance offset normally again
            acknowledgment.acknowledge();
        }
    }
}
```

**Expected behavior**

`nack(0, 0)` should cause re-seek to previous offset, but subsequent `acknowledge()` should advance offset normally (no re-seek).

**Actual behavior**

`nack(0, 0)` causes re-seek to previous offset, and all subsequent calls to `acknowledge()` re-seek to the same offset, even though they shouldn't.

**Comment by tomazfernandes** [comment]
@garyrussell can probably look into this on Monday, but this should be related:

https://github.com/spring-projects/spring-kafka/issues/2214

**Comment by SebastianGoeb** [comment]
Yep, seems like the same issue.

**Comment by garyrussell** [comment]
Either use 1ms, or drop back to 2.8.3 until 2.8.5 is available next week.
