### ISSUE TITLE
Revise RetryTopicConfigurationSupport TaskExecutor Strategy

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-kafka#2239]
Currently we add a `ThreadPoolTaskExecutor` `@Bean` in `RetryTopicConfigurationSupport`. That might have undesirable side-effects such as making `Spring Boot`'s auto configuration back off from providing a default `TaskExecutor` for users.

We should investigate this further and if necessary look for alternatives.

**Comment by tomazfernandes** [comment]
I started looking into this, and TBH I think it's a slightly worse scenario than what I'd have thought.

Turns out when there is a `TaskExecutor` bean in the context, Boot's auto configured task executor does back off, as we supposed it would. That might already be bad enough, since auto configuration enables many task executor configurations that users may be relying on.

But what I think is the worst part is that there's logic in the `WebMvcAutoConfiguration#237` class that tries to fetch the auto configured task executor by name - since it's not there when we provide our own, it falls back to a `SimpleAsyncTaskExecutor` for the `RequestMappingHandlerAdapter`, which should be quite less performant than the default `ThreadPoolTaskExecutor` since it doesn't reuse threads.

I think this is really unexpected and weird behavior, but at least in my test application with Boot 2.6.6 that's how it goes.

I'm not sure what'd be a good move here - the less impactful thing I can think of would be if we'd go back to letting the `WakingTimingAdjuster` manage the `TaskExecutor` lifecycle, and maybe even having it instantiate it lazily on the first timing adjustment request.

Any thoughts?

Thanks.

**Comment by artembilan** [comment]
You know I think the `SimpleAsyncTaskExecutor` would be a good compromise for a default settings.
I see we use it in many-many place in all the Spring projects.
Using a `SimpleAsyncTaskExecutor` we won't need to worry about its lifecycle.
The end-user would have a choice for other `TaskExecutor` impls to inject otherwise.

**Comment by tomazfernandes** [comment]
Oh, that sounds great really. TBH, I have no clue of how frequently this timing adjuster kicks in in real life scenarios - it depends on too many factors. But as an overall default dependency for the feature, a full fledged `ThreadPoolTaskExecutor` indeed seems like too much.

I'll do some testing to see if it has any impact on actual precision and submit a PR with this change.

Please let me know if you think of anything else.

Thanks!

**Comment by garyrussell** [comment]
Actually, a SATE is probably not good here; especially with long delays; we could end up with many threads sleeping.

On the other hand too small a pool could cause some short delay to be queued behind longer delays for other partitions.

Maybe in 3.0, we should look at changing the logic to use a `TaskScheduler` instead, rather than sleeping the consumer thread?

**Comment by tomazfernandes** [comment]
Hmm, I didn't really know this `TaskScheduler` abstraction, looks interesting! I'll take a better look into it, but it does seem like a more proper approach than the current sleeping solution.

For clarification, the amount of time sleeping isn't actually related to the delay size. Every time we receive a `PartitionIdleEvent` for a backed off partition, we check if we're within 2 x `pollTimeOut` away from the `dueTimestamp`. If we are, we calculate how off we are from arriving at the due time in increments of pollTimeouts (`long adjustmentAmount = timeUntilDue % pollTimeout`), and then we sleep for this difference.

Let's say `pollTimeout` is `5000`, and we're `5500` ms away from the due time, we're going to sleep for `500` ms only. Of course, the larger the pollTimeout, the bigger the adjustment can get.

https://github.com/spring-projects/spring-kafka/blob/e1160fa75a599387134c052f0ebd96359a8fd2b6/spring-kafka/src/main/java/org/springframework/kafka/listener/WakingKafkaConsumerTimingAdjuster.java#L114-L127

A different solution might be having a single thread that runs through a list and wakes up the proper consumers at the proper time, but it seems the `TaskScheduler` would be simpler.

**Comment by tomazfernandes** [comment]
Also, there's a minimal `threshold` of `100ms` - adjustments below that won't be triggered. All these numbers are configurable, but I think most users should not really toy with these, that's why I didn't add it to the docs.

**Comment by tomazfernandes** [comment]
About this, considering all that's been said, I think it's worth it using the `SimpleAsyncTaskExecutor` for `2.9`, since with that we'd no longer keep `Spring Boot`'s `Executor` from auto configuring correctly. Also, if I understand correctly,  we'd not have the need to manage the `Executor` lifecycle.

Another option would be registering the `WakingTimingAdjuster` as a bean instead of the `Task Executor` and have it create and manage the `Executor`'s lifecycle directly.

For `3.0`  we can change the implementation to rely on the `TaskScheduler` instead.

WDYT?

Thanks

**Comment by tomazfernandes** [comment]
About this, considering all that's been said, I think it's worth it using the `SimpleAsyncTaskExecutor` for `2.9`, since with that we'd no longer keep `Spring Boot`'s `Executor` from auto configuring correctly. Also, if I understand correctly,  we'd not have the need to manage the `Executor` lifecycle.

Another option would be registering the `WakingTimingAdjuster` as a bean instead of the `Task Executor` and have it create and manage the `Executor`'s lifecycle directly.

For `3.0`  we can change the implementation to rely on the `TaskScheduler` instead.

WDYT?

Thanks

**Comment by artembilan** [comment]
Even if a `TaskScheduler` solution is better, we still have a problem with abusing auto-configuration. It is fully similar to what we have discussed above about a `TaskExecutor`.

I guess I need to investigate more in Spring Boot what and how they do with many `TaskExecutor`/`TaskScheduler` beans. 

I recently changes Spring Integration to rely on the auto-configured `TaskScheduler`, but I cannot say yet what is going with the `AbstractMessageBrokerConfiguration` and its `TaskExecutor`/`TaskScheduler` beans...

**Comment by tomazfernandes** [comment]
How about the idea of turning the `WakingTimingAdjuster` to a bean and having it manage the `TaskExecutor` directly? This way we leave auto configuration issues out, and can change the implementation later.

The issue I see with that is that currently we have an option of not having a `TimingAdjuster` - not sure if we can still have that with a `@Bean` declaration without using some `@Conditional`.

**Comment by tomazfernandes** [comment]
Nice, I wasn't sure if that was a proper solution, thanks. I think since we have this auto configuration problems and with some not-so-great consequences, it's worth it shielding the solution from that. We can always revise it later for 3.0 if we need to.

If that sounds good, I can open a PR for us to look at, probably with the `TimingAdjuster` implementing `InitializingBean` and `DisposableBean`, and being registered as a `@Bean` in the `RetryTopicConfigurationSupport` class.

**Comment by artembilan** [comment]
See the same `WebSocketConfigurationSupport`:
```
	@Bean
	@Nullable
	public TaskScheduler defaultSockJsTaskScheduler() {
		if (initHandlerRegistry().requiresTaskScheduler()) {
			ThreadPoolTaskScheduler threadPoolScheduler = new ThreadPoolTaskScheduler();
			threadPoolScheduler.setThreadNamePrefix("SockJS-");
			threadPoolScheduler.setPoolSize(Runtime.getRuntime().availableProcessors());
			threadPoolScheduler.setRemoveOnCancelPolicy(true);
			this.scheduler = threadPoolScheduler;
		}
		return this.scheduler;
	}
```
Where `this.scheduler` is `null` by default.

However I see in the latest version they did something like this:
```
	@Bean
	DefaultSockJsSchedulerContainer defaultSockJsSchedulerContainer() {
		return (initHandlerRegistry().requiresTaskScheduler() ?
				new DefaultSockJsSchedulerContainer(initDefaultSockJsScheduler()) :
				new DefaultSockJsSchedulerContainer(null));
	}
```

The issue is exactly the same what we are talking here about: https://github.com/spring-projects/spring-framework/issues/27903

**Comment by artembilan** [comment]
It comes with the:
```
@AutoConfiguration(after = { DispatcherServletAutoConfiguration.class, TaskExecutionAutoConfiguration.class,
		ValidationAutoConfiguration.class })
```
So, the `WebMvcAutoConfiguration` really relies on the auto-configured `TaskExecutor`.
I guess nothing to comment. 😄

**Comment by tomazfernandes** [comment]
I guess this is it:

`AsyncSupportConfigurer#setTaskExecutor`

*The provided task executor is used to:
Handle Callable controller method return values.
Perform blocking writes when streaming to the response through a reactive (e.g. Reactor, RxJava) controller method return value.
By default only a SimpleAsyncTaskExecutor is used. However when using the above two use cases, it's recommended to configure an executor backed by a thread pool such as ThreadPoolTaskExecutor.
Params:
taskExecutor – the task executor instance to use by default*

So it looks like a niche use case for this executor. Although the javadocs is perhaps a bit misleading since by default the auto configured `ThreadPoolTaskExecutor` is used. But nothing to write home about I guess.

**Comment by artembilan** [comment]
The point is that either way the WebMvc does not provide any extra `TaskExecutor` bean: or it uses that `TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME` or falls back to the `SATE`.
I guess the idea is to use a single managed `TaskExecutor` throughout the whole Spring Boot application.
That's why I don't want to expose `TaskExecutor` beans from our side as well.

**Comment by garyrussell** [comment]
I think I have figured out how we can resolve this using the new `BackOffHandler` concept.

Expect a PR in the next day or so.

**Comment by garyrussell** [comment]
Initial commit here: https://github.com/garyrussell/spring-kafka/commit/aba0171125b62840a1ce2e81c16cf8bc1d62ebcf

Brand new back off manager (and factory) - it is much simpler, no need for timing adjustment etc.

I haven't attacked the tests yet, but I tested it with a Boot app:

```java
@SpringBootApplication
public class Kgh2239Application extends RetryTopicConfigurationSupport {

	private static final Logger log = LoggerFactory.getLogger(Kgh2239Application.class);

	public static void main(String[] args) {
		SpringApplication.run(Kgh2239Application.class, args);
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> {
			template.send("kgh2239", "foo");
		};
	}

	@Bean
	RetryTopicSchedulerWrapper scheduler() {
		return new RetryTopicSchedulerWrapper(new ThreadPoolTaskScheduler());
	}

}

@Component
class Listener {

	private static final Logger log = LoggerFactory.getLogger(Listener.class);

	@KafkaListener(id = "kgh2239", topics = "kgh2239")
	@RetryableTopic(backoff = @Backoff(delay = 5000, multiplier = 2.0))
	void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		log.info("++++++++++ {} from {}", in, topic);
		throw new RuntimeException();
	}

}
```
```
2022-06-29T09:07:26.197-04:00  INFO 58391 --- [  kgh2239-0-C-1] com.example.demo.Listener                
  : ++++++++++ foo from kgh2239
null to aY6QOUGRRJenRx1fzPOg8g
2022-06-29T09:07:26.743-04:00 DEBUG 58391 --- [etry-5000-0-C-1] o.s.k.l.ListenerContainerPauseService    
  : Pausing container: ConcurrentMessageListenerContainer [concurrency=1, beanName=kgh2239-retry-5000, running=true] partition: kgh2239-retry-5000-0, resume scheduled for 2022-06-29T09:07:31.198272
2022-06-29T09:07:26.744-04:00  INFO 58391 --- [etry-5000-0-C-1] o.a.k.clients.consumer.KafkaConsumer     
  : [Consumer clientId=consumer-kgh2239-retry-5000-1, groupId=kgh2239-retry-5000] Seeking to offset 9 for partition kgh2239-retry-5000-0
2022-06-29T09:07:31.201-04:00 DEBUG 58391 --- [TaskScheduler-1] o.s.k.l.ListenerContainerPauseService    
  : Resuming container: ConcurrentMessageListenerContainer [concurrency=1, beanName=kgh2239-retry-5000, running=true] partition: kgh2239-retry-5000-0
2022-06-29T09:07:31.207-04:00  INFO 58391 --- [etry-5000-0-C-1] com.example.demo.Listener                
  : ++++++++++ foo from kgh2239-retry-5000
null to g00TR9hERAqGXp-21cWujg
2022-06-29T09:07:31.715-04:00 DEBUG 58391 --- [try-10000-0-C-1] o.s.k.l.ListenerContainerPauseService    
  : Pausing container: ConcurrentMessageListenerContainer [concurrency=1, beanName=kgh2239-retry-10000, running=true] partition: kgh2239-retry-10000-0, resume scheduled for 2022-06-29T09:07:41.207039
2022-06-29T09:07:31.715-04:00  INFO 58391 --- [try-10000-0-C-1] o.a.k.clients.consumer.KafkaConsumer     
  : [Consumer clientId=consumer-kgh2239-retry-10000-3, groupId=kgh2239-retry-10000] Seeking to offset 9 for partition kgh2239-retry-10000-0
2022-06-29T09:07:41.210-04:00 DEBUG 58391 --- [TaskScheduler-1] o.s.k.l.ListenerContainerPauseService    
  : Resuming container: ConcurrentMessageListenerContainer [concurrency=1, beanName=kgh2239-retry-10000, running=true] partition: kgh2239-retry-10000-0
2022-06-29T09:07:41.213-04:00  INFO 58391 --- [try-10000-0-C-1] com.example.demo.Listener                
  : ++++++++++ foo from kgh2239-retry-10000
2022-06-29T09:07:41.218-04:00 ERROR 58391 --- [try-10000-0-C-1] k.r.DeadLetterPublishingRecovererFactory 
  : Record: topic = kgh2239-retry-10000, partition = 0, offset = 9, main topic = kgh2239 threw an error at topic kgh2239-retry-10000 and won't be retried. Sending to DLT with name kgh2239-dlt.

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed
...
2022-06-29T09:07:41.724-04:00  INFO 58391 --- [h2239-dlt-0-C-1] o.s.k.retrytopic.RetryTopicConfigurer    
  : Received message in dlt listener: kgh2239-dlt-0@18
```

Still some cleanup and deprecations needed.

**Comment by artembilan** [comment]
I agree that we can go ahead with removal of the redundant API even in `2.9`. Should not be a big breaking change since we have introduced some new stuff exactly in that `2.9`.

**Comment by garyrussell** [comment]
I added the code purging commit to my branch https://github.com/garyrussell/spring-kafka/commits/GH-2239 

Tests are all passing.

Let me know if you think I have been too aggressive, or if I have missed anything.

I am off work until Tuesday.

Docs and PR to follow next week.

I left `decorateFactoryWithoutSettingContainerProperties` for now.

**Comment by tomazfernandes** [comment]
This looks good - but just to make sure we're on the same page regarding breaking changes, with this, not only users will need to add the `@EnableKafkaRetryTopic` annotation to make it work, but also any feature configuration they may have done by injecting infrastructure beans following the documentation will stop working as well. This goes for example for `blocking retries`, `fatal classification`, etc.

Of course, if that's not a concern to you, it's not to me either, and we do provide the same features with different configurations so maybe that could be considered an API change.

One thing I didn't really understand is this:

```java
Assert.state(ONLY_ONE_ALLOWED.getAndSet(false), "Only one 'RetryTopicConfigurationSupport' is allowed");
```

Also, as long as we're removing support for legacy bootstrapping, we can also remove support for legacy bean names in `KLABPP`, and leave only the constant:

```java
return this.beanFactory.containsBean("internalRetryTopicConfigurer")
 				? this.beanFactory.getBean("internalRetryTopicConfigurer", RetryTopicConfigurer.class)
 				: this.beanFactory.getBean(RetryTopicBeanNames.RETRY_TOPIC_CONFIGURER_BEAN_NAME, RetryTopicConfigurer.class);
```

The `ListenerContainerFactoryResolver` has a similar situation with legacy bean names as strings.

**Comment by garyrussell** [comment]
I would normally not make such breaking changes in a minor release, but we were up front in the documentation that, while the feature is stable and supported, the APIs were subject to change. So I believe we are justified.

To be honest, I am glad that I added that to the docs; when you first submitted the original PR, the amount of new code was so overwhelming that a normal code review could never fully cover all the bases, so I suspected that we might need some breaking changes as usage increased.

If you feel it's too much, we can defer the second commit until 3.0. I am ok with that too; I would just need to pull some of the polishing into 2.9.

Please discuss with @artembilan while I am away.

The reason I added the "only one allowed" check is because, when I was migrating the tests, I added `extends RetryTopicConfigurationSupport` here...

https://github.com/garyrussell/spring-kafka/blob/9e82f6a386861404b7c60c48a172006d0077b2e8/spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java#L318

...having not noticed there was already one here...

https://github.com/garyrussell/spring-kafka/blob/9e82f6a386861404b7c60c48a172006d0077b2e8/spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java#L392

With that in place, the blocking retry tests all failed because the overridden method to set up the exceptions was not called.

https://github.com/garyrussell/spring-kafka/blob/9e82f6a386861404b7c60c48a172006d0077b2e8/spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java#L394-L399

Perhaps I used a sledge hammer to crack a tiny nut; if you can think why that might have happened (and we can detect and correct it somehow), I would be happy to remove the check.

That said, Boot no longer allows bean overrides by default; having 2 or more of them in a Boot app won't work because of the bean declarations in the super class (without allowing bean overrides in Boot config). With this technique, we will fail fast with a meaningful message.

**Comment by garyrussell** [comment]
Another reason for the change being ok in 2.9 is nobody is forced to use it; it's opt-in, Boot won't pull it in and the 3.2.0 clients work fine with 2.8 if there's a compelling reason for using those.

**Comment by tomazfernandes** [comment]
> I would normally not make such breaking changes in a minor release, but we were up front in the documentation that, while the feature is stable and supported, the APIs were subject to change. So I believe we are justified.

Sure, no worries, I just wanted to make sure you're aware that existing configurations would break too.

> To be honest, I am glad that I added that to the docs; when you first submitted the original PR, the amount of new code was so overwhelming that a normal code review could never fully cover all the bases, so I suspected that we might need some breaking changes as usage increased.

Sure, I realize that, and do appreciate a lot you merging the code in such conditions. This opened a whole universe I didn't know existed and I'm really grateful for that.

> If you feel it's too much, we can defer the second commit until 3.0. I am ok with that too; I would just need to pull some of the polishing into 2.9.

Not necessary for me - let's break some walls!

> Please discuss with @artembilan while I am away.

Looks like we're all on the same page, but if anything comes up I'll bring it up, and I'll be available if anything is needed.

> With that in place, the blocking retry tests all failed because the overridden method to set up the exceptions was not called.
> Perhaps I used a sledge hammer to crack a tiny nut; if you can think why that might have happened (and we can detect and correct it somehow), I would be happy to remove the check.

Looks like the configured beans were overridden by new ones, right?

> That said, Boot no longer allows bean overrides by default; having 2 or more of them in a Boot app won't work because of the bean declarations in the super class (without allowing bean overrides in Boot config). With this technique, we will fail fast with a meaningful message.

Sure, no worries, we can leave it that way, I was just curious.

Thanks a lot for looking into this! And let me know if there's anything else I can help with.
