### ISSUE TITLE
How can I seek the consumer to the end

### ISSUE THREAD

**Issue by krishnaprasadas** [spring-projects/spring-kafka#224]
Each time when I start the consumer I need latest messages only for a specific topic, On each consumer start I will call seekToEnd(), something like this. Is it supported in the current version.

**Comment by artembilan** [comment]
Since version `1.1` there is a `ConsumerSeekAware` abstraction. 
In the [Reference Manual](http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_reference.html#seek) we have a note:

> In order to seek, your listener must implement ConsumerSeekAware which has the following methods:
```
void registerSeekCallback(ConsumerSeekCallback callback);

void onPartitionsAssigned(Map<TopicPartition, Long> assignments, ConsumerSeekCallback callback);

void onIdleContainer(Map<TopicPartition, Long> assignments, ConsumerSeekCallback callback);
```

And you have to call from those methods:
```
interface ConsumerSeekCallback {

	/**
	 * Queue a seek operation to the consumer. The seek will occur after any pending
	 * offset commits. The consumer must be currently assigned the specified partition.
	 * @param topic the topic.
	 * @param partition the partition.
	 * @param offset the offset (absolute).
	 */
	void seek(String topic, int partition, long offset);

}
```

Does that meet your requirements?
Or do you really would like to see `seekToBeginning(Collection<TopicPartition> partitions)` and `seekToEnd(Collection<TopicPartition> partitions)` implementations ?

**Comment by krishnaprasadas** [comment]
Actually as I described, I need to get the latest messages only, which means seekToEnd. Using seek method How can I move to the end ? How can I get the end offset?

**Comment by garyrussell** [comment]
It depends on how you set up your containers, if you use `TopicPartitionInitialOffset`, you can do this...

```java
return new KafkaMessageListenerContainer<>(kafkaConsumerFactory,
		new ContainerProperties(new TopicPartitionInitialOffset(this.topic, 0, Long.MAX_VALUE)));
```

If you are using broker-assigned partitions (group management), you can use the `ConsumerSeekAware` as @artembilan suggested...

```java
/**
 * When using group management, called when partition assignments change.
 * @param assignments the new assignments and their current offsets.
 * @param callback the callback to perform an initial seek after assignment.
 */
void onPartitionsAssigned(Map<TopicPartition, Long> assignments, ConsumerSeekCallback callback);
```

You can then use the seek callback to seek to the current offset.

**Comment by krishnaprasadas** [comment]
Yes, This will do the job. Thank you.
But may I know why 'seekToEnd' is hided.?

**Comment by garyrussell** [comment]
We just haven't exposed it yet; we will consider doing so in a future release.

**Comment by krishnaprasadas** [comment]
Thank you.
