### ISSUE TITLE
Keep original __TypeId__ header in DLT on deserialization exceptions

### ISSUE THREAD

**Issue by sirea-07** [spring-projects/spring-kafka#2241]
**Expected Behavior**

DLT message should contain original _\_\_TypeId\_\__ header in case of a deserialization exception.

**Current Behavior**

 _\_\_TypeId\_\__ is set to `byte[]` on deserialization exceptions.

**Context**

Since, due to the deserialization exception the data was not converted yet, `DefaultJackson2JavaTypeMapper.fromJavaType()` removes the _\_\_TypeId\_\__ header from the original message and replaces it with `byte[]`. This might be fine in general, however it would be helpful to keep the original  _\_\_TypeId\_\__ header as well. Maybe the `DeadLetterPublishingRecoverer` can add an additional header for deserialization exceptions?

I have also checked `DeserializationException.headers`, which is just `null` in my case.

**Comment by garyrussell** [comment]
It is not clear what you mean; please provide more context. With Kafka, headers the header value is always `byte[]`.

```java
public interface Header {
   
    String key();

    byte[] value();
   
}
```
If you are using the `JsonSerializer` with the DLT recoverer, then **that is wrong**; it should use the `ByteArraySerializer` instead.

There are two ways to do that; configure the DLPR with a KafkaTemplate that has the serializer overridden to a `ByteArraySerializer`.

Or, to use the same `KafkaTemplate` for normal (JSON) publishing and in the DLT as well, you should configure it with a `DelegatingByTypeSerializer` configured with a `ByteArraySerializer` for `byte[]` payloads and the `JsonSerializer` for others.

**Comment by sirea-07** [comment]
I hope the following example helps. 

Let's say I have a payload of `com.myorg.Foo` in my input topic. In case the deserialization succeeds, but the consumer fails, the header _\_\_TypeId\_\__ in the DLT topic will have the value _"com.myorg.Foo"_ (serialized as `byte[]`).
However, in case the deserialization fails, the value will be _"[B"_, since the payload was not deserialized yet and therefore `javaType.getRawClass()` in `DefaultJackson2JavaTypeMapper.fromJavaType()` returns this.

My suggestion is to add another header that contains the actual payload type, i.e. _"com.myorg.Foo"_.

Thanks also for your other notes, currently I am really using the DLT recoverer with a `JsonSerializer`. I've read the remark on the docs, but since my tests succeed, for both consumer and deserialization errors, I didn't have the urge to change it yet. :)

I have a very simple setup with a single DLT topic, so the payloads can have different types. I was thinking about specifying a `ByteArraySerializer` for `byte[]` and use `JsonSerializer` for all other types, but it looks like there is no option to define a "default" serializer. I'll look into it in more detail and I'll probably have to change my initialization logic in order to support `DelegatingByTypeSerializer `.

**Comment by garyrussell** [comment]
>I've read the remark on the docs, but since my tests succeed..

Of course, because the type id is correctly set to `byte[]` (since that is exactly what the payload is) so the `JsonDeserializer` properly decodes it to `byte[]` (Jackson converts `byte[]` to/from a base64 encoding.

Yes, we should probably add a default to the delegating serializer.

It might be easier for you to just use a different `KafkaTemplate`; you can override the serializer in one of the constuctors:

```java
	/**
	 * Create an instance using the supplied producer factory and properties, with
	 * autoFlush false. If the configOverrides is not null or empty, a new
	 * {@link DefaultKafkaProducerFactory} will be created with merged producer properties
	 * with the overrides being applied after the supplied factory's properties.
	 * @param producerFactory the producer factory.
	 * @param configOverrides producer configuration properties to override.
	 * @since 2.5
	 */
	public KafkaTemplate(ProducerFactory<K, V> producerFactory, @Nullable Map<String, Object> configOverrides) {
		this(producerFactory, false, configOverrides);
	}
```

**Comment by garyrussell** [comment]
> but it looks like there is no option to define a "default" serializer

Starting with version 2.8.3; you can do an assignable test (instead of equality).

This works fine:

```java
@Bean
CommonErrorHandler eh(KafkaTemplate<Object, Object> template, DefaultKafkaProducerFactory<Object, Object> pf) {
	Map<Class<?>, Serializer> delegates = new LinkedHashMap<>(); // retains the order when iterating
	delegates.put(byte[].class, new ByteArraySerializer());
	delegates.put(Object.class, new JsonSerializer<>());
	DelegatingByTypeSerializer dbts = new DelegatingByTypeSerializer(delegates, true);
	pf.setValueSerializer(dbts);
	return new DefaultErrorHandler(new DeadLetterPublishingRecoverer(template), new FixedBackOff(0L, 0L));
}
```

**Comment by sirea-07** [comment]
After applying your suggestion, everything works as expected. Now I also understand the reason why one should not just use a `JsonSerializer` in combination with a `ErrorHandlingDeserializer`. It doesn't make sense in the first place to use a `JsonSerializer` for `byte[]`, but the serializer also changes the headers of the message (or not as in the case of `ByteArraySerializer`). Although it totally makes sense now, I just didn't make the connection that using a `ByteArraySerializer` will solve my problem.

Thank you very much for your help and sorry for the noise. I will close the issue now.
