### ISSUE TITLE
SCRAM authentication issues with 2.8.3

### ISSUE THREAD

**Issue by Opayne93** [spring-projects/spring-kafka#2243]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.3 and 2.8.4, only when using Springboot version 2.6.5, 2.6.6, and 2.6.7

**Describe the bug**

When attempting to produce records to Kafka using a client configured with SCRAM authentication, the authentication is being rejected, and the following exception is thrown:
```
org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
````
I am seeing this happen with spring kafka versions 2.8.3 and 2.8.4, but only when using the Springboot versions listed above (configured using the springboot gradle plugin)

Using Springboot version 2.6.4 seems to work, with no changes to my configs. I can see that with this version of Springboot, spring kafka 2.8.3 is brought in. Seeing this, I then attempted to use Springboot version 2.6.6 and manually import spring kafka 2.8.3. However, this still did not work.

Debugging through my application, it seems that all the correct properties are being set, even up to where events are being published. 

**To Reproduce**
Configure a gradle project, and configure Springboot using the gradle plugin (note that I am using Kotlin):
```
plugins {
	id("org.springframework.boot") version "2.6.7"
}
```
Configure a ProducerFactory using the following configurations:
```
    @Bean
    fun producerFactory(kafkaProperties: KafkaProperties): ProducerFactory<String, String> {
        val props: MutableMap<String, Any> = HashMap()
        props[ProducerConfig.BOOTSTRAP_SERVERS_CONFIG] = kafkaProperties.bootstrapServers.joinToString()
        props[ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG] = StringSerializer().javaClass.name
        props[ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG] = StringSerializer().javaClass.name

        props["ssl.endpoint.identification.algorithm"] = "https"
        props["sasl.mechanism"] = "SCRAM-SHA-512"
        props["security.protocol"] = "SASL_SSL"
        props["sasl.jaas.config"] = "org.apache.kafka.common.security.scram.ScramLoginModule  required username=\"${apiKey}\" password=\"${apiSecret}\";"
       
        return DefaultKafkaProducerFactory(props)
    }
```
Connect to a kafka service that uses SCRAM authentication and attempt to publish an event. I realize that this step might be tricky to come by. I looked to see if there were any docker containers that would allow for SCRAM authentication, and I wasn't able to get anything working.

**Comment by garyrussell** [comment]
Spring Boot 2.6.5 switched from kafka-clients 3.0.0 to 3.0.1.

I suspect the problem is there.

Perhaps you can try downgrading to kafka-clients 3.0.0 to see if that helps.

If so, I suggest you try using the kafka-clients directly to connect, to see if you can reproduce the problem that way, in which case, you should open an issue agains the kafka-clients and close this.

If you can't reproduce it with the kafka-clients, we need to figure out what else might have changed in Spring (but I seriously doubt it's s Spring problem).

**Comment by Opayne93** [comment]
@garyrussell, that seemed to be the issue! I downgraded and everything works now. I will close this issue.

**Comment by Opayne93** [comment]
Sure thing. Here's the issue I opened: https://issues.apache.org/jira/browse/KAFKA-13859

**Comment by garyrussell** [comment]
I suspect they will need to see the configuration - maybe the INFO log put out by the producer or consumer, as well as the full stack trace.

They might also want to see the server logs too (if you can get them from AWS).

This could also be an AWS problem so you might want to raise an issue over there too.
