### ISSUE TITLE
"current" on docs.spring.io doesn't link to most recent version

### ISSUE THREAD

**Issue by hho** [spring-projects/spring-kafka#225]
At the moment, http://docs.spring.io/spring-kafka/docs/current/ links to the docs for Spring Kafka `1.0.1.RELEASE`.

The most recent release however is `1.1.2.RELEASE`, so the "current" link should probably go to the docs of that version.

The following links _also_ all point to the old version – however, to be in line with the URL structure for other Spring projects, they should probably just be removed:
* http://docs.spring.io/spring-kafka/docs/latest-ga/
* http://docs.spring.io/spring-kafka/api/
* http://docs.spring.io/spring-kafka/reference/

**Comment by garyrussell** [comment]
Fixed; thanks.
