### ISSUE TITLE
DeadLetterPublishingRecoverer should respect onlyLogRecordMatadata listener property

### ISSUE THREAD

**Issue by kdowbecki** [spring-projects/spring-kafka#2268]
**Expected Behavior**

Currently the `org.springframework.kafka.listener.KafkaMessageListenerContainer` class has `onlyLogRecordMatadata` property that governs how `ConsumerRecord` is logged on processing failure. Same `onlyLogRecordMatadata` property should be respected by the `org.springframework.kafka.listener.DeadLetterPublishingRecoverer` class for `ProducerRecord`.

**Current Behavior**

`DeadLetterPublishingRecoverer` currently logs the whole `ProducerRecord` when publication fails with no option to switch to just the metadata.

**Context**

We already have set `onlyLogRecordMatadata = true` because we don't want the message payload to appear in the logs when something fails. Since `DeadLetterPublishingRecoverer` copies the payload from the failed message into a `ProducerRecord` we still see the original message payload in the logs when publication fails.

**Comment by garyrussell** [comment]
Which version are you using? And which log message specifically?

It looks like all logs in 2.8.x properly log the record; in 2.7.x, I see one debug and 2 exceptions that log the full record.

**Comment by garyrussell** [comment]
That flag only controls logging of the consumer record.

The DLPR does log the producer record; in 2.8 we added a new feature to format the logs for producer record.

https://github.com/spring-projects/spring-kafka/blob/f94620aea7e7b43416b67cf9a46dce0acf46aa95/spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java#L168-L176

The default formatter logs the full record.

**Comment by garyrussell** [comment]
Although it was back-ported to 2.7.x, the DLPR doesn't use it.

**Comment by kdowbecki** [comment]
Good point @garyrussell. I'm on 2.7.12, inherited from Spring Boot 2.5.13. I don't see `DeadLetterPublishingRecoverer` using `KafkaUtils` formatting in these lines:

https://github.com/spring-projects/spring-kafka/blob/85cbbed1a28aca28a2c4c9e5dfc698d25cec7d9b/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L501

https://github.com/spring-projects/spring-kafka/blob/85cbbed1a28aca28a2c4c9e5dfc698d25cec7d9b/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L525

**Comment by kdowbecki** [comment]
It might be useful if `failIfSendResultIsError` field and `verifySendResult` method are changed from `private` to `protected` just like `publish` method is already `protected`. That way when when someone wants to override `publish` they can still reuse `failIfSendResultIsError` + `verifySendResult` functionality.

**Comment by garyrussell** [comment]
Yes, I will do some polishing around that at the same time; we don't allow protected fields (except loggers), but I can add a getter for it.

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-kafka/commit/56b7756206462bcd2b9dd8aaad0e64d27efce4d5

(Not sure why this didn't auto-close).
