### ISSUE TITLE
Optionally configure serialisers

### ISSUE THREAD

**Issue by gurpiarbassi** [spring-projects/spring-kafka#2274]
**Expected Behavior**

Sometimes you have already configured your serialiser by calling `configure()` on it and do not want the spring framework to reconfigure it.

**Current Behavior**

In version 2.8.4, if you have already configured your serialiser, the DefaultKafkaProducerFactory attempts to reconfigure it from scratch and all your settings are lost.

**Context**

It would be nice to have a flag/switch to indicate whether you want spring to configure your serialiser for you or not as discussed in this Stackoverflow thread: https://stackoverflow.com/questions/72228636/spring-kafka-serialiser-config/72231032?noredirect=1

**Comment by garyrussell** [comment]
I agree that we should add a flag to disable the `configure()` call.

In the meantime, as a work around, use

    factory.setValueSerializerSupplier(() -> myConfiguredSerializer);

It's probably a bug, but setting the serializer this way skips the `configure()` call.

**Comment by artembilan** [comment]
@garyrussell ,

Yes, it really looks like a bug. According to that your PR: https://github.com/spring-projects/spring-kafka/pull/1907/files#diff-ee2dfb7123c02f066d237b437f06f37c6ab26279ed47f3edd8b7ca0d0a4c96cdR285, the `DefaultKafkaConsumerFactory` does call a `configure()` even for the supplier setters.
The `DefaultKafkaProducerFactory` does not as we see.

But your idea to leverage a setter API for this kind of requested option indeed makes sense for me.
Although it is not obvious and requires JavaDocs reading. 😄
