### ISSUE TITLE
BatchMessagingMessageConverter class -- generateMessageId is set as false. 

### ISSUE THREAD

**Issue by glitch-k8s** [spring-projects/spring-kafka#2275]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.5

**Describe the bug**

I am using spring integration for reading message from kafka in "batch" mode. Then List of those messages are sent to Splitter for break-up into individual messages and further needs to be joined at aggregator after processing.

Issue : BatchMessagingMessageConverter class has generateMessageId=false. It results in "id" being removed from header. Due to absence of "id", "corelationId" is not generated. Hence my aggregator fails to join the messages. 

**Expected behavior**

In BatchMessagingMessageConverter class, both generateMessageId and generateTimestamp  should be true.
It will solve further issues.

**Comment by garyrussell** [comment]
This is by design, They are false by default for performance reasons.

You can easily set them to true.

```java
/**
* Generate {@link Message} {@code ids} for produced messages. If set to {@code false},
* will try to use a default value. By default set to {@code false}.
* @param generateMessageId true if a message id should be generated
*/
public void setGenerateMessageId(boolean generateMessageId) {
this.generateMessageId = generateMessageId;
}

/**
* Generate {@code timestamp} for produced messages. If set to {@code false}, -1 is
* used instead. By default set to {@code false}.
* @param generateTimestamp true if a timestamp should be generated
*/
public void setGenerateTimestamp(boolean generateTimestamp) {
this.generateTimestamp = generateTimestamp;
}
```

**Comment by glitch-k8s** [comment]
@garyrussell Thanks for sharing the knowledge. 
- message driven adapter channel adapter ->auto-startup=false
- get KafkaMessageDrivenChannelAdapter.batchListener.getBatchMessageConverter()
- call setGenerateMessageId (true) and setGenerateTimestamp (true)
- start adapter - doStart()

Again, appreciates your guidance.

**Comment by garyrussell** [comment]
It doesn't have to be that complicated.

Simply add a suitably configured `BatchMessagingMessageConverter` to the adapter in its bean definition.
```java
/**
* Set the message converter; must be a {@link RecordMessageConverter} or
* {@link BatchMessageConverter} depending on mode.
* @param messageConverter the converter.
*/
public void setMessageConverter(MessageConverter messageConverter) {
```
