### ISSUE TITLE
Kafka producer code is unable to reconnect after broker restart

### ISSUE THREAD

**Issue by chnaveens** [spring-projects/spring-kafka#228]
When Kafka cluster was deployed on AWS and if for some reason kafka broker dies and come back with new set of ip address. Kafka producer(client) was unable to reconnect. When i looked into code, i see that KafkaProducer was implemented as singleton. Same as the case with respect to DefaultKafkaProducerFactory, because of this no new producer object was recreated and connect was no re-established. Correct me if am wrong!

**Comment by garyrussell** [comment]
The kafka javadocs recommend using a singleton producer.

The `KafkaProducer` client is responsible for re-establishing the connection after a failure.

I just tested with a local broker (killed the broker and restarted it) and everything recovered as expected.

**Comment by garyrussell** [comment]
Do you have a stack trace to share?

**Comment by chnaveens** [comment]
No i don't have it saved anywhere, will get back to you if i see it again. Thanks @garyrussell
