### ISSUE TITLE
Publish Event In Container when Authorization/Authentication Exception occurs and retry takes place

### ISSUE THREAD

**Issue by indraneelb1903** [spring-projects/spring-kafka#2284]
Hi @garyrussell  and @artembilan 

I am using spring kafka and i need to do something when kafka connection error happens due to authorization/authentication exception been thrown in the following class - https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

No , i do not want the container to stop , hence i have the authExceptionRetryInterval set. But what i would also like is an application event to be published when this kind of error occurs so i can listen on it and then do something custom. 

Also  , i would also like an event to be published when the connection is successfully restored in the pollAndInvoke() method in the same class. Please let me know your thoughts on the same and if you guys are open to such a change.

**Comment by artembilan** [comment]
i think this make sense.

I'm not sure yet in the implementation details, but I'm OK to accept this as a `Feature Request`.

Let's also here from @garyrussell next week when he comes back from vacation!

**Comment by garyrussell** [comment]
Yes, it makes sense; feel free to submit a PR.

**Comment by indraneelb1903** [comment]
Thank you for taking care of this. @danielgentes

**Comment by danielgentes** [comment]
You're welcome, happy to help @indraneelb1903, I hope the changes match your expectations of the feature
