### ISSUE TITLE
kafka-clients dependency

### ISSUE THREAD

**Issue by Ryner51** [spring-projects/spring-kafka#2285]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.6

**Describe the bug**

spring-kafka-test pulls in dependency kafka-clients 3.0.1 but there have been multiple releases of kafka-clients in the last couple of months. 3.2.0 is the latest version of kafka-clients. When will this dependency be upgraded?

**To Reproduce**

mvn dependency:tree

**Expected behavior**

Latest version of kafka-clients should be pulled in.

**Comment by garyrussell** [comment]
The upcoming 2.9 release uses the 3.2.0 clients.
