### ISSUE TITLE
Documentation update for setAckOnError method

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-kafka#2286]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.6 (latest)

**Describe the bug**

The current documentation for Spring Kafka references setAckOnError method that was probably removed earlier:

https://docs.spring.io/spring-kafka/docs/current/reference/html/#default-eh

```
@Bean
public ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory() {
    ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory();
    factory.setConsumerFactory(consumerFactory());
    factory.getContainerProperties().setAckOnError(false);
    factory.getContainerProperties().setAckMode(AckMode.RECORD);
    factory.setCommonErrorHandler(new DefaultErrorHandler(new FixedBackOff(1000L, 2L)));
    return factory;
}
```

I couldn't find it in the latest source version:

https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java

**Expected behavior**

Usage of this method should be removed from the documentation.

**Comment by sergey-morenets** [comment]
There's one more code block in the documentation that fails to compile:

```
DeadLetterPublishingRecoverer recoverer = new DeadLetterPublishingRecoverer(template,
        (r, e) -> {
            if (e instanceof FooException) {
                return new TopicPartition(r.topic() + ".Foo.failures", r.partition());
            }
            else {
                return new TopicPartition(r.topic() + ".other.failures", r.partition());
            }
        });
ErrorHandler errorHandler = new DefaultErrorHandler(recoverer, new FixedBackOff(0L, 2L));
```

It seems to me that ErrorHandler should be replaced with **CommonErrorHandler** here.

**Comment by garyrussell** [comment]
Thanks! Back-ported to affected branches.
