### ISSUE TITLE
The addition of a  parameter of type `ConsumerRecordMetaData` breaks a working setup

### ISSUE THREAD

**Issue by kai-moritz** [spring-projects/spring-kafka#2295]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.6.8

**Describe the bug**

I have written a consumer, that consumes multiple types of messages.
The consumer is annotated with `@KafkaListener` at class-level.
The handler-methods for the known messate-types are annotated with `@KafkaHandler`.
The methods only a parameter of the type of the expected message.

_Everything works fine..._

After adding an additional parameter of type `ConsumerRecordMetaData`, the consumer is no longer able to receive messages of any type, because no appropriate resolvers could be found.
In fact, debugging shows, that not reolvers at all are configured, when the handler-method is called.

After adding a default-method, that handles an messages of unknown type, everything works as expected again.

**To Reproduce**

* [Without an additional parameter of type `ConsumerRecordMetaData` everything works as expexted](https://github.com/juplo/demos-kafka-kafkahandler/releases/tag/works-with-multiple-message-types)
* [After the addtion of the parameter, the messages are no longer resolved](https://github.com/juplo/demos-kafka-kafkahandler/releases/tag/fails-with-metadata)
* [Adding a default-handler "resolves" the issue](https://github.com/juplo/demos-kafka-kafkahandler/releases/tag/default-handler-as-fix)

**Expected behavior**

If receiving of messages of multiple types works without a default-handler for messages of unknown type, the same setup should work without a default-handler.
If the handler-methods also require an additional parameter of type `ConsumerRecordMetaData`, because they require knowledge about the partition, offset or any other technical detail, this should not force the implementation of an additional handler-method for unknown messages.

**Sample**

[Example with a working setup, the broken setup, if metadata are required, and the crooked workaround](https://github.com/juplo/demos-kafka-kafkahandler)

**Comment by garyrussell** [comment]
Strange behavior indeed; thanks for the reproducer.
