### ISSUE TITLE
MessageListenerContainer is started even if autoStartup is false

### ISSUE THREAD

**Issue by tbarabanov** [spring-projects/spring-kafka#2297]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
2.8,2

**Describe the bug**
I have a class like this: 
`@Autowired`
`private KafkaListenerEndpointRegistry registry;`

`@KafkaListener(`
`            id = "#{__listener.id}",`
`            groupId = "#{__listener.groupId}",`
`            topics = "#{__listener.topics}",`
`            properties = {"#{__listener.properties}"},`
`           autoStartup = "false") // autostart is disabled, use listener.start()`

Instances of the class are created this way:
`@Bean`
`@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)`
`public KafkaMessageListener<?, ?> kafkaListener(String groupId,`
`                                  String[] topics,`
`                                  String[] properties) {`
`return new KafkaMessageListener<>(groupId, topics, properties);`
when I create an instance of the KafkaMessageListener it starts up despite the fact that autoStartup is "false". I also tried to set 

ConcurrentKafkaListenerContainerFactory.setAutoStartup(false) but without success.

I found that KafkaListenerEndpointRegistry starts my listener in this method:
`private void startIfNecessary(MessageListenerContainer listenerContainer) {`
`		if (this.contextRefreshed || listenerContainer.isAutoStartup()) {`
`			listenerContainer.start();`
`		}`
`}`

because KafkaListenerEndpointRegistrar.startImmediately is true when I call appCtx.getBean(...) 

I expected that when I create an instance of KafkaMessageListener it must not be started.

**Comment by garyrussell** [comment]
Please learn how to use GitHub markdown to format code properly.

`autoStartup` only applies during context initialization; it is not relevant when the context has been refreshed (fully initialized), including when creating new prototype bean instances after the initialization is complete.

We could consider adding an option to the registry.

**Comment by tbarabanov** [comment]
Thx for the advice ). Is there any need in an option? I mean what if just get rid of the contextRefreshed check in KafkaListenerEndpointRegistry.startIfNecessary?

**Comment by garyrussell** [comment]
I presume you are using `context.getBean()` to get new instance(s) of your listener; why not defer that until you actually want the container to start?

**Comment by tbarabanov** [comment]
Yep, can do it this way. But it puts restrictions on how the code is organised, create/start/stop/ is just a bit more natural.
