### ISSUE TITLE
contextRefreshed in KafkaListenerEndpointRegistry seems useLess

### ISSUE THREAD

**Issue by youngkangrui** [spring-projects/spring-kafka#2315]
version 2.8.6

**Describe the bug**
if  set autoStartUp = false ,eg @KafkaListener(autoStartUp="false")，i find container do not start up even spring context has started，
but in the code，container starts depending on either contextRereshed or autoStartUp，so i think if context has started, container should start too , even if autoStartUp=false

**To Reproduce**
```
public class TestListener {
    @KafkaListener(id="id1",topics = {"tp"},groupId = "consumerGroupId",autoStartup = "false")
    public void Listen(String info){
        System.out.println(info);
    }
}

ConfigurableApplicationContext context = SpringApplication.run(DemoApplication.class, args);
		KafkaListenerEndpointRegistry registry = (KafkaListenerEndpointRegistry)context.getBean("org.springframework.kafka.config.internalKafkaListenerEndpointRegistry");
		MessageListenerContainer id1 = registry.getListenerContainer("id1");
		System.out.println(id1.isRunning());
```

**Expected behavior**
i think if context has started, container should start too , even if autoStartUp=false , otherwise what the use of contextRefreshed in KafkaListenerEndpointRegistry?

**Comment by garyrussell** [comment]
I think you are misunderstanding the concept of `autoStartup`.

It is only examined during the context refresh; simply getting the bean will not start it; you need to `start()` it yourself.

In fact, someone complained about the opposite behavior recently, where newly registered containers are started, even if `autoStartup` is `false`.

We added a new boolean to the registry for that purpose; https://github.com/spring-projects/spring-kafka/pull/2301
