### ISSUE TITLE
alwaysStartAfterRefresh seems not work

### ISSUE THREAD

**Issue by youngkangrui** [spring-projects/spring-kafka#2316]
contextRereshed in KafkaListenerEndPointRegistry is set to true only if received ContextRefreshEvent, but  in Spring SmartLifeCycle  is triggered  before ContextFreshEvent is sended out , so when smartLIfeCycle wants to start the containers, contextRefreshed will always be false, so my question is adding  alwaysStartAfterRefresh this way ( #2301 ) will not start the containers even if context refreshed. 

using 2.8.7 ,following  code's output is still false, while true is expected

```
public class TestListener {
    @KafkaListener(id="id1",topics = {"tp"},groupId = "consumerGroupId",autoStartup = "false")
    public void Listen(String info){
        System.out.println(info);
    }
}

ConfigurableApplicationContext context = SpringApplication.run(DemoApplication.class, args);
KafkaListenerEndpointRegistry registry = (KafkaListenerEndpointRegistry)context.getBean("org.springframework.kafka.config.internalKafkaListenerEndpointRegistry");
MessageListenerContainer id1 = registry.getListenerContainer("id1");
System.out.println(id1.isRunning());
```

**Comment by garyrussell** [comment]
I already closed this as invalid. https://github.com/spring-projects/spring-kafka/issues/2315

`alwaysStartAfterRefresh` means always start **new registrations** after the context has started.

When you register a container before the context is refreshed; the `autoStartup` property is honored. Refreshing the context does not start any containers that were registered before the refresh.

By default, the `autoStartup` property is ignored when registering new containers after the refresh and the container is started. `alwaysStartAfterRefresh=false` means always honor the `autoStartup` property.

**Comment by garyrussell** [comment]
See the javadocs

```java
/**
* By default, containers registered for endpoints after the context is refreshed
* are immediately started, regardless of their autoStartup property, to comply with
* the {@link SmartLifecycle} contract, where autoStartup is only considered during
* context initialization. Set to false to apply the autoStartup property, even for
* late endpoint binding. If this is called after the context is refreshed, it will
* apply to any endpoints registered after that call.
* @param alwaysStartAfterRefresh false to apply the property.
* @since 2.8.7
*/
public void setAlwaysStartAfterRefresh(boolean alwaysStartAfterRefresh) {
this.alwaysStartAfterRefresh = alwaysStartAfterRefresh;
}
```
