### ISSUE TITLE
Group consumer "stop-the-world" when one consumer exceed max.poll.interval.ms

### ISSUE THREAD

**Issue by ducnhilt** [spring-projects/spring-kafka#2337]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

Spring kafka 2.5.3.RELEASE

**Describe the bug**

My application have two ```ConcurrentKafkaListenerContainerFactory``` separate by topic. Let's say ```ConcurrentKafkaListenerContainerFactory``` create consumer A for subscribe topic A and another ```ConcurrentKafkaListenerContainerFactory``` create consumer B for subscribe topic B. 2 instances application deploy on K8S.  When consumer B exceed ```max.poll.interval.ms```

What i received:
```
Member consumer-B-2-05ba4dd6-3a98-4ea8-91eb-003ee4fc7aca sending LeaveGroup request to coordinator <brokers-ip> (id: 2147483645 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
```
I've expected the groupId B would be rebalance and had been assigned partitions again, but nothing happen. Message lag of group B still increased, two instance have stopped consume message . Only group B got stuck, group A worked fine. When I restarted my application and groupId B began consume message. I wonder why this issue happen?

I also check status `isRunning` of the container. Whenever container return `isRunning = false` I will restart my application (health check kubernetes). But my application still alive. So I think KafkaContainer bean had been removed by spring application context. Is it possible ? Or I still missing somewhere?

**To Reproduce**

Very very rarely this issue happen. I still cannot reproduce this issue.

**Expected behavior**
After LeaveGroup. Kafka consumer will gonna rejoin group and begin consume message.

**Sample**
I don't have sample code.

**Comment by ducnhilt** [comment]
My configuration kafka consumer.
```java
public final class KafkaConsumerConfigInit {
    KafkaConsumerConfigInit() {}

    public static <T> ConcurrentKafkaListenerContainerFactory<String, T> getCommonKafkaListenerContainerFactory(TopicConfig topicConfig, Class<T> clazz) {
        ConcurrentKafkaListenerContainerFactory<String, T> factory = new ConcurrentKafkaListenerContainerFactory<>();
        if (topicConfig.getMaxPollRecord() == null || topicConfig.getMaxPollRecord() <= 0) {
            topicConfig.setMaxPollRecord(MAX_POLL_RECORDS_CONFIG);
        }
        if (topicConfig.getMaxPollInterval() == null || topicConfig.getMaxPollInterval() <= 0) {
            topicConfig.setMaxPollInterval(MAX_POLL_INTERVAL_MS_CONFIG);
        }

        if (topicConfig.getShutDownTimeOutInMillie() == null || topicConfig.getShutDownTimeOutInMillie() <= 0) {
            topicConfig.setShutDownTimeOutInMillie(DEFAULT_SHUTDOWN_TIMEOUT);
        }

        if (topicConfig.getNoPollThreshold() == null || topicConfig.getNoPollThreshold() <= 0) {
            topicConfig.setNoPollThreshold(THRESHOLD_NO_RESPONSE);
        }

        String groupId = StringUtils.isEmpty(topicConfig.getGroupId()) ? topicConfig.getTopic() : topicConfig.getGroupId();
        ConsumerFactory<String, T> consumerFactory = getConsumerFactory(topicConfig.getUrl(), groupId,
                topicConfig.getMaxPollRecord(), topicConfig.getMaxPollInterval(), clazz);
        factory.setConsumerFactory(consumerFactory);
        factory.getContainerProperties().setAckMode(ContainerProperties.AckMode.MANUAL);
        factory.getContainerProperties().setShutdownTimeout(topicConfig.getShutDownTimeOutInMillie());
        factory.getContainerProperties().setPollTimeout(topicConfig.getMaxPollInterval());
        factory.getContainerProperties().setNoPollThreshold(topicConfig.getNoPollThreshold());
        factory.getContainerProperties().setMonitorInterval(topicConfig.getMaxPollInterval());
        factory.getContainerProperties().setSyncCommits(topicConfig.isSyncCommit());
        factory.setConcurrency(topicConfig.getConcurrency());

        return factory;
    }
}
```

Which is 
```java
MAX_POLL_RECORDS_CONFIG  = 100, 
MAX_POLL_INTERVAL_MS_CONFIG = 120_000, 
DEFAULT_SHUTDOWN_TIMEOUT = 300_000,
THRESHOLD_NO_RESPONSE = 3
```

When I init bean
```java
    @Bean
    public ConcurrentKafkaListenerContainerFactory<String, EventReportMsg> eventReportContainerFactory() {
        return KafkaConsumerConfigInit.getKafkaListenerContainerFactory(eventReportKafka.getTopicConfig(KafkaConst.EVENT_REPORT_TOPIC), EventReportMsg.class); // this is method above.
    }
```

`@KafkaListener`
```java
        @KafkaListener(topics = "#{'${event_report}'.split(',')}", containerFactory = "eventReportContainerFactory")
        public void listener(EventReportMsg msg, Acknowledgment acknowledgment) throws DBClusterException {
            log.info("[SENDER] received msg from topic={} with data={}", KafkaConst.EVENT_REPORT_TOPIC, msg);
            this.doConsume(msg);
            acknowledgment.acknowledge();
        }
```

**Comment by garyrussell** [comment]
That doesn't help; you need to provide logs when the problem occurs; also take a thread dump to see if the listener thread is "stuck". someplace.

**Comment by ducnhilt** [comment]
`Member consumer-B-2-05ba4dd6-3a98-4ea8-91eb-003ee4fc7aca sending LeaveGroup request to coordinator <brokers-ip> (id: 2147483645 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.` 

this log above is that all I have. No revoked partitions log, JoinGroup log, Attempt HeartBeat fail rebalance log, stuff like that. I wish I could have more log.

**Comment by tdnhduc** [comment]
Problem in user code. User code call make http request without timeout. Feel free for closing this bug.

**Comment by ducnhilt** [comment]
Yes, the poll thread actually stuck in user code when make http connection without timeout. Thanks for your support.
