### ISSUE TITLE
Error while fetching metadata with correlation, UNKNOWN_TOPIC_OR_PARTITION

### ISSUE THREAD

**Issue by topEngineerRay** [spring-projects/spring-kafka#2354]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.7

**Describe the bug**

I am using spring kafka together with spring boot, and I define my kafka topic in the application properties files.
When I start my service locally it will connect the kafka broker in Docker. But in the console there will be a lot of WARN logs for some of my kafka topics like below:

`2022-07-14 07:25:53,746 WARN  [org.springframework.kafka.KafkaListenerEndpointContainer#1-1-C-1] - [org.apache.kafka.clients.NetworkClient] [] - [Consumer clientId=] Error while fetching metadata with correlation id 175 : {xxx.topic=UNKNOWN_TOPIC_OR_PARTITION}`

**To Reproduce**
I am not sure if this can be reproduced in othere project as i am on a business project.

**Expected behavior**

No logs like this should be printed in the console.

**Sample**

**Comment by topEngineerRay** [comment]
I just tried that if I add the following configuration in the project:
`auto.create.topics.enable=true`

Then this warn logs are all gone. But I am still confused that why this warning logs only happend on some of my topics but other topics are fine, they are all created and defined the same way.

**Comment by garyrussell** [comment]
You need to declare a `NewTopic` `@Bean` for each topic, so the framework will create the topic with the desired number of partitions etc.

https://docs.spring.io/spring-kafka/docs/current/reference/html/#configuring-topics

**Comment by topEngineerRay** [comment]
Its not working, I am using the embedded kafka to test kafka event, after I decalre a NewTopic @Bean for each topic, I still got the warning message.

And  add the property:

`auto.create.topics.enable=true` 
only work for application start(with kafka in docker), but not work with the test(with embedded kafka).

**Comment by artembilan** [comment]
The `@EmbeddedKafka` has an attribute:
```

	/**
	 * Topics that should be created Topics may contain property place holders, e.g.
	 * {@code topics = "${kafka.topic.one:topicOne}"} The topics will be created with
	 * {@link #partitions()} partitions; to provision other topics with other partition
	 * counts call the {@code addTopics(NewTopic... topics)} method on the autowired
	 * broker.
	 * Place holders will only be resolved when there is a Spring test application
	 * context present (such as when using {@code @SpringJunitConfig or @SpringRunner}.
	 * @return the topics to create
	 */
	String[] topics() default { };
```

We just don't know what you are doing and how your code looks like.

Please, consider to raise a StackOverflow question with much more info. It might be great if you share a simple project to reproduce the problem.

GH issues are not for asking questions and there is no evidence that it is a bug in the framework some way...
