### ISSUE TITLE
ClassCastException in ErrorHandlerAdapter in 2.8.8

### ISSUE THREAD

**Issue by vooft** [spring-projects/spring-kafka#2363]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.8

**Describe the bug**

There was an issue introduced in 2.8.8 related to bug #2340, looks like a mistake on cherry-picking.
Basically in this branch we check if the error handler is an instance of `RetryingBatchErrorHandler` and then try to cast it to `FallbackBatchErrorHandler`, when in main we do both check and cast to `FallbackBatchErrorHandler`

https://github.com/spring-projects/spring-kafka/blob/v2.8.8/spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java#L165-L167

vs in main:
https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java#L167-L169

**To Reproduce**

It fails immediately on partition assignment if `RetryingBatchErrorHandler` is set as the error handler.

**Comment by garyrussell** [comment]
Oops; sorry about that.

As a work around, make a copy of the adapter and inject it as a `CommonErrorHandler`.

Or, just use the `DefaultErrorHandler` which uses the same logic as the `RetryingBatchErrorHandler` when a non-specific exception is thrown.

**Comment by garyrussell** [comment]
Fixed by https://github.com/spring-projects/spring-kafka/commit/b6b4c1aee65e9d219db6d56ffc9342b871126c04
