### ISSUE TITLE
Kafka Consumer issue in 1.1.1.RELEASE

### ISSUE THREAD

**Issue by prasadnadendla** [spring-projects/spring-kafka#237]
**Exception:**
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topic_metadata': Error reading array of size 3027513, only 100 bytes available

did i missed out to set any consumer config property?
Is it possible to connect to Kafka 0.8.* server version using Kafka 0.9.* client

**Comment by garyrussell** [comment]
No you cannot: http://kafka.apache.org/090/documentation.html#upgrade
