### ISSUE TITLE
Feature Request: Provide `DestinationTopic.Properties#isRetryTopic()` method

### ISSUE THREAD

**Issue by vivekragunathan** [spring-projects/spring-kafka#2377]
Based on @tomazfernandes's [**request**](https://stackoverflow.com/a/73285101/495612), filing this feature request for a `DestinationTopic.Properties#isRetryTopic()` method. There are currently `isMainTopic` and `isDltTopic` methods but not a `isRetryTopic` method.

Workaround today is:

```java
Boolean isRetryTopic = !properties.isMainTopic() && !properties.isDltTopic();
```

**Comment by tomazfernandes** [comment]
Thanks @vivekragunathan - also, feel free to provide a `PR` if you'd like.

**Comment by vivekragunathan** [comment]
Yes sure ... that PR for some bed time stretching tonight
