### ISSUE TITLE
Ability to support splitting large messages

### ISSUE THREAD

**Issue by dunstanmillwright** [spring-projects/spring-kafka#2380]
**Expected Behavior**

Producer should support splitting messages into chunk if it exceeds a pre-defined message size. The consumer should support reading messages transparently and identify large messages and pass it back to consumer after assembling the chunks.

**Current Behavior**

Currently the application relying on spring kafka has to come up with a solution to reliably handle this consumption.

**Context**

Many org has 1 MB limitation in the message size. So every app written using KAFKA by different teams using various techniques to consume large messages. If Spring Kafka provides the solution it avoids re-inventing the wheel.

**Comment by garyrussell** [comment]
I don't believe this is something Spring can help with; Spring has no knowledge of the size of the payload (produced by serialization within the `KafkaProducer`).

Another challenge would be how to re-assemble the record on the consumer side.
