### ISSUE TITLE
FallbackBatchErrorHandler may cause consumers to pause even if they are not retrying

### ISSUE THREAD

**Issue by vooft** [spring-projects/spring-kafka#2382]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

2.8.8+

**Describe the bug**

Error handlers are shared between multiple consumers if concurrency > 1, which may result in pausing consumers if some others are retrying at the moment and rebalancing kicks in.

**Comment by garyrussell** [comment]
Cherry-picked to 2.9.x, back ported to 2.8.x.

6a28cc5e381248987c1ce3afbf2f2afed7617c6e
3de1e89ba697ead04de171cfa35273bb0daddbe6

Thanks @vooft - in future, please limit first commit headline to 50 chars.
