### ISSUE TITLE
FallbackBatchErrorHandler Does Not Publish Pause/Resume Events

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2387]
https://stackoverflow.com/questions/73571243/records-associated-to-a-kafka-batch-listener-are-not-consumed-for-some-partition/73613322?noredirect=1#comment129993155_73613322

**Comment by frosiere** [comment]
Pause and resume events should also be fired from KafkaMessageListenerContainer#pauseForNackSleep and KafkaMessageListenerContainer#resumeConsumerIfNeccessary.

**Comment by garyrussell** [comment]
Pause/Resume events are not published if the container is a `ConcurrentMessageListenerContainer` (e.g. `@KafkaListener`).
