### ISSUE TITLE
Support KRaft mode for EmbeddedKafkaBroker

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects/spring-kafka#2391]
**Expected Behavior**

The embedded Kafka broker should be able to run in KRaft mode.

**Current Behavior**

There is no option to run Kafka in KRaft mode nor to completely disable Zookeeper.

**Context**

KRaft mode becomes production ready from Kafka 3.3.0 and only available mode from Kafka 4+. So support for KRaft is becoming a requirement in 2023. But it is relevant just now for EmbeddedKafkaBroker because it is relative simplicity to run and minimize footprint by removing ZK.

**Comment by artembilan** [comment]
Feel free to contribute this feature.
Or let's wait until it really becomes and official feature (3.3.0 GA), so we would be good to drop any ZK support we have in the embedded broker so far.

**Comment by garyrussell** [comment]
We are now on Kafka 3.3.1 so this can be implemented; contributions are welcome.

**Comment by govi20** [comment]
If no one is working on it, I would like to give it a shot.

**Comment by artembilan** [comment]
@govi20 ,

no one as far as I am aware.

Thank you for help proposal!

**Comment by eddumelendez** [comment]
Hi 👋🏽, sorry for hijacking the thread but I think this can be useful information. Testcontainers Kafka module version 1.18.0 offers support for Kraft mode. Look at this test

https://github.com/testcontainers/testcontainers-java/blob/main/modules/kafka/src/test/java/org/testcontainers/containers/KafkaContainerTest.java#L136-L145

**Comment by garyrussell** [comment]
I also found this https://github.com/apache/kafka/pull/13375 which could be used as a basis for the changes needed here.

**Comment by garyrussell** [comment]
I made some progress, but this is blocked by https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-15092

**Comment by garyrussell** [comment]
Unblocked; the necessary class is in server-common...-test.jar.
