### ISSUE TITLE
Kafka_2.13 version in spring-kafka-test is different from the one in spring-boot 2.7.3

### ISSUE THREAD

**Issue by MichaelZett** [spring-projects/spring-kafka#2398]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?*
2.8.8

**Describe the bug**
Spring-kafka-test 2.8.8 is used in spring-boot 2.7.3. There kafka_2.13 version is 3.1.1 (https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/dependency-versions.html#appendix.dependency-versions). In spring-kafka-test kafka_2.13 version is version is only 3.0.1 - shouldn't that fit, so spring-kafka-test should also use kafka_2.13 version 3.1.1?
In one of our projects that leads to a problem. We are able to work-around that by exlicitely use kafka_2.13 version is 3.1.1. Nevertheless we wanted to inform you about the mismatch.

**Comment by MichaelZett** [comment]
Hi Gary, thanks for looking into this.
If one uses a spring-boot project, you are right: It will use the version from spring-boot.
We have a project without spring-boot bom and try to comply to the versions manually. There we noticed, that spring-kafka-test 2.8.8 uses 3.0.1. Here is the gradle dependencyInsight:

`org.apache.kafka:kafka_2.13:3.0.1
\--- org.springframework.kafka:spring-kafka-test:2.8.8
     \--- testCompileClasspath
`
So is our reasoning wrong, that all spring-projects in a given spring-boot version do use the versions listed for this spring-boot version.

**Comment by MichaelZett** [comment]
In your example, dependencyInsight looks like this:
`org.apache.kafka:kafka_2.13:3.0.1 -> 3.1.1
\--- org.springframework.kafka:spring-kafka-test:2.8.8
     \--- testCompileClasspath (requested org.springframework.kafka:spring-kafka-test)
`

**Comment by garyrussell** [comment]
This is because 2.8.x is also used by Boot 2.6.x; which pulls in kafka 3.0.x. For that reason we cannot change 2.8.x to use the kafka 3.1.x natively.

You will need to specify the updated versions of all dependent jars if not using Boot's dependency management.

**Comment by MichaelZett** [comment]
Thanks for clarification. Will do.
