### ISSUE TITLE
@KafkaListener doesn't supports injection for List<ConsumerRecord<K, V>>

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-kafka#240]
```	
	@KafkaListener(topics = "com.bcs.ibs.domain.Trade", containerFactory = "manualAckTradeListenerContainerFactory")
	public void onMessage(List<ConsumerRecord<String, Trade>> records, Acknowledgment ack) {
		for (ConsumerRecord<String, Trade> record : records) {
			System.out.println(record);
			// TODO process record
		}
		ack.acknowledge();
	}
```
records is `List<Trade>` not `List<ConsumerRecord<String, Trade>>` with spring-kafka-1.1.3 .

**Comment by artembilan** [comment]
We have a test-case there like:
```
@Test
public void testBatchRecordsAck() throws Exception {
	template.send("annotated17", null, "foo");
	template.send("annotated17", null, "bar");
	assertThat(this.listener.latch13.await(60, TimeUnit.SECONDS)).isTrue();
	assertThat(this.listener.payload).isInstanceOf(List.class);
	List<?> list = (List<?>) this.listener.payload;
	assertThat(list.size()).isGreaterThan(0);
	assertThat(list.get(0)).isInstanceOf(ConsumerRecord.class);
	assertThat(this.listener.ack).isNotNull();
}
```
and related config:
```
@KafkaListener(id = "list4", topics = "annotated17", containerFactory = "batchManualFactory")
public void listen13(List<ConsumerRecord<Integer, String>> list, Acknowledgment ack) {
	this.payload = list;
	this.ack = ack;
	ack.acknowledge();
	this.latch13.countDown();
}
...
@Bean
public KafkaListenerContainerFactory<?> batchManualFactory() {
	ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
				new ConcurrentKafkaListenerContainerFactory<>();
	factory.setConsumerFactory(manualConsumerFactory());
	ContainerProperties props = factory.getContainerProperties();
	props.setAckMode(AckMode.MANUAL_IMMEDIATE);
	factory.setBatchListener(true);
	return factory;
}
```

So, would you mind to share something similar on the matter to play from our side?

Because as you see the confirmation is like it works as proposed.

**Comment by quaff** [comment]
Sorry, I missed `factory.setBatchListener(true);` ,  I thought it will be inferred from method signature, maybe it should be a new feature?

**Comment by artembilan** [comment]
No, it can't be. 
Because one Kafka message may have value as a collection of domain objects. 
That is exactly what you have faced with this issue.

**Comment by quaff** [comment]
`List<ConsumerRecord>` can be determinated as batch listener, ConsumerRecord is not domain object.

**Comment by artembilan** [comment]
Well, I still think that it is pretty complicated all around already with those existing options for consuming, that I'd prefer do not introduce more unpredictable behavior. 
There is only answer: if you want batch, please, set an appropriate option on the factory.

It's not a bug, neither significant feature to spend time for trying to meet rare requirement.

But won't mind other opinion or even contribution.

**Comment by dbgrey44** [comment]
But because of type erasure what you really end up getting is `List<String>` and not `List<ConsumerRecord>`.
Is there some way to get `ConsumerRecords` by using `@KafkaListener` ? 
The reason I am asking is I want to get timestamps for `ConsumerRecord` but without that object I can't get hold of that information.

**Comment by artembilan** [comment]
The `ConsumerRecords` doesn't bring too much value, so in case of `factory.setBatchListener(true)` we just provide the `List<ConsumerRecord<K, V>>`. Those has all the information you need and in a raw state, without any subsequent conversions.

Anyway that sounds like a question, which should be handled to the community forum, e.g. StackOverflow.
