### ISSUE TITLE
Kafka 3.2.2 contains significant bug 

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects/spring-kafka#2403]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.9.1

**Describe the bug**

Kafka release 3.2.2 is skipped: https://kafka.apache.org/downloads

Needs to update to 3.2.3: https://downloads.apache.org/kafka/3.2.3/RELEASE_NOTES.html

**Comment by garyrussell** [comment]
Thanks for the heads-up; if you are using Spring Boot, you can override the version as described here: https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps

**Comment by garyrussell** [comment]
I don't think this warrants a new release at this time; the CVE is in the broker and this project only provides an embedded broker for use in test cases and therefore there is no threat vector.

**Comment by vladimirfx** [comment]
Thank you!
