### ISSUE TITLE
Can Annotation  @KafkaListener support String[] groupIds() 

### ISSUE THREAD

**Issue by xzhan** [spring-projects/spring-kafka#2408]
**Expected Behavior**
Backgroud: One topic and one target server address, we may have 3, 5, n consumerGroup need to consumer the topic.
so my requirement is: can we do it like this 

   @KafkaListener(
            topics = {
                    "#{'${kafka.consumer.topic}'.split(',')}"
            },
            groupId = {
                    "#{'${kafka.consumer.consumergroup}'.split(',')}"
            },
    )

Prop define:
kafka.consumer.topic=topic1,topic2
kafka.consumer.consumergroup=consumergroup1,consumergroup2

**Current Behavior**
as @KafkaListner is repeatable annotation , so we can do like below

 @KafkaListener(
            topics = {
                    "#{'${kafka.consumer.topic}'.split(',')}"
            },
            groupId = "consumergroup1"
         
    )

 @KafkaListener(
            topics = {
                    "#{'${kafka.consumer.topic}'.split(',')}"
            },
            groupId = "consumergroup2"
         
    )

.....

that means if we have new consumer group , we need to change the code it .

**Context**
So that's our pain on this point , if we support groupID as  groupID[] that means infuture  if need to add new consumer groupID it only need to do config , no need to add more code

**Comment by xzhan** [comment]
Also I have do some research, as I want to to override the @KafkaListener default kafkaListenerContainerFactory whether can dynamic build consumerGroup with provided groupIDs.but failure.

@garyrussell  @artembilan   can you help us to understand whether we can do it , or what's you point /idea on this case

**Comment by garyrussell** [comment]
Don't use issues to ask questions.

No; there is one container/consumer group per annotation.

However, you can define your listener as a prototype bean to get multiple instances with different groups...

```java
@SpringBootApplication
public class Kgh2408Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh2408Application.class, args);
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("kgh2408").partitions(1).replicas(1).build();
	}

	@Bean
	ApplicationRunner runner(ApplicationContext context, @Value("${groups}") List<String> groups) {
		return args -> {
			groups.forEach(group -> context.getBean(Listener.class, group, group));
		};
	}

	@Bean
	@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
	Listener listener(String id, String group) {
		return new Listener(id, group);
	}

}

class Listener {

	private final String id;

	private final String groupId;

	public Listener(String id, String groupId) {
		this.id = id;
		this.groupId = groupId;
	}

	public String getId() {
		return this.id;
	}

	public String getGroupId() {
		return this.groupId;
	}

	@KafkaListener(id = "#{__listener.id}", topics = "kgh2408", groupId = "#{__listener.groupId}")
	void listen(String in) {
		System.out.println(in);
	}

}
```
```properties
groups=foo,bar,baz
```
```
2022-09-22 08:48:38.042  INFO 22852 --- [      bar-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : bar: partitions assigned: [kgh2408-0]
2022-09-22 08:48:38.042  INFO 22852 --- [      baz-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : baz: partitions assigned: [kgh2408-0]
2022-09-22 08:48:38.042  INFO 22852 --- [      foo-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : foo: partitions assigned: [kgh2408-0]
```

**Comment by xzhan** [comment]
Thx @garyrussell  , seems this way can still use annotation @Kafkalistner . that' cool.

**Comment by xzhan** [comment]
@garyrussell  here is one interesting thing I found this option can't work as we expected 
see the below code snap-snippet  autoStartup=false , it also consume message

@KafkaListener(id = "#{__listener.id}",
            topics ="#{'${kafka.consumer.topic.meeting.notification}'.split(',')}",
            autoStartup ="${kafka.dynamic.consumerGroupIds.enable}",
            groupId = "#{__listener.groupId}"

**Comment by garyrussell** [comment]
That is the default behavior; `autoStartup` is part of `SmartLifecyle` during application context initialization only; it does not apply once the context has been initialized.

However, starting with version 2.8.7, we added an option to the `KafkaListenerEndpointRegistry` - see

https://github.com/spring-projects/spring-kafka/blob/bb34b9cdd8a1ff701c418b34e780f60634cada97/spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java#L125-L137

**Comment by xzhan** [comment]
thx @garyrussell , so how can we set autoStartup="false" take effective while we build @KafkaListener with dynamic way?

if we don't build @KafkaListener with dynamic way , it can works well with my setting  autoStartup="false"

**Comment by garyrussell** [comment]
See the Javadoc I pointed you too. Get a reference to the registry and set that property to false before creating any new listeners. You will need a reference to the registry anyway, if you want to start a listener later

**Comment by garyrussell** [comment]
>what's you design point on autoStartup is part of SmartLifecycle

This was for consistency with other implementations (JMS, etc).

>What's different if we directly create @KafkaListener?

You can't do that, it involves a lot of framework infrastructure.

**Comment by xzhan** [comment]
thx @garyrussell  a lot.  Learn a lot from the discussion
