### ISSUE TITLE
not rollback transactions in database with KafkaTemplate and kafka down

### ISSUE THREAD

**Issue by gpando** [spring-projects/spring-kafka#2411]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

2.9.1 

**Describe the bug**

With kafka down, in a transactional context, an insertion is made in the database and a message is produced in kafka, and not rollback in database.

**To Reproduce**
- Database up and kafka up.
- Transaction: send message to kafka and insert in database.
- Ok, next then i stop kafka.
- Transaction: send message to kafka and insert in database.
- New record in database, not rollback!!!

(view sample)

**Expected behavior**

I do not expect a new record in the database

**Actual behavior**

I can see a new record in the DB with kafka down.

**Sample**

A link to a GitHub repository with a [minimal, reproducible,  sample](https://github.com/gpando/spring-kafka-transactional-bug).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by garyrussell** [comment]
>and a message is produced in kafka,

How is that possible if kafka is down?

Please provide much more information.

**Comment by gpando** [comment]
Actual example (view repo), with this code:

```
@Transactional("transactionManager")
public void doTaskOK() {
    doTask("OK");
}

private void doTask(String type) {
        Account account = createAccount(type);

        kafkaTemplate.send(topicName,account.getName());
        
        repository.save(account);
 }
```


Steps to reproduce the error:

1. execute `doTask()`

New record in DB y new message in kafka -> ok

2. STOP kafka

3. execute (again) `doTask()`

New record in DB!! -> not ok

**Comment by garyrussell** [comment]
You are not waiting for the result of the send. `send()` returns a `Future`; you need to `get(timeout, TimeUnit.SECONDS)` on the future to get an exception. By default, the client will wait 60 seconds for the broker (`max.block.ms`).

**Comment by gpando** [comment]
Thank you very much for the reply.

I understand the `future`, but in the documentation it does not use the `get`:

https://docs.spring.io/spring-kafka/reference/html/#transaction-synchronization

And other tests, without `get`, with exception are ok:

```
    @Transactional("transactionManager")
    public void doTaskKO() {
        doTask("KO");

        throw new RuntimeException("Ops");
    }
```

**Comment by garyrussell** [comment]
But that's how transaction synchronization works. The kafka transaction is committed after the DB. See the note in that document...

>Starting with versions 2.5.17, 2.6.12, 2.7.9 and 2.8.0, if the commit fails on the synchronized transaction (after the primary transaction has committed), the exception will be thrown to the caller. Previously, this was silently ignored (logged at debug). Applications should take remedial action, if necessary, to compensate for the committed primary transaction.

With this app...

```java
@SpringBootApplication
public class Kgh2411Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh2411Application.class, args);
	}

	@Bean
	ApplicationRunner runner(Test test) {
		return args -> {
			test.test();
			System.out.println("Stop Kafka; then hit enter");
			System.in.read();
			test.test();
		};
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("topic1").partitions(1).replicas(1).build();
	}

}

@Component
class Test {

	private final KafkaTemplate<String, String> template;


	public Test(KafkaTemplate<String, String> template) {
		this.template = template;
	}

	@Transactional("transactionManager")
	public void test () {
		template.send("topic1", "test");
	}

}
```
```properties
logging.level.org.springframework.transaction=trace
logging.level.org.springframework.kafka=debug
spring.kafka.producer.transaction-id-prefix=tx-
spring.kafka.producer.properties.max.block.ms=5000
```

I get this...

>2022-09-26 14:24:08.310 ERROR 65924 --- [           main] o.s.k.core.DefaultKafkaProducerFactory   : commitTransaction failed: CloseSafeProducer [delegate=org.apache.kafka.clients.producer.KafkaProducer@1391af3b]

>org.apache.kafka.common.errors.TimeoutException: Timeout expired after 5000ms while awaiting EndTxn(true)

The DB transaction has already committed; you would need to manually back that change out.

Or, you can force the Kafka transaction to commit before the database, by doing something like this...

```java
@Component
class DB {

	private final Test test;

	private final TransactionTemplate transTemplate;


	public DB(Test test, KafkaTransactionManager<?, ?> tm) {
		this.test = test;
		this.transTemplate = new TransactionTemplate(tm);
	}

	@Transactional("transactionManager")
	public void test () {
		this.transTemplate.executeWithoutResult(status -> this.test.test());
	}

}

@Component
class Test {

	private final KafkaTemplate<String, String> template;


	public Test(KafkaTemplate<String, String> template) {
		this.template = template;
	}

	public void test () {
		template.send("topic1", "test");
	}

}
```

**Comment by gpando** [comment]
Thank you very much for the explanation and the example.
