### ISSUE TITLE
How to manually set the offset value in Spring Kafka Listener ?

### ISSUE THREAD

**Issue by dilipthelip** [spring-projects/spring-kafka#242]
Hi All,

We have a scenario where if it errors out in our consumer then we would like to reprocess from the point where it error out.  Is there a way to set the offset value to the consumer so that it can read from that value in the topic to reprocess the messages from that point ?

Config:
````java
@Bean
    KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<String, String>> kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(2);
        factory.getContainerProperties().setPollTimeout(3000);
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL);
        factory.setRetryTemplate(new RetryTemplate() {{
            setRetryPolicy(new AlwaysRetryPolicy());
            setBackOffPolicy(new FixedBackOffPolicy() {{
                setBackOffPeriod(1000); // back off for 1 second between retries
            }});
        }});

        return factory;
    }
````

Listener Code:
````java
@KafkaListener(id = "Listener", topics = {"${topic}"} )
   public void onMessage(ConsumerRecord record, Acknowledgment acknowledgment) {

       try {
           
               logger.info("Read XML is : " + record.value());
               orderReleaseHeaderVO = parser.parseAttributes((String) record.value());
        
           acknowledgment.acknowledge();
       }
       catch(Exception e){
           logger.error("Exception Occured : OnMessage Exception : ", e);
       }
   }
````

**Comment by dilipthelip** [comment]
We are using Spring Kafka 1.0.5 Release and 0.9 Kafka Cluster.

**Comment by artembilan** [comment]
The `seek` support has been introduced since `1.1.x`: http://docs.spring.io/spring-kafka/reference/html/_reference.html#seek.

**Comment by dilipthelip** [comment]
Is this supported against kafka cluster 0.9 ?

**Comment by artembilan** [comment]
M-m-m. You can try to downgrade transitive dependency for `kafka-clients` from its `0.10.1.1` to your `0.9`. Otherwise `0.10` clients aren't compatible with broker `0.9`.

I will check our sample app on the matter lately....

**Comment by artembilan** [comment]
You know, I have just tested sample application - Spring Kafka `1.1.3` and Apache Kafka `0.9.0.1`.
Even if it can be compiled we have some API incompatibility at runtime.

So, the answer is no:  Spring Kafka `1.1.3` can't be used with Apache Kafka `0.9.0.1`. Therefore a `seep` API isn't available for you if you are stick with Apache Kafka `0.9`.

Only a choice to consider to upgrade your cluster to `0.10`.

I'm keeping this open until your answer. Otherwise I'm not sure what we can do here yet...

**Comment by dilipthelip** [comment]
Sure @artembilan. I was able to achieve the same using the seek on a 0.10 version of kafka cluster. Thanks for sharing the link.
