### ISSUE TITLE
spring-kafka-test scala transitive vulnerability

### ISSUE THREAD

**Issue by nikoncode** [spring-projects/spring-kafka#2426]
I am using spring-kafka-test (org.springframework.kafka:spring-kafka-test@2.8) together with latest spring boot 2.7.4.

I know that it is a test dependency but snyk detected vulnerability in following path:
`org.springframework.kafka:spring-kafka-test@2.8.9 › org.apache.kafka:kafka_2.13@3.1.2 › org.scala-lang:scala-library@2.13.6`

https://security.snyk.io/vuln/SNYK-JAVA-ORGSCALALANG-3032987

I know that I can pin other version of broker or even scala, but can transitive itself be fixed?

**Comment by garyrussell** [comment]
cc/ @wilkinsona Thoughts? If we override here, will Boot need to do so too?

**Comment by wilkinsona** [comment]
Boot doesn't have a managed version for Scala and we wouldn't want to add one. If I were you I wouldn't do anything in Spring Kafka either. IMO, this should be fixed at source with a new Kafka 3.1.x release that upgrades to Scala 2.13.9.

**Comment by garyrussell** [comment]
That’s what I thought. @nikoncode please raise the issue with the Kafka folks.
