### ISSUE TITLE
Kafka version support confusion

### ISSUE THREAD

**Issue by cen1** [spring-projects/spring-kafka#243]
Under Reference guide, Quick start, Compatibility it says compatible with Kafka 0.9.0.1 (http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_introduction.html#quick-tour).
But when checking the gradle dependencies for spring-kafka I can see that the project uses 0.10.1.1 kafka clients.

So basically my question is, can I use 1.1.2 with Kafka 0.10.1.1?

**Comment by garyrussell** [comment]
Yes; the documentation is incorrect, 1.0.x is for 0.9.x.x; 1.1.x is for 0.10.x.x.
