### ISSUE TITLE
spring-kafka 1.0.5 create listener thread when rebalance every time

### ISSUE THREAD

**Issue by jintianfan** [spring-projects/spring-kafka#245]
I can not understand this design,I had created a listenerInvoker,why need create another when rebalance,and the first listenerInvoker still running!
Thanks for any advices!

**Comment by artembilan** [comment]
`ListenerInvoker` is volatile, lightweight and stateless object.
More over it is a part of the `ListenerConsumer`.
When the `onPartitionsRevoked()` happens we stop the current `ListenerInvoker` in the `stopInvokerAndCommitManualAcks()`.
There is no guarantee that `onPartitionsAssigned()` will be performed for this `ListenerConsumer`, therefore after rebalance we might not have any `ListenerInvoker` any more.

According Kafka JavaDocs:
```
 * It is guaranteed that all the processes in a consumer group will execute their
 * {@link #onPartitionsRevoked(Collection)} callback before any instance executes its
 * {@link #onPartitionsAssigned(Collection)} callback.
```

So, if your `onPartitionsRevoked()` isn't called and the first `listenerInvoker` still running, you should move away that Apache Kafka version.

Reopen for your feedback...
