### ISSUE TITLE
Unable to create multiple listeners using same class with KafkaListener annotation at class level

### ISSUE THREAD

**Issue by bdbogjoe** [spring-projects/spring-kafka#2451]
There is issue in this line, we have to exclude the current bean if has no annotation in methods **or** in class level, should be something like : 

```
if (annotatedMethods.isEmpty() && ! hasClassLevelListeners) {
          this.nonAnnotatedClasses.add(bean.getClass());
          this.logger.trace(() -> "No @KafkaListener annotations found on bean type: " + bean.getClass());
}
```

https://github.com/spring-projects/spring-kafka/blob/c6bbba8b55406ff6ba605f350959ab070bc0cfea/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L380

**Comment by garyrussell** [comment]
Thanks for reporting.

Curious: How did you create an issue with no labels? The [New Issue]https://github.com/spring-projects/spring-kafka/issues/new/choose page does not have an option for that.
