### ISSUE TITLE
KafkaAdminOperations interface add method to list all topics

### ISSUE THREAD

**Issue by ctlove0523** [spring-projects/spring-kafka#2456]
**Expected Behavior**

add method to list all topics like:
~~~java
Map<String, TopicDescription> listTopics();
~~~
**Current Behavior**

current has no method to list all topics

**Context**
currently our team begin use spring-kafka to replace old sdk about kafka,in our codes we need to list all topics.

**Comment by garyrussell** [comment]
The `KafkaAdmin` is not intended as a replacement for the `AdminClient` provided by `kafka-clients` and its rich. API. It solely exists to automatically provision topics via `NewTopic` beans in the application context; it does, however, expose its configuration so you can easily use an `AdminClient`.

Use 

```java
try (AdminClient client = AdminClient.create(kafkaAdmin.getConfigurationProperties())) {
	Set<String> topics = client.listTopics().names().get(10, TimeUnit.SECONDS);
	System.out.println(topics);
}
```

**Comment by ctlove0523** [comment]
> The `KafkaAdmin` is not intended as a replacement for the `AdminClient` provided by `kafka-clients` and its rich. API. It solely exists to automatically provision topics via `NewTopic` beans in the application context; it does, however, expose its configuration so you can easily use an `AdminClient`.
> 
> Use
> 
> ```java
> try (AdminClient client = AdminClient.create(kafkaAdmin.getConfigurationProperties())) {
> 	Set<String> topics = client.listTopics().names().get(10, TimeUnit.SECONDS);
> 	System.out.println(topics);
> }
> ```

understand
