### ISSUE TITLE
Please add links to spring-docs resources

### ISSUE THREAD

**Issue by zgagnon** [spring-projects/spring-kafka#249]
When viewing the Spring Docs for spring-kafka (http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_preface.html) it is very difficult to find this github, or the javadoc. It would be helpful if the documentation listed there contained links to both.

Thanks!

**Comment by artembilan** [comment]
Does this work for you http://projects.spring.io/spring-kafka/ ?

**Comment by artembilan** [comment]
I have just open even the latest Spring Framework doc and there is no such an information, too: http://docs.spring.io/spring/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/spring-introduction.html

But you really can find it in the main project page: https://spring.io/projects

**Comment by zgagnon** [comment]
The spring.io page is great. Maybe a link back to it from the reference would be helpful tho? I arrived there through Google, not through the spring.io page.
