### ISSUE TITLE
Reuse retry topic for the maxInterval delay of exponential backoff

### ISSUE THREAD

**Issue by jgslima** [spring-projects/spring-kafka#2496]
Related to the discussion below:

https://github.com/spring-projects/spring-kafka/discussions/2484

**Expected Behavior**
In order to allow the configuration of an exponential backoff policy that keeps trying for a long time (say some hours), to have some way to use a single retry topic for the attempts corresponding to the `maxInterval` delay. This makes it more viable to configure the policy to keep trying for a long time because a lot of topics are not needed.

**Current Behavior**
When using exponential backoff, the number of needed retry topics is always the configured `maxAttempts` minus 1.

**Context**
For instance, when configuring the exponential backoff with `initialInterval=1000`, `multiplier=2`, and `maxInterval=16000`, in order to keep trying for one hour, one would need to configure `maxAttempts` as 229, and by default the needed retry topics would be:

* -retry-1000
* -retry-2000
* -retry-4000
* -retry-8000
* -retry-16000-0
* -retry-16000-1
* -retry-16000-2
* ...
* -retry-16000-224

When using the strategy that reuses the retry topic for the same intervals, in the same configuration above the needed retry topics would be only 5:

* -retry-1000
* -retry-2000
* -retry-4000
* -retry-8000
* -retry-16000

**Comment by jgslima** [comment]
> @jgslima what's the reason you don't want to just use a single retry topic for all intervals (like the single topic option for fixed delays)? That's what we'd like to do.
> 
> @garyrussell, anyone: why is the single retry topic option only supported for fixed backoff policies and not exponential or other sleeping backoff policies? Looking at the code I see it tracks the next sleep interval in a kafka header so doesn't require that it be part of the topic name.

It is not possible to use the single retry option for backoffs that may have distinct sleep times for distinct records. The general algorithm only works with the assumption that, in a partition (actually in the topic as a whole), records with higher offsets have should not be processed before records whith lower offsets. Because the Consumer is paused based on the sleep time of the next record.

The motivation to have this new kind of policy is to allow a configuration where you can have the first retries done quickly (with a low interval), keep retrying for a large amount of time (say 4 or 6 hours), but without having to have an excessive amount of retry topics. Currently, when using exponential backoff, you need a large amount of retries topics for this. See how I explained in the issue description.

**Comment by ctoomey** [comment]
> It is not possible to use the single retry option for backoffs that may have distinct sleep times for distinct records. The general algorithm only works with the assumption that, in a partition (actually in the topic as a whole), records with higher offsets should not be processed before records whith lower offsets. Because the Consumer is paused based on the sleep time of the next record.

Ah right, I'd forgotten about the problem w/ mixing records w/ different sleep times, thanks.

**Comment by anshuman-airwallex** [comment]
Is it possible to port this to 2+ version as from what I understand spring kafka 3+ uses java 17. Is there a version of spring kafka 3 that works with java 11?

**Comment by anshuman-airwallex** [comment]
Thanks. But would it be possible to please publish java 11 jars for 3+ version. I could compile and use it myself but I am sure there are others in my position who would still be using java 11 and will not be able to use 3+ version. Thanks a lot.

**Comment by garyrussell** [comment]
No; 3.0.x REQUIRES Java 17; you can't compile it with Java 11.

**Comment by garyrussell** [comment]
Here is a possible work around for 2.9.x users:

```java
@SpringBootApplication
@EnableScheduling
public class Kgh2496Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh2496Application.class, args).close();
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<String, String> template, KafkaAdmin kafkaAdmin,
			KafkaListenerEndpointRegistry registry) {
		return args -> {
			// stop the unused containers
			registry.getListenerContainer("kgh2496-retry-2000-1").stop();
			registry.getListenerContainer("kgh2496-retry-2000-2").stop();
			// delete the extra topics
			try (AdminClient admin = AdminClient.create(kafkaAdmin.getConfigurationProperties())) {
				admin.deleteTopics(List.of("kgh2496-retry-2000-1", "kgh2496-retry-2000-1")).all().get(10,
						TimeUnit.SECONDS);
			}
			template.send("kgh2496", "foo");
			Thread.sleep(30_000);
		};
	}

	@Bean
	KafkaTemplate<String, String> singleLastTopicTemplate(ProducerFactory<String, String> pf) {
		Pattern pat = Pattern.compile(".*-retry-.*-.*");
		return new KafkaTemplate<>(pf) {

			@Override
			protected ListenableFuture<SendResult<String, String>> doSend(ProducerRecord<String, String> pRec) {
				Matcher matcher = pat.matcher(pRec.topic());
				if (matcher.matches()) {
					ProducerRecord<String, String> newRec =
							new ProducerRecord<String, String>(pRec.topic().replaceAll("-[0-9]+$", "-0"),
							pRec.partition(), pRec.timestamp(), pRec.key(), pRec.value(), pRec.headers());
					return super.doSend(newRec);
				}
				else {
					return super.doSend(pRec);
				}
			}

		};
	}

}

@Component
class Listener {

	@RetryableTopic(attempts = "6", backoff = @Backoff(delay = 1000, multiplier = 1.5, maxDelay = 2000),
			kafkaTemplate = "singleLastTopicTemplate")
	@KafkaListener(id = "kgh2496", topics = "kgh2496")
	void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
		throw new RuntimeException("test");
	}

	@DltHandler
	void handle(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
	}

}
```
```
foo from kgh2496
foo from kgh2496-retry-1000
foo from kgh2496-retry-1500
foo from kgh2496-retry-2000-0
foo from kgh2496-retry-2000-0
foo from kgh2496-retry-2000-0
foo from kgh2496-dlt
```

**Comment by anshuman-airwallex** [comment]
This is super helpful. Thanks a lot!
