### ISSUE TITLE
Add section to spring-docs detailing how to configure a MessageListenerContainer with a MessageListener

### ISSUE THREAD

**Issue by zgagnon** [spring-projects/spring-kafka#250]
When reading the spring-docs (http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_preface.html), we were able to create a *MessageListener* instance. However, when creating the *MessageListenerContainer*, both the configuration of the container and the method to attach the *MessageListener* to the container were very difficult to find. A section detailing this process, possibly with code examples, would be very helpful.

**Comment by javacup** [comment]
I was able to do something like this. 
```
   @Bean
    ConcurrentKafkaListenerContainerFactory<Integer, String>
                        kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
                                new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(3);
        factory.getContainerProperties().setPollTimeout(3000);
        factory.getContainerProperties().setMessageListener(listener());
        return factory;
    }
   @Bean
    public Listener listener() {
        return new Listener();
    }

**Comment by artembilan** [comment]
The [Very, Very Quick](http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_introduction.html#_very_very_quick) example describes that for you: 
```
ContainerProperties containerProps = new ContainerProperties("topic1", "topic2");
final CountDownLatch latch = new CountDownLatch(4);
containerProps.setMessageListener(new MessageListener<Integer, String>() {

        @Override
        public void onMessage(ConsumerRecord<Integer, String> message) {
            logger.info("received: " + message);
            latch.countDown();
        }

});

KafkaMessageListenerContainer<Integer, String> container = createContainer(containerProps);
...
private KafkaMessageListenerContainer<Integer, String> createContainer(
                        ContainerProperties containerProps) {
    Map<String, Object> props = consumerProps();
    DefaultKafkaConsumerFactory<Integer, String> cf =
                            new DefaultKafkaConsumerFactory<Integer, String>(props);
    KafkaMessageListenerContainer<Integer, String> container =
                            new KafkaMessageListenerContainer<>(cf, containerProps);
    return container;
}
```

What have we missed, please?

**Comment by zgagnon** [comment]
I did eventually find it. It was only in this code example, and not called out with any copy. It would be nice if there was an explanation of how to do it, as well as an example.

**Comment by artembilan** [comment]
Sorry, to do what? Example for what?
Any comments about the link from my comment above?

How can we help you if your questions are so unclear?

The `KafkaMessageListenerContainer` cannot be created without `ContainerProperties`. That is only the way how we can specify the `Listener` reference.

**Comment by zgagnon** [comment]
Page 4 of the reference is the page which explains in detail about *MessageListener*s and *MessageListenerContainer*s. On that page, it explains both how to create a *MessageListener* and the kinds of *MessageListenerContainer* available. It does not, however, list anywhere on the page (as of the referred to version, 1.2) that you need to set the *MessageListener* on the *ContainerProperties*, or mention the specific method (*ContainerProperties.setMessageListener*) needed to do it. 

The Very, Very Quick example should not be the only source of information on how to do things. It does not (and probably should not) contain the depth of information to fully explain the how and why of things.

**Comment by artembilan** [comment]
OK. Sold.

@zgagnon ,

Let us know if you are open for contribution on the matter or we should proceed ourselves.

Thanks!

**Comment by zgagnon** [comment]
I should have time to put something together today or tomorrow, I'm totally open to contributing.

**Comment by zgagnon** [comment]
Pull request is here: https://github.com/spring-projects/spring-kafka/pull/281

I placed the new section at the end of the current ContainerProperties section because it seemed like the place that all the information was present.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/commit/0e0599eef8b938b56da532fbc392a3251ee34a43

@zgagnon ,
thank you very much for the contribution.
Looking forward for more!
