### ISSUE TITLE
Use Producer/Consumer Bootstrap Servers if Different to the Context's KafkaAdmin Servers

### ISSUE THREAD

**Issue by codependent** [spring-projects/spring-kafka#2505]
Spring Kafka 3.0.0

As seen [in the following Spring Cloud Stream issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2576#issuecomment-1348666138), when activating the binder observability the `KafkaAdmin` client doesn't use the `spring.cloud.stream` properties and requires the configuration of the ones in `spring.kafka`

**Comment by garyrussell** [comment]
Closing this; the functionality is already supported by `KafkaAdminsetBootstrapServersSupplier()`.

**Comment by garyrussell** [comment]
See https://github.com/spring-cloud/spring-cloud-stream/issues/2597

**Comment by garyrussell** [comment]
Correction - this is about configuring the admin used by the template when observability is enabled.
