### ISSUE TITLE
max-poll-records does not poll more than 128 records in a Kafka batch listener

### ISSUE THREAD

**Issue by rameshsubramanian82** [spring-projects/spring-kafka#2506]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

Spring Kafka Version used: 2.8.4
**Describe the bug**
Bug: Below is the configuration I have in my application
spring:
   kafka:
     listener:
       type: batch
     consumer:
        max-poll-records: 2000

And in the listener is configured to be a batch listener. 
When listener polls the records, I could see only 128 records in a single poll. Though I have given 2000 records to be polled, it gets only 128 records. below is my code:

@KafkaListener(topics="sample", groupId="groupid", containerFactory=CustomerFactoryDefined)
public void onMessageTopic(List<ConsumerRecord<String, String>> consumerRecord) throws Exception{
    LOGGER.info("TotalMessage received:"+consumerRecord.stream().count());
}

And the output is:
TotalMessage received: 128
TotalMessage received: 128
TotalMessage received: 128
TotalMessage received: 128
TotalMessage received: 128
TotalMessage received: 128
TotalMessage received: 128

I have around 1M records sitting in the Kafka topic, however the listener pulls only 128 records on each pull. This degrades my performance.
I did not set poll-timeout as that did not impact anything. 
And I set the concurrency to 10 as my topic has 10 partitions.

Please help providing the detail why the batch listener polls only 128 records.

**Comment by garyrussell** [comment]
This has nothing to do with Spring - all interaction with the broker is delegated to the `kafka-clients`.

`max.poll.records` means exactly that, MAX - it defines the largest number of records that can be returned by a poll; it has no bearing on the actual number of records returned (except to cap it).

The actual number of records returned depends on other properties, as well as other factors.

See `fetch.max.bytes`, `fetch.min.bytes`, `fetch.max.wait.ms`, ...

See https://kafka.apache.org/documentation/

There are other things that might affect the number of records returned - e.g. distribution of records in partitions across multiple broker instances.
