### ISSUE TITLE
Question about ConcurrentMessageListenerContainer

### ISSUE THREAD

**Issue by loudywen** [spring-projects/spring-kafka#251]
Hi,

Does this `ConcurrentMessageListenerContainer` behavior like `DefaultMessageListenerContainer` in Spring-JMS? DMLC will automatically spin up threads based on load.

**Comment by artembilan** [comment]
No, it doesn't.
See Reference Manual: http://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/html/_reference.html#_concurrentmessagelistenercontainer

Please, consider do not ask questions here. There is StackOverflow on the matter.
GitHub issues for bugs and feature requests.

**Comment by garyrussell** [comment]
The rationale is that, when you add/remove consumers, Kafka rebalances the partitions (if you are using group management), which can be expensive and cause interruptions.

If you are not using group management, spring-kafka would have to do the rebalancing, which would be equally expensive and cause interruptions.

**Comment by loudywen** [comment]
Yes, I got it, Gary. I thought the same :)
