### ISSUE TITLE
Statefull ReplyingKafkaTemplate and AggregationgReplyingKafkaTemplate

### ISSUE THREAD

**Issue by pszymczyk** [spring-projects/spring-kafka#2510]
**Expected Behavior**

`ReplyingKafkaTemplate` and `AggregationgReplyingKafkaTemplate` stores correlation ids in Kafka topic.

**Current Behavior**

Right now we store correlation ids in memory.

**Context**

Right now, both `ReplyingKafkaTemplate` and `AggregatingReplyingKafkaTemplate` stores pending requests in memory, so during unexpected application shutdown, some responses will be lost. Due to that limitation, practically very short `replyTimeout ` makes sens. Instead of storing pending requests in memory we can store it in auto created Kafka topic, so we can easily recover after unexpected application shutdown, and handle all responses.

**Comment by garyrussell** [comment]
I don't think this is practical; when you perform a `sendAndReceive()` operation, you get a `CompletableFuture` returned - the correlation key is used as the key in a map so we can look up the future when the reply is received so it can be completed.

Since the future is a live object on the heap, even if we stored the key in a topic, there is no way to recreate the future, and therefore no way to convey the reply to the user application code.

Of course, the application can always do its own request/reply correlation, using whatever techniques it needs (without using the RKT).

Happy to hear suggestions on how to resolve that, if you have ideas.

**Comment by pszymczyk** [comment]
So my idea is to stick with current `CompletableFuture sendAndReceive()` approach and extend `ReplyingKafkaTemplate` with some `MissedResponsesHandler`, pass it by constructor or setter. Then regular processing works the same as now, and after unexpected application crashes we can restore pending requests from Kafka, match them with responses have come during inactivity and handle all of them properly.

```java
public interface MissedResponsesHandler<K, V> {
	void onResponse(ConsumerRecord<K, V> data);
}
```

```java
public class NoOperationMissedResponsesHandler<K, V> implements MissedResponsesHandler<K,V>{

	private static final LogAccessor LOGGER = new LogAccessor(LogFactory.getLog(NoOperationMissedResponsesHandler.class));

	@Override
	public void onResponse(ConsumerRecord<K, V> data) {
		LOGGER.warn("Missed response message, topic: " + data.topic() + ", partition: " + data.partition() + ", offset " + data.offset());
	}
}
```

```java
public ReplyingKafkaTemplate(ProducerFactory<K, V> producerFactory,
			GenericMessageListenerContainer<K, R> replyContainer) {

		this(producerFactory, replyContainer, false, new NoOperationMissedResponsesHandler<>());
	}

	public ReplyingKafkaTemplate(ProducerFactory<K, V> producerFactory,
			GenericMessageListenerContainer<K, R> replyContainer, boolean autoFlush,
								 MissedResponsesHandler<K,V> missedResponsesHandler) {
```

**Comment by garyrussell** [comment]
I still don't think it needs the added complexity of storing the keys; you can simply subclass the template and override `logLateArrival` - that way, you will get all uncorrelated (late) replies; the app can decide what do with them.

**Comment by pszymczyk** [comment]
Cool, `logLateArrival` sounds like a good solution, thanks!
