### ISSUE TITLE
Confusing Documentation w.r.t. EOS Mode V2 and Zombie Fencing via `transactional.id` in Spring Kafka 3.0.0

### ISSUE THREAD

**Issue by LukasHeimann** [spring-projects/spring-kafka#2515]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.0

**Describe the bug**

The documentation for Transactions, in it's Overview subsection, mentions how the `transactional.id` is derived from the `transactionIdPrefix`: https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka-docs/src/main/asciidoc/kafka.adoc#overview-1

Specifically, it describes why the naming scheme for transactions started by a listener container is different from the default of `transactionIdPrefix<n>`:

> This is to properly support fencing zombies, [as described here](https://www.confluent.io/blog/transactions-apache-kafka/).

This _used_ to be valid information, as with EOS Mode V1, there really were different semantics at play. Especially when having multiple instances of an application consuming messages, this information was in fact important to know about, as including the instance number in the `transactionIdPrefix` needed to be done for the normal case, but not for the transactions started by a listener container. Compare https://github.com/spring-projects/spring-kafka/issues/1503 and https://stackoverflow.com/questions/56971389/what-should-be-the-transactionidprefix-for-multiple-spring-boot-consumer-produce

With V2, however, this is not necessary anymore, as zombie fencing is handled differently. The _old_ documentation of Spring Kafka 2.8.x actually mentions this, because it supports both modes: https://github.com/spring-projects/spring-kafka/blob/2.8.x/spring-kafka-docs/src/main/asciidoc/kafka.adoc#transaction-id-prefix

> This problem (different rules for transactional.id) has been eliminated when EOSMode.BETA is being used (with broker versions >= 2.5); see [Exactly Once Semantics](https://docs.spring.io/spring-kafka/docs/2.8.11/reference/html/#exactly-once).

The current documentation does _not_ mention this, creating lots of confusion on what should be done.

**To Reproduce**

n/a (read the documentation and compare with previous versions)

**Expected behavior**

I think, the documentation could be clearer here. In the Overview section, it could mention that `transactionIdPrefix` is supposed to be unique per instance of the application, because of the way `transactional.id` is built (and it makes sense to write that pattern down). The section about fencing zombies should be removed and perhaps be replaced by a sentence mentioning that for transactions started by a listener container, EOS Mode V2 does not rely on the `transactional.id` to achieve transactional handling.

I don't know how relevant the pattern to compute the `transactional.id` is anymore in case transactions started by a listener container, and if the fallback property `producerPerConsumerPartition` is still relevant -- if not, this should probably be removed as well.

Thank you for considering this!

**Sample**

n/a

**Comment by garyrussell** [comment]
Thanks for reporting; `producerPerConsumerPartition` is deprecated (and ignored)...

https://github.com/spring-projects/spring-kafka/blob/d34394eeb555103f9c449f088dc8d92671de103d/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L435-L445

**Comment by garyrussell** [comment]
Happy to consider a PR for the fix, if you would like to submit one.

**Comment by LukasHeimann** [comment]
Hi @garyrussell,

thank you for your response! I've opened https://github.com/spring-projects/spring-kafka/pull/2524. Currently, it only includes the minimal changes to remove the outdated documentation. I've included a suggestion for two additional sentences of clarification. If this is okay for you, let me know or just accept the suggestion in the PR.

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-kafka/commit/7e336d19cda31d85f0295afb4288cf1cd7191b9a

**Comment by rishiraj88** [comment]
Thanks, @garyrussell
