### ISSUE TITLE
Topic partition is not resumed after re-assignment for RetryTopic

### ISSUE THREAD

**Issue by dmyronenko** [spring-projects/spring-kafka#2525]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.11

**Describe the bug**

From time to time we get a bug when doing rolling deployment with k8. What happens is that consumption from one of partitions is not being resumed after this partition is assigned to different consumer and then within retry-delay interval reassigned back to the initial consumer.

**To Reproduce**

Topic-A-retry-0 - the retry delay on this topic is 1 minute. In our case it has 5 partitions.

1. Topic-A-retry-0 partition 0 assigned to C1
2. Send message to this partition so that C1 pauses consumption for partition 0

[within 1 minute after sending message]

3. Simulate rolling update by running one more consumer C2. Topic-A-retry-0 partition 0 has to be assigned to C2
4. Bring down C2. Topic-A-retry-0 partition 0 assigned back to C1
5. After this the partition 0 on C1 will be put on pause but will never resume consumption.

[within 1 minute after sending message]

**Expected behavior**

Consuming should be resumed for a given partition after retry delay

**Notes**

I checked code a bit and what happens internally is that:
1. when partition is put on pause in PartitionPausingBackoffManager it calls 	 
```
AbstractMessageListenerContainer
	@Override
	public void pausePartition(TopicPartition topicPartition) {
		this.pauseRequestedPartitions.add(topicPartition);
	}
```
and creates a backoff Context that will resume partition(remove this item from list) based on processing of ListenerContainerPartitionIdleEvent.

One thing to note here is that during processing of the onPartitionsRevoked/Assigned the pauseRequestedPartitions are not cleaned up. But I guess it was a conscious choice because in onPartitionsAssigned these pauseRequestedPartitions are used to pause consumers.

2. What happens on Step 4-5 when partition 0 is assigned back to C1 is that this partition remains in pauseRequestedPartitions. And in onPartitionsAssigned it is being paused
```
KafkaMessageListenerContainer
				Collection<TopicPartition> toRepause = new LinkedList<>();
				partitions.forEach(tp -> {
					if (isPartitionPauseRequested(tp)) {
						toRepause.add(tp);
					}
				});
				if (!ListenerConsumer.this.consumerPaused && toRepause.size() > 0) {
					ListenerConsumer.this.consumer.pause(toRepause);
					ListenerConsumer.this.logger.debug(() -> "Paused consumption from: " + toRepause);
					publishConsumerPausedEvent(toRepause, "Re-paused after rebalance");
				}
				this.revoked.removeAll(toRepause);
				ListenerConsumer.this.pausedPartitions.removeAll(this.revoked);
				this.revoked.clear();
```
Please note here that after calling:
ListenerConsumer.this.consumer.pause(toRepause);
The toRepause partitions are not added to cache ListenerConsumer.this.pausedPartitions (only revoked are removed) which makes this cache out of sync with actual state of partitions. This also happens in other places in this class.

3. When the time to resume partition comes and PartitionPausingBackoffManager call resumePartition (removes it from pauseRequestedPartitions). On the next poll the consumer for that partition is not resumed.
```
KafkaMessageListenerContainer
		private void resumePartitionsIfNecessary() {
			Collection<TopicPartition> assigned = getAssignedPartitions();
			if (assigned != null) {
				List<TopicPartition> partitionsToResume = assigned
						.stream()
						.filter(tp -> !isPartitionPauseRequested(tp)
								&& this.pausedPartitions.contains(tp))
						.collect(Collectors.toList());
				if (partitionsToResume.size() > 0) {
					this.consumer.resume(partitionsToResume);
					this.pausedPartitions.removeAll(partitionsToResume);
					this.logger.debug(() -> "Resumed consumption from " + partitionsToResume);
					partitionsToResume
							.forEach(KafkaMessageListenerContainer.this::publishConsumerPartitionResumedEvent);
				}
			}
		}
```

Because here partitionsToResume are filtered based on this.pausedPartitions which is out of sync with actual KafkaConsumer.paused() state.

**Comment by dmironenko** [comment]
I guess the bug is cause by this change https://github.com/spring-projects/spring-kafka/pull/2353 where resume was removed from KafkaMessageListenerContainer

**Comment by garyrussell** [comment]
Reproduced - investigating...

**Comment by garyrussell** [comment]
@dmyronenko It looks like your analysis is correct. Thanks.

**Comment by dmyronenko** [comment]
Thanks for a quick fix @garyrussell ! Would it be also possible to back port it to 2.8 ?

**Comment by garyrussell** [comment]
@dmyronenko thank **you** for the report and providing detailed analysis - it is refreshing, and much appreciated, when users take the time to do so.

2.8.x is out of OSS support - https://spring.io/projects/spring-kafka#support

The last release was 2.8.11 on Nov 21.

2.9.x is fully compatible with Boot 2.7.x - https://spring.io/projects/spring-kafka#overview

If you have commercial support with VMware and cannot upgrade for some reason, you can request a 2.8 patch release via those channels.

I am sure you can understand that we can't maintain old branches indefinitely.

**Comment by dmyronenko** [comment]
> @dmyronenko thank **you** for the report and providing detailed analysis - it is refreshing, and much appreciated, when users take the time to do so.
> 
> 2.8.x is out of OSS support - https://spring.io/projects/spring-kafka#support
> 
> The last release was 2.8.11 on Nov 21.
> 
> 2.9.x is fully compatible with Boot 2.7.x - https://spring.io/projects/spring-kafka#overview
> 
> If you have commercial support with VMware and cannot upgrade for some reason, you can request a 2.8 patch release via those channels.
> 
> I am sure you can understand that we can't maintain old branches indefinitely.

@garyrussell thanks a lot for the provided information! Updating to 2.9.x makes more sense then as 2.8.x is being phased out.
