### ISSUE TITLE
Kafka Test with TestNG

### ISSUE THREAD

**Issue by lpcanh** [spring-projects/spring-kafka#253]
Hi,

Are there any way for using Kafka Embedded with TestNG ?

Please help !

Thanks.

**Comment by garyrussell** [comment]
I am not familiar with , but you should be able to use the code in the JUnit Rule to start a broker; you just need to extract the parts that don't have JUnit dependencies and start it before your tests.

**Comment by lpcanh** [comment]
Thank you.

I will try it and update status here.

**Comment by garyrussell** [comment]
We'd be happy to accept a [contribution](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc) if/when you get it working with TestNG.

**Comment by garyrussell** [comment]
Starting with version 2.0 (milestone 1 currently available), the `KafkaEmbedded` can be declared as a Spring Bean so should work with any testing framework.
