### ISSUE TITLE
Support loading trust stores from classpath

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-kafka#2546]
Hello Spring Kafka team,

Since this is my first post, wanted to say big thanks for this project. 
Happy New Year! Best wishes for 2023.
This project is super cool and making Spring and Kafka work together in a very nice way.
I would like to start an enhancement request please.

Currently, if the SpringBoot app needs to connect to a Kafka cluster that is behind SSL, we can configure the keystore and truststore via:

```
spring.kafka.security.protocol=SSL
spring.kafka.ssl.trust-store-location=
spring.kafka.ssl.trust-store-password=
spring.kafka.ssl.key-store-location=
spring.kafka.ssl.key-store-password=
```

if the value is something like ```spring.kafka.ssl.key-store-location=file:///path/to/keystore.jks```, it works like a charm, amazing support.

However, if the stores are located under ```src/main/resources``` and then packaged inside the jar, the value needs to be something like: ```spring.kafka.ssl.key-store-location=classpath:keystore.jks```

And unfortunately, this will yields this exception: Cannot be resolved to absolute file path because it does not reside in the file system

After looking online, it seems there is this ticket opened in year 2018: https://issues.apache.org/jira/browse/KAFKA-7685

Years after this ticket is opened, now with SpringBoot 3 and Spring 6, may I ask if Spring Kafka team can still consider this feature please? 

Many projects do put stores inside resources folder.

Thank you for the consideration.

**Comment by garyrussell** [comment]
Unfortunately, this is out of Spring's control; the stores are loaded by the kafka-clients.

This requires a change there but it seems the Kafka community does not consider it an urgent feature.

That said, the last comment on that JIRA does discuss a work around, but they have provided little detail.

Sorry; there is nothing we can do here.

**Comment by patpatpat123** [comment]
I understand it is not urgent, workaround exists, etc...

But can we keep the ticket as enhancement request?
