### ISSUE TITLE
The RetryTopicBeanNames.DEFAULT_SCHEDULER_WRAPPER_BEAN_NAME accidentally points to defaultRetryTopicKafkaTemplate

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-kafka#2557]
Back port of issue #2555

**Comment by garyrussell** [comment]
@artembilan Thanks - FYI, the type and specific text (referencing the PR) is required so that the issue appears correctly in the generated change log (and the contributor gets recognized).

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-kafka/commit/576e854f15523c4fa9170a03506be7d0df513203
