### ISSUE TITLE
Consume messages and start processor threads

### ISSUE THREAD

**Issue by TejasD10** [spring-projects/spring-kafka#257]
Hello,

I am very new to using spring-kafka and having the following question while designing a solution for my project:
1. I am having 7 consumer instances in a consumer group all running on separate machines and i have a topic on my kafka cluster with 7 partitions.
2. After receiving a message on the consumer, my service/processing the received message might take about 5-7 minutes in execution and in that mean time i don't want to stop receiving messages because i am trying to get more throughput.
3. One possible solution that we are thinking is once we receive a message from kafka we spawn up a new thread and complete the execution on it, but then i wouldn't be able to ACK the message properly in case of execution failure.

What are the best options for me so that even my incoming messages increase in number i would be able to provide better throughput.

Feel free to ask questions and get more info.

**Comment by garyrussell** [comment]
Add more partitions and increase the concurrency on each container - for example with 49 partitions you could have 7 consumers per container.

**Comment by TejasD10** [comment]
Thank you @garyrussell !
