### ISSUE TITLE
Container Does Not Pause for Missing Acks After a Rebalance

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2581]
### Discussed in https://github.com/spring-projects/spring-kafka/discussions/2575

Reproducer provided in the discussion exhibits the behavior; the container should again pause after the second set of 500 records are received.

**Comment by AminArria** [comment]
Tested with 3.0.3-SNAPSHOT and everything is working as expected :smile: 

Thank you so much for the help with this and the quick turn around!

**Comment by garyrussell** [comment]
Thanks for testing; the 3.0.3 release is scheduled for next Tuesday (and 2.9.6).
