### ISSUE TITLE
 KafkaMessageListenerContainer pauses for a long time after error handling

### ISSUE THREAD

**Issue by antonin-arquey** [spring-projects/spring-kafka#2596]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

`>= 2.9.0`

**Describe the bug**

It is stated in the documentation that

> Starting with version 2.9, the DefaultErrorHandler can be configured to provide the same semantics as seeking the unprocessed record offsets as discussed below, but without actually seeking. Instead, the records are retained by the listener container and resubmitted to the listener after the error handler exits (and after performing a single paused poll(), to keep the consumer alive; 

Listeners that receives a large amount of data will start to lag behind quickly if they encounter unexpected errors during processing because they are constantly paused and polling for a long time (by default the poll timeout is 5 seconds but could be larger if set otherwise by the user).

**To Reproduce**

Really easy to test, just throw any exception in a listener configured with a [CommonLoggingErrorHandler](https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java) and a poll timeout set to any large value.

The listener will be stuck for the duration of the poll timeout before processing the remaining records.

**Expected behavior**

Do not poll with the consumer paused before processing the remaining records (or at least poll with a shorter poll timeout) as it is not expecting to receive a record anyway.

This should probably be mentionned in the [release notes](https://docs.spring.io/spring-kafka/reference/html/#spring-kafka-intro-new) as it seems small but is quite a big behavoural change and can lead to issues for some people upgrading to SpringBoot 3.

**Comment by garyrussell** [comment]
>a big behavoural change

?? 

The option is turned off by default for exactly that reason.

>Do not poll with the consumer paused ...

We have to poll, to avoid a possible rebalance when there are many errors in the records returned by the previous poll.

But your point is well taken. We should certainly reduce the poll time to zero (or near it) when we know that all partitions are paused.

In a future release, we should consider reducing the default poll timeout.

**Comment by antonin-arquey** [comment]
> ??
> 
> The option is turned off by default for exactly that reason.

Sorry you are right, the `DefaultErrorHandler` does not behave this way so in fact there is no behavioural change out of the box.

The issue we faced is that we used the `CommonLoggingErrorHandler` that replaced the previously existing [LoggingErrorHandler](https://github.com/spring-projects/spring-kafka/blob/2.8.x/spring-kafka/src/main/java/org/springframework/kafka/listener/LoggingErrorHandler.java) in version 2.8.

Then when we tried the upgrade to springboot 3, we encountered the issue as we pulled in the seeking change stated by the documentation. 

It was weird for us as it is the most 'harmless' of error handlers and we did not expect any changes from the previous one.

Maybe the misunderstanding comes from the default implementations in the `CommonErrorHandler ` interface that enable this behaviour by default for error handlers that do not override them:

```java
/**
* Return false if this error handler should only receive the current failed record;
* remaining records will be passed to the listener after the error handler returns.
* When true (default), all remaining records including the failed record are passed
* to the error handler.
* @return false to receive only the failed record.
* @deprecated in favor of {@link #seeksAfterHandling()}.
* @see #handleRecord(Exception, ConsumerRecord, Consumer, MessageListenerContainer)
* @see #handleRemaining(Exception, List, Consumer, MessageListenerContainer)
*/
@Deprecated(since = "2.9", forRemoval = true) // in 3.1
default boolean remainingRecords() {
return false;
}

/**
* Return true if this error handler performs seeks on the failed record and remaining
* records (or just the remaining records after a failed record is recovered).
* @return true if the next poll should fetch records.
*/
@SuppressWarnings("deprecation")
default boolean seeksAfterHandling() {
return remainingRecords();
}
```

**Comment by garyrussell** [comment]
Oh; sorry; yes, the default should have it turned off too.

**Comment by garyrussell** [comment]
However, the logging handler handles (logs) the error, so there should be no pause at all; so that is a bug too.

**Comment by garyrussell** [comment]
However, the logging handler handles (logs) the error, so there should be no pause at all; so that is a bug too if that is indeed what's happening.

It shouldn't happen though because the `handled` boolean is true if the handler doesn't throw an exception.

**Comment by garyrussell** [comment]
The bug is here:

https://github.com/spring-projects/spring-kafka/blob/0cad2d7bce14227c37b84f61ea0b505ef20cf12d/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2921-L2933

The while loop should be with the `if (!handled)` test.

Thanks for reporting.

**Comment by antonin-arquey** [comment]
Thank you for the quick fix and for your work on the project !

**Comment by eamon-sun** [comment]
After GH-2596, it seems that when using nack, the sleep time is no longer pollTimeout, but pollTimeoutWhilePaused? 

<img width="1127" height="102" alt="Image" src="https://github.com/user-attachments/assets/661e4324-35b4-4570-a1aa-bcf6c599a545" />

But I actually tested and found that it seems to still be pollTimeout, and it is also written in the comment.

<img width="1078" height="351" alt="Image" src="https://github.com/user-attachments/assets/0bef46b7-b3d6-4453-ab18-f1bd9ee82194" />
I am using 2.9.13, can someone please answer this question?
