### ISSUE TITLE
JsonDeserializer unable to deserialize Java8 objects

### ISSUE THREAD

**Issue by yihfenglow** [spring-projects/spring-kafka#260]
Hello!

I'm not sure if this is a bug, but from what I can tell by reading the JsonDeserializer class, there is no way to add modules (for e.g. JSR310) to the ObjectMapper so that it can deserialize Java 8 classes such as LocalDateTime. 

Reference: https://blog.oio.de/2015/06/13/add-support-for-java-8-date-time-api-to-jackson-serialized-rest-web-services/

**Comment by garyrussell** [comment]
There is a second constructor, where you can inject a customized `ObjectMapper` ...

    public JsonDeserializer(Class<T> targetType, ObjectMapper objectMapper) { ... }

**Comment by yihfenglow** [comment]
Ah of course. I can't believe I missed that. Thanks!
