### ISSUE TITLE
Spring Messaging batch payload incompatible with Kotlin

### ISSUE THREAD

**Issue by samyempcc** [spring-projects/spring-kafka#2600]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
3.0.2

**Describe the bug**
Cross posting from Spring Messaging as suggested in https://github.com/spring-projects/spring-framework/issues/29963. Kotlin based batch listener does not receive the expected Message payload.

In: https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java#L682

with Kotlin the paramType resolves to:
` ? extends org.springframework.messaging.Message<?>`

while for java, it is:
`org.springframework.messaging.Message<?>`

The rest of the code flow in that method ends up assigning the payload content based on the test for paramType and ends up behaving differently for kotlin.

**To Reproduce**

Running the sample project, it is noticed that in the java.util.List based listener, a GenericMessage is passed to the listener with both header and payload. In Kotlin's List based listener, only the message payload is passed as Message.

**Expected behavior**

Kotlin listener is expected to be identical to Java.

**Sample**
I have a working code to reproduce the issue given a local kafka running on port 9092:
https://github.com/samyem/spring-messaging-issue29963/blob/master/src/main/kotlin/com/example/issue29963/service/BatchTest.kt#L35

**Comment by garyrussell** [comment]
Confirmed; same thing happens with Java and

```java
@KafkaListener(id = "kgh2600", topics = "kgh2600", batch = "true")
void listen(List<? extends Message<?>> in) {
	System.out.println(in);
}
```

Thanks for reporting.
