### ISSUE TITLE
@KafkaListener listener skipped when multiple declared

### ISSUE THREAD

**Issue by sokie** [spring-projects/spring-kafka#261]
If we have multiple @KafkaListener declared for different topics, only the first one declared gets used and the other are skipped. For example in the same class if i have:
```
@KafkaListener(id = "id1", topics = "topic1")
public void receive(byte[] payload) {
}

@KafkaListener(id = "id2", topics = "topic2")
public void receive(byte[] payload) {
}
```
I don't receive any messages on topic2.

**Comment by artembilan** [comment]
Well, there is something wrong in your config. 
The project has `EnableKafkaIntegrationTests` especially for this `@KafkaListener` use-case. 
And there you can find the listener class definition: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java#L611 with many-may `@KafkaListener` methods in the same class.

Since our tests are passing, that mean that multi `@KafkaListener` methods work well.

Please, share some simple Spring Boot application to play from our side if you still think that proposed functionality doesn't work.

**Comment by garyrussell** [comment]
DEBUG logging should help you figure out what the problem is too.

**Comment by sokie** [comment]
I see
`2017-03-30 16:07:59.139  INFO 27985 --- [        execC-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned:[topic1-0]`
And listener receives no messages on topic2
If I do:
```
@KafkaListener(id = "id1", topics = {"topic1","topic2"})
public void receive(byte[] payload, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
}
```
I see
`2017-03-30 16:07:59.139  INFO 27985 --- [        execC-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned:[topic1-0,topic2-0]`
And can receive messages on both topics.

**Comment by garyrussell** [comment]
Please show the rest of your configuration, including the `execC` task executor bean - does it have more than one thread?

**Comment by sokie** [comment]
this is my full kafka configuration
```java
@Configuration
@EnableKafka
public class KafkaConfig {

    @Bean
    KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<Integer, String>>
    kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
                new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(15);
        factory.getContainerProperties().setConsumerTaskExecutor(execC());
        factory.getContainerProperties().setListenerTaskExecutor(execL());
        factory.getContainerProperties().setPollTimeout(3000);
        return factory;
    }

    @Bean
    public AsyncListenableTaskExecutor execC() {
        ThreadPoolTaskExecutor tpte = new ThreadPoolTaskExecutor();
        tpte.setCorePoolSize(3);
        return tpte;
    }

    @Bean
    public AsyncListenableTaskExecutor execL() {
        ThreadPoolTaskExecutor tpte = new ThreadPoolTaskExecutor();
        tpte.setCorePoolSize(3);
        return tpte;
    }

    @Bean
    public ConsumerFactory<Integer, String> consumerFactory() {
        return new DefaultKafkaConsumerFactory<>(consumerConfigs());
    }

    @Bean
    public Map<String, Object> consumerConfigs() {
        Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "kafka-host:9092");
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "group1");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, true);
        props.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, 100);
        props.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, 15000);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, IntegerDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ByteArrayDeserializer.class);
        return props;
    }
}
```

**Comment by sokie** [comment]
Quick info:
If i comment out factory.setConcurrency(); multiple @ KafkaListener work properly, but they get assigned to 1 consumer obviously.

**Comment by garyrussell** [comment]
How can you have this

```
@KafkaListener(id = "id1", topics = "topic1")
public void receive(byte[] payload) {
}

@KafkaListener(id = "id2", topics = "topic2")
public void receive(byte[] payload) {
}
```

...in the same class? It won't compile (duplicate method names).

**Comment by sokie** [comment]
Sorry refactored for the issue purpose

**Comment by garyrussell** [comment]
Well if the concurrency is 15, you need 30 threads in the pools - 15 for each container.

If there's only one partition on the topic, only one thread will actually consume.

**Comment by garyrussell** [comment]
So the second container is starved for threads - that's why it didn't consume.

**Comment by sokie** [comment]
yes you are right!
it was the problem between 
setConcurrency() and the executors. Changing the pools assigns topics correctly!

**Comment by yeralin** [comment]
Also, not related to the conditions @sokie had. 

If you did not define any factories, `@KafkaEnable` annotations, and left it all up to the Spring, and you still can't instantiate two Kafka Listeners. Possible problem might be `spring-kafka` jar's version.

We found out that versions <=`1.2.0`, doesn't set `group` param properly causing only one listener to receive a message (i.e. `@KafkaListner(group = <str>)`). In newer version, the param is renamed to `groupId` and works as expected.

**Comment by garyrussell** [comment]
Actually, `group` was renamed to `containerGroup` (the property has no bearing on Kafka properties, it is a mechanism to "group" containers together so you can start/stop them as a group.

The `groupId` (maps to Kafka consumer `group.id` property was added in version 1.3, specifically to avoid having to create a different container factory for each listener.
