### ISSUE TITLE
Incorrect retry topic suffix

### ISSUE THREAD

**Issue by Desire456** [spring-projects/spring-kafka#2654]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.2

**Describe the bug**

Incorrect retry topic suffix (`retry-5000`) when attempts is equal to 2 in `@RetryableTopic` and `fixedDelayStrategy=SINGLE_TOPIC`

**To Reproduce**

```
@KafkaListener(
        id = "someId",
        topics = [GREETING_TOPIC],
        groupId = "groupId",
        autoStartup = "true"
    )
@RetryableTopic(
        backoff = Backoff(delay = 5000),
        attempts = "2",
        autoCreateTopics = "false",
        fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC
    )
```

**Expected behavior**

Retry topic suffix = `-retry`

**Comment by Desire456** [comment]
The problem is here:
https://github.com/spring-projects/spring-kafka/blob/f351a7a4aa85deb9c56c3f599d2eceac08e0f35f/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java#L272.
`this.backOffValues.size() > 1` 
Why > 1?
Is 1 attempt with fixed delay is not fixed delay according to this method? Or it's feature that I didn't realize?

**Comment by garyrussell** [comment]
Confirmed that this is a bug (when `attempts = "2"`) but, unfortunately, we can't change the default behavior in a patch release; we could make it an opt-in, in a future release.

As a work around, see https://docs.spring.io/spring-kafka/docs/current/reference/html/#custom-naming-strategies

Here's an example:

```java
@SpringBootApplication
public class Kgh2654Application extends RetryTopicConfigurationSupport {

	public static void main(String[] args) {
		SpringApplication.run(Kgh2654Application.class, args);
	}

	@Bean
	NewTopic topic() {
		return TopicBuilder.name("kgh2654").partitions(1).replicas(1).build();
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> {
			template.send("kgh2654", "foo");
		};
	}

	@Override
	protected RetryTopicComponentFactory createComponentFactory() {
		return new RetryTopicComponentFactory() {

			@Override
			public RetryTopicNamesProviderFactory retryTopicNamesProviderFactory() {
				return new CustomRetryTopicNamesProviderFactory();
			}

		};
	}

	@Bean
	TaskScheduler sched() {
		return new ThreadPoolTaskScheduler();
	}

}

@Component
class Listener {

	@RetryableTopic(attempts = "2", fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC)
	@KafkaListener(id = "kgh2654", topics = "kgh2654")
	void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
		throw new RuntimeException("test");
	}

	@DltHandler
	void handle(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
	}

}

class CustomRetryTopicNamesProviderFactory implements RetryTopicNamesProviderFactory {

	@Override
	public RetryTopicNamesProvider createRetryTopicNamesProvider(
			DestinationTopic.Properties properties) {

		if (properties.isMainEndpoint() || properties.isDltTopic()) {
			return new SuffixingRetryTopicNamesProvider(properties);
		}
		else {
			return new SuffixingRetryTopicNamesProvider(properties) {

				@Override
				public String getTopicName(String topic) {
					return topic + "-retry";
				}

			};
		}
	}

}
```

**Comment by iNviNho** [comment]
This is what worked for us in spring-kafka 2.8.8 👇 

First we created a **CustomRetryTopicNamesProviderFactory** that implements **RetryTopicNamesProviderFactory**

```java

import org.springframework.kafka.retrytopic.DestinationTopic;
import org.springframework.kafka.retrytopic.RetryTopicNamesProviderFactory;
import org.springframework.kafka.retrytopic.SuffixingRetryTopicNamesProviderFactory;

public class CustomRetryTopicNamesProviderFactory implements RetryTopicNamesProviderFactory {

  @Override
  public RetryTopicNamesProvider createRetryTopicNamesProvider(final DestinationTopic.Properties properties) {
    if (properties.isMainEndpoint() || properties.isDltTopic()) {
      return new SuffixingRetryTopicNamesProviderFactory.SuffixingRetryTopicNamesProvider(properties);
    } else {
      return new SuffixingRetryTopicNamesProviderFactory.SuffixingRetryTopicNamesProvider(properties) {
        @Override
        public String getTopicName(final String topic) {
          return topic + "-retry";
        }
      };
    }
  }
}
```

and then we created a bean for class **RetryTopicNamesProviderFactory** like this 

```java
package com.bitpanda.legaltenancy.infrastructure.kafka.factories;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.retrytopic.RetryTopicNamesProviderFactory;

@Configuration
public class RetryTopicComponentFactory {

  @Bean
  public RetryTopicNamesProviderFactory retryTopicNamesProviderFactory() {
    return new CustomRetryTopicNamesProviderFactory();
  }

}
```

Works like a charm 🥳

**Comment by garyrussell** [comment]
2.9.x and later require extending `RetryTopicConfigurationSupport` rather than just defining it as a bean, due to some bootstrapping problems.

**Comment by Wzy19930507** [comment]
Hi, @garyrussell 

Look like the correct scenario is
- when maxAttempts == 2 & SameIntervalTopicReuseStrategy.MULTIPLE_TOPICS | topic-main-retry-delay
- when maxAttempts == 2 & SameIntervalTopicReuseStrategy.SINGLE_TOPIC | topic-main-retry

maybe we can change code at `DestinationTopicPropertiesFactory`
https://github.com/spring-projects/spring-kafka/blob/9794c584f6093af76b6bb4e8ba672f1bbd8fefe2/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java#L130-L132
```
	private boolean isSingleTopicFixedDelay() {
		return this.backOffValues.size() == 1 && isFixedDelay() && isSingleTopicSameIntervalTopicReuseStrategy();
	}
```
https://github.com/spring-projects/spring-kafka/blob/9794c584f6093af76b6bb4e8ba672f1bbd8fefe2/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java#L222-L225
```
	private boolean isDelayWithReusedTopic(Long backoffValue) {
                // `hasDuplicates(backoffValue)` contains `isFixedDelay()`
		return hasDuplicates(backoffValue) && isSingleTopicSameIntervalTopicReuseStrategy();
	}
```

---

and add Integration testing case of generating TopicSuffix via @RetryableTopic like

**Comment by Wzy19930507** [comment]
add Integration testing case for generating topicSuffix via @RetryableTopic
- **delay** maxAttempts == 2 and SameIntervalTopicReuseStrategy.MULTIPLE_TOPICS --> topic-main-retry-{delay}
- **singleFixed** maxAttempts >= 2 and SameIntervalTopicReuseStrategy.SINGLE_TOPIC --> topic-main-retry
- **fixed** when maxAttempts > 3 and same delay | **indexStrategy** --> topic-main-retry-{index}
- **muliti duplicate delay** when maxAttempts > 3 and duplicates delay topic and SameIntervalTopicReuseStrategy.MULTIPLE_TOPICS --> topic-main-retry-{delay}-{duplicatesIndex}
- **single duplicate delay** when maxAttempts > 3 and duplicates delay topic and SameIntervalTopicReuseStrategy.SINGLE_TOPIC --> topic-main-retry-{delay}
