### ISSUE TITLE
Issues with @Transactional annotation behavior in more than one template

### ISSUE THREAD

**Issue by kdhyo** [spring-projects/spring-kafka#2655]
**In which version(s) of Spring for Apache Kafka does this problem occur?

For example:

Between 2.8.4 and 3.0.5

**Describe the bug**

I have 2 producers with different values.
They both set the transactionIdPrefix and the
When using the @Transactional annotation, the following error occurs.

> No transaction is in process; possible solutions: run the template operation within the scope of a template.executeInTransaction() operation, start a transaction with @Transactional before invoking the template method, run in a transaction started by a listener container when consuming a record

As the error explains, I could use executeInTransaction, but is there any way to use the annotation?

**Reproduce**

Steps to reproduce the behavior.

**Expected Behavior**

I want the Kafka transaction to commit first, then the database transaction.  
(I get the same error when it's the other way around).

**Example**

https://github.com/kdhyo/kafka-example

**Comment by artembilan** [comment]
The relevant SO thread: https://stackoverflow.com/questions/75956142/error-when-declaring-more-than-one-kafkatransactionmanager.

It is not clear how to run your sample and reproduce.
Also would be great to see the whole stack trace.

You can turn on `TRACE` logging level for the `org.springframework.transaction.interceptor` to see how your transactions are handled.

Only guess I see that you many try to make your `UpdatedMemberProducer` and `CreatedMemberProducer` as a `@Service` instead of `@Configuration`: I'm not sure that framework can see those `@Transactional` on methods in the `@Configuration` classes...

**Comment by garyrussell** [comment]
Your example is much too complicated for us to run, strip it down to the bare minimum:

https://stackoverflow.com/help/minimal-reproducible-example

This works fine for me...

```java
@SpringBootApplication
public class Kgh2655Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh2655Application.class, args);
	}

	@Bean
	ProducerFactory<String, String> pf1(KafkaProperties props) {
		Map<String, Object> pProps = props.buildProducerProperties();
		pProps.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG, "tx1-");
		return new DefaultKafkaProducerFactory<>(pProps);
	}

	@Bean
	ProducerFactory<String, String> pf2(KafkaProperties props) {
		Map<String, Object> pProps = props.buildProducerProperties();
		pProps.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG, "tx2-");
		return new DefaultKafkaProducerFactory<>(pProps);
	}

	@Bean
	KafkaTemplate<String, String> template1(ProducerFactory<String, String> pf1) {
		return new KafkaTemplate<>(pf1);
	}

	@Bean
	KafkaTemplate<String, String> template2(ProducerFactory<String, String> pf2) {
		return new KafkaTemplate<>(pf2);
	}

	@Bean
	KafkaTransactionManager<String, String> tm1(ProducerFactory<String, String> pf1) {
		return new KafkaTransactionManager<>(pf1);
	}

	@Bean
	KafkaTransactionManager<String, String> tm2(ProducerFactory<String, String> pf2) {
		return new KafkaTransactionManager<>(pf2);
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<String, String> template1, KafkaTemplate<String, String> template2,
			Foo foo) {

		return args -> {
			foo.one(template1);
			foo.two(template2);
			foo.one(template1);
			foo.two(template2);
		};
	}

	@Bean
	NewTopic topic() {
		return TopicBuilder.name("topic").partitions(1).replicas(1).build();
	}

	@KafkaListener(id = "kgh2655", topics = "topic")
	void listen(String in, @Header(KafkaHeaders.OFFSET) long off) {
		System.out.println(in + "-@" + off);
	}

}

@Component
class Foo {

	@Transactional(transactionManager = "tm1")
	void one(KafkaTemplate<String, String> template) {
		template.send("topic", "foo");
	}

	@Transactional(transactionManager = "tm2")
	void two(KafkaTemplate<String, String> template) {
		template.send("topic", "foo");
	}

}
```
```properties
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.isolation-level=read-committed
```
```

[Producer clientId=producer-tx2-0, transactionalId=tx2-0] Instantiated a transactional producer.
[Producer clientId=producer-tx1-0, transactionalId=tx1-0] Instantiated a transactional producer.
foo-@28
foo-@30
foo-@32
foo-@34
```

**Comment by kdhyo** [comment]
Oh, I apologize for the difficulty of the example.
However, I looked at your code and found the cause.
I registered the ProducerFactory as a bean and used it, and that solved it.

I think I didn't find it because I created it in transaction manager and template respectively.
Thanks for the kind example.
