### ISSUE TITLE
User Spring-Kafka kafkaTemplate send message failure with IllegalMonitorStateException

### ISSUE THREAD

**Issue by xzhan** [spring-projects/spring-kafka#2697]
**our Prod env:**
1.openjdk-17.0.2-5.el7.x86_64
2.Spring-kafka :2.8.11
3. Kafka client: 3.1.2
4. 

**Java Stack:**

java.lang.IllegalMonitorStateException: current thread is not owner
	at java.lang.Object.wait(Native Method) ~[?:?]
	at org.apache.kafka.common.utils.SystemTime.waitObject(SystemTime.java:55) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerMetadata.awaitUpdate(ProducerMetadata.java:119) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.waitOnMetadata(KafkaProducer.java:1088) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:935) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:914) ~[kafka-clients-3.1.2.jar:?]
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:1087) ~[spring-kafka-2.8.11.jar:2.8.11]
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:655) ~[spring-kafka-2.8.11.jar:2.8.11]
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:429) ~[spring-kafka-2.8.11.jar:2.8.11]

@garyrussell  @artembilan  have you receive this kind of issue reported?

**Comment by garyrussell** [comment]
2.8.x is no longer supported as OSS - https://spring.io/projects/spring-kafka#support

In any case, this code is entirely within the kafka-clients library and is not part of Spring; you should raise issues against that library using the Kafka JIRA.

However, it is not at all clear how that error can occur; the code is

```java
    @Override
    public void waitObject(Object obj, Supplier<Boolean> condition, long deadlineMs) throws InterruptedException {
        synchronized (obj) {
            while (true) {
                if (condition.get())
                    return;

                long currentTimeMs = milliseconds();
                if (currentTimeMs >= deadlineMs)
                    throw new TimeoutException("Condition not satisfied before deadline");

                obj.wait(deadlineMs - currentTimeMs);
            }
        }
    }
```

Where `obj` is the `ProducerMetadata` instance...

```java
    /**
     * Wait for metadata update until the current version is larger than the last version we know of
     */
    public synchronized void awaitUpdate(final int lastVersion, final long timeoutMs) throws InterruptedException {
        long currentTimeMs = time.milliseconds();
        long deadlineMs = currentTimeMs + timeoutMs < 0 ? Long.MAX_VALUE : currentTimeMs + timeoutMs;
        time.waitObject(this, () -> {
            // Throw fatal exceptions, if there are any. Recoverable topic errors will be handled by the caller.
            maybeThrowFatalException();
            return updateVersion() > lastVersion || isClosed();
        }, deadlineMs);

        if (isClosed())
            throw new KafkaException("Requested metadata update after close");
    }
```

...and the thread is clearly synchronized on `obj` when it calls `obj.wait()` on line 55.

**Comment by xzhan** [comment]
> 2.8.x is no longer supported as OSS - https://spring.io/projects/spring-kafka#support
> 
> In any case, this code is entirely within the kafka-clients library and is not part of Spring; you should raise issues against that library using the Kafka JIRA.
> 
> However, it is not at all clear how that error can occur; the code is
> 
> ```java
>     @Override
>     public void waitObject(Object obj, Supplier<Boolean> condition, long deadlineMs) throws InterruptedException {
>         synchronized (obj) {
>             while (true) {
>                 if (condition.get())
>                     return;
> 
>                 long currentTimeMs = milliseconds();
>                 if (currentTimeMs >= deadlineMs)
>                     throw new TimeoutException("Condition not satisfied before deadline");
> 
>                 obj.wait(deadlineMs - currentTimeMs);
>             }
>         }
>     }
> ```
> 
> Where `obj` is the `ProducerMetadata` instance...
> 
> ```java
>     /**
>      * Wait for metadata update until the current version is larger than the last version we know of
>      */
>     public synchronized void awaitUpdate(final int lastVersion, final long timeoutMs) throws InterruptedException {
>         long currentTimeMs = time.milliseconds();
>         long deadlineMs = currentTimeMs + timeoutMs < 0 ? Long.MAX_VALUE : currentTimeMs + timeoutMs;
>         time.waitObject(this, () -> {
>             // Throw fatal exceptions, if there are any. Recoverable topic errors will be handled by the caller.
>             maybeThrowFatalException();
>             return updateVersion() > lastVersion || isClosed();
>         }, deadlineMs);
> 
>         if (isClosed())
>             throw new KafkaException("Requested metadata update after close");
>     }
> ```
> 
> ...and the thread is clearly synchronized on `obj` when it calls `obj.wait()` on line 55.

Yes , it looks like pure kafka client error , Let me raise issue to kafka team

**Comment by xzhan** [comment]
@garyrussell  you can  check the jira which have been reported https://issues.apache.org/jira/browse/KAFKA-10902

it no any response on the issue
