### ISSUE TITLE
Two different KafkaListeners consuming the same queue cannot be paused

### ISSUE THREAD

**Issue by jorgecollado** [spring-projects/spring-kafka#2708]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.7

**Describe the bug**

Given two different KafkaListeners with the same group ID and topic and running at the same time, try to pause both of them by using `MessageListenerContainer.pause()`. The `MessageListenerContainer.isContainerPaused` method does not work as expected (always for the second listener we tried to pause). This method returns `false` even though debugging the library code, the private flag `pause` contains `true` and the KafkaListener is actually paused.

<img width="1227" alt="image" src="https://github.com/spring-projects/spring-kafka/assets/3826373/8e9573b0-a68e-4426-bc70-f4e1b06c5847">

This makes the `MessageListenerContainer.resume()` not work. Somehow this method thinks the KafkaListener is running and do not try to resume it.

**To Reproduce**

- Given two KafkaListeners with `autoStartup=false`
- Listen to `ApplicationStartedEvent` event and try to start and pause them when the event is caught by calling:
    - `MessageListenerContainer.start()`
    - `MessageListenerContainer.pause()`

**Expected behavior**

Given two different KafkaListeners with the same group ID and topic and running at the same time, try to pause both of them by using `MessageListenerContainer.pause()`. Then, the `MessageListenerContainer.isContainerPaused` method should return `true` after the current poll.

**Sample**

https://github.com/jorgecollado/spring-kafka-multiple-listeners

Partner in crime @mariotrucco

**Comment by garyrussell** [comment]
Well technically, the container is not paused, it is in pause requested state; that variable (at the abstract container level) is set when pause is requested.

(isPauseRequested()` returns the same property).

However, for the concurrent listener container, we examine each child container and if any of the children are not paused, it returns false.

https://github.com/spring-projects/spring-kafka/blob/bbefd04f953680c6346575cbf51fdcc6690a1968/spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java#L169-L181

If a rebalance occurs, the `pauseRequested` state is still true so after the partition is assigned, it will immediately pause.

**Comment by jorgecollado** [comment]
Ok! Got it! Then, I will close the issue. Thanks for your quick answer @garyrussell, I really appreciate it 😃
