### ISSUE TITLE
Should nested transactions synchronize with Spring Kafka?

### ISSUE THREAD

**Issue by khaeghar** [spring-projects/spring-kafka#2715]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.11

**Describe the bug**

Following the documentation about Spring for Apache Kafka, I've tried the examples at https://docs.spring.io/spring-kafka/reference/html/#ex-jdbc-sync

The first example that says:

> For producer-only transactions, transaction synchronization works:

```
@Transactional("dstm")
public void someMethod(String in) {
    this.kafkaTemplate.send("topic2", in.toUpperCase());
    this.jdbcTemplate.execute("insert into mytable (data) values ('" + in + "')");
}
```

Works as intended and it synchronizes both database and kafka, rolling back the kafka operation in case the database fails to commit.

But the other example, that says:

> If you wish to commit the Kafka transaction first, and only commit the DB transaction if the Kafka transaction is successful, use nested @Transactional methods:

```
@Transactional("dstm")
public void someMethod(String in) {
    this.jdbcTemplate.execute("insert into mytable (data) values ('" + in + "')");
    sendToKafka(in);
}

@Transactional("kafkaTransactionManager")
public void sendToKafka(String in) {
    this.kafkaTemplate.send("topic2", in.toUpperCase());
}
```

Doesn't synchronize the kafka and the database at the end of the first transaction, but instead it sends the kafka message after the return of the sendToKafka method, and then it executes the rest of the code that the someMethod could have, meaning there's no real synchronization (meaning that the commits are not grouped together and made one after the other without logic in between)

So either the second sample should synchronize, in which case it does not, or it shouldn't synchronize and works as expected, in which case I think it would be nice maybe to specify that there's no such synchronization in that case (and that makes me wonder how we could achieve such synchronization where the kafka commits first and then the database commits after).

To reproduce this I simply created a Spring project with a hsql database and the kafka dependencies and replicated the sample provided in the doc page: https://docs.spring.io/spring-kafka/reference/html/#ex-jdbc-sync

**Comment by garyrussell** [comment]
This works as designed; just don't do anything after the send.

Alternatively, you could use the `ChainedKafkaTransactionManager`; it is deprecated because it's super class was deprecated by the Spring Data team.

See the `ChainedTransactionManager` javadocs for their suggestions on how to register a synchronization if you wish to more tightly synchronize the transactions.
