### ISSUE TITLE
AckCount is invalid when ackMode is Count and ackCount is less than maxPollRecords 

### ISSUE THREAD

**Issue by wapkch** [spring-projects/spring-kafka#2731]
**Expected Behavior**

Assume we have following settings:

application.properties
```css
spring.kafka.listener.ack-mode=count
spring.kafka.listener.ack-count=100
logging.level.org.springframework.kafka=debug
```

Expect to commit offset every 100 messages processed

SpringBoot Application:
```java
@RestController
@SpringBootApplication
public class SpringKafkaDemo2Application {

    public static void main(String[] args) {
        SpringApplication.run(SpringKafkaDemo2Application.class, args);
    }

    @KafkaListener(id = "fooGroup", topics = "topic")
    public void listen(ConsumerRecord<String, String> record) throws Exception {
    }

    @Autowired
    private KafkaTemplate<Object, Object> template;

    @PostMapping(path = "/send/{what}")
    public void sendFoo(@PathVariable String what) {
        for (int i = 0; i < 500; i++) {
            this.template.send("topic", "message" + i);
        }
    }

}
```

**Current Behavior**

Committing the offset every time after 500 records processed:
```css
2023-07-06T18:07:36.680+08:00 DEBUG 26195 --- [ fooGroup-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : Committing in COUNT because count 500 exceeds configured limit of 100
2023-07-06T18:07:36.680+08:00 DEBUG 26195 --- [ fooGroup-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : Commit list: {topic-0=OffsetAndMetadata{offset=560, leaderEpoch=null, metadata=''}}
2023-07-06T18:07:36.680+08:00 DEBUG 26195 --- [ fooGroup-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : Committing: {topic-0=OffsetAndMetadata{offset=560, leaderEpoch=null, metadata=''}}
```

**Context**
Although the larger the ackCount, the better the performance, but it will increase the chance of retransmission, so sometimes it is useful for the ackCount to be smaller than maxPollRecords

**Comment by garyrussell** [comment]
We currently only consider count and time ack modes just before the next poll.

It's probably not a big change; I'll put it on the backlog.

Contributions are welcome.

**Comment by Dharmik2510** [comment]
I am using spring Kafka 2.X and now want to migrate to 3.0

Currently:

I have a listener container factory setup for retry functionality only, where I am setting up recovery like below:

@Bean
public ConcurrentKafkaListenerContainerFactory<?, ?> retryConcurrentKafkaListenerContainerFactory() {
    ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory());

    // Configure the RetryTemplate
    RetryTemplate retryTemplate = new RetryTemplate();
    // Configure your retry policy, backoff policy, and any other necessary options
    // retryTemplate.setRetryPolicy(...);
    // retryTemplate.setBackOffPolicy(...);

  
    RetryOperationsInterceptor interceptor = new RetryOperationsInterceptor();
    interceptor.setRetryOperations(retryTemplate);
    factory.setRetryTemplate(retryTemplate);

    
    RecoveryCallback<Object> recoveryCallback = context -> {
        

        ConsumerRecord<?, ?> record = (ConsumerRecord<?, ?>)        context.getAttribute(RetryingMessageListenerAdapter.CONTEXT_RECORD);
        System.out.println("Recovery callback invoked for record: " + record.value());


     


    Acknowledgment acknowledgment = (Acknowledgment)              context.getAttribute(RetryingMessageListenerAdapter.CONTEXT_ACKNOWLEDGMENT);
        
        System.out.println("Recovery callback invoked for record: " + record.value());
        
        
        if (acknowledgment != null) {
            // Manually acknowledge the record
            acknowledgment.acknowledge();
        }


        return null; 
    };
    factory.setRecoveryCallback(recoveryCallback);

    // Other configuration options for the factory
    return factory;
}

Now using Kafka spring version 3.0 how can I achieve the same thing?

**Comment by artembilan** [comment]
@Dharmik2510 ,

your comment has nothing to do with an issue.
More over you already have raised an SO question: https://stackoverflow.com/questions/76664557/spring-kafka-recoverycallback-migration.

Please, consider to remove it from here to not confuse community.

**Comment by hscom96** [comment]
@garyrussell Can i solve this issue?

**Comment by garyrussell** [comment]
Yes, please go ahead. Please read the contribution guidelines.

**Comment by Wzy19930507** [comment]
@hscom96 @garyrussell can I pick this up ?

**Comment by garyrussell** [comment]
Yes, please do.
