### ISSUE TITLE
Extra bytes in headers of kafka in case data is compressed

### ISSUE THREAD

**Issue by bdivya07** [spring-projects/spring-kafka#2732]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.7

**Describe the bug**

I created a spring Kafka consumer using @KafkaListener.
During this, I encounter a scenario where when data is compressed ( any compression snappy/gzip) and consumed by the consumer then I see that in a heap dump, there is a " byte" occupying the same amount of memory as in value. 

This behavior is seen only in cases when compressed data is consumed by consumers not in the case of uncompressed data.

Tried to capture Kafka's message through wireshark, there it shows the proper size of data nothing wrong with the headers.

Attached is the screenshot of the heap dump and Wireshark.

<img width="893" alt="java heap dump" src="https://github.com/spring-projects/spring-kafka/assets/69679797/289857d1-1654-4d80-a320-f3659f75f694">
<img width="500" alt="wireshark" src="https://github.com/spring-projects/spring-kafka/assets/69679797/567d86b5-a14d-4127-93bb-b590ce1acfad">

Somewhere it feels like the actual message value is copied to headers?

**To Reproduce**

1. Produce compressed data on any topic.
2. Create a simple consumer consuming from the above-created topic.
3. Capture heap dump.

**Expected behavior**

Headers should not show bytes consuming memory equivalent to value.

**Comment by artembilan** [comment]
I think this question is more up to Apache Kafka client by itself: Spring doesn't do any actions about compression.
The whole functionality is done internally in the Kafka client library.

**Comment by bdivya07** [comment]
Thank you. We have raised it with apache kafka.
https://issues.apache.org/jira/browse/KAFKA-15160

**Comment by artembilan** [comment]
Closed in favor of mentioned Apache Kafka Jira ticket.
