### ISSUE TITLE
Fix Invalid Warning Log When With Non-Blocking Retries

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2784]
`Foreign deserialization exception header in (kgh2496-retry-2000-0-0@33) ignored; possible attack?`

**Comment by garyrussell** [comment]
Work around:

`logging.level.org.springframework.kafka.retrytopic.DeadLetterPublishingRecovererFactory=error`

**Comment by jucosorin** [comment]
I got this exception today after upgrading to boot 3.2.0-M2 and took me a while to figure out what it was. I wanted to submit a patch, but you already fixed it! :)

**Comment by garyrussell** [comment]
@jucosorin - fixed in 3.0.11 (and 2.9.12) which are available in Maven Central now.

See https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps for how to override Boot's prescribed version.

**Comment by jucosorin** [comment]
Thank you @garyrussell for all your amazing work!
