### ISSUE TITLE
Add ConsumerAwareMessageListener

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#280]
Allow the user to pause/resume the consumer (and interact with it - e.g. commit rather than using an `AcknowledgingMessageListener`.

We would have to invoke the listener with null `ConsumerRecord` to enable resuming a paused consumer.

**Comment by consulthys** [comment]
Cool! Will this be backported to the 1.2 branch?

**Comment by garyrussell** [comment]
No; this is a 2.0 feature; the first milestone for 2.0 (M1) is scheduled to be released later this week. It requires previous commits that rework in the threading model now that the client code handles heartbeats differently.
