### ISSUE TITLE
Kafka producer send huge data occurs memory leak with spring-kafka 3.1.2

### ISSUE THREAD

**Issue by anranziruo** [spring-projects/spring-kafka#2803]
spring kafka client version 3.1.2
java version:1.10
kafka producer config:
```
compression-type: snappy
properties.put("key.serializer", StringSerializer.class);
properties.put("value.serializer", StringSerializer.class);
properties.put("enable.idempotence", false);
properties.put("retries", 3);
properties.put(ProducerConfig.ACKS_CONFIG, "1");
properties.put(ProducerConfig.BATCH_SIZE_CONFIG, 16384*2);
```
when we use MAT tools to analyse  dump info ,we find some info :
![image](https://github.com/spring-projects/spring-kafka/assets/10794211/a0ed7e99-adc2-4988-8c8e-1f56f60a2153)
 
![image](https://github.com/spring-projects/spring-kafka/assets/10794211/1ab86d35-e30c-4699-b7e5-c4a07556f93f)

java cmd ：
```
java -Xms4G -Xmx4G -jar dataapp-datadispatch-0.1.jar --server.port=9006 --spring.profiles.active=prod
```

**Comment by garyrussell** [comment]
Well, clearly, this is something entirely internal to the Apache `kafka-clients` library; you should raise your concerns over there. But, I am sure they will require much more information than you have provided here; sample code to reproduce, etc.

**Comment by anranziruo** [comment]
> Well, clearly, this is something entirely internal to the Apache `kafka-clients` library; you should raise your concerns over there. But, I am sure they will require much more information than you have provided here; sample code to reproduce, etc.
our code is simple
```
 private final KafkaTemplate<String, String> kafkaTemplate;

    @Autowired
    public KafkaProducerService(KafkaTemplate<String, String> kafkaTemplate){
        this.kafkaTemplate = kafkaTemplate;
    }

    public void send(String topic,String key, String message) {
        var future = kafkaTemplate.send(topic, key, message);
        future.addCallback(success -> {
            //
        }, fail -> {
            log.error("KafkaMessageProducer send msg error ！topic: {}, key: {}, value: {},err：{}", topic, key, message,
                    fail.getMessage());
        });
    }
```
when send msg is huge,java process memory slow growth

**Comment by garyrussell** [comment]
Right, but all the `KafkaTemplate` does is delegate to `KafkaProducer.send()`; so this has nothing to do with Spring.

If you can prove that the same problem does not occur when using the native client, we will take a look.

**Comment by anranziruo** [comment]
> Right, but all the `KafkaTemplate` does is delegate to `KafkaProducer.send()`; so this has nothing to do with Spring.
> 
> If you can prove that the same problem does not occur when using the native client, we will take a look.

fine,when a few data kafka producer sends ,memory is ok ,but when huge data is be send,java process occur memory leak,i suspect batch.size,i config batch.size is 32k
