### ISSUE TITLE
@KakfaListener is not detected if listener bean is spied

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-kafka#2807]
see https://github.com/spring-projects/spring-boot/issues/37376#issuecomment-1719043722

**Comment by garyrussell** [comment]
The listener is detected just fine; the problem is the send is performed before the listener has started consuming and the default auto offset reset is `latest` so it doesn't get already published records.

This works fine...
```java
@SpringBootTest(properties = { "logging.level.org.springframework.kafka=debug",
		"spring.kafka.consumer.auto-offset-reset=earliest"})
```

**Comment by garyrussell** [comment]
However, I would suggest a more robust mechanism than `Thread.sleep()`, such as:

```java
	@Test
	void test() throws Exception {
		this.kafkaTemplate.send(TEST_TOPIC_NAME, "test");
		CountDownLatch latch = new CountDownLatch(1);
		willAnswer(inv -> {
			inv.callRealMethod();
			latch.countDown();
			return null;
		}).given(this.testListener).receive(any());
		assertThat(latch.await(10, TimeUnit.SECONDS)).isTrue();
		then(testListener).should().receive("test");
		assertThat(testListener.latestMessage).isEqualTo("test");
	}
```

**Comment by quaff** [comment]
Thanks very much, It works fine with `spring.kafka.consumer.auto-offset-reset=earliest`, could you explain why the behavior changed after spied?

**Comment by garyrussell** [comment]
It is not a behavior change; people make this mistake all the time, even without spying:

https://stackoverflow.com/questions/50123621/testing-a-kafkalistener-using-spring-embedded-kafka/50123955#50123955

If it worked for you without the spy, you just got lucky; it's all about timing.

>I  assume `spring-kafka` will ensure all @KafkaListener be started 

The containers are indeed started, but getting the consumer fully functional is asynchronous and takes a lot of time, with negotiation with the broker, partition assignment, etc. It would be impractical to wait for all that to happen, especially if you have a lot of listeners. And, this is generally only an issue with test cases.

There are a couple of other solutions; we provide `ContainerTestUtils.waitForAssignment()` that can be used in tests; you can also add a rebalance listener and wait until the partitions are assigned before sending the test message.

But, the simplest solution is to set `auto-offset-reset=earliest`.

**Comment by quaff** [comment]
Thanks for elaboration.
