### ISSUE TITLE
Snappy version upgrade

### ISSUE THREAD

**Issue by pranavakkian-dev** [spring-projects/spring-kafka#2808]
**Expected Behavior**

The snappy version should be 1.1.10 and above.

**Current Behavior**

The snappy version is 1.1.8.4

org.xerial.snappy:snappy-java:jar:1.1.8.4:runtime

**Context**
This version contains a vulnerability that is failing our security checks.

**Comment by garyrussell** [comment]
Snappy is a transitive dependency of `kafka-clients`; its version is not determined by Spring.

If you are using a supported version of Spring for Apache Kafka (2.9.x or 3.0.x), you can override the `kafka-clients` version to 3.5.1, which brings in snappy 1.1.10.1.

Simply add `<kafka.version>3.5.1</kafka.version>` to your POM.

See https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps


<img width="226" alt="Screenshot 2023-09-14 at 8 20 07 AM" src="https://github.com/spring-projects/spring-kafka/assets/483832/ad5c75e9-6407-4736-b2e6-52251d4d37d4">


<img width="268" alt="Screenshot 2023-09-14 at 8 17 44 AM" src="https://github.com/spring-projects/spring-kafka/assets/483832/c8d1f786-128b-452e-8b38-906f50d9898c">

The next release (3.1.0) will use the 3.5.1 clients (or later if available when it is released).
