### ISSUE TITLE
Offset commit by spring-kafka causes custom `onPartitionRevoked` not to be called in manual ack mode

### ISSUE THREAD

**Issue by magicyuli** [spring-projects/spring-kafka#283]
When a rebalance is in process, and the `ConsumerRebalanceListener` defined in the `ListenerConsumer` tries to commit offsets for manual acks in `onPartitionRevoked`, the commit could result in `CommitFailedException` because a rebalance is in process, which in turn causes our own `onPartitionRevoked` not to be called. Could spring-kafka catch that exception and always call the custom callback?

Seems this also can cause 
`ListenerConsumer.this.recordsToProcess.clear();`
`ListenerConsumer.this.unsent = null;`
to not be called, which causes the listener to process data points from partitions don't belong to it anymore.

**Comment by garyrussell** [comment]
It shouldn't fail in `onPartitionRevoked` since you are allowed to commit there.

In any case, I believe this should be fixed in 1.1.4 and 1.2.0 by #269.

**Comment by garyrussell** [comment]
Closed due to lack of response; please reopen if this is still an issue for you.
