### ISSUE TITLE
How to suppress Deserialization exception using DeadLetterPublishingRecoverer, commit offset so that we can move ahead for other records 

### ISSUE THREAD

**Issue by sgump899** [spring-projects/spring-kafka#2842]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

2.8.2

Between 2.7.0 and 2.8.2

**Describe the bug**

Do not create an issue to ask a question; see below.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible,  sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by garyrussell** [comment]
See the documentation: https://docs.spring.io/spring-kafka/docs/current/reference/html/#error-handling-deserializer

>When a deserializer fails to deserialize a message, Spring has no way to handle the problem, because it occurs before the poll() returns. To solve this problem, the `ErrorHandlingDeserializer` has been introduced. ...
