### ISSUE TITLE
Provide a way to customize a transactionIdSuffix

### ISSUE THREAD

**Issue by stillya** [spring-projects/spring-kafka#2852]
**Expected Behavior**

Provide strategy to customize a `transactionIdSuffix`.

**Current Behavior**

Currently, spring-kafka use [AtomicInteger](https://github.com/spring-projects/spring-kafka/blob/61bc2190eb592515e95d322f6d16b359cb5134d0/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L124) for transactionIdSuffix.

**Context**

In my environment, I work with restricted `transactionId` within a specific range(e.g. **topic-{1-5}**).
Currently, spring-kafka use [AtomicInteger](https://github.com/spring-projects/spring-kafka/blob/61bc2190eb592515e95d322f6d16b359cb5134d0/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L124) for `transactionIdSuffix`, it would be beneficial to have the flexibility to implement a custom strategy for `transactionIdSuffix`.
This could involve actions such as resetting the counter after reaching a limit or a storage for managing `transactionsIds`.

I'm happy to contribute a PR once I know what your opinion on this feature is.

**Comment by garyrussell** [comment]
This makes sense, although you can't reset it if there is still a producer with that prefix; the reset would have to eject the existing producer from the cache.

A PR would certainly be welcome; thanks!

**Comment by Wzy19930507** [comment]
> Restricted transactionId within a specific range(e.g. topic-{1-5})

if all transactionId are in tx, `DefaultKafkaProducerFactory.createTransactionalProducer`'s behavior needs to change.
such as return null, wait some time or threw exception.

Is it reasonable to implement a transaction connection pool?

**Comment by stillya** [comment]
> Is it reasonable to implement a transaction connection pool?

I don't think it's feasible because a transaction is a shared resource among many instances rather than a cross-one, so we can't suggest which transactionId is being used. In my opinion, the default strategy could be a round-robin approach. When we reach the limit, the counter resets. After each `FencedException` we got on producing, we increment the counter and eject existing producer from the cache.

**Comment by Wzy19930507** [comment]
https://github.com/spring-projects/spring-kafka/blob/c8e0c3336e91b18cf1525afdea40900c538ac54a/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java#L836-L854
Now the strategy of the code is similar to `Executors.newCachedThreadPool`.
- If producer exists in the cache, return cache
- if producer not exists in cache, create TX producer
- tx producer have keepAliveTime
- If normally close, return producer to cache
- If abnormal close like `FencedException` , close producer

> When we reach the limit, the counter resets. After each FencedException we got on producing, we increment the counter and eject existing producer from the cache.
This scene is similar to `Executors.newFixedThreadPool`
- If producer exists in the cache, return cache
- if producer not exists in the cache, check whether the alive producers have reached the limit
  - if not reached the limit, create tx-producer with unused txid (**diff**)
  - if reached the limit, execute reject policy
- tx producer have keepAliveTime
- If normally close, return producer to cache
- If abnormal close like `FencedException` , close producer

**Comment by garyrussell** [comment]
Probably the simplest solution would be a new property `maxCache`. When non-zero, we pre-populate a blocking queue with the "available" suffixes.

When a producer is not returned to the cache (either because it was fenced, or because the `maxAge` expired in `expire()`) we add that suffix back to the queue for reuse.

When a producer is requested and there are no cached producers, and there are no "available" suffixes, we throw a `NoProducerAvailableException`.

The user can then use a `RetryTemplate` configured to retry that exception, with a suitably configured back off.

**Comment by Wzy19930507** [comment]
Hi, @stillya @garyrussell , If you don't mind, may i pick it up?
I think `maxCache` is feasible.

**Comment by garyrussell** [comment]
Sure; thanks!

**Comment by stillya** [comment]
Hi, @Wzy19930507 and @sobychacko.
I've decided to lend a hand and created a pull request with a new interface to enable the management of `transactionIdSuffix`. Could you please take a look?
