### ISSUE TITLE
Add Option to Log Recovered Record to DeadLetterPublishingRecoverer

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2862]
See https://stackoverflow.com/questions/77368555/spring-boot-with-kafka-not-logging-exceptions-on-deserialization-when-using-dl/77368770#77368770

**Comment by Wzy19930507** [comment]
Hi @garyrussell , may i pick it up?

> Add Option to Log Recovered Record to DeadLetterPublishingRecoverer

If my understanding is correct, i will add code after `DeadLetterPublishingRecoverer.accept()#L505` 
https://github.com/spring-projects/spring-kafka/blob/6876694d4bea8fc5aa995e89097a7bf8f439e61c/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L498-L506

```
if (logRecoveredRecord) {
    logger.error("Recovered Record " + KafkaUtils.format(record) + " , exception " + exception.toString());
}
```

**Comment by garyrussell** [comment]
Sure, but I think it belongs I the the `DefaultErrorHandler` after successful recovery.

**Comment by Wzy19930507** [comment]
Thanks for your reply. I'm sorry I didn't notice that.

**Comment by garyrussell** [comment]
I see, yes, complicated; let's go back to logging in the DLPR only.
