### ISSUE TITLE
Consumer Factory Has the Wrong Default for isAutoCommit

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#288]
Results in the container committing which causes strange behavior with the offsets.

http://stackoverflow.com/questions/43405009/kafka-stop-consuming-message-from-new-assigned-patitions-after-rebalancing/43413899#43413899

**Comment by wuhuanxing** [comment]
Hi Gary,
the work-around setting spring.kafka.consumer.enable-auto-commit=true will cause another issue:
the messages will be consumed twice or more times ( by original consumer and new assigned consumers after rebalancing)

**Comment by garyrussell** [comment]
Auto-commit only commits every 5 seconds by default. If you use container commits (`AckMode.RECORD`) you should be ok.
