### ISSUE TITLE
Need to connect to 2 kafka cluster simultaneously, using auto-configuration

### ISSUE THREAD

**Issue by shubhamsaurav139** [spring-projects/spring-kafka#2886]
![image](https://github.com/spring-projects/spring-kafka/assets/150228472/acbbbe7a-2b15-401e-9421-3eb33424acd2)

**Comment by artembilan** [comment]
This sounds more like Spring Cloud Stream question.
And I would suggest to follow Microservice architecture and have several instances of your application each connected to those different clusters.
No need in mixing concerns in a single application.

If you have more questions, please, consider to raise an issue in the https://github.com/spring-cloud/spring-cloud-stream

**Comment by garyrussell** [comment]
Don't paste text as image; it makes it difficult to quote.

Also see Multi-Binder support https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#multiple-systems - you can define two binders, one for each cluster.
