### ISSUE TITLE
How to get a topic name from a message?

### ISSUE THREAD

**Issue by yeralin** [spring-projects/spring-kafka#290]
```
 @KafkaListener(topics = "#{'${topics}'.split(',')}")
 public void receive(String message) {
 		System.out.println(message);
}
```

So, I declared multiple topics under `topics=topic1,topic2,etc` in my property files.
Everything works as expected, I receive messages from different topics, but I don't know exactly from what topic a message came from.

Is there a way to get a topic name when receiving a message?

**Comment by neetkee** [comment]
Try to declare KafkaHeaders in parameters of method, like this:
```
 @KafkaListener(topics = "#{'${topics}'.split(',')}")
 public void receive(String message, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
 		System.out.println(message);
}
```
it's described in documentation of [KafkaListener annotation](http://docs.spring.io/spring-kafka/docs/1.2.0.RELEASE/reference/html/_reference.html#__kafkalistener_annotation)

**Comment by artembilan** [comment]
Thank you, @neetkee , for answer!

@yeralin , please, consider do not ask questions on GH.
Use community support forums like StackOverflow.
