### ISSUE TITLE
Issue with virtual threads enabled

### ISSUE THREAD

**Issue by ClearClean** [spring-projects/spring-kafka#2933]
# Application
I just updated to spring-boot 3.2.0.

My application is using spring-kafka (3.1.0) and starts a lot of kafka consumers dynamically.

# Problem
When I set : `spring.threads.virtual.enabled=true`, I get the following error in
`org.springframework.kafka.listener.KafkaMessageListenerContainer` :
```
Consumer thread failed to start - does the configured task executor have enough threads to support all containers and concurrency?
```

When I disable virtual threads, its working like before.

Asked on Stackoverflow :
https://stackoverflow.com/questions/77647890/virtual-threads-pool-with-spring-kafka

Might be related to :
https://github.com/spring-projects/spring-boot/issues/38563

**Comment by ClearClean** [comment]
It was not easy to isolate and reproduce ... But I think I found the problem.

I'm using synchronized block along with `container.start()` and this hangs the virtual thread and prevent the start.

[demo.zip](https://github.com/spring-projects/spring-kafka/files/13663182/demo.zip)

**Comment by artembilan** [comment]
So, why do you do that `synchronized (this.containers) {` then?
As it is well-known the `synchronized` is not OK with virtual threads: https://blog.fastthread.io/2023/02/28/pitfalls-to-avoid-when-switching-to-virtual-threads/.

This seems like a problem of your own code: nothing to confirm that we have something in the framework by itself.

**Comment by ClearClean** [comment]
Well it was a stackoverflow question, not really an issue at first...

**Comment by artembilan** [comment]
Virtual treads are mounted to platform threads. And that is really one-to-many. 
So, if you have some coordination between threads, you just end-up with dead lock on `synchronized` block since one virtual thread is pinned to platform in that case and another cannot do anything since it is mounted to the same platform thread.
