### ISSUE TITLE
Is Non Blocking Retry (@Retryable) intended to be combined with Kafka Transactions (consumer initiated) ?

### ISSUE THREAD

**Issue by PaulFert** [spring-projects/spring-kafka#2934]
### Discussed in https://github.com/spring-projects/spring-kafka/discussions/2918

<div type='discussions-op-text'>

<sup>Originally posted by **PaulFert** December  1, 2023</sup>
Hello,

I wanted to use both features for consume -> process -> produce applications

When i use Transaction with Blocking Retry, DLT Recover the flow is : 
![Kafka-Error-Handling-Transaction-Blocking-Retry-Transaction drawio](https://github.com/spring-projects/spring-kafka/assets/5616739/906a9214-ac09-45b8-a1cd-e725250f6a13)

When exception is raised from the listener, the transaction is rollback and then a new transaction is created for the send to DLT, OK fine.

On the oher side, when i use Transaction with Non Blocking Retry the flow is more like that : 
![Kafka-Error-Handling-Transaction-Non-Blocking-Retry-Transaction drawio](https://github.com/spring-projects/spring-kafka/assets/5616739/1fb46c39-aca3-4849-94ec-13baa905bd31)

When exception is raised from the listener, *the transaction is not rollback*, the message is send to retry topic and finally the transaction is comited. Then consumer offsets is commit *plus the messages out* and messages to retry topic. If an exception is raised i want my messages out to be not comited.

It's not what i expected, i expected a flow like that :
![Kafka-Error-Handling-Transaction-Non-Blocking-Retry-Transaction-expected drawio](https://github.com/spring-projects/spring-kafka/assets/5616739/6c22272a-bf35-486c-be09-f7c6576b336e)

Did i miss something with the configuration ? I use standard configuration, with one kafkatemplate, with transactional producer
Or maybe did i misunderstood the Non Blocking Retry pattern,  Transactions are not intended to be combined with ? 

Sorry for my poor english...

Testing with 'org.springframework.boot' version '3.1.1-SNAPSHOT', spring-kafka version 3.0.8

Thanks
</div>

**Comment by Wzy19930507** [comment]
Use `@RetryTopic`, `DeadLetterPublishingRecoverer` will inject `CommonErrorHandler.
`RuntimeException` catch by `CommonErrorHandler`  in transaction, but not throw RuntimeException again.

1. exception catch by `CommonErrorHandler`
https://github.com/spring-projects/spring-kafka/blob/e7e77b9830578d689321acf16b6b57f3c22449de/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2889-L2907

2. CommonErrorHandler call `DeadLetterPublishingRecoverer`, see `DeadLetterPublishingRecoverer.publish`, only log not threw again.
https://github.com/spring-projects/spring-kafka/blob/e7e77b9830578d689321acf16b6b57f3c22449de/spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java#L684-L706
---

not use @RetryTopic, will throw exception to transaction and rollback, Then `AfterRollbackProcessor` catch the exception.
AfterRollbackProcessor also inject `DeadLetterPublishingRecoverer`

**Comment by Wzy19930507** [comment]
Hi, @artembilan @sobychacko @PaulFert for this scenario(enable listener transaction and retry topic),  retry topic break the kafka transaction atomicity, move retry topic logic to `AfterRollbackProcessor` feelings can be resolved this question.

WDYT?
