### ISSUE TITLE
Supported spring boot version for spring-kafka 3.0.x is 3.1.x on https://spring.io/projects/spring-kafka#overview but in build.gradle springboot version is 3.0.x only

### ISSUE THREAD

**Issue by adhanoti** [spring-projects/spring-kafka#2948]
Supported spring boot version for spring-kafka 3.0.x is 3.1.x on https://spring.io/projects/spring-kafka#overview but in build.gradle springboot version is 3.0.x only. Can you please confirm whether spring-kafka 3.0.x is compatible with spring-boot 3.1.x?
![Uploading Screenshot 2023-12-18 155214.png…]()

**Comment by artembilan** [comment]
That one has nothing to do with development and direct project dependencies.
See its comment:
```
springBootVersion = '3.0.12' // docs module
```
So, that one just for samples compilation used in the docs.

But since the current `3.1.x` is aimed only for Spring Boot `3.2.x`, we are going to upgrade that dependency anyway.

Thanks
