### ISSUE TITLE
When Kafka not available, connection retry blocking unrelated http requests to the spring boot application.

### ISSUE THREAD

**Issue by KenanDuzgun** [spring-projects/spring-kafka#2977]
Spring-Kafka 3.0.2

There are two problems. First, When kafka not available, trying to reconnect to Kafka, spring boot application blocks unrelated http requests. If there is not reconnection thread running, requests took 3-4 seconds.  But If kafka is down and there is a reconnection thread running on background, http requests take 40-50 seconds.

Below is my Producer Config

https://gist.github.com/KenanDuzgun/a707419dccc8b0fa4d1446a0b592320e

Second , 

To solve the problem I added below two line to change frequency of reconnection period but it did not take effect when spring application starts running.

configProps.put(org.apache.kafka.clients.producer.ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG,"5000");
configProps.put(org.apache.kafka.clients.producer.ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG,"10000");

https://stackoverflow.com/questions/77717405/spring-boot-kafka-reconnection-frequency-cannot-be-set

**Comment by sobychacko** [comment]
@KenanDuzgun, our apologies for not triaging the issue sooner. Do you have any updates since the time you created this issue? The SO thread referenced above is not available any longer and I wonder whether you got to the bottom of this issue or not.
