### ISSUE TITLE
Can't recognize original exception when abortTransaction() failed

### ISSUE THREAD

**Issue by chanhyeong** [spring-projects/spring-kafka#2981]
If an exception occur in the below code block `producer.abortTransaction()`, the original `Exception e` is discarded.

https://github.com/spring-projects/spring-kafka/blob/c683f31a432acf26c0b570d643b59610524e3ec6/spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java#L660-L663

I recently encountered this case, and I think the original was raised while processing upper line `T result = callback.doInOperations(this);`.

Is there any way to know about the original exception?
If not, it would be nice add logging of the exception or rethrowing composite exception.

**Comment by artembilan** [comment]
Confirming as a bug.
That supposed to use `addSuppressed()` for the original exception where we catch the one from `abortTransaction()`.
