### ISSUE TITLE
KafkaTemplate is invoking onError() method in custom ProducerListener and also throwing Exception after the call

### ISSUE THREAD

**Issue by pavanvarmab** [spring-projects/spring-kafka#2984]
3.0.12

KafkaTemplate is throwing an Exception after invoking the onError() method in the custom ProducerListener.

**To Reproduce**

KafkaTemplate.send("wrong-topic",Data) 
or 
set producer config max.request.size=1
KafkaTemplate.send("topic-name",Data) 

**Expected behavior**
KafkaTemplate.send() invokes the onError() and also throws the KafkaException in doSend() 

this issue is similar to https://github.com/spring-projects/spring-kafka/issues/2817

**Comment by artembilan** [comment]
I'm not fully sure what you are asking here, and how an observation handling is related to your request.

The logic there is like: call `ProducerListener.onError()` and throw that exception back to the caller:
```
		// Maybe an immediate failure
		if (sendFuture.isDone()) {
			try {
				sendFuture.get();
			}
			catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				throw new KafkaException("Interrupted", e);
			}
			catch (ExecutionException e) {
				throw new KafkaException("Send failed", e.getCause()); // NOSONAR, stack trace
			}
		}
```

What do you I miss from your description, please?

**Comment by pavanvarmab** [comment]
I thought it was not supposed to throw the expectation if it is handled by callback.

**Comment by artembilan** [comment]
No, that's not a goal. It never meant to suppress an exception throwing.
See its Javadocs and its reference to the `org.apache.kafka.clients.producer.Callback`.
So, the behavior of `KafkaTemplate.send()` is fully modeled after `KafkaProducer.send()`.

Closing as `Works as Designed`
