### ISSUE TITLE
Invalid reference manual link in README

### ISSUE THREAD

**Issue by mateuszkl** [spring-projects/spring-kafka#3005]
Link from README that's not working: https://docs.spring.io/spring-kafka/docs/current/reference/html/
Valid link: https://docs.spring.io/spring-kafka/reference/index.html

**Comment by devholic22** [comment]
@mateuszkl Can I work this issue?

**Comment by mateuszkl** [comment]
@devholic22 Sure, I'm not planning to contribute to this project so it didn't make sense for me to go through a process that would allow to issue a PR, so I went for an issue instead.
