### ISSUE TITLE
Allow retry for meta data fetch by connecting to other brokers in the bootstrap servers list

### ISSUE THREAD

**Issue by yashtailor** [spring-projects/spring-kafka#3031]
**Expected Behavior**

After receiving producer exception saying topic xxx not available in meta data after xxx ms (max.block.ms), it should allow retry of meta data fetch by connecting to another broker in the boostrap servers list.

**Current Behavior**

After receiving the above exception, it throws an exception and error outs. 

**Context**

Intermittenly one of the brokers in the boostrap serves goes down due to which a lot of producer messages are failed. I want to enable retry for meta data fetch operation. metadata.max.age.ms helps to refresh the meta data, but it again tries to connect to the same broker.

**Comment by artembilan** [comment]
This not Spring functionality you are talking about.
Spring for Apache Kafka just does this:
```
Future<RecordMetadata> sendFuture =
				producer.send(interceptedRecord, buildCallback(interceptedRecord, producer, future, sample, observation));
```
So, all the hard work for publishing and extracting metadata is done by the `KafkaProducer`.
Consider to raise your concern against Apache Kafka by itself.

Closing as `Works as Designed`.
