### ISSUE TITLE
Ability to set ListenerExceptionLoggingStrategy from #2213

### ISSUE THREAD

**Issue by ndwhelan** [spring-projects/spring-kafka#3095]
**Expected Behavior**

A process or manner to set the `ListenerExceptionLoggingStrategy` to any value of `org.springframework.kafka.retrytopic.DeadLetterPublishingRecovererFactory.ListenerExceptionLoggingStrategy` in `org.springframework.kafka.retrytopic.DeadLetterPublishingRecovererFactory`. 

**Current Behavior**

Despite the logging code supporting different values for `loggingStrategy` in `ListenerExceptionLoggingStrategy`, there is no way to change this value. It's set as a private member variable with `ListenerExceptionLoggingStrategy.AFTER_RETRIES_EXHAUSTED` defined at the definition.

**Context**

I would like to be able to configure my retry listeners to not log when publishing to the DLT. It's expected in some situations, and I'd prefer to keep expected errors out of logs/error tracking tools.

I checked out the related PR, from #2213, but there are no details on how to set this. I'm not sure if this would work, but as a private variables, it's not something that I can set by overriding the class.

**Comment by artembilan** [comment]
The `DeadLetterPublishingRecovererFactory` has this by default:
```
private ListenerExceptionLoggingStrategy loggingStrategy = ListenerExceptionLoggingStrategy.AFTER_RETRIES_EXHAUSTED;
```
That strategy has only 3 options:
```
	private enum ListenerExceptionLoggingStrategy {

		/**
		 * Never log the listener exception.
		 */
		NEVER,

		/**
		 * Log the listener exception after each attempt.
		 */
		EACH_ATTEMPT,

		/**
		 * Log the listener only after retries are exhausted.
		 */
		AFTER_RETRIES_EXHAUSTED

	}
```

To turn off that default value there are options on the `DeadLetterPublishingRecovererFactory` to do that:
```
	/**
	 * Never logs the listener exception.
	 * The default is logging only after retries are exhausted.
	 * @since 2.7.13
	 */
	public void neverLogListenerException() {
		this.loggingStrategy = ListenerExceptionLoggingStrategy.NEVER;
	}

	/**
	 * Logs the listener exception at each attempt.
	 * The default is logging only after retries are exhausted.
	 * @since 2.7.13
	 */
	public void alwaysLogListenerException() {
		this.loggingStrategy = ListenerExceptionLoggingStrategy.EACH_ATTEMPT;
	}
```

From there the logging logic is like this:
```
	private void maybeLogListenerException(Exception e, ConsumerRecord<?, ?> cr, DestinationTopic nextDestination) {
		if (nextDestination.isDltTopic()
				&& !ListenerExceptionLoggingStrategy.NEVER.equals(this.loggingStrategy)) {
			LOGGER.error(e, () -> getErrorMessage(cr) + " and won't be retried. "
					+ "Sending to DLT with name " + nextDestination.getDestinationName() + ".");
		}
		else if (nextDestination.isNoOpsTopic()
				&& !ListenerExceptionLoggingStrategy.NEVER.equals(this.loggingStrategy)) {
			LOGGER.error(e, () -> getErrorMessage(cr) + " and won't be retried. "
					+ "No further action will be taken with this record.");
		}
		else if (ListenerExceptionLoggingStrategy.EACH_ATTEMPT.equals(this.loggingStrategy)) {
			LOGGER.error(e, () -> getErrorMessage(cr) + ". "
					+ "Sending to retry topic " + nextDestination.getDestinationName() + ".");
		}
		else {
			LOGGER.debug(e, () -> getErrorMessage(cr) + ". "
					+ "Sending to retry topic " + nextDestination.getDestinationName() + ".");
		}
	}
```

So, what stops you to call `neverLogListenerException()` and turn off `DEBUG` logging level for the `org.springframework.kafka.retrytopic` category?

**Comment by ndwhelan** [comment]
@artembilan thank you for the detailed reply... I appreciate it.

I can do what you've shared. I simply had been unable to figure out how to do this... how to use `DeadLetterPublishingRecovererFactory`. I've got that sorted. I regret that I necessarily took your time, but, again, I genuinely appreciate it.

If anyone else stumbles upon this, I added the following to one of my `@Configuration` classes:

```java
@Bean
DeadLetterPublishingRecoverer dltConfig(DestinationTopicResolver resolver) {
    final DeadLetterPublishingRecovererFactory deadLetterPublishingRecovererFactory = new DeadLetterPublishingRecovererFactory(resolver);
    deadLetterPublishingRecovererFactory.neverLogListenerException();
    return deadLetterPublishingRecovererFactory.create();
}
```

I'll go ahead and close this.
