### ISSUE TITLE
traceId is changing when event is retried.

### ISSUE THREAD

**Issue by mkoralewski** [spring-projects/spring-kafka#3152]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.3

In 3.1.2 works fine

**Describe the bug**

We use @RetryableTopic. When we have spring-kafka 3.1.2 and event is retried it has the same traceId. 
After upgrading to spring-kafka 3.1.3 traceId is changing in each retry.

**To Reproduce**

Send event to @RetryableTopic that will cause some exception and will be retried.

**Expected behavior**

Retried event should have the same traceId like original one (the same behavior as in spring-kafka 3.1.2)

**Sample**

I'm not able to share sample now, hope that description above is enough.

**Comment by artembilan** [comment]
This one is duplication of #3151 since Topic Retry logic fully relies on the mentioned `DefaultErrorHandler`. See `ListenerContainerFactoryConfigurer` for more details:
```
	protected CommonErrorHandler createErrorHandler(DeadLetterPublishingRecoverer deadLetterPublishingRecoverer) {
		DefaultErrorHandler errorHandler = createDefaultErrorHandlerInstance(deadLetterPublishingRecoverer);
		errorHandler.defaultFalse(this.retainStandardFatal);
		errorHandler.setCommitRecovered(true);
		errorHandler.setLogLevel(KafkaException.Level.DEBUG);
		if (this.blockingExceptionTypes != null) {
			errorHandler.addRetryableExceptions(this.blockingExceptionTypes);
		}
		this.errorHandlerCustomizer.accept(errorHandler);
		return errorHandler;
	}
```
