### ISSUE TITLE
Introduce separate `autoStartup` for retry listeners.

### ISSUE THREAD

**Issue by JooHyukKim** [spring-projects/spring-kafka#3164]
**Expected Behavior**

Suggestion : Allow autoStartup configuration for retry-listeners via `@RetryableTopic` or `RetryTopicConfiguration`

There are cases where you want separate `autoStartUp` config for retryable topic listeners, like when you want to consume all existing messages in retry topics first before moving on with the main topics, or vice versa.

Our new, expected behavior is depicted in below example.
Here we have, on application start, main-listeners are at stopped state where as retry-listeners start consuming already.

```java
	@RetryableTopic(attempts = "5", autoStartup = "true")
	@KafkaListener(id = "fooGroup", topics = "topic4", autoStartup = "false")
	public void listen(
                        String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic,
			@Header(KafkaHeaders.OFFSET) long offset
	) {
		// implementation...
```
		               
**Current Behavior**

But currently, in this example, retry-listeners will have `autoStartup` set to `true`

```java
	@RetryableTopic(attempts = "5", autoStartup = "true") // no autoStartup for
	@KafkaListener(id = "fooGroup", topics = "topic4", autoStartup = "false")
	public void listen(
                        String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic,
			@Header(KafkaHeaders.OFFSET) long offset
	) {
		// implementation...
```

**Context**

Again, there are cases where you want separate `autoStartUp` config for retryable topic listeners, like when you want to consume all existing messages in retry topics first before moving on with the main topics, or vice versa.

**Comment by artembilan** [comment]
I feel the reasoning behind the request, but I don't think it is so simple as requested `autoStartup` option on the annotation.
How are you going to start that separate consumption on retry topics?
It looks like we always have only a single container registered into a `KafkaListenerEndpointRegistry`.
And apparently only a single container is listening for all those topics: main and retry.

Please, elaborate how you see an evolution of your request?

Thanks

**Comment by JooHyukKim** [comment]
> And apparently only a single container is listening for all those topics: main and retry.

If so, I guess programatically shutting down main/retry may be more viable solution as I am currently doing now.
Thank you for the explanation --I should've looked into it myself first 🙏🏼

Will close the issue for now. Feel free to re-open if ever needed.
