### ISSUE TITLE
@PartitionOffset supprt TopicPartitionOffset.SeekPosition

### ISSUE THREAD

**Issue by Wzy19930507** [spring-projects/spring-kafka#3178]
**Expected Behavior**

@PartitionOffset Support SeekPosition.BEGINNING, SeekPosition.END, SeekPosition.TIMESTAMP

**Context**

When MessageListenerContainer init, seek consumer offsets by SeekPosition.

**Comment by artembilan** [comment]
That request might make sense, but is not so easy to implement. 
There is needed an extra logic in the `KafkaListenerAnnotationBeanPostProcessor` to build `TopicPartitionOffset` properly from that annotation.

Feel free to contribute the fix though!
