### ISSUE TITLE
Polling for fetches with timeout - Message being printed Continuously in logs after spring boot upgrade to 3.2.4

### ISSUE THREAD

**Issue by cumulate** [spring-projects/spring-kafka#3179]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.3 

**Describe the bug**

I have upgraded the Spring boot version in my Application from `3.1.2 `to `3.2.4`. Since my upgrade, I have seen the below message logged continuously.

The below message floods the logs and it's frustrating that I'm not able to find actual business log statements while on TRACE mode because the whole log file is swammed with these messages.

Is there anything broken in spring-kafka in the latest version??

Unable to figure it out. 

**To Reproduce**

Provided a link to the Github repo where the issue can be reproduced

**Expected behavior**

Log statements for the said case should be limited. Too much trace, swamping the logs and actual business transactions log statements are lost when application is run with TRACE enabled.

**Repository**

link to a GitHub repository with issue being reproduced [ spring-kafka-issue-continuous-log](https://github.com/cumulate/spring-kafka-issue-continuous-log).

Just checkout the code and run it, probably change the username and password, as cloud Kafka is used to reproduce the issue in these case

[ spring-kafka-issue-continuous-log 2024-04-04 13-33-02.mp4](https://github.com/cumulate/spring-kafka-issue-continuous-log/blob/master/spring-kafka-issue-continous-log%20%E2%80%93%20application.yml%20%5Bspring-kafka-issue-continuous-log.main%5D%202024-04-04%2013-33-02.mp4).

Stackoverflow question -> https://stackoverflow.com/questions/78269709/polling-for-fetches-with-timeout-message-printed-continuosly-message-in-logs-a

**Comment by sobychacko** [comment]
In Boot `3.1.2` (Spring Kafka `3.0.x` version), the trace logging is initiated directly from the `KafkaConsumer` class which is under the `org.apache.kafka` package. This is why you are not getting any of those traces in `3.1.2`. However, in Boot `3.2.4` (SK `3.1.x`), the consumer is delegated from the `DefaultKafkaConsumerFactory#ExtendedKafkaConsumer` which is under `org.springframework` package and this is why you see this is traced. In the latest version of the kafka java client (`3.7.0`) that is used in the upcoming SK `3.2.0` release which is going to be part of Boot `3.3.0`, it seems like Kafka removed that tracing statement altogether, so when you upgrade to that version, you won't have this issue. 

To fix your issue, can you add this to your config:
`logging.level.org.apache.kafka.clients.consumer.KafkaConsumer: INFO`

**Comment by cumulate** [comment]
only the below config worked
  ` logging level.org.springframework.kafka.core.[DefaultKafkaConsumerFactory$ExtendedKafkaConsumer]: INFO`

**Comment by sobychacko** [comment]
Ok, that also works. Feel free to close the issue.
