### ISSUE TITLE
support storing offsets outside kafka

### ISSUE THREAD

**Issue by jorgheymans** [spring-projects/spring-kafka#318]
Hi,

I was wondering if spring-kafka facilitates the storing of offsets in a local datastore instead of kafka, as described here http://kafka.apache.org/0102/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html ? It would be nice if it were just a strategy to configure, useful for those that require strong exactly-once semantics on a topic.

Thanks

**Comment by garyrussell** [comment]
We just added the `ConsumerAwareRebalanceListener` for that purpose - it's available in the 2.0.0.M2 milestone release; the GA release is planned for late next month.

[See the reference manual](http://docs.spring.io/spring-kafka/docs/2.0.0.M2/reference/html/_reference.html#rebalance-listeners).

**Comment by artembilan** [comment]
Just to share more info on the matter: https://github.com/spring-projects/spring-kafka/issues/9

**Comment by jorgheymans** [comment]
@garyrussell what i meant was an easy way to let spring-kafka store the offset for a consumerrecord in the local application database, as part of the ongoing transaction. Upon next poll it would seek for this stored offset +1. If the user transactions rolls back for whatever reason the new offset is not stored and the same message will be redelivered.

**Comment by jorgheymans** [comment]
given that the latest kafka release now supports exactly-once semantics this is no longer relevant for me, any effort should be directed towards the new transactional functionality in 0.11.
