### ISSUE TITLE
How to acknowledge from RecoveryCallback

### ISSUE THREAD

**Issue by mvmn** [spring-projects/spring-kafka#319]
Or specifically, why does `RetryContext` get populated with `"record"`, but not `"acknowledgement"` in [RetryingAcknowledgingMessageListenerAdapter](https://github.com/spring-projects/spring-kafka/blob/1.2.x/spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingAcknowledgingMessageListenerAdapter.java)?

	@SuppressWarnings("unchecked")
	@Override
	public void onMessage(final ConsumerRecord<K, V> record, final Acknowledgment acknowledgment) {
		getRetryTemplate().execute(new RetryCallback<Object, KafkaException>() {

			@Override
			public Void doWithRetry(RetryContext context) throws KafkaException {
				context.setAttribute("record", record);
				RetryingAcknowledgingMessageListenerAdapter.this.delegate.onMessage(record, acknowledgment);
				return null;
			}

		}, (RecoveryCallback<Object>) getRecoveryCallback());
	}

Now when I want to have X retries for processing record, and then in recovery callback, say, store record in some deadletters storage - and after that of course acknowledge it - I can't seem to do it in recovery callback.

P.S. In 2.x the RetryingAcknowledgingMessageListenerAdapter seems to be removed, so with 2.x I'm not even sure where to start...

**Comment by mvmn** [comment]
P.P.S. An example of config/code of what I'm trying to achieve


	@Bean(name = { "kafkaIngestionListenerContainerFactory" })
	public KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<Integer, String>> kafkaListenerContainerFactory() {
		ConcurrentKafkaListenerContainerFactory<Integer, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
		factory.setConsumerFactory(consumerFactory());
		factory.setConcurrency(concurrency);
		factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL_IMMEDIATE);
		factory.getContainerProperties().setPollTimeout(15000);
		factory.setRecoveryCallback(new RecoveryCallback<Void>() {

			@Override
			public Void recover(RetryContext arg0) throws Exception {
				ConsumerRecord<?, ?> record = (ConsumerRecord<?, ?>) arg0.getAttribute("record");
				System.out.println("Recovery callback: " + record);
				// Save record to dead letters
				// Acknowledge after successfull save
				return null;
			}
		});
		RetryTemplate rt = new RetryTemplate();
		SimpleRetryPolicy srp = new SimpleRetryPolicy();
		srp.setMaxAttempts(retryAttempts);
		rt.setRetryPolicy(srp);
		factory.setRetryTemplate(rt);

		return factory;
	}

**Comment by garyrussell** [comment]
It's a  bug; the context should contain the ack.

In 2.0, the various listener interfaces have been put into a hierarchy so the single `RetryingMessageListenerAdapter` handles listeners that can acknowledge.

Maintaining discrete listener types became unwieldy when we added the consumer-aware listeners.

**Comment by mvmn** [comment]
Right, just to be clear - the bug is in both 1.x and 2.x, and this is current code from master (so 2.x), which is missing `context.setAttribute("acknowledgment", acknowledgment);` as well:

	@Override
	public void onMessage(final ConsumerRecord<K, V> record, Acknowledgment acknowledgment, Consumer<?, ?> consumer) {
		getRetryTemplate().execute(context -> {
					context.setAttribute("record", record);
					switch (RetryingMessageListenerAdapter.this.delegateType) {
						case ACKNOWLEDGING_CONSUMER_AWARE:
							RetryingMessageListenerAdapter.this.delegate.onMessage(record, acknowledgment, consumer);
							break;
						case ACKNOWLEDGING:
							RetryingMessageListenerAdapter.this.delegate.onMessage(record, acknowledgment);
							break;
						case CONSUMER_AWARE:
							RetryingMessageListenerAdapter.this.delegate.onMessage(record, consumer);
							break;
						case SIMPLE:
							RetryingMessageListenerAdapter.this.delegate.onMessage(record);
					}
					return null;
				},
				getRecoveryCallback());
	}

Ok, thanks for your answer. Looking forward to the fix.

**Comment by garyrussell** [comment]
Yes; I issued 2 PRs, one for master and one for the 1.x branches.
