### ISSUE TITLE
Micrometer observation rewrites message header with invalid value

### ISSUE THREAD

**Issue by skolorz** [spring-projects/spring-kafka#3202]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.1

**Describe the bug**

1. The external system (spring-boot 2.7) sends a kafka message with JSON style headers:
```
spring_json_header_types: "{\"b3\":\"java.lang.String\",\"my-name\":\"java.lang.String\" ...
my-name: "x"
```
where the character " is part of the header value, represented as a byte array [34, 120, 34].

2.  **org.springframework.messaging.support.GenericMessage** is created, and message headers are decoded using types defined in spring_json_header_types. The message header **my-name** has the value **"x"** (String).

3. A baggage-field my-name is created. Raw header value is read from **org.apache.kafka.common.header.Header** using a getter defined in **org.springframework.kafka.support.micrometer.KafkaRecordReceiverContext**
`return new String(header.value(), StandardCharsets.UTF_8)`
As the original Kafka header value is [34, 120, 34], the getter returns "\"x\"".

4.  baggage-field  is propagated to **org.springframework.messaging.support.GenericMessage** headers, and "my-name: "x" is overwritten by "my-name: "\"x\""

**To Reproduce** 
1. Consume a kafka message with JSON style headers. 
2. A string header name is configured as a baggage field in 
management.tracing.baggage.remote-fields

**Expected behavior**
KafkaRecordReceiverContext handles JSON style headers

**Comment by artembilan** [comment]
Consider to se this option to `true` on the `AbstractKafkaHeaderMapper` for your producer:
```
	/**
	 * Set to true to map all {@code String} valued outbound headers to {@code byte[]}.
	 * To map to a {@code String} for inbound, there must be an entry in the rawMappedHeaders map.
	 * @param mapAllStringsOut true to map all strings.
	 * @since 2.2.5
	 * @see #setRawMappedHeaders(Map)
	 */
	public void setMapAllStringsOut(boolean mapAllStringsOut) {
```
There is just no sense to serialize strings as JSON.
So, they are going to be set into Kafka record headers as plain `byte[]` and deserialized properly by the mentioned `KafkaRecordReceiverContext`.

On the other hand, if producer side would use a `KafkaRecordSenderContext` (in other words `KakfaTemplate`), then those headers would not be serialized as JSON:
```
	public KafkaRecordSenderContext(ProducerRecord<?, ?> record, String beanName, Supplier<String> clusterId) {
		super((carrier, key, value) -> record.headers().add(key,
				value == null ? null : value.getBytes(StandardCharsets.UTF_8)));
```

**Comment by skolorz** [comment]
I understand that it can't be solved on the consumer side and must be addressed on the producer side.
