### ISSUE TITLE
Implement CommonErrorHandler.handleOne() in CommonDelegatingErrorHandler

### ISSUE THREAD

**Issue by Blackney** [spring-projects/spring-kafka#3227]
**Expected Behavior**

`CommonDelegatingErrorHandler` should implement `CommonErrorHandler.handleOne()`
This implementation should be the same as the other `handle` methods - Finding a delegate `CommonErrorHandler`, then call it's `.handleOne()` method. If a delegate cannot be found, use the `defaultErrorHandler`

**Current Behavior**

Currently this method is not implemented, and the default behaviour from the `CommonErrorHandler` interface is to log an error and return true, indicating the error was "handled"

**Context**

This issue came up when trying to use the `DefaultErrorHandler` with `seekAfterError` set to `false`
The value of `seekAfterError` is used for the return of the `DefaultErrorHandler.seeksAfterHandling()` method, the value of which is used to decide whether `CommonErrorHandler.handleRemaining()` vs `CommonErrorHandler.handleRemaining()` is called when an error is thrown by a non-batch Listener

I wish to be able to use the `seekAfterError` behaviour in the `DefaultErrorHandler`, while also using the `CommonDelegatingErrorHandler` to delegate between different `DefaultErrorHandler`'s

**Comment by sobychacko** [comment]
Sounds like a reasonable request. If you are open to it, please submit a PR. Otherwise, we will try to make it in before the `3.2.0` release.

**Comment by artembilan** [comment]
Related SO question: https://stackoverflow.com/questions/78417683/why-does-commondelegatingerrorhandler-in-spring-kafka-not-implement-handleone
