### ISSUE TITLE
Why not to support registerSeekCallback and onPartitionsAssigned to batchListener?

### ISSUE THREAD

**Issue by realcbb** [spring-projects/spring-kafka#323]
Code in KafkaMessageListenerContainer:

			if (listener instanceof BatchMessageListener) {
				this.listener = null;
				this.batchListener = (BatchMessageListener<K, V>) listener;
				this.isBatchListener = true;
			}

Why not set  this.listener = listener, otherwise, registerSeekCallback and onPartitionsAssigned can be supported.

**Comment by garyrussell** [comment]
It's a bug.

**Comment by realcbb** [comment]
Thanks for the feedback. 
Also I dont know why consumerAware and retry are not supported to batchListener.
For retry feature, retry is on "onMessage" method rather than consumer's poll method. Why should not end-users have the retry on the whole batch?

**Comment by garyrussell** [comment]
Retry is left to the user because the framework has no idea where in the batch the failure occurred; you can simply use a `RetryTemplate` within your listener.

There is a [`BatchConsumerAwareMessageListener`](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/BatchConsumerAwareMessageListener.java).

**Comment by realcbb** [comment]
I think, the framework does not need to know where in the batch the failure occurred. Just retry the process in onMessage method.

When using @KafkaListener, it seems that BatchComsumerAwareMessageListener will not be auto created, and some error occurred such like List<ConsumerRecord> or List<Message> must be the only parameter.

**Comment by garyrussell** [comment]
Yes, but if the batch fails in the middle, the whole batch will be retried. I don't think the framework can make any assumptions that the listener can handle duplicate messages; it's really a function inside the listener.

The error when trying to use a `Consumer<?, ?>` parameter with a batch `@KafkaListener` is another bug.

Thanks for giving the 2.0 milestone(s) a spin - useful feedback; thanks!

**Comment by realcbb** [comment]
Thanks for your great work!

Besides, is there any possible to support this feature:
When errors occurred during processing messages from consumer's poll, auto-seek to the position of partitions before this poll? Maybe that's not a good idea...

**Comment by garyrussell** [comment]
Perhaps we could add a `ConsumerAwareErrorHandler` (and the batch version) and implementations that do as you suggest.

**Comment by realcbb** [comment]
Thank you very much!

**Comment by garyrussell** [comment]
See #325 and #328
