### ISSUE TITLE
Batch Listener when encountered a poison pill, records after that poison pill are moved to next poll.

### ISSUE THREAD

**Issue by Tarun4572** [spring-projects/spring-kafka#3297]
@garyrussell so in a batch if a record fails (even after retry) records after that failed record are sent to next poll. am i correct. that batch stops at failed record and rest of records are sent to next poll. could you help with this, what happening with my case is, if i have batch of 5 messages and all 5 of them are corrupt messages, so i could see, first message fails and rest 4 are sent to next poll and in next poll, first message fails again and rest are sent to next poll. is this expected behavior. thank you

**Comment by Tarun4572** [comment]
FixedBackOff fixedBackOff = new FixedBackOff(0L, 0L);
        DeadLetterPublishingRecoverer recoverer = new DeadLetterPublishingRecoverer(kafkaTemplate, (r, exception) -> {
            log.error("sending message to dlt topic:{}", dltTopic);
            // pushing message into dltTopic 0th partition
            return new TopicPartition(dltTopic, r.partition());
        });

        return new DefaultErrorHandler(recoverer, fixedBackOff);
        
 
 
 
 @Service("kafkaStreamListener")
@Slf4j
public class KafkaStreamListener implements BatchMessageListener<String, String> {

    @Autowired
    private SubscriberUsageRecordServiceImpl subscriberUsageRecordService;
    
    @Value("${dlt.uagDltTopic}")
    private String uagDltTopic;

    @Override
    public void onMessage(List<ConsumerRecord<String, String>> data) {
        log.info("Kafka Stream Listener");
        
        UUID batchId = UUID.randomUUID();
        long start = System.currentTimeMillis();
        log.info("Received Batch, BatchId: {}", batchId);
        
        for (ConsumerRecord<String, String> consumerRecord : data) {
            String value = consumerRecord.value();
            log.info("<< Input JSON to UAG Service : " + value);
            try {
               throw new ProcessingException();
            } catch(ProcessingException e) {
            	if(!uagDltTopic.isEmpty())
            		throw new BatchListenerFailedException("Failed to process record", consumerRecord); 
            	log.error("Exception while processing Usage Event", e);
            } catch (Exception e) {
            	if(!uagDltTopic.isEmpty())
            		throw new BatchListenerFailedException("Failed to process record", consumerRecord);
            	log.error("Exception while processing Usage Event", e);
			}
        }
        
        long end = System.currentTimeMillis();
		long timeTakenInMillis = end - start;
		log.info("Completed Processing BatchId: {}, time: {} ms", batchId, timeTakenInMillis);
        

    }
}


when there is a poison pill in batch, code after for loop is not executed.

**Comment by artembilan** [comment]
That's correct.
Your logic is like this:
```
if(!uagDltTopic.isEmpty())
        		throw new BatchListenerFailedException("Failed to process record", consumerRecord); 
```
So, as long as you throw an exception from that `try` and `uagDltTopic` is not empty you don't go after that loop.

**Comment by Tarun4572** [comment]
we need to throw BatchListenerFailedException for our errorhandler to get triggered

**Comment by Tarun4572** [comment]
so in a batch if a record fails (even after retry) records after that failed record are sent to next poll. am i correct. that batch stops at failed record and rest of records are sent to next poll. could you help with this, what happening with my case is, if i have batch of 5 messages and all 5 of them are corrupt messages, so i could see, first message fails and rest 4 are sent to next poll and in next poll, first message fails again and rest are sent to next poll. is this expected behavior. 


is this right behavior, could you please answer this.

**Comment by artembilan** [comment]
I answer you in other discussion: https://github.com/spring-projects/spring-kafka/issues/2577#issuecomment-2165782114.

So, yeah, the behavior is expected.

**Comment by sobychacko** [comment]
We are closing this issue. If you see further problems, please feel free to re-open.
