### ISSUE TITLE
getUnregisteredListenerContainer return null

### ISSUE THREAD

**Issue by aliciz** [spring-projects/spring-kafka#3319]
version: 3.1.1

I am encountering an issue where the getUnregisteredListenerContainer method from the KafkaListenerEndpointRegistry returns null. This occurs in the scenario where I am not using the @KafkaListener annotation but instead, I am manually registering custom containers.

```java
public void pause(String id) {
        MessageListenerContainer listenerContainer = registry.getUnregisteredListenerContainer(id);
        if (listenerContainer == null) {
            log.warn("listenerContainer not exists id:{}", id);
            return;
        }
        listenerContainer.pause();
}
```

![image](https://github.com/spring-projects/spring-kafka/assets/45386902/16647d07-b955-49e9-bd39-74b780d78a3d)

**Comment by aliciz** [comment]
container define like this:

```java
    @Bean(name = KafkaBeanName.DEVICE_DATA_LISTENER_CONTAINER)
    public ConcurrentMessageListenerContainer<String, DeviceData> deviceDataListenerContainer(@Qualifier(KafkaBeanName.DEFAULT_LISTENER_CONTAINER_FACTORY) ConcurrentKafkaListenerContainerFactory<String, DeviceData> factory, IDeviceDataListener deviceDataListener) {
        String topic = KafkaTopic.getDeviceDataTopicByAppId(ttliotSdkProperties.getAppId());
        log.info("afka container init topic:{}", topic);
        ConcurrentMessageListenerContainer<String, DeviceData> container = factory.createContainer(topic);
        Properties props = container.getContainerProperties().getKafkaConsumerProperties();
        props.put(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, ListenerContainerInterceptor.class.getName());
        props.put(JsonDeserializer.VALUE_DEFAULT_TYPE, DeviceData.class.getName());
        container.setupMessageListener(deviceDataListener);
        container.setRecordInterceptor(new DeviceDataRecordInterceptor());
        return container;
    }
```

You are correct; the unregisteredContainers list does contain the container, but getUnregisteredListenerContainer still returns null.

![image](https://github.com/spring-projects/spring-kafka/assets/45386902/e726cbfd-96a5-4fff-924a-192330b4052b)


Can't it be written like this?
```java
@Override
@Nullable
public MessageListenerContainer getUnregisteredListenerContainer(String id) {
  MessageListenerContainer container = this.unregisteredContainers.get(id);
  if (container == null) {
	  refreshContextContainers();
	  return this.unregisteredContainers.get(id);
  }
  return container;
}
```

**Comment by artembilan** [comment]
Oh! I see. That is definitely bug 😄 
Since that `refreshContextContainers();` is called only from this method (and `getAllListenerContainers()`), it indeed returns `null` on the subsequent calls for `getUnregisteredListenerContainer()`.

Will fix shortly.
Unfortunately, the release was a couple days ago, so the next one in a month.
As a workaround I suggest to use `getAllListenerContainers()` and filter that result for desired `MessageListenerContainer`.

**Comment by sobychacko** [comment]
Issue is fixed via https://github.com/spring-projects/spring-kafka/commit/8096c9d3fe71dc16d7547624b0976ce0d9b2da6a.
