### ISSUE TITLE
Filtering Messages don't support batch listener when using @KafkaListener

### ISSUE THREAD

**Issue by realcbb** [spring-projects/spring-kafka#335]
A ClassCastException will be thrown if setRecordFilterStrategy to batch-listener-container-factory and using `@KafkaListener`. 

And doc said that, "Finally, FilteringBatchMessageListenerAdapter and FilteringBatchAcknowledgingMessageListenerAdapter are provided, for when using a batch message listener." But there is no FilteringBatchAcknowledgingMessageListenerAdapter class at all.

**Comment by garyrussell** [comment]
Thanks; both are bugs.
