### ISSUE TITLE
please help me ,spring kafka @KafkaListener support placeholder as follow?

### ISSUE THREAD

**Issue by importsource** [spring-projects/spring-kafka#336]
@KafkaListener(id = "abc", topics = "${com.is.topics}", group = "efg")
    @Override
    public void listen(ConsumerRecord<String, byte[]> record) {....

thks  10000 times

**Comment by realcbb** [comment]
Yes

**Comment by artembilan** [comment]
This is invalid place for questions.
The best place to start is some public community forum, for example StackOverflow: https://stackoverflow.com/questions/tagged/spring-kafka
