### ISSUE TITLE
BatchMessagingMessageConverter loses headers from ConsumerRecord

### ISSUE THREAD

**Issue by lm231290** [spring-projects/spring-kafka#3376]
**Version**
3.2.2

**Description**

`List<Map<String, Object>> convertedHeaders = new ArrayList<>();`
...
`addToRawHeaders(rawHeaders, convertedHeaders, natives, raws, conversionFailures);`
...
`if (this.headerMapper != null && record.headers() != null) {`
`Map<String, Object> converted = new HashMap<>();`
`this.headerMapper.toHeaders(record.headers(), converted);`
`convertedHeaders.add(converted);`

convertedHeaders is used before it is populated

**To Reproduce**

Use batch listener - @KafkaListener(batch = "true", ...)
BatchMessagingMessageConverter is used by default

**Expected behavior**

All headers are added to MessageHeaders, just like in MessagingMessageConverter

**Comment by artembilan** [comment]
I'm not sure in your concern.
```
List<Map<String, Object>> convertedHeaders = new ArrayList<>();
```
Then:
```
		if (this.headerMapper != null) {
			rawHeaders.put(KafkaHeaders.BATCH_CONVERTED_HEADERS, convertedHeaders);
		}
```
And we indeed can modify this list afterwards.

Any chances to the see prove that it is not lie that?

I mean something is missed from the whole context, so I don't see how that `convertedHeaders` might be empty.

Some simple project to reproduce and debug would be great.

Thanks

**Comment by lm231290** [comment]
Oh, ok, it comes in KafkaHeaders.BATCH_CONVERTED_HEADERS
