### ISSUE TITLE
DefaultKafkaProducerFactory: add timeout to KafkaProducer.close()

### ISSUE THREAD

**Issue by andrewtyt** [spring-projects/spring-kafka#338]
Hi,

Currently KafkaProducer.close() is called without timeout which can block thread indefinitely. This happens when there are undelivered records in producer's buffer and broker goes down (see [KAFKA-1788](https://issues.apache.org/jira/browse/KAFKA-1788)).
Could please add possibility to close producer with timeout? I'd suggest adding some 'timeout' configuration value which defaults to Long.MAX_VALUE.

Thanks!

**Comment by garyrussell** [comment]
Thanks for pointing this out; this is not so much a problem with a Spring Kafka app since we only actually close the producer when the application is stopped "normal" producer close operations are ignored since we take the recommended approach of using a single producer for all operations.
