### ISSUE TITLE
Incorrect JavaDoc for KafkaMessageHeaderAccessor.getBlockingRetryDeliveryAttempt()

### ISSUE THREAD

**Issue by lm231290** [spring-projects/spring-kafka#3408]
Version 3.2.2

JavaDoc says:
```
Access the header value when the blocking delivery attempt header is present.
Returns:
1 if there is no header present; the decoded header value otherwise.
Throws:
IllegalStateException – if the header is not present.
See Also:
org.springframework.kafka.listener.ContainerProperties.setDeliveryAttemptHeader(boolean)
```

Actually, it doesn't return 1, if no header present, it throws IllegalStateException

**Comment by artembilan** [comment]
Agreed.
Feel free to contribute the fix: https://github.com/spring-projects/spring-kafka/blob/main/CONTRIBUTING.adoc
Thanks

**Comment by MichaelMoyles** [comment]
I can take this issue and update the docs

**Comment by sobychacko** [comment]
@MichaelMoyles, please send a PR addressing this issue. See the contribution guidelines above.

**Comment by artembilan** [comment]
Thanks. @MichaelMoyles , for suggesting the help!
You definitely can take and open PR.
However only team members can be assigned for the issue.
Either way your contribution will be accepted and credited on release motes.
