### ISSUE TITLE
AnnotationEnhancer always return the old attributes

### ISSUE THREAD

**Issue by crmky** [spring-projects/spring-kafka#3425]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.7

**Describe the bug**

It seems `AnnotationEnhancer` introduced by https://github.com/spring-projects/spring-kafka/pull/1818 always return old attributes instead of new attributes. 

Refer to https://github.com/spring-projects/spring-kafka/blob/78d77243bdc61c2097b1d7a792706bdc4db9275e/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L363

**Comment by sobychacko** [comment]
Looks like a bug. We will look at this today. Thanks!

**Comment by sobychacko** [comment]
The `newAttr` is a reference to the old map - `attr`. However, there is a chance that the enhancer impls could change that reference. We will fix it.
