### ISSUE TITLE
PDF reference documentación support for spring Spring Kafka 3.2.x 

### ISSUE THREAD

**Issue by jabrena** [spring-projects/spring-kafka#3426]
Hi, I have observed that the last release version with pdf support is:

- https://docs.spring.io/spring-kafka/docs/3.0.x/reference/

But the following version doesn’t have pdf support:

- https://docs.spring.io/spring-kafka/docs/3.1.x/
- https://docs.spring.io/spring-kafka/docs/3.2.x/
- https://docs.spring.io/spring-kafka/docs/3.3.x/
- https://docs.spring.io/spring-kafka/docs/current/

In theory, the GA version is 3.2.x but it has not a pdf version:
https://spring.io/projects/spring-kafka#learn

can you add it?

many thanks in advance 

Juan Antonio

**Comment by sobychacko** [comment]
Hi @jabrena, After the `3.0.x` generation, we moved to a new antora-based model for reference documents. The PDF output is no longer available as before.
