### ISSUE TITLE
Spring Boot Kafka Micrometer observability doesn't work with concurrency enabled

### ISSUE THREAD

**Issue by claudiomerli** [spring-projects/spring-kafka#3459]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.3.0

**Describe the bug**

I configured my application to load beans based on properties in this way:

```
  @Bean
        @ConditionalOnProperty(
            prefix = "fleexi.kafka.override-concurrency",
            value = {"enabled"}
        )
        ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactoryWithConcurrency(ConsumerFactory<String, String> kafkaConsumerFactory, FleexiKafkaProperties fleexiKafkaProperties) {
            ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory();
            factory.setConcurrency(fleexiKafkaProperties.getOverrideConcurrency().getListenerConcurrency());
            factory.getContainerProperties().setObservationEnabled(true);
            factory.setConsumerFactory(kafkaConsumerFactory);
            return factory;
        }

        @Bean
        @ConditionalOnMissingBean({ConcurrentKafkaListenerContainerFactory.class})
        ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory(ConsumerFactory<String, String> kafkaConsumerFactory) {
            ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory();
            factory.getContainerProperties().setObservationEnabled(true);
            factory.setConsumerFactory(kafkaConsumerFactory);
            return factory;
        }
```

In the first case, with concurrency enabled observabilities log traceId and spanId doesn't work.

![image](https://github.com/user-attachments/assets/dc03f51f-2f0b-4297-85ca-cfc7a63c1b02)

In second case, without concurrency it works properly enter image description here
![image](https://github.com/user-attachments/assets/4e254bfe-dc11-47f7-835f-ab5364587a62)

Concurrency breaks observability?

**To Reproduce**

Configure a spring boot project same as above

**Expected behavior**

Observability works properly in both situation

**Sample**

https://stackoverflow.com/questions/78915817/spring-boot-kafka-micrometer-observability-doesnt-work-with-concurrency-enabled

**Comment by sobychacko** [comment]
@claudiomerli, Can you put your sample code in a self-contained application and provide a way to reproduce it? That way, we can triage it faster.

**Comment by artembilan** [comment]
Closed in favor of StackOverflow question: https://stackoverflow.com/questions/78915817/spring-boot-kafka-micrometer-observability-doesnt-work-with-concurrency-enabled.

We will reopen it when we agree that there is a problem.
Otherwise it is a duplication.

Thanks for understanding!

**Comment by claudiomerli** [comment]
Here the sample: https://github.com/claudiomerli/demo-issue-spring-kafka-3459
