### ISSUE TITLE
Allow `@DltHandler` Method to be Defined in a parent class of class annotated with `@KafkaListener`

### ISSUE THREAD

**Issue by JooHyukKim** [spring-projects/spring-kafka#3463]
**Expected Behavior**

`@DltHandler`-annotated method may be in the same class or parent class as the corresponding `@KafkaListener` annotation.

**Current Behavior**

`@DltHandler`-annotated method must be in the same class as the corresponding `@KafkaListener` annotation.

**Context**

My usecase is that all our consumer class have their own listener method annotated with `@RetryableTopic` and `@KafkaListener` to define per-class specific`RetryableTopic.retryTopicSuffix` property.
But all `@DltHandler` methods implementations are exactly the same.
So it would be nice to allow the suggested behavior.

**Comment by JooHyukKim** [comment]
This sort of offshoot of #3183

**Comment by artembilan** [comment]
@JooHyukKim ,

The proposal is here: #3464 

Thank you for looking into this!

**Comment by JooHyukKim** [comment]
LGTM, thank you for quick response!
