### ISSUE TITLE
Warning log when using AnnotationEnhancer

### ISSUE THREAD

**Issue by RuslanHryn** [spring-projects/spring-kafka#3467]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

in the latest version 3.2.3

**Describe the bug**

There is the following warning log when using AnnotationEnhancer at the start of the app:

`trationDelegate$BeanPostProcessorChecker : Bean 'groupIdEnhancer' of type [org.example.springkafkaenhancerreproducer.EnhancerConfiguration$$Lambda/0x0000000800332650] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [org.springframework.kafka.config.internalKafkaListenerAnnotationProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.`

As I know this warning means that BeanPostProcessor uses `internalKafkaListenerAnnotationProcessor` and Spring had to create `internalKafkaListenerAnnotationProcessor` before the BeanPostProcessor. That's why, internalKafkaListenerAnnotationProcessor can't be processed by the BeanPostProcessor.

Therefore, it should not cause any issues, but eliminating this warning would be nice.

**To Reproduce**

1. Create `AnnotationEnhancer` as described here https://docs.spring.io/spring-kafka/reference/kafka/receiving-messages/kafkalistener-attrs.html
2. Run the app on Spring Boot 3.2 or 3.3
3. There is the following warning message in the logs:

`trationDelegate$BeanPostProcessorChecker : Bean 'groupIdEnhancer' of type [org.example.springkafkaenhancerreproducer.EnhancerConfiguration$$Lambda/0x0000000800332650] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [org.springframework.kafka.config.internalKafkaListenerAnnotationProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.`

**Expected behavior**

No warning messages in the logs when using `AnnotationEnhancer`

**Sample**

I can provide if needed but it should be very easy to reproduce

**Comment by sobychacko** [comment]
@RuslanHryn Thanks for the report. We will look at this.

**Comment by RuslanHryn** [comment]
@sobychacko thanks! forgot to mention that I'm able to reproduce this issue on Spring Boot 3.2 and 3.3

**Comment by artembilan** [comment]
@RuslanHryn ,

I think you mean this doc since there is no mentioning of the `AnnotationEnhancer` in the `testing` chapter: https://docs.spring.io/spring-kafka/reference/kafka/receiving-messages/kafkalistener-attrs.html#page-title.

Do you have that your `groupIdEnhancer` bean definition declared as `static`  like we suggest in the mentioned doc?

**Comment by RuslanHryn** [comment]
@artembilan Sorry, fixed the link in the description.

> Do you have that your groupIdEnhancer bean definition declared as static like we suggest in the mentioned doc?
yes, it is static

**Comment by artembilan** [comment]
Yeah... According to my testing that `static` still does not help.
There is another trick to skip that since it is really only for annotations and not supposed to be heavily dependent on some business logic.
Add `@Role(BeanDefinition.ROLE_INFRASTRUCTURE)` into that `groupIdEnhancer` bean definition.
