### ISSUE TITLE
spring.io API documentation links aren't updated correctly

### ISSUE THREAD

**Issue by sgendler-ep** [spring-projects/spring-kafka#347]
![screen shot 2017-06-06 at 3 32 33 pm](https://user-images.githubusercontent.com/29236290/26855228-b7b3bdca-4ace-11e7-8823-f2fae7b8756c.png)

The first 4 API links in that screenshot on the spring-io site all go to the latest production release of the API instead of pointing to the milestone-specific version of the API (the reference doc links are correct but not the API links).  This makes it very difficult to keep up with changes to the API in release milestones that are weakly documented (most of them), since the changes often aren't visible in the production release - examples include everything to do with retries, which have undergone a variety of changes in the various milestones, errorHandler attribute in @KafkaListener annotation, various others.

**Comment by artembilan** [comment]
Thank you for pointing to that, @sgendler-ep !

Fixed now.
