### ISSUE TITLE
spring-kafka depends on unrelease springframework core libs

### ISSUE THREAD

**Issue by sgendler-ep** [spring-projects/spring-kafka#348]
I'm trying to get working retry and recovery code running in my spring-kafka project, which requires building against the latest snapshot of spring-kafka.  My app uses the latest released version of spring-boot (1.5.3) which requires springframework 4.3.8.  However, the 4.3.8 version of util.Assert doesn't contain an overloaded state() method that takes a function Supplier as the second argument.  I have to look to unreleased springframework 5.0.0 code in order to find that method.  It seems like a mistake for spring-kafka to be dependent on unreleased 5.0.0 springframework for such a trivially small optimization.  Can that code be reverted back to something that compiles against released code?  The calls in question are at the bottom of MessagingMessageListenerAdapter.determineInferredType(method)

Also, is there a map of 2.0.0 milestones somewhere? The project seems very opaque when it comes to such details. I'd love to know how deep a hole I am jumping into when I accept a dependency on spring-kafka 2.0.0

**Comment by garyrussell** [comment]
spring-kafka 2.0 requires Spring Framework 5.0. It will be released soon after that.

You can see the current [milestone dates here on github](https://github.com/spring-projects/spring-kafka/milestones).

What specific fix are you referring to? We have backported most bug fixes to 1.2.x and 1.1.x; we are releasing the next versions of those today.

**Comment by artembilan** [comment]
Isn't this is your question as well https://stackoverflow.com/questions/44420605/spring-kafka-snapshot-builds-exist-somewhere ?

For the task you described you have to take a look to Spring Boot 2.0.
That is normal that project in development depends on the lib in development.
We don't rely for Spring Framework 5.0 just only for the `Assert` change.
We don't encourage users to use our build-snapshots to get a frustrating like yours, but you should be ready that Spring Kafka is fully based on Spring Framework 5.0 and there is no way back.
Everything will be leveraged by Spring Boot 2.0.

**Comment by garyrussell** [comment]
For 2.0, we can add another milestone if you are not comfortable developing on snapshots.

**Comment by sgendler-ep** [comment]
I was looking for a fix that occurred between 2.0.0.M2 and current master, but I was looking for it there mainly because of a difference in how things are documented between 2.x and 1.x.  The 2.x reference docs mention the spring-retry functionality higher up in the documentation such that my first impression was that automated retries were only available in 2.x releases.  I did eventually figure out that the functionality is available in earlier releases but I had just failed to see it in the docs.  A lot of this was exacerbated by the ‘bug’ I reported yesterday where the API links for a variety of releases all pointed to the wrong API.  I drew a lot of conclusions about what functionality was in what releases based on what I was finding in the API before I noticed that every version was going to the same docs. Once I sorted that out, it became a lot easier for me to discover things, but it took me much of today to undo some of the assumptions I had made earlier.  I eventually figured out that I can just use the latest production release to get the functionality I was looking for.



Samuel Gendler
Principal Software Engineer
Technology - IT Software

sgendler@ep.com<mailto:sgendler@ep.com>
PHONE (818) 953-8848
FAX
[Entertainment Partners: an employee owned company]<http://www.ep.com>

Disclaimer - June 7, 2017

This email and any attachments are confidential and intended solely for spring-projects/spring-kafka,spring-projects/spring-kafka,Author. If you are not a named addressee you are prohibited from reviewing, printing, disseminating, distributing, copying or altering this email or any part of it. If you have received this communication in error, please notify the sender of the error immediately, do not read or use the communication in any manner, destroy all copies, and delete it from your system if the communication was sent via email. Warning: Although Entertainment Partners has taken reasonable precautions to ensure no viruses are present in this email, the recipient is responsible for checking for and deleting viruses. Entertainment Partners does not accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by garyrussell** [comment]
1.2.2.RELEASE (kafka 0.10.2.x) and 1.1.6.RELEASE (0.10.0/1.x) are in maven central.
