### ISSUE TITLE
Allow @Override of KafkaAdmin createAdmin()

### ISSUE THREAD

**Issue by anders-swanson** [spring-projects/spring-kafka#3483]
**Expected Behavior**

The Spring KafkaAdmin class has a package-private method "createAdmin" that returns the `org.apache.kafka.clients.admin.AdminClient` type:

```java
AdminClient createAdmin() {
    return AdminClient.create(this.getAdminConfig());
}
```

It'd be great if this method was protected, and returned the `org.apache.kafka.clients.admin.Admin` type. Additionally, the code in KafkaAdmin would need to be updated to use the `Admin` interface, instead of the `KafkaAdmin` class.

It's currently possible to do something similar the default producer/consumer factories, as they have methods like this:

```java
	protected Consumer<K, V> createKafkaConsumer(Map<String, Object> configProps) {
		checkBootstrap(configProps);
		Consumer<K, V> kafkaConsumer = createRawConsumer(configProps);
		if (!this.listeners.isEmpty() && !(kafkaConsumer instanceof ExtendedKafkaConsumer)) {
			LOGGER.warn("The 'ConsumerFactory.Listener' configuration is ignored " +
					"because the consumer is not an instance of 'ExtendedKafkaConsumer'." +
					"Consider extending 'ExtendedKafkaConsumer' or implement your own 'ConsumerFactory'.");
		}

		for (ConsumerPostProcessor<K, V> pp : this.postProcessors) {
			kafkaConsumer = pp.apply(kafkaConsumer);
		}
		return kafkaConsumer;
	}
```

**Current Behavior**

KafkaAdmin cannot be extended/overridden to use another type of class implementing the  `org.apache.kafka.clients.admin.Admin` interface.

**Context**

I'm using [OKafka](https://github.com/oracle/okafka), which has implementations of the Kafka interfaces, e.g., the Admin interface, and I would like to use these implementations with Spring Kafka. Based on my understanding of the code, some modifications would need to be made as described - I'd also be interested in any workarounds, if they are available.

**Comment by sobychacko** [comment]
@anders-swanson I think this is a reasonable request. In these cases, we usually recommend providing the correct bootstrap server config to `KafkaAdmin` as long as you are still using the default `AdminClient` from the Kafka client. But since you are using a completely different `Admin` implementation, it makes sense to override that method. We will discuss this further and give an update here. Thanks!

**Comment by anders-swanson** [comment]
@sobychacko thanks! I created #3484 and ran a few tests against it, seems like it has potential.

**Comment by sobychacko** [comment]
That's great. We will review it and get back to you.

**Comment by anders-swanson** [comment]
Hi @sobychacko, I wanted to check in - have you been able to review this feature request?

**Comment by sobychacko** [comment]
Sorry, we will get to it soon.

**Comment by sobychacko** [comment]
@anders-swanson Sorry for the delay - the PR is now merged upstream and will be part of the upcoming `3.3.0-RC1`. Thank you for your contribution. More PRs are welcomed!

**Comment by anders-swanson** [comment]
Thanks! There might be a few more as I continue to experiment with Spring-Kafka and non-kafka-clients implementations of the Kafka interfaces.
