### ISSUE TITLE
Why 'messageConverter' only worked in method of `send(Message<?> message) `?

### ISSUE THREAD

**Issue by aqlu** [spring-projects/spring-kafka#351]
Such as the title. 

I read the source code of  `KafkaTemplate` and found, `MessageConverter` is only worked in:

```java
       @SuppressWarnings("unchecked")
	@Override
	public ListenableFuture<SendResult<K, V>> send(Message<?> message) {
		ProducerRecord<?, ?> producerRecord = this.messageConverter.fromMessage(message, this.defaultTopic);
		return doSend((ProducerRecord<K, V>) producerRecord);
	}
```

I think process `messageConverter` in  method of `doSend` is better,  in this way, those following method also can be used Converter.

```java
        @Override
	public ListenableFuture<SendResult<K, V>> send(String topic, V data) {
		ProducerRecord<K, V> producerRecord = new ProducerRecord<>(topic, data);
		return doSend(producerRecord);
	}

	@Override
	public ListenableFuture<SendResult<K, V>> send(String topic, K key, V data) {
		ProducerRecord<K, V> producerRecord = new ProducerRecord<>(topic, key, data);
		return doSend(producerRecord);
	}

	@Override
	public ListenableFuture<SendResult<K, V>> send(String topic, int partition, V data) {
		ProducerRecord<K, V> producerRecord = new ProducerRecord<K, V>(topic, partition, null, data);
		return doSend(producerRecord);
	}

	@Override
	public ListenableFuture<SendResult<K, V>> send(String topic, int partition, K key, V data) {
		ProducerRecord<K, V> producerRecord = new ProducerRecord<>(topic, partition, key, data);
		return doSend(producerRecord);
	}
```

**Comment by garyrussell** [comment]
? `MessageConverter` is used to convert from `Message<?>` (see `fromMessage()`).

The `send()` methods don't have a `Message<?>`.

Exactly what are you trying to achieve?

**Comment by aqlu** [comment]
@garyrussell  Thanks for you reply.

I defined `KafkaTemplate` as follows:

```java
@Bean
public KafkaTemplate<?, ?> kafkaTemplate(
        ProducerFactory<Object, Object> kafkaProducerFactory,
        ProducerListener<Object, Object> kafkaProducerListener,
        KafkaProperties properties,
        ObjectMapper objectMapper) {
    KafkaTemplate<Object, Object> kafkaTemplate = new KafkaTemplate<>(
            kafkaProducerFactory);
    kafkaTemplate.setProducerListener(kafkaProducerListener);
    kafkaTemplate.setMessageConverter(new StringJsonMessageConverter(objectMapper));
    kafkaTemplate.setDefaultTopic(properties.getTemplate().getDefaultTopic());
    return kafkaTemplate;
}
```

when I use `kafkaTemplate` to sending a custom object like this: 
```java
public void send(Oplog oplog) {
    kafkaTemplate.send(topic, oplog.getNs(), oplog); 
}
```

I expect `kafkaTemplate` can automatic convert `oplog` to  a `JSON` format string and send it to kafka. But the actual did not convert.

**Comment by realcbb** [comment]
@aqlu You should use JsonSerializer.

**Comment by aqlu** [comment]
@realcbb Thanks. But I'm not sure what you mean, How to use JsonSerializer? 

```java
kafkaTemplate.setMessageConverter(new StringJsonMessageConverter(objectMapper));
```  

Setting message converter  is it not do that?

**Comment by garyrussell** [comment]
As I said, `MessageConverter` is only for converting `Message<?>`, not arbitrary objects. As @realcbb says, use the `JsonSerializer` for your purpose.

You can configure it on the producer factory (via one of the alternate constructors) or as a producer property. For an example, see app5 from my SpringOnePlatform talk last year [code here](https://github.com/SpringOnePlatform2016/grussell-spring-kafka). Producer factory configuration [here](https://github.com/SpringOnePlatform2016/grussell-spring-kafka/blob/master/s1p-kafka/src/main/java/org/s1p/JsonConfiguration.java#L48).

**Comment by aqlu** [comment]
@garyrussell , Thanks again. Use your way to achieve the purpose.
