### ISSUE TITLE
Expect `KafkaOperations` instead of `KafkaTemplate` for `AbstractKafkaListenerContainerFactory#setReplyTemplate`

### ISSUE THREAD

**Issue by neshkeev** [spring-projects/spring-kafka#3524]
**Expected Behavior**

It should be possible to pass an implementation of `KafkaOperations` instead of `KafkaTemplate` into `KafkaListenerContainerFactory` since extending `KafkaTemplate` might not always be possible (no default constructor).

**Current Behavior**

Here is a custom implementation of `KafkaOperations`:

```java
class MyCustomKafkaOperationsImpl implements KafkaOperations<Object, Object> {
    ...
}
```

Unfortunately, I cannot pass an instance of `MyCustomKafkaOperationsImpl` inside `KafkaListenerContainerFactory`:

```java
@Configuration
public class MyConfig {

    public ConcurrentKafkaListenerContainerFactory<Object, Object> containerFactory() {
        var factory = new ConcurrentKafkaListenerContainerFactory();
        factory.setReplyTemplate(new MyCustomKafkaOperationsImpl()); // IMPOSSIBLE
        return factory;
    }
}
```

**Context**

Direct extension of `KafkaTemplate` might be impossible since its constructors requires at least a `ProducerFactory` object.  
I briefly scanned over the code base, I didn't find any places which require `KafkaTemplate` specific methods, all `send` operations come from `KafkaOperations`

**Comment by sobychacko** [comment]
@neshkeev I think this is a reasonable request (as far as I can see). Would you be open to sending a PR for this? Then, we can review it and make sure that there are no side effects.

**Comment by neshkeev** [comment]
@sobychacko , please approve my [PR](https://github.com/spring-projects/spring-kafka/pull/3525) so it can trigger a build

**Comment by artembilan** [comment]
As a project stewarded by US company, we are unable to accept contributions from Russian sources due to US law at this time.

**Comment by neshkeev** [comment]
@artembilan , I understand, no hard feelings.

Please consider implementing this idea yourself
