### ISSUE TITLE
Improving Observability in Asynchronous Processing (`CompletableFuture`, `Mono`)

### ISSUE THREAD

**Issue by chickenchickenlove** [spring-projects/spring-kafka#3528]
## Expected Behavior

When the consumer endpoint method returns `CompletableFuture<?>` or `Mono<?>` as a result, and both the `CompletableFuture<?>` and the `Mono<?>` are fail to complete due to an error thrown in the async loop, `spring-kafka` should report metrics indicating that there have been failures in async consumer tasks. 

For example, 
```
spring_kafka_listener_seconds_count{
error="AsyncLoopExecutionFailedException",
messaging_kafka_consumer_group="topic4",
messaging_operation="receive",
messaging_source_kind="topic",
messaging_source_name="topic4",
messaging_system="kafka",
spring_kafka_listener_id="org.springframework.kafka.KafkaListenerEndpointContainer#0-0"} 6
```

## Current Behavior
When the consumer endpoint method returns `CompletableFuture<?>` or `Mono<?>` as result, the `MessagingMessageListenerAdapater` adds a callback to both the `CompletableFuture<?>` and the `Mono<?>`. 

However, currently, `KafkaMessageListenerContainer` does not consider whether `CompletableFuture` and `Mono` fail to complete.

If both `CompletableFuture` and `Mono` instances are success to be created, `KafkaMessageListenerContainer` will not report error metric even if both `CompletableFuture` and `Mono` fail to complete. 

## Context 

I discovered this issue while solving another problem([GH-3276](https://github.com/spring-projects/spring-kafka/issues/3276)), and I checked to see if it was actually the case.
As expected, there was an issue.

To reproduce it, you can use method below. 
it describes that 
1. The `CompletableFuture<?>` successes to be created. 
2. The `CompletableFuture<?>` fails to complete.
```java
@Slf4j
@Component
public class MyAsyncBean {

    @RetryableTopic(
            attempts = "5",
            topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_DELAY_VALUE,
            autoCreateTopics = "true",
            backoff = @Backoff(delay = 1000)
    )
    @KafkaListener(topics = "topic4", groupId = "topic4")
    public CompletableFuture<Void> receive(ConsumerRecord<Object, Object> record) {
        return CompletableFuture.supplyAsync(() -> {
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }

                    throw new RuntimeException("Should report metric.");
                });
    }
}
```

## To reviewer
If you consider this to be a reasonable request, 
may I take on this task and try to solve it?

**Comment by artembilan** [comment]
I think this makes sense, but does not look that easy to fix.
We have a code like this in the `KafkaMessageListenerContainer`:
```
return observation.observe(() -> {
				try {
					invokeOnMessage(cRecord);
					successTimer(sample, cRecord);
					recordInterceptAfter(cRecord, null);
				}
				catch (RuntimeException e) {
					failureTimer(sample, cRecord);
					recordInterceptAfter(cRecord, e);
					if (this.commonErrorHandler == null) {
						throw e;
					}
					observation.error(e);
```
So, as long as listener returns control over here, an observation is closed.
It sounds like we must not use an `observe()`, but rather `start()` manually and deal with it in the mentioned `MessagingMessageListenerAdapter`. Stop it there (or `error()`) respectively in the async branch.
But need to dig more for technical details.
Feel free to give it a try!

**Comment by chickenchickenlove** [comment]
@artembilan thanks for considering this as a one of reasonable request!
As you mentioned, `Observation` instance will close its observe scope when each record is completed. 

It means that `Observation` instance in `KafkaMessageListenerContainer` does not consider the result of `CompletableFuture<?>` and `Mono<?>`. 

Therefore, i believe a new `Observation` instance is needed here, similar to the one in `KafkaMessageListenerContainer`.

```java
// MessagingMessageListenerAdapater.java
if (result instanceof CompletableFuture<?> completable) {
         ...
	completable.whenComplete((r, t) -> {
                 // newObservation maybe?
                 observation.observer(() -> { 
                     if (t == null) {
		  	asyncSuccess(r, replyTopic, source, messageReturnType);
		  	acknowledge(acknowledgment);
		    }
		    else {
		  	asyncFailure(request, acknowledgment, consumer, t, source);
		    }
                 }
                 ...
```

What do you think?

**Comment by sobychacko** [comment]
@chickenchickenlove We will take a crack at this on our end and share the feedback.

**Comment by chickenchickenlove** [comment]
Thanks for giving me deep information! 🙇‍♂️ 
I will study it even if I can't complete the task.

Also, thanks for keeping me updated on what's going on!"
