### ISSUE TITLE
Multiple group in one spring app

### ISSUE THREAD

**Issue by wangh09** [spring-projects/spring-kafka#353]
Hi, could I use consumers with different groups in one spring application? Thanks!

**Comment by garyrussell** [comment]
Yes, simply create a consumer factory for each one.

If you are using Spring Boot...

```java
Map<String, Object> consumerProperties = kafkaProperties.buildConsumerProperties();
// change the group id
consumerProperties.put(ConsumerConfig.GROUP_ID_CONFIG, "newGroup");
consumerFactory = new DefaultKafkaConsumerFactory<String, String>(consumerProperties), topics)
```

If you are not using Spring Boot, create the properties for each factory yourself.

**Comment by wangh09** [comment]
@garyrussell Thank you for replying! I realized that this is actually a spring usage problem...but could you please explain more specifically how could I affect each @KafkaListener annotation with different factories? Thank you very much!

**Comment by garyrussell** [comment]
You need a separate listener container factory bean for each group.

Boot only provides one.

[See here for how to configure one](http://docs.spring.io/spring-kafka/reference/htmlsingle/#_with_java_configuration).

```java
@Bean
ConcurrentKafkaListenerContainerFactory<Integer, String> containerFactory1() {
    ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
                                new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory1());
    return factory;
}
```

Then 

    @KafkaListener(id = "foo", topics = "annotated1", containerFactory="containerFactory1") 

    @KafkaListener(id = "foo", topics = "annotated1", containerFactory="containerFactory2")

etc.

**Comment by wangh09** [comment]
@garyrussell Thank you! It really helps!

**Comment by garyrussell** [comment]
The upcoming 2.0 release makes this easier; you can specify the `group` on the `@KafkaListener` itself (and we'll use the `id` attribute as the group by default).

**Comment by garyrussell** [comment]
http://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#__kafkalistener_changes
