### ISSUE TITLE
Example in Producer/Consumer Interceptors section of Spring Framework documentation need to be fixed

### ISSUE THREAD

**Issue by jourteen** [spring-projects/spring-kafka#3587]
[Wiring Spring Beans into Producer/Consumer Interceptors](https://docs.spring.io/spring-kafka/reference/kafka/interceptors.html) section of Spring for Apache Kafka documentation contains following code snippet:
```
@Bean
public ProducerFactory<?, ?> kafkaProducerFactory(SomeBean someBean) {
    Map<String, Object> producerProperties = new HashMap<>();
    // producerProperties.put(..., ...)
    // ...
    Map<String, Object> producerProperties = properties.buildProducerProperties();
    producerProperties.put(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, MyProducerInterceptor.class.getName());
    producerProperties.put("some.bean", someBean);
    DefaultKafkaProducerFactory<?, ?> factory = new DefaultKafkaProducerFactory<>(producerProperties);
    return factory;
}
```
I understand this is just an example, but creating producerProperties twice is confusing. I suggest to completely remove the second instance to make kafkaProducerFactory look similar to kafkaConsumerFactory.

**Comment by artembilan** [comment]
@jourteen , please, be our guest with a contribution: https://github.com/spring-projects/spring-kafka/blob/main/CONTRIBUTING.adoc !

**Comment by JiwonKKang** [comment]
Would it be alright if I submitted a PR for this?

**Comment by sobychacko** [comment]
PR merged.
