### ISSUE TITLE
Duplicate header processing in `BatchMessagingMessageConverter#processRecord()`

### ISSUE THREAD

**Issue by borahm-lee** [spring-projects/spring-kafka#3589]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

- 3.3.0-SNAPSHOT

**Describe the bug**

- Originally, logs were supposed to be left once per record list when there is no `headerMapper`, but now they are left as many times as there are records. 
- Similarly, putting `listenerInfo` on `rawHeaders` is being attempted as many times as there are records.

**To Reproduce**

- Run `BatchMessageConverterTests#testNoMapper()`.

**Expected behavior**

- It only logs once when there is no `headerMapper`.
- Putting `listenerInfo` to `rawHeaders` is also attempted only once.

**Sample**

> Currently, the logs in the code are at the `DEBUG` level, but I changed them to `WARN` for ease of reading.
- Test before fixing:
    ![image](https://github.com/user-attachments/assets/dc372c0c-a2e6-4ed9-b484-0cd8a60600f4)

- Test after fixing:
     ![image](https://github.com/user-attachments/assets/f044a6b2-9925-445c-ba9a-8276d1746b4a)

I'm opening a PR right away to address this issue.

**Comment by sobychacko** [comment]
PR merged.
