### ISSUE TITLE
If the concurrency value of ConcurrentMessageListenerContainer is greater than the number of allocated partitions, isContainerPaused will always return false, even after pause has been called.

### ISSUE THREAD

**Issue by jongseok-oh** [spring-projects/spring-kafka#3650]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
No issue occurred : 2.7.4, 2.7.14, 2.8.0, 2.8.5, 2.8.6, 2.8.7
Issue occurred : 2.8.8, 2.8.11, 3.0.0, 3.0.13 (I think over 2.8.8)

**Describe the bug**

The code that was working normally in version 2.7.4 fell into an infinite loop.
    
    public void pause(MessageListenerContainer container) {
            container.pause();
            waitForPause(container);
    }

    private void waitForPause(MessageListenerContainer container) {
        long waitTime = 0, interval = 5_000;
        while (!container.isContainerPaused()) {
            try {
                Thread.sleep(interval);
                waitTime += interval;
                log.info("waiting for pause: {}ms", waitTime);
            } catch (InterruptedException e) {
                log.error("Error while pausing container", e);
            }
        }
    }
    
In this code, if the container's implementation is ConcurrentMessageListenerContainer with a concurrency of 10 and the number of assigned partitions is less than 10, it will get stuck in an infinite loop in waitForPause.

**To Reproduce**

This occurs when the ConcurrentMessageListenerContainer's concurrency count is allocated to be greater than the consuming topic's number of partitions.

**Expected behavior**

I think that even if surplus consumers are created, they should be paused normally.
This issue is related to a commit in version 2.8.8. -> https://github.com/spring-projects/spring-kafka/commit/989fb298fb3aede424ca633a651cb36b86de8b73#diff-49bc63455f16e2f0b1fe17ed1ec885135d494883d5a21a3da53d031098d09a33R1633

If it wasn't intended, I think it should be corrected.

**Comment by sobychacko** [comment]
@jongseok-oh, `2.8.x` is an older release currently out of OSS support. Even versions `3.0.x` and `3.1.x` are out of OSS support. Could you upgrade your environment to Spring for Apache Kafka version 3.2.x or 3.3.0 and see if the problem persists? If so, we would be happy to triage this issue further. Thanks!

See the support timeline here for more details: https://spring.io/projects/spring-kafka#support

**Comment by jongseok-oh** [comment]
@sobychacko, Oh I see. I missed to check the OSS supported version.
Additionally, when I tested on versions 3.2.0, 3.2.5 and 3.3.0, i encountered the same problem.
Let's break down the problem to help you review it,

1. ConcurrentMessageListenerContainer.pause() called
2. ConcurrentMessageListenerContainer.isContainerPaused() called
3. If any of the KafkaMessageListenerContainers that the ConcurrentMessageListenerContainer contains do not have a partition assigned, isContainerPaused() will always return false.
4. KafkaMessageListenerContainers' isContainerPaused() checks isConsumerPaused(), and if no partition is assigned, consumerPaused will not be true.

I think that there may be consumers that are not partition assigned, please review it.

**Comment by sobychacko** [comment]
This is the expected behavior that you are observing. When the `isPaused` method is called, if a container is not assigned with any partitions, there is nothing to pause, and the method should return `false.`  Could you clarify the issue further?

**Comment by jongseok-oh** [comment]
For example, if you set the value of concurrency to high and create a Suppose a ConcurrentMessageListenerContainer exists with three containers with partitions assigned to it and one container with no partitions assigned to it.

The expected behaviour after calling `pause` on a ConcurrentMessageListenerContainer is that all child containers are paused and `isContainerPaused` returns true after a period of time, but this is not the case.

	@Override
	public boolean isContainerPaused() {
		this.lifecycleLock.lock();
		try {
			boolean paused = isPauseRequested();
			if (paused) {
				for (AbstractMessageListenerContainer<K, V> container : this.containers) {
					if (!container.isContainerPaused()) {
						return false;
					}
				}
			}
			return paused;
		}
		finally {
			this.lifecycleLock.unlock();
		}
	}

**ConcurrentMessageListenerContainer** `isContainerPaused`

It traverses the for loop and checks if any of its child containers are paused, and if a container with no partition assigned exists, false is returned.

If the user is careful and sets the concurrency to the number of partitions, the problem is solved, but it would be nice if the method behaviour was clearer.

**Comment by artembilan** [comment]
I understand your pain, but the current behavior reflects whatever is said in the JavaDocs:
```
	/**
	 * Return true if {@link #pause()} has been called; and all consumers in this container
	 * have actually paused.
	 * @return true if the container is paused.
	 * @since 2.1.5
	 */
	default boolean isContainerPaused() {
```

We might revise the logic in the future version for much better lifecycle management.
Since right now it feels like calling `pause()` and then `isContainerPaused()` would mislead - and we would never call `resume()`.
As long s this is a behavior change, we cannot treat it as a bug and fix it right away: it would need some baking for the next upcoming version.

**Comment by jongseok-oh** [comment]
I've looked at the JavaDocs and understand that this is not a bug.
I'll have to change the implementation to call `assignedPartitions` and traverse each TopicPartition and call `isPartitionPaused`.
How about adding an interface method that this implementation wraps around later? Haha
Thanks for the answer :)
