### ISSUE TITLE
Add a hook to allow the user to pass in additional properties to be applied when creating the embedded broker instance(s)

### ISSUE THREAD

**Issue by sslavic** [spring-projects/spring-kafka#369]
I'd like to be able to configure embedded Kafka e.g. with auto topic creation disabled and topic deletion enabled.

**Comment by artembilan** [comment]
Why do you need that option if you can just avoid topics to configure?
```
/**
	 * Create embedded Kafka brokers.
	 * @param count the number of brokers.
	 * @param controlledShutdown passed into TestUtils.createBrokerConfig.
	 * @param topics the topics to create (2 partitions per).
	 */
	public KafkaEmbedded(int count, boolean controlledShutdown, String... topics) {
```
You see that `topics` is vararg and it isn't mandatory.
So, if you don't provide topics to the Embedded Kafka, nothing won't be created.
And if we don't create topics here we can't delete anything. I don't think that is good idea to delete something what we haven't created before.

If you strongly need to control create/delete, consider to use `kafka.admin.AdminUtils`:
```
ZkUtils zkUtils = new ZkUtils(this.kafkaEmbedded.getZkClient(), null, false);
AdminUtils.createTopic(zkUtils, ...)
...
AdminUtils.deleteTopic(zkUtils, ...)
```

Although we can add for `KafkaEmbedded` an option to delete topics we have created before in the end...

**Comment by garyrussell** [comment]
@artembilan that's a different thing; the broker will automatically create topics when you publish to one that doesn't exist. He wants to disable that feature.

You can also configure how many partitions an auto-created partitions gets.

We just need to provide the ability to pass in a `Properties` object to allow the user to specify additional broker configuration properties which will be processed in `before()`.

**Comment by garyrussell** [comment]
https://kafka.apache.org/documentation/#brokerconfigs


`auto.create.topics.enable | Enable auto creation of topic on the server | boolean | true`

**Comment by sslavic** [comment]
I want to be able to write integration tests with Embedded Kafka configured with same feature flags as my production cluster and as my logic expects. Then I would be able to integration test that logic publishing to a topic which doesn't exist will fail and be appropriately handled - that logic assumes Kafka broker/cluster is configured with auto topic creation disabled.

Also, calling AdminUtils.deleteTopic from my logic will not fully work, unless broker is configured with topic deletion enabled - so my integration test verifying topic deleting logic did it's thing, will fail since it will find topic is still there.

**Comment by artembilan** [comment]
A-a-a! Got it.

Why all issues these days are not so clear...

And `delete.topic.enable` respectively...

How do you have time to read all that stuff?..

**Comment by sslavic** [comment]
Thanks!
