### ISSUE TITLE
documentation glitch on KafkaTemplate

### ISSUE THREAD

**Issue by jorgheymans** [spring-projects/spring-kafka#372]
The KafkaTemplate docs state

> Both asynchronous and synchronous methods are provided, with the async methods returning a Future.

This is not the case, at least not anymore IIUC since all methods return a Future. You can get async execution by registering a success/fail callback on the future, otherwise the send happens synchronously. At least that's how i interpret this sentence a couple of paragraphs later:

> Notice that the send methods return a ListenableFuture<SendResult>. You can register a callback with the listener to receive the result of the send asynchronously.

**Comment by artembilan** [comment]
@jorgheymans ,

That is good catch and your interpretation is perfect!

Would you mind contributing the fix on the matter?

Thanks
