### ISSUE TITLE
Minimum spring framework version

### ISSUE THREAD

**Issue by usulkies** [spring-projects/spring-kafka#376]
It is said, in the [Spring For Apache Kafka Reference (ver 1.2.2)](http://docs.spring.io/spring-kafka/docs/1.2.2.RELEASE/reference/htmlsingle/) that the project is 

> Tested with Spring Framework version dependency is 4.3.7 but it is expected that the framework will work with earlier versions of Spring

Tried to run an example above version 3.2.18, and the code won't compile since **ListenableFuture** is heavily used in the **KafkaTemplate** but it is introduced only in Spring Framework 4.0.
Moreover, the **SettableListenableFuture** was introduced in Spring Framework 4.1.
The reference documentation should be updated with this low limit.

**Comment by artembilan** [comment]
OK. Thanks. 

Well, indeed would be better to say which version is minimal.
Or even doesn't mention expectations, but just only tell that Spring Kafka is based on this version of Spring Framework and that's all.

At least with that we will avoid similar confuses and questions in the future.
Plus no one would go to try to test it against Spring Framework 2.5 😉 

Would be great to see a contribution, @usulkies !

We are going release the current milestone today, maximum tomorrow. So, I'm waiting for the PR until this evening.

Thanks

**Comment by usulkies** [comment]
Hi, Artem!
I'm relatively new to GitHub and haven't before sent any PR.
I'm afraid that I don't know where is the text for the reference anyway
(will be happy to learn).
Anyway, since time in my place is already 22:00, I think my contribution
will wait for some other opportunity.

Thanks for your encouraging response,
Uziel

‫בתאריך יום ב׳, 24 ביולי 2017 ב-16:39 מאת ‪Artem Bilan‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by artembilan** [comment]
No problem, @usulkies !

Let me commit the fix for you and you'll learn where and how.

Right, there are many other opportunities to contribute, so you are always welcome!

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-kafka/commit/5eec44501d6dff2bb687ac6f22648c2f54944821
