### ISSUE TITLE
Problem with Retrying deliveries when the application is DiscoveryClient

### ISSUE THREAD

**Issue by dndanoff** [spring-projects/spring-kafka#377]
Hi,

I am writing a Spring Boot application that consumes messages from a Kafka topic. On the ConcurrentKafkaListenerContainerFactory I have set a RetryTemplate with AlwaysRetryPolicy and ExponentialBackOffPolicy. The spring-kafka version is 1.2.2.RELEASE and the Kafka version is 0.10.2.0. With this setup everything works fine.
The problem arises when I add the following dependency from the Camden.SR5 version in the pom.xml:
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
```
The issue is that when there is exception while consuming messages from the topic my AlwaysRetryPolicy with ExponentialBackOffPolicy is not used. Instead I see that the message is retried 3 times and then it goes to some default ErrorHandler that logs the error.
How can I use both discovery client and user defined retry policy for Kafka consumer ?

**Comment by artembilan** [comment]
Would you mind sharing some simple Spring Boot application to play from our side?

Nothing obvious what may cause the problem. Unless you use some reserved bean name for your `RetryPolicy` which is overridden by the Spring Cloud.

Thanks

**Comment by dndanoff** [comment]
You were right I changed the name of our retry policy bean and now it is working.
Thank you very much for the time and support.

Should I close the issue ?

**Comment by artembilan** [comment]
Great!

Yes, we can close it, indeed. But let's think about the fix for the Spring Cloud do not override your custom bean! I'm not sure which project there, but that would be great if you raise an issue there. At least we will know the reason of the logic for this overriding.

Thanks

**Comment by dndanoff** [comment]
I am closing this issue. The reference to the issue in Spring Cloud is:
https://github.com/spring-cloud/spring-cloud-netflix/issues/2161
