### ISSUE TITLE
Controlling Offset

### ISSUE THREAD

**Issue by lalib** [spring-projects/spring-kafka#379]
Hey there,

I have a question about controlling offset. Lets assume I have a consumer such as following one.

`
public class ManagerConsumer implements BatchAcknowledgingMessageListener<String, ManagerEvent> {

    @KafkaListener(topics = "bilal-test", group = "benimgrubum", containerFactory = "kafkaListenerContainerFactory")
    @Override
    public void onMessage(final List<ConsumerRecord<String, ManagerEvent>> data, final Acknowledgment acknowledgment) {

        System.out.println("Received Messasge in group foo: ");
        // acknowledgment.acknowledge();

        throw new RuntimeException("dont commit");
    }
}`

Kafka Configuration

`@EnableKafka
@Configuration
public class KafkaConsumerConfig {

    @Bean
    public ConsumerFactory<String, ManagerEvent> consumerFactory() {
        final Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "benimgrubum");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
        props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "3");

        return new DefaultKafkaConsumerFactory<>(props, new StringDeserializer(),
                new JsonDeserializer<>(ManagerEvent.class));
    }

    @Bean
    public ConcurrentKafkaListenerContainerFactory<String, ManagerEvent> kafkaListenerContainerFactory() {

        final ConcurrentKafkaListenerContainerFactory<String, ManagerEvent> factory =
            new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL_IMMEDIATE);
        factory.setBatchListener(true);
        return factory;
    }
}
`

When i throw an exception, i do not want to receive the next sent message. I want to keep getting the same message. In this case, It does not commit the offset but keep getting the messages from the topic. Is there any configuration or a pattern? I am trying to achieve the event sourcing.

**Comment by brijan** [comment]
Hi, 
In your example you are throwing exception after acknowledging the message. If you acknowledge the message kafka will give you new one.

**Comment by lalib** [comment]
@brijan Sorry i forgot to add the kafka configurations. You can see that acknowledge is MANUAL_IMMEDIATE. So it does not commit the offset until i say.

**Comment by brijan** [comment]
Hi bilal,
Follow the link
https://github.com/spring-projects/spring-kafka/blob/master/src/reference/asciidoc/kafka.adoc#message-listeners

it says
MANUAL_IMMEDIATE - commit the offset immediately when the
Acknowledgment.acknowledge() method is called by the listener.


I think what you want to achieve is manual offset management and for that,
you have to write your own offset manager I guess(Not sure).

**Comment by lalib** [comment]
@brijan thanks for the your answer but as you see in the code, i do not commit the offset. When i check the zookeeper, i see that offset is not committed but still i get the following messages. When i restart the consumer, it starts from the beginning. 

The point is i do not want my consumer to get the next message if the offset is not committed. Even if i throw an exception, it gets the next one. How can i solve it?

**Comment by garyrussell** [comment]
Kafka and the container will not redeliver the message; use the retryable message listener adapter for your listener to deliver the same message multiple times.

**Comment by garyrussell** [comment]
[Documentation here](http://docs.spring.io/spring-kafka/reference/html/_reference.html#_retrying_deliveries).

**Comment by lalib** [comment]
@garyrussell thanks but I have already had a look at it. There is a limit in the retry. I want retry works until the exception is fixed. I do not want to receive the next message. Can i achieve it by using kafka client or kafka streams?

**Comment by artembilan** [comment]
There is an `AlwaysRetryPolicy` on the matter.

On the other hand that is not how Kafka works. The offset commit is exactly necessary for the next consumer in the group to follow the processed offset. The current working `Consumer` has its own in-memory control of the offset index and it really doesn't care about your commits.

Only what you can do is to use `ConsumerSeekAware` to `Consumer.seek()` to a desired position. And that happens on the next `poll()`: http://docs.spring.io/spring-kafka/docs/1.2.2.RELEASE/reference/html/_reference.html#seek

**Comment by lalib** [comment]
@artembilan thanks a lot. AlwaysRetryPolicy is what i was looking for. It solves my problem.

**Comment by artembilan** [comment]
Great!

Closing as a solved question...
