### ISSUE TITLE
Adding a timeout parameter to record-getting test utils

### ISSUE THREAD

**Issue by hgwood** [spring-projects/spring-kafka#380]
Hello, 

I got my first end-to-end Kafka Stream test to run successfully today! Thanks a lot for making Spring Kafka! 💯 

I have a suggestion. `getRecords` and `getSingleRecord` from `KafkaTestUtils` currently enforce a timeout of 1 minute when polling the consumer. This means that when a test expects messages to be there but none are (because the tested code is not correct), then it hangs for 1 minute before it fails.

If a `timeout` parameter was added to these methods, a test could specify a shorter timeout and fail faster. To ensure backwards compatibility, the current signatures could remain as overloads of the new methods.

What do you think? I have PR ready if you are interested.

**Comment by artembilan** [comment]
Ship it, @hgwood !

Thank you!
