### ISSUE TITLE
Spring Kakfa Thread pool in listerner

### ISSUE THREAD

**Issue by girish-1234** [spring-projects/spring-kafka#386]
We have a scenario where messages are received on particular topic. once we receive messages , we have thred pool that handles the request

```java
//@topic=topic_name
public void messageListerner()
{
//some message normalization
threadPoolExecutor.submit(<task_to_process_message>)   // This Threadpool is configured with 100 pool size

}
```

The issue is that the messages flow too fast. Messages are received at messageListerner() method and finally threadPoolExecutor takes care of the task and then it starts throwing  java.util.concurrent.RejectedExecutionException as there are no threads available in threadpool to execute the task.

Do we have any way where we can pause the consuming messages from Kafka.? I mean i can add custom code to check whether there is any thread available in threadpool to handle the received message and if it is available then only fetch next message from kafka.

**Comment by garyrussell** [comment]
In the 2.0 version (milestone 3 is available - 2.0.0.M3), there is a consumer-aware listener so you can pause/resume the consumer as you want.

2.0 will be released towards the end of next month.

It requires Java 8 and Spring 5.

**Comment by girish-1234** [comment]
Thanks for the reply. However we have alaready locked down the kafka version 0.10.1.0
Is there any way i can my own customize code to handle this scenarion?

**Comment by garyrussell** [comment]
You could use a "caller blocks" policy when the executor queue is full.

Since you are using 0.10.1.0 (which includes [KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread)) this won't cause a rebalance, as long as you set the `max.poll.interval.ms` to a suitable value. You should read the KIP for more information.

Spring Integration provides an implementation of [CallerBlocksPolicy](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/util/CallerBlocksPolicy.java).

**Comment by garyrussell** [comment]
If you partition your data, you could avoid handing off to an executor altogether, and let the container manage the concurrency for you.

**Comment by girish-1234** [comment]
Did you mean that , I can configure the concurrency in Spring Kafka configuration?
SO whenever message flows through listener, the container itself spawns thread for processing message received in that listener?

**Comment by artembilan** [comment]
The current version still supports `pause/resume` by default. And there is still that `listenerTaskExexutor`.

I don't see reason in your own logic on the matter.
Just try it as is out-of-the-box!

Also pay attention to the `queueDepth` option.

Read the `ContainerProperties` JavaDocs for more information.

**Comment by garyrussell** [comment]
If your topic has at exactly 100 partitions, and you set the concurrency to 100, you will get one thread per partition. The container concurrency should (normally) be an exact multiple of the number of partitions, so they are distributed evenly.

**Comment by garyrussell** [comment]
>The current version still supports pause/resume by default.

Right, but only if he blocks the listener thread.

**Comment by artembilan** [comment]
Right, that's why I said no reason in that custom thread pool if the listener container can handle it for you.

**Comment by garyrussell** [comment]
>Right, that's why I said no reason in that custom thread pool if the listener container can handle it for you.

But he needs concurrency; hence the best solution is to let the container manage it.

**Comment by garyrussell** [comment]
Another downside of using a thread pool within the listener is the possibility (probability) of message loss.

**Comment by 359557728** [comment]
you can use thread sleep in your messageListerner method, which will cause the message number of each poll larger, pay attention,do not sleep too long which may cause partition rebalance.

**Comment by 359557728** [comment]
When you use thread sleep in your method, by default it will cause the consumer used by the message Listener container paused, after the message proceeded, the consumer will resume message polling.

**Comment by 359557728** [comment]
you can use thread sleep in your messageListerner method, which will cause the message number of each poll larger, pay attention,do not sleep too long which may cause partition rebalance.

**Comment by artembilan** [comment]
@garyrussell already suggested `CallerBlocksPolicy` form Spring Integration. That is how you won't need any logic in your code and pause will be performed automatically.

This is already too long story and its subject goes out of the issue in the Framework scope.
This is more like custom project support request. We handle here on GH only bugs and feature requests everything rest is up to community forums where you can meet more people with more wider vision. Moreover we might not be available to answer all your questions here.

Consider to close this issue, please.

Thanks for understanding.

**Comment by girish-1234** [comment]
I tried below option for thread pool in kafka configuration itself, but it didn't spin new thread (thread from the consumerTaskExecutor) for each received message in the listener. We can process message async. 

```
 factory.setConsumerFactory(consumerFactory());
factory.getContainerProperties().setConsumerTaskExecutor(consumerTaskExecutor);  // This taskexecutor has thread pool size 150 and CallerBlocksPolicy set.
```
I thought it would use this threadpool to process message received in messageListener, but its not happening. It uses only one thread.   Your help will be greatly appreciated.

**Comment by artembilan** [comment]
That's not going to happen in the `KafkaListenerContainer`, @girish-1234 .

See our comments. The single listener really works in a single thread. For ordered processing.

The option `CallerRunsPolicy` should be applied to your own thread pool in the target listener.
The `consumerTaskExecutor` is left without effects: one listener - one thread from the configured pool in the container.

**Comment by garyrussell** [comment]
As we said above; to achieve concurrency, you need to create partitions and set the container concurrency to use the number of threads you need.

**Comment by girish-1234** [comment]
Thank you so much for the details. Currently we do not have option to create more partitions. So i would include below CallerRunsPolicy for my own thread pool. I hope below code will make use of caller thread, if the configured thread pool does not have thread available and blocking queue has also no space. I hope this will stop rejectedexecution exception.

```
public class MyRejectedExecutionHandler extends CallerRunsPolicy{
    public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
        // Add your code to log Runnable details.
        super.rejectedExecution(r, executor);
    }

}
```

**Comment by garyrussell** [comment]
It is weird to use Kafka without partitions; if you don't mind the possibility of losing messages you can hand off to a thread pool.

**Comment by sankarge** [comment]
My use case: "single kafka partition + parallel offline processing + block consumer thread if certain parallelism limit is reached"

`executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());`

This way, the messages are safe with kafka if the queue is full.
