### ISSUE TITLE
Add KafkaAdmin

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#388]
- auto declare `NewTopic`s defined in the application context
- see [KIP-117](https://cwiki.apache.org/confluence/display/KAFKA/KIP-117%3A+Add+a+public+AdminClient+API+for+Kafka+admin+operations)

**Comment by artembilan** [comment]
Reopen because of: https://github.com/spring-projects/spring-kafka/pull/389#discussion_r132443329

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/pull/393
