### ISSUE TITLE
Add api to accesss consumer metrics

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-kafka#401]
Currently I can get the metrics for a kafka publisher via `KafkaOperations#metrics()`, but there is no way to access the metrics for consumer(s) created in `KafkaMessageListenerContainer`.

Or there is a way to can access the Consumer directly to work around this?

**Comment by garyrussell** [comment]
The upcoming 2.0 release adds [consumer-aware message listeners](https://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/html/_reference.html#message-listeners); giving you access to the `Consumer`. There is also the new [`ConsumerAwareRebalanceListener`](https://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/html/_reference.html#rebalance-listeners).

**Comment by tsachev** [comment]
@garyrussell thanks for the heads up on the new interfaces.
Those interfaces might work, but if I use the consumer to just to get the metrics from a reporting thread I will need to store them locally. What if the consumer is closed? I will probably need to know that in order to clean my local consumers.

It would be better if there is an API to access the metrics directly. I created #402 with initial proposal that allows me to autowire `KafkaListenerEndpointRegistry` and then get the `MessageListenerContainer`s and access the metrics for underlying consumer(s).


```
@Bean
.... (KafkaListenerEndpointRegistry registry) {
  registry.getListenerContainers().forEach(c -> {
    c.metrics();
  });
}

```

**Comment by garyrussell** [comment]
I haven't looked at the API for metrics; most `Consumer` methods can only be called on the consumer thread itself so that might not be safe. If that's the case; retrieval of the metrics would have to be delegated to that thread and retrieved later.

**Comment by tsachev** [comment]
This is not the case for metrics they are always available (even after close).

**Comment by garyrussell** [comment]
Good to know; thanks.
