### ISSUE TITLE
InferredType determination not working if using @KafkaHandler annotation and StringJsonMessageConverter

### ISSUE THREAD

**Issue by SteluHH** [spring-projects/spring-kafka#407]
Hi,

I noticed a strange behaviour. 
When using a `StringJsonMessageConverter` the Payload Class Type cannot determined because the passed `Method` constructor param is null in `MessagingMessageListenerAdapter`. Therefore the field `inferredType` stays null and the fallback `java.lang.Object` is used which yields to erronous `HashMap` conversion of my JSON object. 

This is only related to usage of `@KafkaListener` class annotation with `@KafkaHandler` method annotation. Another test where I use a `@KafkaListener` annotation directly the Payload is converted to TestEvent correctly:

    @KafkaListener(topics = "product", groupId = KafkaEventConsumerRegistry.KAFKA_GROUP_ID)
    public void handleEvent(@Payload TestEvent event) {
        LOGGER.error(LogMarker.KAFKA, "Event: " + event.getTest()); // Works
    }

    @KafkaListener(topics = KafkaEventPublisher.ORDER_TOPIC, groupId = KafkaEventConsumerRegistry.KAFKA_GROUP_ID)
    public class KafkaEventListener {

        @KafkaHandler
        public void listenTo(@Payload KafkaEvent event) throws Exception {
            LOGGER.error(LogMarker.KAFKA, "Event: " + event); // ClassCastException, cannot convert HashMap to KafkaEvent
        }
    }

I guess this should work also for the combined annotation variant.
For now I will change my code to use only `@KafkaListener` annotation.

**Comment by artembilan** [comment]
The `inferredType` is for the conversion the incoming `payload` to the target argument type.

The `@KafkaHandler` approach is exactly for opposite situation: when we have a `payload` already, but would like to select the proper method:
```
 * <p><b>It is important to understand that when a message arrives, the method selection
 * depends on the payload type. The type is matched with a single non-annotated parameter,
 * or one that is annotated with {@code @Payload}.
 * There must be no ambiguity - the system
 * must be able to select exactly one method based on the payload type.</b>
```
If we would use inferring algorithm here as well, we would end up with some conflicts.
We need exact argument type here to select the target method before invoking it.

**Comment by artembilan** [comment]
Closed as `Works as Designed`.

**Comment by garyrussell** [comment]
We have the following note in the Rabbit docs...

>This type inference can only be achieved when the @RabbitListener annotation is declared at the method level. With class-level @RabbitListener, the converted type is used to select which @RabbitHandler method to invoke. For this reason, the infrastructure provides the targetObject message property which can be used by a custom converter to determine the type.

We should add a similar note in the kafka docs.
