### ISSUE TITLE
Sonar Build Broken Since #22 Was Merged

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#41]
#22 

https://build.spring.io/browse/SK-SON-7

    org.gradle.execution.TaskSelectionException: Task 'sonarRunner' not found in root project 'spring-kafka-dist'.

**Comment by artembilan** [comment]
OK. That's great!

Will keep in mind.
I'm upgrading SI to Gradle 2.12 right now, so this will be affected there as well.

**Comment by artembilan** [comment]
Fixed.
See: https://build.spring.io/browse/SK-SON-9
