### ISSUE TITLE
Topics created automatically?

### ISSUE THREAD

**Issue by radarsh** [spring-projects/spring-kafka#419]
I use the `KafkaListener` annotation to consume messages from Kafka. But what I find strange is that the topic I have configured is always automatically created after starting my Spring Boot app. Is this normal? I was hoping that I will have control over this automatic topic creation.

**Comment by artembilan** [comment]
That's true by default:

```
auto.create.topics.enable | Enable auto creation of topic on the server | boolean | true |   | high
```

See Apache Kafka documentation.

There is nothing what we can do from Spring Kafka perspective. This is exactly Broker option.
