### ISSUE TITLE
Spring Kafka, log4j 1.2.16 -> build problem.

### ISSUE THREAD

**Issue by luchob** [spring-projects/spring-kafka#422]
Hi, guys! I'm not sure that this is a bug but as you know (see also [#278](https://github.com/spring-projects/spring-kafka/issues/278)) spring-kafka has dependency to log4j 1, namely to `log4j:log4j:1.2.16`. Details:

```
+--- org.springframework.kafka:spring-kafka-test: -> 2.0.0.M3
|    +--- org.springframework:spring-context:5.0.0.RC3 (*)
|    +--- org.springframework:spring-test:5.0.0.RC3 (*)
|    +--- org.springframework.retry:spring-retry:1.2.0.RELEASE -> 1.2.1.RELEASE (*)
|    +--- org.apache.kafka:kafka-clients:0.11.0.0 (*)
|    +--- org.apache.kafka:kafka_2.11:0.11.0.0
|    |    +--- org.apache.kafka:kafka-clients:0.11.0.0 (*)
|    |    +--- net.sf.jopt-simple:jopt-simple:5.0.3
|    |    +--- com.yammer.metrics:metrics-core:2.2.0
|    |    |    \--- org.slf4j:slf4j-api:1.7.2 -> 1.7.25
|    |    +--- org.scala-lang:scala-library:2.11.11
|    |    +--- com.101tec:zkclient:0.10
|    |    |    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    |    |    \--- org.apache.zookeeper:zookeeper:3.4.8 -> 3.4.10
|    |    |         +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    |    |         \--- log4j:log4j:1.2.16
```
The problem is though that there is a bug in the POM file of log4j 1.2.16 - see [dependency-management-plugin #59](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/59). We are running into an identical problem in our build:

```
:compileTestJava
Errors occurred while build effective model from /Users/***/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.16/88efb1b8d3d993fe339e9e2b201c75eed57d4c65/log4j-1.2.16.pom:
    'build.plugins.plugin[io.spring.gradle.dependencymanagement.org.apache.maven.plugins:maven-antrun-plugin].dependencies.dependency.scope' for junit:junit:jar must be one of [compile, runtime, system] but is 'test'. in log4j:log4j:1.2.16
```

Please advise what would be the preferred way to resolve this... Spring boot dependencies describe dependency to log4j 2.

**Comment by garyrussell** [comment]
It's known problem; we've been trying to get them to remove the dependency, but not getting much traction; log4j is end of life.

You need to add your voice [here](https://issues.apache.org/jira/browse/KAFKA-1044).

**Comment by garyrussell** [comment]
You could try excluding log4j2 from boot but I don't know if it will work.

**Comment by luchob** [comment]
I do not think that this is necessary to exclude log4j2- isn't it better that we specify 1.2.17 for log4j1?

**Comment by garyrussell** [comment]
I don't know - you might end up with multiple SLF4J bindings; try it.

**Comment by garyrussell** [comment]
You might also have to add the standard commons-logging jar; Spring 5 has a trimmed-down version that doesn't support log4j.

It's a bit of a mess - that's why the proper fix is for Kafka to remove the dependency.

**Comment by luchob** [comment]
Gary, I've added my voice.

If we specify the version the whole thing is unlikely to work worse than before :-) , is it?

```
testCompile('org.springframework.kafka:spring-kafka-test')
testCompile('log4j:log4j:1.2.17')
```

The error disappeared because of the default gradle resolution strategy:

```
log4j:log4j:1.2.16 -> 1.2.17
```
There are no additional bindings, I can't see such at least:

```
|    |    |    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    |    |    \--- org.apache.zookeeper:zookeeper:3.4.8 -> 3.4.10
|    |    |         +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    |    |         \--- log4j:log4j:1.2.16 -> 1.2.17
```

**Comment by artembilan** [comment]
Closed with the solution described above.

Not a Spring Kafka issue though...

**Comment by workplaylifecycle** [comment]
> testCompile('org.springframework.kafka:spring-kafka-test')
> testCompile('log4j:log4j:1.2.17')

@luchob I'm sorry, no gradle experience, where do we put this in build.gradle ?

**Comment by luchob** [comment]
@workplaylifecycle in the dependencies section.

```
dependencies {
    .....
}
```

**Comment by nvo-clgx** [comment]
it does not work for . me. log4j:1.2.16 still show up

**Comment by garyrussell** [comment]
@nvo-clgx Please don't comment on old closed issues; if you believe there is still a problem, open a new issue with many more details - pom, build.gradle and dependency tree information.
