### ISSUE TITLE
Producer does not handle broker leader change

### ISSUE THREAD

**Issue by TimShi** [spring-projects/spring-kafka#429]
When broker leader changes, we expect KafkaTemplate's producer to be able to find the new broker leaders.

Actual behaviour, it seems KafkaTemplate uses cached producer which has outdated meta data for brokers. And we see the following exception:

```
2017-09-14 10:16:17.896 ERROR 1 --- [d | producer-10] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='.....' to topic MY_TOPIC:
org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.
```

**Comment by artembilan** [comment]
Any bad symptoms in your application?
Doesn't that assume the `KafkaProducer` will retry to the proper Broker?

Any ideas how to proceed? 
I can't find the answer for the `NotLeaderForPartitionException` reaction in the Google.
Let's figure out together how to proceed!

Thank you for the report!

**Comment by TimShi** [comment]
Looked into Apache's KafkaProducer, and it seems like this is handled there. i.e. org.apache.kafka.clients.producer.internals.Sender class is "The background thread that handles the sending of produce requests to the Kafka cluster. This thread makes metadata requests to renew its view of the cluster and then sends produce requests to the appropriate nodes."

We are investigating if broker leader election actually failed on the Kafka cluster side and find out how we can reproduce this case.

**Comment by artembilan** [comment]
@TimShi , any new so far, please?

**Comment by TimShi** [comment]
Sorry, it turned out to be a bug in our code. Closing this issue.

**Comment by emedina** [comment]
@TimShi We are experiencing a similar issue. Could you please share what your bug in code was to determine whether that could also be the reason for us?

Thanks.

**Comment by deargopinath** [comment]
Specifying 'retries config' value in the producer configuration will help.
In addition to specifying the 3 usual configuration parameters - 'brokers-list', 'key-serializer' and 'value-serializer', it is good practice to specify the 4th parameter - 'retries-config'.

Example:
@Bean
public KafkaTemplate<String, String> kafkaTemplate(String bootstrapServers) {

Map<String, Object> producerConfigs = new HashMap<>();

// The usual 3 parameters that are sufficient to start kafka producer
producerConfigs.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
producerConfigs.put( ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
producerConfigs.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);

// The useful 4th parameter that helps avert **'this broker is not a leader for that partition'**  problems
producerConfigs.put(ProducerConfig.RETRIES_CONFIG, 10);

ProducerFactory<String, String> producerFactory = 
          new DefaultKafkaProducerFactory<>producerConfigs);
KafkaTemplate<String, String> kafkaTemplate = new KafkaTemplate<>(producerFactory);
kafkaTemplate.setDefaultTopic(kafkaTopic);
return kafkaTemplate;
}

**Comment by artembilan** [comment]
Gentlemen!

How has it turned that you come here into Spring project with the native Apache Kafka problem?
The point is that we don't support it here.
So, please, respect our time to develop and support exactly Spring API.

The StackOverflow is a good place to start with such a question. If we (Spring team) know what to do, we will answer there if the problem is really not about Spring.
But that's definitely going to be a better practice to raise issues in the project exactly in context of this project. The code we don't manage can't be changed from this project.

Thanks for understanding.
