### ISSUE TITLE
A way to access the current offset of a consumer

### ISSUE THREAD

**Issue by ahmedlafta** [spring-projects/spring-kafka#431]
Current version i am using: **1.1.x**

Currently, the only way to get the current offset of a topic-partition is by implementing ```ConsumerSeekAware``` and receiving an idle container event via ```ConsumerSeekAware#onIdleContainer```, and accessing the assignments.

```
/**
 * If the container is configured to emit idle container events, this method is called
 * when the container idle event is emitted - allowing a seek operation.
 * @param assignments the new assignments and their current offsets.
 * @param callback the callback to perform a seek.
 */
 void onIdleContainer(Map<TopicPartition, Long> assignments, ConsumerSeekCallback callback);
```
https://docs.spring.io/spring-kafka/reference/htmlsingle/#_current_positions_when_idle

It would be helpful to provide a method directly on the ```KafkaMessageListenerContainer``` to access the topic-partition offsets on demand rather than on partitions assigned (or idle events), similar to the approach of https://github.com/spring-projects/spring-kafka/pull/402. This method would simply take advantage of ```position(TopicPartition)``` on the apache kafka ```Consumer```.

Reason for this request: When implementing an ```AlwaysRetryPolicy```, the container can continually receive the same message that causes an error, making it not idle. Since the container is no longer idle but the offset is not moving, it can be difficult to detect that the consumer is stuck. Having this would allow someone to track the offset and perform some action if the offset hasn't increased.

I've been digging through the issues looking for a duplicate of this request but haven't seen any specific to this, so apologies if it's been requested before. Thanks!

**Comment by artembilan** [comment]
Starting with version `2.0` there is `ConsumerAwareMessageListener` to consider on the matter: https://docs.spring.io/spring-kafka/docs/2.0.0.RC1/reference/html/_reference.html#message-listeners

And `@KafkaListener` method can be supplied with the `Consumer<?, ?>` argument:
```
@KafkaListener(id = "qux", topics = "annotated4", containerFactory = "kafkaManualAckListenerContainerFactory",
				containerGroup = "quxGroup")
public void listen4(@Payload String foo, Acknowledgment ack, Consumer<?, ?> consumer) {
```

Let us know if that is OK with you.

Right, there is nothing to do with that in the previous versions.
But I think your idea about `KafkaMessageListenerContainer.position(TopicPartition)` API makes sense.

@garyrussell , WDYT?

**Comment by ahmedlafta** [comment]
Thanks for the quick response @artembilan!

The ```@KafkaListener``` approach would definitely work. My current thought is I'd like to have some class, separate from the ```@KafkaListener``` method's class, to have access to and monitor the offsets. Using the ```@KafkaListener``` approach doesn't really support that. Having the offsets available via the listener container follows the approach of the ```metrics``` API I have referenced above.

To expand on the API, it could look something like:

```
public Map<TopicPartition, Long> positions()
```

**Comment by artembilan** [comment]
Well, I'm afraid we can't provide such an API on the `Container` level, since `KafkaConsumer.position()` is one of those methods which can be called only from a single thread:
```
public long position(TopicPartition partition) {
        acquire();
...
    /**
     * Acquire the light lock protecting this consumer from multi-threaded access. Instead of blocking
     * when the lock is not available, however, we just throw an exception (since multi-threaded usage is not
     * supported).
     * @throws IllegalStateException if the consumer has been closed
     * @throws ConcurrentModificationException if another thread already has the lock
     */
    private void acquire() {
        ensureNotClosed();
        long threadId = Thread.currentThread().getId();
        if (threadId != currentThread.get() && !currentThread.compareAndSet(NO_CURRENT_THREAD, threadId))
            throw new ConcurrentModificationException("KafkaConsumer is not safe for multi-threaded access");
        refcount.incrementAndGet();
    }
```

That's how the `ConsumerAwareMessageListener` is better solution since we don't call any other consumer operations during listener process, therefore that `KafkaConsumer` is free for calling from the end-user code.

Does it make sense to you?

**Comment by ahmedlafta** [comment]
Hi @artembilan 

Yeah I noticed this the other day when attempting to implement this locally. I couldn't think of any good clean approaches to get around the issue. Using ```ConsumerAwareMessageListener``` makes sense and will work for me when I upgrade to that version.

Thanks for the analysis and the feedback!
