### ISSUE TITLE
Not able to find a way to override ConsumerRebalanceListener method

### ISSUE THREAD

**Issue by sbogadhi** [spring-projects/spring-kafka#432]
Spring-cloud-dependencies version : Camden.SR6
Spring Kafka version : 1.0.5.RELEASE

Trying to override the setConsumerRebalanceListener method of the AbstractMessageListenerContainer with custom ConsumerRebalanceListener object but not able to find a way.

**Comment by garyrussell** [comment]
Are you talking about direct usage of spring-kafka (this project) or the use of spring-kafka by Spring Cloud Stream?

For the former, you set the rebalance listener in the `ContainerProperties`.

For spring cloud stream; the container is not currently exposed as a bean so such customization is not currently possible; we are reworking Stream in 2.0 to make this possible.

**Comment by sbogadhi** [comment]
Thanks Gary for the response. 
I am using the Spring cloud stream 1.1.2 RELEASE and was not able to configure the rebalance listener. 
Anyway i find a solution how to configure rebalance listener using spring-kafka in the same project.
