### ISSUE TITLE
2.0.0RC1 Lambda expression and spring incompatibility 

### ISSUE THREAD

**Issue by aeolus811tw** [spring-projects/spring-kafka#434]
On this particular commit: 8d1eba7

The abuse of lambda function for the file: MessagingMessageListenerAdapter.java
```
+		Assert.state(!this.isConsumerRecordList || validParametersForBatch,
 +				() -> String.format(stateMessage, "ConsumerRecord"));
 +		Assert.state(!this.isMessageList || validParametersForBatch,
 +				() -> String.format(stateMessage, "Message<?>"));
```

is causing runtime error on 2.0.0RC1 because Java will convert this lambda into function Supplier class that does not work with Spring's Assert.state method.

If anyone was to use @KafkaListener annotation on anything,

the following error will be thrown:

```
 java.lang.NoSuchMethodError: org.springframework.util.Assert.state(ZLjava/util/function/Supplier;)V
 	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.determineInferredType(MessagingMessageListenerAdapter.java:396)
```

Recommend fix: remove the lambda and use String.format directly.

**Comment by garyrussell** [comment]
As [stated here](https://docs.spring.io/spring-kafka/docs/2.0.0.RC1/reference/html/_introduction.html#compatibility) 2.0.0.RC1 requires Spring Framework 5.0.x (currently RC4) which *does* have that form of `Assert.state()`...

[Javadocs here](https://docs.spring.io/spring-framework/docs/5.0.0.RC4/javadoc-api/org/springframework/util/Assert.html#state-boolean-java.util.function.Supplier-).

```java
	/**
	 * Assert a boolean expression, throwing an {@code IllegalStateException}
	 * if the expression evaluates to {@code false}.
	 * <p>Call {@link #isTrue} if you wish to throw an {@code IllegalArgumentException}
	 * on an assertion failure.
	 * <pre class="code">
	 * Assert.state(id == null,
	 *     () -&gt; "ID for " + entity.getName() + " must not already be initialized");
	 * </pre>
	 * @param expression a boolean expression
	 * @param messageSupplier a supplier for the exception message to use if the
	 * assertion fails
	 * @throws IllegalStateException if {@code expression} is {@code false}
	 * @since 5.0
	 */
	public static void state(boolean expression, Supplier<String> messageSupplier) {
		if (!expression) {
			throw new IllegalStateException(nullSafeGet(messageSupplier));
		}
	}
```

Using a lambda is much more efficient than building a string and discarding it if the state is asserted.

**Comment by garyrussell** [comment]
Use 1.3.0.RC1 with Spring Framework 4.3.x.
