### ISSUE TITLE
re consume message after kafka broker restart

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-kafka#435]
i use 
`./kafka-consumer-groups.sh --new-consumer --bootstrap-server 10.10.3.80:9092 --describe --group message-center-consumer-1` 
i found 
![image](https://user-images.githubusercontent.com/1763935/30901068-fb2fb090-a398-11e7-8e03-a58342a5694b.png)
what the mean of 3 and 4 topic ?
and when we restart kafka broker , consumer will re consume message from 238 offset
why current offset was 337，and i receive 238 offset by kafka broker restart？
i use kafka auto commit is true(default) and auto commit interval ms is 5000 (default)

i use kafka broker is 0.11.0 and spring-kafka 1.1.6  and springboot 1.5.7

my question like 
https://stackoverflow.com/questions/45810636/solved-kafka-0-11-0-0-keeps-reseting-offset-on-restart

but i don't know how to solve

**Comment by artembilan** [comment]
We don't use GutHub for questions support. The StackOverflow is good place for that. Here is your question: https://stackoverflow.com/questions/46445480/re-consume-message-after-kafka-broker-restart.

You're free to open feature request or bug report. Right, it maybe as a result of StackOverflow discussion, but not in parallel. The problem with that the same poeple (we) are in help for you here and there.

**Comment by dragontree101** [comment]
sorry,  i question to stackoverflow.
