### ISSUE TITLE
Is it ok to call AbstractMessageListenerContainer#stop() multiple times?

### ISSUE THREAD

**Issue by mats990** [spring-projects/spring-kafka#439]
I'm looking at implementations of this class and it seems to me that both implementations are safe to call multiple times.
https://github.com/spring-projects/spring-kafka/blob/a9fc8336191eeff56bbb474edd6e673e948db2e0/spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java#L174
https://github.com/spring-projects/spring-kafka/blob/a9fc8336191eeff56bbb474edd6e673e948db2e0/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L215

If we call AbstractMessageListenerContainer#stop() once it will stop containers, but if we call it second time(or multiple times) it will wait until timeout (10 sec by default).

Should this be considered as a bug?

**Comment by garyrussell** [comment]
Yes; this is a bug; the second (and subsequent) `stop()` should exit immediately.
