### ISSUE TITLE
application.properties config used even if different file specified

### ISSUE THREAD

**Issue by SteluHH** [spring-projects/spring-kafka#450]
Hi,
I noticed that when I run our Spring Boot application with command line argument to change the application.properties to be used (e. g. out of eclipse), Spring Kafka anyhow fetches Kafka properties from default application.properties. 

`--spring.config.location=classpath:application-dev.properties`

This is unwanted behaviour from my perspective, I do not want to have the default application.properties to be parsed at all if above program argument is used.
I don't know if I am right with that here, or if its more a Spring Boot related issue. However for Kafka I managed to reproduce the issue only. 

2.0.0.RC1

**Comment by artembilan** [comment]
Any chance to have that Spring Boot application to play from our side?
Although I can't imagine what may be wrong here in Spring Kafka. That is indeed something related to Boot or your application finally.

**Comment by garyrussell** [comment]
Spring Kafka has no knowledge that it is running in a boot application.

Also, please note that [2.0.0.RELEASE is now available](https://spring.io/blog/2017/10/02/spring-for-apache-kafka-2-0-ga-available).

**Comment by SteluHH** [comment]
Hi together,

thanks for the hint. Turns out I got the `spring.config.location` property wrong. It is a merge rather than a replacement for application.properties. Opened up [a thread](https://github.com/spring-projects/spring-boot/issues/10595) in Spring Boot project to ask for clarification :)

This one here can be closed I guess.

**Comment by garyrussell** [comment]
Thanks for the update.
