### ISSUE TITLE
Add Consumer Lag Mechanism to KafkaAdmin

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#456]
Interesting technique [here](https://stackoverflow.com/questions/42201616/how-to-get-kafka-consume-lag-in-java-program/46458377#46458377). 

Uses a dummy consumer `seekToEnd` to find the extent of the topic/partition.

Add something like `KafkaAdmin.getPartitionExtents(String topic)` to return the extents.

The listener containers could then expose a method and/or MBean to calculate the current lags.

**Comment by ericbottard** [comment]
Needs to be _per group_

**Comment by garyrussell** [comment]
Each container is assigned a group, so that would be why the container has to calculate the lag (only the container knows the current position for its group).

**Comment by artembilan** [comment]
Looks like this can be achieved now via `MessageListenerContainer.metrics()` - #401 and: https://docs.confluent.io/current/kafka/monitoring.html#new-consumer-metrics.

I consider this a fixed, but feel free to do whatever you think is better.
