### ISSUE TITLE
Concurrency setting is not reflected in number of container consumer and listener threads

### ISSUE THREAD

**Issue by yvch1289** [spring-projects/spring-kafka#457]
Hi, 

using spring kafka 1.1.1 with kafka 0.10.2. 
We observe that the concurrency set into the concurrentMessageListenerContainer is not yielding the expected threading, neither at the kafka client level, nor in the spring kafka listener & consumer threads: 
Test: 
We have a consumer group subscribing  to 2 topics with 5 partitions each, so 10 partitions in total. 
The concurrency is set to 128 in spring kafka (we are testing thread to partition allocation, that is why we wanted to have a higher concurrency than partitions).

-THe kafka consumer-group describe command shows that only 5 consumers are allocated to the partitions, with 2 partitions each. 
-calling dumpallthread() on the Threading JMX MBean of the java process, we see 90+ spring kafka bean consumer threads, and only 5 bean listener threads. 

The documentation specifies that kafka client number of consumer is defined by the concurrency setting of spring kafka, up until the number of partitions. This is not the case here. 
This also implies that the desired parallelism both in kafka client AND in spring kafka for listeners is not achievable ( here we would expect according to spec 10 kafka client consumers, 10 spring kafka bean consumer threads, and 10 listener threads). 

Dodge

**Comment by garyrussell** [comment]
Concurrency must be <= to the number of partitions.

Only one consumer can consume from a partition at a time - that is the way Kafka works.

A rebalance occurs whenever a new client connects. 

When a listener container is configured to listen to multiple topics, each `Consumer` subscribes to all topics; hence the actual number of consumer threads is limited to the the largest number of partitions. Kafka allocates the partitions across the consumers.

For your use case, if you want a consumer per topic/partition, you need to use 2 separate containers, each subscribing to a single topic.

**Comment by garyrussell** [comment]
With the 0.10.2 client, you should be using spring-kafka 1.2.2 - see the [matrix at the bottom of the project page](http://projects.spring.io/spring-kafka/).

**Comment by yvch1289** [comment]
Hi Gary, 
thanks for your explanations. 
From the doc, it said that whenever a higher number for concurrency than number of partitions is set, it scales down concurrency, listener threads, consumers to number of partitions. But your explanation goes deeper. 

We didnt explicitly configured our listener to listen to multiple topic (we had two topics), but counted on the concurrency to scale down to number of partitions as mentioned above. 
So now we learn from you that when the consumer group listen to several topics, implicitly the number of consumers is maxing at the number corresponding to the topic with the highest number of partitions.

So now, in our test cases, we see, for concurrency 128, 128 spring kafka consumer threads, 5 listener threads, and 5 kafka client consumer. It seems listener threads number mirrors the number of kafka consumer, but not for spring kafka consumer threads. Is that normal?

Also the fact that there is 5 kafka consumers for 10 partition (reason that you gave above), does it impede parallelism? for one such consumer that handles 2 partition, does it fetch message from both partitions "simultaneously", and hand them to spring kafka parallelly, or is it round robin like one partition after the other down to the spring kafka listener execution?

Regards
Dodge

**Comment by garyrussell** [comment]
We only launch a listener thread when kafka allocates the consumer a (or more) partitions.

In 1.3.x, the listener threads don't exist any more, the listener is invoked on the consumer thread due to some improvements in the Kafka client.

It make no sense to set the container concurrency to > the max number of partitions on the configured topics.

Kafka returns records for all subscribed topics/partitions. If you limit the number of records per poll, you might only get records from one partition at a time; but that is up to the kafka broker itself; I am not intimately familiar with its internals; that would be a question for the kafka folks. I suggest you experiment too.

When we get a set of records, we call the listener one at a time (when using a normal listener) or with the whole batch when using a batch listener.

**Comment by yvch1289** [comment]
I mean also with the latest question: if we have multiple topics subscription with varying number of partitions (some 6, some 64), we can spawn 64 consumers at max. this will spawn 64 spring kafka with some consumers handling several partitions from different topics. Does this setup is partition ordering compliant with spring kafka?
thanks

**Comment by garyrussell** [comment]
If you have such a complicated scenario, I would recommend using a container-per topic.

We launch consumer threads based on the concurrency setting. How Kafka determines which consumers will get which partitions is a question for the Kafka folks but, in my experience, if you have enough consumers, each will get one partition (up to the partitions). I have no comment/observation on how the partitions will be distributed if you listen to multiple topics; I don't know, for example, if you have 128 consumers and two topics, each with 64 partitions, how Kafka will distribute those; I somehow doubt you'll get 128 consumers each with one partition, but I could be wrong - experiment and/or ask the Kafka guys. But, like I said, for an environment like that, I would suggest using a container for each topic, each with 64 concurrency - that way you will get your desired distribution.

There is no difference between 1.3 and earlier with how the partitions are distributed; the only difference is there is no second thread started when partitions are allocated to a consumer.

**Comment by yvch1289** [comment]
we have spoken with the kafka folks: There are 2 out of the box strategies for consumer 2 partition allocation : round robin and range. However what we observed is not matching: with multiple topics of varying partition size (max 64) and 64 consumers, we got 3 consumers  with no partition allocation. 
Do you know which Consumer Assignor implementation you use by default? 
Finally, we would like to use spring config and @refreshscope on the concurrency setting, to spawn new or remove existing consumers on the fly. Kafka client supports runtime change of consumer numbers, but does spring kafka via the concurrency setting?
Thanks

**Comment by garyrussell** [comment]
>Do you know which Consumer Assignor implementation you use by default?

Whatever Kafka defaults to.

>but does spring kafka via the concurrency setting

No, except by `stop()` ing the container, changing the concurrency and `start()`ing again.

**Comment by tomaszszlek** [comment]
Hi, this topic is closed already but I have update that could be useful for people reading this conversation.
I have KafkaConsumer subscribing to multiple topics (via topic pattern). Each topic have only 1 partition.
It looks like if I have multiple Kafka Listener containers (so concurrency > number of partitions) then each Consumer is assigned to some topic (of course if number of topics >= concurrency). I am using Spring Kafka 2.1 with Kafka client 2.0.

**Comment by artembilan** [comment]
That's correct. That's how it works in a single `ConcurrentMessageListenerContainer`: the partitions are distributed between child `KafkaMessageListenerContainer`s according provided concurrency or by the native Apache Kafka rebalance mechanism because all those consumers are in the same group:
```
for (int i = 0; i < this.concurrency; i++) {
				KafkaMessageListenerContainer<K, V> container;
				if (topicPartitions == null) {
					container = new KafkaMessageListenerContainer<>(this, this.consumerFactory,
							containerProperties);
				}
				else {
					container = new KafkaMessageListenerContainer<>(this, this.consumerFactory,
							containerProperties, partitionSubset(containerProperties, i));
				}
				String beanName = getBeanName();
				container.setBeanName((beanName != null ? beanName : "consumer") + "-" + i);
				if (getApplicationEventPublisher() != null) {
					container.setApplicationEventPublisher(getApplicationEventPublisher());
				}
				container.setClientIdSuffix("-" + i);
				container.setAfterRollbackProcessor(getAfterRollbackProcessor());
				container.start();
				this.containers.add(container);
			}
```
