### ISSUE TITLE
multiple KStreamBuilderFactoryBean for multiple KStream instances not working

### ISSUE THREAD

**Issue by chanakyamandava** [spring-projects/spring-kafka#465]
I am using two Kstreams and two different KStreamBuilderFactoryBean s to create them. I am having trouble managing executing the application. Each KStream is listening to a separate topic in same cluster and performs different operations. At a time only one will execute with [0_0] task and for other it says :
`The following subscribed topics are not assigned to any members in the group png-receiver : [my.other.topic]`

When I use the same KStreamBuilderFactoryBean to create both KStream s, everything works fine. Two tasks are being created [0+0] and [1_0] and running the KStream s. But I want to manage the lifecycle of each stream by different KStreamBuilderFactoryBean by creating endpoints to stop and start them.
Can anyone help me to resolve this issue.

**Comment by artembilan** [comment]
You have to share some application to play from our side, please.
Now it isn't clear what's going on.
Maybe the problem that you use the same `group.id` for both `KStreamBuilderFactoryBean`, therefore only one consumer can subscriber to the same topic. Etc. etc. etc. Hard to speculate without particular evidences.

Thanks

**Comment by chanakyamandava** [comment]
`Config class:

@Bean(name = KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME)
  public StreamsConfig kStreamsConfigs() {

    Map<String, Object> props = new HashMap<>();
    props.put(StreamsConfig.APPLICATION_ID_CONFIG, applicationName);
    props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, stringSerde.getClass().getName());
    props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, stringSerde.getClass().getName());
    props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG,
        streamsProperties.getBootstrapServersConfig());
    props.put(StreamsConfig.NUM_STREAM_THREADS_CONFIG, streamsProperties.getNumOfStreamThreads());
    props.put(StreamsConfig.DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG,
        WallclockTimestampExtractor.class.getName());
    return new StreamsConfig(props);
  }

  @Bean(name = "kStreamBuilderFactoryBean")
  public KStreamBuilderFactoryBean kStreamBuilderFactoryBean() {
    return new KStreamBuilderFactoryBean(kStreamsConfigs());
  }

  @Bean(name = "anotherkStreamBuilderFactoryBean")
  public KStreamBuilderFactoryBean anotherkStreamBuilderFactoryBean() {
    return new KStreamBuilderFactoryBean(kStreamsConfigs());
  }
  
  class 1:
  
  @Autowired
  @Qualifier("kStreamBuilderFactoryBean")
  private KStreamBuilderFactoryBean kStreamBuilderFactoryBean;
  
  @PostConstruct
  public void runStreamOne() {
      kStreamBuilderOne = kStreamBuilderFactoryBean.getObject();
      kStreamOne =
          kStreamBuilderOne.stream(stringSerde, stringSerde, "topic.one");
      kStreamOne.foreach((key, value) -> {
        log.info("The value in stream one is : {}", value);
      });
  }

  @EventListener(ContextRefreshedEvent.class)
  public void injectStreamOne() {
    if (!kStreamBuilderFactoryBean.isRunning()) {
      kStreamBuilderFactoryBean.start();
    }
    streamOne = kStreamBuilderFactoryBean.getKafkaStreams();
  }
  
  class 2:
  
  @Autowired
  @Qualifier("anotherkStreamBuilderFactoryBean")
  private KStreamBuilderFactoryBean anotherkStreamBuilderFactoryBean;
  
  @PostConstruct
  public void runStreamTwo() {
      kStreamBuilderTwo = anotherkStreamBuilderFactoryBean.getObject();
      kStreamTwo =
          kStreamBuilderTwo.stream(stringSerde, stringSerde, "topic.two");
      kStreamTwo.foreach((key, value) -> {
        log.info("The value in stream two is : {}", value);
      });
  }

  @EventListener(ContextRefreshedEvent.class)
  public void injectStreamTwo() {
    if (!anotherkStreamBuilderFactoryBean.isRunning()) {
      anotherkStreamBuilderFactoryBean.start();
    }
    streamTwo = anotherkStreamBuilderFactoryBean.getKafkaStreams();
  }`

This is pretty much my structure and I am using different endpoints to start and stop the streams.

Thanks!

**Comment by artembilan** [comment]
No, that's not enough.

Please, share the project somewhere on GitHub. Too many variables to guess the problem.
I need exact code to reproduce.

Thanks

**Comment by chanakyamandava** [comment]
https://github.com/chanakyamandava/kafka-streams-example

Here is the application code.

**Comment by artembilan** [comment]
Thanks.

Please, also explain what is the problem. What to expect as a good outcome and what is bad.
I somehow can't compile what "[0_0] task" means...

**Comment by artembilan** [comment]
I don't know what you are expecting from me to see there.
I have ran your application as is and I have this logs:
```
2017-11-02 14:12:04.365 DEBUG 8424 --- [  restartedMain] k.s.sample.consumer.StreamsListener1     : the state of streams1 after start: RUNNING
...
2017-11-02 14:12:04.481 DEBUG 8424 --- [  restartedMain] k.s.sample.consumer.StreamsListener2     : the state of streams2 after start: RUNNING
```
Thanks

**Comment by chanakyamandava** [comment]
when I create both the streams using the same builderbean, I am able to see both topics assigned to different tasks when the streams are started. But when I used two different KStreamBuilderFactoryBean s to create each stream, only one kstream is running and I am seeing a message that says one of the topics is not assigned to any task to initiate the stream. 

`The following subscribed topics are not assigned to any members in the group png-receiver : [two.test]`

I am expecting to see both the streams are assigned to a separate task that listens to the specified topic.

**Comment by artembilan** [comment]
OK. I think the problem is here:
```
props.put(StreamsConfig.APPLICATION_ID_CONFIG, "myKafkaStreamsApp");
```

See documentation:
```
public static final String APPLICATION_ID_CONFIG = "application.id";
    private static final String APPLICATION_ID_DOC = "An identifier for the stream processing application. Must be unique within the Kafka cluster. It is used as 1) the default client-id prefix, 2) the group-id for membership management, 3) the changelog topic prefix.";
```

Since with two separate `KStreamBuilderFactoryBean` we have two separate `KafkaStreams` instances. And according Apache Kafka "politics" it's abnormal.

I agree that it is sad do not have a proper exception on the matter, but I'm sure the broker somehow tries to merge them both and miss something during validation.

When I changed to this:
```
@Bean
  public KStreamBuilderFactoryBean anotherKStreamBuilderFactoryBean() {
    Map<String, Object> props = kStreamsConfigs().originals();
    props.put(StreamsConfig.APPLICATION_ID_CONFIG, "myKafkaStreamsApp2");
    return new KStreamBuilderFactoryBean(new StreamsConfig(props));
  }
```

It started to work for me and two different stream are able to consume message from their particular topics.

I'm pretty sure we can reach the same behavior with the raw Apache Kafka, even without any Spring, so I'd consider this as "Works as Designed" and move the problem to the Apache Kafka bug tracker. 

Does it make sense to you, @chanakyamandava ?

**Comment by chanakyamandava** [comment]
Thank you Bilan. This works for me, thank you for the clarification.

**Comment by artembilan** [comment]
Misconfiguration problem with shared `application.id`.
Not a Spring Kafka issue.
Closed
