### ISSUE TITLE
Backport transaction support to 1.3.x branch

### ISSUE THREAD

**Issue by miketzian** [spring-projects/spring-kafka#478]
Kafka transactions are in 2.0.x which requires spring 5.0 which I'm not able to upgrade to (yet).

Could the transaction support changes be merged back to 1.3.x ?

**Comment by artembilan** [comment]
Your concern isn't clear. The Kafka transactions support is indeed there: https://docs.spring.io/spring-kafka/docs/1.3.1.RELEASE/reference/html/_reference.html#transactions

Pay attention to the version.

**Comment by miketzian** [comment]
Ok thanks - will recheck; had been looking at https://github.com/spring-projects/spring-kafka/issues/362 and it seemed as though it was only 2.0+.

**Comment by miketzian** [comment]
Acknowledged, thanks!
