### ISSUE TITLE
Update Bean factories names according to changes released in kafka 1.0

### ISSUE THREAD

**Issue by neoXfire** [spring-projects/spring-kafka#479]
Factory names should be updated.
Details can be found [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-120%3A+Cleanup+Kafka+Streams+builder+API)

**Comment by artembilan** [comment]
That's not related and just opinion.
We can't change their names because we went GA already.
For better use-experience and less noise about broken backward compatibility I don't see reason to rename.

That's how Spring policy works.

So, now what are your arguments to rename anyway?
Thanks

**Comment by garyrussell** [comment]
2.1 uses the new kafka-clients class names `StreamBuilder` etc... https://github.com/spring-projects/spring-kafka/commit/67104ed1a580c43c00bb9a80e852010ed498c040#diff-0e61ae081c1980fe22d3ab684ff8373c

I see no compelling reason to rename the factory bean; but we have time before 2.1 goes GA next week.

Maybe just add a subclass to ease transition?

**Comment by artembilan** [comment]
I don't find such a rename (even through the new class with deprecation on this one) as valuable.

There are too much `Stream`s these days in the world. And when we rename it into just a `StreamBuilderFactoryBean` that will become a bit clumsy and make end-users nervous a bit with choosing a proper class from the IDE auto-suggestion.

So, I even would say that Apache Kafka was wrong to rename it to just a generic `StreamBuilder`.

Just IMO...

**Comment by neoXfire** [comment]
I was thinking about `StreamsBuilderFactoryBean` (plural) and not `StreamBuilderFactoryBean` (singular) to keep the convention `InstanceTypeFactoryBean`.
However I can agree with you when you say StreamBuilder is too overloaded nowadays. Maybe `KafkaStreamsBuilderFactoryBean` to avoid confusion from users with a "false convention" but it's a bit long.

@artembilan you made me smile when you said

> For better use-experience and less noise about broken backward compatibility I don't see reason to rename.
> That's how Spring policy works.

because you already chose to go from `public class KStreamBuilderFactoryBean extends AbstractFactoryBean<KStreamBuilder>` to `public class KStreamBuilderFactoryBean extends AbstractFactoryBean<StreamsBuilder>`.
Thus, all people using interfaces in return types, as in the [reference documentation example](https://docs.spring.io/spring-kafka/docs/2.1.0.RC1/reference/html/_reference.html#kafka-streams), will have their code broken. If you stay as it is, you should at least update the documentation I think.

**Comment by artembilan** [comment]
Ha! I see your point. Indeed that's already a breaking change 😉 

Well, I guess, we have to step back from here and really introduce a new `KafkaStreamsBuilderFactoryBean` and deprecate existing `KStreamBuilderFactoryBean` strongly based on the deprecate  `KStreamBuilder` . Just because it is point release and we can only deprecate, but can't remove/rename and yes introduce a breaking changes.

@garyrussell ?

So sad story, but thank you for heads up and pointers!

Can we ask you about contribution, @neoXfire , though? 
https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc

**Comment by garyrussell** [comment]
? 2.1.0 is not a point release. 2.0.1 is. Breaking changes are ok on minor releases. We can't deprecate on 2.0.x though because, although it works on 1.0.0, it has to remain compatible with 0.11. Type erasure makes deprecation painful here.

**Comment by neoXfire** [comment]
I'd be pleased to contribute but i can't do it on my work time. I could only do it on Saturday.
I'm new to open-source contribution so maybe it's short if you planned GA for next week and you want the changes for this version, i don't know. 
It's your choice.

**Comment by neoXfire** [comment]
Sorry, I didn't get enough time to work on this on my free time :( ...
I would not have done this way since you talked about subclassing to ease transition. However I prefer your way with just a rename : so much simpler. Good job ! 👍
