### ISSUE TITLE
Add support to consume POJOs with batch listener

### ISSUE THREAD

**Issue by kaarelk** [spring-projects/spring-kafka#487]
Currently one cannot use POJO-s with @KafkaListener with batching enabled

Add support for message level MessageConverter into BatchMessagingMessageConverter (i.e so that one could compose BatchMessagingMessageConverter with StringJsonMessageConverter).

**Comment by artembilan** [comment]
Not sure what is the problem and why we should backport even if we are going to fix it.

There is this code which says what to do and what isn't supported:
```
	/**
	 * Subclasses can convert the value; by default, it's returned as provided by Kafka.
	 * @param record the record.
	 * @param type the required type.
	 * @return the value.
	 */
	protected Object extractAndConvertValue(ConsumerRecord<?, ?> record, Type type) {
		return record.value() == null ? KafkaNull.INSTANCE : record.value();
	}
```

**Comment by garyrussell** [comment]
@artembilan the `MessagingMessageConverter` says the same thing, but we provided a subclass `StringJsonMessageConverter` - I just failed to do the same thing for batches.
