### ISSUE TITLE
Allow different type for replyTemplate in AbstractKafkaListenerContainerFactory<K, V>

### ISSUE THREAD

**Issue by yoransabern** [spring-projects/spring-kafka#490]
When using a containerFactory it should be possible to use a different <k, v> for the KafkaTemplate.

This way something like this would be possible:

```
@KafkaListener(id = "id", topics = "t", containerFactory = "customF")
@SendTo("back")
public Pojo consumeStringProducePojo(String foo) {
    ...
    return new Pojo();
}
```

Unless there already is a different way to consume a different message type than the return type?

**Comment by garyrussell** [comment]
You can use raw types as a work around - i.e. inject just a `KafkaTemplate` (with no generic types).

**Comment by yoransabern** [comment]
Ah I didn't know that was possible, thanks a lot!
