### ISSUE TITLE
Transactional producer factory - set enable.idempotence to true by default

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#493]
From the [kafka documentation](https://kafka.apache.org/documentation/)...

>Note that `enable.idempotence` must be enabled if a TransactionalId is configured.

**Comment by nklmish** [comment]
We can set `configs.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG,true)`, when `setTransactionIdPrefix` get called 
However if someone has set `enable.idempotence=false`, than may its better if we throw an exception/log warning rather than overwriting the property in config map? 

Thoughts?

**Comment by nklmish** [comment]
Thanks for the reply, so in this case I will send a PR
