### ISSUE TITLE
Lost messages and messed up offsets

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-kafka#497]
I'm using Kafka 0.10.0, spring-kafka 1.1.0 and spring-integration-kafka 2.1.0.

I'm reading messages from a single topic (20 partitions), using 4 consumers (one group), using the standard KafkaMessageListenerContainer with default configuration. The DefaultKafkaConsumerFactory that is uses is configured with a key and value deserializer, and a group id; no other settings.

We've been experiencing a serious problem a few times now, after a large burst of messages (75000) have been posted to the topic. The consumer lag (as reported by Kafka's kafka-consumer-groups.sh) immediately shows a huge lag, which is expected. The consumers start processing the messages, which is expected to take them at least 30 minutes. In the mean time, more messages are posted to the topic, but at a "normal" rate, which the consumers normally handle easily. The problem is that the reported consumer lag is not decreasing at all. After some 30 minutes, it has even increased slightly. This would mean that the consumers are not able to process the backlog at all, which is extremely unlikely.

After a restart of all consumer applications, something really surprising happens: the lag immediately drops to nearly 0! It is technically impossible that the consumers really processed all messages in a matter of seconds. Manual verification showed that many messages were not processed at all; they seem to have disappeared somehow. So it seems that restarting the consumers somehow messed up the offset (I think).

On top of that, I noticed that the reported lag shows seemingly impossible figures. During the time that the lag was not decreasing, before the restart of the consumers, the "current offset" that was reported for some partitions decreased. To my knowledge, that is impossible. 

Does anyone have an idea on how this could have happened?

**Comment by garyrussell** [comment]
Sounds like a question for the Kafka folks, not here; I've not seen anything like that.

However, I never use auto commit (set `enable.auto.commit=false`) and have the listener container manage the offsets.

**Comment by garyrussell** [comment]
I would also recommend updating to a newer broker (1.0.0 is out) and newer spring project versions; we're planning on releasing Spring Kafka 2.1.0 and S-I-K 3.0 tomorrow.

**Comment by tomvandenberge** [comment]
Is there a specific reason why you don't use auto commit? Are there known problems or other reasons why you would not recommend this?

**Comment by garyrussell** [comment]
>Is there a specific reason why you don't use auto commit? Are there known problems or other reasons why you would not recommend this?

Sorry for the delay in replying (SpringOne Platform + vacation).

I just prefer to have the container do the commits, either a record at a time (`AckMode.RECORD` or after each batch of `poll()`d records (`AckMode.BATCH` - the default), rather than relying on the consumer doing it itself on some schedule.

**Comment by artembilan** [comment]
Closed with the answer from Gary. See above.
