### ISSUE TITLE
Move `Endpoint` classes from the `listener` to the `config` package

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-kafka#5]
Just the proposal IMO.

Any `...Endpoint` classes and `KafkaListenerContainerFactory` look like fully configuration artifacts, so should be in the appropriate place.
From other side their implementations are already there.

Looks weird for me and should be fixed or explained.

Thanks

**Comment by garyrussell** [comment]
I see what you mean; but this is consistent with Rabbit.

**Comment by artembilan** [comment]
Well, it's "brand new" project, why don't be more robust then? :smile: 

Although I won't mind if you decide to leave it as is.
At least it isn't so spiky after the review already.

**Comment by garyrussell** [comment]
I went ahead and did it - it helped with the tangles too.
