### ISSUE TITLE
enable-auto-commit: false is ignored (auto-commit stays enabled)

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-kafka#516]
With this configuration:

```
spring:
  kafka:
    consumer:
      enable-auto-commit: false
```

When using `MANUAL` ack mode, my app crashes with this error message:

> Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is 
> java.lang.IllegalStateException: Consumer cannot be configured for auto commit for ackMode MANUAL

While debugging the code, I noticed `org.springframework.boot.autoconfigure.kafka.KafkaProperties.Consumer#enableAutoCommit` remains `null`.

Affects `2.1.0.RC1`

**Comment by behrangsa** [comment]
This was due to a misconfiguration on my part. Closing.

**Comment by sparkmuse** [comment]
Could you tell what was the error so other can learn lol ( I am having the same error)

**Comment by behrangsa** [comment]
Damn. I am really sorry, I had to explain what I had done wrong in the comment above.

Unfortunately I have completely forgotten what I had done wrong.

If you can create a minimal project reproducing that issue I will look into it and debug it for you -- hopefully it refreshes my memory too :sweat_smile:.

**Comment by sparkmuse** [comment]
Do not worry. I fixed mine  already.

I my case I ended up with the current configuration and it worked. 

`@Bean
    public ConcurrentKafkaListenerContainerFactory<Long, Book> kafkaListenerContainerFactory() {

        ConcurrentKafkaListenerContainerFactory<Long, Book> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.getContainerProperties().setAckOnError(false);
        factory.getContainerProperties().setErrorHandler(new SeekToCurrentErrorHandler());
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL);
        return factory;
    }`

Thanks for the reply.

**Comment by yuranos** [comment]
My problem(same issue with an ignored auto commit) was that we had a separately configured DefaultKafkaConsumerFactory, like so:
`    @Bean
    fun consumerFactory(): ConsumerFactory<String, String> {
        return DefaultKafkaConsumerFactory(consumerConfigs())
    }`
which meant that all properties should be manually passed into consumerConfigs().

**Comment by garyrussell** [comment]
@yuranos When creating your own consumer factory, you can still populate it will Boot properties (and then customize more properties) as follows...

```java
	@Bean
	public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
		Map<String, Object> consumerProps = properties.buildConsumerProperties();
		consumerProps.put(..., ...);
                 ...
		return new DefaultKafkaConsumerFactory<Object, Object>(consumerProps);
	}
```
