### ISSUE TITLE
Overide the client.id property for consumer factory in @KafkaListener

### ISSUE THREAD

**Issue by yoransabern** [spring-projects/spring-kafka#518]
Can we get an option to override the client.id property of the consumer factory in @KafkaListener?

This way we don't have to create a bunch of container factories when we want the consumer to have a static client id.

**Comment by garyrussell** [comment]
It's already there, since 1.3 - see [`idIsGroup` and `groupId`](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java#L166).

**Comment by garyrussell** [comment]
Sorry - misread.
