### ISSUE TITLE
Producer config settings of KafkaTemplate not used in @SendTo

### ISSUE THREAD

**Issue by yoransabern** [spring-projects/spring-kafka#519]
When I use a listener factory with a Reply Template, it seems the producer that is created with the @SendTo annotation always uses the default properties, instead of the propertys of the KafkaTemplate's producerFactory.

**Comment by artembilan** [comment]
Sorry, what are you talking about?

The `AbstractKafkaListenerContainerFactory` has this one:
```
/**
	 * Set the {@link KafkaTemplate} to use to send replies.
	 * @param replyTemplate the template.
	 * @since 2.0
	 */
	public void setReplyTemplate(KafkaTemplate<K, V> replyTemplate) {
		this.replyTemplate = replyTemplate;
}
```
Which you can specify when declare the bean for the `AbstractKafkaListenerContainerFactory`.

Why it is so hard to be a bit more clear in describing the problem?..
Also how about the test-case to reproduce?

Thanks

**Comment by yoransabern** [comment]
Never mind, I made a mistake. Sorry about that.
