### ISSUE TITLE
Nullpointer in spring-kafka

### ISSUE THREAD

**Issue by pradi** [spring-projects/spring-kafka#522]
we are using spring-kafka-2.0.1.RELEASE and get this error in production:

> exception java.lang.NullPointerException java.lang.NullPointerException: null at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$000(KafkaMessageListenerContainer.java:271) ~[spring-kafka-2.0.1.RELEASE.jar:2.0.1.RELEASE] at org.springframework.kafka.listener.KafkaMessageListenerContainer.getAssignedPartitions(KafkaMessageListenerContainer.java:152) ~[spring-kafka-2.0.1.RELEASE.jar:2.0.1.RELEASE] at

ref: https://stackoverflow.com/questions/47794253/possible-nullpointer-in-spring-kafka

**Comment by pradi** [comment]
Hi,

is version spring-kafka 2.1.1 also compatible with kafka 0.11.x.x?

Thanks

**Comment by artembilan** [comment]
Don't worry: we will back-port the fix up to `1.3.x`. So, `2.0.x` will be fixed as well.

**Comment by garyrussell** [comment]
But, yes, the 1.0.0 kafka-clients will communicate ok with an 0.11.x.x broker.

**Comment by garyrussell** [comment]
GitHub issues doesn't support multiple milestones so we just add the latest one.
