### ISSUE TITLE
org.apache.kafka.common.errors.GroupAuthorizationException while trying to consume messages

### ISSUE THREAD

**Issue by sandip0018** [spring-projects/spring-kafka#526]
Hi, 

We are trying to use Spring-kafka 1.0.6 with hortonworks kafka 0.9 for consuming messages.
We have kerberos security enable on kafka side and using kafka java client api, we are able to consume messages.

But when we are tried to use Spring kafka 1.0.6 with kafka client api we are getting below error.
`org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group:`

For kerberos related configuration we are passing jaas config as a jvm argument in cloud foundry while starting microservices.

is there anything else we have to do for kerberos related configuration for consuming messages?

Let me know in case more information needed related to this problem.

Thanks,
Sandip

**Comment by artembilan** [comment]
Take a look here, please: https://groups.google.com/forum/#!topic/confluent-platform/Yj0ToxYS0Zk.

Looks like you don't have enough permissions to do what you want.

Some info is here as well: https://developer.ibm.com/opentech/2017/05/31/kafka-acls-in-practice/

This one might be as an answer for you as well: https://stackoverflow.com/questions/37536259/broker-replication-error-not-authorized-to-access-topics-topic-authorization

BTW, it would be better to ask questions on community forums (e.g. StackOverflow). We manage only bugs and feature requests here on GH.

Thank you for understanding
