### ISSUE TITLE
Add spring configuration property for trusted-packages in serializer/JsonDeserializer.java

### ISSUE THREAD

**Issue by yoransabern** [spring-projects/spring-kafka#535]
It would be nice to set the trusted packages for deserialization in the spring config properties, instead of having to add the trusted packages to the mapper programmatically.

**Comment by garyrussell** [comment]
If you are talking about Spring Boot properties; it is already available (with Spring Kafka 2.1.0 and above - currently 2.1.1)...

```
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.foo,org.bar
```

**Comment by yoransabern** [comment]
Ah thats great, I couldn't find any documentation on this. Thanks!

**Comment by garyrussell** [comment]
See [here, scroll down to "Starting with version 2.1...](https://docs.spring.io/spring-kafka/reference/html/_reference.html#serdes).

"In addition, the serializer/deserializer can be configured using Kafka properties."

Arbitrary kafka properties can be set in boot; [as mentioned in the boot docs](https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/htmlsingle/#boot-features-kafka-extra-props).

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-boot/pull/11638

**Comment by garyrussell** [comment]
I just tested it and it worked fine for me (same versions)...

```
spring.kafka.consumer.properties.spring.json.trusted.packages=com.myapp
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
```

![screen shot 2018-03-29 at 6 14 21 pm](https://user-images.githubusercontent.com/483832/38116228-32c885f8-337d-11e8-9a4e-fcf043f1c01e.png)

**Comment by spazbob** [comment]
I think I've found the problem. When I comment out VALUE_DESERIALIZER_CLASS_CONFIG, the container won't start as it complains the config is missing. This suggests it's not reading my config from application.properties. I presume either I can't mix the Java config and the properties file, or somehow my manual creation of the factory means it skips the properties? Will keep digging...

	@Bean
	public ConsumerFactory<Object, Object> scrapeRequestConsumerFactory() {
		return new DefaultKafkaConsumerFactory<>(scrapeRequestConsumerConfigs());
	}

	@Bean
	public Map<String, Object> scrapeRequestConsumerConfigs() {
		Map<String, Object> props = new HashMap<>();
		props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaConfig.getKafkaBootstrapServers());
		props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
		//props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);
		props.put(ConsumerConfig.GROUP_ID_CONFIG, "myapp-request-consumer-group");
		props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, 1);
		return props;
	}

**Comment by garyrussell** [comment]
That is correct, boot will only configure a consumer factory [if the application doesn't define its own](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java#L91).

```java
	@Bean
	@ConditionalOnMissingBean(ConsumerFactory.class)
	public ConsumerFactory<?, ?> kafkaConsumerFactory() {
		return new DefaultKafkaConsumerFactory<>(
				this.properties.buildConsumerProperties());
	}
```

However, you can access the boot properties thus...

```java
@Bean
public Map<String, Object> scrapeRequestConsumerConfigs(KafkaProperties properties) {
	Map<String, Object> props = properties.buildConsumerProperties();

         // make more modifications as needed...

	return props;
}```

**Comment by spazbob** [comment]
Fantastic, thank you for the guidance @garyrussell.

**Comment by vxavictor513** [comment]
@garyrussell: Does this work for Spring Cloud Stream Binder Kafka too?
```
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.foo,org.bar
```

**Comment by garyrussell** [comment]
@vxavictor513 Yes, with 2.0.x. But, the binding has to be configured with

    spring.cloud.stream.binding.<channel>.consumer.useNativeDecoding=true

to use a non-standard deserialiizer, which can be configured using those boot properties.

**Comment by adarshpalbrar** [comment]
Hi,

Specify the configuration as following:

@Bean
    public ConsumerFactory<String, User> consumerFactory() {
        Map<String, Object> config = new HashMap<>();
        config.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "127.0.0.1:9092");
        config.put(ConsumerConfig.GROUP_ID_CONFIG, GROUP_ID);
        config.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        config.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);
        config.put(JsonDeserializer.TRUSTED_PACKAGES, "package.where.domain.object.resides");
        return new DefaultKafkaConsumerFactory<>(config);
    }

**Comment by wadhokarshruti** [comment]
Hi,

Below both solutions worked for me...

Solution 1:
@Bean
    public ConsumerFactory<String, Customer> customerConsumerFactory(){
        Map<String, Object> customerConfigMap = new HashMap<>();
        customerConfigMap.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG,"localhost:9092");
        customerConfigMap.put(ConsumerConfig.GROUP_ID_CONFIG,"group_json");
        customerConfigMap.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        customerConfigMap.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);
        customerConfigMap.put(JsonDeserializer.TRUSTED_PACKAGES, "*");
        return new DefaultKafkaConsumerFactory<>(customerConfigMap);
    }


Solution 2:

public class CustomJsonDeserializer<T> extends JsonDeserializer<T> {
    public CustomJsonDeserializer() {
        // defaults from superclass
        super();
        // * to trust all 
        this.addTrustedPackages("*");
    }
}

 @Bean
    public ConsumerFactory<String, Customer> customerConsumerFactory(){
        Map<String, Object> customerConfigMap = new HashMap<>();
        customerConfigMap.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG,"localhost:9092");
        customerConfigMap.put(ConsumerConfig.GROUP_ID_CONFIG,"group_json");
        customerConfigMap.put(JsonDeserializer.TRUSTED_PACKAGES, "*");
        return new DefaultKafkaConsumerFactory<>(customerConfigMap, new StringDeserializer(), new CustomJsonDeserializer<>());
    }

**Comment by aleksey-suprun** [comment]
Does anyone know how to configure `spring.json.trusted.packages` for Kafka Streams? I'm using the following config%
```
@Configuration
@EnableKafka
@EnableKafkaStreams
public class KafkaStreamsConfig {

    @Bean(name = KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME)
    public KafkaStreamsConfiguration kStreamsConfig(KafkaProperties kafkaProperties) {
        return new KafkaStreamsConfiguration(Map.of(
                StreamsConfig.APPLICATION_ID_CONFIG, kafkaProperties.getStreams().getApplicationId(),
                StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaProperties.getStreams().getBootstrapServers(),
                StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName(),
                StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName(),
                StreamsConfig.DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG, WallclockTimestampExtractor.class.getName()
        ));
    }
```
My `application.yml` is the following:
```
spring:
  kafka:
    streams:
      bootstrap-servers: XXX.XXX.XXX.XXX:9092
      application-id: spring-kafka-test
      properties:
        processing.guarantee: exactly_once
        spring.json.trusted.packages: com.mypackage.streams.entity.kafka.*
```
But when I change the package of the entity published into Kafka, I'm receiving the following exception:
```
Caused by: java.lang.IllegalArgumentException: The class 'com.geocomply.streams.entity.transaction.kafka.raw.Transaction' is not in the trusted packages: [java.util, java.lang, com.mypackage.streams.entity.kafka, com.mypackage.streams.entity.kafka.*]. If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).
	at org.springframework.kafka.support.mapping.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:129)
	at org.springframework.kafka.support.mapping.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:103)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:569)
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:58)
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66)
	... 9 more
``` 
Looks like the property added to the `appplication.yml` does not work.
