### ISSUE TITLE
Seeking to offset (which is bigger than messages count in partition) causes processing messages from beginning

### ISSUE THREAD

**Issue by AndrewPonyk** [spring-projects/spring-kafka#536]
```java
@KafkaListener(id = "kafka_consumerListener", topics = {"${spring.kafka.template.default-topic}"})
public void receive(String message, @Header(KafkaHeaders.OFFSET) String offset,
                        @Header(KafkaHeaders.RECEIVED_PARTITION_ID) String receivedPartitionId) throws IOException {
 // process message
}   

@Override
public void onPartitionsAssigned(Map<TopicPartition, Long> assignments, ConsumerSeekAware.ConsumerSeekCallback callback) {
        assignments.forEach((assignment, assignmentKey) -> {
            callback.seek(assignment.topic(), assignment.partition(), 100);
        });
    }
```

If there is less then 100 messages in the partition, then messages are processed from the beginning (and not from offset 100).

**Comment by garyrussell** [comment]
That was not my experience when I tested it a long time ago, but something might have changed in kafka itself (client or server).

However, tarting with version 1.3.0 (1.3.2 is the current 1.3.x release), we added `seekToBeginning()` and `seekToEnd()` to the callback.

**Comment by AndrewPonyk** [comment]
@garyrussell , actually, if I seek to 100 offset for some partition, then first incoming message should have offset 100 (no matter how many message are in partition).

Any ideas ?

**Comment by garyrussell** [comment]
That's not how Kafka works; in my experience, if you seek to an offset that is greater than the current maximum extent of the partition you will seek to the end.

i.e. If the max offset is currently 50 and you seek to 100, you'll actually seek to 51.

Offset 100 doesn't exist yet, so you can't seek to it.

**Comment by AndrewPonyk** [comment]
@garyrussell , thank you. I understood.
