### ISSUE TITLE
Spring Kafka does not work properly inside openjdk:9-jdk-slim docker image

### ISSUE THREAD

**Issue by pasali** [spring-projects/spring-kafka#540]
I have a simple app that uses spring kafka 1.1.7 and i am using `openjdk:9-jdk-slim` docker image to dockerize my app. When i try to run my docker image, it starts normally and attaches brokers but can not get any message. So i assume that there are some missing packages and build my docker image with `openjdk:9-jdk` and it just worked fine. But since `openjdk:9-jdk` is large image i don't want to use it. Do you have any idea which packages could cause this issue?

**Comment by garyrussell** [comment]
Do you have any logs?

**Comment by pasali** [comment]
[ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : Successfully joined group test_search with generation 61
    [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions [test_db_foo-0] for group test_search
    [ntainer#0-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned:[test_db_foo-0]

Three is no error or warn log just this and keeps waiting.

**Comment by pasali** [comment]
I do not know how but its related to `glibc` library. Installing it resolves the issue

**Comment by garyrussell** [comment]
Interesting; thanks for reporting back.

**Comment by zhongyusimon** [comment]
i just meet this problem too. with 8-jdk-alpine

**Comment by zhongyusimon** [comment]
it has be resolved when I change it to openjdk:8-jdk-slim
