### ISSUE TITLE
failed to get offset by time

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-kafka#541]
Hi

This maybe a direct kafka question, but trying to see if theres a configuration missed in spring-kafka

After we upgraded to 2.1 and kafka 1.0, im seeing these errors

o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 305000 ms

**Comment by alemjimer** [comment]
Hi,
we have the same problem after upgrading kafka. 
Have you solved the problem?

Thanks
