### ISSUE TITLE
Configurable KafkaStreams cleanup

### ISSUE THREAD

**Issue by pszymczyk** [spring-projects/spring-kafka#542]
Hi

In our application we have a lot of KTable's based on persistent store. As I can see now every time application stops all states are removed by ```kafkaStreams.cleanup()```. As far as I understood Kafka Streams architecture and as can I see in [manual](https://goo.gl/LQNrDC) it is not necessary. This operation should be done after application reset tool execution and"before restarting an application instance on the same machine".

What I'd like to achieve? 
- do not remove persistent store files in regular application restart
- cleanup persistent store on application startup only when specified property is passed to application: eg spring.kafka.streams.cleanup=true

As I can see now all Kafka properties are defined in [spring-boot](https://github.com/spring-projects/spring-boot/blob/v1.5.9.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java) so I can introduce this custom property on my own, only thing it's necessary to introduce is simple enhancement in ```StreamsBuilderFactoryBean```.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/commit/63b2bcb01827f2cfab3ce279d352f787bd3c1a6f
