### ISSUE TITLE
Make StreamsConfig customizable in StreamsBuilderFactoryBean

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-kafka#548]
Currently, `StreamsBuilderFactoryBean` constructor requires a `StreamsConfig`. There are use cases in which it is required to set the `StreamsConfig` later than when the factory is created, but right before the  `start` method is called. Also, it will be beneficial if we can set the `phase` on the bean to `Integer.MAX_VALUE` as we need to ensure that the lifecycle for the object created by the factory is started only after all the other components are started.

**Comment by garyrussell** [comment]
I generally prefer to leave some "breathing" room, in case some other bean needs to be started after this; so I would suggest `Integer.MAX_VALUE - 1000` or similar.
