### ISSUE TITLE
KafkaMLC - make addOffsets() thread-safe

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#566]
https://stackoverflow.com/questions/47652651/spring-kafka-is-acknowledgement-acknowledge-thread-safe/47663459#comment84501434_47663459

**Comment by lhsm** [comment]
Hi, seems still not thread safe. Please, take a look into KafkaMessageListenerContainer.ListenerConsumer#buildCommits. While iterating offsets new offset may be added
The same in KafkaMessageListenerContainer.ListenerConsumer#commitPendingAcks

**Comment by garyrussell** [comment]
Good catch; thanks.
