### ISSUE TITLE
Transaction And RetryTemplate

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#575]
Hi,

I'm using a chainedTransactionManager (kafka+jms)

I'm using @Transactional on a @KafkaListener which is publishing to jms. (spring-kafka 1.3.3)
The consumer is configured with RetryTemplate to retry 3 times and an ErrorHandler.
During some test I set up the application to produce 50% errors by throwing RuntimeExceptions.

On the first try, an error occured and the transaction is rolledback. No message is sent to JMS.
Then the retry template retries, and succeed. The jms message is sent but strangely the Kafka transaction is rolled back.

Here is the message :
essageListenerContainer$ListenerConsumer : Transaction rolled back
org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only

1) Is that normal ? The message is then re-poll by the @KafkaListener and reprocessed, leading me to have duplicate messages on my JMS consumer
2) When using transaction, if an error occure, the errorHandler is never called. Is there a way to prevent this ?

My goal is to have a Transactional Kafka Consumer which retries 3 times on any error and if it fails, call the error handler and rollback the jms message

**Comment by garyrussell** [comment]
Can you show your configuration?

Are you injecting the KTM into the container as well? If so, it will start the kafka transaction before calling the listener, and the retries will be performed within the transaction.

If you don't inject the KTM into the container (or if you inject the Chained TM), the container can't send the consumer offsets to the transaction - it can only do that if the TM is a KTM so it has access to the producer.

It should work fine if there is no TM in the container, the ChainedTM is used by the `@Transactional` annotation which starts the Tx and you manually send the offset to the transaction using a `KafkaTemplate`.

**Comment by Rajh** [comment]
Thanks for the fast reply.

I have 2 issues :
- If the listener fail once, then the container can not commit (and it should) thus leading to an error. Therefor the other TM in the ChainedTM has sucessfully committed the transaction.

- When it fails, I would like the transaction to be rolledback and call the errorHandler without seeking the original offset like in KafkaMessageListenerContainer:904 (kafka-spring 1.3.3)

Here is my configuration :
`@Bean
    public ConcurrentKafkaListenerContainerFactory kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory();
        factory.setConsumerFactory(consumerFactory());
        factory.getContainerProperties().setAckOnError(false);
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.RECORD);
        factory.getContainerProperties().setErrorHandler((thrownException, data) -> System.out.println("#### Exception " + thrownException.getMessage()));
        factory.setRetryTemplate(new RetryTemplate());
        factory.getContainerProperties().setTransactionManager(kafkaTransactionManager);

        return factory;
    }`

`@Bean(name = "chainedTransactionManager")
    @Primary
    public ChainedTransactionManager chainedTransactionManager(KafkaTransactionManager kafkaTransactionManager, JmsTransactionManager jmsTransactionManager) {
        return new ChainedTransactionManager(kafkaTransactionManager, jmsTransactionManager);
    }

    @Bean(name = "jmsTransactionmanager")
    public JmsTransactionManager jmsTransactionmanager(ConnectionFactory connectionFactory) {
        return new JmsTransactionManager(connectionFactory);
    }

    @Bean(name = "transactionManager")
    public KafkaTransactionManager kafkaTransactionManager(ProducerFactory producerFactory) {
        return new KafkaTransactionManager(producerFactory);
    }

    @Bean
    public TransactionTemplate transactionTemplate(ChainedTransactionManager tm) {
        return new TransactionTemplate(tm);
    }`

`@KafkaListener(topics = "${kafka.consumer.topic.name}")
    @Transactional(transactionManager = "chainedTransactionManager")
    public void onKafkaMessage(ConsumerRecord<String, String> record) {
        if (record.key() == null) {
            throw new RuntimeException("Error deser");
        }
        LOGGER.info("New message : " + record.value());
        jmsMessagingTemplate.send("test.queue", new GenericMessage<>(record.value()));
        if (new Random().nextInt(10) < 5) {
            LOGGER.error("Fail consumer");
            throw new RuntimeException("Fail consumer");
        } else {
            LOGGER.error("Success consumer");
            throw new RuntimeException("Fail consumer");
        }
    }`

**Comment by garyrussell** [comment]
This should work as you expect...

Remove this:
    
    factory.getContainerProperties().setTransactionManager(kafkaTransactionManager);

So that the container doesn't start the transaction, we wait until the `@Transactional` is encountered (within the retry).

    factory.getContainerProperties().setAckOnError(false);

so the failed message offset with be committed after the failure.

Define a `KafkaTemplate` (using the same `ProducerFactory` as the KTM).

In your listener, call 

    this.kafkaTemplate.sendOffsetsToTransaction(Collections.singletonMap(new TopicPartition(record.topic(), record.partition()), record.offset()+1));

**Comment by Rajh** [comment]
Oh ok, I miss understood the container configuration.
Sorry for inconvenience :s

What is factory.getContainerProperties().setTransactionManager() then ?

The kafkaTemplate is optional, isnt it ? The offset will be auto committed on the next successfull message ?
Leaving me the possibility to restart and reprocess everything when the listener is in a constant error state ?

**Comment by garyrussell** [comment]
Right - good point; the container knows nothing about the transaction so it will commit the offsets normally; sorry for the confusion.

>What is factory.getContainerProperties().setTransactionManager() for then ?

That is for the pattern where you received from one topic and publish to another and you want them to be atomic.

The container starts the transaction; the kafka template participates in it and the container commits.

It's not intended for use with `@Transactional`.

**Comment by garyrussell** [comment]
However, if you are not publishing to Kafka, why do you need a `KafkaTransactionManager` at all?

**Comment by Rajh** [comment]
Well ... depending on the topic i'm comitting to kafka.

I have several use case.
1) One consuming from kafka and publishing to JMS
2) An other consuming from kafka and publishing to kafka.

I want to be the closest to exactly once delivery. For kafka to kafka I wanted to use kafka transaction.
And for JMS a chained transaction.

I wanted a generic configuration, but if I understand what you are saying is that:
for the 1st case I just need a jms transaction ?
And for the 2nd case I need to set a KTM on the container ? Or via @Transactional ?

**Comment by garyrussell** [comment]
If you want transactions within retries, you have to use `@Transactional`.

I would recommend setting the container's ackMode to MANUAL and always use `KafkaTemplate.sendOffsetsToTransaction` rather than the container committing offsets outside of the transaction scope.

For the JMS case, you'd use the chained TM; for the just kafka case, there's no point in starting a JMS Tx.

**Comment by Rajh** [comment]
For the kafka case, can I use the KafkaTransactionManager in @Transactional or I have to use the factory.getContainerProperties().setTransactionManager() ?

This seems a bit strange for me to declare a KafkaTemplate which will not "produce" any message.
Which serializer should I chose ? Which configuration ? Which default topic ?
It doesn't matter ? I can use any kafkaTemplate ? Creating a specific one used only to sendOffsets by every listeners ?

Sorry to bother you about that but I have an other question about the producer :
For the setting "setTransactionIdPrefix" should i use an unique id per kafkaTemplate ?
Can i use the same ID for an application which is scaled and deployed several time (having several time the same config and ID) ?

**Comment by garyrussell** [comment]
Don't inject the TM into the container if you want transactions within retries; the container knows nothing about the retries; one transaction will span them all if you pass the TM into the container.

>This seems a bit strange for me to declare a KafkaTemplate which will not "produce" any message.

You really should manage the consumed offsets within the transaction.

See the javadocs for `KafkaProducer.sendOffsetsToTransaction`; they will be committed or rolled back appropriately.

>Which serializer should I chose ? Which configuration ? Which default topic ?

It doesn't matter, since you are not actually publishing any messages.

>It doesn't matter ? I can use any kafkaTemplate ? Creating a specific one used only to sendOffsets by every listeners ?

You don't need a special one; you just need to be sure to use the same `group.id` as the container in the `sendOffsetsToTransaction` (use the overloaded one that takes a groupId) so that the proper association with the consumer is achieved.

**Comment by Rajh** [comment]
The producer doesn't have a group.id does it ?

I can create a kafkaTemplate like that for all my offset commits ?
@Bean(name = "defaultKafkaTemplate")
    public KafkaTemplate<Void, Void> defaultKafkaTemplate() {
        final KafkaTemplate<Void, Void> kafkaTemplate = new KafkaTemplate<>(producerFactory());
        return kafkaTemplate;
    }

Just to be sure, @Transactional will work with a KTM even if not positioned on a container ?

If I want offset to be managed by the container in AckMode.RECORD and handling ackOnError I have to remove RetryTemplate and the @Transactional. And set the KTM into the container.
Else I have to set AckMode.MANUAL commit the offset manually and I'll be able to use RetryTemplate and my ChainedTM in @Transactional

**Comment by garyrussell** [comment]
>The producer doesn't have a group.id does it ?

No; the consumer does, though.

I just re-read the KafkaProducer javadocs...

     * This method should be used when you need to batch consumed and produced messages
     * together, typically in a consume-transform-produce pattern. Thus, the specified
     * {@code consumerGroupId} should be the same as config parameter {@code group.id} of the used
     * {@link KafkaConsumer consumer}. Note, that the consumer should have {@code enable.auto.commit=false}
     * and should also not commit offsets manually (via {@link KafkaConsumer#commitSync(Map) sync} or
     * {@link KafkaConsumer#commitAsync(Map, OffsetCommitCallback) async} commits).

So I guess if you are not publishing to Kafka, you  don't really need a transaction at all; just let the container manage the offsets.

Yes, `@Transactional` will work if you are not running on a container but then, of course, there is no group.id and therefore no offsets to send to the transaction.

**Comment by Rajh** [comment]
I'm really confused now xD

1) A KafkaConsumer read kafka and publish to JMS
Create a Container without KTM and add @Transactional with a JMS transaction on the listener.
AckMode.RECORD, RetryTemplate, ackOnError(false)

2) A KafkaConsumer consuming and producing to Kafka
Create a container with a KTM. Do not add any @Transaction on the listener.
AckMode.RECORD, no retry template, ackOnError(false)
OR
Create a container without KTM. Add @Transaction with KTM on the listener.
AckMode.MANUAL, RetryTemplate, ackOnError(false), "sendOffsetsToTransaction" using any of the producers ?

**Comment by garyrussell** [comment]
1. Correct except you might want ackOnError(true) if you want no possibility that the bad record will be redelivered. With false, the offset won't be committed (until a subsequent successful record is processed).

2.1. With that configuration, the message will be retried indefinitely.

2.2. Correct except the ProducerFactory must the same as the one wired into the TM

**Comment by garyrussell** [comment]
Just to close this out; I added a new [specialized `ChainedKafkaTransactionManager`](https://github.com/spring-projects/spring-kafka/pull/576). It doesn't help your use case, but helps avoid sending the offsets in user code when `@Transactional` is not used and transaction synchronization is needed.

**Comment by Rajh** [comment]
Ok thanks a lot for your help
