### ISSUE TITLE
MessageConversionException if use @Payload and @Header

### ISSUE THREAD

**Issue by dusan-eremic** [spring-projects/spring-kafka#579]
Hi,
 
I have a `@KafkaListener` that accepts a custom pojo message as a `@Payload` and that works fine. 

If in addition to `@Payload` parameter I add `Header(KafkaHeaders.RECEIVED_TOPIC) String topic` as a second parameter likes this
```
@Override
@KafkaListener(topics = "${kafka.topic.fulfilment}")
public void processOrder(@Payload FulfilmentMessage message, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) 
```
`MessageConversionException` gets thrown.

> 
> Caused by: org.springframework.messaging.converter.MessageConversionException: Cannot handle message; nested exception is org.springframework.messaging.converter.MessageConversionException: Cannot convert from [com.dusan.service.model.FulfilmentMessage] to [java.lang.String] for GenericMessage [payload=FulfilmentMessage(correlationId=9edfb1f9abcc6, orderId=108737886056134563, created=1519050744972), headers={kafka_offset=14, kafka_receivedMessageKey=null, kafka_receivedPartitionId=2, kafka_receivedTopic=order-fulfilment}], failedMessage=GenericMessage [payload=FulfilmentMessage(correlationId=9edfb1f9abcc6, orderId=108737886056134563, created=1519050744972), headers={kafka_offset=14, kafka_receivedMessageKey=null, kafka_receivedPartitionId=2, kafka_receivedTopic=order-fulfilment}]
> 	... 12 common frames omitted

Any idea why this is happening?

**Comment by dusan-eremic** [comment]
Resolved the issue by moving `@Payload` and `@Header` annotations to the interface.

**Comment by artembilan** [comment]
May we close this or do you still have a question or concern?

Thanks

**Comment by dusan-eremic** [comment]
I'll close it now. 

Thanks

**Comment by Rama000777** [comment]
aim facing the same issue.. how to fix?
