### ISSUE TITLE
Question about transaction.id.prefix

### ISSUE THREAD

**Issue by Rajh** [spring-projects/spring-kafka#580]
Hi,

I'm using kafka-spring 1.3.3.RELEASE and Kafka 0.11.0.1 and I'd like to use transaction for my producers.

Spring-kafka requires a transaction.id.prefix to be set on the kafka producer but I don't understand what should I set.

The transaction.id.prefix should be different for each :
    - Producer ? (If I understand correctly the answer is yes and its handled by spring by the prefix)
    - Instances of one application ? (Launching several time the same application producing to the same topic)
    - Application ? (Other application producing to the same or different topic)

Thanks

**Comment by artembilan** [comment]
Per `Producer`. This property is mapped to the `transactional.id` directly like this:
```
configs.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG,
					this.transactionIdPrefix + this.transactionIdSuffix.getAndIncrement());
```
when we create a `Producer` via `DefaultKafkaProducerFactory`.

See more info [here](https://www.confluent.io/blog/transactions-apache-kafka/) from the bear Apache Kafka perspective.

**Comment by Rajh** [comment]
But does that mean that launching several time the same application has to have a different value for this transaction.id.prefix  ?

**Comment by artembilan** [comment]
No, that's not. You really can stick with the same value here. It definitely must be different for several producer-based applications in parallel, but that's fine to reuse the same `transaction.id.prefix` over restart.

At least that is how I feel it...

@garyrussell , what can you say on the matter?

**Comment by garyrussell** [comment]
If you are running multiple instances concurrently, each app instance needs a unique prefix. Otherwise you'll get `transaction.id` collisions.

**Comment by Rajh** [comment]
Thanks.
So I need a way to specify an unique id for each instances running concurrently (I'm using OpenShift which automatically start/stop pods with the same config/binaries).

Using :
props.put("transaction.id.prefix", UUID.randomUUID());
Is not a good idea since if the app crash it will generate a new one (on restart) instead of using the last prefix to resume ongoing transactions, is that right ?

So I need to find a way to create an unique prefix for each instances automatically created by OpenShift.
Seems not trivial :s

**Comment by SamiraaAB** [comment]
Hi
Iam facing same issue, 
@Rajh  did u find a solution other than randomUUID ? :)

**Comment by SamiraaAB** [comment]
Hi , 
Iam facing the same issue @Rajh  did u find another solution than UUID.randomUUID ?

**Comment by garyrussell** [comment]
Note that this is not a Spring Kafka issue; it's a requirement of Kafka itself.

At least with spring you could populate it via a `${property.placeholder}` from, for example, an environment variable. For example, on cloud foundry you could use an instance index from the VCAP: https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html
