### ISSUE TITLE
EmbeddedKafka too many exceptions.

### ISSUE THREAD

**Issue by nklmish** [spring-projects/spring-kafka#581]
I am using spring-kafka-2.1.2.RELEASE for developing unit tests. The tests works fine but produces too many exceptions on console. My embeddedKafka instance is configured like this
```    @Rule
    public KafkaEmbedded embeddedKafka = new KafkaEmbedded(3, true, SOME_TOPIC);
```
[stacktrace.txt](https://github.com/spring-projects/spring-kafka/files/1738046/stacktrace.txt)

**Comment by artembilan** [comment]
Why don't just turn off such a low level of the logging for the Kafka per se?
```
log4j.category.org.apache.kafka.clients=ERROR
log4j.category.org.apache.kafka.common.network.Selector=ERROR
log4j.category.kafka.server.ReplicaFetcherThread=ERROR
```
Seems for me that's how all of that rebalancing and leader election machinery works in Apache Kafka.
 
That doesn't look like Spring Kafka issue though...

Any particular reason to raise the problem exactly here?

Thanks

**Comment by nklmish** [comment]
@artembilan Thank you for your reply, initially thought about switching off the verbose logging but was wondering may be its better to adjust globally the log level for embedded kafka to some defaults, since in most cases those errors/warnings are adding just an extra noise due to in-memory process?

**Comment by garyrussell** [comment]
`spring-kafka-test` provides no logging implementation or configuration, it just calls the commons-logging API which delegates to your logging subsystem. There's nothing we can do - we don't know which logging implementation you might use (log4j2, logback etc).

**Comment by artembilan** [comment]
>  to adjust globally the log level for embedded kafka to some defaults

That's exactly what you should do in your logging config.
And on the other hand what we are talking about here not `KafkaEmbedded` logs.
See the config I've shared above - there in no any `org.springframework` at all.

To adjust something there in the Kafka logging source code, you really should go to Apache Kafka project for such a request. 

Sorry that we are so useless here, but our project is Spring for Apache Kafka, not Apache Kafka per se.

Thank you for understanding.

*Closing as Works as Designed*
