### ISSUE TITLE
KafkaEmbedded does not create topic for KTable when aggregated

### ISSUE THREAD

**Issue by dmfrey** [spring-projects/spring-kafka#589]
I'm building an app that is using Kafka Streams to read a topic and aggregate the `DomainEvent`s into a materialized view. Running the app with a real Zookeeper and Apache Kafka demonstrates the below groupby-aggregate pipeline work. However, when writing a Unit Test for the same code with the `KafkaEmbedded` Junit Rule it fails.  The test is set up exactly as the `spring-kafka` samples for the upcoming SCSt Kafka Stream 2.x release.

    @StreamListener( "input" )
    public void process( KStream<Object, byte[]> input ) {
        input
                .map( (key, value) -> {
                    try {
                        DomainEvent domainEvent = mapper.readValue( value, DomainEvent.class );
                        log.debug( "process : domainEvent=" + domainEvent );
                        return new KeyValue<>( domainEvent.getBoardUuid().toString(), domainEvent );
                    } catch( IOException e ) {
                        log.error( "process : error converting json to DomainEvent", e );
                    }
                    return null;
                })
                .groupBy( (s, domainEvent) -> s, Serialized.with( Serdes.String(), domainEventSerde ) )
                .aggregate(
                        Board::new,
                        (key, domainEvent, board) -> board.handleEvent( domainEvent ),
                        Materialized.<String, Board, KeyValueStore<Bytes, byte[]>>as( BOARD_EVENTS_SNAPSHOTS )
                            .withKeySerde( Serdes.String() )
                            .withValueSerde( boardSerde )
                );
    }

Here is the test case

public class KafkaBoardClientEmbeddedKafkaTests {

    public static final String BOARD_EVENTS_SNAPSHOTS = "board-events-snapshots";
    private static String RECEIVER_TOPIC = "board-events";

    @ClassRule
    public static KafkaEmbedded embeddedKafka = new KafkaEmbedded( 1, true, RECEIVER_TOPIC );

    private static Consumer<String, String> consumer;

    @BeforeClass
    public static void setUp() throws Exception {

        Map<String, Object> consumerProps = KafkaTestUtils.consumerProps("command-board-events-group", "false", embeddedKafka );
        consumerProps.put( ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest" );

        DefaultKafkaConsumerFactory<String, String> cf = new DefaultKafkaConsumerFactory<>( consumerProps );

        consumer = cf.createConsumer();

        embeddedKafka.consumeFromAnEmbeddedTopic( consumer, RECEIVER_TOPIC );

    }

    @AfterClass
    public static void tearDown() {

        consumer.close();

    }

    @Test
    public void testFind() throws Exception {

        log.debug( "testFind : --spring.cloud.stream.kafka.streams.binder.brokers=" + embeddedKafka.getBrokersAsString() );
        log.debug( "testFind : --spring.cloud.stream.kafka.streams.binder.zkNodes=" + embeddedKafka.getZookeeperConnectionString() );

        SpringApplication app = new SpringApplication( Application.class );
        app.setWebApplicationType( WebApplicationType.NONE );
        ConfigurableApplicationContext context = app.run("--server.port=0",
                "--spring.cloud.service-registry.auto-registration.enabled=false",
                "--spring.jmx.enabled=false",
                "--spring.cloud.stream.bindings.input.destination=board-events",
                "--spring.cloud.stream.bindings.output.destination=board-events",
                "--spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000",
                "--spring.cloud.stream.bindings.output.producer.headerMode=raw",
                "--spring.cloud.stream.bindings.input.consumer.headerMode=raw",
                "--spring.cloud.stream.kafka.streams.binder.brokers=" + embeddedKafka.getBrokersAsString(),
                "--spring.cloud.stream.kafka.streams.binder.zkNodes=" + embeddedKafka.getZookeeperConnectionString(),
                "--spring.profiles.active=kafka",
                "--spring.jackson.serialization.write_dates_as_timestamps=false",
                "--logger.level.io.pivotal.dmfrey=DEBUG");
        try {

            receiveAndValidateBoard( context );

        } finally {

            context.close();

        }

    }

    private void receiveAndValidateBoard( ConfigurableApplicationContext context ) throws Exception {

        Map<String, Object> senderProps = KafkaTestUtils.producerProps( embeddedKafka );
        DefaultKafkaProducerFactory<String, String> pf = new DefaultKafkaProducerFactory<>( senderProps );
        KafkaTemplate<String, String> template = new KafkaTemplate<>( pf, true );
        template.setDefaultTopic( RECEIVER_TOPIC );

        ObjectMapper mapper = context.getBean( ObjectMapper.class );
        BoardClient boardClient = context.getBean( BoardClient.class );

        UUID boardUuid = UUID.randomUUID();
        BoardInitialized boardInitialized = createTestBoardInitializedEvent( boardUuid );
        String event = mapper.writeValueAsString( boardInitialized );
        template.sendDefault( event );

        Board board = boardClient.find( boardUuid );
        assertThat( board, is( notNullValue() ) );
        assertThat( board.getBoardUuid(), is( equalTo( boardUuid ) ) );
        assertThat( board.getName(), is( equalTo( "New Board" ) ) );
        assertThat( board.getStories().isEmpty(), is( equalTo( true ) ) );
        assertThat( board.changes(), hasSize( 0 ) );

    }

    private BoardInitialized createTestBoardInitializedEvent( final UUID boardUuid ) {

        return new BoardInitialized( boardUuid, Instant.now() );
    }

  }

Exception thrown:

```java
2018-02-23 09:13:06,584 ERROR main i.p.d.e.d.c.k.s.KafkaBoardClient:75 - find : error
 org.apache.kafka.streams.errors.InvalidStateStoreException: the state store, board-events-snapshots, may have migrated to another instance.
	at 
 org.apache.kafka.streams.state.internals.StreamThreadStateStoreProvider.stores(StreamThreadStateStoreProvider.java:48) ~[kafka-streams-1.0.0.jar:na]
	at 
 org.apache.kafka.streams.state.internals.QueryableStoreProvider.getStore(QueryableStoreProvider.java:57) ~[kafka-streams-1.0.0.jar:na]
	at org.apache.kafka.streams.KafkaStreams.store(KafkaStreams.java:1034) ~[kafka-streams-1.0.0.jar:na]
	at 
 org.springframework.cloud.stream.binder.kafka.streams.QueryableStoreRegistry.getQueryableStoreType(QueryableStoreRegistry.java:47) ~[spring-cloud-stream-binder-kafka-streams-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at 
 io.pivotal.dmfrey.eventStoreDemo.domain.client.kafka.service.KafkaBoardClient.find(KafkaBoardClient.java:58) ~[classes/:na]
	at 
 io.pivotal.dmfrey.eventStoreDemo.domain.client.kafka.KafkaBoardClientEmbeddedKafkaTests.receiveAndValidateBoard(KafkaBoardClientEmbeddedKafkaTests.java:117) [classes/:na]
	at 
 io.pivotal.dmfrey.eventStoreDemo.domain.client.kafka.KafkaBoardClientEmbeddedKafkaTests.testFind(KafkaBoardClientEmbeddedKafkaTests.java:89) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
```

The exception is a bit misleading.  I've found it usually means the topic doesn't exists.

**Comment by artembilan** [comment]
Why isn't your `BOARD_EVENTS_SNAPSHOTS` included to the `KafkaEmbedded` ctor alongside with the `RECEIVER_TOPIC` ?

**Comment by dmfrey** [comment]
@artembilan I've updated it to include it. But its really just constant that represents a topic name and it's different that events topic.

**Comment by garyrussell** [comment]
@dmfrey Artem's point is the `new KafkaEmbedded( 1, true, RECEIVER_TOPIC );` will pre-configure any topics in the list.

If you don't do that there might be a race - auto provisioning on the broker seems to be async so you might get errors when initially publishing to a new topic.

**Comment by artembilan** [comment]
Yeah... Right, my point is like this:
```
@ClassRule
public static KafkaEmbedded embeddedKafka = new KafkaEmbedded( 1, true, RECEIVER_TOPIC, BOARD_EVENTS_SNAPSHOTS);
```

**Comment by dmfrey** [comment]
I was able to get this resolved by using @artembilan recommendation above. @sobychacko asked me to create a PR with a test that demonstrates the groupby and aggregation. I will try to do that sometime this week or next.
