### ISSUE TITLE
Losing messages when restarting ConcurrentMessageListenerContainer

### ISSUE THREAD

**Issue by lbak** [spring-projects/spring-kafka#594]
I have a similar approach that was described [here](https://github.com/spring-projects/spring-kafka/issues/126) when there is a fatal error but instead of only stoping particular `ConcurrentMessageListenerContainer` I am also starting it as below.

```java
    private static class RestartBatchErrorHandler implements BatchErrorHandler {
        private final KafkaListenerEndpointRegistry listenerEndpointRegistry;
        private final String listenerId;

        private final AtomicBoolean restarting = new AtomicBoolean(false);

        private RestartBatchErrorHandler(KafkaListenerEndpointRegistry listenerEndpointRegistry, String listenerId) {
            this.listenerEndpointRegistry = listenerEndpointRegistry;
            this.listenerId = listenerId;
        }

        @Override
        public void handle(Exception thrownException, ConsumerRecords<?, ?> data) {
            if (restarting.compareAndSet(false, true)) {
                listenerEndpointRegistry.getListenerContainer(listenerId).stop();
                listenerEndpointRegistry.getListenerContainer(listenerId).start();
                restarting.set(false);
            }
        }
    }
```
My `ListenerContainerFactory` configuration
```java
    @PostConstruct
    private void kafkaListenerContainerFactory() {
        properties.getConsumers().forEach((key, value) -> {
            ConcurrentKafkaListenerContainerFactory<Integer, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
            factory.setConcurrency(value.getConcurrency());
            factory.setBatchListener(value.isBatchMode());
            factory.getContainerProperties().setPollTimeout(value.getPollTimeout());
            factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL);
            factory.getContainerProperties().setAckOnError(false);
            factory.getContainerProperties().setGenericErrorHandler(new RestartBatchErrorHandler(listenerEndpointRegistry,
                                                                                                 value.listenerId));
            factory.setConsumerFactory(consumerFactory(value));
            beanFactory.registerSingleton(value.containerId, factory);
        });
    }
```
I am using `spring-kafka:1.1.3.RELEASE`.

With the configuration above I can see that I am losing messages.

I thought at the beginning that the issue is that I am not using separate thread while restarting as was mentioned [here](https://github.com/spring-projects/spring-kafka/issues/126#issuecomment-259138893) but it does not look like.

Thanks in advance for any help.

**Comment by garyrussell** [comment]
Sorry for the delay; this one fell through the cracks. Can you show the rest of your configuration (consumer factory etc).

Also, I would recommend upgrading to at least version 1.3.3 (the current version is 2.1.4). 1.3.x introduced a much simpler threading model, thanks to KIP-62.

**Comment by lbak** [comment]
```java
private ConsumerFactory<Integer, String> consumerFactory(Properties.Consumer consumer) {
        return new DefaultKafkaConsumerFactory<>(ImmutableMap.<String, Object>builder().
                put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName()).
                put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName()).
                put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, properties.getBootstrapServers()).
                put(ConsumerConfig.GROUP_ID_CONFIG, consumer.getGroup()).
                put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, consumer.getAutoOffsetReset()).
                put(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, consumer.getMaxPartitionFetchBytes()).
                put(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, 1).
                put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false).
                put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, consumer.getMaxPollRecords()).
                build());
    }
```
Please let me know if you need more details

**Comment by lbak** [comment]
I have:
- upgraded to `spring-kafka:1.3.3.RELEASE`
- started to invoking `beanFactory.initializeBean(factory, value.containerId)` just after `registerSingleton` 

When I have deployed it to production I have noticed that topic's lag growing very fast like the offset was not committing (my kafka version on production is 0.11.0.0)

Do I miss something in my configuration?

**Comment by garyrussell** [comment]
factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL);

With manual ack mode, you have to do the acks - are you doing that? Show your listener code. Do you really need MANUAL acks? It's generally better to let the container manage the offsets.

**Comment by lbak** [comment]
I have already set it please look at the code snippet above but I think it might be related to the fact that  `put(ConsumerConfig.GROUP_ID_CONFIG, consumer.getGroup())` is not taken under consideration. I can see that a new group was created so all commits are going to it but I need to confirm it.

**Comment by garyrussell** [comment]
I don't understand what you are trying to do; how do all these factories get associated with a `@KafkaListener` ?

**Comment by lbak** [comment]
All these factories are associated by `containerId` please see below

```java
@KafkaListener(
  id = "${value.listenerId}",
  topics = "${value.topic}",
  containerFactory = "${value.containerId}"
)
```

So the problem is with missing `groupId` in `KafkaListener` annotation before when I was using `spring-kafka:1.1.3.RELEASE` I set it by using `put(ConsumerConfig.GROUP_ID_CONFIG, consumer.getGroup())` but now `spring-kafka:1.3.3.RELEASE` sets a default value for `groupId` . 

I need to set `groupId` in `@KafkaListener` and then the problem should be fixed (I have already tested)

**Comment by garyrussell** [comment]
To revert to the previous behavior, you can set `idIsGroup` to false.

```java
	/**
	 * When {@link #groupId() groupId} is not provided, use the {@link #id() id} (if
	 * provided) as the {@code group.id} property for the consumer. Set to false, to use
	 * the {@code group.id} from the consumer factory.
	 * @return false to disable.
	 * @since 1.3
	 */
	boolean idIsGroup() default true;
```
