### ISSUE TITLE
StringJsonMessageConverter doesn't work with List<Message<PO>>

### ISSUE THREAD

**Issue by realcbb** [spring-projects/spring-kafka#601]
`StringJsonMessageConverter` works well with `Message<PO>` as method parameter when using `@KafkaListener`, but doesn't work with `List<Message<PO>>` in batch listener mode. Already set `factory.setMessageConverter(new BatchMessagingMessageConverter(jsonMessageConverter));`. 
It seems that the listener does not using `StringJsonMessageConverter` to convert each record when the message parameter `isMessageList`.

**Comment by garyrussell** [comment]
Confirmed.

Do you really need the complete message?

This works...

```java
@KafkaListener(...)
public void listen1(List<Foo> foos, @Header(KafkaHeaders.RECEIVED_TOPIC) List<String> topics,
		@Header(KafkaHeaders.RECEIVED_PARTITION_ID) List<Integer> partitions) {
    ...
}
```
