### ISSUE TITLE
Allow setting MAX_POLL_INTERVAL_MS_CONFIG using KafkaProperties.Consumer

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-kafka#604]
Add a property to `org.springframework.boot.autoconfigure.kafka.KafkaProperties.Consumer` to allow users setting the value for `MAX_POLL_INTERVAL_MS_CONFIG` (`max.poll.interval.ms`) using properties.

**Comment by behrangsa** [comment]
This issue can be extended to ensure all these settings can be configured using `KafkaProperties.Consumer`:

* GROUP_ID_CONFIG = "group.id"
* MAX_POLL_RECORDS_CONFIG = "max.poll.records"
* MAX_POLL_INTERVAL_MS_CONFIG = "max.poll.interval.ms"
* SESSION_TIMEOUT_MS_CONFIG = "session.timeout.ms"
* HEARTBEAT_INTERVAL_MS_CONFIG = "heartbeat.interval.ms"
* BOOTSTRAP_SERVERS_CONFIG = CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG
* ENABLE_AUTO_COMMIT_CONFIG = "enable.auto.commit"
* AUTO_COMMIT_INTERVAL_MS_CONFIG = "auto.commit.interval.ms"
* PARTITION_ASSIGNMENT_STRATEGY_CONFIG = "partition.assignment.strategy"
* AUTO_OFFSET_RESET_CONFIG = "auto.offset.reset"
* FETCH_MIN_BYTES_CONFIG = "fetch.min.bytes"
* FETCH_MAX_BYTES_CONFIG = "fetch.max.bytes"
* FETCH_MAX_WAIT_MS_CONFIG = "fetch.max.wait.ms"
* METADATA_MAX_AGE_CONFIG = CommonClientConfigs.METADATA_MAX_AGE_CONFIG
* MAX_PARTITION_FETCH_BYTES_CONFIG = "max.partition.fetch.bytes"
* SEND_BUFFER_CONFIG = CommonClientConfigs.SEND_BUFFER_CONFIG
* RECEIVE_BUFFER_CONFIG = CommonClientConfigs.RECEIVE_BUFFER_CONFIG
* CLIENT_ID_CONFIG = CommonClientConfigs.CLIENT_ID_CONFIG
* RECONNECT_BACKOFF_MS_CONFIG = CommonClientConfigs.RECONNECT_BACKOFF_MS_CONFIG
* RECONNECT_BACKOFF_MAX_MS_CONFIG = CommonClientConfigs.RECONNECT_BACKOFF_MAX_MS_CONFIG
* RETRY_BACKOFF_MS_CONFIG = CommonClientConfigs.RETRY_BACKOFF_MS_CONFIG
* METRICS_SAMPLE_WINDOW_MS_CONFIG = CommonClientConfigs.METRICS_SAMPLE_WINDOW_MS_CONFIG
* METRICS_NUM_SAMPLES_CONFIG = CommonClientConfigs.METRICS_NUM_SAMPLES_CONFIG
* METRICS_RECORDING_LEVEL_CONFIG = CommonClientConfigs.METRICS_RECORDING_LEVEL_CONFIG
* METRIC_REPORTER_CLASSES_CONFIG = CommonClientConfigs.METRIC_REPORTER_CLASSES_CONFIG
* CHECK_CRCS_CONFIG = "check.crcs"
* KEY_DESERIALIZER_CLASS_CONFIG = "key.deserializer"
* VALUE_DESERIALIZER_CLASS_CONFIG = "value.deserializer"
* CONNECTIONS_MAX_IDLE_MS_CONFIG = CommonClientConfigs.CONNECTIONS_MAX_IDLE_MS_CONFIG
* REQUEST_TIMEOUT_MS_CONFIG = CommonClientConfigs.REQUEST_TIMEOUT_MS_CONFIG
* INTERCEPTOR_CLASSES_CONFIG = "interceptor.classes"
* EXCLUDE_INTERNAL_TOPICS_CONFIG = "exclude.internal.topics"
* LEAVE_GROUP_ON_CLOSE_CONFIG = "internal.leave.group.on.close"
* ISOLATION_LEVEL_CONFIG = "isolation.level"

**Comment by artembilan** [comment]
This is not Spring Kafka question, but indeed Spring Boot one.

However I think we the answer there for you: https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/htmlsingle/#boot-features-kafka-extra-props.

So, what you are asking can be done like this:
```
spring.kafka.consumer.properties.max.poll.interval.ms = 100
```

**Comment by behrangsa** [comment]
Thanks @artembilan. I think we can close the issue.
