### ISSUE TITLE
Upgrade to kafka 1.0.1

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-kafka#608]
The recent kafka1.0.1 release fixes a bug that made joining streams on windows machines impossible. It would be nice if spring used the kafka 1.0.1 version of kafka clients and kafka streams

**Comment by garyrussell** [comment]
Already done: https://github.com/spring-projects/spring-kafka/commit/1d080e711be666cfb66395f68f8b41985a77b97f

We are planning on releasing 2.1.5 on March 28.

**Comment by jbotuck** [comment]
OK, thanks.
