### ISSUE TITLE
How do we inject user defined Key/Value serializer/deserializer objects?

### ISSUE THREAD

**Issue by kvmkreddy** [spring-projects/spring-kafka#61]

**Comment by garyrussell** [comment]
Just add them to the consumer/producer properties - see [this test case](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java#L82).

**Comment by kvmkreddy** [comment]
Thank you very much for your quick response.

How can we inject user defined decoders references instead of Kafka creating/stubbing object?
Example of user defined decoder:
```
 	<bean id="kafkaConfluentValueDecoder" class="com.my.own.KafkaAvroDecoder">
		<constructor-arg >
			<bean class="kafka.utils.VerifiableProperties">
				<constructor-arg>
					<props>
						<prop key="schema.registry.url">http://localhost:8081</prop>
						<prop key="something.else.key">something_else_value</prop>
					</props>
				</constructor-arg>
			</bean>
		</constructor-arg>
	</bean>
```

**Comment by garyrussell** [comment]
The Kafka 0.9 client doesn't support it - it has no APIs for that.

The scala `Decoder` and `Encoder` APIs are not supported by the pure Java 0.9 API.

You need to implement `Serializer` (and `Deserializer`) and the producer/consumer properties object (in which the class is defined is passed into the `configure()` method.

**Comment by garyrussell** [comment]
Please reopen if you have more concerns.

**Comment by kvmkreddy** [comment]
Both kafka consumer and producer implementations are provided API where we can inject custom Serializer/Deserializer implementations.

Find the below consumer API for example:
```
    public KafkaConsumer(Map<String, Object> configs,
                         Deserializer<K> keyDeserializer,
                         Deserializer<V> valueDeserializer) {
        this(new ConsumerConfig(ConsumerConfig.addDeserializerToConfig(configs, keyDeserializer, valueDeserializer)),
            keyDeserializer,
            valueDeserializer);
    }
```

My thoughts on spring kafka API:

It should allow clients to inject their own serializer/deserializer implementations in addition to providing 
default behavior of kafka API to create these instances.

For example [DefaultKafkaConsumerFactory](https://github.com/kvmkreddy/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java) implementation will be like 
```
private KafkaConsumerProducerStrategy<K,V> strategy;

public DefaultKafkaConsumerFactory(Map<String, Object> configs, KafkaConsumerProducerStrategy<K,V> strategy) {
			this.configs = new HashMap<>(configs);
			this.strategy = strategy;
	}

@Override
public Consumer<K, V> createConsumer() {
	return createKafkaConsumer();
}

protected KafkaConsumer<K, V> createKafkaConsumer() {
	return this.strategy.createKafkaConsumer();
}

```

Default implementation of [KafkaConsumerProducerStrategy](https://github.com/kvmkreddy/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerProducerStrategy.java) strategy looks like:

```
public class DefaultKafkaConsumerProducerStrategy<K,V> implements KafkaConsumerProducerStrategy<K,V> {

		private final Map<String, Object> configs;		
		
		public DefaultKafkaConsumerProducerStrategy(Map<String, Object> configs) {
			this.configs = new HashMap<>(configs);	
		}		

		@Override	
		public KafkaConsumer<K,V> createKafkaConsumer() {		
			return new KafkaConsumer<K,V>(this.configs);	
		}	

		@Override	
		public KafkaProducer<K,V> createKafkaProducer() {		
			return new KafkaProducer<K, V>(this.configs);	
		}
}

```

Extended implementation of this [KafkaConsumerProducerStrategy](https://github.com/kvmkreddy/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/ExtendedKafkaConsumerProducerStrategy.java) looks like:

```
public class ExtendedKafkaConsumerProducerStrategy<K,V> implements KafkaConsumerProducerStrategy<K,V> {
	
	private final Map<String, Object> configs;
	private Serializer<K> keySerializer;
	private Serializer<V> valueSerializer;
	private Deserializer<K> keyDeserializer;
	private Deserializer<V> valueDeserializer;

	public ExtendedKafkaConsumerProducerStrategy(Map<String, Object> configs, Deserializer<K> keyDeserializer,	Deserializer<V> valueDeserializer) {
		 super();
		 this.configs = configs;
		 this.keyDeserializer = keyDeserializer;
		 this.valueDeserializer = valueDeserializer;
	}

	public ExtendedKafkaConsumerProducerStrategy(Map<String, Object> configs, Serializer<K> keySerializer,	Serializer<V> valueSerializer) {
		 super();
		 this.configs = configs;
		 this.keySerializer = keySerializer;
		 this.valueSerializer = valueSerializer;
	}

	@Override
	public KafkaConsumer<K, V> createKafkaConsumer() {
		 return new KafkaConsumer<K,V>(this.configs,this.keyDeserializer,this.valueDeserializer);
	}

	@Override
	public KafkaProducer<K, V> createKafkaProducer() {
		return new KafkaProducer<K,V>(this.configs,this.keySerializer,this.valueSerializer);
	}
}

```

Complete implementation will be available [here](https://github.com/kvmkreddy/spring-kafka)

**Comment by garyrussell** [comment]
Thanks for pointing that out; I hadn't looked at the API recently, my bad.

Please consider "signing" the CLA and issue a pull request.

[Contribution guidelines are here](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc).

We are planning on releasing the 1.0 release candidate next week so a quick turn-around would be helpful.

**Comment by kvmkreddy** [comment]
Created pull request [65](https://github.com/spring-projects/spring-kafka/pull/65) for this change.

Please let me know your comments if any on this change
