### ISSUE TITLE
Unable to find way to re-initialize @KafkaListener annotated method.

### ISSUE THREAD

**Issue by rohitverma1986** [spring-projects/spring-kafka#611]
Is there a way to apply changes in consumer properties during runtime.
I am trying to change consumer properties by making change in a property file, which will be watched by @Scheduled method( this will look for change in any property value and re-initialize the consumer after updating container factory bean instance picked from application context).
Or please suggest the right way to do so.

**Comment by garyrussell** [comment]
Which properties? You can't change the topic(s), but most other properties can be changed by stopping the container changing its properties and starting it again.

Use the `KafkaListenerEndpointRegistry` to get a reference to the container (using the `@KafkaListener` `id`).

- call `container.stop()`
- call  `container.getContainerProperties()` and reconfigure
- call `container.start()`

**Comment by garyrussell** [comment]
In future, please use StackOverflow or gitter for questions. Issues are for bug reports or new feature requests.

**Comment by rohitverma1986** [comment]
Sorry Gary for raising this as an issue. I want to introduce new broker or change consumer group name or any other ConsumerConfig's property. 
KafkaListenerEndpointRegistry kler = context.getBean(KafkaListenerEndpointRegistry.class);
kler.stop();
MessageListenerContainer lc = kler.getListenerContainer("Test4Consumer1").

Can't go beyond this.

**Comment by artembilan** [comment]
>  I want to introduce new broker or change consumer group name or any other ConsumerConfig's property.

That's already a `DefaultKafkaConsumerFactory` responsibility, or even better to say the `Map` you inject into the `DefaultKafkaConsumerFactory`. You can change the content of that map and really `stop()` and `start()` for the `MessageListenerContainer` would be enough. When we start a container, we call `new ListenerConsumer(this.listener, listenerType);` which, in turn, `KafkaMessageListenerContainer.this.consumerFactory.createConsumer()`.

However a `consumerGroupId` indeed should be changed via `ContainerProperties`.

**Comment by artembilan** [comment]
Closed in favor of: https://stackoverflow.com/questions/49408270/spring-kafka-integration-changing-consumerconfig-property-without-restarting-a

**Comment by garyrussell** [comment]
You can't change the broker addresses with the `DefaultKafkaConsumerFactory` - it only gives you read-access to its properties. If you build your own (rather than using Boot's) and keep a copy of the original config map, you can change the brokers.

Here's an example of how to change properties that can be change...

```java
@SpringBootApplication
public class Kgh611Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh611Application.class, args);
	}

	private volatile CountDownLatch latch = new CountDownLatch(1);

	@Bean
	public ApplicationRunner runner(KafkaTemplate<String, String> template, KafkaListenerEndpointRegistry registry) {
		return args -> {
			template.send("kgh611a", "foo");
			this.latch.await(10, TimeUnit.SECONDS);
			registry.stop();
			MessageListenerContainer container = registry.getListenerContainer("foo");
			container.getContainerProperties().setGroupId("group2");
			this.latch = new CountDownLatch(1);
			registry.start();
			this.latch.await(10, TimeUnit.SECONDS);
			registry.stop();
		};
	}

	@KafkaListener(id = "foo", topics = "kgh611a", groupId = "group1")
	public void listen(String in) {
		System.out.println(in);
		this.latch.countDown();
	}

	@Bean
	public NewTopic topic() {
		return new NewTopic("kgh611a", 1, (short) 1);
	}

}
```

**Comment by artembilan** [comment]
Ah! I see: `this.configs = new HashMap<>(configs);` and also `return Collections.unmodifiableMap(this.configs);`. But nobody stops you to implement your own `ConsumerFactory`! There is not too much code in the `DefaultKafkaConsumerFactory` to replicate :smile:
