### ISSUE TITLE
Expose application.id / StreamsConfig from StreamsBuilderFactoryBean

### ISSUE THREAD

**Issue by zacholauson** [spring-projects/spring-kafka#618]
I'm working on a project where we are managing multiple Kafka Streams applications using `StreamsBuilderFactoryBean` and I'm looking to get access to some of the properties stored in the StreamsConfig, specifically `application.id`.

I was planning to open a PR to expose the `application.id` since it's a required property and a (seemingly) good identifier for the streams instance, but I figured it would probably make more sense to run this by you all beforehand. 

Does this seem like a reasonable addition to `StreamsBuilderFactoryBean` and if so, should just `application.id` be exposed, or would it make more sense to expose the whole `StreamsConfig`?

**Comment by artembilan** [comment]
Well, the `StreamsBuilderFactoryBean` is fully based on the injected `StreamsConfig`.
While there is no `getStreamsConfig()` yet you can consider to use those external `StreamsConfig` beans to get desired information.

**Comment by zacholauson** [comment]
Sounds good, I'll plan to open a PR tonight @garyrussell.

That's a good point @artembilan, unfortunately in our case I don't think it will work. We currently have a few streams applications in our service, each with slightly different configs (mostly just application.id), so we would have several pairs of StreamsConfigs and StreamsBuilderFactoryBean, without any connection between them.
