### ISSUE TITLE
Add StateRestoreListener customization.

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-kafka#621]
Would you consider `StateRestoreListener` customization through `StreamsBuilderFactoryBean`? So it can be passed via `KafkaStreams#setGlobalStateRestoreListener`. Extending the factory bean does not work because `KafkaStreams` has private access.

Maybe a better solution would be providing an interface like `KafkaStreamsCustomizer` such that; 

`StateListener`, `UncaughtExceptionHandler`, `cleanupOnStart` and `cleanupOnStop` can be configured through.

**Comment by artembilan** [comment]
Works either way for me.

I even think that both: `setStateRestoreListener()` and `KafkaStreamsCustomizer` are good candidates for improvement.

Contribution is welcome!

**Comment by nyilmaz** [comment]
Signed CLA
