### ISSUE TITLE
If I don't acknowledge a message, will the next poll() use the current offset in manual ackmode?

### ISSUE THREAD

**Issue by Ayman250** [spring-projects/spring-kafka#628]
```
@KafkaListener(topics = "TOPIC", containerFactory = "kafkaListenerContainerFactory")
    public void listen(@Payload(required = false) List<String> messages, Acknowledgment acknowledgment){
        try {
            /* PROCESS */
            }
            acknowledgment.acknowledge();

        }
        catch (Exception e){
            logger.error("Error in processing: ", e.getMessage());
            e.printStackTrace();
        }

    }
```
When a message fails to process, the acknowledge is never called. I was under the impression that in manual ack mode, you must acknowledge to move the offset and so if you haven't, when poll() is called, it should use the same offset. Am I not understanding this correctly, and in that case, how can I guarantee at-least once processing.? (VERSION 1.1.3)

**Comment by garyrussell** [comment]
No; you have to perform a seek operation to reset the offset for this consumer on the broker.

It's not easy with such an old version; in the current versions (since 2.0.1) we have the `SeekToCurrentErrorHandler`.

With older versions, your listener has to implement `ConsumerSeekAware`, perform the seek operation on the `ConsumerSeekCallback` (which has to be saved during initialization) and add logic to discard/seek remaining records in the batch until the failed message reappears.

I said it wasn't easy.

I would recommend upgrading to the current version (2.1.4); the newer clients can talk to older brokers (at least back to 0.10.2.0 IIRC).

**Comment by garyrussell** [comment]
Another alternative is to stop and restart the container after the exception; the record will be redelivered after the restart.

**Comment by Ayman250** [comment]
@garyrussell Thank you! Can what is the appropriate way to stop and restart the container or where can I read about it?

**Comment by garyrussell** [comment]
Newer versions have the [ContainerStoppingErrorHandler](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingErrorHandler.java#L37). While your version doesn't have `ContainerAwareErrorHandler` you can use the same technique by getting a reference to the container some other way. The stop must be performed on a separate thread.

You would still have to discard any remaining records retrieved by the previous poll in your listener.

**Comment by Ayman250** [comment]
Thanks for the help. I was wondering, If I catch the error and run 
`kafkaListenerEndpointRegistry.stop();
  kafkaListenerEndpointRegistry.start();`
Will that have the desired effect? I did some reading and it seems you can restart the listener container in this manner.

**Comment by garyrussell** [comment]
Yes; that will work but you should not run the stop() on the listener thread and you should wait for it to stop before restarting.

**Comment by garyrussell** [comment]
If you use the `stop(Runnable runnable)` variant, the `Runnable` is called when the container is completely stopped and it's safe to restart.

**Comment by Ayman250** [comment]
Thank you. How can I ensure that the stop is not being run on the listener thread?

**Comment by garyrussell** [comment]
Use an executor like in [the error handler I pointed you to above](https://github.com/spring-projects/spring-kafka/issues/628#issuecomment-377057367)

**Comment by Ayman250** [comment]
Thank you. That is what I suspected, but I wanted to be sure. Thank you very much! I appreciate it.

**Comment by Ayman250** [comment]
@garyrussell If possible, can you point to an example of a properly implemented ContainerStoppingErrorHandler? I'm have some issues using it correctly.

**Comment by garyrussell** [comment]
```java
@SpringBootApplication
public class Kgh628Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh628Application.class, args);
	}

	final AtomicBoolean failed = new AtomicBoolean();

	@Autowired
	private MyErrorHandler errorHandler;

	@KafkaListener(id = "kgh628", topics = "kgh628")
	public void listen(String in, Acknowledgment ack) {
		if (this.errorHandler.isStopping()) {
			System.out.println("discarding: " + in);
		}
		else if (!failed.getAndSet(true)) {
			System.out.println("failing: " + in);
			throw new RuntimeException("reject");
		}
		else {
			System.out.println("OK: " + in);
			failed.set(false);
			ack.acknowledge();
		}
	}

	@Bean
	public NewTopic topic() {
		return new NewTopic("kgh628", 1, (short) 1);
	}

	@Bean
	public ConcurrentKafkaListenerContainerFactory<?, ?> kafkaListenerContainerFactory(
			ConcurrentKafkaListenerContainerFactoryConfigurer configurer,
			ConsumerFactory<Object, Object> kafkaConsumerFactory,
			MyErrorHandler errorHandler) {
		ConcurrentKafkaListenerContainerFactory<Object, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
		configurer.configure(factory, kafkaConsumerFactory);
		factory.getContainerProperties().setErrorHandler(errorHandler);
		return factory;
	}

	@Bean
	public MyErrorHandler errorHandler(KafkaListenerEndpointRegistry registry) {
		return new MyErrorHandler(registry);
	}

	public static class MyErrorHandler implements ErrorHandler {

		private final KafkaListenerEndpointRegistry registry;

		private final Executor executor = new SimpleAsyncTaskExecutor();

		private volatile boolean stopping;

		public MyErrorHandler(KafkaListenerEndpointRegistry registry) {
			this.registry = registry;
		}

		public boolean isStopping() {
			return this.stopping;
		}

		@Override
		public void handle(Exception thrownException, ConsumerRecord<?, ?> data) {
			this.stopping = true;
			this.executor.execute(() -> {
				this.registry.stop(() -> {
					this.registry.start();
					this.stopping = false;
				});
			});
			this.registry.getListenerContainers().forEach(c -> {
				while (c.isRunning()) {
					try {
						Thread.sleep(100);
					}
					catch (InterruptedException e) {
						Thread.currentThread().interrupt();
						break;
					}
				}
			});
		}

	}

}
```

I added 2 messages to the topic before starting this...

```
2018-03-30 13:01:47.264  INFO 28689 --- [   kgh628-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [kgh628-0]
failing: foo
discarding: bar
2018-03-30 13:01:47.387  INFO 28689 --- [   kgh628-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-03-30 13:01:47.390  INFO 28689 --- [   kgh628-0-C-1] essageListenerContainer$ListenerConsumer : Consumer stopped
...
2018-03-30 13:01:50.410  INFO 28689 --- [   kgh628-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [kgh628-0]
OK: foo
failing: bar
2018-03-30 13:01:50.518  INFO 28689 --- [   kgh628-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-03-30 13:01:50.521  INFO 28689 --- [   kgh628-0-C-1] essageListenerContainer$ListenerConsumer : Consumer stopped
...
2018-03-30 13:01:53.538  INFO 28689 --- [   kgh628-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [kgh628-0]
OK: bar
```

**Comment by sustainablepace** [comment]
This is solved by acknowledgement.nack() since 2.3

**Comment by matijatrajkovic993** [comment]
> This is solved by acknowledgement.nack() since 2.3

Thank you for this!
