### ISSUE TITLE
Is there way to commitSync() in Spring Kafka on Consumer side?

### ISSUE THREAD

**Issue by shrikantpatel** [spring-projects/spring-kafka#63]
In our use case we want to synchronously commit as soon as the message is proceed by the consumer. From looking at the http://docs.spring.io/spring-kafka/docs/1.0.0.M2/reference/htmlsingle/ I don't see a way to do this with current version of API.

I do see there is MANUAL_IMMEDIATE, but still the underlying its commitAsync(). Is there a way of synchronously committing the offset?

**Comment by garyrussell** [comment]
Thanks for the feedback, not currently, but we'll add an option.
