### ISSUE TITLE
Spring Kafka vs. Spring Cloud Stream

### ISSUE THREAD

**Issue by steve-roy** [spring-projects/spring-kafka#643]
Hi,

When would it be recommended to use Spring Kafka vs Spring Cloud Stream?

Thank you,
- steve

**Comment by artembilan** [comment]
Closed in favor of: https://github.com/spring-cloud/spring-cloud-stream/issues/1350.

Unfortunately the same people here and here, so apparently you won't get different answers for the questions :smile:
