### ISSUE TITLE
Question about KafkaTemplate and KafkaTransactionManager.

### ISSUE THREAD

**Issue by Gunju-Ko** [spring-projects/spring-kafka#649]
Hi I have a question about KafkaTemplate and KafkaTransactionManager.
Please understand that I'm not good at english

### KafkaTemplate's inTransaction()
KafkaTransactionManager's default transactionSynchronization is `SYNCHRONIZATION_NEVER`, So TransactionSynchronizationManager.isActualTransactionActive() return false through KafkaTransactionManager begin transaction. As a result inTransaction method return false even thougn KafkaTransactionManager begin transaction.  

				
```java
protected boolean inTransaction() {
	return this.producers.get() != null || TransactionSynchronizationManager.isActualTransactionActive();
}
```

### KafkaTemplate's doSend method 
If a transaction is active, any KafkaTemplate operations performed within the scope of the transaction will use the transaction’s Producer. The problem is that KafkaTemplate close the transaction's Producer after send a message. The code below is doSend method in KafkaTemplate.
```java
final boolean inLocalTx = inTransaction();
producer.send(producerRecord, new Callback() {
	@Override
	public void onCompletion(RecordMetadata metadata, Exception exception) {
		try {
			// skip
		}
		finally {
			if (KafkaTemplate.this.producers.get() == null) {
				closeProducer(producer, inLocalTx);
			}
		}
    }
});
```
 
If inLocalTx is false, call the Producer's close() method in the callback method. So CloseSafeProducer is returned to the cache. And if another transaction begins in the another thread It can be use returned CloseSafeProducer which is not commit transaction yet. As a result exception is occur (Invalid transition attempted from state IN_TRANSACTION to state IN_TRANSACTION)

I think inTransaction() method check that `TransactionSynchronizationManager
				.getResource(producerFactory)` is not null (That mean KafkaTransactionManager begin transaction and not committed)
				
```java
protected boolean inTransaction() {
	return this.producers.get() != null || TransactionSynchronizationManager.isActualTransactionActive() || TransactionSynchronizationManager
				.getResource(producerFactory) != null;
}
```

**Comment by garyrussell** [comment]
Yes; thanks; I found the same problem; it was fixed yesterday... https://github.com/spring-projects/spring-kafka/commit/42e2d01026636cdb76e341af3759e04c4315e48c

**Comment by Gunju-Ko** [comment]
Thank you for your reply.
