### ISSUE TITLE
Externally subscribe to ConsumerRebalanceListener

### ISSUE THREAD

**Issue by martindam** [spring-projects/spring-kafka#66]
In order for applications to react to a kafka consumer rebalance, it would be very helpful to expose the ConsumerRebalanceListener in the native KafkaConsumer. For example to ensure offset and/or state is committed before another instance takes over the partition. This is currently not possible with the current implementation of KafkaMessageListenerContainer. 

Do you plan to add support for this?

**Comment by garyrussell** [comment]
Thanks for the feedback; it's certainly something we can look at.

**Comment by garyrussell** [comment]
[Contributions are welcome](https://github.com/garyrussell/spring-kafka/blob/master/CONTRIBUTING.adoc) 😄

**Comment by kvmkreddy** [comment]
Can you check whether this [fix](https://github.com/spring-projects/spring-kafka/pull/67)

**Comment by garyrussell** [comment]
Thanks for the contribution @kvmkreddy !!

However, we need to have the default listener call the injected one (if provided) - the container needs to know the assigned partitions (see `getAssignedPartitions()`); we'd also still see the log messages.

I can make those changes to your commit if you don't have time.

**Comment by kvmkreddy** [comment]
Below is listener implementation which is used by KafkaConsumer
```
ConsumerRebalanceListener rebalanceListener = new ConsumerRebalanceListener() {

				@Override
				public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
					KafkaMessageListenerContainer.this.consumerRebalanceListener.onPartitionsRevoked(partitions);
				}

				@Override
				public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
					ListenerConsumer.this.assignedPartitions = partitions;
					KafkaMessageListenerContainer.this.consumerRebalanceListener.onPartitionsAssigned(partitions);
				}

			};
```
Above implementation is invoking onPartitionsRevoked() and onPartitionsAssigned() on the user injected(if provided) or default implementation(if not provided) which have log messages..

```
	protected final ConsumerRebalanceListener createConsumerRebalanceListener() {
		return new ConsumerRebalanceListener() {

			@Override
			public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
				logger.info("partitions revoked:" + partitions);
			}

			@Override
			public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
				logger.info("partitions assigned:" + partitions);
			}

		};
	} 
```

**Comment by garyrussell** [comment]
Sorry - my mistake - I obviously didn't look carefully enough - please go ahead and issue a PR - thanks again !!

**Comment by artembilan** [comment]
I see the PR is here #67 already.
Thank @kvmkreddy for contribution!
