### ISSUE TITLE
Single shared KafkaEmbedded is all JUnit tests

### ISSUE THREAD

**Issue by evgeniy-khist** [spring-projects/spring-kafka#666]
It seems like there is no convenient way to define single shared KafkaEmbedded that will be used in all JUnit tests.

There might be multiple tests that require `KafkaEmbedded`.
When `@KafkaEmbedded` is used with `@ClassRule`, Kafka server is started and stopped for every test class. 
It may take a lot of time. Better to have embedded Kafka server started only once for all test classes.

Straightforward approach is to add to test sources configuration class defining a `KafkaEmbedded` bean:

```java
@Configuration
public class KafkaEmbeddedConfig {

  @Bean
  public KafkaEmbedded kafkaEmbedded() {
    KafkaEmbedded kafkaEmbedded = new KafkaEmbedded(1, false, 1, "test_topic");
    kafkaEmbedded.setKafkaPorts(9092);
    return kafkaEmbedded;
  }
}
```

The problem is that there might tests creating multiple test contexts:

```java
@TestPropertySource("classpath:test.properties")
@RunWith(SpringRunner.class)
@SpringBootTest
public class KafkaListenerTest {
...
```

and

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureMockMvc
public class RestControllerTest {
...
```

In this example Kafka server will be started twice. Second executed test class will fail with the exception 

```
Caused by: kafka.common.KafkaException: Socket server failed to bind to localhost:9092: Address already in use.
```

if port is specified or new Kafka server will be started if random port is used.

Moreover, if `@DirtiesContext` is used, together with the refresh of the test context Kafka server will be restarted.

As a workaround `KafkaEmbedded` can be defined as a constant in some base test class that test classes will extend:

```java
@ActiveProfiles("kafka")
public class KafkaTestBase {

  public static final KafkaEmbedded KAFKA_EMBEDDED = createKafkaEmbedded();

  private static KafkaEmbedded createKafkaEmbedded() {
    AnnotationConfigApplicationContext context =
        new AnnotationConfigApplicationContext(KafkaEmbeddedConfig.class);
    KafkaEmbedded kafkaEmbedded = context.getBean(KafkaEmbedded.class);
    Runtime.getRuntime().addShutdownHook(new Thread(context::close));
    return kafkaEmbedded;
  }
}
```

```java
@TestPropertySource("classpath:test.properties")
@RunWith(SpringRunner.class)
@SpringBootTest
public class KafkaListenerTest extends KafkaTestBase {
...
```

This way Kafka server will be started in a separate Spring application context that will not be affected by `@DirtiesContext` or multiple test contexts (due to the usage of `@AutoConfigureMockMvc` etc.).

**Can such approach be considered a normal solution or a workaround?
Are there any more efficient ways to have single shared `KafkaEmbedded` instance across all JUnit tests?**

Sample:

* Repo with sample project reproducing the problem with exception `BindException: Address already in use`: https://github.com/evgeniy-khist/spring-kafka-embedded-sample
* Fix making `KafkaEmbedded` a constant of base test class:
https://github.com/evgeniy-khist/spring-kafka-embedded-sample/pull/1/files

**Comment by artembilan** [comment]
How about this: https://docs.spring.io/spring-kafka/docs/2.1.5.RELEASE/reference/html/_reference.html#__embeddedkafka_annotation ?

Although that sounds like you just need a fully blown external Kafka running and that's all.

**Comment by evgeniy-khist** [comment]
With `@EmbeddedKafka` there is a problem also.
When I have multiple tests using this annotation each of them passes when executed individually but fails when executed together.
Sample (branch embedded-kafka-annotation): https://github.com/evgeniy-khist/spring-kafka-embedded-sample/blob/embedded-kafka-annotation/src/test/java/com/example/kafka/sample/embedded/KafkaListenerTest.java
Maybe I just use it in a wrong way.
In my understanding, it's because I can't specify Kafka port to listen on in annotation and random one is used. So, in different test classes property `spring.kafka.bootstrap-servers=${spring.embedded.kafka.brokers}` resolves to different values. It is just an assumption.

**Comment by garyrussell** [comment]
You can use a [test suite](https://github.com/junit-team/junit4/wiki/aggregating-tests-in-suites) and put the embedded kafka broker there.

It's generally not a good idea to use a fixed port in tests since that port might be in use elsewhere on the server; this is particularly a problem on CI servers which might have multiple builds running.

However, since it's best to define the topics to the embedded server so that they are created before the tests start, the suite would have to be configured with all the required topics for all the tests.

**Comment by evgeniy-khist** [comment]
@garyrussell thank you for the answer.
A JUnit *test suite* was the first idea that came to my mind. But when a test suite is used Kafka-related tests can only be executed from the central class (suite class). It's not an optimal solution when there are a lot of tests using Kafka.

Hardcoded port in the sample is used for simplicity. Port can be specified as a property:

```java
@Value("${embedded.kafka.port:9092}")
private int port;

@Bean
public KafkaEmbedded kafkaEmbedded() {
  KafkaEmbedded kafkaEmbedded = new KafkaEmbedded(1, false, 1, "test_topic");
  kafkaEmbedded.setKafkaPorts(port);
  return kafkaEmbedded;
}
```

To avoid problems on CI with the port conflicts, a random port can be passed as a property:

```
./gradlew test -Dembedded.kafka.port=<RANDOM PORT>
```

Usage of a fixed port makes sure that only 1 instance of Kafka server is started.

To use random port chosen by Spring either `@EmbeddedKafka` or `@ClassRule` has to be used to have the property `spring.embedded.kafka.brokers` populated before test context will be started.
If `KafkaEmbedded` defined as a `@Bean` in a `@Configuration`, the property `spring.embedded.kafka.brokers` will be not be resolved (test context will need to resolve it before it will be set).

**Comment by evgeniy-khist** [comment]
@artembilan regarding `@EmbeddedKafka`. 

This annotation with the list of all topics has to be added to every class that requires Kafka.
When there are a lot of topics it's a big code duplication. The solution might be to create base Kafka test class, a single place where `@EmbeddedKafka` will be added:

```java
@EmbeddedKafka(topics = {"test_topic", "test_topic2"})
public class KafkaTestBase {

  @Autowired
  protected KafkaEmbedded kafkaEmbedded;

}
```

The problem is that with `@EmbeddedKafka` in the base class or each test class, second Kafka test class is failing from time to time. Messages are not delivered to the second listener when all tests executed in the group while passing when executed individually.

1. https://github.com/evgeniy-khist/spring-kafka-embedded-sample/tree/embedded-kafka-annotation
2. https://github.com/evgeniy-khist/spring-kafka-embedded-sample/tree/embedded-kafka-annotation-in-base-test-class (with base tests class there are more failures than successful build but maybe just coincidence).

Am I using `@EmbeddedKafka` in a wrong way?

**Comment by garyrussell** [comment]
@evgeniy-khist The attached PR seems to fit the bill.

**Comment by evgeniy-khist** [comment]
@garyrussell A section in the *testing.adoc* in the attached PR answers my question. Thanks!

**Comment by ashishkujoy** [comment]
Thanks, @artembilan, for let me know about this,

**Comment by artembilan** [comment]
I have decided to go ahead and introduce the mentioned listener as a framework component.
See the linked PR: https://github.com/spring-projects/spring-kafka/pull/2308

**Comment by estigma88** [comment]
Facing the same challenge, I was checking the `GlobalEmbeddedKafkaTestExecutionListener` class, but I didn't find a way to access the `EmbeddedKafkaBroker` instance. I need to do something as follows:

```
val consumerProps: MutableMap<String, Any> =  KafkaTestUtils.consumerProps(name, "true", kafka)

consumerProps[ConsumerConfig.AUTO_OFFSET_RESET_CONFIG] = "latest"

val cf: ConsumerFactory<String, String> = DefaultKafkaConsumerFactory(consumerProps, StringDeserializer(),           StringDeserializer())

val consumer: Consumer<String, String> = cf.createConsumer()

kafka.consumeFromAnEmbeddedTopic(consumer, topic)
```

Where `kafka` is the `EmbeddedKafkaBroker` instance.

Any advice would be appreciated.

**Comment by artembilan** [comment]
@estigma88 ,

This issue is old enough and resolved some way in mutual agreement.
It might be great if you raise your concern as new Stackoverflow question.
Just because I don't see relevance between your request and what we have done in this issue.

Now about the problem.
The `GlobalEmbeddedKafkaTestExecutionListener` is a JUnit feature. It has nothing (and knows nothing) about Spring.
Therefore when JUnit engine is started, this listener is triggered and all the test (Spring or not) might have access to embedded Kafka broker via regular Kafka Client connection.

I understand the convenience of the `consumeFromAnEmbeddedTopic()` API, but that is not available for when we use `GlobalEmbeddedKafkaTestExecutionListener` and cannot be because `GlobalEmbeddedKafkaTestExecutionListener` is not Spring environment component.
You may consider some other way: https://docs.spring.io/spring-kafka/reference/testing.html#same-broker-multiple-tests.

Or just design your tests if you would deal with real Kafka broker.
