### ISSUE TITLE
Safe use of batch listener?

### ISSUE THREAD

**Issue by michelbetancourt** [spring-projects/spring-kafka#672]
Hi,

I am trying to use spring-kafka 1.3.x (1.3.3 and 1.3.4).  What is not clear is whether there is a safe way to consume messages in batch without skipping a message (or set of messages) when an exception occurs eg network outage.

I am setting the following properties onto a ConcurrentMessageListenerContainer :
```
.setAckOnError(false);
.setAckMode(AckMode.MANUAL);
```

I am also setting the following kafka specific consumer properties:

```
enable.auto.commit=false
auto.offset.reset=earliest
```

If I set a RetryTemplate, I get a class cast exception since it only works for non-batch consumers.  Documentation states retry is not available for batch so this may be OK.

I then setup a consumer such as this one:
```java
@KafkaListener(containerFactory = "conatinerFactory",
                   groupId = "myGroup",
                   topics = "myTopic")
    public void onMessage(@Payload List<Entries> batchedData,
            @Header(required = false,
                    value = KafkaHeaders.OFFSET) List<Long> offsets,
			Acknowledgment ack) {
        log.info("Working on: {}" + offsets);
        int x = 1;
        if(x == 1) {
            log.info("Failure on: {}" + offsets);
            throw new RuntimeException("mock failure");
        }
        
        // do nothing else for now

        // unreachable code        
        ack.acknowledge();
        
   }
```

When I send a message into the system to mock the exception above then the only visible action to me is that the listener reports the exception.

When I send another (new) message into the system, the container consumes the new message.  The old message is skipped since the offset is advanced to the next offset.

Since I have asked the container not to acknowledge (directly or indirectly) and since there is no other properties that I can see to notify the container not to advance, then I am confused why the container does advance.  

What I noticed is that for a similar consideration, what is being recommended is to upgrade to 2.1.x and use the container stop capability that was added into the ContainerAware ErrorHandler there.

But what if you are trapped in 1.3.x for the time being, is there a way or missing property that can be used to ensure the container does not advance to the next message or batch of messages?

Thoughts?

**Comment by michelbetancourt** [comment]
I moved this question to stackoverflow since it's unclear whether this may be an issue with the spring-kafka module.

**Comment by garyrussell** [comment]
The offset has not been committed but the broker won't send the data again. You have to re-seek the topics/partitions.

2.1 provides the `SeekToCurrentBatchErrorHandler` which will re-seek automatically for you.

2.0 Added consumer-aware listeners, giving you access to the consumer (for seeking) in the listener.

With 1.3.x you have to implement `ConsumerSeekAware` and perform the seeks yourself (in the listener after catching the exception). Save off the `ConsumerSeekCallback` in a `ThreadLocal`.

You will need to add the partitions to your method signature; then seek to the lowest offset in the list for each partition.

**Comment by michelbetancourt** [comment]
@garyrussell thank you for your prompt feedback and reply.  I am updating stackoverflow with this information.

**Comment by garyrussell** [comment]
Can you add a link here? I don't see a recent question with the usual tags.

**Comment by michelbetancourt** [comment]
https://stackoverflow.com/questions/50234296/safe-way-to-use-batch-listener
