### ISSUE TITLE
KafkaEmbeddedHolder - topic created but not added.

### ISSUE THREAD

**Issue by nklmish** [spring-projects/spring-kafka#676]
NOTE: In order to reproduce this issue locally please clone https://github.com/nklmish/spring-kafka-issue-676 and execute `./gradlew clean test`.

I ll like to use the same broker(s) for multiple test classes (https://github.com/garyrussell/spring-kafka/commit/24c399ec8992707a35297207d6cc91dcc09fc0f9), and saw this example mentioned in [docs](https://docs.spring.io/spring-kafka/reference/htmlsingle/#_using_the_same_broker_s_for_multiple_test_classes). However, it seems that topic(s) are created in Kafka (I have verified this) but never appended inside [KafkaEmbedded#topics](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java#L121) as a result when we try to access a newly created topic, e.g.
`  embeddedKafka.consumeFromAnEmbeddedTopic(consumer, SOME_TOPIC);`
An assertion error gets thrown due to [this](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java#L481) .  

We should update the topic array after this [call](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java#L255). I can also submit a PR if the above suggestions sounds reasonable.

Thanks!

**Comment by garyrussell** [comment]
Agreed; thanks for the offer of a PR. We should not add them when called from before() though; maybe change the array to a Set? That will also save iterating over the array in `consumeFromEmbeddedTopics()`.

**Comment by nklmish** [comment]
Thank you, set sounds a good idea, however once we change `String[]` -> `Set`, we need to choose one of the following paths:
a). Don't change method signature and perform an internal conversion from `String[]` -> `Set` (it introduce a penalty for converting `list` to `set` in `addTopics` & `consumeFromEmbeddedTopics`)
b). Change method signature of [addTopics()](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java#L248) and [consumeFromEmbeddedTopics()](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java#L479) to accept `Set` instead of `Strings...`. It will introduce **backward incompatible changes**
c). Deprecate old methods and introduce new ones.
Thoughts ?

**Comment by garyrussell** [comment]
I would vote for option `a)` - don't worry about overhead - it's only minor; it's noise compared to everything else going on in the test cases.

**Comment by nklmish** [comment]
Thanks, we are on the same page, here is the PR https://github.com/spring-projects/spring-kafka/pull/677
