### ISSUE TITLE
ProducerListener: add CompositeProducerListener or list of ProducerListener

### ISSUE THREAD

**Issue by mayras** [spring-projects/spring-kafka#691]
Typical situation when there is the need of list of listeners, but there can be set up one ProducerListener for KafkaTemplate only. Pls add CompositeProducerListener with list of inner listeners or 
enhance KafkaTemplate to addProducerListener method.

**Comment by artembilan** [comment]
I think this is fully valid request and `CompositeProducerListener` sounds good to me.

I guess you can simply implement one for your project yourself and when you're done, feel free to contribute it back to the Framework!

**Comment by mayras** [comment]
public class CompositeProducerListener<K, V> implements ProducerListener<K, V> {

    private List<ProducerListener<K,V>> producerListeners = newArrayList();
    private boolean interestedInSuccess;

    public CompositeProducerListener(List<ProducerListener<K,V>> producerListeners, boolean interestedInSuccess) {
        this.producerListeners = producerListeners;
        this.interestedInSuccess = interestedInSuccess;
    }

    @Override
    public void onSuccess(String topic, Integer partition, K key, V value, RecordMetadata recordMetadata) {
        producerListeners.forEach(c -> c.onSuccess(topic, partition, key, value, recordMetadata));
    }

    @Override
    public void onError(String topic, Integer partition, K key, V value, Exception exception) {
        producerListeners.forEach(c -> c.onError(topic, partition, key, value, exception));
    }

    @Override
    public boolean isInterestedInSuccess() {
        return interestedInSuccess;
    }
}
