### ISSUE TITLE
Gracefully react to UNKNOWN_TOPIC_OR_PARTITION

### ISSUE THREAD

**Issue by skliche** [spring-projects/spring-kafka#696]
Hi Spring Kafka team,

I was wondering if there is any way to react programmatically to the situation where a topic is not existing in kafka after creating a ConcurrentMessageListenerContainer. Looking through the code and documentation I did not find anything useful, so I hope you can help me out. Thanks in  #advance.

The warning we see comes only from org.apache.kafka.clients.NetworkClient:
```
org.apache.kafka.clients.NetworkClient   : [Consumer clientId=domain-server-test-platform-data-events_90-1, groupId=domain-server_test-platform-data-events] Error while fetching metadata with correlation id {test-platform-data-events=UNKNOWN_TOPIC_OR_PARTITION} : {}
```

**Comment by garyrussell** [comment]
Of course, you can also add a `NewTopic` bean to the context and Spring will create it for you during initialization:

```java
@Bean
public NewTopic topic() {
	return new NewTopic("kgh696", 10, (short) 1);
}
```

**Comment by Wzy19930507** [comment]
@garyrussell  hi, take a moment of your time, ask a piece of code

```
public class KafkaMessageListenerContainer {
		if (this.clientIdSuffix == null) {   // why need clientIdSuffix == null
			checkTopics();
		}
}
```
