### ISSUE TITLE
KafkaListener annotation for batch consumption does not work with Kotlin

### ISSUE THREAD

**Issue by zach-schoenberger** [spring-projects/spring-kafka#699]
https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java#L428

This does not work when using a kotlin function to consumer a batch list, as the parameter is not of ConsumerRecord.class. It is a WildcardTemplateImpl.class that exends ConsumerRecord.class

**Comment by artembilan** [comment]
Would you mind to share some sample to reproduce?

We have this test class so far: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/kotlin/org/springframework/kafka/listener/EnableKafkaKotlinTests.kt, but I agree that batch mode is not presented there.

Contribution at least with test-case is welcome!

Thanks

**Comment by zach-schoenberger** [comment]
Sure, the sample code is to reproduce is simple if you have a cluster to consume from.
`@KafkaListener(topics = ["topic"])
    fun consumerRecords(consumerRecords: List<ConsumerRecord<String, String>>) {
println(consumerRecords)
}`
What is actually passed to the function is a list of Strings instead of ConsumerRecord.  From what you posted I don't think this would be covered, since the listener function is not actually invoked.

**Comment by zach-schoenberger** [comment]
I have created a pr that adds a test case for this issue, and has a possible solution. if you run the test without the solution you will see the exceptions the bug causes and it will fail. https://github.com/spring-projects/spring-kafka/pull/700
