### ISSUE TITLE
Enable Batch KafkaListener to allow ConsumerRecords as a parameter

### ISSUE THREAD

**Issue by zach-schoenberger** [spring-projects/spring-kafka#701]
The current implementation of batch listener combines all records returned into a list. This loses a lot of information that is provided when the data is returned as a ConsumerRecords. Most importantly, the records are already grouped by topic and partition at this point, which can be useful when implementing processing logic. I would suggest adding additional processing logic to allow the KafkaListener to pass ConsumerRecords as a parameter when batch processing is enabled.

**Comment by garyrussell** [comment]
Good point; the reasoning for converting to a list was so that a `FilteringBatchMessageListenerAdapter` could wrap the listener, but I agree it should be an option.
