### ISSUE TITLE
Kafka producers throwing TimeoutExceptions

### ISSUE THREAD

**Issue by Oduig** [spring-projects/spring-kafka#705]
# Problem description

Spring Kafka SSL producers are throwing timeouts when producing to a Kafka cluster with 3 brokers. 

- The SSL configuration is correct and messages are sent correctly for large periods of time (e.g. hours) before showing intermittent problems. 
- Both the server and clients have plenty of resources left.
- The network is stable and powerful enough (200 mbit, no downtime in the last year).
- The errors do not appear in a PLAINTEXT setup.
- Configurations for the three brokers are identical apart from their broker ID and listeners.
- No errors appear in the broker log or Spring Kafka consumers.

`2018-06-06 11:15:44.103 ERROR 1 --- [ad | producer-1] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='[...redacted...]':
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for topicname-0: 30001 ms has passed since last append`

# Detailed description

https://stackoverflow.com/questions/50725643/spring-kafka-producers-throwing-timeoutexceptions

# Question

How can I determine if this is a problem on my end, or a bug?

**Comment by garyrussell** [comment]
Most likely a question best directed to the Apache Kafka folks rather than here, since we're just using their client.
