### ISSUE TITLE
Cannot load keystore when running java -jar *.jar spring boot application

### ISSUE THREAD

**Issue by aalmazanarbs** [spring-projects/spring-kafka#710]
Hi,

I have a `kafka-keytore.jks` file in `src/main/resources` and when I run the application with `mvn spring-boot:run` there are no exceptions but when I run the application with `java -jar target/demo-0.0.1-SNAPSHOT.jar` the following error occurs:

> Caused by: java.io.FileNotFoundException: class path resource [kafka-keytore.jks] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/aalmazan/demo/target/demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/kafka-keytore.jks
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:133) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.boot.autoconfigure.kafka.KafkaProperties$Ssl.resourceToPath(KafkaProperties.java:945) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	... 76 common frames omitted

If I unpack `target/demo-0.0.1-SNAPSHOT.jar` the `kafka-keytore.jks.jks` file is inside.

Here are the steps to reproduce the problem:
- Go to [](https://start.spring.io/) and generate new project skeleton with **spring boot 2.0.3**, **demo** artifact name and add `Kafka` dependency.
- Add the following properties to `src/main/resources/application.properties` file:
```
spring.kafka.ssl.key-password=testkey
spring.kafka.ssl.keystore-location=classpath:kafka-keytore.jks
spring.kafka.ssl.keystore-password=teststore
```
- Execute `mvn clean install`
- Execute `mvn spring-boot:run` -> no error occurs
- Execute `java -jar target/demo-0.0.1-SNAPSHOT.jar` -> the error occurs

**Comment by garyrussell** [comment]
Please move this to the spring-boot project.

**Comment by garyrussell** [comment]
Actually, no. This is a limitation of the Kafka client.

Kafka requires the keystore on the file system (it doesn't understand class path resources).

It works with `spring-boot:run` because maven runs the exploded task, not the jar.

You must put the keystore on the file system someplace.

**Comment by aalmazanarbs** [comment]
Hi Gary, I have noticed it reviewing the internal code. Thank you for your response.

**Comment by garyrussell** [comment]
One possible workaround  is to extract the keystore to a temporary file:

```java
@SpringBootApplication
public class Kgh710Application {

	public static void main(String[] args) throws Exception {
		FileCopyUtils.copy(new ClassPathResource("client.ks").getInputStream(),
				new FileOutputStream("/tmp/client.ks"));

		SpringApplication.run(Kgh710Application.class, args);
	}

}
```

and

    spring.kafka.ssl.keystore-location=file:/tmp/client.ks

**Comment by webmutation** [comment]
@garyrussell Do you think it would be feasible to get the jks file from Spring Vault. Would you consider a good approach to do the same you are doing for the classpath? Given that it would require connecting to Vault, do a base 64 decode of the data and write it to filesystem. Before initiating the Spring Boot application and connection with Spring Kafka.

**Comment by garyrussell** [comment]
Yes, that should work ok for you. I don't think there is any other choice, given the limitations of the Kafka clients.

**Comment by zmumi** [comment]
Is this the related proposal? [KIP-398](https://cwiki.apache.org/confluence/display/KAFKA/KIP-398%3A+Support+reading+trust+store+from+classpath )

**Comment by garyrussell** [comment]
@zmumi Looks like it, yes; the KIP even mentions Spring's `Resource` abstraction.

The [associated JIRA](https://issues.apache.org/jira/browse/KAFKA-7685) doesn't appear to have any recent activity however.
