### ISSUE TITLE
Inner class name be a logger name can not config level

### ISSUE THREAD

**Issue by raylua2566** [spring-projects/spring-kafka#714]
https://github.com/spring-projects/spring-kafka/blob/7d85c56dc7cdf2cebc18f3cc124660056df9d15b/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L718

When I setting logging
``` yml
org.springframework.kafka: debug
```
it will log repeat.
```
Received: 0 records
```

There is no way to disable that because the logger name is a inner class name `org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer` and config
```
org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer: info
```
 is not work

**Comment by garyrussell** [comment]
I presume you are setting those properties in `application.yml`; in which case it looks like a Boot problem. It works fine with a `logback.xml` file:

```xml
<configuration>

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <!-- encoders are assigned the type
         ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>

  <root level="info">
    <appender-ref ref="STDOUT" />
  </root>

  <logger name="org.springframework.kafka" level="debug" />
  <logger name="org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer" level="info" />

</configuration>
```

**Comment by garyrussell** [comment]
This works...

    logging.level.[org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer]=info

**Comment by garyrussell** [comment]
Or like this with yaml:

```yaml
logging:
  level:
    org.springframework.kafka: debug
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: info
```
