### ISSUE TITLE
Relaxing replying `KafkaTemplate` in `AbstractKafkaListenerContainerFactory`

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-kafka#723]
Since `KafkaTemplate` has its own message converter, shouldn't we relax that instance property to wildcard types such as: `private KafkaTemplate<?, ?> replyTemplate;`.

Otherwise spring-kafka forces users of listener container factory to reply exactly the same semantics as listener ie. `<K, V>`.

What would you think?

**Comment by garyrussell** [comment]
Good point; yes.

As a work-around you can just inject `KafkaTemplate` with no generics and suppress the warning.
