### ISSUE TITLE
ReplyingKafkaTemplate scalability restrictions

### ISSUE THREAD

**Issue by b-liberman** [spring-projects/spring-kafka#731]
Hello, 
is it possible to remove the restrictions of ReplyingKafkaTemplate that every client instance requires its own topic or partition?

According to the reference 
> If you have multiple client instances, each will need a dedicated reply topic for each instance. An alternative is to set the KafkaHeaders.REPLY_PARTITION and use a dedicated partition for each instance

This makes an easy (auto-)scaling cumbersome. 
Looking at the code, my understanding is that this is only required to produce an error log entry: 
```java
RequestReplyFuture<K, V, R> future = this.futures.remove(correlationId);
if (future == null) {
	this.logger.error("No pending reply: " + record + " with correlationId: "
		+ correlationId + ", perhaps timed out");
}
else {
	if (this.logger.isDebugEnabled()) {
		this.logger.debug("Received: " + record + " with correlationId: " + correlationId);
	}
	future.set(record);
}
```

Is not it better to 

1. allow multiple (client) instances listen to the same topic and filter their own correlation ids

1. in case a timeout occurs to move the entry (future) with that correlation ID into another map for a certain period of time and report the "perhaps timed out" based on that map. If nothing found there - do not report anything.

I also suggest to improve the implementation and set the reply header automatically if possible, i.e. remove the need for 
```java
record.headers().add(new RecordHeader(KafkaHeaders.REPLY_TOPIC, "kReplies".getBytes()));
```
and set the header in `ReplyingKafkaTemplate` based on the reply container configuration as they need to match anyway.

Regards

Boris

**Comment by garyrussell** [comment]
>Is not it better to

"Better" is rather subjective here. If it's ok to waste broker, network and CPU resources receiving and discarding unexpected replies then using a common reply topic is ok.

There is no actual restriction - if each instance uses a unique `group.id` in the reply container, all instances will get all replies, which will be discarded by the uninterested instances; you can suppress the ERROR log with appropriate configuration of your logging subsystem. We could consider making that log message level configurable.

I don't think there is a need for a "second map" at all; the "right" template will either find, or not, the `Future<?>` and the others will never find it. The timeout is logged as a warning elsewhere.

I agree that the template can set the reply topic header, if the container has simple configuration (i.e. it is configured to listen to a single topic and not a topic pattern).

**Comment by b-liberman** [comment]
thanks a lot! 

I think that the documentation should also describe a way (e.g. using different group ids as suggested by you) to scale the listeneres instead of makeing an Impression that it is impossible.
