### ISSUE TITLE
Add support for JUnit 5 extension.

### ISSUE THREAD

**Issue by NeveHanter** [spring-projects/spring-kafka#732]
Currently `spring-kafka` allow using `KafkaEmbedded` using `@ClassRule` or using spring's injection thanks to provided context customizer.

Is there any reason why there's no JUnit 5 extension provided or are there any plans on supporting this?

For now I'm using custom written JUnit 5 extension which implements both replication manager shutdown and high watermark _hacks_ from #194 but it will be best to have this done properly by spring-kafka itself.

**Comment by garyrussell** [comment]
We didn't write a JUnit5 extension because we already have the `@EmbeddedKafka` annotation, which can be used with JUnit5.

[Documentation here](https://docs.spring.io/spring-kafka/reference/html/_reference.html#__embeddedkafka_annotation).

Feel free to create a PR for your extension and we'll consider merging it if it adds significant value.

**Comment by Woodham** [comment]
@garyrussell As far as I can see, the `@EmbeddedKafka` still requires junit4 (or junit-jupiter-vintage) on the classpath because `KafkaEmbedded.java` imports `org.junit.rules.ExternalResource`.

Is there any way to use `KafkaEmbedded` without having junit 4 on the classpath?

**Comment by artembilan** [comment]
Yep! That's good catch, indeed!

I think we need a JUnit 5 variant of the `KafkaEmbedded` and that `@EmbeddedKafka` should be able to select the proper implementation according classpath state.
Although we definitely should extract a common logic in the separate class, free from JUnit at all and provide appropriate wrappers.
Something like `KafkaEmbeddedJunit4Rule` and `KafkaEmbeddedJunit5Extension` ?

**Comment by d35h** [comment]
Does it work for you now with JUnit4?
I have the following when running ```./gradlew build```:
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required  dependencies in the classpath:
    class org.springframework.kafka.test.rule.EmbeddedKafkaRule, unresolved supertypes: org.junit.rules.ExternalResource, org.junit.rules.TestRule
    class org.springframework.kafka.test.rule.KafkaRule, unresolved supertypes: org.junit.rules.TestRule
```

Those are my dependencies:
```
testImplementation("org.springframework.kafka:spring-kafka-test")
testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")
```

However, I can make it work if I add this:
```testCompileOnly("junit:junit:4.12")```
Which is strange as ```org.junit.rules.TestRule``` are brought by ```testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")```, but ignored by within my build

**Comment by artembilan** [comment]
We definitely use `junit:junit:4.12` in our project just because we need to compile against its classes.

Not sure about `:junit-vintage-engine`, but if that doesn't work for you as is, just have that `junit:junit` as a workaround. Should not harm any possible way.
The `junit-vintage-engine` is in our dependencies as well.

**Comment by d35h** [comment]
> We definitely use `junit:junit:4.12` in our project just because we need to compile against its classes.
> 
> Not sure about `:junit-vintage-engine`, but if that doesn't work for you as is, just have that `junit:junit` as a workaround. Should not harm any possible way.
> The `junit-vintage-engine` is in our dependencies as well.

Thank you for your quick response

Sorry, I meant JUnit5, not JUnit4 as I mentioned in my original post, do you still have ```junit:junit:4.12``` for JUnit5?

**Comment by artembilan** [comment]
No, for that reason you shouldn't use `EmbeddedKafkaRule` because it is really just for JUnit 4.
For JUnit 5 we suggest to use `@EmbeddedKafka` together with the `@SpringJUnitConfig`:
```
@SpringJUnitConfig
@DirtiesContext
@EmbeddedKafka
public class KafkaStreamsCustomizerTests {
```

**Comment by d35h** [comment]
Unfortunately, it does not work for me if I have the following configuration:
```
@ExtendWith(value = [LocalstackDockerExtension::class, SpringExtension::class])
@SpringBootTest
@EmbeddedKafka
@DirtiesContext
@TestInstance(PER_CLASS)
@LocalstackDockerProperties(randomizePorts = false, services = ["s3"])
@DisplayName("Kafka and S3 integration tests")
```

I mean I can run my tests from Intellij, but it fails when I run ```./gradlew build```, do you know something about this?

**Comment by artembilan** [comment]
Well, if that works from IDE, then there is something wrong with your build tool.

Do you have there in Gradle config this:
```
test {
	useJUnitPlatform()
}
```

What is an error you get there though?

**Comment by d35h** [comment]
Thank you again for your quick response :)

Yes, I do have this in my gradle config, to be more precise, this is how it looks like:
``
dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("org.simpleflatmapper:sfm-csv:$csvFormatter")
    implementation("com.amazonaws:aws-java-sdk:$awsJavaSdk")

    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude("junit", "junit")
    }
    testImplementation("cloud.localstack:localstack-utils:$localStackVersion")
    testImplementation("org.springframework.kafka:spring-kafka-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
    testImplementation("org.junit.vintage:junit-vintage-engine:$junitVersion")
}

tasks.test {
    useJUnitPlatform()
}
```

When I run my ```./gradlew build``` I receive the following exception:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.springframework.kafka.test.rule.EmbeddedKafkaRule, unresolved supertypes: org.junit.rules.ExternalResource, org.junit.rules.TestRule
    class org.springframework.kafka.test.rule.KafkaRule, unresolved supertypes: org.junit.rules.TestRule


> Task :compileTestKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by artembilan** [comment]
So, you use somewhere else exactly `EmbeddedKafkaRule` in your test, when you shouldn't since you aiming fully for JUnit 5

**Comment by d35h** [comment]
I checked it just now and I didn't find any occurrence of this, this is the result of my full context search:
![image](https://user-images.githubusercontent.com/1194698/58719451-fc8bcc80-83cf-11e9-9cdf-6a948a2c4f3d.png)

**Comment by d35h** [comment]
@artembilan thanks for all of your answers.  

Is there anything else coming to your mind where the problem might be? As you can see from the picture above I don’t use the rule anywhere in my code

**Comment by d35h** [comment]
@artembilan Hey Artem, sorry for bombarding you with messages here, but I found where the issue was and created an issue for it, could you take a look at it, please? Here is the link: https://github.com/spring-projects/spring-kafka/issues/1109

Thank you!
