### ISSUE TITLE
Add support for serializing JSR 310 time types

### ISSUE THREAD

**Issue by ColdFerrin** [spring-projects/spring-kafka#739]
Currently, when you serialize the JSON with JsonSerializer.class, it converts the JSR 310 time types to their internal fields. If you add one dependency and configure the serializer, it will allow you to write the JSR 310 types DateTime, LocalDate, and LocalTime out as their appropriate ISO8601 representations.

The needed dependency is 
```
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>{Current Version}</version>
</dependency>
```

The serializer feature that you will need to add is
```
new ObjectMapper()
            .registerModule(new JavaTimeModule());
```

**Comment by artembilan** [comment]
According [Reference Manual](https://docs.spring.io/spring-kafka/docs/2.1.7.RELEASE/reference/html/_reference.html#serdes):
> To meet this API, the `DefaultKafkaProducerFactory` and `DefaultKafkaConsumerFactory` also provide properties to allow to inject a custom `(De)Serializer` to target `Producer/Consumer`.

 you can inject a custom `ObjectMapper` into the `JsonSerializer` which eventually can be injected into the `DefaultKafkaProducerFactory`:
```
public DefaultKafkaProducerFactory(Map<String, Object> configs, Serializer<K> keySerializer,
		Serializer<V> valueSerializer) {

```
 So, what do we miss here, please?

That's already not a Framework responsibility to make some unconditional assumption based on the classpath.

**Comment by ColdFerrin** [comment]
That is not very obvious from just the wording in the reference. It would be good if that could be made more obvious.

**Comment by artembilan** [comment]
??? 

Why that ctor on the `DefaultKafkaProducerFactory` is not so obvious?

OK. We will add some simple sample into the Reference Manual.
