### ISSUE TITLE
How to fail execution when Kafka server is not available?

### ISSUE THREAD

**Issue by daniiltischenko** [spring-projects/spring-kafka#740]
In our project, we need to periodically fetch data from the 3rd party by many threads and to push this data to the Kafka then. And if Kafka server is not available at the moment, the flow should be terminated, the fetched data should be lost and re-fetched during the next scheduled execution. Also, there's a need to use transaction management, because we need to send the batch of messages to Kafka to different topics. And if one message is not sent, all others should be rolled back.

We've been experiencing an issue with terminating execution if Kafka Server is not available. When transaction management is disabled, everything works fine and we're getting `org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.`
But with transaction management enabled, Kafka producer tries to reach the server infinitely and all threads that initiate pushing messages to Kafka sticking. We've tried different settings to make it fail after some time of unavailability, but it didn't help.

Is there some combination of settings that make Kafka Producer fail after some timeout when Kafka server is not available and the transaction management is enabled?

**Comment by artembilan** [comment]
First of all this is question and we don't manage questions here on GitHub. Consider to move it to some community forum, e.g. StackOverflow.
Another concern that it doesn't sound like a Spring Kafka problem, but Apache Kafka per se and we don't provide here support for it. 
We may answer some Kafka related questions, but if it doesn't fall to deep and doesn't expose something what is fully out of Spring control.

Thank you for understanding. 

Maybe `transaction.timeout.ms` property can help you on the matter though?

**Comment by garyrussell** [comment]
It's a bug in the kafka client see [KAFKA-6446](https://issues.apache.org/jira/browse/KAFKA-6446). It will be fixed in the 2.0.0 client.

**Comment by garyrussell** [comment]
All 1.x users are recommended to upgrade to at least 1.3.5 because it has a much simpler threading model thanks to KIP-62. 

2.1.7 is the current release and has significant new features above 1.x.
