### ISSUE TITLE
spring.kafka.listener.concurrency large than partition count, is that any problem?

### ISSUE THREAD

**Issue by tastypinenut** [spring-projects/spring-kafka#741]
I'v configured `spring.kafka.listener.concurrency=10` in my application, with `num.partitions=8
` in kafka server.properties. After start up the application for a while, the cpu load is much higher than before, even reached 100%. Is there any rule for the concurrency configuration? Why the cpu load is too high? Thanks for your reply.

**Comment by artembilan** [comment]
Well, you need to confirm with some report that it is indeed a Spring Kafka problem.

A concurrency behavior is like this: minimum from the `spring.kafka.listener.concurrency` and `num.partitions`. In other words we are not going to have more threads, than you have partitions.

**Comment by izeye** [comment]
Based on the comment from @garyrussell this seems intended to be closed.
