### ISSUE TITLE
ConsumerSeekAware.registerSeekCallback is not partition aware

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-kafka#746]
```public interface ConsumerSeekAware {

	/**
	 * Register the callback to use when seeking at some arbitrary time. When used with a
	 * {@code ConcurrentMessageListenerContainer} or the same listener instance in multiple
	 * containers listeners should store the callback in a {@code ThreadLocal}.
	 * @param callback the callback.
	 */
	void registerSeekCallback(ConsumerSeekCallback callback);
```

I would like to consumer to be asked to seek into a particular offset from the code that is running on the other thread.

I've tried to use the callback from onPartitionsAssigned but it has to be called from the kafka thread.

But if I have 64 partitions I would get 63 errors when I do something like this
```
private Set<ConsumerSeekCallback> callbacks = Collections.synchronizedSet(new HashSet<>());

@Override public void registerSeekCallback(ConsumerSeekCallback callback) {
    callbacks.add(callback);
}

public void seek(String topic, int partition, long offset) {
    for (ConsumerSeekCallback callback : callbacks) {
        callback.seek(topic, partition, offset);
    }
}
```

So there a better way to do it?

**Comment by igouss** [comment]
Is there another way to set a partition offset in the running application?

**Comment by garyrussell** [comment]
You can enable idle events [docs here](https://docs.spring.io/spring-kafka/reference/html/_reference.html#idle-containers) (which give you access to the Consumer in 2.0); the event is published on the consumer thread (by default).

Before 2.0 you need to save the callback in a `ThreadLocal`.

BTW; you can't just seek arbitrary partitions - only those assigned to this instance so you need to track those too.
