### ISSUE TITLE
Add "clientId" in @KafkaListener

### ISSUE THREAD

**Issue by essepuig** [spring-projects/spring-kafka#749]
Could it be possible to add a "clientId" (or "consumerId") field in the KafkaListener annotation ?

This new field could be used override the ConsumerConfig.CLIENT_ID_CONFIG configuration, the same way as "groupId" overrides the ConsumerConfig.GROUP_ID_CONFIG

This new field could be useful to identify the consumer when looking at the exposed kafka jmx metrics, specially when a single containerFactory is used for many consumers.

**Comment by artembilan** [comment]
Tell us, please, if this existing property works for you:
```
/**
 * When provided, overrides the client id property in the consumer factory
 * configuration. A suffix ('-n') is added for each container instance to ensure
 * uniqueness when concurrency is used.
 * @return the client id prefix.
 * @since 2.1.1
 */
String clientIdPrefix() default "";
```

**Comment by garyrussell** [comment]
Oops - I forgot we already did it - thanks; @artembilan

**Comment by essepuig** [comment]
I was not aware of this property, as I am using the 1.3.5 version :(, but i think that is is exactly was i was looking for.
Anyway, I guess I will use that as an excuse to upgrade.

Thanks.

**Comment by artembilan** [comment]
Has been fixed via: https://github.com/spring-projects/spring-kafka/issues/518
