### ISSUE TITLE
JsonSerializer and JsonDeserializer don't search for jackson modules

### ISSUE THREAD

**Issue by ST-DDT** [spring-projects/spring-kafka#751]
By default jackson's ObjectMapper does not search for modules such as the Java8-Time-Module.

Due to that it is impossible to use java 8 time objects in the message queue properly.
It would be nice if there was an config option to search for modules aka invoke `ObjectMapper#findAndRegisterModules()` or always invoke it.

````properties
spring.kafka.bootstrap-servers=broker.kafka
spring.kafka.consumer.group-id=some-app
spring.kafka.consumer.properties.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.someapp.dto
spring.kafka.consumer.properties.spring.json.search.modules=true
spring.kafka.producer.properties.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.search.modules=true
````

**Possible Workaround**

Create a custom (subclass) of `JsonSerializer` and `JsonDeserializer` which invoke `findAndRegisterModules()` and reference them in the config instead:

````java
public class CustomJsonDeserializer<T> extends JsonDeserializer<T> {

	public CustomJsonDeserializer() {
		super();
		this.objectMapper.findAndRegisterModules();
	}

}
````

This however takes quite some time to debug (especially if you use the SpringBoot's auto configuration) . Also IMO the java 8 support is required in a lot of cases nowadays and usage will only increase.

**Comment by artembilan** [comment]
I think we don't need any extra options, but just add such a detection functionality as an out-of-the-box feature.
Some sample can be borrowed from Spring Integration: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/support/json/Jackson2JsonObjectMapper.java#L154

**Comment by artembilan** [comment]
Has been fixed via: https://github.com/spring-projects/spring-kafka/commit/c2a4c1e1e7e804ec12ff155f84a676844a06d30b
