### ISSUE TITLE
KafkaTemplate.executeInTransaction() does not throw exception 

### ISSUE THREAD

**Issue by kennethk91** [spring-projects/spring-kafka#774]
Hi!

KafkaTemplate.executeInTransaction(OperationsCallback<K, V, T> callback) does not seem to throw exception if something happens in the callback/operation.

**Comment by garyrussell** [comment]
@kennethk91 The 2.1.9.RELEASE is now in the spring repo and will be in maven central shortly.

Thanks for pointing this out.
