### ISSUE TITLE
autoStartup attribute of KafkaListener only exists in version 2.2, how do we use this for 2.1x version?

### ISSUE THREAD

**Issue by tianhao-au** [spring-projects/spring-kafka#779]
I am looking for ways to not initialise Kafka when I  start spring application. 

So I find that autoStartup attribute can help me on this for the doc, [https://docs.spring.io/spring-kafka/reference/htmlsingle/#kafkalistener-lifecycle](https://docs.spring.io/spring-kafka/reference/htmlsingle/#kafkalistener-lifecycle)

However this attribute is only introduced for 2.2 version. First I am wondering why the document already said that and current stable release is 2.1.x?

Second, how can we control to not to initialise Kafka when we start Spring application?

**Comment by garyrussell** [comment]
Please don't use GitHub to ask questions.

For earlier versions, set the property on the [container factory](https://docs.spring.io/spring-kafka/reference/htmlsingle/#kafka-listener-annotation). The 2.2 Javadoc clearly says that the annotation property overrides the factory property.
