### ISSUE TITLE
RecordFilterStrategy don't allow to use child classes of the record value

### ISSUE THREAD

**Issue by Kirill380** [spring-projects/spring-kafka#787]
I have a base class for Kafka events that inherited by specific DTO events classes related to a particular topic.
When I tried to filter Kafka events by **RecordFilterStrategy** parametrized with the base class I found out that I can't set up **KafkaListenerContainerFactories** parametrized with child DTO classes using this filter. I looked into the source code of the filter class and I figured out that the filter method doesn't use _upper-bounded wildcard generic_ for **ConsumerRecord** so it means I can put only exactly the same type but not its successors. 
It is better to use bounded generics to allow to put child classes.

**Comment by artembilan** [comment]
Please, raise a PullRequest and we will see what's going on.

Looks like I didn't have enough coffee after weekend, so not fully clear what's going on.

Thank you!

**Comment by artembilan** [comment]
Seems for me I see what is going on here. 
Let's imagine we have a design like this:

```
public class Bar<T> {

    setFoo(Foo<T> foo) {
      ...
    }

}
```

The point is that `Foo` can handle target type, as well as its supper type.
So, what we really need here is something like this:

```
  setFoo(Foo<? super T> foo) 
```

So, this way into the `new Bar<String>()` we even can inject this `setFoo(new Foo<CharSequence>())`.

I believe this is the main point of this issue and this is exactly a design selected for the generics in Java core, e.g. `Collection.removeIf(Predicate<? super E> filter)`.

Will issue some PR soon...
