### ISSUE TITLE
Seek capability for Springboot 1.5.15 and Spring Kafka 1.3.5 moving forward with new data in topic/partition

### ISSUE THREAD

**Issue by michelbetancourt** [spring-projects/spring-kafka#798]
🐞 Bug report

We are using Springboot 1.5.15 and Spring Kafka 1.3.5's seek capability to queue back to a failing offset.  This capability seems to work great if the topic has no new offset.  But if we have new data in the partition, the offset moves forward.

We see this behavior if we use the seek within the same consumer or within the error handler of the consumer (using Generic Error Handler).

We tried different settings to see if it may be consumer commit related, but even when switching to auto commit off and Ack mode of MANUAL_IMMEDIATE and manually setting setting the Acknowledgement.acknowledgment() after the exception is thrown shows the same behavior -- offset moving forward after the seek is called.

As a result, this seems like a bug.  Any thoughts on what may be happening? 

This is what we post in our application logs:
```
2018-09-04T17:14:15,721 [org.springframework.kafka.KafkaListenerEndpointContainer#7-0-C-1] INFO : Waited, now seeking to the requested offset,waitMillis=1002.867935,topic=MyStream,partition=0,offset=128
2018-09-04T17:14:15,721 [org.springframework.kafka.KafkaListenerEndpointContainer#7-0-C-1] INFO : ######## IN Consumer=Thread[org.springframework.kafka.KafkaListenerEndpointContainer#7-0-C-1,5,main],topic=MyStream,partition=0,offset=129
```

**Comment by artembilan** [comment]
Any chances for simple project on GitHub to let us to reproduce and play?

Does look like a bug from the framework perspective.

The `ConsumerSeekCallback.seek()` is queuing the requested seek position:
```
public void seek(String topic, int partition, long offset) {
	this.seeks.add(new TopicPartitionInitialOffset(topic, partition, offset));
}
```

The main loop for the `KafkaConsumer` does exactly this:
```
processSeeks();
ConsumerRecords<K, V> records = this.consumer.poll(this.containerProperties.getPollTimeout());
```
So, we definitely move offset first of all and only then go to the consumer to poll.

Maybe your problem that you use a `ConcurrentMessageListenerContainer` and therefore you have several `KafkaConsumer` instances. This way you need to ensure that you use a `ConsumerSeekCallback` for the proper `KafkaConsumer` in the proper thread.
This way we have a recommendation to store that callback in the `ThreadLocal`: https://docs.spring.io/spring-kafka/docs/2.1.9.RELEASE/reference/html/_reference.html#seek
So, this way when you decide to seek for the particular partition, you need to obtain a `ConsumerSeekCallback` from the `ThreadLocal` in your `ConsumerSeekAware` listener:
```
private final ThreadLocal<ConsumerSeekCallback> seekCallBack = new ThreadLocal<>();
...
@Override
public void registerSeekCallback(ConsumerSeekCallback callback) {
	this.seekCallBack.set(callback);
}
...
		this.seekCallBack.get().seek(topic, partition, 0);
```

Let us know how is ti going with your solution and if you can share a simple project with us!

**Comment by garyrussell** [comment]
You are probably seeing prefetched records after the failure. With 1.3.x
you need to set max.poll.records to 1 or add logic to the listener to also
seek prefetched topics/partitions until the failed message is redelivered

In 2.0 we added the SeekToCurrentErrorHandler which does this all for you
and the prefetched records are not sent to the listener.

The simplest path forward is to upgrade to boot.2.0.4 and spring kafka
2.1.x.

>
>

**Comment by garyrussell** [comment]
Another alternative is to use the retry listener adapter and don't involve Kafka in the retries at all.

**Comment by michelbetancourt** [comment]
I appreciate the quick feedback.  

We are applying the callback with ThreadLocal so that should ensure that with our ConcurrentMessageListener, we have the adequate instance available to us.  We decided though to use the GenericErrorHandler to implement something very similar to SeekToCurrentErrorHandler available for 2.x since it is a challenge for our organization to move quickly onto new versions.  But depending on our testing that is what we will recommend in the end.

Our game plan this morning is to test the pre-fetch and resolve this issue since that is likely what is happening as you are noting.  

Question though regarding 2.x, would prefetch scenario still be an issue if we were to move to 2.x and use the out of the box capabilities to ensure message consumption? 

Thank you again for your support.

**Comment by michelbetancourt** [comment]
Pre fetching is the issue.  Issue resolved.

Thanks.

**Comment by garyrussell** [comment]
>Question though regarding 2.x, would prefetch scenario still be an issue if we were to move to 2.x and use the out of the box capabilities to ensure message consumption?

Yes, with the default error handler; with the `SeekToCurrentErrorHandler` the remaining records are sent to the error handler so it can see each partition to the proper point so that the next poll will refetch everything; in the upcoming 2.2 release, it is enhanced further to allow only n attempts and the ability to send the failed record to a dead-letter topic.
