### ISSUE TITLE
Implement methods hashCode and equals in EmbeddedKafkaContextCustomizer

### ISSUE THREAD

**Issue by OArtyomov** [spring-projects/spring-kafka#804]
Problem:
  We have set of tests(near 150), which use EmbeddedKafka. If each test will have their own context, test start will be very expensive operation. Spring has concept of caching context between tests. HashCode and Equals methods of ContextCustomizer are using for calculating key in cache. See example of methods implementation in org.springframework.boot.test.mock.mockito.MockitoContextCustomizer, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer. It will be good to be fixed in 1.3.X version. It is not bottleneck now, we have workaround, but it will be good to fix it in core library.

**Comment by artembilan** [comment]
I think you are right and we need to treat this a as **bug**:
```
 * <p>Implementations must implement correct {@code equals} and {@code hashCode}
 * methods since customizers form part of the {@link MergedContextConfiguration}
 * which is used as a cache key.
 *
 * @author Phillip Webb
 * @author Sam Brannen
 * @since 4.3
 * @see ContextCustomizerFactory
 * @see org.springframework.test.context.support.AbstractContextLoader#customizeContext
 */
@FunctionalInterface
public interface ContextCustomizer {
```
Thank you for the pointer!

Please, contribution is welcome!

**Comment by OArtyomov** [comment]
Is it possible to fix in 1.3.x version ?

**Comment by artembilan** [comment]
Right. Whenever you provide a PullRequest, we review and cherry-pick it into all supported versions, including `1.3.x`.

I wonder if we can have some tests to confirm the fix though...

**Comment by garyrussell** [comment]
I am not familiar with the mechanism, but wouldn't the hashCode have to depend on the topics (and other properties) defined in the `@EmbeddedKafka` ?

**Comment by artembilan** [comment]
I think we can investigate other implementations to determine the proper way of hash codding.

**Comment by OArtyomov** [comment]
@artembilan 
 Is it ok to have the same implementation of these methods as in org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer ?

**Comment by garyrussell** [comment]
I don't believe so; what if you have 2 `@EnableKafka`s on different tests, but with, say, different `brokerProperties` - the second test will get the first one's broker AFAICT.

**Comment by artembilan** [comment]
I think @garyrussell  is right and we need to build a `key` based on the provided `@EmbeddedKafka`. 
Not sure if annotations can provide meaningful hash codes, but we can give it a shot:
```
  /**
     * Returns the hash code of this annotation, as defined below:
     *
     * <p>The hash code of an annotation is the sum of the hash codes
     * of its members (including those with default values), as defined
     * below:
     *
     * The hash code of an annotation member is (127 times the hash code
     * of the member-name as computed by {@link String#hashCode()}) XOR
     * the hash code of the member-value, as defined below:
     *
     * <p>The hash code of a member-value depends on its type:
     * <ul>
     * <li>The hash code of a primitive value <tt><i>v</i></tt> is equal to
     *     <tt><i>WrapperType</i>.valueOf(<i>v</i>).hashCode()</tt>, where
     *     <tt><i>WrapperType</i></tt> is the wrapper type corresponding
     *     to the primitive type of <tt><i>v</i></tt> ({@link Byte},
     *     {@link Character}, {@link Double}, {@link Float}, {@link Integer},
     *     {@link Long}, {@link Short}, or {@link Boolean}).
     *
     * <li>The hash code of a string, enum, class, or annotation member-value
     I     <tt><i>v</i></tt> is computed as by calling
     *     <tt><i>v</i>.hashCode()</tt>.  (In the case of annotation
     *     member values, this is a recursive definition.)
     *
     * <li>The hash code of an array member-value is computed by calling
     *     the appropriate overloading of
     *     {@link java.util.Arrays#hashCode(long[]) Arrays.hashCode}
     *     on the value.  (There is one overloading for each primitive
     *     type, and one for object reference types.)
     * </ul>
     *
     * @return the hash code of this annotation
     */
    int hashCode();
```

**Comment by OArtyomov** [comment]
@artembilan 
See my PR https://github.com/spring-projects/spring-kafka/pull/805
