### ISSUE TITLE
Provide setter method for CleanupConfig in StreamsBuilderFactoryBean

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-kafka#810]
Currently, `StreamsBuilderFactoryBean` provides an empty constructor and allows `StreamsConfig` to be injected through a setter method. When doing this, there is no way currently to provide a custom `CleanupConfig` as setter for this is not available in `StreamsBuilderFactoryBean`.

**Comment by artembilan** [comment]
This is what we have since version `2.2`:
```
/**
 * Construct an instance with the supplied streams configuration and
 * clean up configuration.
 * @param streamsConfig the streams configuration.
 * @param cleanupConfig the cleanup configuration.
 * @since 2.2
 */
public StreamsBuilderFactoryBean(KafkaStreamsConfiguration streamsConfig, CleanupConfig cleanupConfig) {
```

Does it make sense to you? Or do you still want a setter? Then contribution is welcome!

**Comment by sobychacko** [comment]
The `setter` for `CleanupConfig` is not necessary. Sorry for the noise. Closing the issue.

**Comment by adrien-ben** [comment]
That would be great to have a setter though. I use Springboot and it would be helpful if i could inject a `StreamsBuilderFactoryBeanCustomizer` to set the CleanupConfig.
