### ISSUE TITLE
The headers are not sent back by @SendTo 

### ISSUE THREAD

**Issue by heerdev** [spring-projects/spring-kafka#811]
For https://docs.spring.io/spring-kafka/reference/html/_reference.html#annotation-send-to
the @SendTo, does not seems to send back the header it received except correlation_id.
We can see this on Kafka Broker, the message key is empty for the reply message.
We can send our custom header , if the reply type of the method is Message<T>.
In this case, consumer will decide what header he wants to send to producer.
But , as per replyTemplate, the producer should be able to decide what headers it set.

**Comment by artembilan** [comment]
@heerdev ,

What do you suggest has to be as a fix for this issue?
Any chances that we can see a Pull Request from you on the matter?

Thanks

**Comment by garyrussell** [comment]
I was thinking we can add a `Predicate<String> shouldCopyHeader` to the listener adapter/container factory.
