### ISSUE TITLE
Rebalancing while KafkaMessageListenerContainer is paused prevent it from being paused again after the rebalance

### ISSUE THREAD

**Issue by jffou17** [spring-projects/spring-kafka#813]
Kafka spring version : 2.1.5.RELEASSE
Kafka client version : 1.0.0

If a rebalance occurs while a KafkaMessageListenerContainer is paused, consumption of records will resume and it will not be possible to pause the container again.

This is because the private variable "consumerPaused" is not reinitialised during a rebalance. It while be stuck on "true" even though the consumer is not paused anymore. From this moment on, it will not be possible to pause the container again and records will be fetched/consumed on each poll. To pause the container again you have to resume it, let it poll once, then you can pause it again. 

This can be reproduce with a KafkaMessageListenerContainer configured as follows :

```
ContainerProperties containerProperties = new ContainerProperties("topic-test");
containerProperties.setGroupId("group-test");
containerProperties.setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL_IMMEDIATE);
containerProperties.setMessageListener(new TestListener());
containerProperties.setErrorHandler(new TestErrorHandler());
KafkaMessageListenerContainer<K, V> messageListenerContainer = new KafkaMessageListenerContainer<>(consumerFactory, containerProperties);

```

```
public class TestListener implements AcknowledgingMessageListener<String, String> {

    private static final Logger log = LoggerFactory.getLogger(TestListener.class);

    @Override
    public void onMessage(ConsumerRecord<String, String> record, Acknowledgment ack) {
        log.info("Consuming " + record.partition() + ":" + record.offset());

        throw new IllegalStateException("Test");
    }
}
```

```
public class TestErrorHandler implements ContainerAwareErrorHandler {

    private static final Logger log = LoggerFactory.getLogger(TestErrorHandler.class);

    @Override
    public void handle(Exception thrownException, List<ConsumerRecord<?, ?>> records, Consumer<?, ?> consumer, MessageListenerContainer container) {

        seekToCurrent(records, consumer);

        container.pause();

        log.info("Consumer paused in Error handler");
    }

    private void seekToCurrent(List<ConsumerRecord<?, ?>> records, Consumer<?, ?> consumer) {
        Map<TopicPartition, Long> offsets = new LinkedHashMap<>();
        records.forEach(r -> offsets.computeIfAbsent(new TopicPartition(r.topic(), r.partition()), k -> r.offset()));
        offsets.forEach(consumer::seek);
    }
}
```

At start up it should output something like this :

```
 partitions assigned: [topic-test-9, topic-test-7, topic-test-8, topic-test-5, topic-test-6, topic-test-3, topic-test-4, topic-test-1, topic-test-2, topic-test-0]
 Consuming 7:1
 Consumer paused in Error handler
```

If you then start another instance, it will try to join the group. This will cause a rebalance. This should output something like this :

```
partitions revoked: [topic-test-9, topic-test-7, topic-test-8, topic-test-5, topic-test-6, topic-test-3, topic-test-4, topic-test-1, topic-test-2, topic-test-0]
partitions assigned: [topic-test-9, topic-test-7, topic-test-8, topic-test-5, topic-test-6]
Consuming 7:1
Consumer paused in Error handler
Consuming 7:1
Consumer paused in Error handler
Consuming 7:1
Consumer paused in Error handler
...
```

As you can see, it is now impossible to pause the container. This is because the variable consumerPaused in KafkaMessageListenerContainer.java is still true even though the consumer as been "reset" during the rebalance.

Not sure if the is the right way to fix it but it could be fixed by calling resume() during onPartitionsRevoked in the ConsumerRebalanceListener.

**Comment by artembilan** [comment]
Can't we have a configuration option like `resumeAfterRebalance` to give a choice for users to stay paused even after rebalance?

**Comment by garyrussell** [comment]
Actually, the consumer thread will automatically re-pause before the first poll after the rebalance, so users can use a rebalance listener to resume() the container so it won't automatically re-pause.

**Comment by christopher-gilbert** [comment]
Hi Gary,

Just wanted to double check that this definitely fixes the issue - before using spring-kafka we faced a similar issue in that when we had a consumer in paused state, which we checked before each poll then after a rebalance there was exactly one set of records returned before the pause was honoured again.

The problem we had was that just prior to calling poll on the consumer, we would, if we detected we should be paused, call consumer.pause(consumer.assignment()). However prior to the first poll after a rebalance, the assignment() call returns no partitions, and so none were paused. The assignment of partitions actually happens synchronously *during* the first poll. After a rebalance, the synchronous steps that occur in consumer.poll are - update assigned partitions, invoke onPartitionsAssigned on any rebalanceListeners, then retrieve records for any non-paused partitions.

This means that the only way to avoid accidentally consuming records after a rebalance is to pause the assigned partitions on the consumer IN the rebalanceListener so it takes effect before the first records are fetched.. 

I *think* in this solution you are setting the (spring) pause flag in the rebalanceListener when partitions are assigned but not pausing the consumer itself. This will occur in the first poll, and the first set of records would be fetched before the second poll when the flag is noticed and the consumer partitions are paused.

I could be wrong here. I'm glad to see the issue has been raised as I just noticed the problem in our application, having just switched to spring-kafka. I'll check if we are using the version with this fix in, and if not, update and try to reproduce.

Thanks, Chris

**Comment by garyrussell** [comment]
@christopher-gilbert The consumer **is** re-paused in the listener, we don't just set the flag...

https://github.com/spring-projects/spring-kafka/blob/9342e191f9f9b2fe3727ad310ae74f605ba454a5/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1754-L1759

I looked at the consumer code while I was working on this and, if the current poll (that invokes the listener) has already retrieved records for any of these partitions, it discards them because the consumer is paused.

**Comment by garyrussell** [comment]
Sorry - the original fix for this just reset the flag; doing the pause in the listener was a follow-up.

https://github.com/spring-projects/spring-kafka/issues/1111

**Comment by christopher-gilbert** [comment]
Thanks Gary, I'll upgrade to the latest to pull in this fix. I should have checked the latest source code to see that it had been covered.

Cheers, Chris

**Comment by christopher-gilbert** [comment]
To be honest this seems like one of the oddest parts of Kafka client code, the need to pause specific partitions, I can't imagine any case where you wouldn't want a consumer group to pause on an entire topic,  suggesting that the group co-ordinator should just figure out whether its members should be getting records or not.
