### ISSUE TITLE
Validating Spring Kafka Payloads

### ISSUE THREAD

**Issue by cmreigrut** [spring-projects/spring-kafka#816]
Per Gary and https://stackoverflow.com/questions/52526886/validating-spring-kafka-payloads.

I am trying to set up a service that has both a REST (POST) endpoint and a Kafka endpoint, both of which should take a JSON representation of the request object (let's call it Foo). I would want to make sure that the Foo object is valid (via JSR-303 or whatever). So Foo might look like:
```
public class Foo {
    @Max(10)
    private int bar;

    // Getter and setter boilerplate
}
```
Setting up the REST endpoint is easy:
```
@PostMapping(value = "/", produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<String> restEndpoint(@Valid @RequestBody Foo foo) {
    // Do stuff here
}
```
and if I POST, { "bar": 9 } it processes the request, but if I post: { "bar": 99 } I get a BAD REQUEST. All good so far!

The Kafka endpoint is easy to create (along with adding a StringJsonMessageConverter() to my KafkaListenerContainerFactory so that I get JSON->Object conversion:
```
@KafkaListener(topics = "fooTopic")
public void kafkaEndpoint(@Valid @Payload Foo foo) {
    // I shouldn't get here with an invalid object!!!
    logger.debug("Successfully processed the object" + foo);

    // But just to make sure, let's see if hand-validating it works
    Validator validator = localValidatorFactoryBean.getValidator();
    Set<ConstraintViolation<SlackMessage>> errors = validator.validate(foo);
    if (errors.size() > 0) {
        logger.debug("But there were validation errors!" + errors);
    }
}
```
But no matter what I try, I can still pass invalid requests in and they process without error.

I've tried both @Valid and @Validated. I've tried adding a MethodValidationPostProcessor bean. I've tried adding a Validator to the KafkaListenerEndpointRegistrar (a la the EnableKafka javadoc):
```
@Configuration
public class MiscellaneousConfiguration implements KafkaListenerConfigurer {
    private Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    LocalValidatorFactoryBean validatorFactory;

    @Override
    public void configureKafkaListeners(KafkaListenerEndpointRegistrar registrar) {
        logger.debug("Configuring " + registrar);
        registrar.setMessageHandlerMethodFactory(kafkaHandlerMethodFactory());
    }

    @Bean
    public MessageHandlerMethodFactory kafkaHandlerMethodFactory() {
        DefaultMessageHandlerMethodFactory factory = new DefaultMessageHandlerMethodFactory();
        factory.setValidator(validatorFactory);
        return factory;
    }
}
```
I've now spent a few days on this, and I'm running out of other ideas. Is this even possible (without writing validation into every one of my kakfa endpoints)?

Gary responded: "The infrastructure currently does not pass a Validator into the payload argument resolver. Please open an issue on GitHub."

**Comment by garyrussell** [comment]
I had forgotten about that Javadoc; thanks for reminding us.

That said, it works fine for me...

```java
@SpringBootApplication
public class So52526886Application implements KafkaListenerConfigurer {

	public static void main(String[] args) {
		SpringApplication.run(So52526886Application.class, args);
	}

	@KafkaListener(id = "soso52526886a", topics = "so52526886")
	public void listen(@Valid @Payload Foo in) {
		System.out.println(in);
	}

	@Bean
	public StringJsonMessageConverter converter() {
		return new StringJsonMessageConverter();
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> {
			template.send("so52526886", "{\"bar\":42}");
		};
	}

	@Autowired
	LocalValidatorFactoryBean validatorFactory;

	@Override
	public void configureKafkaListeners(KafkaListenerEndpointRegistrar registrar) {
		registrar.setMessageHandlerMethodFactory(kafkaHandlerMethodFactory());
	}

	@Bean
	public MessageHandlerMethodFactory kafkaHandlerMethodFactory() {
		DefaultMessageHandlerMethodFactory factory = new DefaultMessageHandlerMethodFactory();
		factory.setValidator(validatorFactory);
		return factory;
	}

	public static class Foo {

		@Max(10)
		private int bar;

		public int getBar() {
			return this.bar;
		}

		public void setBar(int bar) {
			this.bar = bar;
		}

		@Override
		public String toString() {
			return "Foo [bar=" + this.bar + "]";
		}

	}

}
```

and

```
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method could not be invoked with the incoming message
...
```
>Caused by: org.springframework.messaging.handler.annotation.support.MethodArgumentNotValidException: Could not resolve method parameter at index 0 in public void com.example.So52526886Application.listen(com.example.So52526886Application$Foo): 1 error(s): [Field error in object 'in' on field 'bar': rejected value [42]; codes [Max.in.bar,Max.bar,Max.int,Max]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [in.bar,bar]; arguments []; default message [bar],10]; default message [must be less than or equal to 10]] 

Tested with Boot 2.0.5, spring-kafka 2.1.10.

**Comment by garyrussell** [comment]
(But I think we can auto-detect the validator and apply it by default without the need for explicit configuration).

**Comment by cmreigrut** [comment]
Well, that's extremely unusual...I compiled your version and it runs fine.  Then I went back to my original project and it now works fine, too.  
Thanks for looking at it!

**Comment by artembilan** [comment]
Sounds like Spring Boot issue to auto-detect a `Validator` bean and inject it into the `DefaultMessageHandlerMethodFactory` created in the `KafkaAnnotationDrivenConfiguration` ?

**Comment by garyrussell** [comment]
MVC and WebFlux don't rely on boot to do it...

`WebMvcConfigurationSupport`

```java
	@Bean
	public Validator mvcValidator() {
		Validator validator = getValidator();
		if (validator == null) {
			if (ClassUtils.isPresent("javax.validation.Validator", getClass().getClassLoader())) {
				Class<?> clazz;
				try {
					String className = "org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean";
					clazz = ClassUtils.forName(className, WebMvcConfigurationSupport.class.getClassLoader());
				}
				catch (ClassNotFoundException | LinkageError ex) {
					throw new BeanInitializationException("Failed to resolve default validator class", ex);
				}
				validator = (Validator) BeanUtils.instantiateClass(clazz);
			}
			else {
				validator = new NoOpValidator();
			}
		}
		return validator;
	}
```

**Comment by artembilan** [comment]
Sounds, good, Gary., but I'm not sure that we need to create a bean on the matte.

I would say that `KafkaListenerEndpointRegistrar` should have a new `setValidator()` option to let to configure an external one via `KafkaListenerConfigurer`. Otherwise fallback internally into the logic mentioned in Spring MVC.

Does it make sense?

**Comment by garyrussell** [comment]
Agreed, but I think an easier way to detect the validator is `ObjectProvider<LocalValidatorFactoryBean>`.

**Comment by artembilan** [comment]
If you mean an existing bean detection, then I don't think it's good idea to go that way unconditionally. We are not in Spring Boot to be opinionated and that may confuse someone when he/she produces such a bean for some other reason, but it is picked up by Spring Kafka.
We may be restricted by some particular bean name, but that doesn't sound to complicated to just expose some hook via `KafkaListenerConfigurer`. That is going to be something similar what we have with that `WebMvcConfigurationSupport.getValidator()`.

**Comment by garyrussell** [comment]
Yes; I agree; I decided to do just that, and not auto-detect, due to https://jira.spring.io/browse/SPR-17319
