### ISSUE TITLE
Feature to receive the list of new messages at a given poll intervals

### ISSUE THREAD

**Issue by abbinv** [spring-projects/spring-kafka#819]
🎁 Enhancement
It would be really nice and handy if we can give a poll interval, and get the list of all new messages untill then. 

For example, if i am listening for Message object, I want to get the "List Message messages"  since the last poll. Something like :
```
@KafkaListener(poll-interval=1000, topics = "${kafka.topic}", containerFactory = "objectListListenerContainerFactory", )
public void messageListener(List<Message> messages) {
    log.info("Count of new messages since last poll : {}", messages.size());
}
```

**Comment by artembilan** [comment]
See StackOverflow question on the matter: https://stackoverflow.com/questions/52647498/is-there-a-way-to-do-a-kafka-poll-using-spring-kafka-which-retrives-the-list-o

You can do it right now with the `ConsumerFactory` and `@Scheduled` on your service method to initiate a polling on the `KafkaConsumer.poll()`.

We may consider to implement something like `KafkaTemplate.poll()`, but it is really would be better to distinguish a `KafkaConsumer` instance of the appropriate polling setting and keep it for a while.

**Comment by garyrussell** [comment]
```java
@KafkaListener(poll-interval=1000, topics = "${kafka.topic}", containerFactory = "objectListListenerContainerFactory", )
public void messageListener(List<Message> messages) {
    log.info("Count of new messages since last poll : {}", messages.size());
```

You can do this now; just set the poll interval on the container factory's containerProperties instead of on the annotation.

**Comment by abbinv** [comment]
> ```java
> @KafkaListener(poll-interval=1000, topics = "${kafka.topic}", containerFactory = "objectListListenerContainerFactory", )
> public void messageListener(List<Message> messages) {
>     log.info("Count of new messages since last poll : {}", messages.size());
> ```
> 
> You can do this now; just set the poll interval on the container factory's containerProperties instead of on the annotation.

I tried that.. But messages(as in example) always have one element even if there are more than one in the queue. (Any chance that I am doing it wrong ?)

**Comment by artembilan** [comment]
For that purpose you need to turn on a `batch` mode on the container factory:
```
		@Bean
		public KafkaListenerContainerFactory<?> batchFactory() {
			ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
					new ConcurrentKafkaListenerContainerFactory<>();
			factory.setConsumerFactory(consumerFactory());
			factory.setBatchListener(true);
			return factory;
		}
```

**Comment by abbinv** [comment]
> ConcurrentKafkaListenerContainerFactory

I tried it that way.. But still the same way. Could you pls tell me where I am going wrong ?
Below are my codes and at the end, the logs when I sent 3 messages.

    private ConsumerFactory<String, MyObject> myObjectBatchFactory() {
        Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, SERVERS);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);
        props.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 20000);
        return new DefaultKafkaConsumerFactory<>(props, new StringDeserializer(), new JsonDeserializer<>(MyObject.class));
    }

	 @Bean
    public KafkaListenerContainerFactory<?> myObjectBatchListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, MyObject> factory =  new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(myObjectBatchFactory());
        factory.setBatchListener(true);
        return factory;
    }
	
	    @KafkaListener(topics = "${social.kafka.topic.01}", groupId = "SF.02", clientIdPrefix = "CLIENT.01", containerFactory = "myObjectBatchListenerContainerFactory")
    public void mongoMessageListener(List<MyObject> messages, @Header(KafkaHeaders.RECEIVED_PARTITION_ID) int partition) {
        log.info("Recieved {} messages", messages.size());
        for (MyObject message : messages) {
            log.info("MongoMessageListener recieved MyObject from partition {} : {}", partition, message.getMessageId());
        }
    }

	
2018-10-05 15:35:53.890  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : Recieved 1 messages
2018-10-05 15:35:53.891  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : MongoMessageListener recieved MyObject from partition 0 : Friday 01
2018-10-05 15:35:55.953  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : Recieved 1 messages
2018-10-05 15:35:55.953  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : MongoMessageListener recieved MyObject from partition 0 : Friday 02
2018-10-05 15:35:59.321  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : Recieved 1 messages
2018-10-05 15:35:59.322  INFO 12996 --- [ntainer#0-0-C-1] c.k.s.s.k.InboundSocialMessageConsumers  : MongoMessageListener recieved MyObject from partition 0 : Friday 03

**Comment by artembilan** [comment]
May you share with us the simple project to reproduce?
As far as I know the default `max.poll.records` is `500` for the consumer config. So, should not be relevant.
But on the other hand it isn't clear when you send records to the topic: before starting consumer or already after...

**Comment by abbinv** [comment]
I have extracted a basic format of what i am trying to do and pushed to  : https://github.com/abbinv/kafka-batchtest. 

I have a producer which sends 4 messages every 10 seconds.

For Listener, even though I have set MAX_POLL_INTERVAL_MS_CONFIG as 30000ms, the consumer is listening all the time is active the moment a new message has reached the queue.

I would expect that the Listener will poll the data every 30seconds and gives back the list of all records which is new since the last poll.

**Comment by garyrussell** [comment]
No; it doesn't work that way; the poll will return as soon as records are available; there is no delay between polls.

You can, however, increase `fetch.min.bytes`:

>The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.

And `fetch.max.wait.ms`:

>The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.

These are both kafka consumer properties.

**Comment by abbinv** [comment]
> No; it doesn't work that way; the poll will return as soon as records are available; there is no delay between polls.
> 
> You can, however, increase `fetch.min.bytes` (default:1):
> 
> > The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.
> 
> And `fetch.max.wait.ms` (default:500):
> 
> > The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.
> 
> These are both kafka consumer properties.

This is even better. I am going to try this. Thanks a lot. :)

**Comment by garyrussell** [comment]
The `max.poll.interval.ms` property is used by the broker to detect a "dead" client - if it doesn't issue a `poll()` within that time, a topic rebalance is performed.

**Comment by abbinv** [comment]
This issue can be closed since the expected behaviour can be achieved by setting the interval in ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG and a fairly high value in ConsumerConfig.FETCH_MIN_BYTES_CONFIG
