### ISSUE TITLE
Flow control support

### ISSUE THREAD

**Issue by martindam** [spring-projects/spring-kafka#84]
This is more a feature request and an issue: While working with this project and the spring-integration-kafka project, I faced the problem that KafkaConsumer can fetch messages much faster than I can consume them. With the current implementation the batch of messages are read and each one is pushed downstream for processing. However, if it takes more than session.timeout.ms to process the batch (which can be thousands of messages if there is a large kafka lag) a rebalance will be triggered as KafkaConsumer was not able to send heart beats (it happens while calling poll()). This could be solved by placing a queueChannel after the KafkaMessageListenerContainer, but that just moves the problem as at some point that queue is going to fill up or I run out of memory. 

So my suggestion is this: Add support for some flow control in the KafkaMessageListenerContainer so I can start/pause the KafkaConsumer when my downstream processing pipe is backed up to prevent filling up all buffers. KafkaConsumer supports start/pause out of the box, so it allows to pause the consumer while it keeps sending heart beats (with poll()) but not receive more messages until it can be consumed downstream. This could then be wrapped in a integration component that could manage the flow control based on MessageDeliveryExceptions or similar.

I did an implementation like the above, but it required to copy the existing KafkaMessageListenerContainer to make it work due to most of the logic is in the inner class.

**Comment by garyrussell** [comment]
Good suggestion; thanks - feel free to issue a pull request - be sure to follow the [contribution guidelines](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc) - especially "signing" the CLA. We need to release the GA by the end of the month so that means we need to get the (feature complete) release candidate out in the next day or so.

If you don't think you could turn around a PR in that timeframe, please share your code and one of us can take a stab at it (but we'd still need you to "sign" the CLA - it currently doesn't have Spring Kafka in the dropdown, you can choose Spring Integration instead).

Thanks!!

**Comment by garyrussell** [comment]
I think we should consider this a bug.

**Comment by martindam** [comment]
Will submit my code as it is and you can have a look at it. I should be able to make the needed change within a day. 
I already signed the CLA for spring-integration-kafka earlier so that should be okay right? Also, do you have a eclipse style format you typically use?

**Comment by martindam** [comment]
Have a look at https://github.com/spring-projects/spring-kafka/pull/85

**Comment by garyrussell** [comment]
@martindam Here is my approach: https://github.com/spring-projects/spring-kafka/pull/91

I believe it satisfies both use cases (pause for slow listener, pause if the listener throws a specific exception).

**Comment by martindam** [comment]
Tried out the implementation and it has a serious problem during rebalance. If the ConsumerRecords contains a lot of messages (I have seen up to 15000 records in a single ConsumerRecords<>), the rebalance fails in the new implementation. 
What happens:
 - The rebalance onPartitionRevoked is called and this tries to stop the ListenerInvoker. 
 - The ListenerInvoker may be in the middle of a huge ConsumerRecords and do not return before it is done with all the records (which can be seconds and even minutes later depending on the downstream processing and size of the batch)
 - Since the ListenerInvoker did not stop as expected, the Thread is interrupted instead which causes an error to be thrown for every record not yet processed in invokeListener()
- When the thread finally closes, the session have timed out with Kafka and a new rebalance is triggered

I believe the implementation need to support being stopped in the middle of processing a ConsumerRecords<> and not just per batch as currently supported.

**Comment by mbogoevici** [comment]
Hi Martin,

Thanks for the feedback. I think it makes sense to reject processing per-record and not per-batch.

**Comment by martindam** [comment]
Looking into this further, I am finding other serious issues:
1) When the ListenerInvoker is killed, and AckMode is not MANUAL_IMMEDIDATE*, the KafkaConsumer is waked up. However, as the ListenerInvoker is stopped from within the ConsumerRebalanceListener this calls the Wakeup on the consumer which interrupts the rebalance listener so the onPartitionsAssigned is not called before. 
2) The unsent ConsumerRecords in the run method is not cleared on a rebalance and paused should be false after a rebalance since the queue is cleared

Currently the above issues causes an unstable rebalance

**Comment by martindam** [comment]
On another note, this new design is very difficult to reason about the behavior with all the thread synchronization/management, message passing and a bunch of acknowledgement modes . I am afraid it is going to be very difficult to ensure this class operate as intended. Given that users will need to fully understand the consumer in order analyze delivery guarantees, I think a simplification should be done. 

E.g.: 
 - Do not start/stop the ListenerInvoker, keep it running but let it read from a unbounded BlockingQueue that can be safely cleared when needed. 
 - When a ConsumerRecords<> is pulled, put all the records in the BlockingQueue.
 - If the BlockingQueue size exceeds some threshold, pause the consumer. Simply call the consumer every pollTimeout and check the size of the queue afterwards and resume when the queue is below some other threshold (should be two different threshold to avoid fluctuating pause/resume)
 - The rebalance is simply clearing the blocking queue and resuming the consumer (which is automatic)

This would allow to have a very snappy rebalance as there is no synchronization and a message that is currently being delivered will finish and not interrupted in the middle which I believe is happening right now?

**Comment by mbogoevici** [comment]
Hi Martin,

Thanks for trying this out and for the (continued) feedback :). 

@garyrussell can tell better, but I think we can avoid a wakeup up during rebalance. We can also avoid interrupting the message processing, I believe. 

Looking at ways to simplify this:
Maybe I am missing something here, but shouldn't we ensure that we are done (i.e. either by processing or by discarding) the currently held messages and commit the offsets before proceeding further with the rebalance? Since messages are processed on a separate thread, I think that this will require some form of synchronization between beyond simply clearing the work queue, whether the invoking thread stops or doesn't. The scenario that I am thinking of is: if a message will keep being processed while the consumers rebalance - in particular a message that belongs to a partition that will not belong to the current consumer going forward - any new consumer picks up the partition would replay that message (since it hasn't completed yet, and therefore there is no commit for it). The obvious downside is that we'd need to wait until the current message is being processed (the concern about large batches would be mitigated by #108 changing the stopping model from waiting for an entire batch to waiting for a single message), but not sure how else we can guarantee that we don't process the same message in two separate consumers. Really looking forward for suggestions here.

Thinking a bit more about this, is the undesired rebalancing something that can be rather addressed by tuning the fetch size and heartbeat settings? (I agree that it still doesn't address the concerns of a new consumer joining the group).

**Comment by garyrussell** [comment]
@martindam 

I think we have reached the best compromise we can with the 0.9 client; we are eagerly awaiting improvements in 0.10 (and 0.11).

WIth the merge of #109, we now handle the rebalance by immediately stopping the invoker, clearing the queues and starting a new invoker when the rebalance is complete. If a rebalance is in process, we no longer wake the consumer.

I tested this with a backlog of messages across a couple of messages and everything recovered as expected. And it was quite snappy - 104ms between the revoke and the results of the next poll.

**Comment by artembilan** [comment]
@martindam ,

We appreciate your help with the issue and would like to hear from you back one more time for the latest changes we did recently. 
The problem that we are going to release RC this Monday, so looks like you don't have so much time to test the solution :smile: 

Anyway there will be still a time window before we go GA.

Thank you one more time.
Looking forward to hear from your side again!

**Comment by martindam** [comment]
As soon as the latest build-snapshot is available I will test this in a real environment. Should be able to do that by end of today (friday)

**Comment by artembilan** [comment]
Well, it is there already since this morning, if that: http://repo.spring.io/libs-snapshot-local/org/springframework/kafka/spring-kafka-test/1.0.0.BUILD-SNAPSHOT/

**Comment by artembilan** [comment]
The latest build was this: https://build.spring.io/browse/SK-MAS-56

**Comment by martindam** [comment]
Thanks, using the libs-snapshot-local repo let me get it. 

I tried it out, and with the latest fix it works great! Even with synchronization on other part of my application I finished a rebalance in 300 ms with batches of 15000+ records. 
I'll continue to test by running this in a staging cluster and let you know if any issues. Thanks for the quick turnaround on this.

**Comment by mbogoevici** [comment]
Hi @martindam,

Thanks for confirming - looking forward to more detailed feedback!

**Comment by martindam** [comment]
I may have found another issue: When the consumer is paused, the manual offset commits are not processed. Should line 431 in KafkaMessageListenerContainer simply be !this.autoCommit ?

**Comment by artembilan** [comment]
@martindam , here you go!

I find that as a good catch and according to the logic, the commit offsets doesn't relate to paused/active behavior. OTOH after the first run of `processCommits();` in paused state everything will be committed and cleared, therefore all other following calls will be just void.

Not sure (yet) how to cover with the unit-test, after fix everything is in `BUILD SUCCESSFUL`.

**Comment by martindam** [comment]
You can't make the assumption that the calls after the first one will be void. If you pull a big batch of records that the ListenerInvoker is processing. As each record is processed the manual acknowledgement may be called. I do not want to wait until my current batch is finished to commit my offsets in that case. While I am processing the entire batch the consumer is paused and therefore not committing offsets.

**Comment by artembilan** [comment]
I don't understand you now.
Your previous comments was about that it is a problem:
```
if (!this.paused && !this.autoCommit) {
	processCommits();
}
```
and we should process commits independently of the paused state.
And it really looks like we may still process a long batch and exceed the `time/count`, so nothing stops us to commit them! We just care about a new incomes, but still can commit in-process.
Correct?

Why your new conclusion is about:
> the consumer is paused and therefore not committing offsets. 

?
Thanks.

**Comment by martindam** [comment]
My last statement is about what it is doing now. My point is that we should be committing offset independently of the pause/active state - exactly as you said.

**Comment by artembilan** [comment]
Great!
Let's raise an new ticket and contribution from you is welcome!
