### ISSUE TITLE
NPE that hides real error when trying to create IllegalStateException on annotation processing

### ISSUE THREAD

**Issue by thomas-hugon** [spring-projects/spring-kafka#842]
Hello,

There are multiple possible NPE in class org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor
 on methods resolveExpressionAs* in the else statements because if the resolved value is null, resolved.getClass() that is used to create context for the thrown exception will throw a NPE that will hide the real error.

exemple:
https://github.com/spring-projects/spring-kafka/blob/c92f1bd3a36a30fd70eff065772d2b9910318620/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L663
https://github.com/spring-projects/spring-kafka/blob/c92f1bd3a36a30fd70eff065772d2b9910318620/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L522
https://github.com/spring-projects/spring-kafka/blob/c92f1bd3a36a30fd70eff065772d2b9910318620/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L694
https://github.com/spring-projects/spring-kafka/blob/c92f1bd3a36a30fd70eff065772d2b9910318620/spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java#L678

**Comment by artembilan** [comment]
@thomas-hugon ,

Please, go ahead and contribute the fix on the matter.
Even if an input value can't be `null` or empty String, the `resolveEmbeddedValue()` and `BeanExpressionResolver.evaluate()` have a `@Nullable` contract for their return value.

Thank you for catching that!
