### ISSUE TITLE
Is there a demo of spring-kafka 2.2.0.RELEASE?

### ISSUE THREAD

**Issue by SoftwareKing** [spring-projects/spring-kafka#852]
Is there a demo of spring-kafka 2.2.0.RELEASE?

**Comment by garyrussell** [comment]
See the new `samples` [directory in the GitHub repo](https://github.com/spring-projects/spring-kafka). Let us know if there is something else you need a sample for.

**Comment by SoftwareKing** [comment]
ok,thank you @garyrussell

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/commit/56f5bfb8c552b3265e9f111f3148db9361492584
