### ISSUE TITLE
Documentation about using the SeekToCurrentErrorHandler in Spring Kafka 2.2 is wrong

### ISSUE THREAD

**Issue by MartinX3** [spring-projects/spring-kafka#862]
I did not found the github project for the docs to make a pull request. Sorry!
___
https://docs.spring.io/spring-kafka/docs/2.2.0.RELEASE/reference/html/_reference.html#seek-to-current

According to the docs, I should write

```
@Bean
public ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory() {
    ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory();
    factory.setConsumerFactory(consumerFactory());
    factory.getContainerProperties().setAckOnError(false);
    factory.getContainerProperties().setErrorHandler(new SeekToCurrentErrorHandler());
    factory.getContainerProperties().setAckMode(AckMode.RECORD);
    return factory;
}
```

but only
```
    factory.setErrorHandler(new SeekToCurrentErrorHandler());
```
is usable.
The usage of
```
    factory.getContainerProperties().setErrorHandler(new SeekToCurrentErrorHandler());
```
creates a "Cannot resolve method" exception.

**Comment by garyrussell** [comment]
Thanks; yes; the property was moved to the container some releases ago and we failed to reflect it in the docs.

**Comment by artembilan** [comment]
BTW, to fix the docs you just need to fork this project and modify this file there: https://github.com/spring-projects/spring-kafka/blob/master/src/reference/asciidoc/kafka.adoc

I mean docs for this project is present exactly in this project.

Thanks for catching this though!
