### ISSUE TITLE
Fully asynchronous publishing to kafka

### ISSUE THREAD

**Issue by mawek** [spring-projects/spring-kafka#877]
Although this is probably more of kafka-clients related question, I was wondering whether spring-kafka  has ambition to wrap KafkaProducer so it is fully asynchronous. 
Currently, only publishing itself is asynchronous, but there are some operations that are performed before publishing (for example serialisation) and they are performed on main (caller) thread.
In most cases serialisation is fast, but sometimes it has to contact schema-registry and it can get stuck there (if there is some network glitch etc).
We can get around that issue with own threadpool placed before kafkaTemplate, but then order of events isn't ensured. Currently, I have threadpool with size of 1 with unlimited queue capacity but I don't think that's the best solution.

**Comment by garyrussell** [comment]
Please see this pull request https://github.com/spring-projects/spring-kafka/pull/559

**Comment by mawek** [comment]
I was hoping there might be some solution that wouldn't require refactoring on client side. Since `KafkaTemplate` nicely encapsulates publishing to kafka and it already returns `ListenableFuture` I thought that it might be extended to support fully async mode without requiring api change (or client code modification). 
But I understand that it might be not so straightforward as it seems.

**Comment by mawek** [comment]
That's what I'm doing currently, I just thought that it might be common usecase for `spring-kafka` clients (having publishing completely async) so it would be useful to have it included in spring-kafka out of the box. 
It was a bit surprising to me that though method returns `ListenableFuture`, it does block (when serialising/contacting schema registry/invoking interceptors,...).

**Comment by garyrussell** [comment]
I suggest you take that up with the Kafka community; the responsibility lies in the kafka-clients - we can't anticipate what its internals might or might not do.
