### ISSUE TITLE
MINOR: Replace "org.apache.commons.logging" with "org.slf4j"

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-kafka#88]
Is there any reason to use commons-logging instead of slf4j?

I can update this, if it's not a feature.

P.S.: Also could you please explain the reason of not making Logger static?

**Comment by artembilan** [comment]
Hello, @stepio !

See here, please: https://github.com/spring-projects/spring-integration/issues/1782

Re. `static` VS non-`static`.
Well, it depends. Sometimes it is much better just let people to extend our classes and reuse super methods, as well as reuse our `protected` logger. So, all actions in the instance will be logged with the same logger.
See difference, please:
````java
private static final Log logger = LogFactory.getLog(Foo.class);
...
protected final Log logger = LogFactory.getLog(getClass());
````
So, in the second case `getClass()` is exactly a class of the target object.

**Comment by stepio** [comment]
That explains much - thanks for details!
I've implemented backward change for my code here: f8e3e53592b87718613ca6823785e3f057bbddb8

May do the PR, although it's a minor polishing. Issue may be closed, case is clear.

**Comment by artembilan** [comment]
Oh! I missed there that you use slf4j. :smile: 

Please, raise a PR on the matter with this issue as a subject.

Thank you for contribution and sane discussion!

**Comment by artembilan** [comment]
I think we even should reconsider our dependencies excluding any transitive `slf4j` and that `compile log4j` to avoid exactly undesired cases like this in the `JsonDeserializer`.
