### ISSUE TITLE
Listener gets duplicated records with 2.2.0

### ISSUE THREAD

**Issue by MartinX3** [spring-projects/spring-kafka#884]
I get duplicated records in my listener.
On the kafka bus are single items.
That's my listener:

```java
 @KafkaListener(id = "courses-administration-listener",
            topicPartitions =
                    {@TopicPartition(topic = "courses",
                            partitionOffsets = @PartitionOffset(partition = "0", initialOffset = "0"))})
    public void listen(ConsumerRecord<String, String> cr) {
        try {
            Operation op = mapper.readValue(cr.value(), Operation.class);
        } catch (IllegalArgumentException | IOException e) {
            log.error(e.getMessage());
        }
    }
```
They are coming from the listen method.

Which informations  do you need and where I can debug? :)

**Comment by artembilan** [comment]
I think we need a simple Spring Boot project to play with and may be reproduce an issue.

Please, try to prepare one and share somewhere on GitHub.

That's the first time we hear about such a duplication problem, so something fishy is going on in your project...

**Comment by MartinX3** [comment]
This will be a bit difficult.

The files are getting into kafka by the kafkacat application from many json files in our kubernetes cluster. (It's a company project).

Can I somehow debug it somewhere in your spring kafka dependency?

**Comment by artembilan** [comment]
OK. That's fine too.

You can debug a `KafkaMessageListenerContainer.ListenerConsumer.pollAndInvoke()`.
Also you can turn on `DEBUG` logging level for the `org.springframework.kafka` to see some logs on the matter as well.

**Comment by MartinX3** [comment]
Sorry for forgetting this issue.
I use it only in my company and jumped from task to task. :S

Of course that's intended, because the application has only a in memory database. :)

**Comment by MartinX3** [comment]
Maybe the Upgrade to Apache Kafka 2.1.0 after the 20. Nov fixed the problem.
I can't reproduce it anymore. :)

**Comment by garyrussell** [comment]
Thanks for reporting back.
