### ISSUE TITLE
Add additional error handler to allow previous, non-skipping behaviour

### ISSUE THREAD

**Issue by larsduelfer** [spring-projects/spring-kafka#885]
With the latest version of spring kafka (2.2.0) the default behaviour of the listener has changed. Our application is relying to not continue consuming messages from a topic, in case there was an error. Now, after upgrading the library, the new default behaviour is to skip a record after 10 retries. As far as we can see, it is not easy to recreate the previous behaviour to block further processing.

Would it make sense to add the old SeekToCurrentErrorHandler implementation as an additional error handler? We are currently thinking about copying the old implementation to a custom error handler.

Regards, Lars

**Comment by garyrussell** [comment]
While it really doesn't make sense to keep retrying over and over again, you can configure the number of retries to `Integer.MAX_VALUE`, which is effectively infinity.

	/**
	 * Construct an instance with the provided recoverer which will be called after
	 * maxFailures have occurred for a topic/partition/offset.
	 * @param recoverer the recoverer; if null, the default (logging) recoverer is used.
	 * @param maxFailures the maxFailures.
	 * @since 2.2
	 */
	public SeekToCurrentErrorHandler(@Nullable BiConsumer<ConsumerRecord<?, ?>, Exception> recoverer, int maxFailures) {

Or, as you say, you can copy the old error handler.

What we can do is consider a negative number in `maxFailures` to be infinity.

**Comment by larsduelfer** [comment]
I like the suggestion to have -1 as infinity.

By the way, there are use cases like an event store for event sourcing where you have to fix the error first before you can consume further messages,. since the sequence of consumption is important. In this case, the application MUST NOT skip a message. You can argue to shut down the listener container instead. However, it might also be that due to whatever reason, an external system that is required to process the next message is down. In this case, you would like to have the system keep trying and to recover once the external dependency is avaiable again.

**Comment by garyrussell** [comment]
Good point; however, you might want to consider adding [stateful retry](https://docs.spring.io/spring-kafka/reference/html/_reference.html#stateful-retry) to the listener so you can at least add a delay between delivery attempts.
