### ISSUE TITLE
Appendix to override kafka-clients is missing in latest 2.2.x docs

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-kafka#888]
The appendix is missing in the docs but the link from the Spring Kafka home page still exists and gives a 404 error.

I'm assuming this is still valid with 2.2.x to enable use of kafka-clients 2.1.x?

**Comment by garyrussell** [comment]
@manderson23 I have updated the project page link.

We have not yet tested 2.2.x against the 2.1.x clients; we will update and replace the appendix when we have done so.

**Comment by garyrussell** [comment]
The [notable changes](https://kafka.apache.org/documentation/#upgrade_210_notable) in their documentation leads me to believe there should be no issues; we will test today.

**Comment by garyrussell** [comment]
Tested and reinstated the appendix; thanks for pointing this out.
