### ISSUE TITLE
Application doesn't bootup if Kafka Fails to connect to broker

### ISSUE THREAD

**Issue by saroj8807** [spring-projects/spring-kafka#890]
Team, 

I am using spring-kafka version "1.3.6.RELEASE" release. Currently if i bootup my application and kafka connection fails due to any reason, It terminates the application startup (server). 

I want my application to boot-up even if kafka broker is down or it is not able to connect to kafka as I have another messaging system if any failure occurs during publishing message to kafka topic.

Here is how my application.properties looks like:

#Spring-Kafka SSL Configuration
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.keystore.location=/tmp/kafka_idps_keystore.jks
spring.kafka.properties.ssl.truststore.location=/tmp/kafka_idps_truststore.jks
spring.kafka.properties.ssl.key.password=
spring.kafka.properties.ssl.keystore.password=
spring.kafka.properties.ssl.truststore.password=
kafka.ssl.keystore=
kafka.ssl.truststore=

spring.kafka.client-id=sample-client-id

#Spring-Kafka Producer Configuration
spring.kafka.producer.acks=all
spring.kafka.producer.compression-type=gzip
spring.kafka.producer.retries=3
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

So my requirement is that i want to bring up my application and serve the traffic even if kafka connection was failed.

Please help!!!!

**Comment by garyrussell** [comment]
Please show a stack trace.

**Comment by saroj8807** [comment]
I gave the wrong bootstrap server deliberately to fail the kafka connection. Here are the logs:

**Comment by saroj8807** [comment]
Fixed!!!! Removed the Consumer written for debugging purpose.
