### ISSUE TITLE
Offset Management support?

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-kafka#9]
The previous version of Spring Integration Kafka had an `offset management` stuff.

Has that gone since Kafka-0.9?

Thanks

**Comment by garyrussell** [comment]
In the first milestone, we'll only support native kafka-based offset management; we'll consider external offset management after the first milestone.

**Comment by davidrabinowitz** [comment]
:+1:

**Comment by garyrussell** [comment]
[Milestone](https://spring.io/blog/2016/03/14/spring-for-apache-kafka-milestone-1-available) is now available.

**Comment by jd73** [comment]
👍
