### ISSUE TITLE
Remaining records not passed to RemainingRecordsErrorHandler 

### ISSUE THREAD

**Issue by mawri** [spring-projects/spring-kafka#916]
As can be seen here - https://github.com/spring-projects/spring-kafka/blob/7c512c900c280750f2883d3a7d53adaaa030acf8/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1231 -that remaining records are passed only for `ContainerAwareErrorHandler `. `RemainingRecordsErrorHandler` implements `ConsumerAwareErrorHandler` and hence ````
this.errorHandler.handle(e, record, this.consumer);
```` is called which throws `UnsupportedOperationException`

**Comment by garyrussell** [comment]
Ref: https://gitter.im/spring-projects/spring-kafka?at=5c24f8e5db5b5c6883158523
