### ISSUE TITLE
Specify the port with annotation

### ISSUE THREAD

**Issue by JBertaux** [spring-projects/spring-kafka#917]
Hello,
With the class rule `EmbeddedKafkaRule` this is possible to specify the port like that:
```java
public static EmbeddedKafkaRule embeddedKafka = new EmbeddedKafkaRule(1, true, "topic").kafkaPorts(9092);
```
How can I achieve the same with the annotation ? (I use Junit 5)
```java
@EmbeddedKafka(controlledShutdown = true, topics = {"topic"})
```

**Comment by artembilan** [comment]
I think this is not too bad to support on the annotation level:
```
/**
 * @return ports for brokers.
 */
int[] ports() default { };
```

So, treating this as an  improvement.
And that's not too late yet to implement in the current version.
