### ISSUE TITLE
How can i use producer and consumer connection pooling?

### ISSUE THREAD

**Issue by arashiya** [spring-projects/spring-kafka#92]
I would like to have a feature where i am allowed to use connection pooling. How do i do that?

**Comment by garyrussell** [comment]
Can you explain further? There is only one producer so all code that sends messages share the same connection. There is a separate connection for each consumer.

**Comment by arashiya** [comment]
I just want to understand whether i will get any performance benefit if i create multiple producers? Maybe one for each topic?

**Comment by garyrussell** [comment]
From [the producer javadoc](https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html) ...

>The producer is thread safe and sharing a single producer instance across threads will generally be faster than having multiple instances.

... so spring-kafka uses that model in `DefaultKafkaProducerFactory` - it always returns the same producer. If you want to use multiple connections, you will need a separate factories.

**Comment by jmirc** [comment]
KafkaProducer can send message asynchronously, so you didn't need to start multiple KafkaProducer to have performance.
This is not the same pattern for the consumer.
