### ISSUE TITLE
Stateful retry and multiple topics

### ISSUE THREAD

**Issue by nromanetti** [spring-projects/spring-kafka#931]
🎁 Enhancement

Stateful retries works like a charm.
See [StatefulRetryTests.java](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/annotation/StatefulRetryTests.java)

But, if you declare a second topic in the test above and listen to it using the same method annotated with
```
@KafkaListener(id = "retry", topics = {"sr1", "sr2"}, groupId = "sr1)
```

And send the messages in that order:
```
this.template.send("sr1", "foo1");
this.template.send("sr2", "foo2");
```

Message sent to sr2 will be read only after the message sent to sr1 is retried. In other word, there are 3 delivery attempt of "foo1" to listen1 method before "foo2" is delivered to listen1 method.

Ideally the delivery of "foo2" should not be blocked by the error triggered on a different topic.

**Comment by garyrussell** [comment]
I don't think that's practical without adding complex logic to the container - in addition to other topics, there might be other pre-fetched records from the same topic/partition.

Use a different listener per topic.

I think the only practical thing the framework can do to help is add a new property `consumerPerTopic` so each topic gets its own consumer/thread. Even then, though, there might be messages in other partitions for the same topic that will be held up (unless the concurrency is set to ensure only one partition per consumer instance).

**Comment by nromanetti** [comment]
I agree, it is complex and indeed it works with 1 listener per topic.

Regarding your `consumerPerTopic` option, if combined with the use of `topicPattern` of `@KafkaListener` it would really add some value to the framework.

**Comment by garyrussell** [comment]
>if combined with the use of topicPattern

That's a bit more tricky (if even possible).

With a static list of topics, we can distribute them across consumers; with topic patterns, we know nothing about them until Kafka starts assigning partitions for them.

I guess we could do some initial discovery during startup, but I don't think we could address the condition where new topics matching the pattern are added after the container is started.

**Comment by nromanetti** [comment]
I realize that what I need is a listener per topic with the possibility to add programmatically one or more listener on the fly. So given the trickyness of my initial demand, I think you may close this enhancement request. Thanks for your time.

**Comment by garyrussell** [comment]
Thanks for getting back to us.

**Comment by PieterBenjamin** [comment]
@nromanetti did you ever figure out how 
> to add programmatically one or more listener on the fly
