### ISSUE TITLE
Upgrade kafkaVersion in build.gradle from 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-kafka#933]
org.apache.kafka:kafka-clients:2.1.0 is available since 2018-11-19. IMHO, it should be considered to upgrade from 2.0.1 to 2.1.0.

**Comment by garyrussell** [comment]
Spring project dependency rules do not allow us to make such a change; we can (and have) upgrade from 2.0.0 to 2.0.1, but can't upgrade to 2.1.x in a point release.

The next version (2.3.x) will use 2.1.x (or 2.2.x if it's available by then), but 2.2.x is stuck on the 2.0.x clients generation.

We have, however, tested with it and provide [instructions here for how to override to the newer version](https://docs.spring.io/spring-kafka/reference/html/deps-for-21x.html).
