### ISSUE TITLE
TopicExistsException printed - causing lots of noise in logs

### ISSUE THREAD

**Issue by magaton** [spring-projects/spring-kafka#942]
Latest change in KafkaAdmin (due to sonar warnings) where the Exception is thrown and printed in catch introduces lots of noise in logs in case that topic already exists.

**Comment by garyrussell** [comment]
@magaton Can you provide an example? I don't see any new log messages when creating topics; there are existing INFO logs produced when the actual partition count doesn't match, but those are not new.

**Comment by magaton** [comment]
I have 3 instances of monolith app starting at the same time and trying to create topic "events". 1 succeeds, 2 fail with the exception below.


KakaAdmin is declared as bean
`@Bean
	public KafkaAdmin admin() {
		Map<String, Object> configs = new HashMap<>();
		configs.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaBrokerProperties.getBootstrapServers());
		return new KafkaAdmin(configs);
	}`
The topic "events" is configured as 
	`@Bean
	public NewTopic inboundEvent() {
         // ...
        }`


Jan 18 12:44:42 bi-test-3 java[2847]: 12:44:42.101 monolith [main] ERROR o.s.kafka.core.KafkaAdmin - Failed to create topics
Jan 18 12:44:42 bi-test-3 java[2847]: org.apache.kafka.common.errors.TopicExistsException: Topic 'events' already exists.
Jan 18 12:44:42 bi-test-3 java[2847]: 12:44:42.102 monolith [main] ERROR o.s.kafka.core.KafkaAdmin - Could not configure topics
Jan 18 12:44:42 bi-test-3 java[2847]: org.springframework.kafka.KafkaException: Failed to create topics; nested exception is org.apache.kafka.common.errors.TopicExistsException: Topic 'events' alr
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.kafka.core.KafkaAdmin.addTopics(KafkaAdmin.java:258)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.kafka.core.KafkaAdmin.addTopicsIfNeeded(KafkaAdmin.java:199)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.kafka.core.KafkaAdmin.initialize(KafkaAdmin.java:167)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.kafka.core.KafkaAdmin.afterSingletonsInstantiated(KafkaAdmin.java:137)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:863)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
Jan 18 12:44:42 bi-test-3 java[2847]:         at com.acme.bi.core.app.BiApplication.init(acmeBiApplication.java:82)
Jan 18 12:44:42 bi-test-3 java[2847]:         at com.acme.bi.core.app.BiApplication.init(acmeBiApplication.java:131)
Jan 18 12:44:42 bi-test-3 java[2847]:         at com.acme.bi.monolith.app.MonolithApplication.main(MonolithApplication.java:13)
Jan 18 12:44:42 bi-test-3 java[2847]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jan 18 12:44:42 bi-test-3 java[2847]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jan 18 12:44:42 bi-test-3 java[2847]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 18 12:44:42 bi-test-3 java[2847]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
Jan 18 12:44:42 bi-test-3 java[2847]:         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Jan 18 12:44:42 bi-test-3 java[2847]: Caused by: org.apache.kafka.common.errors.TopicExistsException: Topic 'events' already exists.

**Comment by garyrussell** [comment]
Please read about Git Markup.

Again; this is not new, the same code has been there since the `KafkaAdmin` was first added ; why you do claim this has changed since the commit you cited?

**Comment by garyrussell** [comment]
I agree we can suppress if for a `TopicExistsException` - I am just curious about why you think it's new.
