### ISSUE TITLE
How i can configure many partitions @TopicPartition#partitions over property place holder?

### ISSUE THREAD

**Issue by dateslya** [spring-projects/spring-kafka#95]

**Comment by garyrussell** [comment]
You can put a PPH in each...

    @TopicPartition(topic = "annotated6", partitions = { "${foo}", "${bar}" })

However, if it's a comma-delimited list, I expected this would work...

    partitions = { "#{T(org.springframework.util.StringUtils).commaDelimitedListToStringArray('${foo}')}" }),

...but it doesn't - due to another bug. Fixing now...

**Comment by garyrussell** [comment]
@dateslya - thanks for finding these issues, we are expecting to put out the release candidate shortly.

**Comment by garyrussell** [comment]
Actually this works too...

    partitions = "#{'${foo:0,1}'.split(',')}"

...and is less typing.

But it still needs the fix in #96 though.

**Comment by artembilan** [comment]
Will fix to that code during merge! :smile:
