### ISSUE TITLE
producer transactions hanging on commitTransaction / abortTransaction if broker fails

### ISSUE THREAD

**Issue by iwastoldtheredbelunch83** [spring-projects/spring-kafka#952]
Running on Spring Boot Starter 2.1.1.Release I have observed that when broker fails, issue with transaction producer hanging still persists

Within TransactionalRequestResult.class lines 36-42

```java
while(!completed) {
      try {
        this.latch.await();
        completed = true;
      } catch (InterruptedException var3) {
      }
    }
```

this.latch.await() never returns

Suggest (1) calling latch.await() with timeout parameter or (2) allow for easier overriding of method by developers to allow them to call await() with a timeout 

**Affects Version(s):** \<Spring for Apache Kafka version 2.2.2.RELEASE>

**Comment by garyrussell** [comment]
This repo is for spring-kafka (the Spring for Apache Kafka).

That code is in the `kafka-clients` library; I suggest you [raise your issue there](https://github.com/apache/kafka).

**Comment by garyrussell** [comment]
Actually, that repo is a mirror; they use [JIRA](https://issues.apache.org/jira/browse/KAFKA) for issues.

**Comment by garyrussell** [comment]
Actually, that repo is a mirror; they use [JIRA](https://issues.apache.org/jira/browse/KAFKA) for issues.

Feel free to add a link to your issue here.

**Comment by iwastoldtheredbelunch83** [comment]
Thank you!
