### ISSUE TITLE
Provide configurer for StreamsBuilderFactoryBean

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-kafka#981]
First of all, thanks for this great project. I really like it. 
I dived into configuration problem.

At this time I don't see an easy way how to set additional properties for `StreamsBuilderFactoryBean`. `uncaughtExceptionHandler`  or `stateListener`. 
I can remove `@EnableKafkaStreams` to create custom `StreamsBuilderFactoryBean` instance (I cannot/I don't want to override beans since it's not recommended for Spring Core > 2.1) but I don't think it's a proper way to do it. I want to use inner code of `StreamsBuilderFactoryBean` initialization and also possible new bundled features of `@EnableKafkaStreams` in the future. 
According to my experience the correct way to handle it is some "StreamsBuilderFactoryConfigurer" 
(similar to well known `WebSecurityConfigurerAdapter`) where I can update FactoryBean before any StreamsBuilder is being instantiated. 
There is also 
`KafkaStreamsFactoryBeanConfigurer` in `org.springframework.boot.autoconfigure.kafka.KafkaStreamsAnnotationDrivenConfiguration` but it's not reusable for users...

I hope I described problem properly, let me know if there is something unclear.

**Comment by garyrussell** [comment]
We can certainly do that (and will) but I think we will defer it to 2.3 because there is a simple workaround you can use today...

```java
@Bean
public static BeanPostProcessor bpp() {
	return new BeanPostProcessor() {

		@Override
		public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
			if (bean instanceof StreamsBuilderFactoryBean) {
				StreamsBuilderFactoryBean fb = (StreamsBuilderFactoryBean) bean;
				fb.setStateListener((newState, oldState) -> {
					System.out.println("State transition from " + oldState + " to " + newState);
				});
			}
			return bean;
		}

	};
}
```

**Comment by Vity01** [comment]
Thank you.

**Comment by Vity01** [comment]
Thank you! Excellent work!
