### ISSUE TITLE
How can I know when no records were consumed by Consumer.poll()?

### ISSUE THREAD

**Issue by YoannBuch** [spring-projects/spring-kafka#99]
Currently, when `Consumer.poll()` times out and no records were consumed, I have no way to know that.

See: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L394

The `MessageListener.onMessage()` is called for each record consumed. What I would like is to also be notified when no records were consumed, like `MessageListener.onNoRecordsConsumed()`.

Why do I want that? My use case is a follows: if `Consumer.poll()` times out, it means that whatever was in the topic was consumed (the topic has a finite number of records), therefore I want to stop the consumer.

**Comment by garyrussell** [comment]
We could do something similar to [what we recently did with RabbitMQ](http://docs.spring.io/spring-amqp/docs/1.6.0.BUILD-SNAPSHOT/reference/html/_reference.html#idle-containers). i.e. publish an `ApplicationEvent` when the container has been idle for some configurable time.

**Comment by YoannBuch** [comment]
Sounds like a really good solution!
